# -*- coding: utf-8 -*-
"""gita_data16.py — Chapter 16 (Daivāsura-Sampad-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH16_THEMES = [
    ("Divine and demoniac: freedom or bondage",
     "The divine qualities are set against hypocrisy, pride and anger. One nature frees, the other binds; Kṛṣṇa reassures Arjuna that he is born to the divine.",
     [("Fearlessness and purity", "Fearlessness, purity of heart, steadfastness in knowledge and yoga, charity, self-control, sacrifice, study of scripture, austerity and uprightness,", "16.01", "16.01"),
      ("Non-violence and truth", "— non-violence, truth, freedom from anger, renunciation, peace, absence of slander, compassion, non-covetousness, gentleness, modesty and steadiness —", "16.02", "16.02"),
      ("Vigour and forgiveness", "— vigour, forgiveness, fortitude, purity, freedom from malice and from pride — these belong to one born to the divine destiny, O Bhārata.", "16.03", "16.03"),
      ("The six marks", "Hypocrisy, arrogance, pride, anger, harshness and ignorance — these belong to one born to the demoniac destiny, O Pārtha.", "16.04", "16.04"),
      ("Liberation and bondage", "The divine endowment leads to liberation, the demoniac to bondage — grieve not, O Pāṇḍava, for you are born to the divine destiny.", "16.05", "16.05")]),
    ("A false view becomes destructive conduct",
     "The demoniac reject truth, purity, a foundation and a Lord. Insatiable desire and false conviction turn that worldview into harmful deeds.",
     [("The two creations", "There are two creations of beings in this world — the divine and the demoniac; the divine has been described at length — now hear of the demoniac, O Pārtha.", "16.06", "16.06"),
      ("Without truth or purity", "The demoniac do not know right action or renunciation; there is no purity, no conduct, no truth in them.", "16.07", "16.07"),
      ("The godless world-view", "They say the world is unreal, without foundation, without a Lord — produced by mutual union, born of lust — what else?", "16.08", "16.08"),
      ("The ruined souls", "Holding this view, these ruined souls of little understanding act cruelly against the welfare of the world.", "16.09", "16.09"),
      ("Insatiable desire, hypocrisy and pride", "Given to insatiable desire, full of hypocrisy, pride and arrogance, holding false views through delusion, they act with impure resolves.", "16.10", "16.10")]),
    ("Desire, boast and the net of delusion",
     "Boundless worry and unjust gain feed the boast of wealth, power and superiority. Entangled in desire and false self-praise, the deluded fall into misery.",
     [("Cares that end only in death", "Given to boundless cares ending only in death, intent on the enjoyment of desires, thinking 'this is all' —", "16.11", "16.11"),
      ("The fetters of hope", "— bound by hundreds of fetters of hope, given to desire and anger, they strive to amass wealth by unjust means for the gratification of lust.", "16.12", "16.12"),
      ("This I gained; more shall be mine", "'This I gained today; this wish I shall fulfil; this wealth is mine — and more shall be mine,' they think —", "16.13", "16.13"),
      ("I am the Lord", "'I have slain this enemy, and I will slay others too; I am the lord, I am the enjoyer, I am accomplished, powerful and happy,'", "16.14", "16.14"),
      ("Who else is like me", "'I am rich and well-born; who else is like me? I will sacrifice, I will give, I will rejoice' — thus deluded by ignorance.", "16.15", "16.15"),
      ("The net of delusion", "Bewildered by many thoughts, wrapped in the net of delusion, devoted to sensual pleasures, they fall into a foul hell.", "16.16", "16.16")]),
    ("Empty sacrifice and hatred deepen the fall",
     "Sacrifice becomes display without rule; ego turns to hatred of the Lord in oneself and others. Repeated demoniac births carry this conduct downward.",
     [("Sacrifice in name only", "Self-conceited, stubborn, filled with the pride of wealth, they perform sacrifices in name only, with hypocrisy, not according to the rule.", "16.17", "16.17"),
      ("The hatred of the Lord", "Filled with ego, power, pride, desire and anger, hating me in their own and in others' bodies, these malicious beings —", "16.18", "16.18"),
      ("Cast again and again", "— these cruel haters, the vilest of men, I cast again and again into demoniac wombs in the rounds of rebirth.", "16.19", "16.19"),
      ("The lowest state", "Entering a demoniac womb, deluded birth after birth, never reaching me, they sink to the lowest state, O son of Kuntī.", "16.20", "16.20")]),
    ("Close hell’s gates and let scripture guide action",
     "Abandon desire, anger and greed—the three gates of ruin. Do not follow impulse alone; scripture must guide what to do and what not to do.",
     [("The three gates", "Threefold is this gate of hell, the destroyer of the self: desire, anger and greed — therefore abandon these three.", "16.21", "16.21"),
      ("Freed from the gates", "Freed from these three gates of darkness, O son of Kuntī, a man works for his own good and attains the supreme goal.", "16.22", "16.22"),
      ("Casting scripture aside", "He who, casting aside the ordinance of scripture, acts by the impulse of desire — he attains neither perfection, nor happiness, nor the supreme goal.", "16.23", "16.23"),
      ("Let scripture be your guide", "Therefore let the scripture be your authority in determining what is to be done and not done; knowing what is ordained by the scripture, act here accordingly.", "16.24", "16.24")]),
]

CH16_TRANSLATIONS = {
1: ("The Blessed Lord said: Fearlessness, purity of heart, steadfastness in knowledge and yoga, charity, self-control, sacrifice, study of scripture, austerity and uprightness,",
    "Kṛṣṇa said: “Fearlessness, purity of heart, firmness in knowledge and meditation, charity, self-restraint, sacrifice, study, austerity, and honesty,”"),
2: ("— non-violence, truth, freedom from anger, renunciation, peace, absence of slander, compassion, non-covetousness, gentleness, modesty and steadiness —",
    "“— harmlessness, truth, freedom from anger, letting go, calm, no backbiting, compassion, no greed, gentleness, humility, and firmness —”"),
3: ("— vigour, forgiveness, fortitude, purity, freedom from malice and from pride — these belong to one born to the divine destiny, O Bhārata.",
    "“— energy, patience, resolve, purity, and freedom from spite and vanity — these are the marks of one born to the divine nature.”"),
4: ("Hypocrisy, arrogance, pride, anger, harshness and ignorance — these belong to one born to the demoniac destiny, O Pārtha.",
    "“Hypocrisy, haughtiness, vanity, anger, rudeness, and ignorance — these mark the demonic nature.”"),
5: ("The divine endowment leads to liberation, the demoniac to bondage — grieve not, O Pāṇḍava, for you are born to the divine destiny.",
    "“The divine nature frees you; the demonic binds you. Do not grieve, Arjuna — you are born with the divine nature.”"),
6: ("There are two creations of beings in this world — the divine and the demoniac; the divine has been described at length — now hear of the demoniac, O Pārtha.",
    "“Two kinds of beings exist in this world — divine and demonic. I have described the divine; now hear of the demonic.”"),
7: ("The demoniac do not know right action or renunciation; there is no purity, no conduct, no truth in them.",
    "“The demonic do not know what should be done or renounced — they have no purity, no good conduct, no truth.”"),
8: ("They say the world is unreal, without foundation, without a Lord — produced by mutual union, born of lust — what else?",
    "“They claim the world is false, without ground, without God — arising by chance from desire.”"),
9: ("Holding this view, these ruined souls of little understanding perform cruel deeds, enemies of the world, for its destruction.",
    "“With this view, the lost, dull-witted souls do brutal things — enemies of the world, bent on ruining it.”"),
10: ("Given to insatiable desire, full of hypocrisy, pride and arrogance, holding false views through delusion, they act with impure resolves.",
    "“Slaves of never-satisfied craving, puffed with vanity and arrogance, they cling to wrong ideas and act with impure intentions.”"),
11: ("Given to boundless cares ending only in death, intent on the enjoyment of desires, thinking 'this is all' —",
    "“Consumed by endless worries that end only at death, living for pleasure, they think, 'this is all there is' —”"),
12: ("— bound by hundreds of fetters of hope, given to desire and anger, they strive to amass wealth by unjust means for the gratification of lust.",
    "“— tied by a hundred ropes of hope, devoted to desire and anger, they pile up wealth by wrongful means for their pleasures.”"),
13: ("'This I gained today; this wish I shall fulfil; this wealth is mine — and more shall be mine,' they think —",
    "‘I got this today; I will get that desire tomorrow; this is mine, and more will be mine,’ they boast —"),
14: ("'I have slain this enemy, and I will slay others too; I am the lord, I am the enjoyer, I am accomplished, powerful and happy,'",
    "‘I have killed that foe, and I will kill the rest; I am the master, the enjoyer, successful, mighty, and happy,’"),
15: ("'I am rich and well-born; who else is like me? I will sacrifice, I will give, I will rejoice' — thus deluded by ignorance.",
    "“‘I am wealthy and noble; who can equal me? I will offer, give, and enjoy’ — so the ignorant delude themselves.”"),
16: ("Bewildered by many thoughts, wrapped in the net of delusion, devoted to sensual pleasures, they fall into a foul hell.",
    "“Torn by countless thoughts, caught in the web of delusion, addicted to pleasure — they plunge into a foul hell.”"),
17: ("Self-conceited, stubborn, filled with the pride of wealth, they perform sacrifices in name only, with hypocrisy, not according to the rule.",
    "“Self-important and obstinate, drunk with the pride of riches, they offer sacrifices only in show — hypocritical, not as scripture bids.”"),
18: ("Filled with ego, power, pride, desire and anger, hating me in their own and in others' bodies, these malicious beings —",
    "“Full of ego, might, arrogance, lust, and rage, they despise me dwelling in their own and others' hearts —”"),
19: ("— these cruel haters, the vilest of men, I cast again and again into demoniac wombs in the rounds of rebirth.",
    "“— these cruel, hateful, lowest of men I hurl into demonic wombs, again and again, through the cycles of rebirth.”"),
20: ("Entering a demoniac womb, deluded birth after birth, never reaching me, they sink to the lowest state, O son of Kuntī.",
    "“Born into demonic wombs, deluded life after life, never attaining me, they fall to the lowest state.”"),
21: ("Threefold is this gate of hell, the destroyer of the self: desire, anger and greed — therefore abandon these three.",
    "“Three doors lead to hell and ruin the soul: lust, anger, and greed. Give up all three.”"),
22: ("Freed from these three gates of darkness, O son of Kuntī, a man works for his own good and attains the supreme goal.",
    "“One who escapes these three dark gates, Arjuna, works for his own welfare and reaches the highest goal.”"),
23: ("He who, casting aside the ordinance of scripture, acts by the impulse of desire — he attains neither perfection, nor happiness, nor the supreme goal.",
    "“One who ignores the scripture's rule and acts on whim gains neither perfection, nor joy, nor the supreme end.”"),
24: ("Therefore let the scripture be your authority in determining what is to be done and not done; knowing what is ordained by the scripture, act here accordingly.",
    "“So let scripture be your guide in deciding right and wrong; knowing its command, do your work here accordingly.”"),
}
