# -*- coding: utf-8 -*-
"""gita_data14.py — Chapter 14 (Guṇa-Traya-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH14_THEMES = [
    ("The Supreme Knowledge",
     "Kṛṣṇa declares the highest knowledge, knowing which the sages reach perfection — beyond rebirth and dissolution.",
     [("The Highest Knowledge", "I will declare again the supreme knowledge, the best of all — knowing which the sages have gone to the highest perfection.", "14.01", "14.02")]),
    ("The Womb of Creation",
     "The great Brahman is my womb; I place the seed and all beings arise; whatever forms appear in any womb have me as their seed-giving father.",
     [("My Womb", "My womb is the great Brahman; in it I place the seed — from that comes the birth of all beings, O Bhārata.", "14.03", "14.04")]),
    ("The Three Guṇas",
     "Sattva, rajas and tamas — born of prakṛti — bind the imperishable Self in the body; each binds in its own way.",
     [("The Three Qualities", "Sattva, rajas and tamas — the qualities born of prakṛti — bind the imperishable embodied one in the body, O mighty-armed one.", "14.05", "14.05"),
      ("Sattva Binds", "Of these, sattva, being pure, illumines and is free from disease; it binds by attachment to happiness and to knowledge.", "14.06", "14.06"),
      ("Rajas Binds", "Know rajas as of the nature of passion, born of thirst and attachment; it binds the embodied one by attachment to action.", "14.07", "14.07"),
      ("Tamas Binds", "Know tamas as born of ignorance, deluding all embodied beings; it binds by heedlessness, sloth and sleep.", "14.08", "14.08")]),
    ("The Guṇas in Conflict",
     "Sattva attaches to happiness, rajas to action, tamas covers knowledge; they prevail over one another in turn.",
     [("Each Binds to Its Object", "Sattva attaches to happiness, rajas to action, O Bhārata; tamas, covering knowledge, attaches to heedlessness.", "14.09", "14.09"),
      ("Their Mutual Rise", "Sattva rises by overpowering rajas and tamas; so rajas by overpowering sattva and tamas; and so tamas.", "14.10", "14.10")]),
    ("Signs of the Prevailing Guṇa",
     "When illumination shines through all the gates of the body, know sattva to have grown; greed and restlessness mark rajas; darkness and delusion mark tamas.",
     [("When Sattva Grows", "When light shines through all the gates of this body, then know that sattva has grown.", "14.11", "14.11"),
      ("When Rajas Grows", "Greed, activity, the beginning of works, restlessness and longing arise when rajas has grown.", "14.12", "14.12"),
      ("When Tamas Grows", "Darkness, inertia, heedlessness and delusion arise when tamas has grown, O joy of the Kurus.", "14.13", "14.13")]),
    ("Death Under Each Guṇa",
     "Dying in sattva, one reaches the pure worlds of the knowers of the highest; in rajas one is born among the action-bound; in tamas among the deluded.",
     [("Death in Sattva", "If the embodied one dies when sattva prevails, he reaches the pure worlds of the knowers of the highest.", "14.14", "14.14"),
      ("Death in Rajas and Tamas", "Dying in rajas, one is born among those attached to action; dying in tamas, one is born in the wombs of the deluded.", "14.15", "14.15")]),
    ("The Fruits of the Guṇas",
     "The fruit of good action is pure and sāttvic; the fruit of rajas is sorrow; the fruit of tamas is ignorance.",
     [("The Fruits Declared", "They say the fruit of good action is pure and sāttvic; the fruit of rajas is sorrow; the fruit of tamas is ignorance.", "14.16", "14.16")]),
    ("The Paths of the Guṇas",
     "From sattva arises knowledge, from rajas greed, from tamas delusion; the sāttvic rise, the rājasic stay in the middle, the tāmasic sink.",
     [("The Results", "From sattva arises knowledge; from rajas, greed; from tamas, delusion and ignorance.", "14.17", "14.17"),
      ("The Three Destinies", "Those established in sattva go upward; the rājasic stay in the middle; the tāmasic, sunk in the lowest qualities, go downward.", "14.18", "14.18")]),
    ("The Transcendence of the Guṇas",
     "When one sees no agent but the guṇas, and knows what is beyond them, he attains my being; transcending the three, he is freed and immortal.",
     [("Beyond the Guṇas", "When the seer sees no agent but the guṇas, and knows what is beyond them, he attains my being.", "14.19", "14.19"),
      ("Freed from the Guṇas", "Transcending these three guṇas born of the body, freed from birth, death, old age and sorrow, the embodied one tastes immortality.", "14.20", "14.20")]),
    ("Arjuna's Question",
     "Arjuna asks by what marks the one beyond the guṇas is known, and how he lives and transcends them.",
     [("The Marks of the Transcendent", "By what marks is he who has crossed these three guṇas known, O Lord? What is his conduct, and how does he transcend them?", "14.21", "14.21")]),
    ("The Answer: The Guṇātīta",
     "Kṛṣṇa describes the man beyond the guṇas: indifferent to light, activity and delusion, seated like an unconcerned witness, equal in all opposites.",
     [("Indifferent to the Guṇas", "He who neither hates illumination, activity and delusion when they arise, nor longs for them when they cease,", "14.22", "14.22"),
      ("Seated Like a Witness", "— seated as one indifferent, not shaken by the guṇas, thinking 'the guṇas act' and abiding unmoved —", "14.23", "14.23"),
      ("Equal in All Things", "— equal in pleasure and pain, self-abiding, to whom a clod, stone and gold are alike, equal to the pleasant and unpleasant, firm, equal in praise and blame —", "14.24", "14.25")]),
    ("The Way and the Goal",
     "He who serves me with unwavering devotion transcends the guṇas and becomes Brahman; for I am the support of Brahman, immortality and eternal dharma.",
     [("Devotion Transcends", "He who serves me with the unwavering yoga of devotion — transcending these guṇas, he becomes fit for Brahman.", "14.26", "14.26"),
      ("I Am the Support", "For I am the support of Brahman, of immortality and the imperishable, of eternal dharma and of absolute bliss.", "14.27", "14.27")]),
]

CH14_TRANSLATIONS = {
1: ("The Blessed Lord said: I will again declare the supreme knowledge, the best of all knowledges — knowing which all the sages have gone to the highest perfection.",
    "Kṛṣṇa said: “I will now tell you the highest knowledge, the best of all — knowing which, the sages reached the supreme perfection.”"),
2: ("Taking refuge in this knowledge, they attain unity with my being; they are not born at creation, nor are they troubled at dissolution.",
    "“Resting on this knowledge, they become one with me; they are not born at the dawn of creation, nor disturbed at its end.”"),
3: ("My womb is the great Brahman; in it I place the seed — from that comes the birth of all beings, O Bhārata.",
    "“The great Brahman is my womb; I place the seed in it, and from that all beings are born.”"),
4: ("Whatever forms arise in any womb, O son of Kuntī — the great Brahman is their womb, and I am the father who gives the seed.",
    "“Whatever forms appear in any womb — the great Brahman is that womb, and I am the father who sows the seed.”"),
5: ("Sattva, rajas and tamas — the qualities born of prakṛti — bind the imperishable embodied one in the body, O mighty-armed one.",
    "“Sattva, rajas, and tamas — the qualities of nature — bind the deathless Self in the body.”"),
6: ("Of these, sattva, being pure, illumines and is free from disease; it binds by attachment to happiness and to knowledge, O sinless one.",
    "“Sattva is pure, luminous, and healthy — yet it binds through attachment to joy and to knowledge.”"),
7: ("Know rajas as of the nature of passion, born of thirst and attachment; it binds the embodied one by attachment to action, O son of Kuntī.",
    "“Rajas is passion, born of craving and clinging; it binds the embodied soul through attachment to action.”"),
8: ("Know tamas as born of ignorance, deluding all embodied beings; it binds by heedlessness, sloth and sleep, O Bhārata.",
    "“Tamas is born of ignorance, deluding all beings; it binds through carelessness, laziness, and sleep.”"),
9: ("Sattva attaches to happiness, rajas to action, O Bhārata; tamas, covering knowledge, attaches to heedlessness.",
    "“Sattva ties you to joy, rajas to action, and tamas — veiling wisdom — to carelessness.”"),
10: ("Sattva arises by overpowering rajas and tamas; so rajas arises by overpowering sattva and tamas; and so tamas, overpowering both.",
    "“Sattva rises by dominating rajas and tamas; rajas rises by dominating sattva and tamas; and tamas likewise rises over both.”"),
11: ("When illumination shines through all the gates of this body, then know that sattva has grown.",
    "“When light streams through every gate of the body, know that sattva prevails.”"),
12: ("Greed, activity, the undertaking of works, restlessness and longing arise when rajas has grown, O bull of the Bhāratas.",
    "“Greed, busy-ness, starting projects, restlessness, and craving appear when rajas prevails.”"),
13: ("Darkness, inertia, heedlessness and delusion arise when tamas has grown, O joy of the Kurus.",
    "“Dullness, inactivity, carelessness, and confusion arise when tamas prevails.”"),
14: ("If the embodied one meets death when sattva prevails, he attains the pure worlds of the knowers of the highest.",
    "“Dying while sattva prevails, one reaches the pure realms of those who know the highest.”"),
15: ("Dying in rajas, one is born among those attached to action; dying in tamas, one is born in the wombs of the deluded.",
    "“Dying in rajas, one is reborn among the action-bound; dying in tamas, among the deluded.”"),
16: ("They say the fruit of good action is pure and sāttvic; the fruit of rajas is sorrow; the fruit of tamas is ignorance.",
    "“Good deeds bear the pure fruit of sattva; rajas bears sorrow; tamas bears ignorance.”"),
17: ("From sattva arises knowledge; from rajas, greed; from tamas arise heedlessness and delusion, and also ignorance.",
    "“Knowledge comes from sattva; greed from rajas; carelessness, confusion, and ignorance from tamas.”"),
18: ("Those established in sattva go upward; the rājasic stay in the middle; the tāmasic, sunk in the lowest qualities, go downward.",
    "“The sāttvic rise; the rājasic remain in the middle; the tāmasic, bound to the lowest qualities, sink down.”"),
19: ("When the seer perceives no agent other than the guṇas, and knows what is beyond them, he attains my being.",
    "“When the wise one sees that only the guṇas act, and knows what is beyond them, he reaches my own being.”"),
20: ("Transcending these three guṇas born of the body, freed from birth, death, old age and sorrow, the embodied one tastes immortality.",
    "“Going beyond the three qualities born of the body, freed from birth, death, age, and pain, the embodied soul tastes immortality.”"),
21: ("Arjuna said: By what marks is he who has transcended these three guṇas known, O Lord? What is his conduct, and how does he transcend them?",
    "Arjuna asks: “How can one tell who has gone beyond the three qualities, O Lord? How does he live, and how does he cross them?”"),
22: ("The Blessed Lord said: He who neither hates illumination, activity and delusion when they arise, nor longs for them when they cease, O Pāṇḍava,",
    "Kṛṣṇa said: “One who neither resents light, activity, and delusion when they appear, nor yearns for them when they fade,”"),
23: ("— seated as one indifferent, unshaken by the guṇas, thinking 'the guṇas act' and abiding unmoved —",
    "“— seated like an unconcerned onlooker, unshaken by the qualities, thinking ‘the qualities act,’ and standing firm —”"),
24: ("— equal in pleasure and pain, self-abiding, to whom a clod, stone and gold are alike, equal to the pleasant and unpleasant, firm, equal in praise and blame —",
    "“— equal in joy and sorrow, content in himself, seeing mud, stone, and gold alike, unmoved by praise or blame —”"),
25: ("— equal in honour and dishonour, equal to friend and foe, renouncing all undertakings — he is said to have transcended the guṇas.",
    "“— equal in honour and disgrace, friend and foe, giving up all selfish undertakings — such a one is beyond the qualities.”"),
26: ("He who serves me with the unwavering yoga of devotion — transcending these guṇas, he becomes fit for Brahman.",
    "“Whoever serves me with steadfast devotion — crossing these qualities — becomes worthy of Brahman.”"),
27: ("For I am the support of Brahman, of immortality and the imperishable, of eternal dharma and of absolute bliss.",
    "“For I am the ground of Brahman, of immortality and the eternal — of everlasting dharma and of perfect bliss.”"),
}
