# -*- coding: utf-8 -*-
"""gita_data6.py — Chapter 6 (Dhyāna Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH6_THEMES = [
    ("The true sannyāsin renounces the fruit",
     "Renunciation is not the abandoning of fire and rites but of the fruit of action; no one becomes a yogi without giving up selfish intention.",
     [("Not he who lights no fire", "He who does his duty without depending on the fruit is the sannyāsin and the yogi — not he who lights no fire and does no rites.", "6.01", "6.01"),
      ("Renunciation is Yoga", "Know that what they call renunciation is yoga; no one becomes a yogi who has not renounced selfish intention.", "6.02", "6.02"),
      ("Action for the ascending, stillness for the ascended", "For the sage who wishes to ascend to yoga, action is the means; for one who has ascended, serenity is the means.", "6.03", "6.03"),
      ("Clinging to nothing, he has risen in yoga", "When he clings neither to sense-objects nor to actions, having renounced all intention, then he is said to have ascended to yoga.", "6.04", "6.04")]),
    ("Lift the Self by the Self",
     "The Self is the friend of the self and also its enemy; for the conquered self, it is the best of friends — for the unconquered, hostile.",
     [("The Self is the friend and the enemy of the Self", "Let a man lift himself by his own Self, and not degrade himself; the Self alone is the friend of the self, and the Self alone its enemy. For him who has conquered the self by the Self, the Self is a friend — but for the unconquered, it remains hostile like an enemy.", "6.05", "6.05"),
      ("The Self is the enemy", "Master yourself and the Self befriends you; fail to master yourself and the Self turns hostile.", "6.06", "6.06"),
      ("The self-conquered is at peace", "The self-conquered and peaceful man is settled in the supreme Self, alike in cold and heat, pleasure and pain, honour and dishonour.", "6.07", "6.07"),
      ("A clod, a stone, and gold alike", "The yogi satisfied with knowledge and realization, unmoved, master of the senses, is said to be united — to whom a clod, a stone and gold are the same.", "6.08", "6.08"),
      ("Equal to friend and foe", "He excels who is equal-minded toward well-wishers, friends, enemies, the indifferent, the hateful, kinsmen, the righteous and the sinful alike.", "6.09", "6.09")]),
    ("The Seat of Meditation",
     "The practical instructions: a solitary place, a firm seat neither too high nor too low, the body held erect and still.",
     [("Alone, in solitude", "Let the yogi constantly discipline himself, remaining in solitude, alone, with mind and body controlled, free from desire and possessions.", "6.10", "6.10"),
      ("A clean place, neither too high nor too low", "In a clean place, having set a firm seat neither too high nor too low, covered with cloth, deerskin and kuśa grass — there, seated, making the mind one-pointed, with thought and senses controlled, let him practise yoga for self-purification.", "6.11", "6.11"),
      ("Calm the mind and senses", "Sitting there, focus the mind, calm thought and senses, and practise yoga to purify yourself.", "6.12", "6.12"),
      ("Body, head and neck erect", "Holding body, head and neck erect and still, gazing at the tip of his own nose without looking around — serene, fearless, firm in the vow of celibacy, controlling the mind, let him sit intent on me.", "6.13", "6.13"),
      ("Calm and fearless", "Calm and fearless, chaste and self-controlled, thoughts on me alone — sit in meditation, devoted to me.", "6.14", "6.14"),
      ("The yogi attains the peace that rests in me", "Thus ever disciplining himself, the yogi of subdued mind attains the peace abiding in me, which culminates in nirvāṇa.", "6.15", "6.15")]),
    ("Yoga is for one who lives in measure",
     "Yoga is not for the one who eats too much or too little, sleeps too much or too little — it is the middle way.",
     [("Not for him who eats too much", "Yoga is not for him who eats too much, nor for him who does not eat at all; not for him who sleeps too much, nor for him who keeps awake.", "6.16", "6.16"),
      ("Moderate in food, sleep and work", "For him who is moderate in food and recreation, moderate in effort in action, moderate in sleep and waking — yoga becomes the destroyer of sorrow.", "6.17", "6.17")]),
    ("The Lamp in a Windless Place",
     "When the disciplined mind rests in the Self alone, it is like a lamp in a windless place that does not flicker.",
     [("When the mind rests in the Self", "When the well-controlled mind rests in the Self alone, free from longing for all desires, then one is said to be united.", "6.18", "6.18"),
      ("As a lamp in a windless place", "As a lamp in a windless place does not flicker — that is the figure used of the yogi of controlled mind, practising union with the Self.", "6.19", "6.19"),
      ("Beholding the Self, content in the Self", "That in which the mind, restrained by the practice of yoga, comes to rest, and in which, beholding the Self by the self, one is content in the Self — that boundless joy, grasped by the intellect beyond the senses, established in which one never departs from the truth —", "6.20", "6.20"),
      ("A joy the senses cannot reach", "— when you taste that boundless joy known beyond the senses, and nothing can shake you from it —", "6.21", "6.21"),
      ("No gain is counted greater than this", "— having gained which one thinks no other gain greater, and established in which one is not shaken even by heavy sorrow.", "6.22", "6.22"),
      ("Practise with undiscouraged mind", "Know that severance from union with pain is called yoga; that yoga is to be practised with determination and an undespairing mind.", "6.23", "6.23")]),
    ("Bringing the Mind Home",
     "Abandon every desire born of intention; then, slowly and by degrees, let the mind come to rest — and wherever it wanders, bring it back.",
     [("Abandon all desires born of intention", "Abandoning without exception all desires born of selfish intention, restraining the whole group of senses on every side by the mind —", "6.24", "6.24"),
      ("Slowly, gradually, let him come to rest", "— little by little let him come to rest, with intellect held firm; fixing the mind on the Self, let him think of nothing at all.", "6.25", "6.25"),
      ("Wherever the mind wanders, bring it back", "From whatever cause the restless, unsteady mind wanders away, from that let him restrain it and bring it back under the control of the Self.", "6.26", "6.26")]),
    ("Seeing the Self in All",
     "Supreme bliss comes to the stainless yogi, who sees the Self in all beings and all beings in the Self — and so is never lost to me.",
     [("Supreme bliss comes to the stainless", "Supreme bliss comes to the yogi whose mind is at peace, whose passion is stilled, who is stainless and has become Brahman. Thus constantly disciplining himself, freed from stain, he easily attains the boundless joy of contact with Brahman.", "6.27", "6.27"),
      ("The purified reach bliss", "Practising this always, the purified yogi easily reaches the limitless joy of union with Brahman.", "6.28", "6.28"),
      ("The Self in all beings — And I am never lost to him", "Seeing the Self in all beings and all beings in the Self, he sees the same everywhere. He who sees me everywhere and sees everything in me — for him I am never lost, nor is he lost to me.", "6.29", "6.29"),
      ("I am never lost to him", "Whoever sees me in all and all in me — I never leave him, and he never leaves me.", "6.30", "6.30"),
      ("The supreme yogi", "Established in unity, the yogi who worships me abiding in all beings dwells in me, whatever his mode of life. He who, by the likeness of his own self, sees the same everywhere — in pleasure and in pain — is deemed the supreme yogi.", "6.31", "6.31"),
      ("He who feels all as his own", "One who feels others' joy and pain as his own, seeing all equally — he is the greatest yogi, Arjuna.", "6.32", "6.32")]),
    ("Arjuna says: the mind is restless as wind",
     "Arjuna objects that the mind is as hard to hold as the wind; Kṛṣṇa answers with practice and dispassion.",
     [("Arjuna: the mind is too restless for this", "This yoga of evenness you have declared — I do not see its steady continuance, because of restlessness.", "6.33", "6.33"),
      ("The mind is restless as the wind", "The mind is restless, turbulent, powerful and obstinate; to restrain it seems to me as hard as to restrain the wind.", "6.34", "6.34"),
      ("By practice and detachment", "Undoubtedly the mind is hard to curb and restless — but by practice and by dispassion it can be held.", "6.35", "6.35"),
      ("For the unrestrained, Yoga is hard", "Yoga is hard to attain for one whose self is unrestrained; but for the self-controlled, striving by right means, it can be won.", "6.36", "6.36")]),
    ("The Yogi Who Falls Away",
     "What becomes of one who strives but fails? He is not destroyed — no one who does good ever comes to a bad end.",
     [("Arjuna asks what befalls one who fails", "He who has faith but is not persevering, whose mind falls away from yoga and fails to reach perfection — what path does he take? Fallen from both, without support, does he not perish like a scattered cloud on the path to Brahman?", "6.37", "6.37"),
      ("Lost like a torn cloud", "Lost from both worlds — does he perish like a torn cloud, clinging to nothing, confused on the path to Brahman?", "6.38", "6.38"),
      ("No one who does good comes to grief", "You alone can dispel this doubt of mine completely; none but you can be found to remove it. Neither in this world nor the next is there destruction for him; no one who does good ever comes to a bad end.", "6.39", "6.39"),
      ("Never comes to grief", "Kṛṣṇa said: “Never, Arjuna — neither here nor after death — does such a one perish. No one who does good ever goes to evil.", "6.40", "6.40"),
      ("Born again in a pure house", "Having reached the worlds of the righteous and dwelt there many years, the fallen yogi is born in the house of the pure and prosperous.", "6.41", "6.41"),
      ("Or in a family of yogis", "Or he is born in a family of wise yogis — though such a birth is very hard to gain in this world.", "6.42", "6.42"),
      ("He regains the knowledge of his former birth", "There he regains the knowledge acquired in his former body, and strives again for perfection, O joy of the Kurus.", "6.43", "6.43")]),
    ("The greatest yogi abides in me",
     "Carried on by former practice, the yogi is purified over many births — and the greatest yogi of all is he who worships me with faith.",
     [("Carried onward by former practice", "By that former practice alone he is carried on, even against his will; even the seeker after yoga goes beyond the word of the Vedas.", "6.44", "6.44"),
      ("Perfected through many births", "The yogi who strives with effort, purified of sin and perfected through many births, then reaches the supreme goal.", "6.45", "6.45"),
      ("The yogi is greater than the ascetic", "The yogi is greater than the ascetic, greater even than the man of knowledge, greater than the ritualist — therefore become a yogi, O Arjuna.", "6.46", "6.46"),
      ("Dearest of all: He who worships me", "And of all yogis, he who worships me with faith, his inmost self absorbed in me — he is deemed by me the most devoted of all.", "6.47", "6.47")]),
]

CH6_TRANSLATIONS = {
1: ("The Blessed Lord said: He who performs his bounden action without depending on its fruit — he is both a renouncer and a yogi, not he who is without fire and without rites.",
    "Kṛṣṇa said: “One who does his duty without clinging to results is a true renouncer and yogi — not someone who merely abandons rituals.”"),
2: ("That which they call renunciation, know that to be yoga, O son of Pāṇḍu; for none becomes a yogi who has not renounced selfish intention.",
    "“What people call renunciation is the same as yoga — no one can be a yogi without giving up selfish planning.”"),
3: ("For the sage who wishes to ascend in yoga, action is said to be the means; for him who has ascended, quiescence is said to be the means.",
    "“To climb toward yoga, action is the way; once established, inner stillness becomes the way.”"),
4: ("When one is attached neither to sense-objects nor to actions, having abandoned all selfish intentions — then he is said to have ascended in yoga.",
    "“When you cling neither to pleasures nor to work, having dropped all selfish aims — you have truly risen in yoga.”"),
5: ("Let one raise the self by the Self and not degrade the self; for the Self alone is the friend of the self, and the Self alone is the enemy of the self.",
    "“Raise yourself by your own Self; never let it sink. The Self is your own best friend — or your own worst enemy.”"),
6: ("For him who has conquered the self by the Self, the Self is a friend; but for him who has not conquered the self, the Self abides as an enemy, hostile.",
    "“Master yourself and the Self befriends you; fail to master yourself and the Self turns hostile.”"),
7: ("The self-conquered, tranquil one is established in the Self — equal in cold and heat, pleasure and pain, honour and dishonour.",
    "“The self-mastered sage, calm and poised, stays equal through heat and cold, joy and pain, praise and blame.”"),
8: ("He who is satisfied with knowledge and realization, unmoved, with senses conquered, to whom a lump of earth, a stone and gold are alike — he is called a yoked one.",
    "“Content in wisdom, steady, senses mastered, seeing mud, stone, and gold as equal — such a one is truly joined to yoga.”"),
9: ("He who is the same toward well-wishers, friends, foes, the indifferent, neutrals, the hateful, kinsmen and the righteous — he excels.",
    "“Equal to friends and enemies, the neutral and the hostile, kin and strangers — such a one stands highest.”"),
10: ("Let the yogi constantly discipline himself, abiding in a solitary place, alone, with mind and self controlled, free from desire and possessiveness.",
    "“Practise yoga alone in a quiet place — mind and heart controlled, free from craving and clinging.”"),
11: ("Establishing in a pure spot a steady seat for himself, neither too high nor too low, covered with cloth, a deer-skin and kuśa grass,",
    "“In a clean place, set up a firm seat — not too high or low, spread with cloth, skin, and sacred grass —”"),
12: ("making the mind one-pointed, restraining the activities of the mind and the senses, seated on that seat, let him practise yoga for the purification of the self.",
    "“sitting there, focus the mind, calm thought and senses, and practise yoga to purify yourself.”"),
13: ("Holding body, head and neck steady and unmoving, gazing at the tip of his own nose, not looking about,",
    "“Keep the body, head, and neck straight and still; fix the gaze on the nose-tip, without glancing around —”"),
14: ("with a serene mind, fearless, firm in the vow of brahmacarya, the mind controlled, thoughts resting on me — let the yoked one sit, devoted to me.",
    "“calm and fearless, chaste and self-controlled, thoughts on me alone — sit in meditation, devoted to me.”"),
15: ("Thus disciplining himself always, the yogi of controlled mind attains the peace of nirvāṇa that abides in me.",
    "“Practising thus, the yogi with a stilled mind reaches the peace of liberation that rests in me.”"),
16: ("Verily yoga is not attained by him who eats too much nor by him who does not eat at all, nor by him who sleeps too much nor by him who keeps awake too much, O Arjuna.",
    "“Yoga is not for those who overeat or starve, oversleep or never sleep — moderation in everything, Arjuna.”"),
17: ("For him who is temperate in food and recreation, temperate in his efforts, temperate in sleep and waking, yoga becomes the destroyer of sorrow.",
    "“Balanced in food, rest, work, and sleep — for such a person yoga dissolves all suffering.”"),
18: ("When the well-trained mind rests in the Self alone, free from longing for all objects of desire — then one is said to be yoked.",
    "“When the trained mind settles in the Self, free from every craving — that is true establishment in yoga.”"),
19: ("As a lamp placed in a windless spot does not flicker — this simile is declared of a yogi of controlled mind, practising yoga of the Self.",
    "“Like a lamp in a windless place that never flickers — so is the yogi whose mind is stilled in the Self.”"),
20: ("That in which, by the practice of yoga, the mind comes to rest, and beholding the Self by the self, one is content in the Self alone —",
    "“When the practised mind grows still, and seeing the Self within, you delight in your own Self —”"),
21: ("— that which, being apprehended by the intellect beyond the senses, one knows as boundless joy, and established in which one never departs from the truth —",
    "“— when you taste that boundless joy known beyond the senses, and nothing can shake you from it —”"),
22: ("— having gained which one deems no other gain superior, in which one is not disturbed even by great sorrow — that state is known as yoga, the sundering of union with sorrow.",
    "“— a gain beyond which nothing matters, unshaken even by deep grief — know that as yoga, the end of all sorrow.”"),
23: ("That yoga, the disconnection of union with sorrow, should be practised with determination, with an undiscouraged mind.",
    "“Practise this yoga — which severs you from sorrow — with firm resolve and an untiring heart.”"),
24: ("Abandoning without exception all desires born of selfish intention, restraining the whole group of senses on every side by the mind alone —",
    "“Let go of all imagined desires; rein in every sense with the mind —”"),
25: ("— slowly, gradually, let him come to rest through the intellect held firm by resolve; and fixing the mind on the Self alone, let him think of nothing else.",
    "“— step by step, let the intellect, steady in resolve, bring the mind to rest in the Self — and think of nothing else.”"),
26: ("From whatever cause the wavering, unsteady mind wanders away, from that alone let him withdraw it and bring it under the control of the Self.",
    "“Wherever the restless mind strays, bring it back, again and again, under the Self's control.”"),
27: ("Supreme bliss verily comes to this yogi whose mind is peaceful, whose passion is stilled, who is become Brahman, free from stain.",
    "“Great bliss comes to the yogi whose mind is calm, passions cooled, who has become Brahman, spotless.”"),
28: ("Thus constantly disciplining the self, the yogi, freed from stain, easily attains the endless joy of union with Brahman.",
    "“Practising this always, the purified yogi easily reaches the limitless joy of union with Brahman.”"),
29: ("Seeing the Self in all beings and all beings in the Self, one who sees the same in everything — he attains the Supreme.",
    "“Seeing the Self in all and all in the Self, seeing the same everywhere — such a one reaches the highest.”"),
30: ("He who sees me everywhere and sees everything in me — for him I am not lost, and he is not lost to me.",
    "“Whoever sees me in all and all in me — I never leave him, and he never leaves me.”"),
31: ("Established in unity, the yogi who worships me abiding in all beings — abiding in that, he lives in me, whatever his way of life.",
    "“The yogi who sees me in all beings and worships me there — he lives in me, whatever he does.”"),
32: ("He who, through the likeness of the self, sees the same everywhere, in pleasure and in pain — he is deemed the supreme yogi, O Arjuna.",
    "“One who feels others' joy and pain as his own, seeing all equally — he is the greatest yogi, Arjuna.”"),
33: ("Arjuna said: This yoga of equanimity declared by you, O Madhusūdana — I see no firm foundation for it, because of restlessness.",
    "Arjuna asks: “This yoga of even-mindedness you describe — I don't see how it can last, since the mind is so restless.”"),
34: ("Verily the mind is restless, turbulent, strong and unyielding, O Kṛṣṇa; I think it is as hard to restrain as the wind.",
    "“The mind is wild, turbulent, stubborn, and strong — I think controlling it is as hard as catching the wind.”"),
35: ("The Blessed Lord said: Undoubtedly the mind is restless and hard to restrain, O mighty-armed one; but it is restrained, O son of Kuntī, by practice and by dispassion.",
    "Kṛṣṇa said: “Yes, the mind is restless and hard to tame — but practice and detachment can master it.”"),
36: ("Yoga is hard to attain, I think, for one whose self is unrestrained; but for the self-controlled one who strives by the proper means, it is attainable.",
    "“Without self-mastery, yoga is very hard; but one who is self-controlled and strives rightly will attain it.”"),
37: ("Arjuna said: He who, full of faith but unable to control himself, whose mind has fallen away from yoga — not attaining perfection in yoga — what end does he reach, O Kṛṣṇa?",
    "Arjuna asks: “What happens to someone who tries, with faith, but fails — whose mind falls from yoga before reaching perfection, Kṛṣṇa?”"),
38: ("Falling from both, does he not perish like a riven cloud, O mighty-armed one, without support, deluded on the path of Brahman?",
    "“Lost from both worlds — does he perish like a torn cloud, clinging to nothing, confused on the path to Brahman?”"),
39: ("This doubt of mine you should dispel wholly, O Kṛṣṇa; no other than you is found to destroy this doubt.",
    "“Please remove this doubt of mine completely, Kṛṣṇa — no one else can resolve it.”"),
40: ("The Blessed Lord said: O Pārtha, neither in this world nor in the next is there destruction for him; for none who does good, my son, goes to evil.",
    "Kṛṣṇa said: “Never, Arjuna — neither here nor after death — does such a one perish. No one who does good comes to a bad end.”"),
41: ("Having attained the worlds of the righteous and dwelt there for immemorial years, he who fell from yoga is born again in the house of the pure and prosperous.",
    "“He enjoys the realms of the virtuous for ages, then is reborn in a pure and fortunate family.”"),
42: ("Or he is born into a family of wise yogis; truly a birth like this is very hard to obtain in this world.",
    "“Or else he is born into a household of seasoned yogis — and that is the rarest birth of all.”"),
43: ("There he regains the understanding of his former body, O son of the Kurus, and from there he strives again for perfection.",
    "“There the wisdom of his past life returns, and from that point he presses on toward perfection.”"),
44: ("By that very former practice he is carried along, even in spite of himself; even the one who merely wishes to know yoga transcends the mere word of the Vedas.",
    "“His past practice carries him forward even against his will — even wanting to know yoga takes you beyond mere scripture.”"),
45: ("But the yogi who strives with effort, purified of sin, perfected gradually through many births, then reaches the highest state.",
    "“But the yogi who strives sincerely, purified of sin, perfected over many lives — he reaches the supreme goal.”"),
46: ("The yogi is greater than the ascetic, deemed greater than the man of knowledge, and greater than the man of rites; therefore be a yogi, O Arjuna.",
    "“The yogi surpasses the ascetic, the scholar, and the ritualist — so become a yogi, Arjuna.”"),
47: ("And among all yogis, he who, full of faith, worships me with his inmost self established in me — him I deem the most yoked, in my view.",
    "“And among all yogis, the one who worships me with deep faith, his whole being fixed on me — he is the greatest of all, in my eyes.”"),
}
