# -*- coding: utf-8 -*-
"""gita_data15.py — Chapter 15 (Puruṣottama Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH15_THEMES = [
    ("The world is an upside-down tree",
     "Kṛṣṇa describes the imperishable aśvattha — the world-tree with its root above and branches below — which must be cut with the axe of detachment.",
     [("The Aśvattha tree", "They speak of the imperishable aśvattha with its root above and branches below; the Vedas are its leaves — he who knows it knows the Vedas.", "15.01", "15.01"),
      ("Its branches below", "Its branches spread below and above, nourished by the guṇas, with sense-objects as shoots; its roots bind one to action in the world of men.", "15.02", "15.02"),
      ("Cut this rooted tree with detachment", "Its true form is not seen thus, nor its end, beginning or support; cut this firmly-rooted aśvattha with the strong axe of detachment,", "15.03", "15.03")]),
    ("The Path to the Supreme Abode",
     "Then seek the goal from which none return; freed from pride and delusion, having conquered the guṇas, the wise reach that imperishable abode.",
     [("Seek the supreme goal", "Then seek that state from which, having gone, none returns — I take refuge in the primal Person from whom flows the ancient course.", "15.04", "15.04"),
      ("Free of pride and delusion, they reach it", "Free from pride and delusion, having conquered the fault of attachment, ever in the Self, desires turned away — freed from the pairs, they reach that imperishable goal.", "15.05", "15.05")]),
    ("The Abode of the Lord",
     "That supreme abode of mine, which neither sun, moon nor fire illumines, and from which none return — is the highest.",
     [("The supreme abode", "That abode of mine neither the sun nor the moon nor fire illumines; having gone there, none return — that is my supreme abode.", "15.06", "15.06")]),
    ("The soul in the body is a part of me",
     "An eternal part of me, the soul in the world of life draws the senses and mind, which abide in prakṛti; it wanders from body to body as wind carries fragrance.",
     [("The eternal portion", "An eternal portion of myself, become a living soul in the world of life, draws around itself the senses, of which the mind is the sixth, resting in prakṛti.", "15.07", "15.07"),
      ("The wandering soul", "When the lord (of the body) takes up a body, and when he departs from it, he goes carrying these with him, as the wind carries fragrance from its seat.", "15.08", "15.08"),
      ("Enjoying through the senses", "Presiding over hearing, touch, sight, taste and smell, and the mind, he enjoys the sense-objects.", "15.09", "15.09")]),
    ("The Seer and the Blind",
     "The deluded do not see the soul as it departs, dwells or enjoys; but those with the eye of knowledge see.",
     [("Who sees and who not", "The deluded do not see him as he departs, dwells or enjoys, or as he is joined with the guṇas; but those with the eye of knowledge see.", "15.10", "15.10")]),
    ("The striving see, the undisciplined do not",
     "Striving yogis see the Self dwelling within; but the undisciplined, however they strive, do not see it.",
     [("The striving yogis", "The striving yogis see him established in the Self; but the undisciplined, though striving, do not see him, lacking understanding.", "15.11", "15.11")]),
    ("The Light of the World",
     "The light of the sun, moon and fire is mine; I enter the earth and sustain all beings; I am the fire of digestion in all bodies.",
     [("I am the light", "The light in the sun, which illumines the whole world, and that in the moon and in fire — know that light as mine.", "15.12", "15.12"),
      ("I sustain all", "Entering the earth I sustain all beings with my energy; becoming the sap-laden moon I nourish all herbs.", "15.13", "15.13"),
      ("The fire of digestion", "Becoming the fire of digestion in the bodies of living beings, joined with the in-breath and out-breath, I cook the four kinds of food.", "15.14", "15.14")]),
    ("I Am in Every Heart",
     "I dwell in the heart of all; from me come memory, knowledge and their loss; I am the knowable of all the Vedas and their author.",
     [("In the heart of all", "I am seated in the heart of all; from me come memory, knowledge and their removal; by all the Vedas I alone am to be known — I am the author of Vedānta and the knower of the Vedas.", "15.15", "15.15")]),
    ("Two persons: perishable and imperishable",
     "There are two persons in the world — the perishable and the imperishable; the perishable is all beings, the imperishable is the unchanging.",
     [("The perishable and the imperishable", "There are two persons in this world: the perishable and the imperishable. The perishable is all beings; the unchanging is called the imperishable.", "15.16", "15.16"),
      ("The supreme person", "But there is another, the supreme Person, called the supreme Self — the eternal Lord who, entering the three worlds, sustains them.", "15.17", "15.17")]),
    ("I am the Puruṣottama, beyond both",
     "Because I transcend the perishable and am higher than the imperishable, I am renowned in the world and in the Veda as Puruṣottama — the highest Person.",
     [("Why I am Puruṣottama", "Since I transcend the perishable and am higher than the imperishable, I am known in the world and in the Veda as the highest Person.", "15.18", "15.18"),
      ("The knower of the highest", "He who, undeluded, knows me as the highest Person — knowing all, he worships me with all his being, O Bhārata.", "15.19", "15.19")]),
    ("Knowing this, a man becomes wise",
     "Thus this most secret scripture has been declared; he who understands it becomes wise and accomplished, O Bhārata.",
     [("The secret teaching", "Thus this most secret teaching has been declared by me, O sinless one; knowing this, one becomes wise and has done all that is to be done, O Bhārata.", "15.20", "15.20")]),
]

CH15_TRANSLATIONS = {
1: ("The Blessed Lord said: They speak of the imperishable aśvattha with its root above and branches below; the Vedas are its leaves — he who knows it is a knower of the Vedas.",
    "Kṛṣṇa said: “They call it the eternal sacred fig — the world-tree with its root above, branches below. The Vedas are its leaves; one who knows it knows the Vedas.”"),
2: ("Its branches spread above and below, nourished by the guṇas, with sense-objects as their shoots; and below its roots stretch down, binding to action in the world of men.",
    "“Its branches spread everywhere, fed by the three qualities, with the objects of the senses as sprouts; its roots, reaching below, bind one to action in the human world.”"),
3: ("Its true form is not perceived here, nor its end, nor its beginning, nor its support; having cut this firmly-rooted aśvattha with the strong axe of detachment,",
    "“Its true nature cannot be seen here, nor its end, beginning, or base. Cut down this deep-rooted fig tree with the strong axe of dispassion,”"),
4: ("— then that state must be sought, going to which none returns; I take refuge in that primal Person from whom flows the ancient course.",
    "“— and then seek that goal from which no one returns. I surrender to that primeval Person, the source of the eternal stream.”"),
5: ("Free from pride and delusion, having conquered the fault of attachment, ever established in the Self, desires turned away — freed from the pairs known as pleasure and pain, the undeluded reach that imperishable goal.",
    "“Freed from pride and confusion, conquering the taint of clinging, ever dwelling in the Self, desireless — beyond joy and sorrow — the wise reach that eternal abode.”"),
6: ("Neither the sun nor the moon nor fire illumines that abode of mine; having gone there, none returns — that is my supreme abode.",
    "“My highest home is not lit by sun, moon, or fire; once reached, no one ever returns — that is my supreme abode.”"),
7: ("An eternal portion of myself, become a living soul in the world of life, draws around itself the senses, of which the mind is the sixth, which abide in prakṛti.",
    "“An eternal spark of myself becomes the living soul in this world; it draws to itself the five senses and the mind, which rest in nature.”"),
8: ("When the lord of the body takes up a body, and when he departs from it, he goes taking these with him, as the wind carries fragrance from its seat.",
    "“When this lord of the body enters a body, and when he leaves it, he carries the senses along — as the wind carries a scent from its source.”"),
9: ("Presiding over hearing, touch, sight, taste and smell, and the mind, he enjoys the sense-objects.",
    "“Using hearing, touch, sight, taste, smell, and the mind, he delights in the objects of the senses.”"),
10: ("The deluded do not see him as he departs, dwells, or enjoys, or as he is joined with the guṇas; but those with the eye of knowledge see him.",
    "“Fools do not see him leaving, abiding, or enjoying, bound by the qualities; but those with the eye of wisdom see him.”"),
11: ("The striving yogis see him established in the Self; but the undisciplined, though striving, do not see him, lacking true understanding.",
    "“Striving yogis see him dwelling within; but those not yet purified — however hard they try — cannot see him.”"),
12: ("The light in the sun, which illumines the whole world, and that in the moon and in fire — know that light as mine.",
    "“The light of the sun that lights the whole world, the light of the moon and of fire — know it all as mine.”"),
13: ("Entering the earth I sustain all beings with my energy; becoming the sap-laden moon I nourish all herbs.",
    "“I enter the earth and hold up all beings with my power; becoming the nourishing moon, I feed all plants.”"),
14: ("Becoming the fire of digestion in the bodies of living beings, joined with the in-breath and out-breath, I cook the four kinds of food.",
    "“I become the digestive fire in all living bodies; united with the breath, I digest the four kinds of food.”"),
15: ("I am seated in the heart of all; from me come memory, knowledge and their removal; by all the Vedas I alone am to be known — I am the author of Vedānta and the knower of the Vedas.",
    "“I dwell in every heart; from me come memory, wisdom, and also their loss. I am what all the Vedas teach — their author and their knower.”"),
16: ("There are two persons in this world: the perishable and the imperishable. The perishable is all beings; the unchanging is called the imperishable.",
    "“Two persons exist in the world: the perishable and the imperishable. All beings are the perishable; the unchanging Self is the imperishable.”"),
17: ("But there is another, the supreme Person, called the supreme Self — the eternal Lord who, entering the three worlds, sustains them.",
    "“Yet beyond both is the highest Person, called the supreme Self — the changeless Lord who enters the three worlds and supports them.”"),
18: ("Since I transcend the perishable and am higher than the imperishable, I am known in the world and in the Veda as the highest Person.",
    "“Because I am beyond the perishable and above the imperishable, I am celebrated in the world and in the Veda as Puruṣottama — the highest Person.”"),
19: ("He who, undeluded, knows me as the highest Person — knowing all, he worships me with all his being, O Bhārata.",
    "“One who, free of delusion, knows me as the Supreme Person — knowing everything, he worships me with his whole heart, Arjuna.”"),
20: ("Thus this most secret teaching has been declared by me, O sinless one; understanding this, one becomes wise and has accomplished all, O Bhārata.",
    "“So I have taught you this most secret scripture, blameless one. One who grasps it becomes wise and fulfils all his purpose, Arjuna.”"),
}
