# -*- coding: utf-8 -*-
"""gita_data.py — Bhagavad Gita app data: chapter metadata, theme/subtheme structure,
and translations (literal + paraphrase) for Chapter 1 (pilot)."""

# All 18 chapters: (num, name, devanagari, verse_count, one-line theme)
CHAPTERS = [
    (1,  "Arjuna Viṣāda Yoga",        "अर्जुनविषादयोग",        47, "The warrior's despair on the battlefield"),
    (2,  "Sāṅkhya Yoga",              "साङ्ख्ययोग",             72, "The immortal Self and the way of action without attachment"),
    (3,  "Karma Yoga",                "कर्मयोग",               43, "The discipline of selfless action"),
    (4,  "Jñāna-Karma-Sannyāsa Yoga", "ज्ञानकर्मसंन्यासयोग",    42, "Knowledge, action, and the renunciation of their fruits"),
    (5,  "Karma-Sannyāsa Yoga",       "कर्मसंन्यासयोग",         29, "Renunciation and the true yogi of action"),
    (6,  "Dhyāna Yoga",               "आत्मसंयमयोग / ध्यानयोग", 47, "Meditation and the mastery of the mind"),
    (7,  "Jñāna-Vijñāna Yoga",        "ज्ञानविज्ञानयोग",        30, "Knowledge of the divine and the ways to reach it"),
    (8,  "Akṣara-Brahma Yoga",        "अक्षरब्रह्मयोग",         28, "The imperishable Brahman and the path of departure"),
    (9,  "Rāja-Vidyā-Rāja-Guhya Yoga","राजविद्याराजगुह्ययोग",    34, "The royal secret: devotion and the divine majesty"),
    (10, "Vibhūti Yoga",              "विभूतियोग",             42, "The glories and powers of the divine"),
    (11, "Viśvarūpa-Darśana Yoga",    "विश्वरूपदर्शनयोग",       55, "The vision of the cosmic form"),
    (12, "Bhakti Yoga",               "भक्तियोग",              20, "The path of devotion"),
    (13, "Kṣetra-Kṣetrajña-Vibhāga Yoga", "क्षेत्रक्षेत्रज्ञविभागयोग", 34, "The field, the knower of the field, and discernment"),
    (14, "Guṇa-Traya-Vibhāga Yoga",   "गुणत्रयविभागयोग",       27, "The three guṇas and the one who transcends them"),
    (15, "Puruṣottama Yoga",          "पुरुषोत्तमयोग",          20, "The supreme Person, the root of all"),
    (16, "Daivāsura-Sampad-Vibhāga Yoga", "दैवासुरसम्पद्विभागयोग", 24, "The divine and demonic natures"),
    (17, "Śraddhā-Traya-Vibhāga Yoga", "श्रद्धात्रयविभागयोग",    28, "The three kinds of faith"),
    (18, "Mokṣa-Sannyāsa Yoga",       "मोक्षसंन्यासयोग",        78, "Liberation through renunciation — the Gita's conclusion"),
]

# Chapter 1 theme/subtheme structure: (theme_title, theme_desc, [(part_title, part_desc, start, end), ...])
CH1_THEMES = [
    ("The Blind King's Question",
     "Dhṛtarāṣṭra asks what happened on the field of dharma; Sañjaya begins with Duryodhana going to his teacher.",
     [("What Did They Do?", "Dhṛtarāṣṭra asks what his sons and the Pāṇḍavas did on the field of dharma.", "1.01", "1.01"),
      ("Duryodhana Approaches Droṇa", "Seeing the Pāṇḍava array, Duryodhana goes to his teacher and points out their host.", "1.02", "1.03")]),
    ("The Two Armies",
     "The catalogue of warriors on both sides, and Duryodhana's order to guard the grandsire.",
     [("The Pāṇḍava Heroes", "Yuyudhāna, Virāṭa, Drupada and the other great archers on Arjuna's side.", "1.04", "1.06"),
      ("The Kaurava Captains", "Duryodhana names Bhīṣma, Karṇa, Kṛpa and the leaders of his own army.", "1.07", "1.09"),
      ("Guard Bhīṣma", "Weighing the two forces, Duryodhana orders every division to protect the grandsire.", "1.10", "1.11")]),
    ("The Conches Sound",
     "The armies raise their war-cries; the conches of both sides shatter the silence.",
     [("Bhīṣma's Blast", "The grandsire's lion-roar and the sudden clamour of drums and horns.", "1.12", "1.13"),
      ("Kṛṣṇa and the Pāṇḍavas", "Pāñcajanya, Devadatta and Pauṇḍra — the divine conches of Kṛṣṇa, Arjuna and Bhīma.", "1.14", "1.16"),
      ("The Uproar", "The remaining heroes sound their conches; the din rends the hearts of Dhṛtarāṣṭra's sons.", "1.17", "1.19")]),
    ("Arjuna Surveys the Field",
     "Arjuna asks to be placed between the armies — and sees his own kin drawn up to die.",
     [("Place My Chariot Between", "Seeing the Dhārtarāṣṭras arrayed, Arjuna raises his bow and asks Kṛṣṇa to halt between the armies.", "1.20", "1.21"),
      ("That I May See Them", "His reason: to look on those eager to fight, gathered to please the evil-minded son of Dhṛtarāṣṭra.", "1.22", "1.23"),
      ("Behold These Kurus", "Kṛṣṇa halts the chariot before Bhīṣma and Droṇa: behold the assembled Kurus.", "1.24", "1.25"),
      ("Seeing Kinsmen", "Fathers, teachers, brothers, sons and friends standing in both armies.", "1.26", "1.27")]),
    ("The Body Fails",
     "At the sight of his family, Arjuna's body and mind collapse.",
     [("My Limbs Fail", "Compassion overwhelms him: trembling limbs, dry mouth, burning skin, a reeling mind.", "1.28", "1.30"),
      ("Inauspicious Omens", "The Gāṇḍīva has slipped; he sees no good in killing his own kinsmen.", "1.31", "1.31")]),
    ("The Moral Crisis",
     "Victory, kingdom and pleasure lose all meaning; killing one's own kin can bring only sin.",
     [("Of What Use Is a Kingdom?", "Those for whose sake we wanted kingdom and joy stand here ready to die.", "1.32", "1.35"),
      ("Only Sin Would Follow", "Slaying the sons of Dhṛtarāṣṭra could bring no pleasure — only sin.", "1.36", "1.37")]),
    ("The Ruin of the Family",
     "The destruction of family-dharma unravels society: lost rites, corrupted women, the mixing of classes, and hell for the destroyers.",
     [("Though They See No Fault", "Their minds overcome by greed, they see no crime in destroying the family — but we do.", "1.38", "1.39"),
      ("When Dharma Is Lost", "Family-duties perish, adharma spreads, and the women of the family are corrupted.", "1.40", "1.41"),
      ("The Mixing of Classes", "Ancestors fall, eternal duties are destroyed, and hell awaits the destroyers.", "1.42", "1.44")]),
    ("The Bow Is Laid Down",
     "The argument ends and the collapse comes: better to die unarmed than commit this sin — and Arjuna sinks down in grief.",
     [("Alas, What a Great Sin", "Better to die unarmed and unresisting; Arjuna casts aside bow and arrows and sinks down on the chariot seat.", "1.45", "1.47")]),
]

# Translations: verse num -> (literal, paraphrase)
CH1_TRANSLATIONS = {
1: ("Dhṛtarāṣṭra said: On the field of dharma, the field of the Kurus, assembled and eager for battle — my people and the sons of Pāṇḍu — what did they do, O Sañjaya?",
    "King Dhṛtarāṣṭra asks: “On the sacred field of Kurukṣetra, my sons and Pāṇḍu's sons have gathered, ready to fight. Tell me, Sañjaya — what happened?”"),
2: ("Sañjaya said: Seeing the Pāṇḍava army drawn up in battle-array, Duryodhana then approached his teacher and spoke these words, O King.",
    "Sañjaya replies: “Seeing the Pāṇḍavas' army in formation, Duryodhana went to his teacher Droṇa and said, O King…”"),
3: ("Behold, O teacher, this great army of the sons of Pāṇḍu, arrayed for battle by the son of Drupada, your wise disciple.",
    "“Look, my teacher — this mighty host of Pāṇḍu's sons, drawn up by your own clever disciple, Drupada's son Dhṛṣṭadyumna.”"),
4: ("Here are heroes, great archers, equals of Bhīma and Arjuna in war: Yuyudhāna, Virāṭa, and Drupada, the great chariot-warrior.",
    "“In their ranks are champions and master bowmen, the match of Bhīma and Arjuna: Yuyudhāna, King Virāṭa, and the great warrior Drupada.”"),
5: ("And Dhṛṣṭaketu, Cekitāna, the valiant king of Kāśī, Purujit, Kuntibhoja, and Śaibya, the bull among men.",
    "“And there too: Dhṛṣṭaketu, Cekitāna, the brave King of Kāśī, Purujit, Kuntibhoja, and the peerless Śaibya.”"),
6: ("The mighty Yudhāmanyu and the valiant Uttamaujas, the son of Subhadrā, and the sons of Draupadī — all great chariot-warriors.",
    "“The fearless Yudhāmanyu, the strong Uttamaujas, Subhadrā's son Abhimanyu, and Draupadī's five sons — all masters of the war-chariot.”"),
7: ("But know, O best of the twice-born, those who are distinguished among us — the leaders of my army; I name them to you for your information.",
    "“But, best of priests, let me tell you who stands out on our side — the commanders of my forces, so you know exactly who leads us.”"),
8: ("You yourself, Bhīṣma, Karṇa, Kṛpa the conqueror in battle, Aśvatthāmā, Vikarṇa, and the son of Somadatta as well.",
    "“You, my teacher; and Bhīṣma, Karṇa, the battle-victorious Kṛpa, Aśvatthāmā, Vikarṇa, and Somadatta's son — all unconquered in war.”"),
9: ("And many other heroes, ready to give up their lives for my sake, armed with various weapons, all skilled in war.",
    "“Many more heroes stand with us, ready to die for me, wielding every kind of weapon — all of them seasoned in battle.”"),
10: ("Insufficient is that strength of ours, guarded by Bhīṣma; sufficient is this strength of theirs, guarded by Bhīma.",
    "“Our force, though shielded by Bhīṣma, is not enough; theirs, protected by Bhīma, is more than sufficient.”"),
11: ("Stationed at all the approaches, take your places in your divisions — and above all, protect Bhīṣma alone, all of you.",
    "“Take your positions at every approach, each in your assigned place — and you must all protect Bhīṣma above all.”"),
12: ("To gladden him, the grandsire of the Kurus, the glorious Bhīṣma, roared a lion's roar and blew his conch loudly.",
    "To lift Duryodhana's spirits, the aged grandsire Bhīṣma let out a lion's roar and blew his great conch with all his might."),
13: ("Then conches, drums, kettledrums, tabors and horns were suddenly struck together — that sound became tumultuous.",
    "At once conches and kettledrums, tabors and trumpets crashed together, and the din swelled into a tremendous clamour."),
14: ("Then, standing in a great chariot yoked with white horses, Mādhava and the son of Pāṇḍu blew their divine conches.",
    "Then, on the great chariot drawn by white horses, Kṛṣṇa (Mādhava) and Arjuna raised their celestial conches and blew."),
15: ("Hṛṣīkeśa blew Pāñcajanya; Dhanañjaya blew Devadatta; and Bhīma, the doer of herculean deeds, blew the great conch Pauṇḍra.",
    "Kṛṣṇa sounded his conch Pāñcajanya, Arjuna his Devadatta, and the mighty Bhīma, famed for his great deeds, blew the colossal Pauṇḍra."),
16: ("King Yudhiṣṭhira, son of Kuntī, blew Anantavijaya; Nakula and Sahadeva blew Sughoṣa and Maṇipuṣpaka.",
    "“King Yudhiṣṭhira sounded the conch called Endless Victory; Nakula and Sahadeva sounded theirs, Sweet-Toned and Jewel-Blossom.”"),
17: ("And the king of Kāśī, the supreme archer, Śikhaṇḍī the great chariot-warrior, Dhṛṣṭadyumna, Virāṭa, and the unconquered Sātyaki.",
    "So too the great archer of Kāśī, Śikhaṇḍī the mighty warrior, Dhṛṣṭadyumna, King Virāṭa, and the never-defeated Sātyaki."),
18: ("Drupada and the sons of Draupadī, O lord of the earth, and the mighty-armed son of Subhadrā — all blew their conches, each his own.",
    "Drupada, Draupadī's sons, and the strong-armed son of Subhadrā — each, O king, blew his own conch in turn."),
19: ("That uproar shattered the hearts of the sons of Dhṛtarāṣṭra, resounding tumultuously through the sky and the earth.",
    "The deafening blast tore into the hearts of Dhṛtarāṣṭra's sons and echoed across both heaven and earth."),
20: ("Then, seeing the Dhārtarāṣṭras stationed in array, as the clash of weapons was about to begin, the Pāṇḍava, whose banner bore the ape, raised his bow.",
    "As the battle was about to erupt, Arjuna — whose banner bore the emblem of Hanumān — looked at the enemy host and lifted his bow."),
21: ("O lord of the earth, he then spoke this word to Hṛṣīkeśa: “Place my chariot between the two armies, O Acyuta.”",
    "Then, O king, Arjuna said to Kṛṣṇa: “Set my chariot between the two armies, O changeless Lord.”"),
22: ("“So that I may see those standing here eager for battle — with whom I must contend in this great enterprise of war.”",
    "“Let me see those who have come to fight, and know who it is I must face in this coming battle.”"),
23: ("“I wish to see those who are to fight, who have gathered here — desiring to please the evil-minded son of Dhṛtarāṣṭra in battle.”",
    "“I want to see the warriors assembled here, those who have come to gratify the wicked Duryodhana by waging this war.”"),
24: ("Sañjaya said: Thus addressed by Gudākeśa, Hṛṣīkeśa, O descendant of Bharata, placed that best of chariots between the two armies.",
    "Sañjaya continues: “So ordered by Arjuna, O Dhṛtarāṣṭra, Kṛṣṇa drove the finest chariot to the middle of the two armies.”"),
25: ("Before Bhīṣma, Droṇa, and all the rulers of the earth, he said: “O Pārtha, behold these Kurus assembled here.”",
    "Before Bhīṣma, Droṇa, and all the world's kings, Kṛṣṇa said: “Look, Arjuna — the whole Kuru clan gathered before you.”"),
26: ("There Arjuna saw stationed: fathers, grandfathers, teachers, maternal uncles, brothers, sons, grandsons, and friends as well.",
    "There, between the armies, Arjuna saw his fathers and grandfathers, teachers and uncles, brothers, sons, grandsons, and friends."),
27: ("Fathers-in-law and well-wishers in both armies — seeing all these kinsmen stationed there, the son of Kuntī…",
    "Fathers-in-law and dear companions on both sides — as Arjuna, Kuntī's son, looked upon all his kin drawn up for battle…"),
28: ("Overwhelmed with profound compassion and grieving, he spoke — Arjuna said: “Seeing these my own people, O Kṛṣṇa, standing here eager for battle…”",
    "Filled with deep pity and grief, Arjuna said: “O Kṛṣṇa, seeing my own family before me, ready to fight…”"),
29: ("“My limbs fail, my mouth dries up, trembling runs through my body, and my hair stands on end.”",
    "“My legs give way, my mouth goes dry, my whole body trembles, and my hair bristles with dread.”"),
30: ("“The Gāṇḍīva slips from my hand, my skin burns; I cannot stand still, and my mind reels.”",
    "“Gāṇḍīva falls from my hand, my skin burns; I can hardly stand, and my mind is spinning out of control.”"),
31: ("“And I see inauspicious omens, O Keśava; nor do I see any good in killing my own kinsmen in battle.”",
    "“I see only evil omens, Kṛṣṇa — and no good that could come from slaughtering my own people in war.”"),
32: ("“I do not desire victory, O Kṛṣṇa, nor kingdom nor pleasures. Of what use is a kingdom to us, O Govinda — what use are enjoyments, or even life?”",
    "“I want no victory, Kṛṣṇa — no kingdom, no pleasures. What are a kingdom, delights, or life itself to us now, Govinda?”"),
33: ("“Those for whose sake we desired kingdom, enjoyments and pleasures — they stand here in battle, having given up their lives and wealth.”",
    "“The very people for whom we wanted a kingdom, comforts and happiness stand here now, ready to lay down their lives and fortunes.”"),
34: ("“Teachers, fathers, sons, and likewise grandfathers, maternal uncles, fathers-in-law, grandsons, brothers-in-law and other relatives.”",
    "“My teachers, fathers, sons and grandfathers, my uncles and fathers-in-law, grandsons, brothers-in-law and all our kin — all are here.”"),
35: ("“I do not wish to kill them, even if they kill me, O Madhusūdana — not even for the sovereignty of the three worlds, let alone for the sake of this earth.”",
    "“I will not kill them, Madhusūdana — even if they kill me. Not for dominion over all three worlds would I do it, let alone for this earth.”"),
36: ("“Slaying the sons of Dhṛtarāṣṭra, what pleasure would be ours, O Janārdana? Sin alone would take hold of us for killing these aggressors.”",
    "“Even if we destroyed the sons of Dhṛtarāṣṭra, what joy would we feel, Janārdana? Only sin would cling to us for murdering these would-be killers.”"),
37: ("“Therefore we should not kill our kinsmen, the sons of Dhṛtarāṣṭra; for how, having slain our own people, could we be happy, O Mādhava?”",
    "“So it is wrong for us to kill our own family — the sons of Dhṛtarāṣṭra. How could we ever be happy, Mādhava, after slaughtering our own kin?”"),
38: ("“Though these men, their minds overcome by greed, see no fault in destroying the family and no crime in treachery toward friends…”",
    "“True, these men — their hearts blinded by greed — see no wrong in wrecking a family and no sin in betraying friends…”"),
39: ("“But how can we not know — we who see the fault of family-destruction — that we must turn back from this sin, O Janārdana?”",
    "“But we can see the ruin that destroying a family brings — so how could we fail to draw back from this sin, Janārdana?”"),
40: ("“With the destruction of the family, the eternal family-duties are lost; and when dharma is lost, adharma overwhelms the whole family.”",
    "“When a family is destroyed, its age-old sacred customs die with it; and once dharma is lost, irreligion takes over the entire family.”"),
41: ("“From the rise of adharma, O Kṛṣṇa, the women of the family become corrupted; and from corrupted women, O Vārṣṇeya, arises the mixing of classes.”",
    "“When adharma prevails, Kṛṣṇa, the family's women are corrupted; and from corrupted women comes the confusion of castes and lines.”"),
42: ("“This mixing leads to hell for the destroyers of the family and for the family itself; their ancestors fall, deprived of the offerings of rice and water.”",
    "“Such confusion drags both the family's destroyers and the family itself toward hell, and their departed ancestors fall, robbed of their funeral rites.”"),
43: ("“By these faults of the family-destroyers, which cause the mixing of classes, the eternal duties of the community and the family are destroyed.”",
    "“Through these sins that breed class-confusion, the timeless duties of both the caste and the clan are swept away.”"),
44: ("“For men whose family-duties are destroyed, O Janārdana, there is said to be a certain abode in hell — thus have we heard.”",
    "“And, Janārdana, we have heard it said that those whose family-rites are destroyed must dwell in hell.”"),
45: ("“Alas! What a great sin we have resolved to commit — driven by greed for kingdom and pleasure, we are ready to kill our own kin.”",
    "“What terrible wrong are we about to do! Blinded by the craving for a throne and its pleasures, we are prepared to kill our own family.”"),
46: ("“If the sons of Dhṛtarāṣṭra, weapons in hand, should kill me in battle — me unarmed and unresisting — that would be better for me.”",
    "“If Dhṛtarāṣṭra's sons should strike me down — me defenceless and unarmed — that would be far better than to fight.”"),
47: ("Sañjaya said: Having spoken thus on the battlefield, Arjuna sat down on the seat of the chariot, casting aside his bow and arrows, his mind overwhelmed with grief.",
    "Sañjaya concludes: “So saying, Arjuna sank down on the chariot's seat, dropped his bow and arrows, and sat there, his heart torn apart with grief.”"),
}
