# -*- coding: utf-8 -*-
"""gita_data11.py — Chapter 11 (Viśvarūpa-Darśana Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH11_THEMES = [
    ("Arjuna's Request",
     "The delusion is gone; now Arjuna longs to see the imperishable form itself.",
     [("My Delusion Is Gone", "By the supreme secret word concerning the Self which you have spoken out of compassion, this delusion of mine is gone.", "11.01", "11.01"),
      ("I Have Heard of Your Origin and Passing", "I have heard in full from you of the origin and dissolution of beings, and of your imperishable majesty. As you have described yourself, O supreme Lord, so I desire to see your divine form.", "11.02", "11.03"),
      ("If You Think I Can Bear It, Show Me", "If you think it possible for me to behold it, O Lord, master of yoga, then show me your imperishable Self.", "11.04", "11.04")]),
    ("The Vision Granted",
     "Behold my hundreds and thousands of forms — and, since mortal eyes cannot see them, receive a divine eye.",
     [("Behold My Hundreds and Thousands of Forms", "Behold my forms, O Pārtha, by hundreds and by thousands, of many kinds, divine, of various colours and shapes. Behold the Ādityas, Vasus, Rudras, Aśvins and Maruts; behold many wonders never seen before.", "11.05", "11.06"),
      ("See the Whole World in My Body", "Behold now the whole universe, moving and unmoving, standing together here in my body — and whatever else you desire to see.", "11.07", "11.07"),
      ("I Give You a Divine Eye", "But you cannot see me with these eyes of yours; I give you a divine eye — behold my sovereign yoga.", "11.08", "11.08")]),
    ("Sañjaya Describes",
     "The narrator's voice: if a thousand suns should rise together, that would not equal the splendour of that great Self.",
     [("The Great Lord of Yoga Showed His Form", "Having spoken thus, the great Lord of yoga, Hari, showed to Arjuna his supreme sovereign form — with many mouths and eyes, many wondrous sights, many divine ornaments and uplifted divine weapons.", "11.09", "11.10"),
      ("If a Thousand Suns Should Rise", "Wearing divine garlands and robes, anointed with divine perfumes, all-wonderful, resplendent, boundless, facing every direction. If the splendour of a thousand suns were to rise at once in the sky, it would not equal the splendour of that great being.", "11.11", "11.12"),
      ("The Whole Universe in One Place", "There Arjuna beheld the whole universe, divided in many ways, standing as one in the body of the God of gods.", "11.13", "11.13"),
      ("Hair on End, Bowing With Folded Hands", "Then Arjuna, filled with amazement, his hair standing on end, bowed his head to the God and spoke with folded hands.", "11.14", "11.14")]),
    ("I See All the Gods",
     "In your body I see all beings — Brahmā on his lotus seat, the seers, the serpents — a blazing mass of radiance without beginning or end.",
     [("I See All Beings in Your Body", "I see all the gods in your body, O God, and the hosts of all kinds of beings; Brahmā the Lord seated on the lotus, all the seers and the divine serpents.", "11.15", "11.15"),
      ("Infinite Arms, No Beginning, Middle or End", "I see you with countless arms, bellies, mouths and eyes, of boundless form on every side; I see no end, no middle, and no beginning in you, O Lord of all, universal form.", "11.16", "11.16"),
      ("A Blazing Mass of Radiance", "I see you crowned, armed with mace and discus, a mass of radiance blazing everywhere — hard to look upon, immeasurable, like blazing fire and sun on every side.", "11.17", "11.17"),
      ("You Are the Imperishable, the Supreme to Be Known", "You are the imperishable, the supreme to be known; you are the ultimate resting place of this universe; you are the undying guardian of eternal dharma — you are the primal Person, I hold.", "11.18", "11.18")]),
    ("The Terrible Form",
     "Sun and moon for eyes, mouths blazing with fire — the three worlds tremble, and Arjuna with them.",
     [("Sun and Moon for Eyes", "Without beginning, middle or end, of infinite power, with countless arms, with sun and moon for eyes — I see you with fire-like mouths, burning this whole universe with your radiance.", "11.19", "11.19"),
      ("The Three Worlds Tremble", "The space between heaven and earth and all the quarters are filled by you alone; seeing this wondrous, terrible form of yours, the three worlds tremble, O great soul.", "11.20", "11.20"),
      ("The Hosts of Gods Enter You", "The hosts of gods enter into you; some in fear praise you with folded hands; bands of great seers and perfected ones cry 'Hail!' and extol you with abundant hymns.", "11.21", "11.21"),
      ("Rudras, Ādityas, Vasus Gaze in Wonder", "The Rudras, Ādityas, Vasus, Sādhyas, Viśvedevas, Aśvins, Maruts and the ancestors; the hosts of gandharvas, yakṣas, demons and perfected ones — all gaze upon you in wonder.", "11.22", "11.22"),
      ("Seeing Your Fearsome Form, I Tremble", "Seeing your great form of many mouths and eyes, many arms, thighs and feet, many bellies and many terrible tusks — the worlds tremble, and so do I.", "11.23", "11.23")]),
    ("I Find No Peace",
     "Touching the sky, blazing with many colours, mouths like the fire at the end of time — Arjuna's heart shakes and he begs for grace.",
     [("Touching the Sky, Blazing With Many Colours", "Seeing you touching the sky, blazing with many colours, with gaping mouths and huge fiery eyes — my inmost self trembles, and I find neither courage nor peace, O Viṣṇu.", "11.24", "11.24"),
      ("Like the Fire at the End of Time", "Seeing your mouths, terrible with tusks, like the fire of universal destruction, I know not the directions and find no refuge; be gracious, O Lord of gods, abode of the universe.", "11.25", "11.25"),
      ("The Sons of Dhṛtarāṣṭra Enter Your Mouths", "All these sons of Dhṛtarāṣṭra, with the hosts of kings, and Bhīṣma, Droṇa and Karṇa, together with the chief warriors of our side too —", "11.26", "11.26"),
      ("Heads Crushed Between Your Teeth", "— they rush headlong into your fearful mouths with their terrible tusks; some are seen caught between your teeth, their heads crushed to powder.", "11.27", "11.27")]),
    ("As Moths Into a Flame",
     "As rivers rush into the ocean and moths into a blazing fire, so these worlds rush into your mouths to their destruction.",
     [("As Rivers Rush Into the Ocean", "As the many torrents of rivers race toward the ocean, so these heroes of the world of men enter your blazing mouths.", "11.28", "11.28"),
      ("As Moths Fly Into a Blazing Fire", "As moths rush headlong into a blazing fire to their destruction, so these worlds rush into your mouths to their own destruction.", "11.29", "11.29"),
      ("You Lick Up All the Worlds", "You lick up, devouring on all sides, all the worlds with your flaming mouths; your fierce rays fill the whole universe with radiance and scorch it, O Viṣṇu.", "11.30", "11.30"),
      ("Tell Me Who You Are", "Tell me who you are, so fierce of form — salutation to you, O best of gods, be gracious! I desire to know you, the primal one, for I do not comprehend your working.", "11.31", "11.31")]),
    ("I Am Time",
     "The answer: I am Time, grown mature, come forth to annihilate the worlds — these warriors are already slain; be but my instrument.",
     [("I Am Time, Destroyer of Worlds", "I am Time, the mighty destroyer of the worlds, come forth here to annihilate them; even without you, all the warriors arrayed in the opposing armies shall cease to be.", "11.32", "11.32"),
      ("Be My Instrument", "Therefore arise and win glory; conquering the foe, enjoy a prosperous kingdom. By me alone they have already been slain — be you the mere instrument, O left-handed archer.", "11.33", "11.33"),
      ("They Are Already Slain by Me", "Droṇa, Bhīṣma, Jayadratha, Karṇa and the other brave warriors are already slain by me; slay them without wavering — fight, you shall conquer your rivals in battle.", "11.34", "11.34")]),
    ("Arjuna Bows and Praises",
     "Trembling and with folded hands, Arjuna hails him greater than Brahmā, the primal God, the ancient Person — and bows on every side.",
     [("Trembling, With Faltering Voice", "Hearing these words of Keśava, the crowned Arjuna, trembling, with folded palms, bowed again and spoke to Kṛṣṇa in a faltering voice, overcome with fear.", "11.35", "11.35"),
      ("The World Rejoices in Your Praise", "It is fitting, Hṛṣīkeśa, that the world rejoices and delights in your glory; the rākṣasas flee in fear in every direction, and the hosts of the perfected bow to you.", "11.36", "11.36"),
      ("Why Should They Not Bow to You?", "And why should they not bow to you, O great soul, greater even than Brahmā, the primal creator? O infinite Lord of gods, abode of the universe, you are the imperishable, being and non-being and what is beyond both.", "11.37", "11.37"),
      ("You Are the Primal God, the Ancient Person", "You are the primal God, the ancient Person; you are the supreme resting place of this universe; you are the knower and the known, the supreme abode — by you the universe is pervaded, O form infinite.", "11.38", "11.38"),
      ("You Are Vāyu, Yama, Agni, the Moon", "You are Vāyu, Yama, Agni, Varuṇa, the moon, Prajāpati and the great-grandsire; salutation to you a thousand times, and again and yet again salutation to you.", "11.39", "11.39"),
      ("Salutation on Every Side", "Salutation to you before and behind, salutation to you on every side, O All! Of infinite power and immeasurable might, you pervade all — therefore you are all.", "11.40", "11.40")]),
    ("Forgive My Familiarity",
     "Whatever I said carelessly, calling you friend — not knowing your greatness — forgive, as a father forgives a son.",
     [("Whatever I Said, Calling You \u201cFriend\u201d", "Whatever I said rashly, from carelessness or love — 'O Kṛṣṇa, O Yādava, O friend' — thinking you my companion, not knowing this greatness of yours,", "11.41", "11.41"),
      ("Whatever Disrespect I Showed in Sport", "— and in whatever way I may have shown you disrespect, in jest, while resting, sitting or at meals, alone or before others, O unshaken one — I beg forgiveness of you, immeasurable.", "11.42", "11.42"),
      ("Father of the World, Teacher Beyond Compare", "You are the father of this world, of the moving and the unmoving; you are its object of worship and its most venerable teacher. There is none equal to you in the three worlds — how then any greater, O being of matchless power?", "11.43", "11.43"),
      ("Forgive as a Father Forgives His Son", "Therefore, bowing down and prostrating my body, I crave your forgiveness, O adorable Lord; as a father to his son, as a friend to his friend, as a lover to the beloved — please bear with me, O God.", "11.44", "11.44")]),
    ("Show Me the Gracious Form",
     "Delighted yet trembling, Arjuna asks for the familiar four-armed form; and Kṛṣṇa says: this form none but you has ever seen.",
     [("Delighted, Yet My Mind Trembles", "I am delighted at having seen what was never seen before — yet my mind is shaken with fear; show me that other form of yours, O God; be gracious, Lord of gods, abode of the universe.", "11.45", "11.45"),
      ("I Long to See You Crowned, With Mace and Discus", "I wish to see you just as before — crowned, bearing the mace and discus in your hand; assume again that four-armed form, O thousand-armed one of universal form.", "11.46", "11.46"),
      ("By My Grace You Have Seen It", "By my grace, and through my own power, this supreme form has been shown to you, O Arjuna — luminous, universal, infinite, primeval, which none but you has ever seen.", "11.47", "11.47"),
      ("Not by Vedas or Austerities Can It Be Seen", "Neither by the Vedas nor by sacrifices, nor by study or gifts, nor by rites or severe austerities can I be seen in this form in the world of men, by any but you, O hero of the Kurus.", "11.48", "11.48")]),
    ("The Gentle Form Restored",
     "Be not afraid; behold again my familiar form — and Arjuna, composed, returns to his own nature.",
     [("Be Not Afraid or Bewildered", "Do not be afraid or bewildered on seeing this terrible form of mine; free from fear and glad at heart, behold once more this former form of mine.", "11.49", "11.49"),
      ("Vāsudeva Shows His Own Form Again", "Having spoken thus to Arjuna, Vāsudeva showed his own form again; and the great soul, assuming once more his gentle shape, comforted the terrified one.", "11.50", "11.50"),
      ("Now I Am Composed and Restored", "Seeing this gentle human form of yours, O Janārdana, I am now composed in mind and restored to my own nature.", "11.51", "11.51")]),
    ("By Devotion Alone",
     "This form even the gods long to see; not by Vedas or austerities, but by undivided devotion alone can I be known — and he who works for me, free from enmity, comes to me.",
     [("Even the Gods Long to See This Form", "Very hard to see is this form of mine which you have seen; even the gods are ever eager to behold this form.", "11.52", "11.52"),
      ("Not by Vedas, Austerity or Gifts", "Not by the Vedas, nor by austerity, nor by gifts, nor by sacrifice can I be seen as you have seen me.", "11.53", "11.53"),
      ("By Undivided Devotion Alone", "But by undivided devotion, O Arjuna, I can be known and truly seen in this form — and entered into, O scorcher of foes.", "11.54", "11.54"),
      ("He Who Works for Me Comes to Me", "He who does my work, who holds me as supreme, who is devoted to me, free from attachment and without enmity toward any being — he comes to me, O Pāṇḍava.", "11.55", "11.55")]),
]

CH11_TRANSLATIONS = {
1: ("Arjuna said: By your compassionate words about the supreme secret of the Self, my delusion is gone.",
    "Arjuna says: “Because you graciously spoke to me of the highest secret of the Self, my confusion has vanished.”"),
2: ("The origin and dissolution of beings have I heard from you in detail, O lotus-eyed one, and your infinite glory.",
    "“I have heard from you, O lotus-eyed Lord, of the birth and passing of all beings, and of your endless majesty.”"),
3: ("Even as you have described yourself, O supreme Lord, I long to see your cosmic form, O best of persons.",
    "“Just as you have described yourself, O highest Lord, I want to see your universal form.”"),
4: ("If you think it can be seen by me, O Lord, then show me your imperishable self, O Lord of yoga.",
    "“If you judge that I am able to see it, O Lord of yoga, reveal to me your eternal Self.”"),
5: ("The Blessed Lord said: Behold, O Pārtha, my forms by the hundred and thousand, of various kinds and colors.",
    "Kṛṣṇa said: “See now, Arjuna, my hundreds and thousands of forms — of many kinds and many colors.”"),
6: ("Behold the Ādityas, the Vasus, the Rudras, the Aśvins and the Maruts; behold many wonders never seen before, O Bhārata.",
    "“See the sun-gods, the Vasus, the Rudras, the twin Aśvins, the storm-winds — wonders you have never seen, Arjuna.”"),
7: ("Behold now the whole universe, moving and unmoving, gathered in one body here in mine, O Guḍākeśa — and whatever else you wish to see.",
    "“See the entire universe — moving and still — all at once within my body, and whatever else you desire to see.”"),
8: ("But you cannot see me with your own eye; I give you the divine eye — behold my divine sovereignty.",
    "“Your mortal eye cannot see me — take this divine eye and behold my cosmic power.”"),
9: ("Sañjaya said: Having spoken thus, O king, the great Lord of yoga, Hari, showed Pārtha his supreme divine form.",
    "Sañjaya narrates: “Having said this, O king, the great Lord of yoga, Kṛṣṇa, revealed to Arjuna his supreme cosmic form.”"),
10: ("With countless faces and eyes, with countless wondrous sights, with countless divine ornaments and uplifted weapons,",
    "“— with innumerable faces and eyes, marvels beyond count, celestial ornaments, and weapons raised on every side —”"),
11: ("wearing divine garlands and robes, anointed with divine perfumes, full of all wonders — the infinite God, facing everywhere.",
    "“— adorned with heavenly garlands and garments, anointed with divine fragrances, the limitless God with faces in every direction.”"),
12: ("If the splendour of a thousand suns were to rise at once in the sky, it would not equal the splendour of that great being.",
    "“If a thousand suns blazed up together in the sky, it would not match the glory of that great being.”"),
13: ("There, in the body of the God of gods, the son of Pāṇḍu saw the whole universe, one yet divided into manifold forms.",
    "“There Arjuna saw the entire universe — united yet infinitely varied — within the body of the God of gods.”"),
14: ("Then, filled with wonder, his hair standing on end, Dhanañjaya bowed his head to the God and spoke with joined palms.",
    "“Then, overwhelmed with wonder, hair on end, Arjuna bowed down and, folding his hands, spoke.”"),
15: ("I see all the gods in your body, O God, and all the hosts of beings; Brahmā the Lord seated on the lotus, and all the seers and divine serpents.",
    "“In your body I see all the gods and every class of being — Brahmā on his lotus throne, the sages, and the celestial serpents.”"),
16: ("I see you with countless arms, bellies, mouths and eyes — your form is endless on every side; I see no end, no middle, no beginning of you, O Lord of the universe, cosmic form.",
    "“I see you, O universal form, with numberless arms, bellies, faces and eyes — infinite on all sides; you have no beginning, middle, or end.”"),
17: ("I see you crowned, wielding mace and discus, a mass of light shining everywhere — hard to gaze upon, blazing like fire and sun, immeasurable.",
    "“I see you with crown, mace, and discus — a blaze of light, too dazzling to look upon, like fire and sun, measureless.”"),
18: ("You are the imperishable, the supreme object of knowledge; you are the supreme refuge of this universe; you are the eternal guardian of dharma — the primal Person, so I deem you.",
    "“You are the eternal, the highest to be known; you are the universe's supreme treasure, the changeless guardian of dharma — the original Person.”"),
19: ("Without beginning, middle or end, of infinite power, with countless arms, with sun and moon for eyes — I see you blazing with fire-like mouths, consuming the whole world with your radiance.",
    "“Without beginning or end, infinite in might, countless-armed, sun-and-moon-eyed — I see you, fire-mouthed, burning up the world with your brilliance.”"),
20: ("The space between earth and heaven is filled by you alone, and all the directions; seeing your terrible, wondrous form, the three worlds tremble, O great soul.",
    "“Between heaven and earth, in every direction, you alone fill all — and the three worlds tremble at your awesome form.”"),
21: ("The hosts of gods enter you; some, afraid, praise you with folded hands; the hosts of great seers and siddhas sing your praises with hymns.",
    "“The troops of gods stream into you; some, terrified, glorify you with joined palms; the sages and perfected ones praise you with sacred hymns.”"),
22: ("The Rudras, Ādityas, Vasus, Sādhyas, Viśve-devas, Aśvins, Maruts and the ancestors — the gandharvas, yakṣas, demons and siddhas — all gaze on you in wonder.",
    "“All the orders of gods — the Rudras, sun-gods, Vasus, and the rest — together with celestial singers and spirits, gaze upon you astonished.”"),
23: ("Seeing your immense form, O mighty-armed one, with many mouths and eyes, many bellies, many fearsome fangs, the worlds tremble — and so do I.",
    "“At the sight of your colossal form, mighty-armed one — with its many faces, eyes, bellies, and terrible jaws — the worlds tremble, and I too.”"),
24: ("Touching the sky, blazing, of many colours, with gaping mouths and blazing wide eyes — seeing you, my inmost heart trembles; I find no firmness or peace, O Viṣṇu.",
    "Beholding your sky-touching, blazing, many-coloured form — gaping mouths, wide flaming eyes — my heart is shaken; I find no steadiness or calm, O Viṣṇu."),
25: ("Seeing your terrible mouths with their fearful fangs, like the fire of the end of time, I do not know the directions, nor find any refuge; be gracious, O Lord of gods, abode of the world.",
    "Beholding your dreadful fanged mouths, blazing like the fire of destruction, I lose all bearings and find no shelter; have mercy, Lord of gods."),
26: ("All these sons of Dhṛtarāṣṭra, with the hosts of kings, enter your mouths — Bhīṣma, Droṇa, Karṇa, and the chief warriors of our side,",
    "“These sons of Dhṛtarāṣṭra, together with their kings, are rushing into your mouths — Bhīṣma, Droṇa, Karṇa, and our foremost warriors,”"),
27: ("their heads crushed between your teeth — some cling in fear, visible in the gaps of your terrible fangs.",
    "“— their heads ground to powder in your teeth; some, caught between your terrible jaws, are seen clinging in terror.”"),
28: ("As the many rushing currents of rivers pour into the ocean, so these heroes of the mortal world enter your blazing mouths.",
    "“As rivers pour their countless waters into the sea, so these champions of men stream into your blazing mouths.”"),
29: ("As moths fly with full speed into a blazing fire for their destruction, so these worlds fly into your mouths for their destruction.",
    "“As moths hurl themselves into the flame to perish, so these worlds rush into your mouths to be destroyed.”"),
30: ("You lick up all the worlds with your flaming mouths, devouring them on every side; your terrible rays fill the whole universe, O Viṣṇu.",
    "“You lap up the worlds with your burning jaws, swallowing them wholly; your fierce glory fills the universe, O Viṣṇu.”"),
31: ("Tell me who you are, O terrible form; I bow to you — be gracious, O best of gods! I long to know you, the primeval one; I do not understand your workings.",
    "“Tell me who you are in this dreadful form; I bow to you — have mercy, Lord. I want to know you, the Ancient One, for I cannot grasp your ways.”"),
32: ("The Blessed Lord said: I am Time, the world-destroyer, grown mature; I have come to destroy these worlds — even without you, none of these warriors arrayed against you will remain.",
    "Kṛṣṇa said: “I am Time, ripened to destroy the worlds. Even without your striking, none of these warriors will survive.”"),
33: ("Therefore arise and win glory; conquer your enemies and enjoy the thriving kingdom — they are already slain by me; be only the instrument, O Sāvyasācin.",
    "“So stand up and win renown; defeat the foe and enjoy the flourishing realm. I have already killed them — you are merely the means, Arjuna.”"),
34: ("Slay Droṇa, Bhīṣma, Jayadratha, Karṇa and the other warrior-heroes — already killed by me; strike without fear, fight — you shall conquer your rivals in battle.",
    "“Kill Droṇa, Bhīṣma, Jayadratha, and Karṇa — I have already destroyed them. Strike without hesitation and fight; you will triumph in battle.”"),
35: ("Sañjaya said: Hearing these words of Keśava, the crowned Arjuna, trembling, folded his palms and, bowing again, spoke to Kṛṣṇa with faltering voice.",
    "Sañjaya narrates: “Hearing Kṛṣṇa's words, Arjuna, shaking, joined his palms, bowed once more, and spoke in a stammering voice.”"),
36: ("It is fitting, Hṛṣīkeśa, that the world rejoices and delights in your glory; the rākṣasas flee in fear in all directions, and the hosts of siddhas bow to you.",
    "“Rightly, O Kṛṣṇa, the world delights in praising you; the demons flee in terror, and the perfected ones bow to you.”"),
37: ("Why should they not bow to you, O great soul, greater than Brahmā, the primal creator — O infinite Lord of gods, abode of the universe, you are the imperishable, being and non-being and beyond both.",
    "“Who would not bow to you, O great one, superior even to Brahmā, the first creator? You are the eternal, the real and the unreal, and what lies beyond.”"),
38: ("You are the primal God, the ancient Person, the supreme refuge of this universe; you are the knower and the known, the supreme abode; by you this universe is pervaded, O infinite form.",
    "“You are the first God, the ancient Person, the universe's highest refuge; you are the knower and the known, the supreme home — and all is spread through you.”"),
39: ("You are wind, death, fire, Varuṇa, the moon, and the progenitor — and the great grandsire; I bow to you a thousand times — again and yet again I bow to you.",
    "“You are air, death, fire, Varuṇa, the moon — the father and the great ancestor. Salutations to you a thousand-fold — again and again, I bow.”"),
40: ("I bow to you from the front and from behind; I bow to you on every side, O all! You are of infinite might and measureless vigour; you pervade all, and so you are all.",
    "“I bow to you before and behind; I bow to you on every side, O All. Your power is endless — you are everything, for you fill everything.”"),
41: ("Whatever I said in rash familiarity — 'O Kṛṣṇa, O Yādava, O friend' — not knowing your majesty, whether in carelessness or in love,",
    "“Whatever I said to you boldly and thoughtlessly — calling you Kṛṣṇa, Yādava, my friend — ignorant of your greatness, whether in jest or fondness,”"),
42: ("and whatever disrespect I showed you in sport, rest, sitting or at meals, alone or before others, O Acyuta — that I beg you to forgive, O immeasurable one.",
    "“— and however I slighted you in play, in rest, at meals, alone or in company — forgive all that, O changeless, measureless Lord.”"),
43: ("You are the father of this world, moving and unmoving; you are its supreme object of worship and the most venerable teacher; none equals you in the three worlds, how then could any surpass you, O being of matchless power?",
    "“You are the father of all that moves and stands; you are the supreme object of reverence, the greatest teacher. In the three worlds nothing equals you — let alone surpasses you.”"),
44: ("Therefore I bow and prostrate my body before you, and beg your grace, O adorable Lord; as a father forgives his son, a friend his friend, a lover the beloved — so forgive me, O God.",
    "“So I bow low before you and implore your grace. As a father pardons a son, a friend a friend, a lover the beloved — forgive me, O Lord.”"),
45: ("Having seen what I never saw before, I am delighted, yet my mind trembles with fear; show me, O God, your gracious form — be merciful, O Lord of the universe.",
    "“Having seen this wonder I rejoice, yet my heart quakes with fear; show me your gentle form, O Lord — have mercy.”"),
46: ("I long to see you as before — crowned, with mace and discus in hand; appear in that four-armed form, O thousand-armed, universal form.",
    "“I wish to see you again as before — with crown, mace, and discus; appear in that four-armed shape, O cosmic form.”"),
47: ("The Blessed Lord said: By my grace, Arjuna, I have shown you this supreme form — the luminous, universal, infinite, primeval form that none but you has ever seen.",
    "Kṛṣṇa said: “Out of grace, Arjuna, I have revealed to you this supreme, radiant, universal, infinite, primal form — seen by no one before you.”"),
48: ("Not by the study of the Vedas and sacrifices, nor by gifts, rites or fierce austerities, can I be seen in this form in the world of men — by any but you, O prince of the Kurus.",
    "“Neither by Vedic study, sacrifice, charity, ritual, nor harsh austerity can this form be seen in the mortal world — by anyone but you.”"),
49: ("Do not be afraid or bewildered at the sight of this terrible form of mine; free from fear, with a glad heart, behold once more this gracious form of mine.",
    "“Fear not, nor be confused, at this dread vision of mine. With fear gone and heart at ease, look again upon my gentle form.”"),
50: ("Sañjaya said: Having spoken thus to Arjuna, Vāsudeva again showed his own form, and the great soul comforted the frightened Arjuna, once more in his gracious appearance.",
    "Sañjaya narrates: “So saying, Kṛṣṇa again assumed his gentle form, and the great soul comforted the terrified Arjuna.”"),
51: ("Arjuna said: Seeing this your gracious human form, O Janārdana, I am now composed and restored to my own nature.",
    "Arjuna says: “Seeing your gentle human form, O Janārdana, I am calm again, and my mind has returned to itself.”"),
52: ("The Blessed Lord said: This form of mine that you have seen is very hard to see; even the gods ever long to see this form.",
    "Kṛṣṇa said: “The form you have seen is exceedingly hard to behold — even the gods always yearn for a sight of it.”"),
53: ("I am not to be seen in this way through the Vedas, nor through austerity, nor through gifts, nor through worship; only in the way you have seen me can I be seen.",
    "“This vision is not won by Vedic study, austerity, charity, or ritual — I am seen thus only as you have seen me.”"),
54: ("But through single-pointed devotion I can be known, seen and entered in truth, O Arjuna, in this very form.",
    "“Yet by undivided devotion I may be truly known, seen, and entered, Arjuna — in this very form.”"),
55: ("He who does my work, who holds me as the supreme goal, who is devoted to me, free from attachment, without enmity toward any being — he comes to me, O Pāṇḍava.",
    "“One who works for me, making me his supreme goal, devoted to me, free of clinging and of enmity toward all — he reaches me, Arjuna.”"),
}
