# -*- coding: utf-8 -*-
"""gita_data8.py — Chapter 8 (Akṣara-Brahma Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH8_THEMES = [
    ("Arjuna asks eight questions",
     "What is Brahman, the Self, action? What are the adhibhūta, adhidaiva and adhiyajña — and how are you to be known at the hour of death?",
     [("The eight questions", "What is that Brahman, what the Self, what action? What is declared the adhibhūta, and what the adhidaiva? Who is the adhiyajña here in this body, and how? And how at the time of departure are you to be known by the self-controlled?", "8.01", "8.01"),
      ("Who is the adhiyajña, and how known at death?", "And what is adhiyajña in this body — and how can those of steady mind know you at the hour of death?", "8.02", "8.02")]),
    ("Kṛṣṇa answers the eight questions",
     "Brahman is the imperishable supreme; one's own nature is adhyātma; the creative force is action; the perishable is adhibhūta, the Puruṣa adhidaiva — and I myself am adhiyajña in the body.",
     [("Brahman, Adhyātma, Karma", "Brahman is the imperishable, the supreme; its essential nature is called adhyātma; the creative force that brings beings into existence is called action.", "8.03", "8.03"),
      ("Adhibhūta, adhidaiva, adhiyajña", "The perishable world is adhibhūta; the Puruṣa is adhidaiva; and I myself am adhiyajña in the body.", "8.04", "8.04")]),
    ("Remembering at the End",
     "Whoever leaves the body remembering me attains my being; whatever state one remembers at the last, to that one goes.",
     [("He who remembers me at the end", "He who at the hour of death leaves the body remembering me alone attains my being — of this there is no doubt.", "8.05", "8.05"),
      ("Whatever state one remembers at death", "Whatever state a man remembers when he gives up the body at the end, to that alone he goes — ever moulded into that being.", "8.06", "8.06"),
      ("Therefore remember me and fight", "Therefore at all times remember me, and fight; with mind and intellect fixed on me, you shall doubtless come to me.", "8.07", "8.07")]),
    ("The Yoga of Constant Practice",
     "With mind fixed by constant practice on the ancient Seer, subtler than the atom, one reaches the supreme divine Person.",
     [("With mind unwavering", "With the mind disciplined by constant practice and not straying elsewhere, meditating on the supreme divine Person, one goes to him.", "8.08", "8.08"),
      ("The ancient seer, subtler than the atom", "He who meditates on the omniscient, ancient, ruler, subtler than the atom, supporter of all, of inconceivable form, sun-coloured, beyond darkness —", "8.09", "8.09"),
      ("At death, with the breath between the brows", "— at the time of departure, with unmoving mind, joined by devotion and the power of yoga, fixing the breath between the brows, he reaches that supreme divine Person.", "8.10", "8.10"),
      ("That which the Vedas call imperishable", "That which the knowers of the Veda call imperishable, which ascetics free from passion enter, desiring which they lead a life of continence — that goal I shall declare to you in brief.", "8.11", "8.11")]),
    ("Depart uttering Om, and reach me",
     "Closing the gates of the senses, holding the breath in the head, uttering the single syllable Om — he goes to the highest state.",
     [("Closing the gates, fixing the breath", "Closing all the gates of the body, confining the mind in the heart, fixing the breath in the head, established in the concentration of yoga —", "8.12", "8.12"),
      ("Uttering Om, the single syllable", "— uttering the single syllable Om, which is Brahman, remembering me as he departs and leaves the body, he goes to the supreme goal.", "8.13", "8.13"),
      ("Easily won by him who remembers daily", "For him who constantly remembers me daily, with mind on nothing else, I am easy to reach, O Pārtha — for that ever-steadfast yogi.", "8.14", "8.14"),
      ("No rebirth in this impermanent house of sorrow", "Having come to me, these great souls are not reborn into this impermanent abode of sorrow, for they have reached the highest perfection.", "8.15", "8.15"),
      ("Even Brahmā's world returns", "From the world of Brahmā downward, all worlds are subject to return; but on reaching me, O son of Kuntī, there is no rebirth.", "8.16", "8.16")]),
    ("A day of Brahmā, a thousand ages",
     "A thousand ages make one day of Brahmā and a thousand ages his night; at daybreak all beings emerge, at nightfall they dissolve.",
     [("A thousand ages are one day", "Those who know that Brahmā's day lasts a thousand ages and his night a thousand ages — they are the knowers of day and night.", "8.17", "8.17"),
      ("At daybreak all emerge, at nightfall dissolve", "At the coming of day, all manifestations arise from the unmanifest; at the coming of night they dissolve into that same unmanifest.", "8.18", "8.18"),
      ("Helplessly reborn again and again", "This very multitude of beings, coming into being again and again, dissolves helplessly at the coming of night and is born again at daybreak.", "8.19", "8.19")]),
    ("Beyond it, an Unmanifest that never dies",
     "Beyond that unmanifest is another Unmanifest, eternal, which does not perish when all beings perish — that is my supreme abode.",
     [("Another unmanifest, eternal", "But beyond that unmanifest is another Unmanifest, eternal, which does not perish when all beings perish.", "8.20", "8.20"),
      ("Reaching it, they do not return", "That unmanifest is called the imperishable, and is declared the supreme goal; those who reach it do not return — that is my supreme abode.", "8.21", "8.21"),
      ("Attained by devotion alone", "That supreme Person, in whom all beings dwell and by whom all this is pervaded, is attainable by undivided devotion, O Pārtha.", "8.22", "8.22")]),
    ("The bright path and the dark",
     "The two eternal ways of departure: by fire, light and the northern course one goes to Brahman and does not return; by smoke, night and the southern course one returns again.",
     [("The two times of departure", "Now I shall declare the times of departure at which yogis go forth to return, and not to return, O best of the Bhāratas.", "8.23", "8.23"),
      ("Fire, light, day, the bright fortnight", "Fire, light, daytime, the bright fortnight, the six months of the northern course — departing then, the knowers of Brahman go to Brahman.", "8.24", "8.24"),
      ("Smoke, night, the dark fortnight", "Smoke, night, the dark fortnight, the six months of the southern course — the yogi attaining the lunar light returns.", "8.25", "8.25"),
      ("The two eternal paths", "These bright and dark paths of the world are held to be eternal; by the one a man goes not to return, by the other he returns again.", "8.26", "8.26"),
     ]),
    ("Knowing both paths, be yoked in yoga",
     "Kṛṣṇa turns from the two paths to Arjuna himself: knowing them, no yogi is deluded — therefore be yoked at all times, and pass beyond every fruit the scriptures promise.",
     [("Knowing both, no yogi is deluded", "Knowing these two paths, no yogi is deluded; therefore at all times be established in yoga, O Arjuna.", "8.27", "8.27"),
      ("Beyond the fruit of Vedas, sacrifice and gifts", "Whatever fruit of merit is declared for the Vedas, sacrifices, austerities and gifts — the yogi who knows this passes beyond them all and reaches the supreme primal abode.", "8.28", "8.28")]),
]

CH8_TRANSLATIONS = {
1: ("Arjuna said: What is that Brahman, what is adhyātma, what is action, O best of men? What is declared adhibhūta, and what is called adhidaiva?",
    "Arjuna asks: “What is Brahman? What is the Self? What is action, Kṛṣṇa? What are adhibhūta and adhidaiva?”"),
2: ("Who and how is adhiyajña here in this body, O Madhusūdana? And how are you to be known at the time of death by the self-controlled?",
    "“And what is adhiyajña in this body — and how can those of steady mind know you at the hour of death?”"),
3: ("The Blessed Lord said: The imperishable is the supreme Brahman; one's own nature is called adhyātma; the creative impulse that brings forth beings is called karma.",
    "Kṛṣṇa said: “The imperishable is the supreme Brahman; one's own being is adhyātma; and the impulse of creation is karma.”"),
4: ("Adhibhūta is the perishable nature; the Puruṣa is adhidaivata; I myself am adhiyajña here in the body, O best of the embodied.",
    "“The perishable world is adhibhūta; the Puruṣa is adhidaiva; and I myself am adhiyajña in the body.”"),
5: ("Whoever, at the end, leaves the body remembering me alone — he attains my being; there is no doubt of this.",
    "“Whoever leaves the body thinking of me alone comes to my very being — of this there is no doubt.”"),
6: ("Whatever state one remembers at the end while leaving the body — to that state one goes, ever pervaded by that thought.",
    "“Whatever you think of at the final hour — that is what you become, shaped by that last thought.”"),
7: ("Therefore remember me at all times and fight; with mind and intellect offered to me, you will surely come to me, without doubt.",
    "“So remember me always and fight! With mind and heart given to me, you will surely reach me.”"),
8: ("United with the yoga of practice, with a mind that goes nowhere else — one reaches the supreme divine Person, contemplating him.",
    "“Practising with a one-pointed mind, meditating on the supreme divine Person, the yogi reaches him.”"),
9: ("He who meditates on the ancient seer, the ruler, subtler than the subtle, the support of all, of inconceivable form, radiant as the sun, beyond darkness —",
    "“Hold your mind on the ancient one: finer than anything fine, the ground that carries everything, past imagining, glowing like the sun on the far side of all darkness —”"),
10: ("— at the time of death, with an unwavering mind, united with devotion and the power of yoga, breath fixed between the brows — he reaches that supreme divine Person.",
    "“— at death, with a steady mind, devotion, and yogic power, breath held between the brows — reaches that supreme divine Person.”"),
11: ("That which the knowers of the Vedas call the imperishable, which the desireless ascetics enter, desiring which they practise celibacy — that goal I shall declare to you briefly.",
    "“The imperishable that the Vedic sages declare, which desireless ascetics enter — that goal I will now tell you briefly.”"),
12: ("Restraining all the gates of the body, confining the mind in the heart, fixing the life-breath in the head, established in yogic concentration —",
    "“Shutting the body's gates, holding the mind in the heart, breath rising to the crown — established in yogic absorption —”"),
13: ("— uttering the single syllable Om, the Brahman, and remembering me — he who departs, giving up the body, reaches the supreme goal.",
    "“— chanting the single syllable Om, remembering me — whoever leaves the body thus reaches the supreme goal.”"),
14: ("He who always remembers me, with a single mind, ever — for that ever-yoked yogi I am easy to reach, O Pārtha.",
    "“One who remembers me always, with undivided mind — I am easy to reach for that ever-yoked yogi.”"),
15: ("Having reached me, the great souls do not return to birth — the abode of sorrow, impermanent — they have attained the highest perfection.",
    "“Reaching me, the great souls never return to this world of sorrow and change — they have reached the highest perfection.”"),
16: ("From the world of Brahmā down, all worlds return again, O Arjuna; but reaching me, O Kaunteya, there is no rebirth.",
    "“All worlds, even up to Brahmā's, revolve and return; but one who reaches me is never reborn.”"),
17: ("Those who know Brahmā's day to end in a thousand yugas, and the night to end in a thousand — they know day and night.",
    "“Those who know that a thousand ages make Brahmā's day, and a thousand his night — they know the divine measure of time.”"),
18: ("From the unmanifest all manifest things arise at the coming of day; at the coming of night they dissolve into the unmanifest.",
    "“At the dawn of Brahmā's day, all beings arise from the unmanifest; at his night, they dissolve back into it.”"),
19: ("This same host of beings, arising again and again, dissolves at the coming of night, and arises at the coming of day.",
    "“This multitude of beings, born again and again, melts away at night and reappears at daybreak.”"),
20: ("But beyond this unmanifest is another unmanifest, eternal — which, when all beings perish, does not perish.",
    "“Yet beyond this unmanifest is another, eternal unmanifest — which remains when all beings pass away.”"),
21: ("That unmanifest is called the imperishable; they call it the supreme goal; reaching which they do not return — that is my supreme abode.",
    "“That is the imperishable, the supreme goal. Reaching it, none returns — it is my highest abode.”"),
22: ("That supreme Person, O Pārtha, is attainable by devotion to him alone; in him all beings dwell, and by him all this is pervaded.",
    "“That supreme Person is reached by single-pointed devotion; all beings dwell in him, and he pervades everything.”"),
23: ("Now I shall declare, O bull of the Bhāratas, the time in which yogis, departing, do not return, and the time in which they return.",
    "“Now I will tell you, Arjuna, the times of departing — the path of no-return and the path of return.”"),
24: ("Fire, light, day, the bright fortnight, the six months of the northern course — departing by that path, the knowers of Brahman go to Brahman.",
    "“By the path of fire and light, of day and the bright fortnight and the northern course, the knowers of Brahman go to Brahman.”"),
25: ("Smoke, night, the dark fortnight, the six months of the southern course — attaining the lunar light by that path, the yogi returns.",
    "“By the path of smoke and night, of the dark fortnight and the southern course, the yogi reaches the lunar light and returns.”"),
26: ("These two paths, bright and dark, are the eternal paths of the world; by one, one goes without return, by the other one returns again.",
    "“These two paths — bright and dark — are eternal in this world. One leads to no-return, the other brings return.”"),
27: ("Knowing these two paths, O Pārtha, the yogi is never deluded; therefore, at all times be united in yoga, O Arjuna.",
    "“Knowing both paths, the yogi is never confused — so remain steadfast in yoga at all times, Arjuna.”"),
28: ("Whatever fruit of merit is declared in the Vedas, sacrifices, austerities and gifts — the yogi, knowing all this, transcends it all and reaches the supreme primeval abode.",
    "“The yogi who knows this truth surpasses all the merit of Vedas, sacrifice, austerity and charity — and reaches the supreme, primeval abode.”"),
}
