# -*- coding: utf-8 -*-
"""gita_data12.py — Chapter 12 (Bhakti Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH12_THEMES = [
    ("The Question",
     "Who knows yoga better — those who worship the manifest with devotion, or those who worship the imperishable Unmanifest?",
     [("Which Knows Yoga Better?", "Those devotees who, ever steadfast, worship you thus, and those who worship the imperishable Unmanifest — which of them has the better knowledge of yoga?", "12.01", "12.01"),
      ("Those Ever-Steadfast Who Worship Me", "Those who fix their minds on me and worship me, ever steadfast and endowed with supreme faith — them I hold to be the most perfect in yoga.", "12.02", "12.02")]),
    ("The Unmanifest Path",
     "Those who worship the imperishable, unthinkable and immovable also reach me — but greater is their toil.",
     [("Those Who Worship the Imperishable", "But those who worship the imperishable, the indefinable, the unmanifest, the all-pervading, unthinkable, unchanging, immovable and eternal — restraining all the senses, even-minded everywhere, rejoicing in the welfare of all beings, they too attain me.", "12.03", "12.04"),
      ("Greater Is the Toil of Those Set on the Unmanifest", "Greater is their trouble whose minds are set on the Unmanifest; for the goal of the Unmanifest is hard for the embodied to reach.", "12.05", "12.05")]),
    ("I Swiftly Deliver Them",
     "For those who surrender all actions to me and meditate on me, I become the deliverer from the ocean of death and rebirth.",
     [("Those Who Surrender All to Me", "But those who, renouncing all actions in me and intent on me, worship me with single-minded yoga and meditate on me —", "12.06", "12.06"),
      ("I Become Their Deliverer From the Ocean of Death", "— for them, whose minds are set on me, I become before long the deliverer from the ocean of death and rebirth, O Pārtha.", "12.07", "12.07"),
      ("Fix Your Mind on Me Alone", "Fix your mind on me alone, place your intellect in me; then you shall dwell in me hereafter — of this there is no doubt.", "12.08", "12.08")]),
    ("If You Cannot",
     "The ladder of concession: if not steady meditation, then practice; if not practice, then work for me; if not that, then renounce the fruit.",
     [("Then Seek Me by Repeated Practice", "If you cannot fix your mind steadily on me, then seek to reach me by the yoga of repeated practice, O Dhanañjaya.", "12.09", "12.09"),
      ("If Not, Work for My Sake", "If you are unable even to practise, be intent on doing work for me; even performing actions for my sake, you shall attain perfection.", "12.10", "12.10"),
      ("If Not Even That, Renounce the Fruit", "If you are unable to do even this, then take refuge in union with me and renounce the fruit of all action, with the self restrained.", "12.11", "12.11"),
      ("Better Than Knowledge Is Renunciation of Fruit", "Better indeed is knowledge than practice; better than knowledge is meditation; better than meditation is the renunciation of the fruit of action — from renunciation peace follows immediately.", "12.12", "12.12")]),
    ("He Who Is Dear to Me",
     "The portrait of the devotee: hating no being, friendly and compassionate, undisturbed by the world and not disturbing it.",
     [("Hating No Being, Friendly and Compassionate", "He who hates no being, who is friendly and compassionate, free from possessiveness and egoism, the same in pleasure and pain, forgiving — ever content, steady in meditation, self-controlled, of firm conviction, with mind and intellect given to me: that devotee of mine is dear to me.", "12.13", "12.14"),
      ("He by Whom the World Is Not Disturbed", "He by whom the world is not troubled and who is not troubled by the world, who is free from joy, envy, fear and anxiety — he is dear to me.", "12.15", "12.15"),
      ("Unattached, Pure, Capable, Untroubled", "He who is free from wants, pure, capable, unconcerned, untroubled, renouncing every undertaking — he who is thus devoted to me is dear to me.", "12.16", "12.16")]),
    ("Equal in All Things",
     "Neither rejoicing nor hating, equal to friend and foe, honour and dishonour — such a devotee is exceedingly dear to me.",
     [("Neither Rejoicing Nor Hating", "He who neither rejoices nor hates, neither grieves nor desires, who has renounced good and evil, and is full of devotion — he is dear to me.", "12.17", "12.17"),
      ("Equal to Friend and Foe, Honour and Dishonour", "He who is the same to foe and friend, in honour and dishonour, in cold and heat, in pleasure and pain, free from attachment — alike in blame and praise, silent, content with anything, homeless, steady in mind, full of devotion: that man is dear to me.", "12.18", "12.19"),
      ("They Who Follow This Immortal Dharma Are Dearest", "But those who follow this immortal dharma as declared above, endowed with faith, holding me as the supreme goal — those devotees are exceedingly dear to me.", "12.20", "12.20")]),
]

CH12_TRANSLATIONS = {
1: ("Arjuna said: Those devotees who, ever united, worship you — and those who worship the imperishable unmanifest — which of these are the better knowers of yoga?",
    "Arjuna asks: “Which are the greater yogis — those who worship you with devotion, or those who worship the formless, imperishable Absolute?”"),
2: ("The Blessed Lord said: Those who, fixing their minds on me, ever united, worship me with supreme faith — them I deem the most yoked.",
    "Kṛṣṇa said: “Those who fix their minds on me, ever devoted, worshipping me with supreme faith — they are the greatest yogis in my view.”"),
3: ("But those who worship the imperishable, the indefinable, the unmanifest — the all-pervading, unthinkable, unchanging, immovable, eternal —",
    "“But those who worship the unmanifest — indefinable, all-pervading, unthinkable, immutable, eternal —”"),
4: ("— controlling all the senses, of equal mind everywhere, rejoicing in the welfare of all beings — they too reach me.",
    "“— who restrain the senses, see all equally, and delight in the good of all beings — they also reach me.”"),
5: ("Greater is the toil of those whose minds are attached to the unmanifest; the unmanifest is hard to attain by embodied beings.",
    "“But their struggle is greater, for the formless Absolute is hard to reach for those who dwell in bodies.”"),
6: ("But those who surrender all actions to me, intent on me, worshipping me with undivided yoga and meditating on me,",
    "“But those who offer all their actions to me, take me as supreme, and worship me with single-minded meditation,”"),
7: ("— for them, whose minds are fixed on me, O Pārtha, I swiftly become the deliverer from the ocean of death and rebirth.",
    "“— for them, whose hearts rest in me, I quickly become their saviour from the ocean of birth and death.”"),
8: ("Fix your mind on me alone; establish your intellect in me; then you shall live in me alone — of this there is no doubt.",
    "“Rest your mind and understanding on me alone — and you will surely live in me; of this there is no doubt.”"),
9: ("If you cannot fix your mind steadily on me, then practise the yoga of repetition — seek to reach me by practice, O Dhanañjaya.",
    "“If you cannot fix your mind on me steadily, then use repeated practice to reach me, Arjuna.”"),
10: ("If you are unable to practise even that, be devoted to working for me; even performing actions for my sake, you shall attain perfection.",
    "“If even that is beyond you, devote yourself to working for me — doing your work for my sake, you will reach perfection.”"),
11: ("If you cannot do even this, then, taking refuge in my yoga, renounce the fruit of all actions — with the self controlled.",
    "“If you cannot do even that, then surrender the fruits of all your actions to me — with a self-controlled mind.”"),
12: ("Better indeed is knowledge than practice; better than knowledge is meditation; better than meditation is renunciation of the fruit of action — for from renunciation comes peace, immediately.",
    "“Knowledge is better than practice; meditation is better than knowledge; and better still is renouncing the fruits of work — for that brings peace at once.”"),
13: ("He who hates no being, is friendly and compassionate, free from possessiveness and ego, equal in pleasure and pain, forgiving —",
    "“One who hates no one, is kind and compassionate, free of 'mine' and 'I', even in joy and sorrow, patient —”"),
14: ("— ever content, a yogi, self-controlled, of firm resolve, mind and intellect offered to me — that devotee of mine is dear to me.",
    "“— always content, self-mastered, resolute, with mind and heart given to me — such a devotee is dear to me.”"),
15: ("He by whom the world is not disturbed, and who is not disturbed by the world — freed from joy, anger, fear and anxiety — he is dear to me.",
    "“One who disturbs no one and is disturbed by no one, free from joy, anger, fear, and worry — he is dear to me.”"),
16: ("He who is unattached, pure, capable, indifferent, free from anxiety, renouncing all undertakings — that devotee of mine is dear to me.",
    "“One who is detached, pure, skilled, neutral, worry-free, and gives up all selfish projects — that devotee is dear to me.”"),
17: ("He who neither rejoices nor hates, neither grieves nor desires, renouncing good and evil — that devoted one is dear to me.",
    "“One who neither delights nor despairs, neither mourns nor craves, letting go of good and evil — such a devotee is dear to me.”"),
18: ("Equal to friend and foe, to honour and dishonour, to cold and heat, pleasure and pain, free from attachment —",
    "“Equal toward friend and enemy, praise and blame, cold and heat, joy and sorrow, free from clinging —”"),
19: ("— silent, content with anything, homeless, of steady mind, full of devotion — that man is dear to me.",
    "“— silent, satisfied with whatever comes, unattached to place, steady-minded, devoted — such a person is dear to me.”"),
20: ("But those who follow this immortal dharma, as declared, with faith, making me the supreme goal — those devotees are exceedingly dear to me.",
    "“But those who follow this deathless dharma with faith, holding me as the highest goal — such devotees are most dear to me of all.”"),
}
