# -*- coding: utf-8 -*-
"""gita_data13.py — Chapter 13 (Kṣetra-Kṣetrajña-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH13_THEMES = [
    ("The Field and the Knower",
     "Kṛṣṇa opens the teaching: the body is the field, the knower of the field is the Self — and the knowledge of both is true knowledge.",
     [("The Body Is the Field", "This body, O Kaunteya, is called the field; he who knows it, the sages call the knower of the field.", "13.01", "13.01"),
      ("Know Me as the Knower", "Know me as the knower of the field in all fields; the knowledge of field and knower is my true knowledge.", "13.02", "13.02")]),
    ("What the Field Is",
     "Kṛṣṇa will describe the field — its nature, modifications and source; the seers have sung it in many ways.",
     [("I Shall Declare", "Hear from me in brief what the field is, what it is like, its modifications and source — and who he is and his powers.", "13.03", "13.03"),
      ("Sung by the Seers", "The seers have sung it in many ways, in diverse meters — and in the aphorisms of Brahman, well-reasoned and certain.", "13.04", "13.04")]),
    ("The Twenty-Four Constituents",
     "The field comprises the great elements, ego, intellect, the unmanifest, the senses, and their objects — and desire, aversion, pleasure and pain.",
     [("The Elements of the Field", "The great elements, ego, intellect, the unmanifest, the ten senses and the one, and the five objects of the senses.", "13.05", "13.05"),
      ("Desire and Aversion", "Desire, aversion, pleasure, pain, the body, consciousness and constancy — this, in brief, is the field with its modifications.", "13.06", "13.06")]),
    ("The Means of Knowledge",
     "Humility, non-violence, service to the teacher, purity, steadfastness, dispassion, absence of ego, and constant meditation — these are declared knowledge.",
     [("The Virtues", "Humility, modesty, non-violence, forbearance, uprightness, service to the teacher, purity, steadfastness, self-control,", "13.07", "13.08"),
      ("Non-attachment and Evenness", "— non-attachment, non-clinging to son, wife and home, and constant even-mindedness toward whatever comes, welcome or unwelcome,", "13.09", "13.09"),
      ("Devotion, Solitude, Self-Knowledge", "— unwavering devotion to me, a love of solitude, no taste for crowds, constant commitment to Self-knowledge and insight into the purpose of truth: all this is knowledge; the rest is ignorance.", "13.10", "13.11")]),

    ("The Knowable",
     "Kṛṣṇa declares the knowable: Brahman, beginningless, beyond being and non-being — the supreme reality.",
     [("The Knowable Declared", "I will declare the object of knowledge, knowing which one tastes immortality — the beginningless supreme Brahman, called neither being nor non-being.", "13.12", "13.12")]),
    ("The Omnipresent Lord",
     "Brahman is all-hands and all-feet, all-eyes, all-heads, all-ears — pervading all, without senses yet sensing all, unattached yet upholding all.",
     [("All Hands, All Feet", "With hands and feet everywhere, eyes, heads and faces everywhere, ears everywhere — it stands, pervading all in the world.", "13.13", "13.14"),
      ("Within and Without, Far and Near", "It is within and without all beings, unmoving and yet moving; so subtle it cannot be known — far away, and at the same time near.", "13.15", "13.15"),
      ("Undivided in the Divided", "Undivided, yet appearing divided among beings; know it as the sustainer of beings, and as the one that devours and brings forth.", "13.16", "13.16")]),
    ("The Imperishable Light",
     "The light of lights, beyond all darkness, seated in the heart of every being — and with that, the field, knowledge and the knowable stand declared.",
     [("The Light of Lights", "The light of all lights, said to be beyond darkness — knowledge, the object of knowledge, the goal of knowledge — seated in the heart of every being.", "13.17", "13.17"),
      ("The Field, Knowledge and the Knowable", "The field, knowledge and the knowable have now been told in brief; my devotee, understanding this, enters into my being.", "13.18", "13.18")]),
    ("Prakṛti and Puruṣa",
     "Kṛṣṇa declares prakṛti and puruṣa as beginningless; the guṇas arise from prakṛti, and it is the cause of agency, while puruṣa is the enjoyer.",
     [("The Two Beginningless", "Prakṛti and puruṣa are both beginningless, know this; the modifications and the guṇas arise from prakṛti.", "13.19", "13.19"),
      ("Agency and Enjoyment", "Prakṛti is said to be the cause of agency in action; puruṣa is said to be the cause of the enjoyment of pleasure and pain.", "13.20", "13.20"),
      ("The Enjoyer in Prakṛti", "Puruṣa, seated in prakṛti, enjoys the guṇas born of prakṛti; attachment to the guṇas is the cause of birth in good and evil wombs.", "13.21", "13.21")]),
    ("The Supreme Puruṣa",
     "The one who knows this supreme puruṣa — witness, sustainer, enjoyer, great Lord, the supreme Self — is never born again.",
     [("The Witness and Lord", "The witness, the approver, the sustainer, the enjoyer, the great Lord — and called the supreme Self, this supreme puruṣa in the body.", "13.22", "13.22"),
      ("Beyond Rebirth", "He who thus knows puruṣa and prakṛti with its guṇas — whatever his way of life, he is born no more.", "13.23", "13.23")]),
    ("The Ways to Knowledge",
     "Some see the Self in themselves by meditation, others by knowledge, others by karma-yoga; and those who do not know hear from others and cross beyond death.",
     [("The Three Paths", "Some see the Self within themselves through meditation; others through the yoga of knowledge; still others through the yoga of action.", "13.24", "13.24"),
      ("The Path of Hearing", "Others, not knowing, worship after hearing from others — and they too cross beyond death, devoted to what they have heard.", "13.25", "13.25")]),
    ("The One in the Many",
     "Whatever being arises, moving or unmoving, comes from the union of field and knower; he who sees the Lord equally present, imperishable, truly sees.",
     [("All from the Union", "Whatever being is born, moving or unmoving — know it to be from the union of the field and its knower, O bull of the Bhāratas.", "13.26", "13.26"),
      ("Equal Vision", "He who sees the supreme Lord standing equally in all beings, not perishing as they perish — he truly sees.", "13.27", "13.28")]),
    ("The Akartā Attainment",
     "He who sees that all actions are done by prakṛti and the Self as non-doer — and sees the one in the many — attains Brahman.",
     [("Prakṛti Acts", "He who sees that all actions are performed by prakṛti, and the Self as the non-doer — he truly sees.", "13.29", "13.29"),
      ("The One in the Many", "When he sees the manifold states of beings resting in the One and spread out from it alone — then he attains Brahman.", "13.30", "13.30")]),
    ("The Unstained Self",
     "Because it is beginningless and without guṇas, the supreme Self is imperishable; like space, it is not stained by the body.",
     [("Beyond Guṇas", "Because it is beginningless and without guṇas, this supreme Self is imperishable — though it dwells in the body, it neither acts nor is stained.", "13.31", "13.31"),
      ("As Space Is Unstained", "As the all-pervading space is not stained by subtlety, so the Self, present in every body, is not stained.", "13.32", "13.32")]),
    ("The Light of the Field",
     "As the sun illumines the whole world, the knower of the field illumines the whole field; those who see this distinction reach the supreme.",
     [("The Sun and the Field", "As the one sun illumines this whole world, so the knower of the field illumines the whole field, O Bhārata.", "13.33", "13.33"),
      ("The Final Vision", "Those who, with the eye of knowledge, see the distinction between field and knower, and the liberation from prakṛti — they reach the supreme.", "13.34", "13.34")]),
]

CH13_TRANSLATIONS = {
1: ("The Blessed Lord said: This body, O son of Kuntī, is called the field; he who knows it, the wise call the knower of the field.",
    "Kṛṣṇa said: “This body is called the field; one who knows it is called the knower of the field.”"),
2: ("Know me also as the knower of the field in all fields, O Bhārata; the knowledge of the field and its knower is deemed by me true knowledge.",
    "“Know me as the knower of the field in every body; the wisdom of the field and its knower is what I call real knowledge.”"),
3: ("What the field is, what it is like, what its modifications, from what it arises, and who he is and what his powers — hear all this from me in brief.",
    "“Hear from me, in brief, what the field is, its nature, its changes, its source — and who the knower is and what his powers are.”"),
4: ("Sung by the seers in many ways, in diverse meters, and in the aphorisms of Brahman, with reasons, well-decided —",
    "“The sages have sung it in many ways, in varied meters, and in the Brahman-sūtras, with reasoning, decisively —”"),
5: ("— the great elements, ego, intellect, the unmanifest, the ten senses and the one, the five objects of the senses,",
    "“— the great elements, ego, intellect, the unmanifest, the ten senses plus mind, and the five sense-objects,”"),
6: ("— desire, aversion, pleasure, pain, the body, consciousness and constancy: this is the field, in brief, with its modifications.",
    "“— desire, dislike, joy, sorrow, the body itself, awareness and steadiness: this, briefly, is the field with all its changes.”"),
7: ("Humility, modesty, non-violence, forbearance, uprightness, service to the teacher, purity, steadfastness, self-control,",
    "“Humility, modesty, harmlessness, patience, honesty, serving one's teacher, purity, firmness, self-mastery,”"),
8: ("— dispassion toward the objects of the senses, absence of ego, and the perception of the evil of birth, death, old age and disease,",
    "“— disinterest in sense-pleasures, no ego, and the clear seeing of the misery of birth, death, age, and sickness,”"),
9: ("— non-attachment, non-clinging to son, wife and home, constant even-mindedness toward gain and loss,",
    "“— detachment, no clinging to family and home, steady even-mindedness in success and failure,”"),
10: ("— unwavering devotion to me through undivided yoga, delight in solitude, distaste for the company of men,",
    "“— unwavering devotion to me with single-pointed yoga, fondness for solitude, distaste for worldly crowds,”"),
11: ("— constant commitment to Self-knowledge, and insight into the purpose of the knowledge of truth: this is declared knowledge; what is other than this is ignorance.",
    "“— constant pursuit of knowledge of the Self, and seeing the aim of truth-knowledge: this is called knowledge; anything else is ignorance.”"),
12: ("I shall declare the object of knowledge, knowing which one tastes immortality — the beginningless supreme Brahman, which is called neither being nor non-being.",
    "“I will tell you of the knowable, knowing which you taste immortality — the beginningless supreme Brahman, beyond being and non-being.”"),
13: ("With hands and feet everywhere, with eyes, heads and faces everywhere, with ears everywhere — it stands, pervading all in the world.",
    "“It has hands and feet on every side, eyes, heads, and faces everywhere, ears everywhere — it stands embracing all.”"),
14: ("Appearing with all the attributes of the senses, yet devoid of all senses; unattached, yet upholding all; without guṇas, yet enjoying the guṇas.",
    "“It appears to have all the senses' qualities, yet has no senses; it is unattached, yet supports all; beyond the guṇas, yet enjoys them.”"),
15: ("It is within and without all beings; it is unmoving and moving; being subtle, it is unknowable — it is far away, and yet near.",
    "“It is inside and outside all beings; unmoving and moving; too subtle to grasp — far away, and yet close at hand.”"),
16: ("It is undivided, yet appears as if divided among beings; know it as the supporter of beings, the devourer and the creator.",
    "“Undivided, it appears divided among beings; know it as the sustainer of all, the devourer, and the source.”"),
17: ("It is the light of lights, declared beyond darkness — knowledge, the object of knowledge, and the goal of knowledge, seated in the heart of all.",
    "“It is the light of all lights, beyond darkness — wisdom itself, its object, and its goal, dwelling in every heart.”"),
18: ("Thus the field, knowledge and the knowable have been declared in brief; my devotee, knowing this, attains my being.",
    "“So I have told you, in brief, of the field, knowledge, and the knowable; my devotee who understands this reaches my state.”"),
19: ("Know prakṛti and puruṣa both as beginningless; and know the modifications and the guṇas as born of prakṛti.",
    "“Know that nature and the person are both beginningless; and that all changes and qualities arise from nature.”"),
20: ("Prakṛti is declared the cause of agency in bringing about the effect; puruṣa is declared the cause of the enjoyment of pleasure and pain.",
    "“Nature is the cause of doing; the person is the cause of experiencing joy and sorrow.”"),
21: ("Puruṣa, seated in prakṛti, enjoys the guṇas born of prakṛti; attachment to the guṇas is the cause of birth in good and evil wombs.",
    "“The person, resting in nature, tastes the qualities born of nature; clinging to those qualities causes birth in high or low wombs.”"),
22: ("The witness, the approver, the sustainer, the enjoyer, the great Lord — and called the supreme Self: this supreme puruṣa in the body.",
    "“The witness, the sanctioner, the sustainer, the enjoyer, the great Lord — called the supreme Self: this is the highest Person in the body.”"),
23: ("He who thus knows puruṣa and prakṛti with its guṇas — whatever his way of life, he is not born again.",
    "“One who knows this Person and nature with its qualities — however he lives, he is never reborn.”"),
24: ("Some see the Self within themselves by meditation; others by the yoga of knowledge; still others by the yoga of action.",
    "“Some see the Self within by meditation; others by wisdom; still others by selfless action.”"),
25: ("Others, not knowing, worship after hearing from others; and they too cross beyond death, devoted to what they have heard.",
    "“Others, not knowing directly, worship after hearing from teachers — and they too cross beyond death by faith in the heard teaching.”"),
26: ("Whatever being is born, moving or unmoving — know it, O bull of the Bhāratas, to be from the union of the field and its knower.",
    "“Whatever comes into being, moving or still — know it arises from the union of the field and its knower, Arjuna.”"),
27: ("He who sees the supreme Lord standing equally in all beings, not perishing as they perish — he truly sees.",
    "“One who sees the supreme Lord equally present in all beings, undying among the dying — he truly sees.”"),
28: ("For seeing the Lord equally established everywhere, he does not harm the Self by the self; therefore he attains the supreme goal.",
    "“Seeing the Lord equally in all, he never degrades his Self; and so he reaches the highest goal.”"),
29: ("He who sees that all actions are performed by prakṛti, and the Self as the non-doer — he truly sees.",
    "“One who sees that all actions are done by nature, and the Self as the non-doer — he truly sees.”"),
30: ("When he sees the manifold states of beings resting in the One and spread out from it alone — then he attains Brahman.",
    "“When he sees all the varied states of beings resting in the One and arising from it alone — then he becomes Brahman.”"),
31: ("Because it is beginningless and without guṇas, this supreme Self is imperishable — though dwelling in the body, it neither acts nor is stained.",
    "“Being beginningless and beyond all qualities, the supreme Self is eternal — though it dwells in the body, it neither acts nor is tainted.”"),
32: ("As the all-pervading space is not stained, being subtle, so the Self, present in every body, is not stained.",
    "“As space, though pervading all, is never tainted, so the Self present in every body is never tainted.”"),
33: ("As the one sun illumines this whole world, so the knower of the field illumines the whole field, O Bhārata.",
    "“As one sun lights up the entire world, so the knower of the field illumines the whole field, Arjuna.”"),
34: ("Those who, with the eye of knowledge, see the distinction between the field and its knower, and the liberation from prakṛti — they reach the supreme.",
    "“Those who, with the eye of wisdom, discern the difference between the field and its knower, and the freedom from nature — they attain the highest.”"),
}
