# -*- coding: utf-8 -*-
"""gita_data2.py — Chapter 2 (Sāṅkhya Yoga) themes and translations (literal + paraphrase)."""

# Theme structure: (title, desc, [(part_title, part_desc, start, end), ...])
CH2_THEMES = [
    ("Kṛṣṇa rebukes Arjuna's weakness",
     'Whence has this dejection come in the hour of peril? Cast off faintness of heart and arise.',
     [
      ("The Lord's rebuke", "Seeing Arjuna overcome with pity, his eyes full of tears and agitation, Kṛṣṇa speaks.", '2.01', '2.01'),
      ('Where has this weakness come from?', 'Kṛṣṇa asks: where has this dejection come from, at this hour of crisis? It is ignoble and heaven-barred.', '2.02', '2.02'),
      ('Cast off this faintness and arise', 'Do not yield to this impotence, Arjuna; shake it off and stand up, Scorcher of the Enemy.', '2.03', '2.03'),
     ]),
    ('How can I strike Bhīṣma and Droṇa?',
     'How can I strike men worthy of worship? Better to live on alms than to taste pleasures stained with blood.',
     [
      ('Bhīṣma and Droṇa', "How can I strike Bhīṣma and Droṇa with arrows in battle, O Madhusūdana — they who are worthy of worship?", '2.04', '2.04'),
      ('Better to beg', 'It would be better to live on alms in this world than to kill these revered elders.', '2.05', '2.05'),
      ('We cannot tell which is better', 'Victory or defeat — we cannot tell which is better; the sons of Dhṛtarāṣṭra stand before us.', '2.06', '2.06'),
     ]),
    ('Teach Me, I Am Your Disciple',
     'My nature is overcome, my mind confused about duty — I take refuge in you: teach me.',
     [
      ('Teach me, I am your disciple', 'My nature is overcome, my mind confused about duty — I take refuge in you: teach me.', '2.07', '2.07'),
      ('I will not fight', 'No kingdom on earth or lordship over the gods could drive away this grief; Arjuna falls silent.', '2.08', '2.08'),
      ('I will not fight, he said', "Declaring 'I will not fight,' Arjuna fell silent before Kṛṣṇa.", '2.09', '2.09'),
     ]),
    ('Kṛṣṇa smiles and begins to teach',
     'Between the two armies, as if smiling, Hṛṣīkeśa begins to speak.',
     [
      ('Kṛṣṇa smiles and begins to speak', 'Between the two armies, as if smiling, Hṛṣīkeśa begins to speak.', '2.10', '2.10'),
     ]),
    ('Never Was There a Time',
     'You grieve for those who need no grief; never was there a time when we did not exist.',
     [
      ('You mourn for the unmournable', 'You grieve for those who deserve no grief, yet speak like the learned; the wise grieve neither for the living nor the dead.', '2.11', '2.11'),
      ('Never was there a time', 'You grieve for those who need no grief; never was there a time when we did not exist.', '2.12', '2.12'),
      ('Childhood, youth, old age', 'As the embodied one passes through the ages of the body, so it passes into another body.', '2.13', '2.13'),
     ]),
    ('Cold and Heat Come and Go',
     'Sense-contacts bring heat and cold, pleasure and pain — impermanent; endure them.',
     [
      ('Cold and heat come and go', 'Sense-contacts bring heat and cold, pleasure and pain — impermanent; endure them.', '2.14', '2.14'),
      ('The sage stays even-minded', 'Joy and sorrow come and go; the sage whom these cannot shake attains immortality.', '2.15', '2.15'),
     ]),
    ('The Real Never Ceases',
     'The unreal has no being, the real never ceases; these bodies end, but the imperishable embodied Self does not — therefore fight.',
     [
      ('The unreal has no being', 'The unreal has no being, the real never ceases; seers of the essence have seen the truth of both.', '2.16', '2.16'),
      ('The imperishable pervades all', 'Know that to be indestructible which pervades all this; no one can destroy the inexhaustible.', '2.17', '2.17'),
      ('The bodies end, the Self does not', 'The bodies of the eternal, imperishable Self come to an end; therefore fight, Bhārata.', '2.18', '2.18'),
     ]),
    ('Neither Slays Nor Is Slain',
     'Whoever thinks the Self slays or is slain — neither knows; it neither kills nor is killed.',
     [
      ('Neither kills nor is killed', 'Whoever thinks the Self slays, and whoever thinks it is slain — neither knows.', '2.19', '2.19'),
      ('It is never born, never dies', 'Unborn, eternal, everlasting, ancient — it is not slain when the body is slain.', '2.20', '2.20'),
      ('Who then can kill, or cause killing?', 'Knowing the Self imperishable and unborn — how can any man kill, or cause to kill?', '2.21', '2.21'),
     ]),
    ('As Clothes, So Bodies',
     'As one casts off worn clothes, so the Self casts off worn bodies; weapons cut it not, fire burns it not — unmanifest, unthinkable, unchanging.',
     [
      ('As one casts off worn-out clothes', 'As a man puts on new garments, so the embodied Self enters new bodies.', '2.22', '2.22'),
      ('No weapon cuts the Self', 'Fire does not burn it, water does not wet it, wind does not dry it; eternal, all-pervading, immovable.', '2.23', '2.23'),
      ('The Self is eternal and unmoving', 'The Self cannot be cut, burnt, wetted or dried — eternal, all-pervading, immovable.', '2.24', '2.24'),
      ('Unmanifest and unthinkable', 'Unmanifest, unthinkable, unchanging — knowing it thus, you have no cause to grieve.', '2.25', '2.25'),
     ]),
    ('No Cause to Grieve',
     'Death is certain for the born, birth for the dead; the embodied Self is eternally inviolable — therefore grieve for no being.',
     [
      ('Even then you should not grieve', "Even if you hold the Self to be perpetually born and perpetually dying, O mighty-armed, even then you should not grieve.", '2.26', '2.26'),
      ('Birth and death are certain', 'Whoever is born must die; whoever dies must be born again; why grieve over the inevitable?', '2.27', '2.27'),
      ('Unmanifest beginning and end', 'Beings are unmanifest before, manifest between, unmanifest again — what is there to lament?', '2.28', '2.28'),
      ('A wonder to behold', 'One sees it as a wonder, another speaks of it so — and even having heard, no one truly knows it.', '2.29', '2.29'),
      ('Grieve for no being', 'The embodied Self in every body is eternally inviolable; grieve for no creature.', '2.30', '2.30'),
     ]),
    ('Nothing Better Than a Righteous War',
     'For a kṣatriya there is no greater good; blessed are those to whom such a war comes unsought.',
     [
      ('Nothing better than a righteous war', 'Look to your own dharma and do not waver: for a kṣatriya nothing is better than a righteous war.', '2.31', '2.31'),
      ('An open gate to heaven', 'Fortunate the warriors who meet such a war — an open gate to heaven.', '2.32', '2.32'),
     ]),
    ('Disgrace Is Worse Than Death',
     'Refusing this war, you abandon dharma and glory and incur sin; for the honoured, disgrace is worse than death.',
     [
      ('Disgrace is worse than death', 'Refusing this war, you abandon dharma and glory and incur sin; for the honoured, disgrace is worse than death.', '2.33', '2.33'),
      ('Your lasting shame', 'The world will spread word of your lasting shame; honour turns away from you.', '2.34', '2.34'),
      ('What the warriors will say', 'The great chariot-warriors will think you fled in fear; your enemies will slander your strength.', '2.35', '2.35'),
      ('Words that should never be said', 'Your foes will mock your courage with words that should never be said; what could be more painful?', '2.36', '2.36'),
     ]),
    ('Slain you win heaven, victorious the earth',
     'Killed, you gain heaven; victorious, you enjoy the earth — therefore arise, resolved to fight.',
     [
      ('Slain, you win heaven', 'Killed, you gain heaven; victorious, you enjoy the earth — therefore arise, resolved to fight.', '2.37', '2.37'),
      ('Make pleasure and pain the same', 'Holding gain and loss, victory and defeat alike, fight — and you will incur no sin.', '2.38', '2.38'),
     ]),
    ('Now hear the wisdom of yoga',
     'The sāṅkhya has been declared; now the yoga of action — by which no effort is ever lost and even a little of this dharma protects from great fear.',
     [
      ('Now hear the wisdom of Yoga', 'The wisdom of sāṅkhya has been declared; joined with yoga, you will cast off the bondage of karma.', '2.39', '2.39'),
      ('No effort is ever lost', 'Here no effort is wasted and no contrary result follows; even a little of this dharma protects from great fear.', '2.40', '2.40'),
     ]),
    ('One-pointed, or endlessly branching',
     'The single mark of the resolute: one intellect, one aim. The irresolute mind divides itself without end.',
     [
      ('One-Pointed or endlessly branching', 'The intellect of the resolute is single; the intellects of the irresolute branch out endlessly.', '2.41', '2.41'),
     ]),
    ('The flowery words of the Veda-lovers',
     'Those who take ritual and enjoyment for the whole of the Veda promise rebirth as the reward — and for such scattered minds the one-pointed samādhi never arises.',
     [
      ('The flowery words of the Vedas', 'Those addicted to ritual and enjoyment promise birth as fruit; for them the intellect of samādhi never arises.', '2.42', '2.42'),
      ('Full of craving, longing for heaven', 'Full of desire, longing for heaven, they promise rebirth and reward and urge elaborate rites for pleasure and power.', '2.43', '2.43'),
      ('No Samādhi for the scattered', 'Those clinging to pleasure and power, scattered by such words, find no one-pointed samādhi.', '2.44', '2.44'),
     ]),
    ('Rise above the three guṇas, Arjuna',
     'The command turned back on Arjuna: the Vedas treat of the three guṇas — go beyond them, free of the pairs of opposites, self-possessed.',
     [
      ('Rise above the three Guṇas', 'Be free from the pairs of opposites, ever in sattva; the Vedas serve the knower as a well serves a flooded land.', '2.45', '2.45'),
     ]),
    ('A well is little use in a flood',
     'The image that closes the argument: to the brāhmaṇa who knows, all the Vedas are worth as much as a well when water stands everywhere.',
     [
      ('The well and the flood', 'As a well in a flood is of use everywhere, so are all the Vedas to the brāhmaṇa who knows.', '2.46', '2.46'),
     ]),
    ('Your right is to action, never to its fruits',
     'The heart of karma-yoga: act because it is right, not for what it yields; and act established in evenness, the same in success and failure.',
     [
      ('Action alone, not the fruits', 'Your right is to action alone, never to its fruits; let not the fruit be your motive, nor cling to inaction.', '2.47', '2.47'),
      ('Evenness is called Yoga', 'Established in yoga, act with attachment cast off, the same in success and failure.', '2.48', '2.48'),
     ]),
    ('Take refuge in the intellect',
     'The turn from action to discernment: mere action is far inferior to buddhi-yoga. Take refuge in the intellect — and once it stands unmoved in samādhi, you have attained yoga.',
     [
      ('Yoga is skill in action', 'Action is far inferior to the yoga of discernment; take refuge in the intellect — yoga is skill in action.', '2.49', '2.49'),
      ('Skill in action, evenness of mind', 'Action with desire for fruit is far inferior; take refuge in evenness; the skillful abandon both good and bad fruit.', '2.50', '2.50'),
      ('Freed from the bonds of birth', 'The wise, renouncing the fruit of action, are released from birth and reach the place beyond all ill.', '2.51', '2.51'),
      ('Beyond the mire of delusion', 'When your intellect crosses the thicket of delusion and stands unmoved in samādhi, you will attain yoga.', '2.52', '2.52'),
      ('The mind stands fixed', "When the intellect, bewildered by the Vedas' words, stands fixed in samādhi — then you attain yoga.", '2.53', '2.53'),
     ]),
    ('What marks the man of steady wisdom?',
     "Arjuna asks how the sthitaprajña speaks, sits and moves; Kṛṣṇa answers: content in the Self alone, untroubled in sorrow, senses drawn in like a tortoise's limbs.",
     [
      ("Arjuna asks the marks of steady wisdom", 'What is the mark of the man of steady wisdom, established in samādhi?', '2.54', '2.54'),
      ('Content in the Self alone', 'Casting off all desires of the mind, content in the Self through the Self — untroubled in sorrow, unlonging in joy.', '2.55', '2.55'),
      ('The muni of steady wisdom', 'Whoever is unattached amid sorrows, free from craving amid pleasures — his wisdom is steady.', '2.56', '2.56'),
      ('Neither rejoicing nor recoiling', 'Without affection anywhere, meeting good and evil without delight or revulsion — that wisdom is firmly set.', '2.57', '2.57'),
      ('Like a tortoise drawing in its limbs', 'When the senses are withdrawn from their objects on every side, that wisdom is firmly set.', '2.58', '2.58'),
     ]),
    ('The taste remains until the Supreme is seen',
     'The subtler problem: objects fall away from the abstinent, but the relish for them lingers — and only on seeing the Supreme does even that go. Until then the senses carry off the mind by force.',
     [
      ('The taste remains', 'Objects fall away from the abstinent, but the relish lingers; seeing the Supreme, even that departs.', '2.59', '2.59'),
      ('The turbulent senses', 'Even for the striving sage the senses carry off the mind by force; restraining them, sit intent on Me.', '2.60', '2.60'),
      ('Reining in the senses', 'Reining in all the senses, the yogi sits devoted to Me; his wisdom is firm.', '2.61', '2.61'),
     ]),
    ('From brooding to ruin',
     'The ladder down: dwelling on objects breeds attachment, attachment desire, desire anger, anger delusion — and from the ruin of understanding, a man perishes.',
     [
      ('Brooding breeds desire, desire breeds anger', 'Dwelling on objects breeds attachment; from attachment desire; from desire anger.', '2.62', '2.62'),
      ('From anger, delusion — And ruin', 'From anger delusion, from delusion loss of memory, from that the ruin of understanding, and one perishes.', '2.63', '2.63'),
     ]),
    ('But the self-controlled attain serenity',
     'The reversal: one who moves among the same objects with the senses mastered, free of attraction and aversion, gains the peace in which all sorrow ends.',
     [
      ('The self-controlled attain serenity', 'Moving among objects with senses mastered, free from attraction and aversion, one gains serenity and all sorrows cease.', '2.64', '2.64'),
      ('In peace, all suffering ends', 'In that peace all suffering ends; the mind at peace soon rests in the Self.', '2.65', '2.65'),
      ('No peace, no happiness', 'For the undisciplined there is no wisdom, no meditation, no peace — and without peace, how can there be happiness?', '2.66', '2.66'),
      ('As wind carries a boat', 'The mind that follows the wandering senses carries off understanding as wind carries a boat on the waters.', '2.67', '2.67'),
      ('The senses fully drawn back', 'The one who has fully drawn the senses back from their objects — his wisdom is firm.', '2.68', '2.68'),
     ]),
    ('The brāhmī state at the hour of death',
     'As rivers enter the unmoved ocean, so desires enter the sage; free of longing and ego he attains peace — the Brāhmī state, the Brahman-nirvāṇa.',
     [
      ('Night for all beings', 'What is night for all beings is the waking of the disciplined sage, and their waking his night.', '2.69', '2.69'),
      ('As rivers enter the ocean', 'Desires enter the sage as waters enter the ocean, which is filled yet unmoved — he attains peace, not the lover of desires.', '2.70', '2.70'),
      ('Without longing, without ego', 'Abandoning all desires, moving free of craving, possessiveness and ego — that one attains peace.', '2.71', '2.71'),
      ('Reaching this, one is not deluded', 'This is the state of Brahman; attaining it one is not deluded — resting in it even at the end, one reaches Brahman-nirvāṇa.', '2.72', '2.72'),
     ]),
]

CH2_TRANSLATIONS = {
1: ("Sañjaya said: Seeing him thus overcome with pity, his eyes filled with tears and agitation, the sorrowing Arjuna — Madhusūdana spoke these words.",
    "Sañjaya narrates: “Seeing Arjuna drowning in pity, his eyes brimming with tears and agitation, Kṛṣṇa (Madhusūdana) addressed him as he grieved.”"),
2: ("The Blessed Lord said: Whence has come upon you, in this hour of peril, this dejection — unworthy of an Āryan, closing the door of heaven, and bringing disgrace, O Arjuna?",
    "Kṛṣṇa said: “Where has this weakness come from, Arjuna — at this very moment of crisis? It is unworthy of you, it shuts heaven's door, and it will bring you dishonour.”"),
3: ("Yield not to unmanliness, O Pārtha — it does not become you. Cast off this petty faintness of heart and arise, O scorcher of foes!",
    "“Do not give in to this cowardice, Arjuna — it ill becomes you. Shake off this small-hearted weakness, stand up, O burner of enemies!”"),
4: ("Arjuna said: How shall I strike Bhīṣma and Droṇa in battle with my arrows, O Madhusūdana — they who are worthy of worship, O slayer of foes?",
    "Arjuna asks: “How can I aim my arrows at Bhīṣma and Droṇa in war, Kṛṣṇa? They deserve my reverence, not my weapons.”"),
5: ("Better in this world to live on alms as a beggar than to slay these noble teachers. Killing them — even with worldly aims in view — I would taste only pleasures stained with blood.",
    "“It would be better to beg for food than to kill these revered elders. If I killed them for kingdom and enjoyment, I would taste only joys smeared with their blood.”"),
6: ("Nor do we know which is better for us — to conquer them or be conquered. The very sons of Dhṛtarāṣṭra stand before us; killing them, we should not care to live.",
    "“We cannot even tell which is preferable — victory or defeat. These sons of Dhṛtarāṣṭra stand before us, and after killing them we would not want to live.”"),
7: ("My nature is overcome by weak compassion; my mind is confused about duty. I ask you: tell me for certain what is good — I am your disciple; teach me, I have taken refuge in you.",
    "“Compassion has undone me and I am confused about what is right. Tell me plainly what is best. I am your student — guide me, for I have come to you for refuge.”"),
8: ("I do not see what could drive away this grief that dries up my senses — even if I won an unrivaled kingdom on earth or lordship over the gods.",
    "“Nothing I can see would remove this grief that parches my senses — not even an undivided kingdom of the earth, or rule over the gods themselves.”"),
9: ("Sañjaya said: Having spoken thus to Hṛṣīkeśa, Arjuna, the scorcher of foes, said to Govinda, 'I will not fight' — and fell silent.",
    "Sañjaya continues: “So saying to Kṛṣṇa, and declaring 'I will not fight,' Arjuna, the terror of his enemies, fell quiet.”"),
10: ("To him, as he grieved between the two armies, Hṛṣīkeśa, as if smiling, spoke these words, O descendant of Bharata.",
    "Sañjaya adds: “Then, O Dhṛtarāṣṭra, as Arjuna sat sorrowing between the two armies, Kṛṣṇa smiled and spoke to him.”"),
11: ("The Blessed Lord said: You grieve for those who should not be grieved for, yet speak words of wisdom. The wise grieve neither for the living nor for the dead.",
    "Kṛṣṇa said: “You mourn for those who deserve no mourning, and yet you talk like a sage. The wise mourn neither the living nor the dead.”"),
12: ("Never was there a time I did not exist, nor you, nor these rulers of men; nor will any of us ever cease to be hereafter.",
    "“There was never a time when I was not, nor you, nor these kings; and none of us will ever cease to be in the future.”"),
13: ("As the embodied soul passes in this body through childhood, youth and old age, so it passes into another body; the wise are not deluded by this.",
    "“Just as the Self within this body moves through childhood, youth, and old age, so it passes on to a new body at death. The wise are never confused by this.”"),
14: ("The contacts of the senses with their objects, O son of Kuntī, give cold and heat, pleasure and pain; they come and go, impermanent — endure them, O Bhārata.",
    "“Contact with the world brings cold and heat, joy and sorrow — these come and go, Arjuna; they are fleeting. Learn to endure them.”"),
15: ("The man whom these cannot disturb, O bull among men — the wise one who is equal in pleasure and pain — he is fit for immortality.",
    "“The person these cannot shake — the sage who stays even-minded in joy and pain — that one is worthy of immortality.”"),
16: ("The unreal has no being; the real never ceases to be. The truth of both is seen by the seers of the essence.",
    "“What is not real never truly exists; what is real never ceases. Those who see reality have understood the boundary between the two.”"),
17: ("Know that to be imperishable by which all this is pervaded. No one can bring about the destruction of that inexhaustible one.",
    "“Know that the One pervading all of this is indestructible. Nothing in existence can destroy that which is changeless.”"),
18: ("These bodies of the eternal, indestructible, immeasurable embodied Self are said to have an end; therefore fight, O Bhārata.",
    "“The bodies of the eternal, imperishable, immeasurable Self come to an end — but the Self does not. So fight, Arjuna.”"),
19: ("Whoever thinks the Self is the killer, and whoever thinks it is killed — neither truly knows: it does not kill, nor is it killed.",
    "“One who thinks the Self can kill, and one who thinks it can be killed, are both mistaken: the Self neither kills nor is killed.”"),
20: ("It is never born, never dies; having been, it will never again cease to be. Unborn, eternal, everlasting and ancient — it is not slain when the body is slain.",
    "“The Self is never born and never dies. Once it is, it never stops being. Unborn, eternal, timeless — it is not killed when the body is killed.”"),
21: ("Knowing this Self to be imperishable, eternal, unborn and inexhaustible — how, O Pārtha, can any man cause another to be killed, or kill?",
    "“When one knows the Self as indestructible, eternal, unborn, and inexhaustible — how can such a person kill anyone, or cause anyone to be killed?”"),
22: ("As a man casts off worn-out clothes and puts on new ones, so the embodied Self casts off worn-out bodies and enters new ones.",
    "“Just as a person sheds old garments and takes up fresh ones, so the Self sheds its worn-out bodies and takes on new ones.”"),
23: ("Weapons do not cut it, fire does not burn it, water does not wet it, wind does not dry it.",
    "“No weapon can cleave the Self, no fire burn it, no water drench it, no wind parch it.”"),
24: ("It cannot be cut, burned, wetted, or dried. Eternal, all-pervading, fixed, immovable, and everlasting is it.",
    "“The Self cannot be cut, burnt, wetted, or dried. It is eternal, omnipresent, stable, immovable, and ancient.”"),
25: ("It is said to be unmanifest, unthinkable, and unchanging. Knowing it thus, you have no cause to grieve.",
    "“The Self is called unmanifest, unthinkable, and immutable. Knowing it this way, you have no reason to mourn.”"),
26: ("But even if you think the Self is perpetually born and perpetually dies, O mighty-armed one, even then you should not grieve.",
    "“Even if you mistakenly think the Self is constantly being born and dying, Arjuna — even so, you should not grieve.”"),
27: ("For death is certain for the born, and birth is certain for the dead. Therefore, in an unavoidable matter, you should not grieve.",
    "“Whoever is born will surely die, and whoever dies will surely be born again. So in this unavoidable matter, there is no room for grief.”"),
28: ("All beings are unmanifest in their beginning, manifest in their middle, and unmanifest again in their end. What is there to lament, O Bhārata?",
    "“All beings are unseen before birth, visible in life, and unseen again after death. So what is there to grieve about?”"),
29: ("One sees the Self as a wonder, another speaks of it as a wonder, another hears of it as a wonder — and even having heard, no one truly knows it.",
    "“Some behold the Self as a marvel, some describe it as a marvel, some hear of it as a marvel — and even after hearing, none really understands it.”"),
30: ("The embodied Self in the body of everyone is eternally inviolable, O Bhārata. Therefore you should not grieve for any being.",
    "“The Self dwelling in every body is forever indestructible, Arjuna. So you should grieve for no one at all.”"),
31: ("Considering also your own dharma, you should not waver; for a kṣatriya, nothing is better than a righteous war.",
    "“Look also to your own duty, and you will not hesitate: for a warrior, there is nothing better than a war fought for righteousness.”"),
32: ("Blessed are the kṣatriyas, O Pārtha, who find such a war — come to them of its own accord — an open door to heaven.",
    "“Fortunate are the warriors, Arjuna, who meet a war like this — it comes to them unsought, and it is an open gate to heaven.”"),
33: ("But if you do not wage this righteous war, then, abandoning your own dharma and your glory, you will incur sin.",
    "“But if you refuse to fight this righteous war, you will turn your back on your duty and your honour — and sin will be yours.”"),
34: ("People will speak of your everlasting disgrace; and for one held in honour, disgrace is worse than death.",
    "“The world will spread word of your lasting shame; and for one who has been honoured, dishonour is worse than death.”"),
35: ("The great warriors will think you fled the battle out of fear; and those who held you in high regard will think little of you.",
    "“The great chariot-warriors will say you retreated from fear; those who once admired you will dismiss you with contempt.”"),
36: ("Your enemies will speak many unutterable words, slandering your strength. What could be more painful than that?",
    "“Your foes will say things that should never be said, mocking your courage. What could hurt more than that?”"),
37: ("Slain, you will win heaven; victorious, you will enjoy the earth. Therefore arise, O son of Kuntī, resolved to fight.",
    "“Killed, you will gain heaven; victorious, you will rule the earth. So stand up, Arjuna, with your mind made up for battle.”"),
38: ("Making pleasure and pain, gain and loss, victory and defeat the same, then fight — and you will incur no sin.",
    "“Hold pleasure and pain, profit and loss, triumph and defeat as one — then fight. No sin will touch you.”"),
39: ("This wisdom of sāṅkhya has been declared to you, O Pārtha. Now hear the wisdom of yoga; joined with it, you will cast off the bondage of karma.",
    "“I have taught you the discernment of sāṅkhya; now hear the wisdom of yoga. Living by it, you will break free from the bondage of action.”"),
40: ("Here there is no loss of effort, nor any contrary result. Even a little of this dharma protects one from great fear.",
    "“In this path no effort is wasted and no obstacle turns it back. Even a little of this practice saves you from great dread.”"),
41: ("The intellect of the resolute is single and one-pointed here, O joy of the Kurus; but the intellects of the irresolute branch out endlessly.",
    "“The mind of firm resolve is single and steady, Arjuna; the minds of the irresolute scatter into countless branches.”"),
42: ("The unwise, delighting in the flowery words of the Vedas, declare that there is nothing else — addicted to ritual and enjoyment, O Pārtha.",
    "“The shallow-minded rejoice in the Veda's flowery promises and claim there is nothing beyond them — clinging to rites and their fruits.”"),
43: ("Desire-filled, heaven-seeking, they promise birth and karma as their fruit, and preach many special rites for the sake of pleasure and power.",
    "“They are full of craving, longing for heaven, promising rebirth and rewards, and urging elaborate rituals to win pleasure and power.”"),
44: ("For those attached to pleasure and power, whose minds are carried away by such words, the one-pointed intellect of samādhi does not arise.",
    "“For those bewitched by pleasure and power, whose hearts these promises have stolen, the steady intellect of absorption never takes root.”"),
45: ("The Vedas deal with the three guṇas; rise above the three guṇas, O Arjuna — free from the pairs of opposites, ever established in sattva, beyond gain and keeping, self-possessed.",
    "“The Vedas move within the three guṇas; rise beyond them, Arjuna — beyond duality, resting in purity, free from craving and possessions, master of yourself.”"),
46: ("As much use as a well is when water floods everywhere, so much is all the Veda for a brāhmaṇa of understanding.",
    "“A well is of little use when water floods the land — likewise all the Vedas to the sage who has realized the truth.”"),
47: ("Your right is to action alone, never to its fruits. Let not the fruits of action be your motive, nor let your attachment be to inaction.",
    "“You have a right to act, but never to the results of action. Do not act for reward, and do not cling to doing nothing.”"),
48: ("Established in yoga, perform your actions, casting off attachment, O Dhanañjaya; equal in success and failure — this evenness is called yoga.",
    "“Rooted in yoga, do your work without clinging, Arjuna. Remain the same in success and failure — that poise is what yoga means.”"),
49: ("Action is far inferior to the yoga of discernment, O Dhanañjaya. Seek refuge in the intellect; pitiful are those who act for results.",
    "“Ordinary action is far below the yoga of understanding, Arjuna. Take refuge in wise discernment — pitiable are those who labor only for reward.”"),
50: ("One joined to the intellect leaves behind here both good deeds and bad. Therefore devote yourself to yoga — yoga is skill in action.",
    "“United with wisdom, one sheds both merit and demerit in this very life. So turn to yoga — for yoga is the art of action.”"),
51: ("The wise, united with the intellect and renouncing the fruits of their actions, are freed from the bonds of birth and reach the place beyond all ill.",
    "“The wise, established in understanding, give up the fruits of action and are released from the bonds of rebirth, reaching the state that knows no suffering.”"),
52: ("When your intellect crosses beyond the mire of delusion, you will grow indifferent to what has been heard and what is yet to be heard.",
    "“When your mind passes beyond the swamp of confusion, you will become indifferent to scriptures heard and yet to be heard.”"),
53: ("When your intellect, bewildered by the scriptures, stands firm and unmoved in samādhi, then you will attain yoga.",
    "“When your intellect, no longer shaken by conflicting scriptures, rests steady in absorption — then you have reached yoga.”"),
54: ("Arjuna said: What is the description of the man of steady wisdom, established in samādhi, O Keśava? How does the steady-minded one speak, how sit, how move?",
    "Arjuna asks: “What marks the man of steady wisdom, fixed in absorption, Kṛṣṇa? How does such a one speak, sit, and walk?”"),
55: ("The Blessed Lord said: When one casts off all desires of the mind, O Pārtha, and is content in the Self alone through the Self — then one is called steady in wisdom.",
    "Kṛṣṇa answers: “When a person lets go of every desire that arises in the mind and is content in the Self alone, that one is called steady in wisdom.”"),
56: ("One whose mind is untroubled in sorrow and free from longing in joy, from whom passion, fear and anger have departed — that one is the steady-minded sage.",
    "“The sage whose mind is unshaken by pain and free of craving in pleasure, who has let go of lust, fear, and anger — that one is of steady mind.”"),
57: ("One who is without affection everywhere, who neither rejoices nor recoils on meeting good or evil — that one's wisdom is firmly set.",
    "“One who clings to nothing, who is neither elated by the good nor upset by the bad — that person's understanding stands firm.”"),
58: ("When, like a tortoise drawing in its limbs from all sides, one withdraws the senses from their objects — that one's wisdom is firmly set.",
    "“A tortoise pulls in its legs and head at the first sign of danger. Do that with your senses, and your wisdom is steady.”"),
59: ("The objects fall away from the self-controlled one, but the taste for them remains; and when the Supreme is seen, even that taste departs.",
    "“Sense objects drop away from the one who abstains, yet the craving for them lingers; but when one sees the Supreme, even that craving falls away.”"),
60: ("Even for the striving sage, O son of Kuntī, the turbulent senses forcibly carry away the mind.",
    "“Even a wise person who is striving, Arjuna, finds that the restless senses snatch the mind away by force.”"),
61: ("Having restrained them all, the disciplined one should sit intent on Me; for one whose senses are under control, wisdom is firmly set.",
    "“Reining in all the senses, the yogi should sit devoted to Me; for one whose senses are mastered, understanding stands firm.”"),
62: ("Brooding on sense objects breeds attachment to them; from attachment arises desire; from desire arises anger.",
    "“Dwelling on the objects of the senses creates attachment; from attachment comes craving; from craving comes anger.”"),
63: ("From anger comes delusion; from delusion, confusion of memory; from broken memory, the ruin of understanding; and from that ruin, one is destroyed.",
    "“Anger brings delusion; delusion confuses memory; confused memory destroys reason; and with reason destroyed, a person is lost.”"),
64: ("But one who moves among objects with the senses mastered, free from attraction and aversion, self-controlled — that one attains serenity.",
    "“But the self-controlled one who walks among sense objects with the senses mastered, free of liking and disliking — that one wins peace.”"),
65: ("In serenity, all sorrows cease for that one; for the mind of the serene is quickly established in steadiness.",
    "“In that peace all suffering comes to an end for such a person; the heart of the serene quickly settles into clarity.”"),
66: ("There is no wisdom for the undisciplined, no meditation for the unsteady; and without meditation there is no peace — how can there be happiness without peace?",
    "“The undisciplined have no discernment, the restless have no meditation; without meditation there is no peace, and without peace, how can there be happiness?”"),
67: ("For the mind that follows the wandering senses carries away the understanding, as the wind carries a boat on the waters.",
    "“The mind that drifts after the roaming senses sweeps away one's judgment, just as the wind drives a boat across the sea.”"),
68: ("Therefore, O mighty-armed one, one whose senses are wholly withdrawn from their objects — that one's wisdom is firmly set.",
    "“Therefore, Arjuna, the one who has fully drawn the senses back from their objects — that person's understanding stands firm.”"),
69: ("What is night for all beings is the waking time for the disciplined sage; what is waking for beings is night for the sage who sees.",
    "“What is night to the ordinary world is waking for the self-controlled sage; and what the world calls day is night to the seer.”"),
70: ("As the waters enter the ocean, which remains unmoved though filled from every side, so the sage whom all desires enter remains at peace — not the one who lusts for desires.",
    "“Just as rivers pour into the ocean, which stays unmoved and full, so the sage into whom all desires flow remains serene — unlike one who craves desire itself.”"),
71: ("The man who casts off all desires and moves without longing, without possessiveness, without ego — that one attains peace.",
    "“The person who lets go of every desire and lives free of craving, free of 'mine,' free of 'I' — that one finds peace.”"),
72: ("This is the Brāhmī state, O Pārtha; attaining it, one is no longer deluded. Resting in it even at the end, one reaches Brahman-nirvāṇa.",
    "“This is the state of Brahman, Arjuna. Reaching it, no one is ever deluded again. Abiding in it even at death, one attains liberation in Brahman.”"),
}
