# -*- coding: utf-8 -*-
"""gita_data4.py — Chapter 4 (Jñāna-Karma-Sannyāsa Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH4_THEMES = [
    ("This yoga is ancient, handed down",
     "Kṛṣṇa reveals the immemorial lineage of this yoga — from Vivasvān to Manu to Ikṣvāku — lost in time and now restored to Arjuna.",
     [("Taught to vivasvān", "I taught this imperishable yoga to Vivasvān; he told it to Manu, and Manu to Ikṣvāku — thus the royal sages knew it, till it was lost by long lapse of time.", "4.01", "4.01"),
      ("In time this yoga was lost", "Handed down from teacher to student, the sage-kings knew it — but after a very long time it was lost, Arjuna.", "4.02", "4.02"),
      ("I declare that ancient yoga to you", "That same ancient yoga I now teach to you, for you are devoted to me and you are my friend — this is the supreme secret.", "4.03", "4.03")]),
    ("Arjuna asks: how could you teach it then?",
     "How could you, born later, have taught this yoga to Vivasvān at the beginning?",
     [("Arjuna asks how that can be", "Your birth is later, Vivasvān's earlier — how am I to understand that you declared it in the beginning?", "4.04", "4.04")]),
    ("I take birth age after age",
     "Many births have passed for both of us; unborn though I am, I come into being by my own power whenever dharma declines.",
     [("My births are divine", "Many births of mine have passed, and of yours; I know them all, you do not. Though unborn and imperishable, I come into being through my own māyā.", "4.05", "4.05"),
      ("I come into being by my own māyā", "I am unborn and eternal, the Lord of all beings — yet, taking up my own nature, I appear in the world through my own māyā.", "4.06", "4.06"),
      ("Whenever dharma declines", "Whenever dharma declines and adharma rises, I manifest myself — to protect the good, destroy the wicked, and establish dharma, age after age.", "4.07", "4.07"),
      ("To protect the righteous", "To protect the righteous, to destroy the wicked, and to restore righteousness, I am born in every age.", "4.08", "4.08"),
      ("Knowing this, one is not reborn", "He who truly knows my divine birth and work is not reborn on leaving the body — he comes to me.", "4.09", "4.09")]),
    ("The Way of Approach",
     "Freed from passion and fear, many have reached me; and in whatever way men approach me, in that way I receive them.",
     [("Freed from passion and fear", "Freed from attachment, fear and anger, absorbed in me, purified by the austerity of knowledge, many have attained my being.", "4.10", "4.10"),
      ("As they approach, so I receive", "However you come to me, I receive you in that way. Every path leads back to me, Arjuna.", "4.11", "4.11"),
      ("Those who want quick fruit worship gods", "People seeking quick results worship the deities; in the human world, results do come quickly from action.", "4.12", "4.12")]),
    ("I am the author, yet not the doer",
     "The fourfold order was created by me according to guṇa and action — yet know me, its author, as the eternal non-doer.",
     [("The fourfold order was created by me", "The fourfold order was created by me according to the distribution of guṇas and actions; though its author, know me as the non-doer, changeless.", "4.13", "4.13"),
      ("Actions do not taint me", "I crave no results, so actions never touch me. Whoever understands this is equally free.", "4.14", "4.14"),
      ("The ancients acted so", "The wise of old, longing for freedom, acted this way. You too should act, Arjuna, as they did before you.", "4.15", "4.15")]),
    ("What is action, what is inaction?",
     "The riddle at the heart of karma-yoga: even the wise are bewildered about what action and inaction are.",
     [("Even poets are confounded", "What is action, what is inaction? Even the wise are bewildered here. The nature of action, of forbidden action and of inaction must be understood — mysterious is the course of action.", "4.16", "4.16"),
      ("The mystery of action", "You must understand action, wrong action, and non-action — the ways of karma are deep and hard to fathom.", "4.17", "4.17"),
      ("The non-doer sees", "One who sees no doer in the doing, and action in stillness — he is truly wise; acting, he yet performs all actions.", "4.18", "4.18")]),
    ("Though he acts, he does nothing",
     "The portrait of the man whose works are burnt by knowledge: content with what comes unsought, beyond the pairs, and his actions dissolve entirely.",
     [("Desires burnt by knowledge", "Whose undertakings are free of desire and intention, whose works are burnt in the fire of knowledge — him the wise call learned. Abandoning attachment to the fruit, ever content and dependent on nothing, though engaged he does nothing at all.", "4.19", "4.19"),
      ("Free from fever", "Free from clinging to results, always satisfied, needing nothing — such a person acts, yet nothing is done by him.", "4.20", "4.20"),
      ("Owning nothing, he incurs no sin", "Desireless, self-controlled, owning nothing, he acts only with the body — and no sin touches him.", "4.21", "4.21"),
      ("Content with what comes", "Happy with whatever comes, beyond heat and cold, win and loss, free of jealousy — his actions never bind him.", "4.22", "4.22"),
      ("The freed man's action", "One who is unattached and free, whose mind rests in wisdom and whose work is an offering — his karma dissolves entirely.", "4.23", "4.23")]),
    ("All is Brahman: the offering and the fire",
     "The great formula chanted before food: the offering, the oblation, the fire and the offerer are all Brahman.",
     [("Brahman is the ladle, Brahman the oblation", "Brahman is the ladle, Brahman the oblation, poured by Brahman into the fire of Brahman; Brahman alone is reached by him absorbed in the action of Brahman.", "4.24", "4.24")]),
    ("Sacrifice takes many forms",
     "Sacrifice takes many forms — to the gods, of the senses, of the breath, of wealth and study and austerity.",
     [("Sacrifice to the gods, and into Brahman", "Some yogis offer sacrifice to the gods; others offer the sacrifice itself into the fire of Brahman.", "4.25", "4.25"),
      ("Senses offered into the fires of restraint", "Some disciplines offer their senses into the fire of self-control; others offer the objects of the senses into the fires of the senses.", "4.26", "4.26"),
      ("All action offered in the fire of yoga", "Others surrender every act of the senses and of the breath into the fire of self-mastery, lit by wisdom.", "4.27", "4.27"),
      ("Sacrifice of knowledge excels", "Some sacrifice by giving wealth, by austerities, by meditation, or by studying the scriptures — all are ascetics of firm vows.", "4.28", "4.28"),
      ("Breath offered to breath", "Others practise breath control, offering one breath into the other and stilling the flow of the life-forces.", "4.29", "4.29"),
      ("Breath offered into breath, sins consumed", "Others, eating little, offer breath into breath. All who understand sacrifice have their sins consumed by sacrifice.", "4.30", "4.30")]),
    ("Sacrifice frees you from action",
     "The eaters of sacrifice's nectar reach the eternal; all sacrifices are born of action, and knowing this you are released.",
     [("Not even this world for the non-sacrificer", "Eating the nectar-remnant of sacrifice, they go to eternal Brahman; this world is not for the non-sacrificer — how then the next?", "4.31", "4.31"),
      ("All sacrifices are born of action", "The scriptures describe many kinds of sacrifice. Know that all arise from action — and understanding this, you shall be released.", "4.32", "4.32"),
      ("Knowledge-sacrifice is greater than things", "The offering of wisdom is greater than any material offering — all action, without exception, culminates in knowledge.", "4.33", "4.33")]),
    ("Go to the wise and ask",
     "How knowledge is got: by prostration, by questioning, by service. Those who have seen the truth will teach it — and knowing it you will never be deluded again.",
     [("Approach a teacher, ask, serve", "Know this by prostration, by questioning, by service; the wise who have seen the truth will teach you that knowledge — knowing which you will not fall into delusion again, and will see all beings in the Self and in me.", "4.34", "4.34"),
      ("The better path", "With this knowledge you will never be deluded again — you will see all beings in yourself, and in me.", "4.35", "4.35"),
     ]),
    ("Knowledge burns all actions to ashes",
     "The praise of jñāna: it carries the worst sinner across, burns karma as fire burns fuel, and nothing here purifies like it — but the doubter, faithless, perishes.",
     [("Faith removes doubt", "Even if you were the worst sinner imaginable, the boat of knowledge would carry you across all your sins.", "4.36", "4.36"),
      ("The fire of wisdom", "Just as fire burns fuel to ash, the fire of wisdom burns up all karma.", "4.37", "4.37"),
      ("The peace of knowledge", "Nothing purifies like wisdom. The yogi who is ready finds it arising within himself, in due time.", "4.38", "4.38"),
      ("The doubt perishes", "One who has faith, devotion to the goal, and mastery of the senses gains wisdom — and with wisdom, he soon reaches supreme peace.", "4.39", "4.39"),
      ("The doubting soul perishes", "The ignorant and faithless, torn by doubt, are lost — the doubter enjoys nothing here or beyond.", "4.40", "4.40"),
      ("Yoga burns the doubt", "One who has surrendered his karma through yoga, whose doubts are cut by wisdom — nothing can bind him, Arjuna.", "4.41", "4.41"),
     ]),
    ("Cut your doubt and arise",
     "The chapter's closing command, in two imperatives: cut the doubt lodged in your heart with the sword of knowledge, take your stand in yoga — and rise.",
     [("Cut the doubt and take your stand", "So cut the doubt in your heart with the sword of wisdom, take your stand in yoga — and rise up, Arjuna!", "4.42", "4.42")]),
]

CH4_TRANSLATIONS = {
1: ("The Blessed Lord said: I declared this imperishable yoga to Vivasvān; Vivasvān communicated it to Manu; Manu proclaimed it to Ikṣvāku.",
    "Kṛṣṇa said: “Long ago I taught this eternal yoga to the sun-god Vivasvān; he passed it on to Manu, and Manu to King Ikṣvāku.”"),
2: ("Thus received in succession, the royal sages came to know it; but in the long course of time, this yoga was lost, O scorcher of foes.",
    "“Handed down from teacher to student, the sage-kings knew it — but after a very long time it was lost, Arjuna.”"),
3: ("This same ancient yoga is now declared to you by me, because you are my devotee and friend — truly, this is the supreme secret.",
    "“That same ancient yoga I now teach to you, for you are devoted to me and you are my friend — this is the highest secret.”"),
4: ("Arjuna said: Later is your birth, and earlier the birth of Vivasvān; how then am I to understand that you taught it in the beginning?",
    "Arjuna asks: “You were born long after the sun-god Vivasvān. How could you have taught him this yoga at the very beginning?”"),
5: ("The Blessed Lord said: Many births of mine have passed, and of yours too, O Arjuna; I know them all, but you do not know them, O scorcher of foes.",
    "Kṛṣṇa said: “Both of us have passed through countless births, Arjuna. I remember them all; you do not.”"),
6: ("Though unborn, though the imperishable Self, though the Lord of beings — resorting to my own prakṛti, I come into being through my own māyā.",
    "“I am unborn and eternal, the Lord of all beings — yet, taking up my own nature, I appear in the world through my own divine power.”"),
7: ("Whenever, O Bhārata, there is a decline of dharma and a rise of adharma, then I bring myself into being.",
    "“Whenever righteousness wanes and unrighteousness waxes, Arjuna, I manifest myself.”"),
8: ("For the protection of the good, for the destruction of the evil-doers, for the establishment of dharma, I take birth age after age.",
    "“To protect the righteous, to destroy the wicked, and to restore righteousness, I am born in every age.”"),
9: ("He who thus knows in truth my divine birth and action — having abandoned the body, he is not born again; he comes to me, O Arjuna.",
    "“Whoever truly understands my divine birth and deeds is never reborn after death — he comes to me, Arjuna.”"),
10: ("Free from attachment, fear and anger, filled with me, taking refuge in me, many — purified by the austerity of knowledge — have attained my state.",
    "“Those free of craving, fear and anger, who take shelter in me, are purified by the fire of wisdom and reach my very being.”"),
11: ("In whatever way men approach me, in that same way I favour them; people follow my path in every way, O Pārtha.",
    "“However you come to me, I receive you in that way. Every path leads back to me, Arjuna.”"),
12: ("Those who desire the success of actions worship the gods here; indeed, in this human world success born of action comes quickly.",
    "“People seeking quick results worship the deities; in the human world, results do come quickly from action.”"),
13: ("The fourfold order was created by me according to the distinction of guṇas and actions; though I am its author, know me as the non-doer and imperishable.",
    "“I created the four orders of society by qualities and work — yet I stand beyond them all, the changeless non-doer.”"),
14: ("Actions do not stain me, nor have I any longing for the fruit of action; he who knows me thus is not bound by actions.",
    "“I crave no results, so actions never touch me. Whoever understands this is equally free.”"),
15: ("Knowing this, the ancient seekers of liberation performed action; therefore you too perform action, as was done before by the ancients.",
    "“The wise of old, longing for freedom, acted this way. You too should act, Arjuna, as they did before you.”"),
16: ("What is action, what is inaction — even the wise are bewildered here; I shall declare to you that action, knowing which you will be released from evil.",
    "“What is truly action, and what is inaction? Even the learned are confused. I will teach you the truth of action — knowing it, you will be free of all harm.”"),
17: ("Indeed the nature of action must be understood, and of forbidden action too, and of inaction; mysterious is the course of action.",
    "“You must understand action, wrong action, and non-action — the ways of karma are deep and hard to fathom.”"),
18: ("He who sees inaction in action, and action in inaction, is intelligent among men; he is engaged in yoga and performs all actions.",
    "“One who sees no doer in the doing, and action in stillness — he is truly wise; acting, he yet performs all that must be done.”"),
19: ("Whose undertakings are all free from desire and selfish intention, and whose actions are burnt by the fire of knowledge — him the wise call a man of learning.",
    "“One whose every act is free of craving, whose karma is consumed by wisdom — the learned call him truly wise.”"),
20: ("Having abandoned attachment to the fruit of action, ever content, without any support — though engaged in action, he verily does nothing.",
    "“Free from clinging to results, always satisfied, needing nothing — such a person acts, yet nothing is done by him.”"),
21: ("Free from desire, with the mind and self controlled, having given up all possessions, performing only bodily action, he does not incur sin.",
    "“Desireless, self-controlled, owning nothing, he acts only with the body — and no sin touches him.”"),
22: ("Content with what comes unsought, beyond the pairs of opposites, free from envy, equal in success and failure — even acting, he is not bound.",
    "“Happy with whatever comes, beyond heat and cold, win and loss, free of jealousy — his actions never bind him.”"),
23: ("The actions of one free from attachment, liberated, whose mind is established in knowledge and who acts for sacrifice — they dissolve entirely.",
    "“One who is unattached and free, whose mind rests in wisdom and whose work is an offering — his karma melts away completely.”"),
24: ("The ladle is Brahman, the oblation is Brahman, offered in the fire of Brahman by Brahman; Brahman alone is reached by him who is absorbed in the action of Brahman.",
    "“When the offering, the fire, the giver and the giving are all seen as Brahman, the act itself becomes the path to Brahman.”"),
25: ("Some yogis worship the gods through sacrifice; others offer the sacrifice itself, by sacrifice, into the fire of Brahman.",
    "“Some offer material worship to the gods; others see the whole of life as an offering into the fire of the Absolute.”"),
26: ("Some offer hearing and the other senses into the fires of restraint; others offer sound and the other sense-objects into the fires of the senses.",
    "“Some disciplines offer their senses into the fire of self-control; others offer the objects of the senses themselves.”"),
27: ("And others offer all the activities of the senses and of the vital breaths into the fire of the yoga of self-restraint, kindled by knowledge.",
    "“Others surrender every act of the senses and of the breath into the fire of self-mastery, lit by wisdom.”"),
28: ("Others perform the sacrifices of wealth, austerity, yoga, and scriptural study — ascetics of firm vows.",
    "“Some sacrifice by giving wealth, by austerities, by meditation, or by studying the scriptures — all are seekers of firm resolve.”"),
29: ("Some offer the up-breath into the down-breath, and the down-breath into the up-breath, checking the courses of the breaths, devoted to breath-control.",
    "“Others practise breath control, offering one breath into the other and stilling the flow of the life-forces.”"),
30: ("Others, with regulated diet, offer the vital breaths into the vital breaths; all these are knowers of sacrifice, whose sins are consumed by sacrifice.",
    "“Others, eating little, offer breath into breath. All who understand sacrifice have their sins burnt away by it.”"),
31: ("Tasting the nectar of the remnant of sacrifice, they reach the eternal Brahman; this world is not for the non-sacrificer, how then the next, O best of the Kurus?",
    "“Those who live on the blessed remnant of the offering reach the eternal Brahman. Without sacrifice you cannot even enjoy this world — let alone the next.”"),
32: ("Thus manifold sacrifices are set forth in the scriptures; know them all as born of action — knowing this, you shall be released.",
    "“The scriptures describe many kinds of sacrifice. Know that all arise from action — and understanding this sets you free.”"),
33: ("The sacrifice of knowledge is better than the sacrifice of material things, O scorcher of foes; all action, in its entirety, O Pārtha, culminates in knowledge.",
    "“The offering of wisdom is greater than any material offering — all action, without exception, reaches its end in knowledge.”"),
34: ("Know that wisdom through prostration, by questioning, and by service; the knowers of truth who have seen reality will instruct you.",
    "“Approach the wise with humility, ask sincerely, and serve them — the seers of truth will impart wisdom to you.”"),
35: ("Knowing that, O son of Pāṇḍu, you will not again fall under delusion; by it you will see all beings without exception in the Self, and also in me.",
    "“With this knowledge you will never be deluded again — you will see all beings in yourself, and in me.”"),
36: ("Even if you are the most sinful of all sinners, you shall cross all evil by the boat of knowledge alone.",
    "“Even if you were the worst sinner imaginable, the boat of knowledge would carry you across all your sins.”"),
37: ("As the kindled fire reduces fuel to ashes, O Arjuna, so does the fire of knowledge reduce all actions to ashes.",
    "“Just as fire burns fuel to ash, the fire of wisdom burns up all karma.”"),
38: ("Indeed, nothing here is as purifying as knowledge; one perfected in yoga finds it in the Self in time, of himself.",
    "“Nothing purifies like wisdom. The yogi who is ready finds it arising within himself, in due time.”"),
39: ("The faithful man, intent on it, with senses subdued, attains knowledge; and having attained knowledge, he soon reaches supreme peace.",
    "“One who has faith, devotion to the goal, and mastery of the senses gains wisdom — and with wisdom, deep and lasting peace.”"),
40: ("But the ignorant man without faith, full of doubt, perishes; for the doubting soul there is neither this world, nor the next, nor happiness.",
    "“The ignorant and faithless, torn by doubt, are lost — the doubter enjoys nothing here or beyond.”"),
41: ("Actions do not bind him who has renounced actions through yoga, whose doubt is destroyed by knowledge, who is self-possessed, O Dhanañjaya.",
    "“One who has surrendered his karma through yoga, whose doubts are cut by wisdom — nothing can bind him, Arjuna.”"),
42: ("Therefore, cutting with the sword of knowledge this doubt born of ignorance that dwells in your heart, stand firm in yoga — arise, O Bhārata!",
    "“So cut the doubt in your heart with the sword of wisdom, take your stand in yoga — and rise up, Arjuna!”"),
}
