# -*- coding: utf-8 -*-
"""gita_data10.py — Chapter 10 (Vibhūti Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH10_THEMES = [
    ("Hear My Supreme Word",
     "Neither gods nor great seers know my origin; he who knows me as unborn and beginningless is freed from all sins.",
     [("Hear again my supreme word", "Hear again, O mighty-armed one, my supreme words, which I speak to you who are dear, wishing your good.", "10.01", "10.01"),
      ("Neither gods nor seers know my origin", "Neither the hosts of gods nor the great seers know my origin; for I am the beginning of the gods and the great seers in every way.", "10.02", "10.02"),
      ("He who knows me unborn and beginningless", "He who knows me as unborn, without beginning, the great Lord of the world — undeluded among mortals, he is freed from all sins.", "10.03", "10.03")]),
    ("Every quality of beings comes from me",
     "Intellect, knowledge, truth, self-control, fame and infamy — all the states of beings arise from me alone.",
     [("Intellect, knowledge, non-delusion", "Intellect, knowledge, freedom from delusion, forbearance, truth, self-control, calm — pleasure, pain, birth, death, fear and fearlessness,", "10.04", "10.04"),
      ("All these states arise from me", "non-violence, equanimity, contentment, austerity, generosity, fame and infamy — these various states of beings arise from me alone.", "10.05", "10.05"),
      ("The seven great seers", "The seven great seers, the four ancient Manus, born of my mind — from them come the beings of this world.", "10.06", "10.06"),
      ("He who knows this glory is joined to me", "He who knows in truth this glory and power of mine is united to me by unwavering yoga — of this there is no doubt.", "10.07", "10.07")]),
    ("I Am the Source of All",
     "I am the origin of all; the wise, knowing this, worship me — and to them I give the yoga of understanding.",
     [("I am the origin of all; the wise worship me", "I am the source of all; everything proceeds from me. Knowing this, the wise worship me, filled with devotion.", "10.08", "10.08"),
      ("Speaking of me, my devotees rejoice", "Their thoughts on me, their lives given to me, enlightening one another, always speaking of me — they are content and rejoice.", "10.09", "10.09"),
      ("To them I give the Yoga of understanding", "To them, ever devoted, worshipping me with love, I give the yoga of discernment, by which they come to me.", "10.10", "10.10"),
      ("I destroy the darkness with the lamp of knowledge", "Out of compassion for them, dwelling in their hearts, I destroy the darkness born of ignorance with the shining lamp of knowledge.", "10.11", "10.11")]),
    ("Arjuna praises: you are supreme Brahman",
     "You are the supreme Brahman, the supreme abode; the sages and Nārada affirm it, and now you tell me yourself.",
     [("You are the supreme Brahman", "You are the supreme Brahman, the supreme light, the supreme purifier; the eternal divine Person, the primal God, unborn and all-pervading.", "10.12", "10.12"),
      ("All the sages say so", "Thus the seers call you — Nārada the divine sage, Asita, Devala, Vyāsa — and you yourself tell me.", "10.13", "10.13"),
      ("Neither gods nor demons know your manifestation", "I hold all this you tell me as true, Keśava; indeed, neither gods nor demons, O Lord, know your manifestation.", "10.14", "10.14")]),
    ("How Shall I Know You?",
     "You alone know yourself by yourself; tell me the glories by which I may meditate on you — I am never sated with your nectar.",
     [("You alone know yourself by yourself", "You yourself know yourself by yourself, O supreme Person — O source of beings, Lord of beings, God of gods, Lord of the world!", "10.15", "10.15"),
      ("Tell me of your divine glories", "Tell me without omission your divine glories, by which you abide, pervading these worlds.", "10.16", "10.16"),
      ("In what forms shall I meditate on you?", "How shall I know you, O yogi, contemplating you always? And in what states are you to be thought of, O Lord?", "10.17", "10.17"),
      ("I am never sated hearing your nectar", "Tell me again, in detail, your yoga and your glory, O Janārdana; I am never satiated with hearing your nectar.", "10.18", "10.18")]),
    ("Kṛṣṇa begins to name his glories",
     "Kṛṣṇa consents, but only in outline — for his glories have no end; and first: I am the Self seated in the heart of all beings.",
     [("Only the chief of my glories", "Yes, I shall declare to you my divine glories — chiefly, O best of the Kurus; there is no end to my extent.", "10.19", "10.19"),
      ("I am the Self seated in the heart of all", "I am the Self, O Guḍākeśa, dwelling in the hearts of all beings; I am the beginning, the middle, and the end of all beings.", "10.20", "10.20")]),
    ("My glories among gods and lights",
     "Among the Ādityas Viṣṇu, among lights the sun, among the Vedas the Sāma, among words the syllable Om.",
     [("Viṣṇu, the sun, the moon", "Among the Ādityas I am Viṣṇu; among the lights, the radiant sun; I am Marīci among the winds; I am the moon among the stars.", "10.21", "10.21"),
      ("Among the senses I am the mind", "Among the Vedas I am the Sāma-veda; among the gods I am Indra; among the senses I am the mind; among beings I am consciousness.", "10.22", "10.22"),
      ("Śaṅkara, kubera, fire, Meru", "Among the Rudras I am Śaṅkara; among the yakṣas and rākṣasas, the lord of wealth; among the Vasus I am fire; among mountains, Meru.", "10.23", "10.23"),
      ("Bṛhaspati, Skanda, the ocean", "Among priests, O Pārtha, know me as the chief, Bṛhaspati; among generals I am Skanda; among waters I am the ocean.", "10.24", "10.24"),
      ("Among words, the syllable Om", "Among the great seers I am Bhṛgu; among words I am the single syllable Om; among sacrifices I am the japa-sacrifice; among the immovable I am the Himālaya.", "10.25", "10.25"),
      ("The Aśvattha, Nārada, kapila", "Among all trees I am the aśvattha; among the divine sages, Nārada; among the gandharvas, Citraratha; among the perfected, the sage Kapila.", "10.26", "10.26")]),
    ("The Glories of Earth and Beings",
     "Among horses Uccaiḥśravas, among serpents Vāsuki, among letters the letter A — and I am all-devouring death.",
     [("Uccaiḥśravas, Airāvata, the king", "Among horses know me as Uccaiḥśravas, born of nectar; among lordly elephants, Airāvata; among men, the king.", "10.27", "10.27"),
      ("The thunderbolt, Kāmadhuk, Vāsuki", "Among weapons I am the thunderbolt; among cows I am Kāmadhuk; I am the lord of love among procreators; among serpents, Vāsuki.", "10.28", "10.28"),
      ("Ananta, Varuṇa, Aryaman, Yama", "I am the infinite among serpents; Varuṇa among the waters; among the ancestors I am Aryaman; among rulers, Yama.", "10.29", "10.29"),
      ("Prahlāda, time, the lion, Garuḍa", "Among the demons I am Prahlāda; among the calculators, time; among beasts I am the lion; among birds, Garuḍa.", "10.30", "10.30"),
      ("The wind, rāma, the Ganges", "Among purifiers I am the wind; among warriors I am Rāma; among fishes I am the makara; among streams I am the Ganges.", "10.31", "10.31"),
      ("The beginning, middle and end of all", "Of creations I am the beginning, the middle, and also the end, O Arjuna; among the sciences I am the science of the Self; among debaters, the argument.", "10.32", "10.32"),
      ("Among letters, the letter a", "Among letters I am the letter A; among compounds the dvandva; I am indeed inexhaustible time; I am the ordainer facing everywhere.", "10.33", "10.33"),
      ("I am all-devouring death", "I am all-devouring death and the birth of all that will be; among women I am fame, fortune, speech, memory, wisdom, constancy and forbearance.", "10.34", "10.34")]),
    ("Among chants, months and sages, I am the best",
     "The enumeration continues: among Sāman hymns the Bṛhat, among metres the Gāyatrī, among the Pāṇḍavas Arjuna — and the seed of every being that exists.",
     [("The bṛhat-sāma, the Gāyatrī, the spring", "Among the Sāma-chants I am the Bṛhat-sāma; among metres the Gāyatrī; among months I am Mārgaśīrṣa; among seasons the spring.", "10.35", "10.35"),
      ("The dice of gamblers, the splendour of the splendid", "I am the dice of the gamblers; I am the splendour of the splendid; I am victory, I am determination; I am the goodness of the good.", "10.36", "10.36"),
      ("Among the Pāṇḍavas, Arjuna", "Among the Vṛṣṇis I am Vāsudeva; among the Pāṇḍavas, Arjuna; among the sages I am Vyāsa; among the poets, Uśanā the poet.", "10.37", "10.37"),
      ("The silence of secrets", "I am the rod of the punishers; among those seeking victory I am policy; I am the silence of the secret; among the knowing I am knowledge.", "10.38", "10.38"),
      ("Whatever is the seed of all beings", "And whatever is the seed of all beings, that I am, O Arjuna; no being, moving or unmoving, exists without me.", "10.39", "10.39")]),
    ("There is no end to my glories",
     "Kṛṣṇa stops the list: what has been named is only a summary. Whatever is glorious or powerful anywhere is a spark of his splendour — and one fragment of him upholds the whole world.",
     [("There is no end to my glories", "There is no end to my divine glories, O scorcher of foes; this is but a summary declared by me of the extent of my glory.", "10.40", "10.40"),
      ("Whatever is glorious is a spark of my splendour", "Whatever being is glorious, radiant or powerful — know that to be born of a portion of my splendour.", "10.41", "10.41"),
      ("I support this whole world with one fragment", "But what need, Arjuna, of this detailed knowledge? I stand supporting this whole world with one part of myself.", "10.42", "10.42")]),
]

CH10_TRANSLATIONS = {
1: ("The Blessed Lord said: Hear again, O mighty-armed one, my supreme words, which I speak to you who are dear, wishing your good.",
    "Kṛṣṇa said: “Listen once more, mighty-armed Arjuna, to my highest teaching — which I give you out of love, for your welfare.”"),
2: ("Neither the hosts of gods nor the great seers know my origin; for I am the beginning of the gods and the great seers in every way.",
    "“Neither the gods nor the great sages know where I come from — I am the very source of them all.”"),
3: ("He who knows me as unborn, without beginning, the great Lord of the world — undeluded among mortals, he is freed from all sins.",
    "“One who knows me as unborn, beginningless, the Lord of all worlds — he is no longer confused, and all his sins fall away.”"),
4: ("Intellect, knowledge, freedom from delusion, forbearance, truth, self-control, calm — pleasure, pain, birth, death, fear and fearlessness,",
    "“Understanding, wisdom, clarity, patience, truth, self-mastery, peace — joy, sorrow, coming-to-be, ceasing, fear, and courage,”"),
5: ("non-violence, equanimity, contentment, austerity, generosity, fame and infamy — these various states of beings arise from me alone.",
    "“— harmlessness, even-mindedness, contentment, tapas, giving, renown and disgrace — all these qualities of beings come from me alone.”"),
6: ("The seven great seers, the four ancient Manus, born of my mind — from them come the beings of this world.",
    "“The seven ancient sages and the four Manus, born of my thought — from them all the creatures of this world descend.”"),
7: ("He who knows in truth this glory and power of mine is united to me by unwavering yoga — of this there is no doubt.",
    "“Whoever truly knows my glories and my power is joined to me with unshakable yoga — of this there is no doubt.”"),
8: ("I am the source of all; everything proceeds from me. Knowing this, the wise worship me, filled with devotion.",
    "“I am the origin of everything; all flows from me. The wise, knowing this, worship me with love.”"),
9: ("Their thoughts on me, their lives given to me, enlightening one another, always speaking of me — they are content and rejoice.",
    "“With minds on me, lives devoted to me, teaching each other and always talking of me — they are satisfied and delighted.”"),
10: ("To them, ever devoted, worshipping me with love, I give the yoga of discernment, by which they come to me.",
    "“To those ever united, worshipping me with devotion, I give the wisdom-yoga by which they reach me.”"),
11: ("Out of compassion for them, dwelling in their hearts, I destroy the darkness born of ignorance with the shining lamp of knowledge.",
    "“Out of compassion, dwelling within them, I dispel their darkness of ignorance with the radiant lamp of wisdom.”"),
12: ("Arjuna said: You are the supreme Brahman, the supreme light, the supreme purifier; the eternal divine Person, the primal God, unborn and all-pervading.",
    "Arjuna says: “You are the supreme Brahman, the highest abode, the purest; the eternal divine Person, the first God, unborn and everywhere.”"),
13: ("Thus the seers call you — Nārada the divine sage, Asita, Devala, Vyāsa — and you yourself tell me.",
    "“All the sages say so — Nārada, Asita, Devala, Vyāsa — and you yourself confirm it to me.”"),
14: ("I hold all this you tell me as true, Keśava; indeed, neither gods nor demons, O Lord, know your manifestation.",
    "“I believe everything you say, Keśava. Neither gods nor demons can know how you appear, O Lord.”"),
15: ("You yourself know yourself by yourself, O supreme Person — O source of beings, Lord of beings, God of gods, Lord of the world!",
    "“Only you know yourself, O highest Person — creator of all, God of gods, Lord of the universe!”"),
16: ("Tell me without omission your divine glories, by which you abide, pervading these worlds.",
    "“Please tell me fully your divine glories — through which you stand pervading all these worlds.”"),
17: ("How shall I know you, O yogi, contemplating you always? And in what states are you to be thought of, O Lord?",
    "“How can I know you, thinking of you always? In which forms, O Lord, should I meditate on you?”"),
18: ("Tell me again, in detail, your yoga and your glory, O Janārdana; I am never satiated with hearing your nectar.",
    "“Tell me again at length of your power and glories, Janārdana — I never tire of drinking in this nectar.”"),
19: ("The Blessed Lord said: Yes, I shall declare to you my divine glories — chiefly, O best of the Kurus; there is no end to my extent.",
    "Kṛṣṇa said: “I will tell you of my divine glories — the chief among them, Arjuna; for my extent has no end.”"),
20: ("I am the Self, O Guḍākeśa, dwelling in the hearts of all beings; I am the beginning, the middle, and the end of all beings.",
    "“I am the Self seated in the hearts of all beings; I am their beginning, middle, and end.”"),
21: ("Among the Ādityas I am Viṣṇu; among the lights, the radiant sun; I am Marīci among the winds; I am the moon among the stars.",
    "“Of the Ādityas I am Viṣṇu; of lights, the blazing sun; of winds, Marīci; of stars, the moon.”"),
22: ("Among the Vedas I am the Sāma-veda; among the gods I am Indra; among the senses I am the mind; among beings I am consciousness.",
    "“Of the Vedas I am the Sāma; of gods, Indra; of the senses, the mind; of beings, consciousness.”"),
23: ("Among the Rudras I am Śaṅkara; among the yakṣas and rākṣasas, the lord of wealth; among the Vasus I am fire; among mountains, Meru.",
    "“Of the Rudras I am Śiva; of the yakṣas and demons, Kubera; of the Vasus, fire; of mountains, Meru.”"),
24: ("Among priests, O Pārtha, know me as the chief, Bṛhaspati; among generals I am Skanda; among waters I am the ocean.",
    "“Know me as Bṛhaspati among priests, Skanda among commanders, the ocean among bodies of water.”"),
25: ("Among the great seers I am Bhṛgu; among words I am the single syllable Om; among sacrifices I am the japa-sacrifice; among the immovable I am the Himālaya.",
    "“Of the great sages I am Bhṛgu; of speech, the sacred Om; of sacrifices, silent repetition; of the immovable, the Himalaya.”"),
26: ("Among all trees I am the aśvattha; among the divine sages, Nārada; among the gandharvas, Citraratha; among the perfected, the sage Kapila.",
    "“Of trees I am the sacred fig; of divine sages, Nārada; of celestial musicians, Citraratha; of the perfected, Kapila.”"),
27: ("Among horses know me as Uccaiḥśravas, born of nectar; among lordly elephants, Airāvata; among men, the king.",
    "“The white horse that rose from the churning of the ocean — that is me. So is Indra's elephant, and so is the king among men.”"),
28: ("Among weapons I am the thunderbolt; among cows I am Kāmadhuk; I am the lord of love among procreators; among serpents, Vāsuki.",
    "“Of weapons I am the thunderbolt; of cows, the wish-fulfilling cow; of the lustful, Kāma; of serpents, Vāsuki.”"),
29: ("I am the infinite among serpents; Varuṇa among the waters; among the ancestors I am Aryaman; among rulers, Yama.",
    "“Of serpents I am the endless Ananta; of sea-creatures, Varuṇa; of ancestors, Aryaman; of punishers, Yama.”"),
30: ("Among the demons I am Prahlāda; among the calculators, time; among beasts I am the lion; among birds, Garuḍa.",
    "“Of the demons I am Prahlāda; of reckoners, time; of beasts, the lion; of birds, Garuḍa.”"),
31: ("Among purifiers I am the wind; among warriors I am Rāma; among fishes I am the makara; among streams I am the Ganges.",
    "“Of purifiers I am the wind; of weapon-bearers, Rāma; of fish, the makara; of rivers, the Ganges.”"),
32: ("Of creations I am the beginning, the middle, and also the end, O Arjuna; among the sciences I am the science of the Self; among debaters, the argument.",
    "“Of all creations I am the beginning, middle, and end; of sciences, the science of the Self; of debates, sound reasoning.”"),
33: ("Among letters I am the letter A; among compounds the dvandva; I am indeed inexhaustible time; I am the ordainer facing everywhere.",
    "“Of letters I am the A; of compounds, the dvandva; I am endless time; I am the all-facing creator.”"),
34: ("I am all-devouring death and the birth of all that will be; among women I am fame, fortune, speech, memory, wisdom, constancy and forbearance.",
    "“I am death that carries all away, and the source of all that comes to be; among women, fame, grace, eloquence, memory, wisdom, steadiness, and patience.”"),
35: ("Among the Sāma-chants I am the Bṛhat-sāma; among metres the Gāyatrī; among months I am Mārgaśīrṣa; among seasons the spring.",
    "“Of the Sāma hymns take the greatest; of metres, the Gāyatrī; of the twelve months, the one when the harvest ripens; of the seasons, spring in flower.”"),
36: ("I am the dice of the gamblers; I am the splendour of the splendid; I am victory, I am determination; I am the goodness of the good.",
    "“I am the craft of the gambler, the glory of the glorious; I am victory and resolve; I am the virtue of the virtuous.”"),
37: ("Among the Vṛṣṇis I am Vāsudeva; among the Pāṇḍavas, Arjuna; among the sages I am Vyāsa; among the poets, Uśanā the poet.",
    "“Of the Vṛṣṇis I am Vāsudeva; of the Pāṇḍavas, Arjuna; of sages, Vyāsa; of poets, Uśanas.”"),
38: ("I am the rod of the punishers; among those seeking victory I am policy; I am the silence of the secret; among the knowing I am knowledge.",
    "“I am the sceptre of rulers and the statesmanship of the victorious; I am the silence of mysteries; of the wise, wisdom.”"),
39: ("And whatever is the seed of all beings, that I am, O Arjuna; no being, moving or unmoving, exists without me.",
    "“Whatever seed gives rise to all beings — that is I. Nothing moving or still exists apart from me.”"),
40: ("There is no end to my divine glories, O scorcher of foes; this is but a summary declared by me of the extent of my glory.",
    "“My divine glories have no end, Arjuna — this is only a brief statement of their vast extent.”"),
41: ("Whatever being is glorious, radiant or powerful — know that to be born of a portion of my splendour.",
    "“Whatever is splendid, shining, or mighty — know it springs from a spark of my glory.”"),
42: ("But what need, Arjuna, of this detailed knowledge? I stand supporting this whole world with one part of myself.",
    "“But why know all this in detail, Arjuna? With a single part of myself I sustain this entire universe.”"),
}
