# -*- coding: utf-8 -*-
"""gita_data17.py — Chapter 17 (Śraddhā-Traya-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH17_THEMES = [
    ("Faith is threefold, born of one's nature",
     "Arjuna asks about those who worship without scriptural rule; Kṛṣṇa replies: the faith of each is threefold, according to his nature.",
     [("Arjuna asks about faith outside scripture", "Those who, casting aside the ordinance of scripture, worship with faith — what is their state, O Kṛṣṇa? Is it sattva, rajas or tamas?", "17.01", "17.01"),
      ("The threefold faith", "The faith of embodied beings is threefold, born of their own nature — sāttvic, rājasic and tāmasic; hear of it.", "17.02", "17.02"),
      ("Faith shapes the man", "The faith of each is according to his nature, O Bhārata; a man is made of his faith — as is his faith, so is he.", "17.03", "17.03")]),
    ("The Three Kinds of Worshippers",
     "The sāttvic worship the gods, the rājasic the yakṣas and rākṣasas, the tāmasic ghosts and spirits.",
     [("Whom each worships", "The sāttvic worship the gods; the rājasic the yakṣas and rākṣasas; and others — the tāmasic — worship ghosts and the hosts of spirits.", "17.04", "17.04")]),
    ("Those who torture themselves are demoniac",
     "Those who torture body and soul with austerities scripture never ordained, driven by hypocrisy, ego and desire — know them to be of demoniac resolve.",
     [("Austerity not ordained", "The men who practise terrible austerities not ordained by scripture, full of hypocrisy and ego, impelled by the force of desire and attachment,", "17.05", "17.05"),
      ("Torturing me within", "— tormenting the elements of the body and also me dwelling within the body — know them as of demoniac resolves.", "17.06", "17.06")]),
    ("Food, sacrifice, austerity, gift: each threefold",
     "Food, sacrifice, austerity and gifts are each threefold; hear how they are distinguished.",
     [("The threefold distinction", "Food, too, dear to each, is threefold; and sacrifice, austerity and gifts — hear their distinction.", "17.07", "17.07")]),
    ("The food each nature loves",
     "Food dear to each is threefold — sāttvic, rājasic and tāmasic; hear what each is.",
     [("The Sāttvic food", "Foods that increase life, purity, strength, health, joy and cheer — savoury, smooth, firm and agreeable — are dear to the sāttvic.", "17.08", "17.08"),
      ("The Rājasic food", "Foods that are bitter, sour, salty, very hot, pungent, dry and burning — causing pain, grief and disease — are dear to the rājasic.", "17.09", "17.09"),
      ("The Tāmasic food", "Stale, tasteless, putrid and leftover food, and impure leavings — such food is dear to the tāmasic.", "17.10", "17.10")]),
    ("Sacrifice by rule, by desire, by neglect",
     "The sāttvic sacrifice is offered without desire, according to rule; the rājasic seeks fruit and display; the tāmasic is without rule and faith.",
     [("The Sāttvic sacrifice", "The sacrifice ordained by scripture, offered without desire for fruit by those who think 'this must be performed' — that is sāttvic.", "17.11", "17.11"),
      ("The Rājasic sacrifice", "But the sacrifice offered seeking fruit and for the sake of display, O best of the Bhāratas — know that as rājasic.", "17.12", "17.12"),
      ("The Tāmasic sacrifice", "The sacrifice without rule, without food-gifts, without mantra, without fees, devoid of faith — is declared tāmasic.", "17.13", "17.13")]),
    ("Austerity of body, speech and mind",
     "Austerity is threefold: of the body, of speech, and of the mind.",
     [("The austerity of body", "Worship of the gods, the twice-born, teachers and the wise; purity, uprightness, chastity and non-violence — this is the austerity of the body.", "17.14", "17.14"),
      ("The austerity of speech", "Speech that causes no distress, that is truthful, pleasant and beneficial, and the regular study of scripture — this is the austerity of speech.", "17.15", "17.15"),
      ("The austerity of mind", "Serenity of mind, gentleness, silence, self-control, and purity of heart — this is called the austerity of the mind.", "17.16", "17.16")]),
    ("Austerity done in faith, without desire",
     "The threefold austerity performed with supreme faith, without desire for fruit — is sāttvic; for honour and display — rājasic; with self-torture — tāmasic.",
     [("The Sāttvic austerity", "This threefold austerity, performed with supreme faith by the steadfast, without desire for fruit — is declared sāttvic.", "17.17", "17.17"),
      ("The Rājasic austerity", "Austerity performed for honour, reverence and worship, and with hypocrisy — is here declared rājasic, unstable and transitory.", "17.18", "17.18"),
      ("The Tāmasic austerity", "Austerity performed with foolish obstinacy, with self-torture, or to ruin another — is declared tāmasic.", "17.19", "17.19")]),
    ("The gift given without expectation",
     "The sāttvic gift is given to the worthy, at the right time and place, without expecting return; the rājasic expects reward; the tāmasic is given contemptuously.",
     [("The Sāttvic gift", "The gift given because it ought to be given, to one who can do nothing in return, at the right place and time, to a worthy person — is deemed sāttvic.", "17.20", "17.20"),
      ("The Rājasic gift", "But the gift given expecting a return, or seeking fruit again, or reluctantly — is deemed rājasic.", "17.21", "17.21"),
      ("The Tāmasic gift", "The gift given at the wrong place and time, to unworthy persons, without respect and with contempt — is declared tāmasic.", "17.22", "17.22")]),
    ("Om Tat Sat: the threefold name of Brahman",
     "Om Tat Sat — the threefold designation of Brahman. Each of the three words is taken in turn: Om begins every sacred act, Tat renounces its fruit, and Sat marks what is real, good and steadfast.",
     [("The threefold name", "Om Tat Sat — this is the threefold designation of Brahman; by it were ordained of old the brāhmaṇas, the Vedas and the sacrifices.", "17.23", "17.23"),
      ("Om: The beginning of every act", "Therefore, uttering Om, the acts of sacrifice, gift and austerity ordained by rule are begun, ever, by the knowers of Brahman.", "17.24", "17.24"),
      ("Tat: Without desire for fruit", "Uttering Tat, without desiring fruit, are the acts of sacrifice, austerity and the various acts of giving performed by seekers of liberation.", "17.25", "17.25"),
      ("Sat: reality and goodness", "Sat is used in the sense of reality and goodness, and also in auspicious works, O Pārtha.", "17.26", "17.26"),
      ("Firmness is also Sat", "Steadfastness in sacrifice, austerity and giving is also called Sat; and action for the sake of that is called Sat.", "17.27", "17.27")]),
    ("The Fruitless Without Faith",
     "Whatever is offered, given, performed or done without faith — is called Asat; it is nothing here or hereafter.",
     [("Without faith is asat", "Whatever is offered, given or performed without faith, and whatever is done — is called Asat, O Pārtha; it is naught here or hereafter.", "17.28", "17.28")]),
]

CH17_TRANSLATIONS = {
1: ("Arjuna said: Those who, casting aside the ordinance of scripture, worship with faith — what is their state, O Kṛṣṇa? Is it sattva, rajas or tamas?",
    "Arjuna asks: “Those who worship with faith but ignore the scriptural rules — what is their standing, Kṛṣṇa? Are they sāttvic, rājasic, or tāmasic?”"),
2: ("The Blessed Lord said: The faith of embodied beings is threefold, born of their own nature — sāttvic, rājasic and tāmasic; hear of it.",
    "Kṛṣṇa said: “Faith comes in three kinds, born of one's own nature: sāttvic, rājasic, and tāmasic. Listen.”"),
3: ("The faith of each is according to his nature, O Bhārata; a man is made of his faith — as is his faith, so is he.",
    "“Faith follows nature, Arjuna. A person is what his faith makes him — as he believes, so he becomes.”"),
4: ("The sāttvic worship the gods; the rājasic the yakṣas and rākṣasas; and others — the tāmasic — worship ghosts and the hosts of spirits.",
    "“The sāttvic adore the gods; the rājasic the demigods and demons; the tāmasic worship ghosts and spirits.”"),
5: ("The men who practise terrible austerities not ordained by scripture, full of hypocrisy and ego, impelled by the force of desire and attachment,",
    "“Those who, full of pride and vanity, driven by lust, practise harsh penances forbidden by scripture,”"),
6: ("— tormenting the elements of the body and also me dwelling within the body — know them as of demoniac resolves.",
    "“— torturing the body's constituents and me within the body — know them as demonic in their intentions.”"),
7: ("Food, too, dear to each, is threefold; and sacrifice, austerity and gifts — hear their distinction.",
    "“Food, sacrifice, austerity, and charity each have three forms, dear according to one's nature. Hear the difference.”"),
8: ("Foods that increase life, purity, strength, health, joy and cheer — savoury, smooth, firm and agreeable — are dear to the sāttvic.",
    "“Foods that promote life, clarity, strength, health, joy, and contentment — juicy, smooth, nourishing, and pleasant — are loved by the sāttvic.”"),
9: ("Foods that are bitter, sour, salty, very hot, pungent, dry and burning — causing pain, grief and disease — are dear to the rājasic.",
    "“Bitter, sour, salty, fiery, pungent, dry, and burning foods — which bring pain, sorrow, and sickness — are dear to the rājasic.”"),
10: ("Stale, tasteless, putrid and leftover food, and impure leavings — such food is dear to the tāmasic.",
    "“Food that is stale, flavourless, spoiled, or leftover, and unclean remnants — that is loved by the tāmasic.”"),
11: ("The sacrifice ordained by scripture, offered without desire for fruit by those who think 'this must be performed' — that is sāttvic.",
    "“A sacrifice offered according to scripture, without seeking reward, with the conviction that it must be done — that is sāttvic.”"),
12: ("But the sacrifice offered seeking fruit and for the sake of display, O best of the Bhāratas — know that as rājasic.",
    "“But a sacrifice offered for results or for show — know that as rājasic.”"),
13: ("The sacrifice without rule, without food-gifts, without mantra, without fees, devoid of faith — is declared tāmasic.",
    "“A sacrifice without proper rite, without offerings, without chants, without gifts, and without faith — that is tāmasic.”"),
14: ("Worship of the gods, the twice-born, teachers and the wise; purity, uprightness, chastity and non-violence — this is the austerity of the body.",
    "“Honouring the gods, the learned, teachers, and sages; purity, honesty, celibacy, and non-violence — this is bodily austerity.”"),
15: ("Speech that causes no distress, that is truthful, pleasant and beneficial, and the regular study of scripture — this is the austerity of speech.",
    "“Speech that is gentle, true, pleasant, and helpful, along with the daily recitation of scripture — this is the austerity of speech.”"),
16: ("Serenity of mind, gentleness, silence, self-control, and purity of heart — this is called the austerity of the mind.",
    "“A calm mind, kindness, silence, self-restraint, and inner purity — this is mental austerity.”"),
17: ("This threefold austerity, performed with supreme faith by the steadfast, without desire for fruit — is declared sāttvic.",
    "“This threefold discipline, practised with great faith by the resolute, expecting nothing in return — is called sāttvic.”"),
18: ("Austerity performed for honour, reverence and worship, and with hypocrisy — is here declared rājasic, unstable and transitory.",
    "“Penance done for fame, respect, and praise, and with hypocrisy — that is rājasic: unstable and fleeting.”"),
19: ("Austerity performed with foolish obstinacy, with self-torture, or to ruin another — is declared tāmasic.",
    "“Penance done out of foolish stubbornness, self-torment, or to hurt others — that is tāmasic.”"),
20: ("The gift given because it ought to be given, to one who can do nothing in return, at the right place and time, to a worthy person — is deemed sāttvic.",
    "“A gift given because it is right to give, to one who can never repay, at the proper place and time, to a deserving person — that is sāttvic.”"),
21: ("But the gift given expecting a return, or seeking fruit again, or reluctantly — is deemed rājasic.",
    "“A gift given expecting something back, seeking reward, or given grudgingly — that is rājasic.”"),
22: ("The gift given at the wrong place and time, to unworthy persons, without respect and with contempt — is declared tāmasic.",
    "“A gift given at the wrong time and place, to the undeserving, without respect or with disdain — that is tāmasic.”"),
23: ("Om Tat Sat — this is the threefold designation of Brahman; by it were ordained of old the brāhmaṇas, the Vedas and the sacrifices.",
    "“Om Tat Sat: three syllables that stand for Brahman. From them, in the beginning, came the brāhmaṇas, the Vedas and the rites.”"),
24: ("Therefore, uttering Om, the acts of sacrifice, gift and austerity ordained by rule are begun, ever, by the knowers of Brahman.",
    "“So the knowers of Brahman begin every act of sacrifice, charity, and penance — as scripture ordains — uttering Om.”"),
25: ("Uttering Tat, without desiring fruit, are the acts of sacrifice, austerity and the various acts of giving performed by seekers of liberation.",
    "“Seekers of freedom perform sacrifice, penance, and charity of every kind — saying Tat, seeking no reward.”"),
26: ("Sat is used in the sense of reality and goodness, and also in auspicious works, O Pārtha.",
    "“Sat means reality and goodness; it is also used of noble deeds, Arjuna.”"),
27: ("Steadfastness in sacrifice, austerity and giving is also called Sat; and action for the sake of that is called Sat.",
    "“Firmness in sacrifice, penance, and charity is called Sat; so is any action done for its sake.”"),
28: ("Whatever is offered, given or performed without faith, and whatever is done — is called Asat, O Pārtha; it is naught here or hereafter.",
    "“Anything offered, given, done, or performed without faith is called Asat — it is nothing here, and nothing after death.”"),
}
