# -*- coding: utf-8 -*-
"""gita_data18.py — Chapter 18 (Mokṣa-Sannyāsa Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH18_THEMES = [
    ("Arjuna asks: sannyāsa or tyāga?",
     "Arjuna asks the difference between renunciation and abandonment; Kṛṣṇa distinguishes sannyāsa from tyāga, and declares that tyāga is of three kinds.",
     [("Arjuna asks: what is renunciation?", "I wish to know the truth of renunciation, O mighty-armed one, and of abandonment, O Hṛṣīkeśa, and the difference between the two, O slayer of Keśin.", "18.01", "18.01"),
      ("Giving up desire, and giving up fruit", "The wise call the giving up of desired actions renunciation; the abandonment of all fruits of action the wise call tyāga.", "18.02", "18.02"),
      ("The schools of thought", "Some wise men say action is to be given up as evil; others say sacrifice, gift and austerity are not to be given up.", "18.03", "18.03"),
      ("Tyāga is of three kinds", "Hear my certain conclusion on tyāga, O best of the Bhāratas; for tyāga, O tiger among men, is declared to be of three kinds.", "18.04", "18.04")]),
    ("Sacrifice, gift and austerity must not be dropped",
     "Kṛṣṇa's ruling before the classification: these three purify even the wise and are never to be abandoned — but perform them giving up attachment and fruit.",
     [("Sacrifice, gift and austerity are not to be given up", "The acts of sacrifice, gift and austerity are not to be given up; they must be performed, for they purify even the wise.", "18.05", "18.05"),
      ("Without clinging to fruit", "But even these actions should be performed, giving up attachment and the fruits, O Pārtha — this is my certain and best conviction.", "18.06", "18.06")]),
    ("The three kinds of abandonment",
     "Having ruled that action must not be dropped, Kṛṣṇa classifies the dropping of it: through delusion is tāmasic, from fear of pain rājasic, and giving up only attachment and fruit is sāttvic.",
     [("Giving up duty through delusion is tāmasic", "The renunciation of prescribed action is not proper; abandoning it through delusion is declared tāmasic.", "18.07", "18.07"),
      ("Giving it up from fear of pain is rājasic", "He who gives up action because it brings pain, from fear of bodily suffering — performing the rājasic abandonment, he does not gain the fruit of renunciation.", "18.08", "18.08"),
      ("Doing it because it ought to be done", "But the prescribed action done because it ought to be done, O Arjuna, giving up attachment and fruit — that is deemed sāttvic abandonment.", "18.09", "18.09"),
      ("Neither dislikes nor craves", "The sāttvic renouncer, endowed with sattva and firm understanding, neither hates unpleasant action nor clings to pleasant.", "18.10", "18.10"),
      ("No one can give up all action", "Indeed, the embodied one cannot give up all actions entirely; but he who gives up the fruit of action is called a true renouncer.", "18.11", "18.11"),
      ("Three kinds of fruit", "The threefold fruit of action — pleasant, unpleasant and mixed — comes after death to the non-renouncer; but never to the renouncer.", "18.12", "18.12")]),
    ("The Five Causes of Action",
     "All action is accomplished by five causes: the body, the agent, the instruments, the efforts, and destiny.",
     [("Learn the five causes", "Learn from me, O mighty-armed one, these five causes of all action, declared in the philosophy of the end of action:", "18.13", "18.13"),
      ("Fate as the fifth", "— the seat, the agent, the instruments, the various efforts, and destiny, the fifth.", "18.14", "18.14"),
      ("Whatever action a man undertakes", "Whatever action a man undertakes with body, speech or mind — rightly or wrongly — these five are its causes.", "18.15", "18.15"),
      ("Who sees the Self alone as doer sees wrongly", "That being so, he who — with imperfect understanding — sees the Self alone as the agent, does not truly see.", "18.16", "18.16"),
      ("Free of ego, he slays and is not bound", "He whose mind is free from ego, whose intellect is not stained — though he slays these worlds, he slays not, nor is bound.", "18.17", "18.17"),
      ("Knowledge, action, agent", "Knowledge, the known and the knower — the threefold impulse to action; the instrument, the act and the agent — the threefold basis of action.", "18.18", "18.18")]),
    ("The guṇas divide knowledge itself",
     "Knowledge, action and agent are threefold by the guṇas — hear how they are distinguished.",
     [("The threefold knowledge", "Knowledge, action and agent are declared threefold by the distinction of the guṇas — hear them as they are in the enumeration of the guṇas.", "18.19", "18.19"),
      ("The Sāttvic knowledge", "That knowledge by which one sees one imperishable being in all beings, undivided in the divided — know that as sāttvic.", "18.20", "18.20"),
      ("Rājasic knowledge sees beings as separate", "But the knowledge that sees manifold and separate beings in all beings — know that as rājasic.", "18.21", "18.21"),
      ("Irrational, clinging to a part", "And the knowledge that clings to one single effect as if it were the whole, without reason, without truth, trivial — is declared tāmasic.", "18.22", "18.22")]),
    ("The three kinds of action",
     "Action itself divided by the guṇas: sāttvic is done as duty without craving its fruit; rājasic with great effort and ego; tāmasic begun in delusion, heedless of ruin.",
     [("Sāttvic action seeks no fruit", "Action done as prescribed, without attachment, without desire or aversion, by one who seeks no fruit — is declared sāttvic.", "18.23", "18.23"),
      ("Rājasic action seeks desire", "But action done with great effort, seeking the fulfilment of desires, full of ego — is declared rājasic.", "18.24", "18.24"),
      ("Done in delusion", "Action begun through delusion, heedless of consequence, of ruin and injury, and of one's own capacity — is declared tāmasic.", "18.25", "18.25")]),
    ("The three kinds of doer",
     "The same threefold cut applied to the agent: sāttvic is free of attachment and ego, unmoved by success or failure; rājasic is greedy and passionate; tāmasic is obstinate, deceitful and lazy.",
     [("The Sāttvic agent", "The agent free from attachment, free from ego, firm and zealous, unmoved by success and failure — is declared sāttvic.", "18.26", "18.26"),
      ("The rājasic agent", "The agent full of passion, longing for the fruit of action, greedy, cruel, impure, moved by joy and sorrow — is declared rājasic.", "18.27", "18.27"),
      ("Deceitful, lazy, stubborn", "The agent undisciplined, vulgar, obstinate, deceitful, malicious, lazy, despondent and procrastinating — is declared tāmasic.", "18.28", "18.28")]),
    ("The three kinds of intellect",
     "Buddhi, the power to discern: sāttvic knows action from inaction and bondage from freedom; rājasic sees right and wrong imperfectly; tāmasic, wrapped in darkness, takes wrong for right.",
     [("The threefold intellect", "Hear the threefold distinction of intellect and fortitude, declared fully and separately, by the guṇas, O Dhanañjaya.", "18.29", "18.29"),
      ("The sāttvic intellect", "The intellect that knows action and inaction, right and wrong, fear and fearlessness, bondage and liberation — is sāttvic.", "18.30", "18.30"),
      ("The rājasic intellect", "The intellect that knows right and wrong incorrectly — that, O Pārtha, is rājasic.", "18.31", "18.31"),
      ("Wrapped in darkness", "The intellect that, enveloped in darkness, takes wrong for right and sees all things perversely — is tāmasic.", "18.32", "18.32")]),
    ("The three kinds of resolve",
     "Dhṛti, the power to hold on: sāttvic holds mind, breath and senses unwavering; rājasic clings to duty, pleasure and wealth for their fruit; tāmasic will not let go of sleep, fear and grief.",
     [("The Sāttvic fortitude", "The unwavering fortitude by which one holds the activities of the mind, breath and senses — that, O Pārtha, is sāttvic.", "18.33", "18.33"),
      ("The rājasic fortitude", "But the fortitude by which one holds to duty, pleasure and wealth, attached and desiring fruit — that, O Arjuna, is rājasic.", "18.34", "18.34"),
      ("Holds on to sleep and fear", "The fortitude by which a dull man does not give up sleep, fear, grief, despair and arrogance — that is tāmasic.", "18.35", "18.35")]),
    ("Three kinds of happiness",
     "Happiness is threefold: the sāttvic, sweet like poison at first and nectar at the end; the rājasic, nectar at first and poison at the end; the tāmasic, born of sleep and sloth.",
     [("The threefold happiness", "Hear now from me, O bull of the Bhāratas, the threefold happiness — that in which one rejoices by practice and reaches the end of suffering.", "18.36", "18.36"),
      ("Nectar at last", "That which is like poison at first and nectar at the end — born of the clarity of the Self — is declared sāttvic happiness.", "18.37", "18.37"),
      ("Sweet at first, poison at last", "The happiness from the contact of the senses with their objects, nectar at first and poison at the end — is declared rājasic.", "18.38", "18.38"),
      ("Stupefies from beginning", "The happiness that deludes the soul at first and at the end, born of sleep, sloth and heedlessness — is declared tāmasic.", "18.39", "18.39")]),
    ("The four orders and their own duties",
     "No being on earth or in heaven is free from the three guṇas; the duties of brāhmaṇa, kṣatriya, vaiśya and śūdra are fixed by their natures.",
     [("No one free of the Guṇas", "There is no being on earth, nor among the gods in heaven, free from these three guṇas born of prakṛti.", "18.40", "18.40"),
      ("The fourfold duties", "The duties of brāhmaṇas, kṣatriyas, vaiśyas and śūdras are divided according to the qualities born of their own nature, O scorcher of foes.", "18.41", "18.41"),
      ("The brāhmaṇa's duty, born of his nature", "Tranquillity, self-control, austerity, purity, patience, uprightness, knowledge, wisdom and faith — the duty of the brāhmaṇa, born of his nature.", "18.42", "18.42"),
      ("The kṣatriya's duty, born of his nature", "Valour, splendour, fortitude, skill, not fleeing in battle, generosity and lordship — the duty of the kṣatriya, born of his nature.", "18.43", "18.43"),
      ("The vaiśya's and the śūdra's duty", "Agriculture, cattle-rearing and trade — the duty of the vaiśya, born of his nature; and service — the duty of the śūdra.", "18.44", "18.44")]),
    ("Perfection comes through your own duty",
     "Worshipping the Lord through one's own duty, one attains perfection; hearing how, one who does his own duty reaches the supreme.",
     [("Perfection through duty", "Devoted to his own duty, a man attains perfection — hear how one who delights in his own work attains perfection.", "18.45", "18.45"),
      ("Worships the source", "Worshipping, through his own duty, the source of all beings, by whom all this is pervaded — a man attains perfection.", "18.46", "18.46"),
      ("Better one's own duty", "Better is one's own dharma, though imperfect, than another's well-performed; doing the work born of his own nature, a man incurs no sin.", "18.47", "18.47"),
      ("All undertakings have defects", "One should not abandon one's natural work, O son of Kuntī, though it be faulty; for all undertakings are covered with fault, as fire with smoke.", "18.48", "18.48")]),
    ("The Way of Renunciation",
     "The unattached, self-conquered soul attains the perfection of freedom from action; the wise, becoming Brahman, neither grieves nor desires.",
     [("The freedom from action", "The unattached, self-conquered, desire-free one attains the supreme perfection of freedom from action, through renunciation.", "18.49", "18.49"),
      ("How one reaches Brahman", "Learn from me, O son of Kuntī, how one who has attained this perfection reaches Brahman — that supreme state of knowledge.", "18.50", "18.50"),
      ("Turning from sound", "Endowed with pure intellect, restraining the self with fortitude, giving up sound and the other objects, casting aside desire and aversion,", "18.51", "18.51"),
      ("Solitude, little food, restrained speech", "— dwelling in solitude, eating little, controlling speech, body and mind, ever engaged in meditation and contemplation,", "18.52", "18.52"),
      ("Freed from ego and force", "— free from ego, power, pride, desire, anger and possessiveness, tranquil, no longer claiming 'mine' — such a one becomes fit for Brahman.", "18.53", "18.53"),
      ("Become Brahman, he neither grieves nor desires", "Become Brahman, serene of soul, he neither grieves nor desires; equal to all beings, he attains supreme devotion to me.", "18.54", "18.54"),
      ("The final devotion", "By that devotion he knows me in truth, who and what I am; knowing me in truth, he enters me immediately.", "18.55", "18.55")]),
    ("Do all for me and reach the eternal",
     "Resting in me, doing all actions for me, one attains the eternal, imperishable state; but the ego-driven one, refusing to fight, is bound by his nature.",
     [("Rest in me", "Performing all actions ever, taking refuge in me, he attains the eternal, imperishable state by my grace.", "18.56", "18.56"),
      ("Surrender all actions to me", "Surrendering all actions to me in thought, making me supreme, resorting to the yoga of discernment, fix your mind on me.", "18.57", "18.57"),
      ("If from ego you will not listen, you perish", "With your mind on me, you shall cross all difficulties by my grace; but if from ego you will not listen, you shall be destroyed.", "18.58", "18.58"),
      ("Your nature will drive you", "If, relying on ego, you think 'I will not fight' — vain is your resolve; your nature will compel you.", "18.59", "18.59"),
      ("Your own nature will compel you", "Bound, O son of Kuntī, by your own action born of your nature, what you do not wish to do — that you will do helplessly.", "18.60", "18.60")]),
    ("The Lord dwells in the heart of all",
     "The Lord dwells in the hearts of all, causing all beings to revolve like puppets; take refuge in him alone and attain supreme peace.",
     [("The Lord in every heart", "The Lord dwells in the heart of all beings, O Arjuna, causing all beings to revolve by his māyā, as if mounted on a machine.", "18.61", "18.61"),
      ("Take refuge in him with all your being", "Take refuge in him alone with all your being, O Bhārata; by his grace you shall attain supreme peace and the eternal abode.", "18.62", "18.62")]),
    ("Surrender to me and I will free you",
     "Kṛṣṇa declares the most secret of all teachings: surrender to me alone and I will free you from all sins.",
     [("Reflect on it fully, then do as you will", "Thus I have declared to you the knowledge, more secret than the secret; reflect on it fully, and do as you will.", "18.63", "18.63"),
      ("The most secret", "Hear again my supreme word, the most secret of all: you are dearly loved by me, so I speak for your good.", "18.64", "18.64"),
      ("Fix your mind on me, be my devotee", "Fix your mind on me, be my devotee, offer to me, bow to me — you shall surely come to me; I promise you truly, for you are dear to me.", "18.65", "18.65"),
      ("Abandon all dharmas", "Abandon all dharmas and take refuge in me alone; I will free you from all sins — grieve not.", "18.66", "18.66")]),
    ("To Whom the Teaching Is Given",
     "This teaching is not for the austere, the faithless or the insincere; but he who teaches it to my devotees with devotion, and he who hears it with faith, are freed.",
     [("Not for the unworthy", "This is not to be spoken to one without austerity, nor to the faithless, nor to one who does not serve, nor to one who reviles me.", "18.67", "18.67"),
      ("The teacher's reward", "He who teaches this supreme secret to my devotees with supreme devotion — having given me his highest love, he shall come to me.", "18.68", "18.68"),
      ("No one dearer", "None among men does me greater service than he; and none shall be dearer to me on earth than he.", "18.69", "18.69"),
      ("The hearer's reward", "And he who studies this sacred dialogue of ours — by him I am worshipped with the sacrifice of knowledge; so I deem.", "18.70", "18.70"),
      ("Released and rejoices", "Even the man who hears it with faith, without carping — freed, he attains the auspicious worlds of the virtuous.", "18.71", "18.71")]),
    ("Arjuna answers: I will do your word",
     "Kṛṣṇa's last question and the answer the whole Gītā was spoken to produce: the delusion is destroyed, memory regained, doubt gone — I will do your word.",
     [("The Lord's question", "Has this been heard by you, O Pārtha, with a one-pointed mind? Has the delusion of ignorance been destroyed?", "18.72", "18.72"),
      ("My delusion is gone; I will do your word", "Destroyed is my delusion; I have gained memory by your grace, O Acyuta; I stand firm, my doubt gone — I will do your word.", "18.73", "18.73")]),
    ("Sañjaya tells what he heard",
     "The narrator steps forward: by Vyāsa's grace he heard this supreme secret from the Lord of yoga himself, and remembering the dialogue and that marvellous form, he rejoices again and again.",
     [("Thus I heard this wondrous dialogue", "Thus I heard the wondrous, thrilling dialogue of Vāsudeva and the great-souled Pārtha.", "18.74", "18.74"),
      ("The grace of Vyāsa", "By the grace of Vyāsa I heard this supreme, most secret yoga from Kṛṣṇa, the Lord of yoga, speaking himself.", "18.75", "18.75"),
      ("The joy of remembering", "Remembering again and again this wondrous, holy dialogue of Keśava and Arjuna, O king, I rejoice again and again.", "18.76", "18.76"),
      ("Remembering that form, I rejoice again", "And remembering again and again that most wondrous form of Hari, my wonder is great, O king — and I rejoice again and again.", "18.77", "18.77")]),
    ("Where Kṛṣṇa and Arjuna are, there is victory",
     "The final verse of the Gītā — Sañjaya's benediction: wherever the Lord of yoga and the archer stand together, there are prosperity, victory, glory and steadfast wisdom.",
     [("Where Kṛṣṇa and Arjuna are", "Wherever Kṛṣṇa, the Lord of yoga, and Pārtha, the archer, are — there are prosperity, victory, glory and constant wisdom; so I deem.", "18.78", "18.78")]),
]

CH18_TRANSLATIONS = {
1: ("Arjuna said: I wish to know the truth of renunciation, O mighty-armed one, and of abandonment, O Hṛṣīkeśa, and the difference between the two, O slayer of Keśin.",
    "Arjuna asks: “Please tell me the truth about sannyāsa and tyāga, Kṛṣṇa — and how they differ.”"),
2: ("The Blessed Lord said: The wise call the giving up of desired actions renunciation; the abandonment of all fruits of action the wise call tyāga.",
    "Kṛṣṇa said: “The wise call giving up selfish actions sannyāsa; giving up the fruits of all actions they call tyāga.”"),
3: ("Some wise men say action is to be given up as evil; others say sacrifice, gift and austerity are not to be given up.",
    "“Some thinkers call action itself evil and to be renounced; others say sacrifice, charity, and penance should never be abandoned.”"),
4: ("Hear my certain conclusion on tyāga, O best of the Bhāratas; for tyāga, O tiger among men, is declared to be of three kinds.",
    "“Hear my settled view on tyāga, Arjuna — for renunciation is said to be of three kinds.”"),
5: ("The acts of sacrifice, gift and austerity are not to be given up; they must be performed, for they purify even the wise.",
    "“Sacrifice, charity, and penance should never be renounced — they purify even the wise and must be performed.”"),
6: ("But even these actions should be performed, giving up attachment and the fruits, O Pārtha — this is my certain and best conviction.",
    "“Yet even these should be done without attachment and without longing for results — this is my firm and final view.”"),
7: ("The renunciation of prescribed action is not proper; abandoning it through delusion is declared tāmasic.",
    "“Renouncing one's prescribed duty is wrong — abandoning it out of confusion is tāmasic.”"),
8: ("He who gives up action because it brings pain, from fear of bodily suffering — performing the rājasic abandonment, he does not gain the fruit of renunciation.",
    "“One who drops a duty because it is hard or painful makes a rājasic renunciation and gains nothing from it.”"),
9: ("But the prescribed action done because it ought to be done, O Arjuna, giving up attachment and fruit — that is deemed sāttvic abandonment.",
    "“But when duty is done simply because it is duty, without clinging and without seeking results — that is sāttvic renunciation.”"),
10: ("The sāttvic renouncer, endowed with sattva and firm understanding, neither hates unpleasant action nor clings to pleasant.",
    "“The sāttvic renouncer, wise and clear, neither dislikes unpleasant work nor is attached to pleasant work.”"),
11: ("Indeed, the embodied one cannot give up all actions entirely; but he who gives up the fruit of action is called a true renouncer.",
    "“No embodied being can abandon action altogether; but one who renounces the fruits of action is a true renouncer.”"),
12: ("The threefold fruit of action — pleasant, unpleasant and mixed — comes after death to the non-renouncer; but never to the renouncer.",
    "“Cling to results and three kinds of fruit follow you past death — sweet, bitter and mixed. Let them go and none does.”"),
13: ("Learn from me, O mighty-armed one, these five causes of all action, declared in the philosophy of the end of action:",
    "“Learn from me the five factors of all action, as taught in the sāṅkhya of the Vedānta:”"),
14: ("— the seat, the agent, the instruments, the various efforts, and destiny, the fifth.",
    "“— the body, the doer, the senses, the various efforts, and fate as the fifth.”"),
15: ("Whatever action a man undertakes with body, speech or mind — rightly or wrongly — these five are its causes.",
    "“Anything you do — with your hands, your words or your thoughts, well or badly — has these five behind it.”"),
16: ("That being so, he who — with imperfect understanding — sees the Self alone as the agent, does not truly see.",
    "“Therefore, one who, with limited vision, thinks the Self alone is the doer — he does not see rightly.”"),
17: ("He whose mind is free from ego, whose intellect is not stained — though he slays these worlds, he slays not, nor is bound.",
    "“One free of ego, with an unstained intellect — even killing these people, he kills nothing and is not bound.”"),
18: ("Knowledge, the known and the knower — the threefold impulse to action; the instrument, the act and the agent — the threefold basis of action.",
    "“Knowledge, the object, and the knower form the threefold spur to action; the instrument, the deed, and the doer are its threefold basis.”"),
19: ("Knowledge, action and agent are declared threefold by the distinction of the guṇas — hear them as they are in the enumeration of the guṇas.",
    "“Knowledge, action, and doer are each said to be of three kinds, by the qualities — hear them fully.”"),
20: ("That knowledge by which one sees one imperishable being in all beings, undivided in the divided — know that as sāttvic.",
    "“See one undying life in every living thing, whole in each though the forms differ: that seeing is sāttvic.”"),
21: ("But the knowledge that sees manifold and separate beings in all beings — know that as rājasic.",
    "“But the knowledge that sees all beings as many and separate — that is rājasic.”"),
22: ("And the knowledge that clings to one single effect as if it were the whole, without reason, without truth, trivial — is declared tāmasic.",
    "“And the knowledge that clings to one small part as if it were all, irrational, untrue, and shallow — that is tāmasic.”"),
23: ("Action done as prescribed, without attachment, without desire or aversion, by one who seeks no fruit — is declared sāttvic.",
    "“An action done as duty, without attachment, without liking or disliking, by one who wants no reward — that is sāttvic.”"),
24: ("But action done with great effort, seeking the fulfilment of desires, full of ego — is declared rājasic.",
    "“Action done with great strain, craving desires, and full of self-importance — that is rājasic.”"),
25: ("Action begun through delusion, heedless of consequence, of ruin and injury, and of one's own capacity — is declared tāmasic.",
    "“Action begun in delusion, ignoring its consequences, the harm it causes, and one's own strength — that is tāmasic.”"),
26: ("The agent free from attachment, free from ego, firm and zealous, unmoved by success and failure — is declared sāttvic.",
    "“The doer who is unattached, ego-free, steady and energetic, untouched by success or failure — that doer is sāttvic.”"),
27: ("The agent full of passion, longing for the fruit of action, greedy, cruel, impure, moved by joy and sorrow — is declared rājasic.",
    "“The doer who is passionate, hungry for results, greedy, cruel, impure, swayed by elation and despair — that doer is rājasic.”"),
28: ("The agent undisciplined, vulgar, obstinate, deceitful, malicious, lazy, despondent and procrastinating — is declared tāmasic.",
    "“The doer who is undisciplined, coarse, stubborn, deceitful, dishonest, lazy, morose, and slow — that doer is tāmasic.”"),
29: ("Hear the threefold distinction of intellect and fortitude, declared fully and separately, by the guṇas, O Dhanañjaya.",
    "“Now hear, Arjuna, how intellect and resolve, in their three forms according to the qualities, are distinguished.”"),
30: ("The intellect that knows action and inaction, right and wrong, fear and fearlessness, bondage and liberation — is sāttvic.",
    "“The understanding that knows what is to be done and not done, what is right and wrong, bondage and freedom — that is sāttvic.”"),
31: ("The intellect that knows right and wrong incorrectly — that, O Pārtha, is rājasic.",
    "“The understanding that confuses right and wrong — that, Arjuna, is rājasic.”"),
32: ("The intellect that, enveloped in darkness, takes wrong for right and sees all things perversely — is tāmasic.",
    "“The understanding that, wrapped in darkness, mistakes wrong for right and turns everything upside-down — that is tāmasic.”"),
33: ("The unwavering fortitude by which one holds the activities of the mind, breath and senses — that, O Pārtha, is sāttvic.",
    "“The steady resolve by which one keeps the mind, breath, and senses in check — that, Arjuna, is sāttvic.”"),
34: ("But the fortitude by which one holds to duty, pleasure and wealth, attached and desiring fruit — that, O Arjuna, is rājasic.",
    "“But the resolve that clings to duty, pleasure, and wealth, eager for their rewards — that is rājasic.”"),
35: ("The fortitude by which a dull man does not give up sleep, fear, grief, despair and arrogance — that is tāmasic.",
    "“And the resolve by which a foolish person cannot let go of sleep, fear, sorrow, gloom, and vanity — that is tāmasic.”"),
36: ("Hear now from me, O bull of the Bhāratas, the threefold happiness — that in which one rejoices by practice and reaches the end of suffering.",
    "“Now hear of happiness in its three forms, Arjuna — the joy in which one delights by practice and comes to the end of pain.”"),
37: ("That which is like poison at first and nectar at the end — born of the clarity of the Self — is declared sāttvic happiness.",
    "“The joy that is bitter at first but nectar at last — born of Self-knowledge — is sāttvic happiness.”"),
38: ("The happiness from the contact of the senses with their objects, nectar at first and poison at the end — is declared rājasic.",
    "“The pleasure of the senses meeting their objects, sweet at first but poison at last — that is rājasic.”"),
39: ("The happiness that deludes the soul at first and at the end, born of sleep, sloth and heedlessness — is declared tāmasic.",
    "“The joy that stupefies the soul from beginning to end, born of sleep, laziness, and carelessness — that is tāmasic.”"),
40: ("There is no being on earth, nor among the gods in heaven, free from these three guṇas born of prakṛti.",
    "“No one on earth — not even the gods in heaven — is free of these three qualities of nature.”"),
41: ("The duties of brāhmaṇas, kṣatriyas, vaiśyas and śūdras are divided according to the qualities born of their own nature, O scorcher of foes.",
    "“The duties of the four orders — priest, warrior, merchant, worker — are set by the qualities of their own nature.”"),
42: ("Tranquillity, self-control, austerity, purity, patience, uprightness, knowledge, wisdom and faith — the duty of the brāhmaṇa, born of his nature.",
    "“Calm, self-restraint, penance, purity, patience, honesty, knowledge, wisdom, and faith — these are the natural duties of a brāhmaṇa.”"),
43: ("Valour, splendour, fortitude, skill, not fleeing in battle, generosity and lordship — the duty of the kṣatriya, born of his nature.",
    "“Courage, brilliance, firmness, skill, not retreating in battle, generosity, and leadership — these are the natural duties of a warrior.”"),
44: ("Agriculture, cattle-rearing and trade — the duty of the vaiśya, born of his nature; and service — the duty of the śūdra.",
    "“Farming, herding, and trade are the natural work of the vaiśya; service, that of the śūdra.”"),
45: ("Devoted to his own duty, a man attains perfection — hear how one who delights in his own work attains perfection.",
    "“By doing one's own duty one reaches perfection — hear how the one who rejoices in his own work succeeds.”"),
46: ("Worshipping, through his own duty, the source of all beings, by whom all this is pervaded — a man attains perfection.",
    "“Doing his own duty, a person worships the One from whom all beings arise and by whom all is pervaded — and so reaches perfection.”"),
47: ("Better is one's own dharma, though imperfect, than another's well-performed; doing the work born of his own nature, a man incurs no sin.",
    "“Better to do your own duty poorly than another's perfectly. Following the work natural to you, you gather no sin.”"),
48: ("One should not abandon one's natural work, O son of Kuntī, though it be faulty; for all undertakings are covered with fault, as fire with smoke.",
    "“Never abandon the work born of your nature, even with its defects — all ventures are tinged with fault, as fire is veiled by smoke.”"),
49: ("The unattached, self-conquered, desire-free one attains the supreme perfection of freedom from action, through renunciation.",
    "“One who is unattached, self-mastered, and free from craving reaches, by renunciation, the highest perfection of actionlessness.”"),
50: ("Learn from me, O son of Kuntī, how one who has attained this perfection reaches Brahman — that supreme state of knowledge.",
    "“Hear from me, Arjuna, how one who has reached this perfection goes on to Brahman — the highest state of wisdom.”"),
51: ("Endowed with pure intellect, restraining the self with fortitude, giving up sound and the other objects, casting aside desire and aversion,",
    "“With a purified mind, holding the self firm, turning from sound and the other senses' objects, setting aside liking and disliking,”"),
52: ("— dwelling in solitude, eating little, controlling speech, body and mind, ever engaged in meditation and contemplation,",
    "“— living apart, eating lightly, master of speech, body, and mind, ever intent on meditation,”"),
53: ("— free from ego, power, pride, desire, anger and possessiveness, tranquil, no longer claiming 'mine' — such a one becomes fit for Brahman.",
    "“— freed from ego, force, pride, lust, anger, and grasping, calm and without possessiveness — such a one becomes worthy of Brahman.”"),
54: ("Become Brahman, serene of soul, he neither grieves nor desires; equal to all beings, he attains supreme devotion to me.",
    "“United with Brahman, tranquil in heart, he neither mourns nor craves; seeing all equally, he wins the highest devotion to me.”"),
55: ("By that devotion he knows me in truth, who and what I am; knowing me in truth, he enters me immediately.",
    "“Through that devotion he truly knows me — what and who I am; and knowing me truly, he enters me at once.”"),
56: ("Performing all actions ever, taking refuge in me, he attains the eternal, imperishable state by my grace.",
    "“Always doing all actions, resting on me, he reaches the eternal, changeless state by my grace.”"),
57: ("Surrendering all actions to me in thought, making me supreme, resorting to the yoga of discernment, fix your mind on me.",
    "“Offer every action to me in mind, hold me supreme, and relying on wisdom-yoga, keep your heart on me.”"),
58: ("With your mind on me, you shall cross all difficulties by my grace; but if from ego you will not listen, you shall be destroyed.",
    "“With your mind fixed on me, you will cross all obstacles by my grace. But if, in ego, you refuse — you will be lost.”"),
59: ("If, relying on ego, you think 'I will not fight' — vain is your resolve; your nature will compel you.",
    "“If, full of ego, you think, 'I will not fight' — that resolve is futile; your own nature will force you.”"),
60: ("Bound, O son of Kuntī, by your own action born of your nature, what you do not wish to do — that you will do helplessly.",
    "“Bound by the karma born of your own nature, Arjuna, you will do, helplessly, what you do not want to do.”"),
61: ("The Lord dwells in the heart of all beings, O Arjuna, causing all beings to revolve by his māyā, as if mounted on a machine.",
    "“The Lord resides in the heart of every being, spinning all creatures on the wheel of his power, like puppets on a machine.”"),
62: ("Take refuge in him alone with all your being, O Bhārata; by his grace you shall attain supreme peace and the eternal abode.",
    "“Surrender to him alone with all your heart, Arjuna; by his grace you will find supreme peace and the eternal home.”"),
63: ("Thus I have declared to you the knowledge, more secret than the secret; reflect on it fully, and do as you will.",
    "“So I have taught you this wisdom, more secret than secrecy itself. Ponder it fully — then act as you choose.”"),
64: ("Hear again my supreme word, the most secret of all: you are dearly loved by me, so I speak for your good.",
    "“Now hear my final, most hidden word: you are very dear to me, so I speak this for your good.”"),
65: ("Fix your mind on me, be my devotee, offer to me, bow to me — you shall surely come to me; I promise you truly, for you are dear to me.",
    "“Set your heart on me, worship me, sacrifice to me, bow to me — you will surely reach me. This I promise, for you are dear to me.”"),
66: ("Abandon all dharmas and take refuge in me alone; I will free you from all sins — grieve not.",
    "“Give up all other paths and surrender to me alone. I will release you from all sin — do not grieve.”"),
67: ("This is not to be spoken to one without austerity, nor to the faithless, nor to one who does not serve, nor to one who reviles me.",
    "“Do not teach this to one who lacks discipline, to the faithless, to the unwilling, or to one who despises me.”"),
68: ("He who teaches this supreme secret to my devotees with supreme devotion — having given me his highest love, he shall come to me.",
    "“One who shares this supreme secret with my devotees, out of love for me — giving me his deepest devotion — will reach me.”"),
69: ("None among men does me greater service than he; and none shall be dearer to me on earth than he.",
    "“No one serves me more than such a teacher; no one will be dearer to me than he.”"),
70: ("And he who studies this sacred dialogue of ours — by him I am worshipped with the sacrifice of knowledge; so I deem.",
    "“And whoever studies this holy dialogue of ours — I deem him to have worshipped me with the sacrifice of wisdom.”"),
71: ("Even the man who hears it with faith, without carping — freed, he attains the auspicious worlds of the virtuous.",
    "“Even one who merely listens with faith and without envy is released and reaches the blissful worlds of the righteous.”"),
72: ("Has this been heard by you, O Pārtha, with a one-pointed mind? Has the delusion of ignorance been destroyed?",
    "“Did you hear this with full attention, Arjuna? Has the confusion of ignorance been dispelled?”"),
73: ("Arjuna said: Destroyed is my delusion; I have gained memory by your grace, O Acyuta; I stand firm, my doubt gone — I will do your word.",
    "Arjuna replies: “My delusion is gone; by your grace I have regained memory, O changeless Lord. I stand firm, free of doubt — I will follow your command.”"),
74: ("Sañjaya said: Thus I heard the wondrous, thrilling dialogue of Vāsudeva and the great-souled Pārtha.",
    "Sañjaya narrates: “Thus I heard the wonderful, hair-raising conversation of Vāsudeva and the noble Pārtha.”"),
75: ("By the grace of Vyāsa I heard this supreme, most secret yoga from Kṛṣṇa, the Lord of yoga, speaking himself.",
    "“By Vyāsa's grace I heard this supreme, secret yoga from Kṛṣṇa himself, the master of yoga.”"),
76: ("Remembering again and again this wondrous, holy dialogue of Keśava and Arjuna, O king, I rejoice again and again.",
    "“Recalling again and again this wonderful and sacred dialogue between Keśava and Arjuna, O king, I thrill with joy.”"),
77: ("And remembering again and again that most wondrous form of Hari, my wonder is great, O king — and I rejoice again and again.",
    "“And remembering, again and again, that most marvellous form of the Lord, I am filled with wonder and delight.”"),
78: ("Wherever Kṛṣṇa, the Lord of yoga, and Pārtha, the archer, are — there are prosperity, victory, glory and constant wisdom; so I deem.",
    "“Where Kṛṣṇa, the Lord of yoga, and Arjuna, the archer, stand — there are fortune, victory, abundance, and unwavering wisdom. This is my conviction.”"),
}
