# -*- coding: utf-8 -*-
"""gita_data3.py — Chapter 3 (Karma Yoga) themes and translations (literal + paraphrase).
Aligned to the Śaṅkara-bhāṣya readings."""

# Theme structure: (title, desc, [(part_title, part_desc, start, end), ...])
CH3_THEMES = [
    ("Arjuna asks: why urge me to war?",
     "If wisdom is better than action, why does Kṛṣṇa urge this dreadful war? Arjuna asks for one clear answer.",
     [("Why engage me in this dreadful action?", "If, O Janārdana, wisdom is considered by you to be superior to action, then why, O Keśava, do you engage me in this dreadful action?", "3.01", "3.01"),
      ("Tell me one thing decisively", "With words that appear equivocal you seem to confuse my intellect. Tell me one thing decisively, by which I may attain the good.", "3.02", "3.02")]),
    ("Knowledge for Some, Action for Others",
     "A twofold steadfastness was declared by me of old: jñāna-yoga for the Sāṅkhyas, karma-yoga for the yogis.",
     [("Knowledge for some, action for others", "In this world a twofold path of steadfastness was declared by me of old, O sinless one: the yoga of knowledge for the Sāṅkhyas, and the yoga of action for the yogis.", "3.03", "3.03"),
      ("Not by abstaining", "Not by the non-performance of actions does one attain freedom from action, nor by mere renunciation alone does one reach perfection.", "3.04", "3.04"),
      ("No one can sit idle", "Indeed no one ever remains actionless even for a moment; everyone is made to act, helpless, by the guṇas born of prakṛti.", "3.05", "3.05")]),
    ("Act Unattached, Not Idle",
     "The hypocrite idles in body while the mind craves; the true yogi acts with the body, unattached, and excels.",
     [("Still in body, craving in mind", "He who, restraining the organs of action, sits recollecting sense objects in his mind — that deluded one is called a hypocrite.", "3.06", "3.06"),
      ("He who acts unattached excels", "But he who, controlling the senses by the mind, undertakes karma-yoga with the organs of action, unattached — he excels.", "3.07", "3.07"),
      ("Do the allotted duty", "Perform your prescribed action, for action is superior to inaction; even the maintenance of the body would not be accomplished by inaction.", "3.08", "3.08"),
      ("Act for sacrifice alone", "The world is bound by action, except action performed for the sake of sacrifice; for that purpose, O son of Kuntī, perform action free from attachment.", "3.09", "3.09")]),
    ("Prajāpati's gift: the wheel of sacrifice",
     "Created with sacrifice, beings were told: by this shall you prosper; nourish the gods and they will nourish you.",
     [("Prajāpati made beings with sacrifice", "Having created creatures together with sacrifice from the beginning, Prajāpati declared: “By this shall you prosper; may this be to you the cow of desires.", "3.10", "3.10"),
      ("Serve and be sustained", "With this nourish the gods, and may the gods nourish you; nourishing one another, you shall attain the highest good.", "3.11", "3.11"),
      ("He who enjoys without giving is a thief", "Nourished by sacrifice, the gods will give you the joys you desire; he who enjoys what they have given without offering back to them is verily a thief.", "3.12", "3.12"),
      ("The leftovers cleanse", "The good who eat the remnants of sacrifice are released from all sins; but the wicked who cook for their own sake verily eat sin.", "3.13", "3.13")]),
    ("Who Does Not Turn the Wheel Lives in Vain",
     "He who does not follow the wheel thus set in motion, delighting in the senses, lives in vain.",
     [("From food, from rain, from sacrifice", "Beings arise from food; food arises from rain; rain arises from sacrifice; sacrifice arises from action.", "3.14", "3.14"),
      ("Action arises from Brahman", "Know that action arises from Brahman, and Brahman from the Imperishable; therefore the all-pervading Brahman is ever established in sacrifice.", "3.15", "3.15"),
      ("Who does not turn the wheel lives in vain", "He who does not follow here this wheel thus set in motion, whose life is sin, delighting in the senses — lives in vain, O Pārtha.", "3.16", "3.16")]),
    ("Nothing to Do, Yet Act",
     "For one content in the Self there is nothing to gain or lose; therefore act unattached — always do the duty at hand.",
     [("For him there is nothing left to do", "But the man who rejoices only in the Self, is gratified with the Self, and is content in the Self alone — for him there is nothing to do.", "3.17", "3.17"),
      ("Nothing to gain or lose", "For him there is no purpose in what has been done or not done, nor does he depend on any being for any purpose.", "3.18", "3.18"),
      ("Therefore act, unattached", "Therefore, always perform the action that is your duty, unattached; for performing action without attachment, a man attains the Supreme.", "3.19", "3.19")]),
    ("As the Great One Does, So the World",
     "Janaka attained by action; whatever the best sets as standard, the world follows — Kṛṣṇa acts though he needs nothing, lest the worlds perish.",
     [("Janaka attained by action", "Indeed by action alone did Janaka and others attain perfection; even having regard for the welfare of the world, you should act.", "3.20", "3.20"),
      ("As the great one does, so do others", "Whatever the best person does, that indeed the common person does; whatever he makes the standard, the world follows.", "3.21", "3.21"),
      ("Nothing I need, yet I act", "For me, O Pārtha, there is nothing to be done in the three worlds, nothing unattained to be attained — yet I continue to act.", "3.22", "3.22"),
      ("All would follow my example", "If I did not engage in action ever, untiringly, then people would follow my path in all respects, O Pārtha.", "3.23", "3.23"),
      ("These worlds would perish", "These worlds would perish if I did not perform action; I would be the maker of chaos and would destroy these creatures.", "3.24", "3.24")]),
    ("The Wise Act Unattached",
     "As the unwise act attached, so the wise act unattached; the guṇas are the doers — the knower does not unsettle the partial knowers.",
     [("Act as the unwise act — But unattached", "As the unwise act, attached to action, O Bhārata, so should the wise act, unattached, desiring the welfare of the world.", "3.25", "3.25"),
      ("Do not unsettle the ignorant", "Let him not create disturbance in the minds of the ignorant who are attached to action; acting himself with devotion, let him make them do all actions.", "3.26", "3.26"),
      ("The Guṇas are the doers", "All actions are performed by the guṇas of prakṛti in every way; the one deluded by egoism thinks, “I am the doer.", "3.27", "3.27"),
      ("Qualities act on qualities", "But the knower of truth, O mighty-armed, knowing the distinction of the guṇas and actions, and that the guṇas move among the guṇas, does not become attached.", "3.28", "3.28"),
      ("Let the knower not disturb them", "Those deluded by the guṇas of prakṛti cling to actions born of the guṇas; the one of complete knowledge should not unsettle the dull-witted, partial knowers.", "3.29", "3.29")]),
    ("Surrender All Actions to Me",
     "Renouncing all actions in Me, fixed on the Self, free from fever — fight; those who follow this teaching with faith are released.",
     [("Renouncing all actions in me, fight", "Renouncing all actions in me, with the mind fixed on the Self, being free from desire and from possessiveness, fight — free from fever.", "3.30", "3.30"),
      ("Those who follow it are freed", "Those men who always follow this teaching of mine with faith, without finding fault, are released even from the bondage of action.", "3.31", "3.31"),
      ("Those who scoff at it are lost", "But those who, finding fault, do not follow this teaching of mine — know them as deprived of all wisdom, ruined, and without understanding.", "3.32", "3.32")]),
    ("Follow Your Own Nature",
     "All act according to nature; attraction and aversion waylay the senses — better one's own dharma, though flawed, than another's well performed.",
     [("Even the wise follow their nature", "Even a man of knowledge acts according to his own nature; beings follow their nature — what will restraint accomplish?", "3.33", "3.33"),
      ("Attraction and aversion lie in wait", "Attachment and aversion are fixed regarding the object of each sense; let one not come under their power, for they are one's waylayers.", "3.34", "3.34"),
      ("Better one's own dharma, though flawed", "Better is one's own dharma, though defective, than another's well-performed; death in one's own dharma is better — another's dharma brings fear.", "3.35", "3.35")]),
    ("Desire, the All-Devouring Enemy",
     "Impelled by what does one commit evil? By desire and anger, born of rajas — smoke on fire, dust on a mirror, the womb about the embryo.",
     [("Arjuna asks what drives a man to sin", "Then, impelled by what, O Vārṣṇeya, does a man commit evil, even against his will, as though forced by power?", "3.36", "3.36"),
      ("Desire and anger, the all-devourer", "It is desire, it is anger, born of the rajo-guṇa; all-devouring, greatly sinful — know this as the enemy here.", "3.37", "3.37"),
      ("Smoke, dust, and the womb", "As fire is enveloped by smoke, and a mirror by dust, and an embryo by its membrane, so is this covered by that (desire).", "3.38", "3.38"),
      ("Desire covers wisdom like fire", "Wisdom is covered by this constant enemy of the wise, having the form of desire, which is insatiable, O son of Kuntī, like fire.", "3.39", "3.39")]),
    ("Slay desire, the enemy within",
     "Knowing Him beyond the intellect, steadying the self by the Self, slay this enemy in the form of desire, so hard to conquer.",
     [("Its seat: Senses, mind, intellect", "The senses, the mind and the intellect are said to be its seat; covering wisdom by these, it deludes the embodied soul.", "3.40", "3.40"),
      ("Rein in the senses first", "Therefore, O bull of the Bhāratas, first controlling the senses, cast off this sinner, the destroyer of knowledge and discrimination.", "3.41", "3.41"),
      ("Higher than the intellect is he", "They say the senses are higher; higher than the senses is the mind; higher than the mind is the intellect; but higher than the intellect is He (the Self).", "3.42", "3.42"),
      ("Slay the enemy", "Thus knowing Him who is beyond the intellect, restraining the self by the Self, O mighty-armed one, slay the enemy having the form of desire, so difficult to conquer.", "3.43", "3.43")]),
]

CH3_TRANSLATIONS = {
1: ("Arjuna said: If, O Janārdana, wisdom is considered by you to be superior to action, then why, O Keśava, do you engage me in this dreadful action?",
    "Arjuna asks: “If you think knowledge is better than action, then why are you pushing me into this terrible war, Keśava?”"),
2: ("With words that appear equivocal you seem to confuse my intellect. Tell me one thing decisively, by which I may attain the good.",
    "“Your words seem mixed and contradictory — they only confuse me. Tell me plainly the single path by which I can reach what is truly good.”"),
3: ("The Blessed Lord said: In this world a twofold path of steadfastness was declared by me of old, O sinless one: the yoga of knowledge for the Sāṅkhyas, and the yoga of action for the yogis.",
    "Kṛṣṇa said: “Long ago I taught two paths, blameless one: the way of knowledge for the contemplative, the way of selfless action for the active yogi.”"),
4: ("Not by the non-performance of actions does one attain freedom from action, nor by mere renunciation alone does one reach perfection.",
    "“You do not become free of action by refusing to act, nor does giving up the world by itself bring perfection.”"),
5: ("Indeed no one ever remains actionless even for a moment; everyone is made to act, helpless, by the guṇas born of prakṛti.",
    "“Nobody can sit idle even for a second — the forces of nature (the guṇas) compel everyone, willing or not, to act.”"),
6: ("He who, restraining the organs of action, sits recollecting sense objects in his mind — that deluded one is called a hypocrite.",
    "“Someone who keeps the hands idle but lets the mind dwell on pleasures is a self-deceived pretender.”"),
7: ("But he who, controlling the senses by the mind, undertakes karma-yoga with the organs of action, unattached — he excels.",
    "“But one who disciplines the senses with the mind and then acts with his body, without attachment — that person truly excels.”"),
8: ("Perform your prescribed action, for action is superior to inaction; even the maintenance of the body would not be accomplished by inaction.",
    "“Do the duty allotted to you, for action beats inaction — without some action, even keeping the body alive is impossible.”"),
9: ("The world is bound by action, except action performed for the sake of sacrifice; for that purpose, O son of Kuntī, perform action free from attachment.",
    "“Action done for selfish gain binds you; only action offered as sacrifice frees you. So act for that purpose, unattached, Arjuna.”"),
10: ("Having created creatures together with sacrifice from the beginning, Prajāpati declared: “By this shall you prosper; may this be to you the cow of desires.”",
    "“In the beginning the Creator gave humanity the practice of sacrifice: ‘Through this you will flourish; it will grant you all your needs.’”"),
11: ("With this nourish the gods, and may the gods nourish you; nourishing one another, you shall attain the highest good.",
    "“Serve the higher powers through sacrifice and they will sustain you in return — in this mutual giving all reach the highest good.”"),
12: ("Nourished by sacrifice, the gods will give you the joys you desire; he who enjoys what they have given without offering back to them is verily a thief.",
    "“The gods, pleased by your offering, grant you the good things of life. Enjoy their gifts without giving back and you are a thief.”"),
13: ("The good who eat the remnants of sacrifice are released from all sins; but the wicked who cook for their own sake verily eat sin.",
    "“Those who share the leftovers of the offering are cleansed of sin; those who cook only for themselves eat nothing but sin.”"),
14: ("Beings arise from food; food arises from rain; rain arises from sacrifice; sacrifice arises from action.",
    "“Life comes from food, food from rain, rain from sacrifice, and sacrifice from right action — everything is linked in one chain.”"),
15: ("Know that action arises from Brahman, and Brahman from the Imperishable; therefore the all-pervading Brahman is ever established in sacrifice.",
    "“All action springs from the eternal Brahman; hence the all-pervading Absolute is ever present in selfless offering.”"),
16: ("He who does not follow here this wheel thus set in motion, whose life is sin, delighting in the senses — lives in vain, O Pārtha.",
    "“Refuse to take part in this cycle of giving and receiving, and your life is wasted, Arjuna — you live only for your senses.”"),
17: ("But the man who rejoices only in the Self, is gratified with the Self, and is content in the Self alone — for him there is nothing to do.",
    "“One who is wholly happy within himself has nothing left to do — no duty remains for him.”"),
18: ("For him there is no purpose in what has been done or not done, nor does he depend on any being for any purpose.",
    "“Such a person gains nothing from doing or not doing; no creature or goal holds any sway over him.”"),
19: ("Therefore, always perform the action that is your duty, unattached; for performing action without attachment, a man attains the Supreme.",
    "“So keep acting, but never cling to the results — acting without attachment is the way to reach the Highest.”"),
20: ("Indeed by action alone did Janaka and others attain perfection; even having regard for the welfare of the world, you should act.",
    "“King Janaka and many others reached perfection through action itself. For the good of the world, you too must act.”"),
21: ("Whatever the best person does, that indeed the common person does; whatever he makes the standard, the world follows.",
    "“People imitate their leaders. Whatever the best among you do becomes the rule others follow.”"),
22: ("For me, O Pārtha, there is nothing to be done in the three worlds, nothing unattained to be attained — yet I continue to act.",
    "“I have nothing left to gain in all the three worlds — and still I keep working.”"),
23: ("If I did not engage in action ever, untiringly, then people would follow my path in all respects, O Pārtha.",
    "“If I ever stopped working, everyone would follow my example and give up their duties too.”"),
24: ("These worlds would perish if I did not perform action; I would be the maker of chaos and would destroy these creatures.",
    "“If I stopped acting, the worlds would collapse — and I would be the one who ruined them.”"),
25: ("As the unwise act, attached to action, O Bhārata, so should the wise act, unattached, desiring the welfare of the world.",
    "“The ignorant cling to their work; the wise work just as much but without clinging — for the good of everyone.”"),
26: ("Let him not create disturbance in the minds of the ignorant who are attached to action; acting himself with devotion, let him make them do all actions.",
    "“Don't confuse people who are attached to their duties. Do your own work with devotion — and let them learn from your example.”"),
27: ("All actions are performed by the guṇas of prakṛti in every way; the one deluded by egoism thinks, “I am the doer.”",
    "“Nature's forces do everything through you. The ego-driven person falsely believes, ‘I am the one doing this.’”"),
28: ("But the knower of truth, O mighty-armed, knowing the distinction of the guṇas and actions, and that the guṇas move among the guṇas, does not become attached.",
    "“The wise understand that qualities interact with qualities — they never identify themselves with the action.”"),
29: ("Those deluded by the guṇas of prakṛti cling to actions born of the guṇas; the one of complete knowledge should not unsettle the dull-witted, partial knowers.",
    "“Ignorant people get attached to their work; the enlightened should not disturb them by preaching renunciation.”"),
30: ("Renouncing all actions in me, with the mind fixed on the Self, being free from desire and from possessiveness, fight — free from fever.",
    "“Offer every action to me, keep the mind on the Self, drop all craving and possessiveness — and fight without agitation.”"),
31: ("Those men who always follow this teaching of mine with faith, without finding fault, are released even from the bondage of action.",
    "“Whoever follows my teaching with trust and no resentment is freed from the grip of karma.”"),
32: ("But those who, finding fault, do not follow this teaching of mine — know them as deprived of all wisdom, ruined, and without understanding.",
    "“Those who resent and reject my teaching are lost — bereft of wisdom, they destroy themselves.”"),
33: ("Even a man of knowledge acts according to his own nature; beings follow their nature — what will restraint accomplish?",
    "“Everyone, even the wise, acts from their own nature. Beings follow it — so what is the use of forcing yourself?”"),
34: ("Attachment and aversion are fixed regarding the object of each sense; let one not come under their power, for they are one's waylayers.",
    "“Liking and disliking cling to every sense-object. Don't let them rule you — they ambush the spiritual path.”"),
35: ("Better is one's own dharma, though defective, than another's well-performed; death in one's own dharma is better — another's dharma brings fear.",
    "“It is better to do your own duty imperfectly than someone else's perfectly. Even dying at your own post is better than living in fear doing another's work.”"),
36: ("Arjuna said: Then, impelled by what, O Vārṣṇeya, does a man commit evil, even against his will, as though forced by power?",
    "Arjuna asks: “What force makes a person sin even when he doesn't want to, as if dragged into it against his will?”"),
37: ("The Blessed Lord said: It is desire, it is anger, born of the rajo-guṇa; all-devouring, greatly sinful — know this as the enemy here.",
    "Kṛṣṇa said: “It is desire — and the anger born of it — springing from passion. Insatiable and immensely sinful: know this as your real enemy.”"),
38: ("As fire is enveloped by smoke, and a mirror by dust, and an embryo by its membrane, so is this covered by that (desire).",
    "“Desire obscures wisdom the way smoke hides fire, dust hides a mirror, and a membrane hides an embryo.”"),
39: ("Wisdom is covered by this constant enemy of the wise, having the form of desire, which is insatiable, O son of Kuntī, like fire.",
    "“This eternal enemy — desire — shrouds wisdom. It is never satisfied; it burns like fire, Arjuna.”"),
40: ("The senses, the mind and the intellect are said to be its seat; covering wisdom by these, it deludes the embodied soul.",
    "“Desire lives in the senses, the mind, and the intellect — and through them it blinds and deludes the embodied being.”"),
41: ("Therefore, O bull of the Bhāratas, first controlling the senses, cast off this sinner, the destroyer of knowledge and discrimination.",
    "“So first rein in your senses, Arjuna, and kill this evil one that destroys both knowledge and wisdom.”"),
42: ("They say the senses are higher; higher than the senses is the mind; higher than the mind is the intellect; but higher than the intellect is He (the Self).",
    "“Rise step by step: beyond the senses is the mind, beyond the mind is the intellect — and beyond the intellect is the Self itself.”"),
43: ("Thus knowing Him who is beyond the intellect, restraining the self by the Self, O mighty-armed one, slay the enemy having the form of desire, so difficult to conquer.",
    "“Knowing the Self beyond the intellect, steadying yourself by yourself, kill the hard-to-conquer enemy of desire, Arjuna.”"),
}
