# -*- coding: utf-8 -*-
"""gita_data11.py — Chapter 11 (Viśvarūpa-Darśana Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH11_THEMES = [
    ("Arjuna asks to see the cosmic form",
     "The delusion is gone; now Arjuna longs to see the imperishable form itself.",
     [("My delusion is gone", "By your compassionate words about the supreme secret of the Self, my delusion is gone.", "11.01", "11.01"),
      ("I have heard of your origin and passing", "The origin and dissolution of beings have I heard from you in detail, O lotus-eyed one, and your infinite glory.", "11.02", "11.02"),
      ("I want to see your form", "Even as you have described yourself, O supreme Lord, I long to see your cosmic form, O best of persons.", "11.03", "11.03"),
      ("If you think I can bear it, show me", "If you think it can be seen by me, O Lord, then show me your imperishable self, O Lord of yoga.", "11.04", "11.04")]),
    ("Kṛṣṇa grants the divine eye",
     "Behold my hundreds and thousands of forms — and, since mortal eyes cannot see them, receive a divine eye.",
     [("Behold my hundreds and thousands of forms", "Behold, O Pārtha, my forms by the hundred and thousand, of various kinds and colors.", "11.05", "11.05"),
      ("The Vasus, Rudras, Aśvins", "Behold the Ādityas, the Vasus, the Rudras, the Aśvins and the Maruts; behold many wonders never seen before, O Bhārata.", "11.06", "11.06"),
      ("See the whole world in my body", "Behold now the whole universe, moving and unmoving, gathered in one body here in mine, O Guḍākeśa — and whatever else you wish to see.", "11.07", "11.07"),
      ("I give you a divine eye", "But you cannot see me with your own eye; I give you the divine eye — behold my divine sovereignty.", "11.08", "11.08")]),
    ("Sañjaya describes a thousand suns",
     "The narrator's voice: if a thousand suns should rise together, that might resemble the splendour of that great Self.",
     [("The great Lord of Yoga showed his form", "Having spoken thus, O king, the great Lord of yoga, Hari, showed Pārtha his supreme divine form.", "11.09", "11.09"),
      ("Marvels beyond count", "With countless faces and eyes, with countless wondrous sights, with countless divine ornaments and uplifted weapons,", "11.10", "11.10"),
      ("Infinite, facing everywhere, full of wonders", "wearing divine garlands and robes, anointed with divine perfumes, full of all wonders — the infinite God, facing everywhere.", "11.11", "11.11"),
      ("Brighter than a thousand suns at once", "If the splendour of a thousand suns were to rise at once in the sky, it would not equal the splendour of that great being.", "11.12", "11.12"),
      ("The whole universe in one place", "There, in the body of the God of gods, the son of Pāṇḍu saw the whole universe, one yet divided into manifold forms.", "11.13", "11.13"),
      ("Hair on end, bowing with folded hands", "Then, filled with wonder, his hair standing on end, Dhanañjaya bowed his head to the God and spoke with joined palms.", "11.14", "11.14")]),
    ("I See All the Gods",
     "In your body I see all beings — Brahmā on his lotus seat, the seers, the serpents — a blazing mass of radiance without beginning or end.",
     [("I see all beings in your body", "I see all the gods in your body, O God, and all the hosts of beings; Brahmā the Lord seated on the lotus, and all the seers and divine serpents.", "11.15", "11.15"),
      ("Infinite arms, no beginning, middle or end", "I see you with countless arms, bellies, mouths and eyes — your form is endless on every side; I see no end, no middle, no beginning of you, O Lord of the universe, cosmic form.", "11.16", "11.16"),
      ("A blazing mass of radiance", "I see you crowned, wielding mace and discus, a mass of light shining everywhere — hard to gaze upon, blazing like fire and sun, immeasurable.", "11.17", "11.17"),
      ("You are the imperishable, the supreme to be known", "You are the imperishable, the supreme object of knowledge; you are the supreme refuge of this universe; you are the eternal guardian of dharma — the primal Person, so I deem you.", "11.18", "11.18")]),
    ("The terrible form devouring the worlds",
     "Sun and moon for eyes, mouths blazing with fire — the three worlds tremble, and Arjuna with them.",
     [("Sun and moon for eyes", "Without beginning, middle or end, of infinite power, with countless arms, with sun and moon for eyes — I see you blazing with fire-like mouths, consuming the whole world with your radiance.", "11.19", "11.19"),
      ("The three worlds tremble", "The space between earth and heaven is filled by you alone, and all the directions; seeing your terrible, wondrous form, the three worlds tremble, O great soul.", "11.20", "11.20"),
      ("The hosts of gods enter you", "The hosts of gods enter you; some, afraid, praise you with folded hands; the hosts of great seers and siddhas sing your praises with hymns.", "11.21", "11.21"),
      ("Rudras, Ādityas, Vasus gaze in wonder", "The Rudras, Ādityas, Vasus, Sādhyas, Viśve-devas, Aśvins, Maruts and the ancestors — the gandharvas, yakṣas, demons and siddhas — all gaze on you in wonder.", "11.22", "11.22"),
      ("Seeing your fearsome form, I tremble", "Seeing your immense form, O mighty-armed one, with many mouths and eyes, many bellies, many fearsome fangs, the worlds tremble — and so do I.", "11.23", "11.23")]),
    ("Arjuna cries: I find no peace",
     "Touching the sky, blazing with many colours, mouths like the fire at the end of time — Arjuna's heart shakes and he begs for grace.",
     [("Touching the sky, blazing with many colours", "Touching the sky, blazing, of many colours, with gaping mouths and blazing wide eyes — seeing you, my inmost heart trembles; I find no firmness or peace, O Viṣṇu.", "11.24", "11.24"),
      ("Like the fire at the end of time", "Seeing your terrible mouths with their fearful fangs, like the fire of the end of time, I do not know the directions, nor find any refuge; be gracious, O Lord of gods, abode of the world.", "11.25", "11.25"),
      ("The sons of Dhṛtarāṣṭra enter your mouths", "All these sons of Dhṛtarāṣṭra, with the hosts of kings, enter your mouths — Bhīṣma, Droṇa, Karṇa, and the chief warriors of our side,", "11.26", "11.26"),
      ("Heads crushed between your teeth", "their heads crushed between your teeth — some cling in fear, visible in the gaps of your terrible fangs.", "11.27", "11.27")]),
    ("As Moths Into a Flame",
     "As rivers rush into the ocean and moths into a blazing fire, so these worlds rush into your mouths to their destruction.",
     [("As rivers rush into the ocean", "As the many rushing currents of rivers pour into the ocean, so these heroes of the mortal world enter your blazing mouths.", "11.28", "11.28"),
      ("As moths fly into a blazing fire", "As moths fly with full speed into a blazing fire for their destruction, so these worlds fly into your mouths for their destruction.", "11.29", "11.29"),
      ("You lick up all the worlds", "You lick up all the worlds with your flaming mouths, devouring them on every side; your terrible rays fill the whole universe, O Viṣṇu.", "11.30", "11.30"),
      ("Tell me who you are", "Tell me who you are, O terrible form; I bow to you — be gracious, O best of gods! I long to know you, the primeval one; I do not understand your workings.", "11.31", "11.31")]),
    ("Kṛṣṇa says: I am Time, the destroyer",
     "The answer: I am Time, grown mature, come forth to annihilate the worlds — these warriors are already slain; be but my instrument.",
     [("I am time, destroyer of worlds", "I am Time, the world-destroyer, grown mature; I have come to destroy these worlds — even without you, none of these warriors arrayed against you will remain.", "11.32", "11.32"),
      ("Be my instrument", "Therefore arise and win glory; conquer your enemies and enjoy the thriving kingdom — they are already slain by me; be only the instrument, O Sāvyasācin.", "11.33", "11.33"),
      ("They are already slain by me", "Slay Droṇa, Bhīṣma, Jayadratha, Karṇa and the other warrior-heroes — already killed by me; strike without fear, fight — you shall conquer your rivals in battle.", "11.34", "11.34")]),
    ("Trembling, Arjuna bows again",
     "Sañjaya's line before the hymn: hearing Kṛṣṇa's words, the crowned Arjuna folded his palms, bowed once more, and spoke in a faltering voice, overcome with fear.",
     [("Trembling, with faltering voice", "Hearing these words of Keśava, the crowned Arjuna, trembling, folded his palms and, bowing again, spoke to Kṛṣṇa with faltering voice.", "11.35", "11.35")]),
    ("Arjuna's hymn: you are the primal God",
     "The hymn itself: the world rejoices in your glory, the demons flee — you are greater than Brahmā, the ancient Person, the knower and the known, and I bow to you on every side.",
     [("The world rejoices in your praise", "It is fitting, Hṛṣīkeśa, that the world rejoices and delights in your glory; the rākṣasas flee in fear in all directions, and the hosts of siddhas bow to you.", "11.36", "11.36"),
      ("Why should they not bow to you?", "Why should they not bow to you, O great soul, greater than Brahmā, the primal creator — O infinite Lord of gods, abode of the universe, you are the imperishable, being and non-being and beyond both.", "11.37", "11.37"),
      ("You are the primal God, the ancient person", "You are the primal God, the ancient Person, the supreme refuge of this universe; you are the knower and the known, the supreme abode; by you this universe is pervaded, O infinite form.", "11.38", "11.38"),
      ("You are Vāyu, Yama, Agni, the moon", "You are wind, death, fire, Varuṇa, the moon, and the progenitor — and the great grandsire; I bow to you a thousand times — again and yet again I bow to you.", "11.39", "11.39"),
      ("Salutation on every side", "I bow to you from the front and from behind; I bow to you on every side, O all! You are of infinite might and measureless vigour; you pervade all, and so you are all.", "11.40", "11.40")]),
    ("Forgive me for calling you friend",
     "Whatever I said carelessly, calling you friend — not knowing your greatness — forgive, as a father forgives a son.",
     [("Whatever I said, calling you “friend”", "Whatever I said in rash familiarity — 'O Kṛṣṇa, O Yādava, O friend' — not knowing your majesty, whether in carelessness or in love,", "11.41", "11.41"),
      ("Whatever disrespect I showed in sport", "and whatever disrespect I showed you in sport, rest, sitting or at meals, alone or before others, O Acyuta — that I beg you to forgive, O immeasurable one.", "11.42", "11.42"),
      ("Father of the world, teacher beyond compare", "You are the father of this world, moving and unmoving; you are its supreme object of worship and the most venerable teacher; none equals you in the three worlds, how then could any surpass you.", "11.43", "11.43"),
      ("Forgive as a father forgives his son", "Therefore I bow and prostrate my body before you, and beg your grace, O adorable Lord; as a father forgives his son, a friend his friend, a lover the beloved — so forgive me, O God.", "11.44", "11.44")]),
    ("Show Me the Gracious Form",
     "Delighted yet trembling, Arjuna asks for the familiar four-armed form; and Kṛṣṇa says: this form none but you has ever seen.",
     [("Delighted, yet my mind trembles", "Having seen what I never saw before, I am delighted, yet my mind trembles with fear; show me, O God, your gracious form — be merciful, O Lord of the universe.", "11.45", "11.45"),
      ("I long to see you crowned, with mace and discus", "I long to see you as before — crowned, with mace and discus in hand; appear in that four-armed form, O thousand-armed, universal form.", "11.46", "11.46"),
      ("By my grace you have seen it", "By my grace, Arjuna, I have shown you this supreme form — the luminous, universal, infinite, primeval form that none but you has ever seen.", "11.47", "11.47"),
      ("Not by Vedas or austerities can it be seen", "Not by the study of the Vedas and sacrifices, nor by gifts, rites or fierce austerities, can I be seen in this form in the world of men — by any but you, O prince of the Kurus.", "11.48", "11.48")]),
    ("The gentle form is restored",
     "Be not afraid; behold again my familiar form — and Arjuna, composed, returns to his own nature.",
     [("Be not afraid or bewildered", "Do not be afraid or bewildered at the sight of this terrible form of mine; free from fear, with a glad heart, behold once more this gracious form of mine.", "11.49", "11.49"),
      ("Vāsudeva shows his own form again", "Having spoken thus to Arjuna, Vāsudeva again showed his own form, and the great soul comforted the frightened Arjuna, once more in his gracious appearance.", "11.50", "11.50"),
      ("Now I am composed and restored", "Seeing this your gracious human form, O Janārdana, I am now composed and restored to my own nature.", "11.51", "11.51")]),
    ("Only undivided devotion can see me",
     "This form even the gods long to see; not by Vedas or austerities, but by undivided devotion alone can I be known — and he who works for me, free from enmity, comes to me.",
     [("Even the gods long to see this form", "This form of mine that you have seen is very hard to see; even the gods ever long to see this form.", "11.52", "11.52"),
      ("Not by Vedas, austerity or gifts", "I am not to be seen in this way through the Vedas, nor through austerity, nor through gifts, nor through worship; only in the way you have seen me can I be seen.", "11.53", "11.53"),
      ("By undivided devotion alone", "But through single-pointed devotion I can be known, seen and entered in truth, O Arjuna, in this very form.", "11.54", "11.54"),
      ("He who works for me comes to me", "He who does my work, who holds me as the supreme goal, who is devoted to me, free from attachment, without enmity toward any being — he comes to me, O Pāṇḍava.", "11.55", "11.55")]),
]

CH11_TRANSLATIONS = {
1: ("Arjuna said: By your compassionate words about the supreme secret of the Self, my delusion is gone.",
    "Arjuna says: “Because you graciously spoke to me of the highest secret of the Self, my confusion has vanished.”"),
2: ("The origin and dissolution of beings have I heard from you in detail, O lotus-eyed one, and your infinite glory.",
    "“I have heard from you, O lotus-eyed Lord, of the birth and passing of all beings, and of your endless majesty.”"),
3: ("Even as you have described yourself, O supreme Lord, I long to see your cosmic form, O best of persons.",
    "“Just as you have described yourself, O highest Lord, I want to see your universal form.”"),
4: ("If you think it can be seen by me, O Lord, then show me your imperishable self, O Lord of yoga.",
    "“If you judge that I am able to see it, O Lord of yoga, reveal to me your eternal Self.”"),
5: ("The Blessed Lord said: Behold, O Pārtha, my forms by the hundred and thousand, of various kinds and colors.",
    "Kṛṣṇa said: “See now, Arjuna, my hundreds and thousands of forms — of many kinds and many colors.”"),
6: ("Behold the Ādityas, the Vasus, the Rudras, the Aśvins and the Maruts; behold many wonders never seen before, O Bhārata.",
    "“See the sun-gods, the Vasus, the Rudras, the twin Aśvins, the storm-winds — wonders you have never seen, Arjuna.”"),
7: ("Behold now the whole universe, moving and unmoving, gathered in one body here in mine, O Guḍākeśa — and whatever else you wish to see.",
    "“See the entire universe — moving and still — all at once within my body, and whatever else you desire to see.”"),
8: ("But you cannot see me with your own eye; I give you the divine eye — behold my divine sovereignty.",
    "“Your mortal eye cannot see me — take this divine eye and behold my cosmic power.”"),
9: ("Sañjaya said: Having spoken thus, O king, the great Lord of yoga, Hari, showed Pārtha his supreme divine form.",
    "Sañjaya narrates: “Having said this, O king, the great Lord of yoga, Kṛṣṇa, revealed to Arjuna his supreme cosmic form.”"),
10: ("With countless faces and eyes, with countless wondrous sights, with countless divine ornaments and uplifted weapons,",
    "“— with innumerable faces and eyes, marvels beyond count, celestial ornaments, and weapons raised on every side —”"),
11: ("wearing divine garlands and robes, anointed with divine perfumes, full of all wonders — the infinite God, facing everywhere.",
    "“— adorned with heavenly garlands and garments, anointed with divine fragrances, the limitless God with faces in every direction.”"),
12: ("If the splendour of a thousand suns were to rise at once in the sky, it would not equal the splendour of that great being.",
    "“If a thousand suns blazed up together in the sky, it would not match the glory of that great being.”"),
13: ("There, in the body of the God of gods, the son of Pāṇḍu saw the whole universe, one yet divided into manifold forms.",
    "“There Arjuna saw the entire universe — united yet infinitely varied — within the body of the God of gods.”"),
14: ("Then, filled with wonder, his hair standing on end, Dhanañjaya bowed his head to the God and spoke with joined palms.",
    "“Then, overwhelmed with wonder, hair on end, Arjuna bowed down and, folding his hands, spoke.”"),
15: ("I see all the gods in your body, O God, and all the hosts of beings; Brahmā the Lord seated on the lotus, and all the seers and divine serpents.",
    "“In your body I see all the gods and every class of being — Brahmā on his lotus throne, the sages, and the celestial serpents.”"),
16: ("I see you with countless arms, bellies, mouths and eyes — your form is endless on every side; I see no end, no middle, no beginning of you, O Lord of the universe, cosmic form.",
    "“I see you, O universal form, with numberless arms, bellies, faces and eyes — infinite on all sides; you have no beginning, middle, or end.”"),
17: ("I see you crowned, wielding mace and discus, a mass of light shining everywhere — hard to gaze upon, blazing like fire and sun, immeasurable.",
    "“I see you with crown, mace, and discus — a blaze of light, too dazzling to look upon, like fire and sun, measureless.”"),
18: ("You are the imperishable, the supreme object of knowledge; you are the supreme refuge of this universe; you are the eternal guardian of dharma — the primal Person, so I deem you.",
    "“You are the eternal, the highest to be known; you are the universe's supreme treasure, the changeless guardian of dharma — the original Person.”"),
19: ("Without beginning, middle or end, of infinite power, with countless arms, with sun and moon for eyes — I see you blazing with fire-like mouths, consuming the whole world with your radiance.",
    "“Without beginning or end, infinite in might, countless-armed, sun-and-moon-eyed — I see you, fire-mouthed, burning up the world with your brilliance.”"),
20: ("The space between earth and heaven is filled by you alone, and all the directions; seeing your terrible, wondrous form, the three worlds tremble, O great soul.",
    "“Between heaven and earth, in every direction, you alone fill all — and the three worlds tremble at your awesome form.”"),
21: ("The hosts of gods enter you; some, afraid, praise you with folded hands; the hosts of great seers and siddhas sing your praises with hymns.",
    "“The troops of gods stream into you; some, terrified, glorify you with joined palms; the sages and perfected ones praise you with sacred hymns.”"),
22: ("The Rudras, Ādityas, Vasus, Sādhyas, Viśve-devas, Aśvins, Maruts and the ancestors — the gandharvas, yakṣas, demons and siddhas — all gaze on you in wonder.",
    "“All the orders of gods — the Rudras, sun-gods, Vasus, and the rest — together with celestial singers and spirits, gaze upon you astonished.”"),
23: ("Seeing your immense form, O mighty-armed one, with many mouths and eyes, many bellies, many fearsome fangs, the worlds tremble — and so do I.",
    "“At the sight of your colossal form, mighty-armed one — with its many faces, eyes, bellies, and terrible jaws — the worlds tremble, and I too.”"),
24: ("Touching the sky, blazing, of many colours, with gaping mouths and blazing wide eyes — seeing you, my inmost heart trembles; I find no firmness or peace, O Viṣṇu.",
    "Beholding your sky-touching, blazing, many-coloured form — gaping mouths, wide flaming eyes — my heart is shaken; I find no steadiness or calm, O Viṣṇu."),
25: ("Seeing your terrible mouths with their fearful fangs, like the fire of the end of time, I do not know the directions, nor find any refuge; be gracious, O Lord of gods, abode of the world.",
    "Beholding your dreadful fanged mouths, blazing like the fire of destruction, I lose all bearings and find no shelter; have mercy, Lord of gods."),
26: ("All these sons of Dhṛtarāṣṭra, with the hosts of kings, enter your mouths — Bhīṣma, Droṇa, Karṇa, and the chief warriors of our side,",
    "“These sons of Dhṛtarāṣṭra, together with their kings, are rushing into your mouths — Bhīṣma, Droṇa, Karṇa, and our foremost warriors,”"),
27: ("their heads crushed between your teeth — some cling in fear, visible in the gaps of your terrible fangs.",
    "“— their heads ground to powder in your teeth; some, caught between your terrible jaws, are seen clinging in terror.”"),
28: ("As the many rushing currents of rivers pour into the ocean, so these heroes of the mortal world enter your blazing mouths.",
    "“As rivers pour their countless waters into the sea, so these champions of men stream into your blazing mouths.”"),
29: ("As moths fly with full speed into a blazing fire for their destruction, so these worlds fly into your mouths for their destruction.",
    "“As moths hurl themselves into the flame to perish, so these worlds rush into your mouths to be destroyed.”"),
30: ("You lick up all the worlds with your flaming mouths, devouring them on every side; your terrible rays fill the whole universe, O Viṣṇu.",
    "“You lap up the worlds with your burning jaws, swallowing them wholly; your fierce glory fills the universe, O Viṣṇu.”"),
31: ("Tell me who you are, O terrible form; I bow to you — be gracious, O best of gods! I long to know you, the primeval one; I do not understand your workings.",
    "“Tell me who you are in this dreadful form; I bow to you — have mercy, Lord. I want to know you, the Ancient One, for I cannot grasp your ways.”"),
32: ("The Blessed Lord said: I am Time, the world-destroyer, grown mature; I have come to destroy these worlds — even without you, none of these warriors arrayed against you will remain.",
    "Kṛṣṇa said: “I am Time, ripened to destroy the worlds. Even without your striking, none of these warriors will survive.”"),
33: ("Therefore arise and win glory; conquer your enemies and enjoy the thriving kingdom — they are already slain by me; be only the instrument, O Sāvyasācin.",
    "“So stand up and win renown; defeat the foe and enjoy the flourishing realm. I have already killed them — you are merely the means, Arjuna.”"),
34: ("Slay Droṇa, Bhīṣma, Jayadratha, Karṇa and the other warrior-heroes — already killed by me; strike without fear, fight — you shall conquer your rivals in battle.",
    "“Kill Droṇa, Bhīṣma, Jayadratha, and Karṇa — I have already destroyed them. Strike without hesitation and fight; you will triumph in battle.”"),
35: ("Sañjaya said: Hearing these words of Keśava, the crowned Arjuna, trembling, folded his palms and, bowing again, spoke to Kṛṣṇa with faltering voice.",
    "Sañjaya narrates: “Hearing Kṛṣṇa's words, Arjuna, shaking, joined his palms, bowed once more, and spoke in a stammering voice.”"),
36: ("It is fitting, Hṛṣīkeśa, that the world rejoices and delights in your glory; the rākṣasas flee in fear in all directions, and the hosts of siddhas bow to you.",
    "“Rightly, O Kṛṣṇa, the world delights in praising you; the demons flee in terror, and the perfected ones bow to you.”"),
37: ("Why should they not bow to you, O great soul, greater than Brahmā, the primal creator — O infinite Lord of gods, abode of the universe, you are the imperishable, being and non-being and beyond both.",
    "“Who would not bow to you, O great one, superior even to Brahmā, the first creator? You are the eternal, the real and the unreal, and what lies beyond.”"),
38: ("You are the primal God, the ancient Person, the supreme refuge of this universe; you are the knower and the known, the supreme abode; by you this universe is pervaded, O infinite form.",
    "“You are the first God, the ancient Person, the universe's highest refuge; you are the knower and the known, the supreme home — and all is spread through you.”"),
39: ("You are wind, death, fire, Varuṇa, the moon, and the progenitor — and the great grandsire; I bow to you a thousand times — again and yet again I bow to you.",
    "“You are air, death, fire, Varuṇa, the moon — the father and the great ancestor. Salutations to you a thousand-fold — again and again, I bow.”"),
40: ("I bow to you from the front and from behind; I bow to you on every side, O all! You are of infinite might and measureless vigour; you pervade all, and so you are all.",
    "“I bow to you before and behind; I bow to you on every side, O All. Your power is endless — you are everything, for you fill everything.”"),
41: ("Whatever I said in rash familiarity — 'O Kṛṣṇa, O Yādava, O friend' — not knowing your majesty, whether in carelessness or in love,",
    "“Whatever I said to you boldly and thoughtlessly — calling you Kṛṣṇa, Yādava, my friend — ignorant of your greatness, whether in jest or fondness,”"),
42: ("and whatever disrespect I showed you in sport, rest, sitting or at meals, alone or before others, O Acyuta — that I beg you to forgive, O immeasurable one.",
    "“— and however I slighted you in play, in rest, at meals, alone or in company — forgive all that, O changeless, measureless Lord.”"),
43: ("You are the father of this world, moving and unmoving; you are its supreme object of worship and the most venerable teacher; none equals you in the three worlds, how then could any surpass you, O being of matchless power?",
    "“You are the father of all that moves and stands; you are the supreme object of reverence, the greatest teacher. In the three worlds nothing equals you — let alone surpasses you.”"),
44: ("Therefore I bow and prostrate my body before you, and beg your grace, O adorable Lord; as a father forgives his son, a friend his friend, a lover the beloved — so forgive me, O God.",
    "“So I bow low before you and implore your grace. As a father pardons a son, a friend a friend, a lover the beloved — forgive me, O Lord.”"),
45: ("Having seen what I never saw before, I am delighted, yet my mind trembles with fear; show me, O God, your gracious form — be merciful, O Lord of the universe.",
    "“Having seen this wonder I rejoice, yet my heart quakes with fear; show me your gentle form, O Lord — have mercy.”"),
46: ("I long to see you as before — crowned, with mace and discus in hand; appear in that four-armed form, O thousand-armed, universal form.",
    "“I wish to see you again as before — with crown, mace, and discus; appear in that four-armed shape, O cosmic form.”"),
47: ("The Blessed Lord said: By my grace, Arjuna, I have shown you this supreme form — the luminous, universal, infinite, primeval form that none but you has ever seen.",
    "Kṛṣṇa said: “Out of grace, Arjuna, I have revealed to you this supreme, radiant, universal, infinite, primal form — seen by no one before you.”"),
48: ("Not by the study of the Vedas and sacrifices, nor by gifts, rites or fierce austerities, can I be seen in this form in the world of men — by any but you, O prince of the Kurus.",
    "“Neither by Vedic study, sacrifice, charity, ritual, nor harsh austerity can this form be seen in the mortal world — by anyone but you.”"),
49: ("Do not be afraid or bewildered at the sight of this terrible form of mine; free from fear, with a glad heart, behold once more this gracious form of mine.",
    "“Fear not, nor be confused, at this dread vision of mine. With fear gone and heart at ease, look again upon my gentle form.”"),
50: ("Sañjaya said: Having spoken thus to Arjuna, Vāsudeva again showed his own form, and the great soul comforted the frightened Arjuna, once more in his gracious appearance.",
    "Sañjaya narrates: “So saying, Kṛṣṇa again assumed his gentle form, and the great soul comforted the terrified Arjuna.”"),
51: ("Arjuna said: Seeing this your gracious human form, O Janārdana, I am now composed and restored to my own nature.",
    "Arjuna says: “Seeing your gentle human form, O Janārdana, I am calm again, and my mind has returned to itself.”"),
52: ("The Blessed Lord said: This form of mine that you have seen is very hard to see; even the gods ever long to see this form.",
    "Kṛṣṇa said: “The form you have seen is exceedingly hard to behold — even the gods always yearn for a sight of it.”"),
53: ("I am not to be seen in this way through the Vedas, nor through austerity, nor through gifts, nor through worship; only in the way you have seen me can I be seen.",
    "“This vision is not won by Vedic study, austerity, charity, or ritual — I am seen thus only as you have seen me.”"),
54: ("But through single-pointed devotion I can be known, seen and entered in truth, O Arjuna, in this very form.",
    "“Yet by undivided devotion I may be truly known, seen, and entered, Arjuna — in this very form.”"),
55: ("He who does my work, who holds me as the supreme goal, who is devoted to me, free from attachment, without enmity toward any being — he comes to me, O Pāṇḍava.",
    "“One who works for me, making me his supreme goal, devoted to me, free of clinging and of enmity toward all — he reaches me, Arjuna.”"),
}
