# -*- coding: utf-8 -*-
"""gita_data13.py — Chapter 13 (Kṣetra-Kṣetrajña-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH13_THEMES = [
    ("The body is the field, the Self its knower",
     "Kṛṣṇa opens the teaching: the body is the field, know Me as the knower of the field in all fields — and the knowledge of field and knower is true knowledge.",
     [("The body is the field", "This body, O son of Kuntī, is called the field; he who knows it, the wise call the knower of the field.", "13.01", "13.01"),
      ("Know me as the knower", "Know me also as the knower of the field in all fields, O Bhārata; the knowledge of the field and its knower is deemed by me true knowledge.", "13.02", "13.02")]),
    ("Kṛṣṇa will describe the field",
     "Kṛṣṇa will describe the field — its nature, modifications and source; the seers have sung it in many ways.",
     [("I shall declare", "What the field is, what it is like, what its modifications, from what it arises, and who he is and what his powers — hear all this from me in brief.", "13.03", "13.03"),
      ("Sung by the seers", "Sung by the seers in many ways, in diverse meters, and in the aphorisms of Brahman, with reasons, well-decided —", "13.04", "13.04")]),
    ("The field's twenty-four constituents",
     "The field comprises the great elements, ego, intellect, the unmanifest, the senses, and their objects — and desire, aversion, pleasure and pain.",
     [("The elements of the field", "— the great elements, ego, intellect, the unmanifest, the ten senses and the one, the five objects of the senses,", "13.05", "13.05"),
      ("Desire and aversion", "— desire, aversion, pleasure, pain, the body, consciousness and constancy: this is the field, in brief, with its modifications.", "13.06", "13.06")]),
    ("The Means of Knowledge",
     "Humility, non-violence, service to the teacher, purity, steadfastness, dispassion, absence of ego, and constant meditation — these are declared knowledge.",
     [("Humility, non-violence, service to the teacher", "Humility, modesty, non-violence, forbearance, uprightness, service to the teacher, purity, steadfastness, self-control,", "13.07", "13.07"),
      ("Seeing the misery of birth", "— dispassion toward the objects of the senses, absence of ego, and the perception of the evil of birth, death, old age and disease,", "13.08", "13.08"),
      ("Non-attachment and evenness", "— non-attachment, non-clinging to son, wife and home, constant even-mindedness toward gain and loss,", "13.09", "13.09"),
      ("Unwavering devotion, delight in solitude", "— unwavering devotion to me through undivided yoga, delight in solitude, distaste for the company of men,", "13.10", "13.10"),
      ("The aim of truth-knowledge", "— constant commitment to Self-knowledge, and insight into the purpose of the knowledge of truth: this is declared knowledge; what is other than this is ignorance.", "13.11", "13.11")]),
    ("The knowable is beginningless Brahman",
     "Kṛṣṇa declares the knowable: Brahman, beginningless, beyond being and non-being — the supreme reality.",
     [("The knowable declared", "I shall declare the object of knowledge, knowing which one tastes immortality — the beginningless supreme Brahman, which is called neither being nor non-being.", "13.12", "13.12")]),
    ("Brahman is everywhere, with every face",
     "Brahman is all-hands and all-feet, all-eyes, all-heads, all-ears — pervading all, without senses yet sensing all, unattached yet upholding all.",
     [("All hands, all feet", "With hands and feet everywhere, with eyes, heads and faces everywhere, with ears everywhere — it stands, pervading all in the world.", "13.13", "13.13"),
      ("Yet has no senses", "Appearing with all the attributes of the senses, yet devoid of all senses; unattached, yet upholding all; without guṇas, yet enjoying the guṇas.", "13.14", "13.14"),
      ("Within and without, far and near", "It is within and without all beings; it is unmoving and moving; being subtle, it is unknowable — it is far away, and yet near.", "13.15", "13.15"),
      ("Undivided in the divided", "It is undivided, yet appears as if divided among beings; know it as the supporter of beings, the devourer and the creator.", "13.16", "13.16")]),
    ("The light of lights in every heart",
     "The light of lights, beyond all darkness, seated in the heart of every being — and with that, the field, knowledge and the knowable stand declared.",
     [("The light of lights", "It is the light of lights, declared beyond darkness — knowledge, the object of knowledge, and the goal of knowledge, seated in the heart of all.", "13.17", "13.17"),
      ("The field, knowledge and the knowable", "Thus the field, knowledge and the knowable have been declared in brief; my devotee, knowing this, attains my being.", "13.18", "13.18")]),
    ("Prakṛti and puruṣa are both beginningless",
     "Kṛṣṇa declares prakṛti and puruṣa as beginningless; the guṇas arise from prakṛti, and it is the cause of agency, while puruṣa is the enjoyer.",
     [("The two beginningless", "Know prakṛti and puruṣa both as beginningless; and know the modifications and the guṇas as born of prakṛti.", "13.19", "13.19"),
      ("Agency and enjoyment", "Prakṛti is declared the cause of agency in bringing about the effect; puruṣa is declared the cause of the enjoyment of pleasure and pain.", "13.20", "13.20"),
      ("Attachment to the guṇas causes birth", "Puruṣa, seated in prakṛti, enjoys the guṇas born of prakṛti; attachment to the guṇas is the cause of birth in good and evil wombs.", "13.21", "13.21")]),
    ("He who knows the supreme puruṣa is free",
     "The one who knows this supreme puruṣa — witness, sustainer, enjoyer, great Lord, the supreme Self — is never born again.",
     [("The witness and Lord", "The witness, the approver, the sustainer, the enjoyer, the great Lord — and called the supreme Self: this supreme puruṣa in the body.", "13.22", "13.22"),
      ("Knowing these two, he is not born again", "He who thus knows puruṣa and prakṛti with its guṇas — whatever his way of life, he is not born again.", "13.23", "13.23")]),
    ("The Ways to Knowledge",
     "Some see the Self in themselves by meditation, others by knowledge, others by karma-yoga; and those who do not know hear from others and cross beyond death.",
     [("The three paths", "Some see the Self within themselves by meditation; others by the yoga of knowledge; still others by the yoga of action.", "13.24", "13.24"),
      ("The path of hearing", "Others, not knowing, worship after hearing from others; and they too cross beyond death, devoted to what they have heard.", "13.25", "13.25")]),
    ("The One in the Many",
     "Whatever being arises, moving or unmoving, comes from the union of field and knower; he who sees the Lord equally present, imperishable, truly sees.",
     [("All from the union", "Whatever being is born, moving or unmoving — know it, O bull of the Bhāratas, to be from the union of the field and its knower.", "13.26", "13.26"),
      ("Seeing the Lord alike in all, he truly sees", "He who sees the supreme Lord standing equally in all beings, not perishing as they perish — he truly sees.", "13.27", "13.27"),
      ("He does not harm the Self by the self", "For seeing the Lord equally established everywhere, he does not harm the Self by the self; therefore he attains the supreme goal.", "13.28", "13.28")]),
    ("Prakṛti acts, the Self does nothing",
     "He who sees that all actions are done by prakṛti and the Self as non-doer — and sees the one in the many — attains Brahman.",
     [("Prakṛti acts, the Self does nothing", "He who sees that all actions are performed by prakṛti, and the Self as the non-doer — he truly sees.", "13.29", "13.29"),
      ("The one in the many", "When he sees the manifold states of beings resting in the One and spread out from it alone — then he attains Brahman.", "13.30", "13.30")]),
    ("The Self is untouched, like space",
     "Because it is beginningless and without guṇas, the supreme Self is imperishable; like space, it is not stained by the body.",
     [("Without beginning or guṇas, it does not act", "Because it is beginningless and without guṇas, this supreme Self is imperishable — though dwelling in the body, it neither acts nor is stained.", "13.31", "13.31"),
      ("As space is unstained", "As the all-pervading space is not stained, being subtle, so the Self, present in every body, is not stained.", "13.32", "13.32")]),
    ("The knower lights the whole field",
     "As the sun illumines the whole world, the knower of the field illumines the whole field; those who see this distinction reach the supreme.",
     [("The sun and the field", "As the one sun illumines this whole world, so the knower of the field illumines the whole field, O Bhārata.", "13.33", "13.33"),
      ("The final vision", "Those who, with the eye of knowledge, see the distinction between the field and its knower, and the liberation from prakṛti — they reach the supreme.", "13.34", "13.34")]),
]

CH13_TRANSLATIONS = {
1: ("The Blessed Lord said: This body, O son of Kuntī, is called the field; he who knows it, the wise call the knower of the field.",
    "Kṛṣṇa said: “This body is called the field; one who knows it is called the knower of the field.”"),
2: ("Know me also as the knower of the field in all fields, O Bhārata; the knowledge of the field and its knower is deemed by me true knowledge.",
    "“Know me as the knower of the field in every body; the wisdom of the field and its knower is what I call real knowledge.”"),
3: ("What the field is, what it is like, what its modifications, from what it arises, and who he is and what his powers — hear all this from me in brief.",
    "“Hear from me, in brief, what the field is, its nature, its changes, its source — and who the knower is and what his powers are.”"),
4: ("Sung by the seers in many ways, in diverse meters, and in the aphorisms of Brahman, with reasons, well-decided —",
    "“The sages have sung it in many ways, in varied meters, and in the Brahman-sūtras, with reasoning, decisively —”"),
5: ("— the great elements, ego, intellect, the unmanifest, the ten senses and the one, the five objects of the senses,",
    "“Break it down and you get: the five elements, the sense of 'I', the reasoning mind, unformed nature, the ten senses with mind as the eleventh, and the five things the senses reach for.”"),
6: ("— desire, aversion, pleasure, pain, the body, consciousness and constancy: this is the field, in brief, with its modifications.",
    "“— desire, dislike, joy, sorrow, the body itself, awareness and steadiness: this, briefly, is the field with all its changes.”"),
7: ("Humility, modesty, non-violence, forbearance, uprightness, service to the teacher, purity, steadfastness, self-control,",
    "“Humility, modesty, harmlessness, patience, honesty, serving one's teacher, purity, firmness, self-mastery,”"),
8: ("— dispassion toward the objects of the senses, absence of ego, and the perception of the evil of birth, death, old age and disease,",
    "“— disinterest in sense-pleasures, no ego, and the clear seeing of the misery of birth, death, age, and sickness,”"),
9: ("— non-attachment, non-clinging to son, wife and home, constant even-mindedness toward gain and loss,",
    "“— detachment, no clinging to family and home, steady even-mindedness in success and failure,”"),
10: ("— unwavering devotion to me through undivided yoga, delight in solitude, distaste for the company of men,",
    "“— unwavering devotion to me with single-pointed yoga, fondness for solitude, distaste for worldly crowds,”"),
11: ("— constant commitment to Self-knowledge, and insight into the purpose of the knowledge of truth: this is declared knowledge; what is other than this is ignorance.",
    "“— constant pursuit of knowledge of the Self, and seeing the aim of truth-knowledge: this is called knowledge; anything else is ignorance.”"),
12: ("I shall declare the object of knowledge, knowing which one tastes immortality — the beginningless supreme Brahman, which is called neither being nor non-being.",
    "“I will tell you of the knowable, knowing which you taste immortality — the beginningless supreme Brahman, beyond being and non-being.”"),
13: ("With hands and feet everywhere, with eyes, heads and faces everywhere, with ears everywhere — it stands, pervading all in the world.",
    "“Wherever you look there are hands and feet, eyes and heads and faces, ears without number. Nothing in the world falls outside it.”"),
14: ("Appearing with all the attributes of the senses, yet devoid of all senses; unattached, yet upholding all; without guṇas, yet enjoying the guṇas.",
    "“It appears to have all the senses' qualities, yet has no senses; it is unattached, yet supports all; beyond the guṇas, yet enjoys them.”"),
15: ("It is within and without all beings; it is unmoving and moving; being subtle, it is unknowable — it is far away, and yet near.",
    "“It is inside and outside all beings; unmoving and moving; too subtle to grasp — far away, and yet close at hand.”"),
16: ("It is undivided, yet appears as if divided among beings; know it as the supporter of beings, the devourer and the creator.",
    "“Look at beings and you see many; look again and there is one. It holds them up, takes them back, and puts them forth once more.”"),
17: ("It is the light of lights, declared beyond darkness — knowledge, the object of knowledge, and the goal of knowledge, seated in the heart of all.",
    "“It is the light of all lights, beyond darkness — wisdom itself, its object, and its goal, dwelling in every heart.”"),
18: ("Thus the field, knowledge and the knowable have been declared in brief; my devotee, knowing this, attains my being.",
    "“So I have told you, in brief, of the field, knowledge, and the knowable; my devotee who understands this reaches my state.”"),
19: ("Know prakṛti and puruṣa both as beginningless; and know the modifications and the guṇas as born of prakṛti.",
    "“Know that nature and the person are both beginningless; and that all changes and qualities arise from nature.”"),
20: ("Prakṛti is declared the cause of agency in bringing about the effect; puruṣa is declared the cause of the enjoyment of pleasure and pain.",
    "“Nature is the cause of doing; the person is the cause of experiencing joy and sorrow.”"),
21: ("Puruṣa, seated in prakṛti, enjoys the guṇas born of prakṛti; attachment to the guṇas is the cause of birth in good and evil wombs.",
    "“The person, resting in nature, tastes the qualities born of nature; clinging to those qualities causes birth in high or low wombs.”"),
22: ("The witness, the approver, the sustainer, the enjoyer, the great Lord — and called the supreme Self: this supreme puruṣa in the body.",
    "“Within this body sits one who watches, permits, upholds and enjoys — the great Lord, the highest Self.”"),
23: ("He who thus knows puruṣa and prakṛti with its guṇas — whatever his way of life, he is not born again.",
    "“One who knows this Person and nature with its qualities — however he lives, he is never reborn.”"),
24: ("Some see the Self within themselves by meditation; others by the yoga of knowledge; still others by the yoga of action.",
    "“Some see the Self within by meditation; others by wisdom; still others by selfless action.”"),
25: ("Others, not knowing, worship after hearing from others; and they too cross beyond death, devoted to what they have heard.",
    "“Others, not knowing directly, worship after hearing from teachers — and they too cross beyond death by faith in the heard teaching.”"),
26: ("Whatever being is born, moving or unmoving — know it, O bull of the Bhāratas, to be from the union of the field and its knower.",
    "“Whatever comes into being, moving or still — know it arises from the union of the field and its knower, Arjuna.”"),
27: ("He who sees the supreme Lord standing equally in all beings, not perishing as they perish — he truly sees.",
    "“One who sees the supreme Lord equally present in all beings, undying among the dying — he truly sees.”"),
28: ("For seeing the Lord equally established everywhere, he does not harm the Self by the self; therefore he attains the supreme goal.",
    "“Seeing the Lord equally in all, he never degrades his Self; and so he reaches the highest goal.”"),
29: ("He who sees that all actions are performed by prakṛti, and the Self as the non-doer — he truly sees.",
    "“Nature does the work, not you. See that clearly and you have seen the truth.”"),
30: ("When he sees the manifold states of beings resting in the One and spread out from it alone — then he attains Brahman.",
    "“The moment the endless variety of things is seen resting in one root and branching out from it, Brahman is reached.”"),
31: ("Because it is beginningless and without guṇas, this supreme Self is imperishable — though dwelling in the body, it neither acts nor is stained.",
    "“Being beginningless and beyond all qualities, the supreme Self is eternal — though it dwells in the body, it neither acts nor is tainted.”"),
32: ("As the all-pervading space is not stained, being subtle, so the Self, present in every body, is not stained.",
    "“As space, though pervading all, is never tainted, so the Self present in every body is never tainted.”"),
33: ("As the one sun illumines this whole world, so the knower of the field illumines the whole field, O Bhārata.",
    "“A single sun lights the whole world. In just that way, the one who knows the field lights up the field entire.”"),
34: ("Those who, with the eye of knowledge, see the distinction between the field and its knower, and the liberation from prakṛti — they reach the supreme.",
    "“Those who, with the eye of wisdom, discern the difference between the field and its knower, and the freedom from nature — they attain the highest.”"),
}
