# -*- coding: utf-8 -*-
"""gita_data14.py — Chapter 14 (Guṇa-Traya-Vibhāga Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH14_THEMES = [
    ("Liberating knowledge and the birth of beings",
     "The highest knowledge leads beyond creation and dissolution. Kṛṣṇa describes the great womb and himself as the seed-giving father of all forms.",
     [("The highest knowledge", "I will again declare the supreme knowledge, the best of all knowledges — knowing which all the sages have gone to the highest perfection.", "14.01", "14.01"),
      ("One with me, not reborn", "Taking refuge in this knowledge, they attain unity with my being; they are not born at creation, nor are they troubled at dissolution.", "14.02", "14.02"),
      ("Brahman is my womb; I place the seed", "My womb is the great Brahman; in it I place the seed — from that comes the birth of all beings, O Bhārata.", "14.03", "14.03"),
      ("All wombs, my seed", "Whatever forms arise in any womb, O son of Kuntī — the great Brahman is their womb, and I am the father who gives the seed.", "14.04", "14.04")]),
    ("Three guṇas, three ways of binding",
     "Sattva binds through happiness and knowledge, rajas through craving and action, tamas through ignorance and inertia. All three bind the embodied Self.",
     [("The three qualities", "Sattva, rajas and tamas — the qualities born of prakṛti — bind the imperishable embodied one in the body, O mighty-armed one.", "14.05", "14.05"),
      ("Sattva binds by happiness and knowledge", "Of these, sattva, being pure, illumines and is free from disease; it binds by attachment to happiness and to knowledge, O sinless one.", "14.06", "14.06"),
      ("Rajas binds by attachment to action", "Know rajas as of the nature of passion, born of thirst and attachment; it binds the embodied one by attachment to action, O son of Kuntī.", "14.07", "14.07"),
      ("Tamas binds by sloth and sleep", "Know tamas as born of ignorance, deluding all embodied beings; it binds by heedlessness, sloth and sleep, O Bhārata.", "14.08", "14.08"),
      ("Each binds to its object", "Sattva attaches to happiness, rajas to action, O Bhārata; tamas, covering knowledge, attaches to heedlessness.", "14.09", "14.09")]),
    ("Recognise which guṇa is prevailing",
     "The guṇas overcome one another in turn. Illumination marks sattva; greed and restless activity mark rajas; darkness and confusion mark tamas.",
     [("The Guṇas overpower one another", "Sattva arises by overpowering rajas and tamas; so rajas arises by overpowering sattva and tamas; and so tamas, overpowering both.", "14.10", "14.10"),
      ("When Sattva grows", "When illumination shines through all the gates of this body, then know that sattva has grown.", "14.11", "14.11"),
      ("When Rajas grows", "Greed, activity, the undertaking of works, restlessness and longing arise when rajas has grown, O bull of the Bhāratas.", "14.12", "14.12"),
      ("When Tamas grows", "Darkness, inertia, heedlessness and delusion arise when tamas has grown, O joy of the Kurus.", "14.13", "14.13")]),
    ("The guṇas shape fruit, rebirth and destiny",
     "A prevailing guṇa shapes the next birth and the fruit of action. Knowledge, greed and delusion lead respectively upward, to the middle, or downward.",
     [("Death in Sattva", "If the embodied one meets death when sattva prevails, he attains the pure worlds of the knowers of the highest.", "14.14", "14.14"),
      ("Death in Rajas and Tamas", "Dying in rajas, one is born among those attached to action; dying in tamas, one is born in the wombs of the deluded.", "14.15", "14.15"),
      ("The fruits declared", "They say the fruit of good action is pure and sāttvic; the fruit of rajas is sorrow; the fruit of tamas is ignorance.", "14.16", "14.16"),
      ("Knowledge, greed and delusion, each in turn", "From sattva arises knowledge; from rajas, greed; from tamas arise heedlessness and delusion, and also ignorance.", "14.17", "14.17"),
      ("The three destinies", "Those established in sattva go upward; the rājasic stay in the middle; the tāmasic, sunk in the lowest qualities, go downward.", "14.18", "14.18")]),
    ("Seeing beyond the guṇas: Arjuna asks its marks",
     "Seeing the guṇas as the agents and knowing what is beyond them brings freedom from ageing and death. Arjuna asks how such a person is recognised and lives.",
     [("Beyond the Guṇas", "When the seer perceives no agent other than the guṇas, and knows what is beyond them, he attains my being.", "14.19", "14.19"),
      ("Freed from the Guṇas", "Transcending these three guṇas born of the body, freed from birth, death, old age and sorrow, the embodied one tastes immortality.", "14.20", "14.20"),
      ("The marks of the transcendent", "By what marks is he who has transcended these three guṇas known, O Lord? What is his conduct, and how does he transcend them?", "14.21", "14.21")]),
    ("The steady witness amid every opposite",
     "Neither resisting nor craving the guṇas, the witness stays unmoved. Equal through pleasure, pain, praise, blame, friend and foe, the person stands beyond them.",
     [("Neither hates them nor longs for them", "He who neither hates illumination, activity and delusion when they arise, nor longs for them when they cease, O Pāṇḍava,", "14.22", "14.22"),
      ("Seated like a witness", "— seated as one indifferent, unshaken by the guṇas, thinking 'the guṇas act' and abiding unmoved —", "14.23", "14.23"),
      ("Equal in all things", "— equal in pleasure and pain, self-abiding, to whom a clod, stone and gold are alike, equal to the pleasant and unpleasant, firm, equal in praise and blame —", "14.24", "14.24"),
      ("Equal in honour and dishonour", "— equal in honour and dishonour, equal to friend and foe, renouncing all undertakings — he is said to have transcended the guṇas.", "14.25", "14.25")]),
    ("Devotion crosses the guṇas to Brahman",
     "Unwavering devotion to Kṛṣṇa crosses the guṇas and makes one fit for Brahman. He is the basis of immortality, eternal dharma and absolute bliss.",
     [("Unwavering devotion carries one beyond", "He who serves me with the unwavering yoga of devotion — transcending these guṇas, he becomes fit for Brahman.", "14.26", "14.26"),
      ("I am the support", "For I am the support of Brahman, of immortality and the imperishable, of eternal dharma and of absolute bliss.", "14.27", "14.27")]),
]

CH14_TRANSLATIONS = {
1: ("The Blessed Lord said: I will again declare the supreme knowledge, the best of all knowledges — knowing which all the sages have gone to the highest perfection.",
    "Kṛṣṇa said: “I will now tell you the highest knowledge, the best of all — knowing which, the sages reached the supreme perfection.”"),
2: ("Taking refuge in this knowledge, they attain unity with my being; they are not born at creation, nor are they troubled at dissolution.",
    "“Resting on this knowledge, they become one with me; they are not born at the dawn of creation, nor disturbed at its end.”"),
3: ("My womb is the great Brahman; in it I place the seed — from that comes the birth of all beings, O Bhārata.",
    "“The great Brahman is my womb; I place the seed in it, and from that all beings are born.”"),
4: ("Whatever forms arise in any womb, O son of Kuntī — the great Brahman is their womb, and I am the father who gives the seed.",
    "“Every womb that ever bore a creature — great Nature is that womb, and the seed is mine.”"),
5: ("Sattva, rajas and tamas — the qualities born of prakṛti — bind the imperishable embodied one in the body, O mighty-armed one.",
    "“Sattva, rajas, and tamas — the qualities of nature — bind the deathless Self in the body.”"),
6: ("Of these, sattva, being pure, illumines and is free from disease; it binds by attachment to happiness and to knowledge, O sinless one.",
    "“Sattva is pure, luminous, and healthy — yet it binds through attachment to joy and to knowledge.”"),
7: ("Know rajas as of the nature of passion, born of thirst and attachment; it binds the embodied one by attachment to action, O son of Kuntī.",
    "“Rajas is passion, born of craving and clinging; it binds the embodied soul through attachment to action.”"),
8: ("Know tamas as born of ignorance, deluding all embodied beings; it binds by heedlessness, sloth and sleep, O Bhārata.",
    "“Tamas is born of ignorance, deluding all beings; it binds through carelessness, laziness, and sleep.”"),
9: ("Sattva attaches to happiness, rajas to action, O Bhārata; tamas, covering knowledge, attaches to heedlessness.",
    "“Sattva ties you to joy, rajas to action, and tamas — veiling wisdom — to carelessness.”"),
10: ("Sattva arises by overpowering rajas and tamas; so rajas arises by overpowering sattva and tamas; and so tamas, overpowering both.",
    "“Sattva rises by dominating rajas and tamas; rajas rises by dominating sattva and tamas; and tamas likewise rises over both.”"),
11: ("When illumination shines through all the gates of this body, then know that sattva has grown.",
    "“When light streams through every gate of the body, know that sattva prevails.”"),
12: ("Greed, activity, the undertaking of works, restlessness and longing arise when rajas has grown, O bull of the Bhāratas.",
    "“Greed, busy-ness, starting projects, restlessness, and craving appear when rajas prevails.”"),
13: ("Darkness, inertia, heedlessness and delusion arise when tamas has grown, O joy of the Kurus.",
    "“Dullness, inactivity, carelessness, and confusion arise when tamas prevails.”"),
14: ("If the embodied one meets death when sattva prevails, he attains the pure worlds of the knowers of the highest.",
    "“Dying while sattva prevails, one reaches the pure realms of those who know the highest.”"),
15: ("Dying in rajas, one is born among those attached to action; dying in tamas, one is born in the wombs of the deluded.",
    "“Dying in rajas, one is reborn among the action-bound; dying in tamas, among the deluded.”"),
16: ("They say the fruit of good action is pure and sāttvic; the fruit of rajas is sorrow; the fruit of tamas is ignorance.",
    "“Good deeds bear the pure fruit of sattva; rajas bears sorrow; tamas bears ignorance.”"),
17: ("From sattva arises knowledge; from rajas, greed; from tamas arise heedlessness and delusion, and also ignorance.",
    "“Knowledge comes from sattva; greed from rajas; carelessness, confusion, and ignorance from tamas.”"),
18: ("Those established in sattva go upward; the rājasic stay in the middle; the tāmasic, sunk in the lowest qualities, go downward.",
    "“The sāttvic rise; the rājasic remain in the middle; the tāmasic, bound to the lowest qualities, sink down.”"),
19: ("When the seer perceives no agent other than the guṇas, and knows what is beyond them, he attains my being.",
    "“When the wise one sees that only the guṇas act, and knows what is beyond them, he reaches my own being.”"),
20: ("Transcending these three guṇas born of the body, freed from birth, death, old age and sorrow, the embodied one tastes immortality.",
    "“Rise clear of the three strands the body is woven from, and birth, death, old age and grief lose their hold; what is left is deathless.”"),
21: ("Arjuna said: By what marks is he who has transcended these three guṇas known, O Lord? What is his conduct, and how does he transcend them?",
    "Arjuna asks: “How can one tell who has gone beyond the three qualities, O Lord? How does he live, and how does he cross them?”"),
22: ("The Blessed Lord said: He who neither hates illumination, activity and delusion when they arise, nor longs for them when they cease, O Pāṇḍava,",
    "Kṛṣṇa said: “One who neither resents light, activity, and delusion when they appear, nor yearns for them when they fade,”"),
23: ("— seated as one indifferent, unshaken by the guṇas, thinking 'the guṇas act' and abiding unmoved —",
    "“— seated like an unconcerned onlooker, unshaken by the qualities, thinking ‘the qualities act,’ and standing firm —”"),
24: ("— equal in pleasure and pain, self-abiding, to whom a clod, stone and gold are alike, equal to the pleasant and unpleasant, firm, equal in praise and blame —",
    "“— equal in joy and sorrow, content in himself, seeing mud, stone, and gold alike, unmoved by praise or blame —”"),
25: ("— equal in honour and dishonour, equal to friend and foe, renouncing all undertakings — he is said to have transcended the guṇas.",
    "“— equal in honour and disgrace, friend and foe, giving up all selfish undertakings — such a one is beyond the qualities.”"),
26: ("He who serves me with the unwavering yoga of devotion — transcending these guṇas, he becomes fit for Brahman.",
    "“Whoever serves me with steadfast devotion — crossing these qualities — becomes worthy of Brahman.”"),
27: ("For I am the support of Brahman, of immortality and the imperishable, of eternal dharma and of absolute bliss.",
    "“For I am the ground of Brahman, of immortality and the eternal — of everlasting dharma and of perfect bliss.”"),
}
