# -*- coding: utf-8 -*-
"""gita_data7.py — Chapter 7 (Jñāna-Vijñāna Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH7_THEMES = [
    ("Know me fully, with realization",
     "Hear how, with mind absorbed in me, you shall know me fully; scarcely one in thousands strives, and of those who strive, scarcely one knows me in truth.",
     [("Hear how you shall know me fully", "With mind absorbed in me, practising yoga and taking refuge in me, hear how you shall know me completely, free from doubt. I shall declare to you in full this knowledge and realization, knowing which nothing more remains to be known here.", "7.01", "7.01"),
      ("Realization, not mere knowledge", "I'll teach you this wisdom fully — together with its direct realization. Once you know it, nothing else remains to be known.", "7.02", "7.02"),
      ("One in thousands strives", "Among thousands of men, scarcely one strives for perfection; and among those who strive, scarcely one knows me in truth.", "7.03", "7.03")]),
    ("My two natures, lower and higher",
     "The eightfold lower nature and the higher nature that sustains the world; all beings have their womb in these, and all is strung on me like pearls on a thread.",
     [("The eightfold lower nature", "Earth, water, fire, air, ether, mind, intellect and ego — this is my nature divided eightfold.", "7.04", "7.04"),
      ("The higher nature that sustains the world", "This is the lower; but know my other and higher nature, the life-element by which this world is sustained.", "7.05", "7.05"),
      ("The womb of all beings", "Know that all beings have their birth in these two; I am the origin of the whole universe, and its dissolution too.", "7.06", "7.06"),
      ("Strung on me like pearls on a thread", "There is nothing higher than me, O Dhanañjaya; all this is strung on me like clusters of gems on a thread.", "7.07", "7.07")]),
    ("I am the essence of every thing",
     "The taste in water, the light of sun and moon, the fragrance of earth, the eternal seed of all beings.",
     [("The taste in water, the light in sun and moon", "I am the taste in water, the radiance in moon and sun, the sacred syllable Om in all the Vedas, the sound in ether, the manhood in men.", "7.08", "7.08"),
      ("The fragrance of earth, the heat in fire", "I am the pure fragrance of the earth and the brightness in fire, the life in all beings and the austerity in ascetics.", "7.09", "7.09"),
      ("The eternal seed of all beings", "Know me as the eternal seed of all beings; I am the intelligence of the intelligent, the splendour of the splendid.", "7.10", "7.10"),
      ("Desire not opposed to dharma", "I am the strength of the strong, free from desire and attachment; and in beings I am desire that is not contrary to dharma.", "7.11", "7.11")]),
    ("The guṇas come from me, I am not in them",
     "The guṇas come from me, yet I am not in them; deluded, the world does not know me. This divine māyā is hard to cross except by refuge in me; evildoers clinging to the demoniac nature do not come to me.",
     [("They are in me, I am not in them", "Whatever states there are of sattva, rajas and tamas — know them as from me alone; yet I am not in them, they are in me.", "7.12", "7.12"),
      ("The world does not know me", "Deluded by these three states made of the guṇas, this whole world does not know me, who am beyond them and imperishable.", "7.13", "7.13"),
      ("This divine Māyā is hard to cross", "This divine māyā of mine, made of the guṇas, is hard to cross over; but those who take refuge in me alone cross beyond it.", "7.14", "7.14"),
      ("The evildoers do not come to me", "Evildoers, the deluded and the lowest of men, whose knowledge is carried away by māyā and who cling to demoniac nature, do not come to me.", "7.15", "7.15")]),
    ("The Four Kinds of Devotees",
     "Four kinds of virtuous men worship me — the distressed, the seeker of knowledge, the seeker of wealth, and the wise; of these the wise one is dearest.",
     [("Four kinds worship me", "Four kinds of virtuous men worship me, O Arjuna: the distressed, the seeker of knowledge, the seeker of wealth, and the wise.", "7.16", "7.16"),
      ("The wise one is dearest", "Of these the wise one, ever steadfast and devoted to the One, excels; for I am exceedingly dear to the wise, and he is dear to me. All these are noble, but the wise one I hold to be my very Self; for he, steadfast in mind, is established in me as the supreme goal.", "7.17", "7.17"),
      ("The wise one is my very Self", "All four are noble, but the wise one is my very self — established in me, the highest goal.", "7.18", "7.18"),
      ("At the end of many births", "At the end of many births the man of wisdom comes to me, knowing 'Vāsudeva is all' — such a great soul is very rare.", "7.19", "7.19")]),
    ("Those who worship other gods reach them",
     "Those whose discernment is carried away by desires resort to other gods; I make their faith unshakeable, but their fruit is finite.",
     [("Deprived of discernment", "Those whose knowledge is carried away by desires resort to other gods, following this or that rite, constrained by their own nature.", "7.20", "7.20"),
      ("I make a devotee's faith unshakeable", "Whatever form a devotee seeks to worship with faith, that very faith I make unshakeable. Endowed with that faith he worships that form, and from it obtains his desires — ordained in truth by me alone.", "7.21", "7.21"),
      ("The desires are granted", "With that faith he worships, and his desires are granted — though the granting comes from me.", "7.22", "7.22"),
      ("Finite fruit for the finite-minded", "But finite is the fruit gained by those of small understanding; the worshippers of gods go to the gods, my devotees come to me.", "7.23", "7.23")]),
    ("The Unmanifest and the Undeluded",
     "The unwise think the Unmanifest has become manifest; veiled by yoga-māyā I am not revealed to all — but those who know Brahman entire know me even at the hour of death.",
     [("The unwise think me manifest", "The unintelligent think of me, the unmanifest, as having come into manifestation, not knowing my higher, imperishable, supreme nature.", "7.24", "7.24"),
      ("Veiled by my Yoga-Māyā", "Veiled by my yoga-māyā, I am not revealed to all; this deluded world does not know me, the unborn and imperishable.", "7.25", "7.25"),
      ("I know all beings; none knows me", "I know the beings that are past, present and yet to come — but none knows me.", "7.26", "7.26"),
      ("Deluded by the pairs of opposites", "By the delusion of the pairs of opposites, arising from desire and hatred, all beings are born into confusion.", "7.27", "7.27"),
      ("Whose sin has ended, freed from the pairs", "But men of virtuous deeds whose sin has come to an end, freed from the delusion of the pairs, worship me with firm resolve.", "7.28", "7.28"),
      ("Striving for freedom, they know Brahman", "Those who strive for release from old age and death, taking refuge in me, know Brahman entire, the Self, and all action. Those who know me together with the adhibhūta, adhidaiva and adhiyajña know me even at the hour of departure, their minds steadfast.", "7.29", "7.29"),
      ("Knowing me, they know me even at death", "Those who know me as pervading all beings, all gods, and all sacrifice — even at death's hour, with steady minds, they know me.", "7.30", "7.30")]),
]

CH7_TRANSLATIONS = {
1: ("The Blessed Lord said: With the mind attached to me, O Pārtha, practising yoga and taking refuge in me — how, without doubt, you will know me in full, that listen.",
    "Kṛṣṇa said: “Fix your mind on me, practise yoga, and take refuge in me — then you will know me completely. Listen to how.”"),
2: ("I shall declare to you this knowledge together with its realization, without remainder; knowing which, nothing further remains to be known here.",
    "“I'll teach you this wisdom fully — together with its direct realization. Once you know it, nothing else remains to learn.”"),
3: ("Among thousands of men, one perchance strives for perfection; and among those who strive, one perchance knows me in truth.",
    "“Out of thousands, one seeks perfection; and of those perfected, one truly knows me.”"),
4: ("Earth, water, fire, air, ether, mind, intellect and egoism — thus is my nature divided eightfold.",
    "“Earth, water, fire, air, ether, mind, intellect, and ego — these eight make up my lower nature.”"),
5: ("This is the lower nature; but know my other nature, higher than this, O mighty-armed one — the life-element, by which the world is upheld.",
    "“That is my lower nature. But I have a higher nature — the living soul — by which this whole world is sustained.”"),
6: ("Know that these two natures are the womb of all beings; I am the origin and also the dissolution of the whole world.",
    "“Everything is born from these two natures of mine. I am the source and the end of the entire universe.”"),
7: ("There is nothing whatever higher than me, O Dhanañjaya; all this is strung on me, like a row of gems on a thread.",
    "“Nothing exists beyond me. All this is strung on me, like jewels threaded on a string.”"),
8: ("I am the taste in waters, O son of Kuntī; I am the radiance of the moon and the sun; the sacred syllable Om in all the Vedas; the sound in ether; the manliness in men.",
    "“I am the taste of water, the light of moon and sun, the Om in the Vedas, the sound in space, the strength of manhood.”"),
9: ("I am the pure fragrance of the earth and the heat of fire; the life of all beings and the austerity of the ascetics.",
    "“I am the fragrance of earth, the warmth of fire, the life in all beings, the tapas of ascetics.”"),
10: ("Know me as the eternal seed of all beings; I am the intelligence of the intelligent, the splendour of the splendid.",
    "“Know me as the eternal seed of everything — the wisdom of the wise, the brilliance of the brilliant.”"),
11: ("And I am the strength of the strong, devoid of desire and attachment; and in beings I am desire that is not opposed to dharma, O bull of the Bhāratas.",
    "“I am the strength of the strong, free of craving; and in beings I am the desire that accords with righteousness.”"),
12: ("And whatever states there are, of sattva, rajas or tamas — know them all as from me alone; yet I am not in them, they are in me.",
    "“All the qualities — sattva, rajas, tamas — come from me. Yet I am beyond them, though they rest in me.”"),
13: ("Deluded by these states made of the three guṇas, this entire world does not know me, who am beyond them, imperishable.",
    "“Bewildered by the three qualities, the world fails to know me — who stand beyond them, eternal.”"),
14: ("This divine māyā of mine, consisting of the guṇas, is hard to overcome; but those who take refuge in me alone cross beyond this māyā.",
    "“My divine power of māyā is hard to cross — but those who surrender to me alone pass beyond it.”"),
15: ("The wrong-doers, the deluded, the lowest of men do not resort to me; robbed of knowledge by māyā, they cling to a demoniac nature.",
    "“The wicked, the deluded, the degraded — robbed of wisdom by māyā and demonic in nature — do not turn to me.”"),
16: ("Four kinds of men of good deeds worship me, O Arjuna: the afflicted, the seeker of knowledge, the seeker of wealth, and the wise.",
    "“Four kinds of good people worship me: the suffering, the curious, the ambitious, and the wise.”"),
17: ("Of them, the man of knowledge, ever yoked, of single devotion, is the best; for I am extremely dear to the wise, and he is dear to me.",
    "“The wisest — ever united to me, single-hearted — is the best. I am deeply dear to him, and he to me.”"),
18: ("Noble are all these; but the wise one is my very self, in my opinion; for he, self-possessed, is established in me, the supreme goal.",
    "“All four are noble, but the wise one is my very self — established in me, the highest goal.”"),
19: ("At the end of many births, the man of wisdom resorts to me, thinking 'Vāsudeva is all'; that great soul is very rare.",
    "“After many lives, the wise come to me, knowing that Vāsudeva is all — such a great soul is extremely rare.”"),
20: ("Those whose knowledge is stolen by desires resort to other deities, following this or that rite, constrained by their own nature.",
    "“Carried away by craving, people worship other gods, following various rules set by their own nature.”"),
21: ("Whatever divine form a devotee desires to worship with faith, I render that very faith of his steady.",
    "“Whatever form a devotee wants to honour with faith, I make that faith firm and steady.”"),
22: ("United with that faith, he engages in the worship of that deity, and from it obtains his desires — which are verily ordained by me.",
    "“With that faith he worships, and his desires are granted — though the granting comes from me.”"),
23: ("But the fruit of those worshippers is limited; the fruit belongs to the small-minded. The worshippers of the gods go to the gods; my devotees come to me.",
    "“But such worship bears only limited fruit. God-worshippers reach the gods; my devotees reach me.”"),
24: ("The unintelligent, not knowing my higher nature — imperishable and unsurpassed — think of me, the unmanifest, as one who has taken on manifestation.",
    "“Fools think of me — the unmanifest — as merely a manifested being, not knowing my higher, eternal nature.”"),
25: ("I am not manifest to all, being enveloped by yoga-māyā; this deluded world does not know me, the unborn, the imperishable.",
    "“Hidden by my divine power, I am not visible to all; the deluded world fails to know me — unborn, eternal.”"),
26: ("I know, O Arjuna, the beings that have passed, that exist now, and that are to come; but no one knows me.",
    "“I know all beings — past, present, and future. But no one truly knows me.”"),
27: ("By the delusion of the pairs of opposites, arising from desire and aversion, O Bhārata, all beings go to delusion at birth, O scorcher of foes.",
    "“Born of liking and disliking, the pairs of opposites delude all beings from birth.”"),
28: ("But those men of good deeds whose sins have come to an end — freed from the delusion of the pairs of opposites — worship me with firm vows.",
    "“Those whose sins are spent, whose deeds are good, freed from the pairs of opposites, worship me with firm resolve.”"),
29: ("Those who, striving for freedom from old age and death, take refuge in me — they know Brahman, the entire adhyātma, and all action.",
    "“Those who seek freedom from age and death, taking refuge in me, come to know Brahman, the Self, and the whole of karma.”"),
30: ("Those who know me along with the elements, the deities and the sacrifice — even at the time of death, with minds established, they know me.",
    "“Those who know me as pervading all beings, all gods, and all sacrifice — even at death's hour, with steady minds, they know me.”"),
}
