# -*- coding: utf-8 -*-
"""gita_data12.py — Chapter 12 (Bhakti Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH12_THEMES = [
    ("Devotion or the unmanifest: the choice of path",
     "Arjuna compares devotion with the unmanifest path. Both reach Kṛṣṇa, but faith-filled personal devotion is praised; the unmanifest is harder for the embodied.",
     [("Which knows yoga better?", "Those devotees who, ever united, worship you — and those who worship the imperishable unmanifest — which of these are the better knowers of yoga?", "12.01", "12.01"),
      ("Those ever-united in me are best in yoga", "Those who, fixing their minds on me, ever united, worship me with supreme faith — them I deem the most yoked.", "12.02", "12.02"),
      ("Some worship the imperishable unmanifest", "But those who worship the imperishable, the indefinable, the unmanifest — the all-pervading, unthinkable, unchanging, immovable, eternal —", "12.03", "12.03"),
      ("They too reach me", "— controlling all the senses, of equal mind everywhere, rejoicing in the welfare of all beings — they too reach me.", "12.04", "12.04"),
      ("Greater is the toil of those set on the unmanifest", "Greater is the toil of those whose minds are attached to the unmanifest; the unmanifest is hard to attain by embodied beings.", "12.05", "12.05")]),
    ("Surrender and fix the heart on me",
     "Kṛṣṇa swiftly delivers those who dedicate action and meditate on him. Fix mind and intellect in him: the promise is to dwell in him.",
     [("Those who surrender all to me", "But those who surrender all actions to me, intent on me, worshipping me with undivided yoga and meditating on me,", "12.06", "12.06"),
      ("I become their deliverer from the ocean of death", "— for them, whose minds are fixed on me, O Pārtha, I swiftly become the deliverer from the ocean of death and rebirth.", "12.07", "12.07"),
      ("Fix your mind on me alone", "Fix your mind on me alone; establish your intellect in me; then you shall live in me alone — of this there is no doubt.", "12.08", "12.08")]),
    ("A ladder of practice ending in peace",
     "A graded path: if concentration is difficult, practise; if that is difficult, work for Kṛṣṇa. If needed, relinquish action’s fruits: renunciation brings peace.",
     [("Then seek me by repeated practice", "If you cannot fix your mind steadily on me, then practise the yoga of repetition — seek to reach me by practice, O Dhanañjaya.", "12.09", "12.09"),
      ("If not, work for my sake", "If you are unable to practise even that, be devoted to working for me; even performing actions for my sake, you shall attain perfection.", "12.10", "12.10"),
      ("If not even that, renounce the fruit", "If you cannot do even this, then, taking refuge in my yoga, renounce the fruit of all actions — with the self controlled.", "12.11", "12.11"),
      ("Better than knowledge is renunciation of fruit", "Better indeed is knowledge than practice; better than knowledge is meditation; better than meditation is renunciation of the fruit of action — for from renunciation comes peace, immediately.", "12.12", "12.12")]),
    ("Compassion and self-mastery make a dear devotee",
     "The dear devotee hates no being, is compassionate and steady, neither disturbs the world nor is disturbed by it, free of expectation, and renounces all undertakings.",
     [("Hating no being, friendly and compassionate", "He who hates no being, is friendly and compassionate, free from possessiveness and ego, equal in pleasure and pain, forgiving —", "12.13", "12.13"),
      ("Ever content, resolved, given to me", "— ever content, a yogi, self-controlled, of firm resolve, mind and intellect offered to me — that devotee of mine is dear to me.", "12.14", "12.14"),
      ("He by whom the world is not disturbed", "He by whom the world is not disturbed, and who is not disturbed by the world — freed from joy, anger, fear and anxiety — he is dear to me.", "12.15", "12.15"),
      ("Unattached, pure, capable, untroubled", "He who is unattached, pure, capable, indifferent, free from anxiety, renouncing all undertakings — that devotee of mine is dear to me.", "12.16", "12.16")]),
    ("Evenness and faithful devotion complete the path",
     "Equal through praise and blame, friend and foe, the devotee remains content and steady. Those who follow this immortal dharma with faith are exceedingly dear.",
     [("Neither rejoicing nor hating", "He who neither rejoices nor hates, neither grieves nor desires, renouncing good and evil — that devoted one is dear to me.", "12.17", "12.17"),
      ("Equal to friend and foe, honour and dishonour", "Equal to friend and foe, to honour and dishonour, to cold and heat, pleasure and pain, free from attachment —", "12.18", "12.18"),
      ("Silent, satisfied with anything", "— silent, content with anything, homeless, of steady mind, full of devotion — that man is dear to me.", "12.19", "12.19"),
      ("They who follow this immortal dharma are dearest", "But those who follow this immortal dharma, as declared, with faith, making me the supreme goal — those devotees are exceedingly dear to me.", "12.20", "12.20")]),
]

CH12_TRANSLATIONS = {
1: ("Arjuna said: Those devotees who, ever united, worship you — and those who worship the imperishable unmanifest — which of these are the better knowers of yoga?",
    "Arjuna asks: “Which are the greater yogis — those who worship you with devotion, or those who worship the formless, imperishable Absolute?”"),
2: ("The Blessed Lord said: Those who, fixing their minds on me, ever united, worship me with supreme faith — them I deem the most yoked.",
    "Kṛṣṇa said: “Those who fix their minds on me, ever devoted, worshipping me with supreme faith — they are the greatest yogis in my view.”"),
3: ("But those who worship the imperishable, the indefinable, the unmanifest — the all-pervading, unthinkable, unchanging, immovable, eternal —",
    "“But those who worship the unmanifest — indefinable, all-pervading, unthinkable, immutable, eternal —”"),
4: ("— controlling all the senses, of equal mind everywhere, rejoicing in the welfare of all beings — they too reach me.",
    "“— who restrain the senses, see all equally, and delight in the good of all beings — they also reach me.”"),
5: ("Greater is the toil of those whose minds are attached to the unmanifest; the unmanifest is hard to attain by embodied beings.",
    "“But their struggle is greater, for the formless Absolute is hard to reach for those who dwell in bodies.”"),
6: ("But those who surrender all actions to me, intent on me, worshipping me with undivided yoga and meditating on me,",
    "“But those who offer all their actions to me, take me as supreme, and worship me with single-minded meditation,”"),
7: ("— for them, whose minds are fixed on me, O Pārtha, I swiftly become the deliverer from the ocean of death and rebirth.",
    "“— for them, whose hearts rest in me, I quickly become their saviour from the ocean of birth and death.”"),
8: ("Fix your mind on me alone; establish your intellect in me; then you shall live in me alone — of this there is no doubt.",
    "“Rest your mind and understanding on me alone — and you will surely live in me; of this there is no doubt.”"),
9: ("If you cannot fix your mind steadily on me, then practise the yoga of repetition — seek to reach me by practice, O Dhanañjaya.",
    "“If you cannot fix your mind on me steadily, then use repeated practice to reach me, Arjuna.”"),
10: ("If you are unable to practise even that, be devoted to working for me; even performing actions for my sake, you shall attain perfection.",
    "“If even that is beyond you, devote yourself to working for me — doing your work for my sake, you will reach perfection.”"),
11: ("If you cannot do even this, then, taking refuge in my yoga, renounce the fruit of all actions — with the self controlled.",
    "“If you cannot do even that, then surrender the fruits of all your actions to me — with a self-controlled mind.”"),
12: ("Better indeed is knowledge than practice; better than knowledge is meditation; better than meditation is renunciation of the fruit of action — for from renunciation comes peace, immediately.",
    "“Knowledge is better than practice; meditation is better than knowledge; and better still is renouncing the fruits of work — for that brings peace at once.”"),
13: ("He who hates no being, is friendly and compassionate, free from possessiveness and ego, equal in pleasure and pain, forgiving —",
    "“One who hates no one, is kind and compassionate, free of 'mine' and 'I', even in joy and sorrow, patient —”"),
14: ("— ever content, a yogi, self-controlled, of firm resolve, mind and intellect offered to me — that devotee of mine is dear to me.",
    "“— always content, self-mastered, resolute, with mind and heart given to me — such a devotee is dear to me.”"),
15: ("He by whom the world is not disturbed, and who is not disturbed by the world — freed from joy, anger, fear and anxiety — he is dear to me.",
    "“One who disturbs no one and is disturbed by no one, free from joy, anger, fear, and worry — he is dear to me.”"),
16: ("He who is unattached, pure, capable, indifferent, free from anxiety, renouncing all undertakings — that devotee of mine is dear to me.",
    "“One who is detached, pure, skilled, neutral, worry-free, and gives up all selfish projects — that devotee is dear to me.”"),
17: ("He who neither rejoices nor hates, neither grieves nor desires, renouncing good and evil — that devoted one is dear to me.",
    "“One who neither delights nor despairs, neither mourns nor craves, letting go of good and evil — such a devotee is dear to me.”"),
18: ("Equal to friend and foe, to honour and dishonour, to cold and heat, pleasure and pain, free from attachment —",
    "“Equal toward friend and enemy, praise and blame, cold and heat, joy and sorrow, free from clinging —”"),
19: ("— silent, content with anything, homeless, of steady mind, full of devotion — that man is dear to me.",
    "“— silent, satisfied with whatever comes, unattached to place, steady-minded, devoted — such a person is dear to me.”"),
20: ("But those who follow this immortal dharma, as declared, with faith, making me the supreme goal — those devotees are exceedingly dear to me.",
    "“But those who follow this deathless dharma with faith, holding me as the highest goal — such devotees are most dear to me of all.”"),
}
