# -*- coding: utf-8 -*-
"""gita_data9.py — Chapter 9 (Rāja-Vidyā-Rāja-Guhya Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH9_THEMES = [
    ("The Royal Secret",
     "Kṛṣṇa reveals the greatest secret: knowledge with realization, the royal knowledge, which frees one from evil.",
     [("The Supreme Secret", "I will declare to you — who do not carp — this profoundest secret: knowledge with realization, knowing which you are freed from evil.", "9.01", "9.01"),
      ("The Royal Knowledge", "This is the royal knowledge, the royal secret, the purest, directly realized, righteous, easy to practise, imperishable — but those without faith in it return to death and rebirth.", "9.02", "9.03")]),
    ("The Lord Who Pervades All",
     "All this is pervaded by me, yet I am not in them; the Lord upholds beings while remaining apart — by his yoga-māyā.",
     [("All Pervaded by Me", "I pervade this whole world in my unmanifest form; all beings dwell in me, yet I am not in them.", "9.04", "9.04"),
      ("The Divine Yoga", "Beings are not in me — behold my divine yoga! I sustain beings yet stand apart, like the vast wind moving everywhere in space.", "9.05", "9.06")]),
    ("The Cycles of Creation",
     "At the end of a kalpa all beings dissolve into my prakṛti; at the beginning I send them forth again — yet these actions do not bind me.",
     [("The Revolving Creation", "At the end of the cycle all beings return to my nature; at the beginning I send them forth again, helpless under nature's sway.", "9.07", "9.08"),
      ("Unbound by Action", "These actions do not bind me, sitting indifferent, unattached; by my supervision nature brings forth the moving and unmoving.", "9.09", "9.10")]),
    ("The Deluded and the Devoted",
     "The deluded, not knowing my supreme being, despise me in my human form; but the great souls, taking refuge in the divine nature, worship me.",
     [("The Deluded Despise Me", "Fools, unaware of my supreme being, despise me wearing a human form; their hopes, works and knowledge are in vain.", "9.11", "9.12"),
      ("The Great Souls Know Me as Imperishable", "But the great souls, resorting to the divine nature, worship me with undivided mind, knowing me as the imperishable source of beings.", "9.13", "9.13"),
      ("Ever Glorifying Me, Firm in Vows", "Always glorifying me, striving with firm vows, bowing to me with devotion, ever united — they worship me.", "9.14", "9.14"),
      ("The Sacrifice of Knowledge", "And others worship me with the sacrifice of knowledge — as the one, as the distinct, as the manifold facing everywhere.", "9.15", "9.15")]),
    ("I Am All",
     "I am the sacrifice, the oblation, the fire, the father, mother, support, goal, refuge and friend — I am everything.",
     [("I Am the Sacrifice", "I am the rite, the sacrifice, the oblation, the herb, the mantra, the fire — and the father, mother, supporter, purifier, Om, and the Vedas.", "9.16", "9.17"),
      ("I Am Everything", "I am the way, the lord, the witness, the abode, refuge and friend — the origin, dissolution, ground, treasure and eternal seed.", "9.18", "9.19")]),
    ("The Finite Fruit of Works",
     "The ritualists who drink soma seek heaven and enjoy divine pleasures; but when merit is spent they return — desiring desires, they come and go.",
     [("The Soma-Drinkers", "The Vedic scholars, drinking soma, pray for heaven and enjoy Indra's world; when merit is spent they return — desiring desires, they come and go.", "9.20", "9.21")]),
    ("The Devoted Are My Care",
     "Those who worship me alone, ever united, I carry their yoga and kṣema; even those who worship other gods worship me — though wrongly.",
     [("I Carry the Devoted", "To those ever united to me who worship me, I myself carry what they lack and preserve what they have.", "9.22", "9.22"),
      ("Even Those Who Worship Other Gods", "Even those devoted to other deities, worshipping them with faith, worship me alone — though not in the prescribed way.", "9.23", "9.23"),
      ("I Am the Enjoyer of All Sacrifices", "For I alone am the enjoyer and lord of all sacrifices; not knowing me in truth, they fall. Worshippers of gods go to the gods, of ancestors to the ancestors — but my worshippers come to me.", "9.24", "9.25")]),
    ("Offering All to Me",
     "Offer every action to me; whatever is done with devotion, even a leaf or a drop, I accept; thus freed from bondage, you come to me.",
     [("The Leaf, the Flower, the Water", "Whatever a devotee offers me with love — a leaf, a flower, fruit or water — I accept it from the pure-hearted.", "9.26", "9.26"),
      ("Freed from Bondage", "Offer to me whatever you do, eat, sacrifice, give or practise — then you are freed from the bonds of good and evil karma.", "9.27", "9.28")]),
    ("The Lord Is Equal to All",
     "I am equal to all beings; none is dear or hated by me — but those who worship me with devotion dwell in me, and I in them.",
     [("Equal to All", "I am the same to all beings; no one is dear or hated by me. But those who worship me with devotion — they are in me, and I in them.", "9.29", "9.29"),
      ("Even the Wicked Is Saved", "Even the most wicked, worshipping me with single devotion, is to be counted as good — he is rightly resolved; he quickly becomes righteous and attains peace.", "9.30", "9.31")]),
    ("No One Is Excluded",
     "All who take refuge in me — even those of sinful birth, women, vaiśyas, śūdras — reach the supreme goal; and blessed brāhmaṇas and royal sages worship me.",
     [("All Reach Me", "Those who take refuge in me — even those of sinful birth, women, traders and labourers — reach the supreme goal.", "9.32", "9.32"),
      ("Worship Me", "How much more then the holy brāhmaṇas and devoted royal sages! Having come to this impermanent, joyless world, worship me.", "9.33", "9.34")]),
]

CH9_TRANSLATIONS = {
1: ("The Blessed Lord said: To you, who do not find fault, I will declare this profoundest secret — knowledge together with its realization; knowing which, you shall be freed from evil.",
    "Kṛṣṇa said: “Because you are sincere, Arjuna, I will teach you the deepest secret — wisdom with its direct realization. Knowing it, you will be free of all evil.”"),
2: ("This is the royal knowledge, the royal secret, the supreme purifier, directly perceived, righteous, very easy to practise, and imperishable.",
    "“This is the king of knowledge and of secrets — the purest, seen directly, in accord with dharma, easy to follow, and eternal.”"),
3: ("The men without faith in this dharma, O scorcher of foes, not reaching me, return to the path of death and rebirth.",
    "“Those without faith in this teaching turn back on the path of death and rebirth, never reaching me.”"),
4: ("By me this whole world is pervaded in my unmanifest form; all beings rest in me, but I am not contained in them.",
    "“I pervade this entire world in my unmanifest form. All beings dwell in me, yet I do not dwell in them.”"),
5: ("And beings do not rest in me — behold my divine yoga! I sustain all beings yet stand apart, and my self is the origin of beings.",
    "“Beings do not truly rest in me — see my divine power! I support all beings, yet remain separate; I am their source.”"),
6: ("As the vast wind, ever moving, abides in space, so all beings abide in me — know this.",
    "“As the great wind moves everywhere and yet lives in space, so all beings live in me — understand this.”"),
7: ("All beings, O son of Kuntī, return to my prakṛti at the end of a kalpa; at the beginning of a kalpa I send them forth again.",
    "“At the end of the cosmic age, all beings merge back into my nature; at the dawn of the age, I send them out again.”"),
8: ("Taking hold of my own prakṛti, I send forth again and again this whole host of beings, helpless under the power of nature.",
    "“Through my own nature I project this entire multitude of beings again and again — creatures helpless under nature's sway.”"),
9: ("These actions do not bind me, O Dhanañjaya, for I sit as one indifferent, unattached to these actions.",
    "“None of this binds me, Arjuna — I remain detached and indifferent, like an unconcerned onlooker.”"),
10: ("Under my supervision, prakṛti brings forth the moving and the unmoving; for this reason, O son of Kuntī, the world revolves.",
    "“Under my direction nature produces everything moving and still; that is why the world turns.”"),
11: ("The deluded, not knowing my supreme being, despise me wearing a human form.",
    "“Fools, blind to my higher nature, look down on me when I take a human body.”"),
12: ("Of vain hopes, vain works and vain knowledge, senseless — they cling to the deluding, demoniac and asuric nature.",
    "“Their hopes, deeds and learning are all in vain; confused and lost, they follow a deluded, demonic nature.”"),
13: ("But the great souls, O Pārtha, taking refuge in the divine nature, worship me with undivided mind, knowing me as the imperishable source of beings.",
    "“The noble souls, Arjuna, turn to the divine nature and worship me single-mindedly, knowing me as the eternal source of all.”"),
14: ("Always glorifying me, striving with firm vows, bowing to me with devotion, ever united — they worship me.",
    "“Always singing my praise, striving with steady resolve, bowing to me in devotion — the ever-united worship me.”"),
15: ("And others worship me with the sacrifice of knowledge, worshipping me as the one, as the distinct, as the manifold facing everywhere.",
    "“Others offer the sacrifice of wisdom — worshipping me as one, as many, as the all-facing divine.”"),
16: ("I am the rite, I am the sacrifice, I am the oblation to the ancestors, I am the herb; I am the mantra, I am the butter, I am the fire, I am the offering.",
    "“I am the ritual, the offering, the ancestral oblation, the healing herb, the chant, the ghee, the fire, and the gift.”"),
17: ("I am the father and mother of this world, its supporter and grandsire; I am the object of knowledge, the purifier, the syllable Om, and the Ṛk, Sāma and Yajus.",
    "“I am the father and mother of the world, its support and grandsire; I am what is to be known, the purifier, the Om, and the three Vedas.”"),
18: ("I am the goal, the sustainer, the lord, the witness, the abode, the refuge and the friend; the origin, dissolution, ground, treasure and eternal seed.",
    "“I am the goal, the bearer, the master, the witness, the home, the refuge, and the friend — the source, end, resting-place, store, and deathless seed of all.”"),
19: ("I give heat; I send and withhold the rain; I am immortality and also death; I am the real and the unreal, O Arjuna.",
    "“I radiate warmth; I hold back the rain and release it. I am life and death, being and non-being, Arjuna.”"),
20: ("The knowers of the three Vedas, drinking soma, purified of sin, worshipping me by sacrifice, pray for the path to heaven; attaining the world of Indra, they enjoy the divine pleasures of the gods in heaven.",
    "“The Vedic ritualists, drinking soma and cleansed of sin, worship me through sacrifice to gain heaven; they enjoy the celestial delights of Indra's world.”"),
21: ("Having enjoyed the vast world of heaven, when their merit is exhausted they return to the world of mortals; thus, following the dharma of the three Vedas, desiring desires, they come and go.",
    "“When their merit is spent after enjoying vast heavenly bliss, they fall back into the mortal world — ever going and returning, bound by desire.”"),
22: ("To those who worship me, ever united, thinking of me alone — for them, ever devoted, I myself carry what they lack and preserve what they have.",
    "“For those who worship me with single-minded devotion, ever united to me, I myself supply what they lack and keep safe what they have.”"),
23: ("Even those who, devoted to other deities, worship them with faith — they worship me alone, O son of Kuntī, though not in the prescribed way.",
    "“Even devotees of other gods, worshipping them in faith, are really worshipping me — though not in the proper manner.”"),
24: ("For I alone am the enjoyer and lord of all sacrifices; but they do not know me in truth, and so they fall.",
    "“I alone am the receiver and lord of every offering. But they do not truly know me, and so they fall away.”"),
25: ("The worshippers of the gods go to the gods; the worshippers of the ancestors go to the ancestors; the worshippers of the spirits go to the spirits; but my worshippers come to me.",
    "“God-worshippers reach the gods, ancestor-worshippers the ancestors, spirit-worshippers the spirits — but my devotees come to me.”"),
26: ("Whoever offers me with devotion a leaf, a flower, a fruit or water — I accept that offering of the pure-hearted.",
    "“Give me with love even a leaf, a flower, a fruit, or water — I accept it from one whose heart is pure.”"),
27: ("Whatever you do, whatever you eat, whatever you offer, whatever you give, whatever austerity you perform, O son of Kuntī — do it as an offering to me.",
    "“Whatever you do, eat, offer, give, or practise as austerity — offer it all to me.”"),
28: ("Thus you shall be freed from the bonds of actions, which bear good and evil fruit; with the self yoked in renunciation, liberated, you shall come to me.",
    "“Doing this, you are freed from the ties of karma and their fruits of good and evil; renouncing in yoga, liberated, you come to me.”"),
29: ("I am the same to all beings; none is dear or hated by me; but those who worship me with devotion — they are in me, and I am in them.",
    "“I play no favourites. Nobody is dearer to me than anyone else. But love me, and you will find you are living in me, and I in you.”"),
30: ("Even if a man of very evil conduct worships me with single-minded devotion, he is to be regarded as good, for he is rightly resolved.",
    "“Even a most wicked person who worships me with undivided love must be counted among the good — for his resolve is right.”"),
31: ("Quickly he becomes righteous of soul and attains lasting peace; know this for certain, O son of Kuntī: my devotee never perishes.",
    "“He soon becomes righteous and reaches enduring peace. Know it for certain: my devotee never comes to ruin.”"),
32: ("For those who take refuge in me, O Pārtha — even those of sinful birth, women, traders and labourers — they too reach the supreme goal.",
    "“All who come to me for refuge — even the low-born, women, merchants, and workers — reach the highest goal.”"),
33: ("How much more then the holy brāhmaṇas and the devoted royal sages! Having come to this impermanent, joyless world, worship me.",
    "“How much more the pure brāhmaṇas and devoted sage-kings! In this fleeting, sorrowful world, worship me.”"),
34: ("Fix your mind on me, be my devotee, offer to me, bow to me — thus yoking the self to me, intent on me, you shall surely come to me.",
    "“Fix your thought on me, be my devotee, worship me, bow to me — devoted wholly to me, you will surely reach me.”"),
}
