# -*- coding: utf-8 -*-
"""gita_data10.py — Chapter 10 (Vibhūti Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH10_THEMES = [
    ("Hear My Supreme Word",
     "Neither gods nor great seers know my origin; he who knows me as unborn and beginningless is freed from all sins.",
     [("Hear Again My Supreme Word", "Hear again, O mighty-armed, my supreme word, which I shall declare to you who are beloved, desiring your welfare.", "10.01", "10.01"),
      ("Neither Gods Nor Seers Know My Origin", "Neither the hosts of gods nor the great seers know my origin; for I am in every way the source of the gods and the great seers.", "10.02", "10.02"),
      ("He Who Knows Me Unborn and Beginningless", "He who knows me as unborn and beginningless, the great Lord of the worlds — he, undeluded among mortals, is freed from all sins.", "10.03", "10.03")]),
    ("From Me Alone",
     "Intellect, knowledge, truth, self-control, fame and infamy — all the states of beings arise from me alone.",
     [("Intellect, Knowledge, Non-Delusion", "Intellect, knowledge, non-delusion, forbearance, truth, self-restraint, calm, pleasure and pain, birth and death, fear and fearlessness — and non-violence, evenness, contentment, austerity, charity, fame and infamy: these manifold states of beings arise from me alone.", "10.04", "10.05"),
      ("The Seven Great Seers", "The seven great seers of old, and the four Manus, were born of my nature, sprung from my mind; from them come these creatures in the world.", "10.06", "10.06"),
      ("He Who Knows This Glory Is Joined to Me", "He who truly knows this glory and power of mine is joined to me by unshakeable yoga — of this there is no doubt.", "10.07", "10.07")]),
    ("I Am the Source of All",
     "I am the origin of all; the wise, knowing this, worship me — and to them I give the yoga of understanding.",
     [("I Am the Origin of All; the Wise Worship Me", "I am the origin of all; from me all proceeds. Knowing this, the wise worship me, filled with fervour.", "10.08", "10.08"),
      ("Speaking of Me, They Rejoice", "With minds fixed on me, their lives surrendered to me, enlightening one another and ever speaking of me, they are content and delighted.", "10.09", "10.09"),
      ("To Them I Give the Yoga of Understanding", "To those ever-steadfast ones who worship me with love, I give the yoga of understanding by which they come to me.", "10.10", "10.10"),
      ("I Destroy the Darkness With the Lamp of Knowledge", "Out of compassion for them, dwelling in their hearts, I destroy the darkness born of ignorance with the shining lamp of knowledge.", "10.11", "10.11")]),
    ("Arjuna's Praise",
     "You are the supreme Brahman, the supreme abode; the sages and Nārada affirm it, and now you tell me yourself.",
     [("You Are the Supreme Brahman", "You are the supreme Brahman, the supreme abode, the supreme purifier — the eternal divine Person, the primal God, unborn and all-pervading. So all the seers declare, and the divine sage Nārada, Asita, Devala and Vyāsa — and you yourself tell me so.", "10.12", "10.13"),
      ("Neither Gods Nor Demons Know Your Manifestation", "I hold all this that you say to me as true, O Keśava; neither the gods nor the demons know your manifestation.", "10.14", "10.14")]),
    ("How Shall I Know You?",
     "You alone know yourself by yourself; tell me the glories by which I may meditate on you — I am never sated with your nectar.",
     [("You Alone Know Yourself by Yourself", "You yourself know yourself by yourself, O supreme Person, source of beings, Lord of beings, God of gods, ruler of the world.", "10.15", "10.15"),
      ("Tell Me of Your Divine Glories", "Deign to tell me in full of your divine glories, by which you pervade and abide in these worlds.", "10.16", "10.16"),
      ("In What Forms Shall I Meditate on You?", "How shall I know you, O yogi, by constant meditation? In what forms are you to be thought of by me, O Lord?", "10.17", "10.17"),
      ("I Am Never Sated Hearing Your Nectar", "Tell me again in detail of your power and glory, O Janārdana; I am never sated with hearing your nectar-like words.", "10.18", "10.18")]),
    ("I Shall Declare",
     "Kṛṣṇa consents, but only in outline — for his glories have no end; and first: I am the Self seated in the heart of all beings.",
     [("Only the Chief of My Glories", "I shall declare to you my divine glories — but only the chief ones, O best of the Kurus, for there is no end to my extent.", "10.19", "10.19"),
      ("I Am the Self Seated in the Heart of All", "I am the Self, O Guḍākeśa, seated in the heart of all beings; I am the beginning, the middle and the end of all beings.", "10.20", "10.20")]),
    ("The Celestial Glories",
     "Among the Ādityas Viṣṇu, among lights the sun, among the Vedas the Sāma, among words the syllable Om.",
     [("Viṣṇu, the Sun, the Moon", "Among the Ādityas I am Viṣṇu; among lights the radiant sun; I am Marīci among the Maruts; among the stars I am the moon.", "10.21", "10.21"),
      ("Among the Senses I Am the Mind", "Among the Vedas I am the Sāma-veda; among the gods I am Indra; among the senses I am the mind; in beings I am consciousness.", "10.22", "10.22"),
      ("Śaṅkara, Kubera, Fire, Meru", "Among the Rudras I am Śaṅkara; among yakṣas and rākṣasas the lord of wealth; among the Vasus I am fire; among mountains, Meru.", "10.23", "10.23"),
      ("Bṛhaspati, Skanda, the Ocean", "Among household priests know me as the chief, Bṛhaspati; among generals I am Skanda; among waters I am the ocean.", "10.24", "10.24"),
      ("Among Words, the Syllable Om", "Among the great seers I am Bhṛgu; among words I am the single syllable Om; among sacrifices I am the sacrifice of silent repetition; among the immovable, the Himālaya.", "10.25", "10.25"),
      ("The Aśvattha, Nārada, Kapila", "Among all trees I am the aśvattha; among the divine seers, Nārada; among the gandharvas, Citraratha; among the perfected, the sage Kapila.", "10.26", "10.26")]),
    ("The Glories of Earth and Beings",
     "Among horses Uccaiḥśravas, among serpents Vāsuki, among letters the letter A — and I am all-devouring death.",
     [("Uccaiḥśravas, Airāvata, the King", "Among horses know me as Uccaiḥśravas, born of nectar; among lordly elephants, Airāvata; and among men, the king.", "10.27", "10.27"),
      ("The Thunderbolt, Kāmadhuk, Vāsuki", "Among weapons I am the thunderbolt; among cows I am Kāmadhuk; I am Kandarpa, the cause of offspring; among serpents I am Vāsuki.", "10.28", "10.28"),
      ("Ananta, Varuṇa, Aryaman, Yama", "Among the nāgas I am Ananta; among water-beings, Varuṇa; among the ancestors I am Aryaman; among the controllers, Yama.", "10.29", "10.29"),
      ("Prahlāda, Time, the Lion, Garuḍa", "Among the daityas I am Prahlāda; among reckoners I am time; among beasts I am the lion; among birds, Garuḍa.", "10.30", "10.30"),
      ("The Wind, Rāma, the Ganges", "Among purifiers I am the wind; among warriors I am Rāma; among fishes I am the makara; among rivers I am the Ganges.", "10.31", "10.31"),
      ("The Beginning, Middle and End of All", "Of creations I am the beginning, the middle and the end; among sciences I am the science of the Self; of those who debate, I am the reasoned conclusion.", "10.32", "10.32"),
      ("Among Letters, the Letter A", "Among letters I am the letter A; among compounds I am the dvandva; I alone am imperishable time; I am the ordainer facing every side.", "10.33", "10.33"),
      ("I Am All-Devouring Death", "I am all-devouring death, and the origin of all that is to be; among feminine powers I am fame, fortune, speech, memory, intelligence, constancy and forgiveness.", "10.34", "10.34")]),
    ("The Seed of All",
     "There is no end to my glories; whatever is glorious or powerful is a spark of my splendour — and I support this whole world with one fragment of myself.",
     [("The Bṛhat-sāma, the Gāyatrī, the Spring", "Among Sāman hymns I am the Bṛhat-sāman; among metres, the Gāyatrī; among months I am Mārgaśīrṣa; among seasons, the flowering spring.", "10.35", "10.35"),
      ("The Dice of Gamblers, the Splendour of the Splendid", "I am the gambling of the deceitful and the splendour of the splendid; I am victory, I am resolve, I am the goodness of the good.", "10.36", "10.36"),
      ("Among the Pāṇḍavas, Arjuna", "Among the Vṛṣṇis I am Vāsudeva; among the Pāṇḍavas, Arjuna; among sages I am Vyāsa; among poets, the poet Uśanā.", "10.37", "10.37"),
      ("The Silence of Secrets", "I am the rod of those who chastise, the statesmanship of those who seek victory; I am the silence of secrets and the knowledge of the knowing.", "10.38", "10.38"),
      ("Whatever Is the Seed of All Beings", "And whatever is the seed of all beings, that also am I; there is no being, moving or unmoving, that can exist without me.", "10.39", "10.39"),
      ("There Is No End to My Glories", "There is no end to my divine glories; what I have declared is but a brief statement of the extent of my glory.", "10.40", "10.40"),
      ("Whatever Is Glorious Is a Spark of My Splendour", "Whatever being is glorious, prosperous or powerful — know that to have sprung from a fragment of my splendour.", "10.41", "10.41"),
      ("I Support This Whole World With One Fragment", "But what need have you to know all this in detail, O Arjuna? I stand supporting this entire world with a single fragment of myself.", "10.42", "10.42")]),
]

CH10_TRANSLATIONS = {
1: ("The Blessed Lord said: Hear again, O mighty-armed one, my supreme words, which I speak to you who are dear, wishing your good.",
    "Kṛṣṇa said: “Listen once more, mighty-armed Arjuna, to my highest teaching — which I give you out of love, for your welfare.”"),
2: ("Neither the hosts of gods nor the great seers know my origin; for I am the beginning of the gods and the great seers in every way.",
    "“Neither the gods nor the great sages know where I come from — I am the very source of them all.”"),
3: ("He who knows me as unborn, without beginning, the great Lord of the world — undeluded among mortals, he is freed from all sins.",
    "“One who knows me as unborn, beginningless, the Lord of all worlds — he is no longer confused, and all his sins fall away.”"),
4: ("Intellect, knowledge, freedom from delusion, forbearance, truth, self-control, calm — pleasure, pain, birth, death, fear and fearlessness,",
    "“Understanding, wisdom, clarity, patience, truth, self-mastery, peace — joy, sorrow, coming-to-be, ceasing, fear, and courage,”"),
5: ("non-violence, equanimity, contentment, austerity, generosity, fame and infamy — these various states of beings arise from me alone.",
    "“— harmlessness, even-mindedness, contentment, tapas, giving, renown and disgrace — all these qualities of beings come from me alone.”"),
6: ("The seven great seers, the four ancient Manus, born of my mind — from them come the beings of this world.",
    "“The seven ancient sages and the four Manus, born of my thought — from them all the creatures of this world descend.”"),
7: ("He who knows in truth this glory and power of mine is united to me by unwavering yoga — of this there is no doubt.",
    "“Whoever truly knows my glories and my power is joined to me with unshakable yoga — of this there is no doubt.”"),
8: ("I am the source of all; everything proceeds from me. Knowing this, the wise worship me, filled with devotion.",
    "“I am the origin of everything; all flows from me. The wise, knowing this, worship me with love.”"),
9: ("Their thoughts on me, their lives given to me, enlightening one another, always speaking of me — they are content and rejoice.",
    "“With minds on me, lives devoted to me, teaching each other and always talking of me — they are satisfied and delighted.”"),
10: ("To them, ever devoted, worshipping me with love, I give the yoga of discernment, by which they come to me.",
    "“To those ever united, worshipping me with devotion, I give the wisdom-yoga by which they reach me.”"),
11: ("Out of compassion for them, dwelling in their hearts, I destroy the darkness born of ignorance with the shining lamp of knowledge.",
    "“Out of compassion, dwelling within them, I dispel their darkness of ignorance with the radiant lamp of wisdom.”"),
12: ("Arjuna said: You are the supreme Brahman, the supreme light, the supreme purifier; the eternal divine Person, the primal God, unborn and all-pervading.",
    "Arjuna says: “You are the supreme Brahman, the highest abode, the purest; the eternal divine Person, the first God, unborn and everywhere.”"),
13: ("Thus the seers call you — Nārada the divine sage, Asita, Devala, Vyāsa — and you yourself tell me.",
    "“All the sages say so — Nārada, Asita, Devala, Vyāsa — and you yourself confirm it to me.”"),
14: ("I hold all this you tell me as true, Keśava; indeed, neither gods nor demons, O Lord, know your manifestation.",
    "“I believe everything you say, Keśava. Neither gods nor demons can know how you appear, O Lord.”"),
15: ("You yourself know yourself by yourself, O supreme Person — O source of beings, Lord of beings, God of gods, Lord of the world!",
    "“Only you know yourself, O highest Person — creator of all, God of gods, Lord of the universe!”"),
16: ("Tell me without omission your divine glories, by which you abide, pervading these worlds.",
    "“Please tell me fully your divine glories — through which you stand pervading all these worlds.”"),
17: ("How shall I know you, O yogi, contemplating you always? And in what states are you to be thought of, O Lord?",
    "“How can I know you, thinking of you always? In which forms, O Lord, should I meditate on you?”"),
18: ("Tell me again, in detail, your yoga and your glory, O Janārdana; I am never satiated with hearing your nectar.",
    "“Tell me again at length of your power and glories, Janārdana — I never tire of drinking in this nectar.”"),
19: ("The Blessed Lord said: Yes, I shall declare to you my divine glories — chiefly, O best of the Kurus; there is no end to my extent.",
    "Kṛṣṇa said: “I will tell you of my divine glories — the chief among them, Arjuna; for my extent has no end.”"),
20: ("I am the Self, O Guḍākeśa, dwelling in the hearts of all beings; I am the beginning, the middle, and the end of all beings.",
    "“I am the Self seated in the hearts of all beings; I am their beginning, middle, and end.”"),
21: ("Among the Ādityas I am Viṣṇu; among the lights, the radiant sun; I am Marīci among the winds; I am the moon among the stars.",
    "“Of the Ādityas I am Viṣṇu; of lights, the blazing sun; of winds, Marīci; of stars, the moon.”"),
22: ("Among the Vedas I am the Sāma-veda; among the gods I am Indra; among the senses I am the mind; among beings I am consciousness.",
    "“Of the Vedas I am the Sāma; of gods, Indra; of the senses, the mind; of beings, consciousness.”"),
23: ("Among the Rudras I am Śaṅkara; among the yakṣas and rākṣasas, the lord of wealth; among the Vasus I am fire; among mountains, Meru.",
    "“Of the Rudras I am Śiva; of the yakṣas and demons, Kubera; of the Vasus, fire; of mountains, Meru.”"),
24: ("Among priests, O Pārtha, know me as the chief, Bṛhaspati; among generals I am Skanda; among waters I am the ocean.",
    "“Know me as Bṛhaspati among priests, Skanda among commanders, the ocean among bodies of water.”"),
25: ("Among the great seers I am Bhṛgu; among words I am the single syllable Om; among sacrifices I am the japa-sacrifice; among the immovable I am the Himālaya.",
    "“Of the great sages I am Bhṛgu; of speech, the sacred Om; of sacrifices, silent repetition; of the immovable, the Himalaya.”"),
26: ("Among all trees I am the aśvattha; among the divine sages, Nārada; among the gandharvas, Citraratha; among the perfected, the sage Kapila.",
    "“Of trees I am the sacred fig; of divine sages, Nārada; of celestial musicians, Citraratha; of the perfected, Kapila.”"),
27: ("Among horses know me as Uccaiḥśravas, born of nectar; among lordly elephants, Airāvata; among men, the king.",
    "“Among horses I am Uccaiḥśravas, born of the nectar; among elephants, Airāvata; among men, their king.”"),
28: ("Among weapons I am the thunderbolt; among cows I am Kāmadhuk; I am the lord of love among procreators; among serpents, Vāsuki.",
    "“Of weapons I am the thunderbolt; of cows, the wish-fulfilling cow; of the lustful, Kāma; of serpents, Vāsuki.”"),
29: ("I am the infinite among serpents; Varuṇa among the waters; among the ancestors I am Aryaman; among rulers, Yama.",
    "“Of serpents I am the endless Ananta; of sea-creatures, Varuṇa; of ancestors, Aryaman; of punishers, Yama.”"),
30: ("Among the demons I am Prahlāda; among the calculators, time; among beasts I am the lion; among birds, Garuḍa.",
    "“Of the demons I am Prahlāda; of reckoners, time; of beasts, the lion; of birds, Garuḍa.”"),
31: ("Among purifiers I am the wind; among warriors I am Rāma; among fishes I am the makara; among streams I am the Ganges.",
    "“Of purifiers I am the wind; of weapon-bearers, Rāma; of fish, the makara; of rivers, the Ganges.”"),
32: ("Of creations I am the beginning, the middle, and also the end, O Arjuna; among the sciences I am the science of the Self; among debaters, the argument.",
    "“Of all creations I am the beginning, middle, and end; of sciences, the science of the Self; of debates, sound reasoning.”"),
33: ("Among letters I am the letter A; among compounds the dvandva; I am indeed inexhaustible time; I am the ordainer facing everywhere.",
    "“Of letters I am the A; of compounds, the dvandva; I am endless time; I am the all-facing creator.”"),
34: ("I am all-devouring death and the birth of all that will be; among women I am fame, fortune, speech, memory, wisdom, constancy and forbearance.",
    "“I am death that carries all away, and the source of all that comes to be; among women, fame, grace, eloquence, memory, wisdom, steadiness, and patience.”"),
35: ("Among the Sāma-chants I am the Bṛhat-sāma; among metres the Gāyatrī; among months I am Mārgaśīrṣa; among seasons the spring.",
    "“Of the Sāma hymns I am the Bṛhat-sāma; of metres, the Gāyatrī; of months, Mārgaśīrṣa; of seasons, flowering spring.”"),
36: ("I am the dice of the gamblers; I am the splendour of the splendid; I am victory, I am determination; I am the goodness of the good.",
    "“I am the craft of the gambler, the glory of the glorious; I am victory and resolve; I am the virtue of the virtuous.”"),
37: ("Among the Vṛṣṇis I am Vāsudeva; among the Pāṇḍavas, Arjuna; among the sages I am Vyāsa; among the poets, Uśanā the poet.",
    "“Of the Vṛṣṇis I am Vāsudeva; of the Pāṇḍavas, Arjuna; of sages, Vyāsa; of poets, Uśanas.”"),
38: ("I am the rod of the punishers; among those seeking victory I am policy; I am the silence of the secret; among the knowing I am knowledge.",
    "“I am the sceptre of rulers and the statesmanship of the victorious; I am the silence of mysteries; of the wise, wisdom.”"),
39: ("And whatever is the seed of all beings, that I am, O Arjuna; no being, moving or unmoving, exists without me.",
    "“Whatever seed gives rise to all beings — that is I. Nothing moving or still exists apart from me.”"),
40: ("There is no end to my divine glories, O scorcher of foes; this is but a summary declared by me of the extent of my glory.",
    "“My divine glories have no end, Arjuna — this is only a brief statement of their vast extent.”"),
41: ("Whatever being is glorious, radiant or powerful — know that to be born of a portion of my splendour.",
    "“Whatever is splendid, shining, or mighty — know it springs from a spark of my glory.”"),
42: ("But what need, Arjuna, of this detailed knowledge? I stand supporting this whole world with one part of myself.",
    "“But why know all this in detail, Arjuna? With a single part of myself I sustain this entire universe.”"),
}
