# -*- coding: utf-8 -*-
"""gita_data5.py — Chapter 5 (Karma-Sannyāsa Yoga) themes and translations.
Aligned to the Śaṅkara-bhāṣya readings."""

CH5_THEMES = [
    ("Arjuna asks: renounce or act?",
     "Arjuna asks which is superior — renunciation of action or the yoga of action; Kṛṣṇa answers that both lead to the good, but yoga excels.",
     [("Arjuna asks: renounce or act?", "You praise renunciation of actions, and also karma-yoga; tell me for certain which of the two is better.", "5.01", "5.01"),
      ("Both lead to the good — But Yoga excels", "Both renunciation and karma-yoga lead to the highest good; of the two, karma-yoga is superior to the renunciation of action.", "5.02", "5.02")]),
    ("Sāṅkhya and Yoga Are One",
     "Only children speak of the two paths as different; whoever is rightly established in one attains the fruit of both.",
     [("He who neither hates nor longs is free", "Know him as an eternal renouncer who neither hates nor desires; free from the pairs of opposites, he is easily released from bondage.", "5.03", "5.03"),
      ("Only children call the two paths different", "The childish, not the wise, speak of sāṅkhya and yoga as distinct; one rightly established in either gains the fruit of both. The state reached by the sāṅkhyas is reached by the yogis too — he who sees them as one truly sees.", "5.04", "5.04"),
      ("The same goal", "Knowledge and action lead to the same goal. Whoever sees them as one sees truly.", "5.05", "5.05"),
      ("Renunciation is hard without Yoga", "But renunciation is hard to attain without yoga; the sage joined to yoga reaches Brahman before long.", "5.06", "5.06")]),
    ("Though Acting, He Is Not Stained",
     "The pure-souled yogi of action knows 'I do nothing at all', and sin does not cling to him — as water does not cling to a lotus leaf.",
     [("The Self of all beings", "Joined to yoga, pure in soul, self-conquered and sense-conquered, whose Self is the Self of all beings — though acting, he is not stained.", "5.07", "5.07"),
      ("“I do nothing at all”", "'I do nothing at all' — so thinks the knower of truth while seeing, hearing, touching, smelling, eating, moving, sleeping, breathing, speaking, releasing, grasping, opening and closing the eyes — holding that the senses move among their objects.", "5.08", "5.08"),
      ("Offering all to Brahman", "Speaking, giving, taking, opening and closing the eyes — knowing it is only the senses meeting their objects.", "5.09", "5.09"),
      ("The lotus leaf", "He who acts offering all actions to Brahman, abandoning attachment, is untouched by sin as a lotus leaf by water.", "5.10", "5.10"),
      ("Action for self-purification", "With body, mind, intellect, or the senses alone, yogis act — abandoning attachment — for the purification of the self.", "5.11", "5.11"),
      ("Peace through giving up the fruit", "The steadfast, abandoning the fruit of action, attains lasting peace; the unsteady, attached to fruit through desire, is bound.", "5.12", "5.12")]),
    ("The City of Nine Gates",
     "Renouncing all actions by the mind, the embodied one rests happily in the city of nine gates — neither acting nor causing action.",
     [("The city of nine gates", "Renouncing all actions by the mind, the embodied one rests happily in the city of nine gates — neither acting at all nor causing action.", "5.13", "5.13"),
      ("The Lord creates no doership", "The Lord creates neither agency nor actions for the world, nor the union of action with its fruit — it is nature that operates.", "5.14", "5.14"),
      ("Nor does he take on sin", "The all-pervading takes on neither the sin nor the merit of any; knowledge is veiled by ignorance, and by that beings are deluded.", "5.15", "5.15"),
      ("Knowledge reveals like the sun", "But for those whose ignorance is destroyed by knowledge of the Self, that knowledge reveals the Supreme like the sun.", "5.16", "5.16")]),
    ("Equal vision: the sage sees the same in all",
     "With intellect, mind and faith in That, the sage sees the same in a brāhmaṇa, a cow, an elephant, a dog and an outcaste.",
     [("Mind, self and refuge all in That", "With intellect in That, self in That, established in That, holding That as the supreme goal, they go whence there is no return, their sins dispelled by knowledge.", "5.17", "5.17"),
      ("The sage sees the same in all", "The wise see the same in a learned brāhmaṇa, a cow, an elephant, a dog and an outcaste. Even here, rebirth is conquered by those whose mind rests in evenness; Brahman is flawless and even, therefore they are established in Brahman.", "5.18", "5.18"),
      ("Already conquered the world", "Those whose minds are poised have already conquered this world — for Brahman is spotless and even, and they are established in Brahman.", "5.19", "5.19"),
      ("He neither rejoices nor recoils", "Neither rejoicing at the pleasant nor recoiling at the unpleasant, of steady understanding and undeluded, the knower of Brahman rests in Brahman.", "5.20", "5.20"),
      ("The joy within", "Unattached to outer contacts, he finds the joy that is in the Self; united with Brahman by yoga, he enjoys imperishable happiness.", "5.21", "5.21")]),
    ("Pleasures Are Wombs of Pain",
     "Contact-born pleasures have a beginning and an end and are wombs of pain; the wise take no delight in them.",
     [("Contacts are wombs of pain", "Pleasures born of contact are wombs of pain, having beginning and end; the wise man does not delight in them.", "5.22", "5.22"),
      ("He who withstands desire and anger", "He who can withstand here, before liberation from the body, the impulse of desire and anger — he is a yogi, he is happy.", "5.23", "5.23"),
      ("Whose joy is within", "He whose joy is within, whose delight is within, whose light is within — that yogi becomes Brahman and attains Brahman-nirvāṇa.", "5.24", "5.24"),
      ("Sages of cut doubt reach Brahman-nirvāṇa", "Seers whose sins are destroyed, whose doubts are cut, self-controlled, delighting in the welfare of all beings, attain Brahman-nirvāṇa. For those freed from desire and anger, self-controlled and knowing the Self, Brahman-nirvāṇa is near.", "5.25", "5.25"),
      ("Free from desire and anger", "To those free of desire and anger, masters of their thoughts, who know the Self — liberation in Brahman is present all around.", "5.26", "5.26")]),
    ("The yogi who meditates finds peace",
     "Shutting out external contacts, gaze between the brows, breath balanced — the sage who knows me as the friend of all beings attains peace.",
     [("Breath, gaze, and stillness", "Shutting out external contacts, the gaze fixed between the brows, balancing the in-breath and out-breath within the nostrils —", "5.27", "5.27"),
      ("Free of craving, fear and anger", "— the sage, self-controlled, free of craving, fear and anger, devoted to freedom — he is forever liberated.", "5.28", "5.28"),
      ("Knowing me, the friend of all beings, he attains peace", "Knowing me as the enjoyer of sacrifices and austerities, the great Lord of all worlds, the friend of all beings — he attains peace.", "5.29", "5.29")]),
]

CH5_TRANSLATIONS = {
1: ("Arjuna said: You praise renunciation of actions, O Kṛṣṇa, and also the yoga of action; tell me for certain which one of the two is better.",
    "Arjuna asks: “You praise both giving up action and performing it as yoga, Kṛṣṇa — tell me plainly which of the two is better.”"),
2: ("The Blessed Lord said: Both renunciation and karma-yoga lead to the supreme good; but of the two, karma-yoga is superior to the renunciation of action.",
    "Kṛṣṇa said: “Both paths lead to liberation, but of the two, the yoga of selfless action is the better.”"),
3: ("He is to be known as ever-renouncing who neither hates nor longs; free from the pairs of opposites, O mighty-armed one, he is easily released from bondage.",
    "“The real renouncer is one free from likes and dislikes — beyond all pairs of opposites, he slips easily out of bondage.”"),
4: ("The childish, not the wise, speak of sāṅkhya and yoga as different; one who is rightly established in even one of them attains the fruit of both.",
    "“Only the immature think knowledge and action are separate paths. Truly grounded in either, you reap the fruit of both.”"),
5: ("The state attained by the sāṅkhyas is also reached by the yogis; he who sees sāṅkhya and yoga as one — he truly sees.",
    "“Knowledge and action lead to the same goal. Whoever sees them as one sees truly.”"),
6: ("But renunciation, O mighty-armed one, is hard to attain without yoga; the sage endowed with yoga reaches Brahman before long.",
    "“Giving up action without inner yoga is very hard; but the yogi of action attains Brahman quickly.”"),
7: ("Devoted to karma-yoga, of pure soul, self-conquered, senses conquered, the Self of all beings — though acting, he is not stained.",
    "“The karma-yogi, pure and self-controlled, seeing himself in all beings, acts without ever being tainted.”"),
8: ("“I do nothing at all” — thus should the knower of truth think, while seeing, hearing, touching, smelling, eating, moving, sleeping, breathing,",
    "“The wise one thinks 'I do nothing' — even while seeing, hearing, touching, tasting, walking, sleeping, breathing,”"),
9: ("speaking, giving up, holding, opening and closing the eyes — holding that the senses move among the objects of the senses.",
    "“talking, giving, taking, opening and closing the eyes — knowing it is only the senses meeting their objects.”"),
10: ("He who acts, offering all actions to Brahman and abandoning attachment, is not stained by sin, just as a lotus leaf is not wetted by water.",
    "“Offer every action to Brahman and drop attachment — sin cannot touch you, any more than water wets a lotus leaf.”"),
11: ("The yogis perform action by body, mind, intellect, or even by the senses alone, having abandoned attachment, for the purification of the self.",
    "“Yogis work with body, mind, or senses, unattached — only to purify themselves.”"),
12: ("The one established in yoga, giving up the fruit of action, attains lasting peace; the one not established, impelled by desire, attached to the fruit, becomes bound.",
    "“The yogi who lets go of results finds steady peace; the one clinging to results, ruled by craving, stays bound.”"),
13: ("Having mentally renounced all actions, the self-controlled embodied one dwells happily in the city of nine gates, neither acting nor causing others to act.",
    "“The self-mastered soul dwells happily in the body — its nine-gated city — having surrendered all actions in the mind, doing nothing and causing nothing.”"),
14: ("The Lord neither creates agency nor actions for the world, nor the connection of action with its fruit; it is nature that acts.",
    "“The Lord creates no doership, no action, no results — nature alone does everything.”"),
15: ("The all-pervading One neither accepts the sin nor the merit of anyone; knowledge is enveloped by ignorance, and thereby beings are deluded.",
    "“The Lord accepts no one's sin or merit. Ignorance veils knowledge, and that is why creatures are confused.”"),
16: ("But for those whose ignorance is destroyed by the knowledge of the Self, that knowledge shines forth like the sun, revealing the Supreme.",
    "“When ignorance is destroyed by Self-knowledge, wisdom blazes like the sun and reveals the Supreme.”"),
17: ("With their intellect in that, their self in that, their refuge in that, their goal that — they go without return, their sins cleansed by knowledge.",
    "“Those whose whole being rests in Brahman, cleansed by wisdom, never return — they are freed forever.”"),
18: ("The wise look equally on a brāhmaṇa endowed with learning and humility, a cow, an elephant, a dog, and even an outcaste.",
    "“With equal vision the wise see a scholar, a cow, an elephant, a dog — and an outcaste — all alike.”"),
19: ("Here itself the world of birth and death is conquered by those whose minds rest in equanimity; Brahman is flawless and equal; therefore they are established in Brahman.",
    "“Those whose minds are poised have already conquered this world — for Brahman is spotless and even, and they dwell in it.”"),
20: ("He does not rejoice on obtaining what is dear, nor is he perturbed on obtaining what is not dear; with steady intellect, undeluded, the knower of Brahman abides in Brahman.",
    "“Pleasure doesn't elate him, pain doesn't upset him — the knower of Brahman stands firm in Brahman, unshaken.”"),
21: ("With the self unattached to external contacts, he finds the happiness that is in the Self; joined with the yoga of Brahman, he enjoys bliss that is imperishable.",
    "“Not clinging to outer pleasures, he discovers joy within — and united with Brahman, he tastes undying bliss.”"),
22: ("Indeed, the pleasures born of contact with the senses are only wombs of sorrow; they have a beginning and an end, O son of Kuntī — the wise do not rejoice in them.",
    "“Sense-born pleasures only breed suffering — they come and go. The wise take no delight in them.”"),
23: ("He who, even here, before the release of the body, is able to endure the impulse born of desire and anger — he is yoked in yoga, he is a happy man.",
    "“Whoever can withstand the urge of desire and anger, right here and now, is a true yogi — a happy soul.”"),
24: ("He who is happy within, who delights within, who is illumined within — that yogi, become Brahman, attains to Brahman-nirvāṇa.",
    "“One whose joy, delight, and light are all within — that yogi, already one with Brahman, reaches liberation in Brahman.”"),
25: ("The seers whose sins are destroyed, whose doubts are cut, whose selves are controlled, who delight in the welfare of all beings — they attain Brahman-nirvāṇa.",
    "“Sages cleansed of sin, free of doubt, self-mastered, devoted to the good of all — they reach liberation in Brahman.”"),
26: ("For the ascetics free from desire and anger, whose thoughts are controlled, who know the Self — Brahman-nirvāṇa is present all around.",
    "“To those free of desire and anger, masters of their thoughts, who know the Self — liberation in Brahman is near at hand.”"),
27: ("Turning the sense-objects outward, fixing the vision between the eyebrows, making the out-breath and in-breath flow evenly within the nostrils —",
    "“Withdrawing from outer objects, gaze set between the brows, breath balanced and flowing evenly —”"),
28: ("— with senses, mind and intellect controlled, the sage intent on liberation, free from desire, fear and anger — he is ever free.",
    "“— the sage, self-controlled, free of craving, fear and anger, devoted to freedom — he is forever liberated.”"),
29: ("Knowing me as the enjoyer of sacrifices and austerities, the great Lord of all the worlds, the friend of all beings — he attains peace.",
    "“Know me as the receiver of all offerings, the Lord of all worlds, the friend of every being — and you will find peace.”"),
}
