# -*- coding: utf-8 -*-
"""gloss_ne.py — Nepali glosses for pada-chheda words (keyed by IAST).
Entries not present fall back to the English gloss."""

GLOSS_NE = {
"a": "बिना",
"abhaktāya": "अभक्तलाई",
"abhavat": "भयो",
"abhayam": "अभय",
"abhibhavati": "दबाउँछ",
"abhibhavāt": "उदयबाट",
"abhibhūya": "दबाएर",
"abhidhāsyati": "सिकाउनेछ",
"abhidhīyate": "भनिन्छ",
"abhihitā": "भनिएको",
"abhijanavān": "उच्च कुलको",
"abhijānanti": "जान्दछन्",
"abhijānāti": "जान्दछ",
"abhijātasya": "जन्मेकाको",
"abhijātaḥ": "जन्मेको",
"abhijāyate": "जन्मिन्छ",
"abhikrama": "प्रयास",
"abhimukhāḥ": "तिर",
"abhinandati": "रम्छ",
"abhipravṛttaḥ": "लागेको",
"abhirakṣantu": "रक्षा गरून्",
"abhirakṣitam": "रक्षा गरिएको",
"abhirataḥ": "रम्ने",
"abhisandhāya": "खोजेर",
"abhitaḥ": "चारैतिर",
"abhivijvalanti": "दनदनी बल्छन्",
"abhram": "बादल",
"abhyadhikaḥ": "अझ ठूलो",
"abhyahanyanta": "प्रहार गरिए",
"abhyantara": "भित्र",
"abhyarcya": "पूजा गरेर",
"abhyasūyakāḥ": "दोष देख्नेहरू",
"abhyasūyantaḥ": "दोष देख्नेहरू",
"abhyasūyati": "दोष देख्छ",
"abhyutthānam": "उदय",
"abhyāsayogayuktena": "अभ्यासयोगले युक्त",
"abhyāsayogena": "अभ्यासयोगद्वारा",
"abhyāse": "अभ्यासमा",
"abhyāsena": "अभ्यासद्वारा",
"abhyāsāt": "अभ्यासबाट",
"abhāvayataḥ": "भावना नभएकोको",
"abhāvaḥ": "अभाव",
"abhāṣata": "बोले",
"abravīt": "भने",
"abuddhayaḥ": "अबुद्धिहरू",
"acala": "अचल",
"acalam": "अचल",
"acalaḥ": "अचल",
"acalena": "अचल",
"acalā": "अचल",
"acalām": "अचल",
"acaram": "अचर",
"acchedyaḥ": "नकाटिने",
"acetasaḥ": "अचेतन",
"acintyam": "अचिन्त्य",
"acintyarūpam": "अचिन्त्य रूप भएको",
"acintyaḥ": "अचिन्त्य",
"acireṇa": "छिट्टै",
"acyuta": "हे अच्युत",
"acāpalam": "स्थिरता",
"adakṣiṇam": "दक्षिणा बिनाको",
"adambhitvam": "अदम्भित्व",
"adbhutam": "अद्भुत",
"adeśakāle": "गलत ठाउँ र समयमा",
"adhamām": "नीचतममा",
"adharma": "अधर्म",
"adharmam": "अधर्म",
"adharmasya": "अधर्मको",
"adharmaḥ": "अधर्म",
"adhaḥ": "तल",
"adhibhūta": "अधिभूत",
"adhibhūtam": "अधिभूत",
"adhidaivam": "अधिदैव",
"adhidaivatam": "अधिदैवत",
"adhigacchati": "प्राप्त गर्दछ",
"adhikam": "अधिक",
"adhikataraḥ": "अझ ठूलो",
"adhikaḥ": "अधिक",
"adhikāraḥ": "अधिकार",
"adhiyajñam": "अधियज्ञ",
"adhiyajñaḥ": "अधियज्ञ",
"adhiṣṭhānam": "आधार",
"adhiṣṭhāya": "अधिकार गरेर",
"adhruvam": "अध्रुव",
"adhyakṣeṇa": "निरीक्षणद्वारा",
"adhyeṣyate": "अध्ययन गर्नेछ",
"adhyātma": "अध्यात्म",
"adhyātmajñānanityatvam": "आत्मज्ञानमा निरन्तरता",
"adhyātmam": "अध्यात्म",
"adhyātmanityāḥ": "अध्यात्ममा नित्य रहने",
"adhyātmavidyā": "अध्यात्मविद्या",
"adrohaḥ": "द्रोहरहितता",
"adveṣṭā": "द्वेष नगर्ने",
"adya": "आज",
"adāhyaḥ": "नबल्ने",
"adṛṣṭapūrvam": "पहिले नदेखिएको",
"adṛṣṭapūrvāṇi": "पहिले नदेखिएका",
"agatāsūn": "जिउँदाहरूलाई",
"agha": "पापको",
"agham": "पाप",
"agnau": "अग्निमा",
"agni": "अग्निले",
"agniḥ": "अग्नि",
"agniṣu": "अग्निहरूमा",
"agre": "पहिले",
"ahaitukam": "बिना कारण",
"aham": "म",
"aharāgame": "दिनको आगमनमा",
"ahatvā": "नमारी",
"ahaḥ": "दिन",
"ahaṁkāram": "अहंकार",
"ahaṁkārāt": "अहंकारबाट",
"ahaṅkāra": "अहंकारले",
"ahaṅkāram": "अहंकार",
"ahaṅkāraḥ": "अहंकार",
"ahitāḥ": "शत्रुहरू",
"ahiṁsā": "अहिंसा",
"aho": "हाय",
"ahorātravidaḥ": "दिन-रातका ज्ञाता",
"airāvatam": "ऐरावत",
"aiśvaram": "दिव्य",
"aiśvarya": "ऐश्वर्य",
"ajam": "अजन्मा",
"ajasram": "निरन्तर",
"ajayau": "पराजयमा",
"ajaḥ": "अजन्मा",
"ajina": "मृगछाला",
"ajñaḥ": "अज्ञानी",
"ajñāna": "अज्ञान",
"ajñānajam": "अज्ञानजन्य",
"ajñānam": "अज्ञान",
"ajñānasaṁmohaḥ": "अज्ञानको मोह",
"ajñānavimohitāḥ": "अज्ञानले मोहित",
"ajñānena": "अज्ञानले",
"ajñānām": "अज्ञानीहरूका",
"ajānantaḥ": "नजान्ने",
"ajānatā": "नजान्नेले",
"akalmaṣam": "निष्पाप",
"akarma": "अकर्म",
"akarmakṛt": "अकर्मा",
"akarmaṇaḥ": "अकर्मको",
"akarmaṇi": "अकर्ममा",
"akartāram": "अकर्ता",
"akhilam": "सम्पूर्ण",
"akledyaḥ": "नभिज्ने",
"akriyaḥ": "क्रियारहित",
"akrodhaḥ": "क्रोधरहितता",
"akurvata": "गरे",
"akuśalam": "अप्रिय",
"akāraḥ": "अकार",
"akāryam": "नगर्नुपर्ने",
"akīrtikaram": "अपकीर्ति ल्याउने",
"akīrtim": "अपकीर्ति",
"akīrtiḥ": "अपकीर्ति",
"akṛtabuddhitvāt": "अपूर्ण समझले",
"akṛtena": "नगरिएकोबाट",
"akṛtsna": "अपूर्ण",
"akṛtātmānaḥ": "असंस्कृत आत्माहरू",
"akṣara": "अक्षरबाट",
"akṣaram": "अक्षर",
"akṣaraḥ": "अक्षर",
"akṣarāt": "अक्षरभन्दा",
"akṣarāṇām": "अक्षरहरूका",
"akṣayam": "अविनाशी",
"akṣayaḥ": "अक्षय",
"akṣiśiromukham": "आँखा, शिर र मुख भएको",
"alasaḥ": "अल्छी",
"aloluptvam": "अस्पृहता",
"alpabuddhayaḥ": "अल्पबुद्धि भएका",
"alpam": "तुच्छ",
"alpamedhasām": "अल्पबुद्धिहरूका",
"alābhau": "अलाभमा",
"amalān": "निर्मल",
"amarṣa": "क्रोध",
"ambhasi": "पानीमा",
"ambhasā": "पानीले",
"ambuvegāḥ": "बग्ने जलधाराहरू",
"amedhyam": "अशुद्ध",
"amitavikramaḥ": "अमित विक्रम भएको",
"amla": "अमिलो",
"amutra": "परलोकमा",
"amānitvam": "नम्रता",
"amī": "यी",
"amūḍhāḥ": "अमोहितहरू",
"amṛta": "अमृत",
"amṛtam": "अमृत",
"amṛtasya": "अमृतको",
"amṛtatvāya": "अमरत्वका निम्ति",
"amṛtodbhavam": "अमृतबाट जन्मेको",
"amṛtopamam": "अमृतजस्तो",
"anabhisandhāya": "नखोजेर",
"anabhisnehaḥ": "स्नेहरहित",
"anabhiṣvaṅgaḥ": "नटाँसिनु",
"anagha": "हे निष्पाप",
"anahaṁvādī": "अहंकाररहित",
"anahaṅkāraḥ": "अहंकाररहितता",
"analaḥ": "आगो",
"analena": "आगोले",
"ananta": "हे अनन्त",
"anantabāhum": "अनन्त बाहु भएको",
"anantam": "अनन्त",
"anantaram": "तुरुन्तै",
"anantarūpa": "हे अनन्त रूप",
"anantarūpam": "अनन्त रूप भएको",
"anantavijayam": "अनन्तविजय",
"anantavīrya": "हे अनन्त शक्ति भएका",
"anantavīryam": "अनन्त शक्ति भएको",
"anantaḥ": "अनन्त",
"anantāḥ": "अनन्त",
"ananyabhāk": "एकनिष्ठ भक्त",
"ananyacetāḥ": "अनन्य चित्त भएको",
"ananyamanasaḥ": "अनन्य मन भएको",
"ananyayogena": "अनन्य योगद्वारा",
"ananyayā": "एकनिष्ठ",
"ananyena": "अनन्य",
"ananyāḥ": "अनन्य",
"anapekṣaḥ": "निःस्पृह",
"anapekṣya": "नहेरी",
"anasūyantaḥ": "दोष नदेख्नेहरू",
"anasūyave": "दोष नदेख्नेलाई",
"anasūyaḥ": "ईर्ष्यारहित",
"anavalokayan": "नहेर्दै",
"anavāptam": "नप्राप्त",
"anaśnataḥ": "नखानेको",
"aneka": "धेरै",
"anekabāhūdaravaktranetram": "धेरै बाहु, पेट, मुख र आँखा भएको",
"anekacittavibhrāntāḥ": "धेरै विचारले भ्रमित",
"anekadhā": "धेरै तरिकाले",
"anekadivyābharaṇam": "धेरै दिव्य आभूषण भएको",
"anekavaktranayanam": "धेरै मुख र आँखा भएको",
"anekavarṇam": "अनेक रङ्गको",
"anekādbhutadarśanam": "धेरै आश्चर्यमय दृश्य भएको",
"anena": "यसद्वारा",
"anicchan": "नचाहँदै",
"aniketaḥ": "घरबारविहीन",
"anirdeśyam": "अवर्णनीय",
"anirviṇṇa": "निरुत्साहित नभएको",
"anityam": "अनित्य",
"anityāḥ": "अनित्य",
"aniṣṭam": "अप्रिय",
"anna": "अन्नको",
"annam": "अन्न",
"annāt": "अन्नबाट",
"antagatam": "अन्त्य भएको",
"antakāle": "अन्त्यकालमा",
"antam": "अन्त्य",
"antaram": "भेद",
"antare": "बीचमा",
"antarjyotiḥ": "भित्रै प्रकाशित",
"antarārāmaḥ": "भित्रै रम्ने",
"antarātmanā": "अन्तरात्माले",
"antavantaḥ": "अन्त्य भएका",
"antavat": "अन्त्य भएको",
"antaḥ": "अन्त्य",
"antaḥsthāni": "भित्र रहने",
"antaḥsukhaḥ": "भित्रै सुखी",
"antaḥśarīrastham": "शरीरभित्र रहने",
"ante": "अन्त्यमा",
"antike": "नजिक",
"anubandham": "परिणाम",
"anubandhe": "अन्त्यमा",
"anucintayan": "चिन्तन गर्दै",
"anudvegakaram": "दुःख नदिने",
"anudvigna": "अविचलित",
"anugrahāya": "कृपाका निम्ति",
"anukampārtham": "करुणाका निम्ति",
"anumantā": "अनुमोदनकर्ता",
"anupakāriṇe": "बदला नसक्नेलाई",
"anupaśyanti": "देख्छन्",
"anupaśyati": "देख्छ",
"anupaśyāmi": "देख्छु",
"anuprapannāḥ": "अनुसरण गर्ने",
"anurajyate": "रम्छ",
"anusantatāni": "तल फैलिएका",
"anusmara": "सम्झ",
"anusmaran": "सम्झँदै",
"anusmaret": "सम्झनुपर्छ",
"anutiṣṭhanti": "अनुसरण गर्छन्",
"anuttamam": "अनुत्तम",
"anuttamām": "परम",
"anuvartante": "अनुसरण गर्छन्",
"anuvartate": "अनुसरण गर्छ",
"anuvartayati": "अनुसरण गर्छ",
"anuvidhīyate": "अनुसरण गरिन्छ",
"anuśocanti": "शोक गर्छन्",
"anuśocitum": "शोक गर्न",
"anuśuśruma": "सुनेका छौं",
"anuśāsitāram": "शासकलाई",
"anuṣajjate": "टाँसिन्छ",
"anvaśocaḥ": "शोक गर्छौ",
"anviccha": "खोज",
"anvitāḥ": "युक्त",
"anya": "अरूहरू",
"anyadevatābhaktāḥ": "अरू देवताका भक्तहरू",
"anyadevatāḥ": "अरू देवताहरू",
"anyagāminā": "अर्कोतिर जाने",
"anyam": "अर्कोलाई",
"anyat": "अरू",
"anyathā": "अन्यथा",
"anyatra": "बाहेक",
"anyayā": "अर्कोद्वारा",
"anyaḥ": "अर्को",
"anye": "अरू",
"anyebhyaḥ": "अरूहरूबाट",
"anyām": "अर्को",
"anyān": "अरूहरूलाई",
"anyāni": "अरू",
"anyāyena": "अन्यायपूर्ण उपायले",
"anādim": "आदिरहित",
"anādimadhyāntam": "आदि, मध्य र अन्त्यरहित",
"anādimat": "आदिरहित",
"anāditvāt": "आदिरहितताले",
"anādī": "आदिरहित",
"anāmayam": "रोगरहित",
"anārambhāt": "अनारम्भबाट",
"anārya": "आर्य-अयोग्य",
"anātmanaḥ": "आत्मा नजित्नेको",
"anāvṛttim": "बिना फिर्ती",
"anāśinaḥ": "अविनाशीको",
"anāśritaḥ": "आश्रय नलिने",
"anīkam": "सेना",
"anīśvaram": "स्वामीरहित",
"apahṛta": "हराएको",
"apahṛtajñānāḥ": "ज्ञान लुटिएका",
"apaiśunam": "निन्दारहितता",
"apalāyanam": "नभाग्नु",
"apamānayoḥ": "अपमानमा",
"apanudyāt": "हटाउन सक्थ्यो",
"aparam": "अर्को",
"aparasparasambhūtam": "परस्पर संयोगबाट उत्पन्न",
"apare": "अरू",
"aparigrahaḥ": "अपरिग्रह",
"aparihārye": "अनिवार्यमा",
"aparimeyām": "असीम",
"aparyāptam": "अपर्याप्त",
"aparā": "अपरा",
"aparājitaḥ": "अपराजित",
"aparān": "अरूहरूलाई",
"aparāṇi": "अरूहरू",
"apaśyat": "देख्यो",
"aphalaprepsunā": "फल नचाहनेद्वारा",
"aphalākāṅkṣibhiḥ": "फल नचाहनेहरूद्वारा",
"api": "पनि",
"apohanam": "तिनको हरण",
"apradāya": "फर्काएर नदिई",
"aprakāśaḥ": "अन्धकार",
"aprameyam": "हे अप्रमेय",
"aprameyasya": "अप्रमेयको",
"apratimaprabhāva": "हे अतुल प्रभाव भएका",
"apratiṣṭham": "आधाररहित",
"apratiṣṭhaḥ": "आधाररहित",
"apravṛttiḥ": "आलस्य",
"apriyam": "अप्रिय",
"aprāpya": "नपाएर",
"apsu": "जलमा",
"apunarāvṛttim": "नफर्कने",
"apyayau": "विनाश",
"apāna": "अपानहरू",
"apānam": "अपान",
"apāne": "अपानमा",
"apātrebhyaḥ": "अयोग्य व्यक्तिहरूलाई",
"apāvṛtam": "खुला",
"apāyinaḥ": "जाने",
"aratiḥ": "अरुचि",
"arcitum": "पूजा गर्न",
"arhasi": "योग्य छौ",
"arhati": "सक्छ",
"arhāḥ": "योग्य",
"ari": "शत्रु",
"arisūdana": "हे अरिसूदन",
"arjuna": "हे अर्जुन",
"arjunam": "अर्जुनलाई",
"arjunaḥ": "अर्जुन",
"arpaṇam": "अर्पण",
"arpita": "अर्पण गरिएको",
"artha": "प्रयोजनको",
"artham": "त्यसका निम्ति",
"arthasañcayān": "धनको थुप्रोहरूलाई",
"arthaḥ": "प्रयोजन",
"arthe": "विषयमा",
"arthān": "विषयहरूलाई",
"arthārthī": "अर्थ खोज्ने",
"arthāt": "निम्ति",
"arthāya": "प्रयोजनका निम्ति",
"aryamā": "अर्यमा",
"arāgadveṣataḥ": "राग-द्वेष बिना",
"asadgrāhān": "झूटा दृष्टिहरूलाई",
"asakta": "आसक्तिरहित",
"asaktabuddhiḥ": "आसक्तिरहित बुद्धि भएको",
"asaktam": "आसक्तिरहित",
"asaktaḥ": "आसक्तिरहित",
"asaktiḥ": "अनासक्ति",
"asamarthaḥ": "असमर्थ",
"asammohaḥ": "असम्मोह",
"asammūḍhaḥ": "अमोहित",
"asannyasta": "नत्यागिएको",
"asapatnam": "प्रतिद्वन्द्वीरहित",
"asat": "असत्",
"asataḥ": "असत्को",
"asatkṛtam": "बिना आदर",
"asatkṛtaḥ": "अनादर गरिएको",
"asatyam": "असत्य",
"asau": "त्यो",
"asaṁyatātmanā": "असंयत आत्माले",
"asaṁśayam": "निस्सन्देह",
"asaṁśayaḥ": "निस्सन्देह",
"asaṅga": "आसक्तिरहितता",
"asi": "छौ",
"asiddhau": "असिद्धिमा",
"asinā": "तरबारले",
"asitaḥ": "असित",
"asmadīyaiḥ": "हाम्रा",
"asmi": "छु",
"asmin": "यसमा",
"asmābhiḥ": "हामीद्वारा",
"asmākam": "हाम्रो",
"asmān": "हामीलाई",
"asmāt": "यस",
"asthiram": "अस्थिर",
"asti": "छ",
"astu": "होस्",
"asukham": "सुखरहित",
"asvargyam": "स्वर्ग नदिने",
"asya": "यसको",
"asyām": "यसमा",
"asṛṣṭānnam": "अन्न-दान बिनाको",
"atandritaḥ": "अथक",
"atapaskāya": "तपस्या बिनाकोलाई",
"atattvārthavat": "सत्यबिनाको",
"ataḥ": "त्यसैले",
"atha": "अनि",
"athavā": "वा",
"atho": "अनि",
"ati": "धेरै",
"atimānaḥ": "अभिमान",
"atiricyate": "बढी हुन्छ",
"atitaranti": "पार गर्छन्",
"ativartate": "पार गर्छ",
"atra": "यहाँ",
"atyadbhutam": "अति अद्भुत",
"atyantam": "असीम",
"atyartham": "अत्यन्त",
"atyeti": "पार गर्छ",
"atyucchritam": "धेरै अग्लो",
"atyuṣṇa": "धेरै तातो",
"atyāginām": "अत्यागीहरूका",
"atīndriyam": "इन्द्रियभन्दा पर",
"atītaḥ": "पार गरेको",
"atītya": "पार गरेर",
"atīva": "अत्यन्त",
"auṣadham": "औषधि",
"auṣadhīḥ": "औषधिहरूलाई",
"avabodhasya": "जागरणको",
"avadhyaḥ": "अवध्य",
"avagaccha": "जान",
"avahāsārtham": "मजाकका निम्ति",
"avajñātam": "हेलाले",
"avajānanti": "हेला गर्छन्",
"avanipālasaṅghaiḥ": "राजाहरूका समूहहरूसँग",
"avaram": "निकृष्ट",
"avasthita": "स्थापित",
"avasthitam": "स्थित",
"avasthitaḥ": "स्थित",
"avasthitān": "स्थित",
"avasthitāḥ": "स्थित",
"avasthātum": "उभिन",
"avasādayet": "ढलाउनुपर्छ",
"avatiṣṭhate": "विश्राम गर्छ",
"avatiṣṭhati": "रहन्छ",
"avaśam": "असहाय",
"avaśaḥ": "असहाय",
"avaśiṣyate": "बाँकी रहन्छ",
"avaṣṭabhya": "धानेर",
"avekṣe": "हेर्न चाहन्छु",
"avekṣya": "विचार गरेर",
"avibhaktam": "अविभाजित",
"avidhipūrvakam": "विधिअनुसार होइन",
"avidvāṁsaḥ": "अज्ञानीहरू",
"avijñeyam": "अज्ञेय",
"avikampena": "अविचलित",
"avikāryaḥ": "अपरिवर्तनीय",
"avināśi": "अविनाशी",
"avināśinam": "अविनाशीलाई",
"avināśyantam": "अविनाशीलाई",
"avipaścitaḥ": "अज्ञानीहरू",
"avyabhicāreṇa": "अविचलित",
"avyabhicāriṇyā": "अविचलित",
"avyabhicāriṇī": "अविचलित",
"avyakta": "अव्यक्तलाई",
"avyaktam": "अव्यक्त",
"avyaktamūrtinā": "अव्यक्त रूपद्वारा",
"avyaktasaṁjñake": "अव्यक्त भनिने",
"avyaktaḥ": "अव्यक्त",
"avyaktā": "अव्यक्त",
"avyaktāt": "अव्यक्तबाट",
"avyavasāyinām": "अनिश्चयीहरूका",
"avyayam": "अव्यय",
"avyayasya": "अविनाशीको",
"avyayaḥ": "अविनाशी",
"avyayām": "अविनाशी",
"avyayātmā": "अविनाशी आत्मा भएको",
"avācya": "नभनिने",
"avāpnoti": "प्राप्त गर्छ",
"avāpsyasi": "प्राप्त गर्नेछौ",
"avāpsyatha": "प्राप्त गर्नेछौ",
"avāptavyam": "प्राप्त गर्नुपर्ने",
"avāptum": "प्राप्त गर्न",
"avāpya": "पाएर",
"avāpyate": "प्राप्त गरिन्छ",
"ayajñasya": "यज्ञरहितको",
"ayam": "यो",
"ayaneṣu": "गतिहरूमा",
"ayathāvat": "गलत",
"ayatiḥ": "असंयत",
"ayaśaḥ": "अपकीर्ति",
"ayogataḥ": "योग बिना",
"ayuktasya": "असंयतको",
"ayuktaḥ": "असंयत",
"aśaktaḥ": "असमर्थ",
"aśamaḥ": "अशान्ति",
"aśanaḥ": "नतृप्त हुने",
"aśeṣataḥ": "सम्पूर्ण रूपमा",
"aśeṣeṇa": "पूर्ण रूपमा",
"aśinaḥ": "खानेहरू",
"aśma": "ढुङ्गा",
"aśnan": "खाँदै",
"aśnanti": "भोग्छन्",
"aśnataḥ": "खानेको",
"aśnute": "अनुभव गर्दछ",
"aśnāmi": "ग्रहण गर्छु",
"aśnāsi": "खान्छौ",
"aśocyān": "शोक नगर्नुपर्नेहरूलाई",
"aśoṣyaḥ": "नसुक्ने",
"aśraddadhānaḥ": "श्रद्धारहित",
"aśraddadhānāḥ": "श्रद्धारहितहरू",
"aśraddhayā": "श्रद्धा बिना",
"aśrauṣam": "सुनेँ",
"aśrupūrṇa": "आँसुले भरिएको",
"aśubham": "अशुभ",
"aśubhān": "अशुभहरूलाई",
"aśubhāt": "अशुभबाट",
"aśucau": "अपवित्र",
"aśucivratāḥ": "अशुद्ध संकल्प भएका",
"aśuciḥ": "अशुद्ध",
"aśuśrūṣave": "सेवा नगर्नेलाई",
"aśvattham": "अश्वत्थ",
"aśvatthaḥ": "पीपल",
"aśvatthāmā": "अश्वत्थामा",
"aśvinau": "अश्विनीकुमारहरू",
"aśvānām": "घोडाहरूका",
"aśāntasya": "अशान्तको",
"aśāstravihitam": "शास्त्रले विधान नगरेको",
"aśāśvatam": "अशाश्वत",
"aṁśaḥ": "अंश",
"aṁśumān": "तेजस्वी",
"aṅgāni": "अङ्गहरू",
"aṇoḥ": "सूक्ष्मभन्दा",
"aṇīyāṁsam": "सूक्ष्मतर",
"aṣṭadhā": "आठ गुनामा",
"babhūva": "भयो",
"baddhāḥ": "बाँधिएका",
"badhnāti": "बाँध्छ",
"badhyate": "बाँधिन्छ",
"bahavaḥ": "धेरै",
"bahiḥ": "बाहिर",
"bahubāhūrupādam": "धेरै बाहु, जांघ र खुट्टा भएको",
"bahudaṁṣṭrākarālam": "धेरै भयानक बङ्गारा भएको",
"bahudhā": "धेरै तरिकाले",
"bahulām": "प्रशस्त",
"bahulāyāsam": "ठूलो प्रयाससहित",
"bahumataḥ": "उच्च सम्मानित",
"bahunā": "धेरै",
"bahuvaktranetram": "धेरै मुख र आँखा भएको",
"bahuvidhāḥ": "धेरै प्रकारका",
"bahuśākhāḥ": "धेरै हाँगा भएका",
"bahūdaram": "धेरै पेट भएको",
"bahūn": "धेरै",
"bahūni": "धेरै",
"bahūnām": "धेरैका",
"bala": "बल",
"balam": "बल",
"balavat": "बलियो",
"balavatām": "बलवान्हरूका",
"balavān": "बलवान्",
"balāt": "बलले",
"bandham": "बन्धन",
"bandhanaḥ": "बाँध्ने",
"bandhuḥ": "बन्धु",
"bandhuṣu": "नातेदारहरूमा",
"bandhāt": "बन्धनबाट",
"bandhūn": "नातेदारहरूलाई",
"bata": "हाय",
"bhagavan": "हे भगवान्",
"bhaikṣam": "भिक्षा",
"bhajante": "पूजा गर्छन्",
"bhajanti": "पूजा गर्छन्",
"bhajasva": "पूजा गर",
"bhajate": "पूजा गर्छ",
"bhajati": "पूजा गर्छ",
"bhajatām": "पूजा गर्नेहरूका",
"bhajāmi": "अनुग्रह गर्छु",
"bhaktaḥ": "भक्त",
"bhaktim": "भक्ति",
"bhaktimān": "भक्त",
"bhaktiyogena": "भक्तियोगद्वारा",
"bhaktiḥ": "भक्ति",
"bhaktyupahṛtam": "भक्तिले चढाइएको",
"bhaktyā": "भक्तिले",
"bhaktāḥ": "भक्तहरू",
"bharata": "भरतका",
"bharatarṣabha": "हे भरतश्रेष्ठ",
"bharatasattama": "हे भरतश्रेष्ठ",
"bharataśreṣṭha": "हे भरतश्रेष्ठ",
"bhartā": "धर्ता",
"bhasmasāt": "खरानी",
"bhava": "होऊ",
"bhavantam": "तपाईंलाई",
"bhavantaḥ": "तिमीहरू",
"bhavanti": "हुन्छन्",
"bhavataḥ": "उत्पन्न हुन्छन्",
"bhavati": "हुन्छ",
"bhavaḥ": "जन्म",
"bhavet": "हुन्थ्यो",
"bhavitā": "हुनेछ",
"bhaviṣyanti": "रहनेछन्",
"bhaviṣyati": "हुनेछ",
"bhaviṣyatām": "आउनेहरूका",
"bhaviṣyāmaḥ": "हुने थियौं",
"bhaviṣyāṇi": "भविष्यका",
"bhavāmi": "बन्छु",
"bhavān": "तपाईं",
"bhaya": "भय",
"bhayam": "डर",
"bhayena": "डरले",
"bhayābhaye": "डर र नडरमा",
"bhayānakāni": "भयानक",
"bhayāt": "डरले",
"bhedam": "भेद",
"bheryaḥ": "नगाराहरू",
"bhinnā": "विभाजित",
"bhoga": "भोग",
"bhogaiḥ": "भोगहरूले",
"bhogān": "भोगहरू",
"bhogāḥ": "भोगहरू",
"bhogī": "भोगी",
"bhojanam": "भोजन",
"bhojaneṣu": "भोजनमा",
"bhoktum": "बाँच्न",
"bhoktā": "भोक्ता",
"bhoktāram": "भोक्तालाई",
"bhoktṛtve": "भोगमा",
"bhokṣyase": "भोग्नेछौ",
"bhramati": "भ्रमण गर्छ",
"bhruvoḥ": "भौंको",
"bhrāmayan": "घुमाउँदै",
"bhrātṝn": "भाइहरूलाई",
"bhujaḥ": "खानेहरू",
"bhuktvā": "भोगेर",
"bhuvi": "पृथ्वीमा",
"bhuñjate": "खान्छन्",
"bhuñjānam": "भोग्दै",
"bhuñjīya": "भोग्थेँ",
"bhuṅkte": "भोग्छ",
"bhuṅkṣva": "भोग गर",
"bhāgam": "विभागहरू",
"bhārata": "हे भारत",
"bhāsayate": "प्रकाशित गर्छ",
"bhāsaḥ": "किरणहरू",
"bhāsvatā": "चम्कने",
"bhāvaiḥ": "अवस्थाहरूद्वारा",
"bhāvam": "भाव",
"bhāvanā": "भावना",
"bhāvasamanvitāḥ": "भक्तिले भरिएका",
"bhāvasaṁśuddhiḥ": "हृदयको शुद्धता",
"bhāvayantaḥ": "पोषण गर्दै",
"bhāvayantu": "पोषण गरून्",
"bhāvayata": "पोषण गर",
"bhāvaḥ": "भाव",
"bhāveṣu": "अवस्थाहरूमा",
"bhāvitāḥ": "पोषित",
"bhāvāḥ": "अवस्थाहरू",
"bhāḥ": "प्रभा",
"bhāṣase": "बोल्छौ",
"bhāṣā": "वर्णन",
"bhīma": "भयानक",
"bhītabhītaḥ": "धेरै डराएको",
"bhītam": "त्रसित",
"bhītāni": "त्रसित",
"bhītāḥ": "डराएका",
"bhīṣma": "भीष्म",
"bhīṣmam": "भीष्मलाई",
"bhīṣmaḥ": "भीष्म",
"bhūmau": "पृथ्वीमा",
"bhūmiḥ": "पृथ्वी",
"bhūtabhartṛ": "प्राणीहरूका धर्ता",
"bhūtabhāvana": "हे प्राणीहरूका स्रोत",
"bhūtabhāvanaḥ": "प्राणीहरूको स्रोत",
"bhūtabhāvodbhavakaraḥ": "प्राणीहरूको उत्पत्तिको कारण",
"bhūtabhṛt": "प्राणीहरूलाई धान्ने",
"bhūtagaṇān": "भूतहरूका समूहहरूलाई",
"bhūtagrāmam": "शरीरका तत्त्वहरू",
"bhūtagrāmaḥ": "प्राणी-समूह",
"bhūtam": "प्राणी",
"bhūtamaheśvaram": "प्राणीहरूका महान् स्वामीलाई",
"bhūtaprakṛtimokṣam": "प्रकृतिबाट मुक्ति",
"bhūtapṛthagbhāvam": "प्राणीहरूका विविध अवस्थाहरूलाई",
"bhūtasargau": "प्राणीहरूका दुई सृष्टिहरू",
"bhūtasthaḥ": "प्राणीहरूमा रहने",
"bhūtaviśeṣasaṅghān": "विविध भूतहरूका समूहहरूलाई",
"bhūtejyāḥ": "भूतपूजकहरू",
"bhūteśa": "हे भूतेश",
"bhūteṣu": "प्राणीहरूमा",
"bhūtiḥ": "समृद्धि",
"bhūtvā": "भएर",
"bhūtādim": "प्राणीहरूको स्रोतलाई",
"bhūtāni": "प्राणीहरू",
"bhūtānām": "प्राणीहरूको",
"bhūyaḥ": "फेरि",
"bhūḥ": "होऊ",
"bhṛguḥ": "भृगु",
"bibharti": "धान्छ",
"boddhavyam": "बुझ्नुपर्ने",
"bodhayantaḥ": "ज्ञान दिँदै",
"brahma": "ब्रह्म",
"brahmabhuvanāt": "ब्रह्मलोकबाट",
"brahmabhūtam": "ब्रह्मभूत",
"brahmabhūtaḥ": "ब्रह्मभूत",
"brahmabhūyāya": "ब्रह्मका निम्ति",
"brahmacaryam": "ब्रह्मचर्य",
"brahmacārivrate": "ब्रह्मचर्य व्रतमा",
"brahmakarma": "ब्रह्मको कर्तव्य",
"brahmanirvāṇam": "ब्रह्मनिर्वाण",
"brahmasaṁsparśam": "ब्रह्मको सम्पर्क",
"brahmasūtrapadaiḥ": "ब्रह्मसूत्रका पदहरूमा",
"brahmavidaḥ": "ब्रह्मज्ञहरू",
"brahmavit": "ब्रह्मज्ञ",
"brahmavādinām": "ब्रह्मवादीहरूका",
"brahmaṇaḥ": "ब्रह्मको",
"brahmaṇi": "ब्रह्ममा",
"brahmaṇā": "ब्रह्मद्वारा",
"brahmāṇam": "ब्रह्मालाई",
"bravīmi": "भन्छु",
"bravīṣi": "भन्छौ",
"brāhmaṇakṣatriyaviśām": "ब्राह्मण, क्षत्रिय र वैश्यहरूका",
"brāhmaṇasya": "ब्राह्मणको",
"brāhmaṇe": "ब्राह्मणमा",
"brāhmaṇāḥ": "ब्राह्मणहरू",
"brāhmī": "ब्राह्मी",
"brūhi": "भन",
"buddhau": "बुद्धिमा",
"buddhayaḥ": "बुद्धिहरू",
"buddheḥ": "बुद्धिको",
"buddhi": "बुद्धिले",
"buddhim": "बुद्धि",
"buddhimatām": "बुद्धिमान्हरूका",
"buddhimān": "बुद्धिमान्",
"buddhināśaḥ": "बुद्धिनाश",
"buddhināśāt": "बुद्धिनाशबाट",
"buddhisaṁyogam": "बुद्धिको संयोग",
"buddhiyogam": "बुद्धियोग",
"buddhiyogāt": "बुद्धियोगभन्दा",
"buddhiyuktaḥ": "बुद्धियुक्त",
"buddhiyuktāḥ": "बुद्धियुक्त",
"buddhiḥ": "बुद्धि",
"buddhvā": "बुझेर",
"buddhyā": "बुद्धिले",
"budhaḥ": "ज्ञानी",
"budhāḥ": "ज्ञानीहरू",
"bāho": "हे बाहु",
"bāhuḥ": "बाहु भएको",
"bāhya": "बाह्य",
"bāhyān": "बाह्य",
"bālāḥ": "बालकहरू",
"bāndhavān": "नातेदारहरूलाई",
"bījam": "बीज",
"bījapradaḥ": "बीज दिने",
"bṛhaspatim": "बृहस्पतिलाई",
"bṛhatsāma": "बृहत्साम",
"ca": "र",
"caila": "वस्त्र",
"cakrahastam": "हातमा चक्र लिएको",
"cakram": "चक्र",
"cakriṇam": "चक्रधारीलाई",
"cakṣuḥ": "दृष्टि",
"calam": "अस्थिर",
"calati": "चल्छ",
"calitamānasaḥ": "मन भड्किएको",
"camūm": "सेना",
"candramasi": "चन्द्रमामा",
"caram": "चल",
"caran": "चल्दै",
"caranti": "अभ्यास गर्छन्",
"carati": "गर्छ",
"caratām": "विचरण गर्ने",
"carācaram": "चर वा अचर",
"carācarasya": "चर-अचरको",
"caturbhujena": "चतुर्भुजद्वारा",
"caturvidham": "चार प्रकारको",
"caturvidhāḥ": "चार प्रकारका",
"catvāraḥ": "चार",
"cañcalam": "चञ्चल",
"cañcalatvāt": "चञ्चलताले",
"cekitānaḥ": "चेकितान",
"cet": "यदि",
"cetanā": "चेतना",
"cetasaḥ": "मनको",
"cetasā": "मनले",
"cetasām": "जसका मन",
"cetāḥ": "चित्त",
"ceṣṭasya": "प्रयासको",
"ceṣṭate": "चेष्टा गर्छ",
"chalayatām": "धूर्तहरूका",
"chandasām": "छन्दहरूका",
"chandobhiḥ": "छन्दहरूमा",
"chandāṁsi": "वेदहरू",
"chettum": "काट्न",
"chettā": "काट्ने",
"chindanti": "काट्छन्",
"chinna": "च्यातिएको",
"chinnasaṁśayaḥ": "सन्देह काटिएको",
"chittvā": "काटेर",
"cikīrṣavaḥ": "चाहनेहरू",
"cikīrṣuḥ": "गर्न चाहने",
"cintayantaḥ": "चिन्तन गर्दै",
"cintayet": "चिन्तन गर्नुपर्छ",
"cintyaḥ": "चिन्तन गर्नुपर्ने",
"cintām": "चिन्ताहरू",
"cirāt": "लामो समयपछि",
"citrarathaḥ": "चित्ररथ",
"citta": "मनको",
"cittam": "चित्त",
"cittātmā": "मन र आत्मा",
"cyavanti": "झर्छन्",
"cāndramasam": "चान्द्र",
"cāpam": "धनुष",
"cāriṇau": "चल्ने",
"cāturvarṇyam": "चार वर्ण",
"cūrṇitaiḥ": "पिसिएका",
"dadhmau": "बजाए",
"dadhmuḥ": "बजाए",
"dadhāmi": "राख्छु",
"dadāmi": "दिन्छु",
"dadāsi": "दिन्छौ",
"dagdha": "जलेको",
"dahati": "बाल्छ",
"daityānām": "दैत्यहरूका",
"daivam": "दैव",
"daivaḥ": "दैवी",
"daivī": "दैवी",
"daivīm": "दैवी",
"dakṣaḥ": "दक्ष",
"dakṣiṇāyanam": "दक्षिणायन",
"damayatām": "दण्ड दिनेहरूमा",
"damaḥ": "संयम",
"dambha": "ढोंग",
"dambhamānamadānvitāḥ": "दम्भ, घमण्ड र मदले भरिएका",
"dambhaḥ": "दम्भ",
"dambhena": "दम्भले",
"dambhāhaṅkārasaṁyuktāḥ": "दम्भ र अहंकारले युक्त",
"dambhārtham": "देखावटका निम्ति",
"darpam": "घमण्ड",
"darpaḥ": "घमण्ड",
"darśanakāṅkṣiṇaḥ": "दर्शन चाहने",
"darśaya": "देखाऊ",
"darśayāmāsa": "देखाए",
"darśitam": "देखाइएको",
"dattam": "दिइएको",
"dattān": "दिइएका",
"daurbalyam": "दुर्बलता",
"dayā": "दया",
"daśa": "दस",
"daśanāntareṣu": "दाँतहरूका बीचमा",
"daṁṣṭrākarālāni": "भयानक बङ्गारा भएका",
"daṇḍaḥ": "दण्ड",
"dehabhṛt": "देहधारी",
"dehabhṛtā": "देहधारीद्वारा",
"dehabhṛtām": "देहधारीहरूका",
"deham": "शरीर",
"dehasamudbhavān": "शरीरबाट जन्मेका",
"dehavadbhiḥ": "देहधारीहरूद्वारा",
"dehe": "शरीरमा",
"dehinam": "देहधारीलाई",
"dehinaḥ": "देहधारीको",
"dehinām": "देहधारीहरूका",
"dehāntara": "अर्को शरीर",
"dehāḥ": "शरीरहरू",
"dehī": "देहधारी",
"deva": "देवताका",
"devabhogān": "देवताका भोगहरू",
"devadattam": "देवदत्त",
"devadeva": "हे देवदेव",
"devadevasya": "देवताका देवताको",
"devalaḥ": "देवल",
"devam": "देवतालाई",
"devarṣiḥ": "देवर्षि",
"devarṣīṇām": "देवर्षिहरूका",
"devatāḥ": "देवताहरू",
"devavara": "हे देवतामा श्रेष्ठ",
"devavratāḥ": "देवपूजकहरू",
"devayajaḥ": "देवपूजकहरू",
"deveśa": "हे देवेश",
"deveṣu": "देवताहरूमा",
"devān": "देवताहरूलाई",
"devānām": "देवताहरूका",
"devāḥ": "देवताहरू",
"deśe": "ठाउँमा",
"dhanam": "धन",
"dhanamānamadānvitāḥ": "धनको घमण्डले भरिएका",
"dhanañjaya": "हे धनञ्जय",
"dhanañjayaḥ": "धनञ्जय",
"dhanaṁjaya": "हे धनञ्जय",
"dhanurdharaḥ": "धनुर्धारी",
"dhanuḥ": "धनुष",
"dhanāni": "धनहरू",
"dharma": "धर्म",
"dharmakāmārthān": "धर्म, काम र अर्थलाई",
"dharmam": "धर्म",
"dharmasya": "धर्मको",
"dharmaḥ": "धर्म",
"dharme": "धर्ममा",
"dharmya": "धार्मिक",
"dharmyam": "धार्मिक",
"dharmyāt": "धार्मिकभन्दा",
"dharmāt": "धर्मभन्दा",
"dharmātmā": "धर्मात्मा",
"dharmāviruddhaḥ": "धर्मविरुद्ध नभएको",
"dharmāḥ": "धर्महरू",
"dharmāṇām": "धर्महरूका",
"dhenūnām": "गाईहरूका",
"dhruvam": "नित्य",
"dhruvaḥ": "निश्चित",
"dhruvā": "स्थिर",
"dhvajaḥ": "ध्वज भएको",
"dhyānam": "ध्यान",
"dhyānayogaparaḥ": "ध्यानयोगमा तत्पर",
"dhyānena": "ध्यानद्वारा",
"dhyānāt": "ध्यानभन्दा",
"dhyāyantaḥ": "ध्यान गर्दै",
"dhyāyataḥ": "चिन्तन गर्नेको",
"dhāma": "धाम",
"dhārayan": "धानेर",
"dhārayate": "धान्छ",
"dhārayāmi": "धान्छु",
"dhārtarāṣṭrasya": "धार्तराष्ट्रको",
"dhārtarāṣṭrān": "धृतराष्ट्रका पुत्रहरुलाई",
"dhārtarāṣṭrāḥ": "धृतराष्ट्र का पुत्रहरूले",
"dhārtarāṣṭrāṇām": "धार्तराष्ट्रहरूका",
"dhāryate": "धानिन्छ",
"dhātā": "विधाता",
"dhātāram": "धर्तालाई",
"dhīmatā": "बुद्धिमान्ले",
"dhīmatām": "ज्ञानीहरूका",
"dhīram": "ज्ञानीलाई",
"dhīraḥ": "धीर",
"dhūmaḥ": "धुवाँ",
"dhūmena": "धुवाँले",
"dhṛtarāṣṭra": "धृतराष्ट्र (अन्धा राजा)",
"dhṛtarāṣṭrasya": "धृतराष्ट्रको",
"dhṛteḥ": "धृतिको",
"dhṛtigṛhītayā": "धैर्यले दृढ गरिएको",
"dhṛtim": "धैर्य",
"dhṛtiḥ": "धैर्य",
"dhṛtyutsāhasamanvitaḥ": "धैर्य र उत्साहले युक्त",
"dhṛtyā": "धैर्यले",
"dhṛṣṭadyumnaḥ": "धृष्टद्युम्न",
"dhṛṣṭaketuḥ": "धृष्टकेतु",
"divi": "स्वर्गमा",
"divyagandhānulepanam": "दिव्य सुगन्धले लेपित",
"divyam": "दिव्य",
"divyamālyāmbaradharam": "दिव्य माला र वस्त्र लगाएको",
"divyau": "दिव्य",
"divyān": "दिव्य",
"divyānekodyatāyudham": "धेरै दिव्य हतियार उठाएको",
"divyāni": "दिव्य",
"divyānām": "दिव्यहरूका",
"divyāḥ": "दिव्य",
"diśaḥ": "दिशाहरू",
"doṣa": "दोष",
"doṣaiḥ": "दोषहरूले",
"doṣam": "दोष",
"doṣavat": "दोषजस्तो",
"doṣeṇa": "दोषले",
"drakṣyasi": "देख्नेछौ",
"draupadeyāḥ": "द्रौपदीका छोराहरू",
"dravanti": "भाग्छन्",
"dravya": "द्रव्यको",
"dravyamayāt": "द्रव्यमयभन्दा",
"draṣṭum": "देख्न",
"draṣṭā": "द्रष्टा",
"drohe": "द्रोहमा",
"droṇa": "द्रोण",
"droṇam": "द्रोणलाई",
"droṇaḥ": "द्रोण",
"drupada": "द्रुपदको",
"drupadaḥ": "द्रुपद",
"dur": "गाह्रो",
"duratyayā": "पार गर्न गाह्रो",
"durbuddheḥ": "दुर्बुद्धिको",
"durgatim": "दुर्गतिमा",
"durlabhataram": "पाउन अझ गाह्रो",
"durmatiḥ": "दुर्मति",
"durmedhā": "दुर्बुद्धि",
"durnigraham": "रोक्न गाह्रो",
"durnirīkṣyam": "हेर्न गाह्रो",
"duryodhanaḥ": "दुर्योधन",
"duḥ": "कठिन",
"duḥkha": "दुःख",
"duḥkhadoṣānudarśanam": "दुःखको दोषको दर्शन",
"duḥkhahā": "दुःख नष्ट गर्ने",
"duḥkham": "दुःख",
"duḥkhasaṁyoga": "दुःखसंयोगको",
"duḥkhataram": "अझ पीडादायक",
"duḥkhayonayaḥ": "दुःखका स्रोतहरू",
"duḥkhe": "दुःखमा",
"duḥkhena": "दुःखले",
"duḥkheṣu": "दुःखहरूमा",
"duḥkhālayam": "दुःखको घर",
"duḥkhāntam": "दुःखको अन्त्य",
"duḥkhānām": "दुःखहरूका",
"duṣkṛte": "दुष्कर्ममा",
"duṣkṛtinaḥ": "दुष्कर्मीहरू",
"duṣkṛtām": "दुष्कर्मीहरूका",
"duṣprāpaḥ": "पाउन गाह्रो",
"duṣpūram": "कहिल्यै पूरा नहुने",
"duṣṭāsu": "भ्रष्ट",
"dvaidhāḥ": "जसका सन्देह",
"dvandva": "द्वन्द्वहरू",
"dvandvaiḥ": "द्वन्द्वहरूबाट",
"dvandvamohanirmuktāḥ": "द्वन्द्वको मोहबाट मुक्त",
"dvandvamohena": "द्वन्द्वको मोहले",
"dvandvaḥ": "द्वन्द्व",
"dvau": "दुई",
"dveṣa": "द्वेष",
"dveṣau": "द्वेष",
"dveṣaḥ": "द्वेष",
"dveṣya": "घृणित",
"dveṣyaḥ": "घृणित",
"dveṣṭi": "घृणा गर्दछ",
"dvija": "द्विज",
"dvividhā": "द्विविध",
"dviṣataḥ": "घृणा गर्ने",
"dvāram": "ढोका",
"dyāvāpṛthivyoḥ": "स्वर्ग र पृथ्वीको",
"dyūtam": "पासा",
"dākṣyam": "दक्षता",
"dānaiḥ": "दानहरूद्वारा",
"dānakriyāḥ": "दान-क्रियाहरू",
"dānam": "दान",
"dānavāḥ": "दानवहरू",
"dāne": "दानमा",
"dānena": "दानद्वारा",
"dāneṣu": "दानहरूमा",
"dāsyante": "दिनेछन्",
"dāsyāmi": "दिनेछु",
"dātavyam": "दिनुपर्ने",
"dāḥ": "दिने",
"dīpaḥ": "बत्ती",
"dīpite": "बालेको",
"dīptahutāśavaktram": "बलेको आगोजस्तै मुख भएको",
"dīptam": "बलेको",
"dīptaviśālanetram": "बलेका विशाल आँखा भएको",
"dīptimantam": "बलेको",
"dīptānalārkadyutim": "बलेको आगो र सूर्यजस्तो तेज भएको",
"dīrghasūtrī": "ढिलाइ गर्ने",
"dīyate": "दिइन्छ",
"dūrastham": "टाढा रहेको",
"dūreṇa": "टाढा",
"dṛḍham": "दृढ",
"dṛḍhaniścayaḥ": "दृढ निश्चयको",
"dṛḍhavratāḥ": "दृढ व्रत भएका",
"dṛḍhena": "बलियो",
"dṛṣṭapūrvam": "पहिले देखिएको",
"dṛṣṭavān": "देखेको",
"dṛṣṭaḥ": "देखिएको",
"dṛṣṭim": "दृष्टि",
"dṛṣṭvā": "देखेर",
"ebhiḥ": "यिनीहरूद्वारा",
"ebhyaḥ": "तीभन्दा पर",
"edhāṁsi": "इन्धनहरू",
"ekabhaktiḥ": "एकनिष्ठ भक्ति",
"ekam": "एक",
"ekasmin": "एकमा",
"ekastham": "एकमा स्थित",
"ekatvam": "एकत्वमा",
"ekatvena": "एकताका रूपमा",
"ekayā": "एकद्वारा",
"ekaḥ": "एक",
"eke": "कोही",
"ekeha": "एक, यहाँ",
"ekena": "एक्लै",
"ekāgram": "एकाग्र",
"ekāgreṇa": "एकाग्र",
"ekākī": "एक्लै",
"ekākṣaram": "एकाक्षर",
"ekāntam": "पूरै",
"ekāntikasya": "एकान्तिकको",
"ekāṁśena": "एक अंशले",
"enam": "उसलाई",
"enām": "यसलाई",
"etaiḥ": "यिनीहरूबाट",
"etasya": "यसको",
"etat": "यो",
"etayoḥ": "यी दुईका",
"ete": "यी",
"etena": "यसद्वारा",
"eteṣām": "यिनका",
"eti": "आउँछ",
"etām": "यो",
"etān": "यिनीहरूलाई",
"etāni": "यी",
"etāvat": "यति",
"eva": "नै",
"evam": "यसरी",
"evaṁrūpaḥ": "यस्तो रूपमा",
"evaṁvidhaḥ": "यस्तो रूपमा",
"eṣaḥ": "यो",
"eṣyasi": "आउनेछौ",
"eṣyati": "पुग्नेछ",
"eṣā": "यो",
"eṣām": "तिनका",
"gaccha": "जाऊ",
"gacchan": "जाँदै",
"gacchanti": "जान्छन्",
"gacchati": "जान्छ",
"gadinam": "गदासहित",
"gahanā": "गहिरो",
"gajendrāṇām": "गजराजहरूका",
"gamaḥ": "जाऊ",
"gamyate": "पुगिन्छ",
"gandharvayakṣāsurasiddhasaṅghāḥ": "गन्धर्व, यक्ष, दानव र सिद्धहरूका समूहहरू",
"gandharvāṇām": "गन्धर्वहरूका",
"gandhaḥ": "गन्ध",
"gandhān": "सुगन्धहरू",
"gantavyam": "पुग्नुपर्ने",
"gantāsi": "जानेछौ",
"garbham": "बीज",
"garbhaḥ": "भ्रूण",
"garīyase": "महान्लाई",
"garīyaḥ": "राम्रो",
"garīyān": "सबैभन्दा ठूलो",
"gata": "गएको",
"gatam": "व्याप्त",
"gatarasam": "बेस्वाद",
"gatasaṁdehaḥ": "सन्देह गएको",
"gatavyathaḥ": "व्यथारहित",
"gataḥ": "फर्केको",
"gatim": "गति",
"gatiḥ": "गति",
"gatvā": "गएर",
"gatāgatam": "आउने-जाने",
"gatāsūn": "मृतकहरूलाई",
"gatāḥ": "गएका",
"gatī": "गतिहरू",
"gavi": "गाईमा",
"gehe": "घरमा",
"ghnataḥ": "मार्दा पनि",
"ghnānām": "मार्नेहरूका",
"ghoram": "भयानक",
"ghore": "भयानक",
"ghoṣaḥ": "कोलाहल",
"ghrāṇam": "घ्राण",
"ghātayati": "मार्न लगाउँछ",
"girām": "शब्दहरूका",
"glāniḥ": "ह्रास",
"gomukhāḥ": "गोमुखहरू",
"govinda": "हे गोविन्द",
"govindam": "गोविन्दलाई",
"grasamānaḥ": "निल्दै",
"grasiṣṇu": "निल्ने",
"grāhyam": "ग्रहण गर्नुपर्ने",
"grīvam": "घाँटी",
"guhyam": "गोप्य",
"guhyatamam": "सबैभन्दा गोप्य",
"guhyataram": "अझ गोप्य",
"guhyānām": "गोप्यहरूका",
"guhyāt": "गोप्यभन्दा",
"guru": "गुरुहरू",
"guruḥ": "गुरु",
"guruṇā": "भारी",
"gurūn": "गुरुहरूलाई",
"guḍākeśa": "हे गुडाकेश",
"guḍākeśaḥ": "गुडाकेश",
"guḍākeśena": "गुडाकेशद्वारा",
"guṇa": "गुण",
"guṇabhedataḥ": "गुणको भेदअनुसार",
"guṇabhoktṛ": "गुण भोग्ने",
"guṇaiḥ": "गुणहरूद्वारा",
"guṇamayaiḥ": "गुणमय",
"guṇamayī": "गुणमयी",
"guṇapravṛddhāḥ": "गुणले पोषित",
"guṇasaṁkhyāne": "गुणको गणनामा",
"guṇasaṅgaḥ": "गुणमा आसक्ति",
"guṇataḥ": "गुणहरूद्वारा",
"guṇebhyaḥ": "गुणभन्दा पर",
"guṇeṣu": "गुणहरूमा",
"guṇān": "गुणहरूलाई",
"guṇānvitam": "गुणसहित",
"guṇātītaḥ": "गुणातीत",
"guṇāḥ": "गुणहरू",
"gām": "पृथ्वीलाई",
"gātrāṇi": "अङ्गहरू",
"gāyatrī": "गायत्री",
"gāṇḍīvam": "गाण्डीव",
"gītam": "गाइएको",
"gṛhyate": "रोकिन्छ",
"gṛhītvā": "लिएर",
"gṛhṇan": "लिँदै",
"gṛhṇāti": "लिन्छ",
"gṛṇanti": "प्रशंसा गर्छन्",
"ha": "नै",
"haniṣye": "मार्नेछु",
"hanta": "हेर",
"hanti": "मार्छ",
"hantum": "मार्न",
"hantāram": "मार्नेलाई",
"hanyamāne": "मारिँदा",
"hanyate": "मारिन्छ",
"hanyuḥ": "मारे भने",
"haranti": "बोक्छन्",
"harati": "बोक्छ",
"hareḥ": "हरिको",
"hariḥ": "हरि",
"harṣa": "हर्ष",
"harṣam": "हर्ष",
"harṣaśokānvitaḥ": "हर्ष-शोकले चल्ने",
"harṣaḥ": "रोमाञ्च",
"hastini": "हात्तीमा",
"hastāt": "हातबाट",
"hatam": "मारिएको",
"hataḥ": "मारिएको",
"hatvā": "मारेर",
"hatān": "मारिएका",
"haviḥ": "आहुति",
"hayaiḥ": "घोडाहरूले",
"he": "हे",
"hetavaḥ": "कारणहरू",
"hetoḥ": "निम्ति",
"hetumadbhiḥ": "कारणसहित",
"hetunā": "यस कारणले",
"hetuḥ": "कारण",
"hi": "नै",
"himālayaḥ": "हिमालय",
"hinasti": "हानि गर्छ",
"hitakāmyayā": "हित चाहेर",
"hitam": "हित",
"hitvā": "त्यागेर",
"hiṁsām": "हिंसा",
"hiṁsātmakaḥ": "हिंसात्मक",
"hriyate": "लैजान्छ",
"hrīḥ": "लज्जा",
"hutam": "अर्पण गरिएको",
"hāniḥ": "नाश",
"hṛdaya": "हृदयको",
"hṛdayāni": "हृदयहरू",
"hṛdaḥ": "हृदय भएका",
"hṛddeśe": "हृदयमा",
"hṛdi": "हृदयमा",
"hṛdyāḥ": "मनपर्ने",
"hṛtajñānāḥ": "ज्ञान लुटिएका",
"hṛtstham": "हृदयमा बस्ने",
"hṛṣitaḥ": "प्रसन्न",
"hṛṣyati": "रम्छ",
"hṛṣyāmi": "रमाउँछु",
"hṛṣīkeśa": "हे हृषीकेश",
"hṛṣīkeśam": "हृषीकेशलाई",
"hṛṣīkeśaḥ": "हृषीकेश",
"hṛṣṭaromā": "रौं ठाडो भएको",
"iccha": "खोज",
"icchantaḥ": "इच्छा गर्दै",
"icchasi": "चाहन्छौ",
"icchati": "इच्छा गर्छ",
"icchā": "इच्छा",
"icchāmi": "चाहन्छु",
"idam": "यो",
"idānīm": "अहिले",
"iha": "यहाँ",
"ijyate": "अर्पण गरिन्छ",
"ijyayā": "पूजाद्वारा",
"ikṣvākave": "इक्ष्वाकुलाई",
"imam": "यो",
"imau": "यी दुई",
"ime": "यी",
"imām": "यो",
"imān": "यी",
"imāḥ": "यी",
"indriya": "इन्द्रिय",
"indriyagocarāḥ": "इन्द्रियका विषयहरू",
"indriyagrāmam": "इन्द्रिय-समूह",
"indriyaiḥ": "इन्द्रियहरूद्वारा",
"indriyasya": "इन्द्रियको",
"indriyebhyaḥ": "इन्द्रियहरूभन्दा",
"indriyārthebhyaḥ": "इन्द्रियविषयहरूबाट",
"indriyārtheṣu": "इन्द्रियविषयहरूमा",
"indriyāṇi": "इन्द्रियहरू",
"indriyāṇām": "इन्द्रियहरूका",
"itaraḥ": "अर्को",
"itaḥ": "यहाँबाट",
"iti": "यसरी",
"iva": "झैँ",
"iyam": "यो",
"iṅgate": "चल्छ",
"iṣubhiḥ": "वाणहरूले",
"iṣvāsaḥ": "धनुर्धारी",
"iṣvāsāḥ": "धनुर्धारीहरू",
"iṣṭa": "इच्छितहरूको",
"iṣṭam": "प्रिय",
"iṣṭaḥ": "पूजित",
"iṣṭvā": "पूजा गरेर",
"iṣṭān": "इच्छितहरूलाई",
"iṣṭāniṣṭopapattiṣu": "लाभ-हानिमा",
"iṣṭāḥ": "प्रिय",
"jagannivāsa": "हे जगन्निवास",
"jagat": "जगत्",
"jagataḥ": "संसारको",
"jagatpate": "हे जगत्पते",
"jaghanyaguṇavṛttasthāḥ": "नीच गुणमा लागेकाहरू",
"jahi": "मार",
"jahāti": "त्याग्छ",
"jaiḥ": "जन्मेका",
"janakādayaḥ": "जनक आदि",
"janam": "मानिस",
"janasaṁsadi": "मानिसको संगतमा",
"janayet": "उत्पन्न गर्नुपर्छ",
"janaḥ": "मानिस",
"janma": "जन्म",
"janmabandha": "जन्मको बन्धनको",
"janmamṛtyujarāduḥkhaiḥ": "जन्म, मृत्यु, बुढ्यौली र दुःखबाट",
"janmamṛtyujarāvyādhi": "जन्म, मृत्यु, बुढ्यौली र रोगको",
"janmani": "जन्मपछि",
"janmanām": "जन्महरूका",
"janmasu": "जन्महरूमा",
"janmāni": "जन्महरू",
"jantavaḥ": "प्राणीहरू",
"janādhipāḥ": "जनका शासकहरू",
"janānām": "मानिसहरूका",
"janārdana": "हे जनार्दन",
"janāḥ": "मानिसहरू",
"japayajñaḥ": "जपयज्ञ",
"jarā": "बुढ्यौली",
"jaya": "विजय",
"jayadratham": "जयद्रथलाई",
"jayadrathaḥ": "जयद्रथ",
"jayaḥ": "विजय",
"jayema": "जित्थ्यौं",
"jayeyuḥ": "जित्थे",
"jetāsi": "जित्नेछौ",
"jhaṣāṇām": "माछाहरूका",
"jighran": "सुँघ्दै",
"jigīṣatām": "विजय चाहनेहरूका",
"jijñāsuḥ": "जिज्ञासु",
"jijīviṣāmaḥ": "जिउन चाहन्थ्यौं",
"jitasaṅgadoṣāḥ": "आसक्तिको दोष जितेका",
"jitaḥ": "जितिएको",
"jitendriyaḥ": "इन्द्रियजित",
"jitvā": "जितेर",
"jitātmanaḥ": "आत्मजितको",
"jitātmā": "आत्मजित",
"joṣayet": "उत्साहित गर्नुपर्छ",
"juhoṣi": "अर्पण गर्छौ",
"juhvati": "अर्पण गर्छन्",
"juṣṭam": "अभ्यास गरिएको",
"jvaladbhiḥ": "बलेका",
"jvalanam": "आगो",
"jvaraḥ": "ज्वरो",
"jyotiḥ": "ज्योति",
"jyotiṣām": "ज्योतिहरूका",
"jyāyasī": "श्रेष्ठ",
"jyāyaḥ": "श्रेष्ठ",
"jñeyam": "जान्नुपर्ने",
"jñeyaḥ": "जान्नुपर्ने",
"jñāna": "ज्ञान",
"jñānacakṣuṣaḥ": "ज्ञानको आँखा भएकाहरू",
"jñānacakṣuṣā": "ज्ञानको आँखाले",
"jñānadīpena": "ज्ञानको बत्तीले",
"jñānagamyam": "ज्ञानको लक्ष्य",
"jñānam": "ज्ञान",
"jñānasaṅgena": "ज्ञानको आसक्तिले",
"jñānasya": "ज्ञानको",
"jñānavatām": "ज्ञानीहरूका",
"jñānavān": "ज्ञानी",
"jñānayajñaḥ": "ज्ञानयज्ञ",
"jñānayajñena": "ज्ञानयज्ञद्वारा",
"jñānayogavyavasthitiḥ": "ज्ञान र योगमा स्थिरता",
"jñānayogena": "ज्ञानयोगद्वारा",
"jñāne": "ज्ञानमा",
"jñānena": "ज्ञानले",
"jñānibhyaḥ": "ज्ञानीहरूभन्दा",
"jñāninaḥ": "ज्ञानीका",
"jñānānām": "ज्ञानहरूका",
"jñānāt": "ज्ञानभन्दा",
"jñānī": "ज्ञानी",
"jñāsyasi": "जान्नेछौ",
"jñātavyam": "जान्नुपर्ने",
"jñātena": "जानेर",
"jñātum": "जान्न",
"jñātvā": "जानेर",
"jāgarti": "जाग्छ",
"jāgrataḥ": "जाग्नेको",
"jāgrati": "जाग्छन्",
"jāhnavī": "गङ्गा",
"jānan": "जान्दै",
"jāne": "जान्दछु",
"jānāti": "जान्दछ",
"jātasya": "जन्मेकाको",
"jāti": "जाति",
"jātu": "कहिल्यै",
"jātāḥ": "जन्मेका",
"jāyante": "उत्पन्न हुन्छन्",
"jāyate": "जन्मन्छ",
"jīrṇāni": "जीर्ण",
"jīvabhūtaḥ": "जीवात्मा बनेको",
"jīvabhūtām": "जीवतत्त्व",
"jīvaloke": "जीवलोकमा",
"jīvanam": "जीवन",
"jīvati": "बाँच्छ",
"jīvitena": "जीवनसँग",
"kaccit": "के",
"kadācana": "कहिल्यै",
"kadācit": "कहिल्यै",
"kaiḥ": "केले",
"kalayatām": "गणना गर्नेहरूका",
"kalevaram": "शरीर",
"kalmaṣāḥ": "जसका पाप",
"kalpakṣaye": "कल्पको अन्त्यमा",
"kalpate": "योग्य हुन्छ",
"kalpādau": "कल्पको सुरुमा",
"kalyāṇakṛt": "कल्याणकारी",
"kam": "कसलाई",
"kamalapatrākṣa": "हे कमलनयन",
"kamalāsanastham": "कमलासनमा बसेको",
"kandarpaḥ": "कन्दर्प",
"kapi": "बाँदर",
"kapilaḥ": "कपिल",
"karaṇam": "करण",
"kariṣyasi": "गर्नेछौ",
"kariṣyati": "गर्नेछ",
"kariṣye": "गर्नेछु",
"karma": "कर्म",
"karmabandham": "कर्मबन्धन",
"karmabandhanaiḥ": "कर्मबन्धनहरूबाट",
"karmabhiḥ": "कर्महरूले",
"karmacodanā": "कर्मको प्रेरणा",
"karmajam": "कर्मबाट जन्मेको",
"karmajā": "कर्मबाट जन्मेको",
"karmajān": "कर्मबाट जन्मेका",
"karmaphala": "कर्मफलको",
"karmaphalam": "कर्मफल",
"karmaphalaprepsuḥ": "कर्मफलको लोभी",
"karmaphalasaṁyogam": "कर्मफलको संयोग",
"karmaphalatyāgaḥ": "कर्मफलको त्याग",
"karmaphalatyāgī": "कर्मफल त्याग्ने",
"karmaphale": "कर्मफलमा",
"karmasannyāsāt": "कर्मसंन्यासभन्दा",
"karmasaṁgrahaḥ": "कर्मको आधार",
"karmasaṁjñitaḥ": "कर्म भनिने",
"karmasaṅgena": "कर्मको आसक्तिले",
"karmasaṅgiṣu": "कर्ममा आसक्तहरूमा",
"karmasu": "कर्महरूमा",
"karmayogaḥ": "कर्मयोग",
"karmayogena": "कर्मयोगद्वारा",
"karmaṇaḥ": "कर्मको",
"karmaṇi": "कर्ममा",
"karmaṇā": "कर्मले",
"karmaṇām": "कर्महरूको",
"karmibhyaḥ": "कर्मीहरूभन्दा",
"karmā": "कर्म गर्ने",
"karmānubandhīni": "कर्ममा बाँध्ने",
"karmāṇam": "जसका कर्म",
"karmāṇi": "कर्महरू",
"karomi": "गर्छु",
"karoti": "गर्छ",
"karoṣi": "गर्छौ",
"kartavyam": "गर्नुपर्ने",
"kartavyāni": "गर्नुपर्ने",
"kartum": "गर्न",
"kartā": "कर्ता",
"kartāram": "कर्ता",
"kartṛtvam": "कर्तृत्व",
"karuṇaḥ": "करुणामय",
"karśayantaḥ": "यातना दिँदै",
"karṇam": "कर्णलाई",
"karṇaḥ": "कर्ण",
"karṣati": "तान्छ",
"kasmāt": "किन",
"kasyacit": "कसैको",
"katarat": "कुन",
"katham": "कसरी",
"kathaya": "भन",
"kathayantaḥ": "बोल्दै",
"kathayataḥ": "बोल्दै",
"kathayiṣyanti": "बोल्नेछन्",
"kathayiṣyāmi": "बताउनेछु",
"kaumāram": "बाल्यावस्था",
"kaunteya": "हे कुन्तीपुत्र",
"kaunteyaḥ": "कौन्तेय",
"kauśalam": "कुशलता",
"kavayaḥ": "कविहरू",
"kavim": "प्राचीन ऋषिलाई",
"kaviḥ": "कवि",
"kavīnām": "कविहरूका",
"kaścana": "कोही",
"kaścit": "कोही",
"kaśmalam": "मोह",
"kaḥ": "को",
"kaṭu": "तितो",
"ke": "कुन",
"kecit": "कोही",
"kena": "केले",
"kenacit": "केही",
"kevalaiḥ": "केवल",
"kevalam": "मात्र",
"keśava": "हे केशव",
"keśavasya": "केशवको",
"keśavārjunayoḥ": "केशव र अर्जुनको",
"keśiniṣūdana": "हे केशिनिषूदन",
"keṣu": "कुनमा",
"kham": "आकाश",
"khe": "आकाशमा",
"kilbiṣaiḥ": "पापहरूबाट",
"kilbiṣam": "पाप",
"kim": "के",
"kirīṭinam": "मुकुटधारी",
"kirīṭī": "मुकुटधारी",
"kiñcana": "केही",
"kiñcit": "केही",
"klaibyam": "कापुरुषता",
"kledayanti": "भिजाउँछन्",
"kleśaḥ": "कष्ट",
"kratur": "क्रतु",
"kriyamāṇāni": "गरिएका",
"kriyante": "गरिन्छन्",
"kriyate": "गरिन्छ",
"kriyaḥ": "जसका क्रियाहरू",
"kriyā": "क्रिया",
"kriyābhiḥ": "क्रियाहरूद्वारा",
"kriyāḥ": "क्रियाहरू",
"krodha": "क्रोध",
"krodham": "क्रोध",
"krodhaḥ": "क्रोध",
"krodhāt": "क्रोधबाट",
"krodhāḥ": "क्रोधहरू",
"krūrān": "क्रूर",
"kula": "कुल",
"kulakṣaya": "कुलको विनाश",
"kulam": "कुल",
"kulasya": "कुलको",
"kule": "कुलमा",
"kuntibhojaḥ": "कुन्तिभोज",
"kuntī": "कुन्तीका",
"kuru": "गर",
"kurunandana": "हे कुरुनन्दन",
"kurupravīra": "हे कुरुप्रवीर",
"kurusattama": "हे कुरुश्रेष्ठ",
"kurute": "गर्छ",
"kuruśreṣṭha": "हे कुरुश्रेष्ठ",
"kuruṣva": "गर",
"kurvan": "गर्दै",
"kurvanti": "गर्छन्",
"kurvāṇaḥ": "गर्दै",
"kuryām": "गर्नुपर्छ",
"kuryāt": "गर्नुपर्छ",
"kurūn": "कुरुहरूलाई",
"kusumākaraḥ": "वसन्त",
"kutaḥ": "कसरी",
"kuśa": "कुश",
"kuśale": "प्रियमा",
"kvacit": "कहिल्यै",
"kā": "के",
"kālam": "काल",
"kālaḥ": "काल",
"kāle": "समयमा",
"kālena": "समयमा",
"kāleṣu": "समयहरूमा",
"kālānalasannibhāni": "कालको आगोजस्ता",
"kām": "के",
"kāma": "कामना",
"kāmabhogeṣu": "इन्द्रियसुखमा",
"kāmabhogārtham": "भोगको तृप्तिका निम्ति",
"kāmadhuk": "कामधेनु",
"kāmahaitukam": "कामनाबाट जन्मेको",
"kāmaiḥ": "कामनाहरूले",
"kāmakrodhaparāyaṇāḥ": "कामना र क्रोधमा समर्पित",
"kāmakāmāḥ": "कामना चाहने",
"kāmakāmī": "कामना चाहने",
"kāmakārataḥ": "कामनाको आवेगले",
"kāmakāreṇa": "कामनाको आवेगले",
"kāmam": "कामना",
"kāmarāgabalānvitāḥ": "कामना र आसक्तिको बलले प्रेरित",
"kāmarāgavivarjitam": "कामना र आसक्तिरहित",
"kāmaḥ": "कामना",
"kāmebhyaḥ": "कामनाहरूबाट",
"kāmepsunā": "कामना चाहनेद्वारा",
"kāmopabhogaparamāḥ": "कामनाको भोगमा तत्पर",
"kāmyānām": "इच्छितका",
"kāmān": "कामनाहरू",
"kāmāt": "कामनाबाट",
"kāmātmānaḥ": "कामनाले भरिएका",
"kāmāḥ": "कामनाहरू",
"kārakaiḥ": "गराउने",
"kārayan": "गराउँदै",
"kāraṇam": "कारण",
"kāraṇāni": "कारणहरू",
"kāraṇāt": "निम्ति",
"kārpaṇya": "कापुरुषताको",
"kāryakaraṇakartṛtve": "कार्य र करणको कर्तृत्वमा",
"kāryam": "गर्नुपर्ने",
"kāryate": "गराइन्छ",
"kārye": "कार्यमा",
"kāryākāryavyavasthitau": "गर्नुपर्ने-नगर्नुपर्नेको निर्णयमा",
"kāryākārye": "कर्तव्य-अकर्तव्य",
"kāya": "शरीर",
"kāyakleśabhayāt": "शारीरिक कष्टको डरले",
"kāyam": "शरीर",
"kāyena": "शरीरले",
"kāñcanaḥ": "सुन",
"kāśyaḥ": "काशीका राजा",
"kāśīrājaḥ": "काशीका राजा",
"kāṅkṣantaḥ": "इच्छा गर्दै",
"kāṅkṣati": "इच्छा गर्छ",
"kāṅkṣe": "इच्छा गर्छु",
"kāṅkṣitam": "इच्छित",
"kīrtayantaḥ": "कीर्तन गर्दै",
"kīrtim": "कीर्ति",
"kīrtiḥ": "कीर्ति",
"kūrmaḥ": "कछुवा",
"kūṭastham": "अचल",
"kūṭasthaḥ": "अचल",
"kṛpayā": "कृपाले",
"kṛpaḥ": "कृप",
"kṛpaṇāḥ": "दयनीय",
"kṛtakṛtyaḥ": "गर्नुपर्ने सबै गरेको",
"kṛtam": "गरिएको",
"kṛtaniścayaḥ": "निश्चय गरेको",
"kṛte": "निम्ति",
"kṛtena": "गरिएकोबाट",
"kṛtsnakarmakṛt": "सबै कर्म गर्ने",
"kṛtsnam": "सम्पूर्ण",
"kṛtsnasya": "सम्पूर्णको",
"kṛtsnavat": "सबै होइनझैं",
"kṛtsnavit": "सम्पूर्ण ज्ञाता",
"kṛtvā": "गरेर",
"kṛtānte": "कर्मको अन्त्यको",
"kṛtāñjaliḥ": "हात जोडेको",
"kṛṣigaurakṣyavāṇijyam": "खेती, गोरु पालन र व्यापार",
"kṛṣṇa": "हे कृष्ण",
"kṛṣṇam": "कृष्णलाई",
"kṛṣṇaḥ": "कृष्ण",
"kṛṣṇāt": "कृष्णबाट",
"kṣamā": "क्षमा",
"kṣamī": "क्षमाशील",
"kṣapita": "भस्म",
"kṣaram": "क्षर",
"kṣaraḥ": "क्षर",
"kṣatriyasya": "क्षत्रियको",
"kṣatriyāḥ": "क्षत्रियहरू",
"kṣayam": "विनाश",
"kṣaye": "नाशमा",
"kṣayāya": "विनाशका निम्ति",
"kṣaṇam": "क्षण",
"kṣemataram": "अझ राम्रो",
"kṣetrajñam": "क्षेत्रज्ञलाई",
"kṣetrajñaḥ": "क्षेत्रज्ञ",
"kṣetrakṣetrajñasaṁyogāt": "क्षेत्र र क्षेत्रज्ञको संयोगबाट",
"kṣetrakṣetrajñayoḥ": "क्षेत्र र क्षेत्रज्ञको",
"kṣetram": "क्षेत्र",
"kṣetre": "क्षेत्रमा",
"kṣetrī": "क्षेत्रज्ञ",
"kṣipram": "छिट्टै",
"kṣipāmi": "हाल्छु",
"kṣitām": "शासकहरूलाई",
"kṣudram": "क्षुद्र",
"kṣāmaye": "क्षमा माग्छु",
"kṣāntiḥ": "धैर्य",
"kṣātram": "क्षत्रियको",
"kṣīṇa": "नष्ट",
"kṣīṇe": "सकिँदा",
"labdham": "प्राप्त",
"labdhvā": "पाएर",
"labdhā": "प्राप्त",
"labhante": "पाउँछन्",
"labhasva": "जित",
"labhate": "प्राप्त गर्दछ",
"labhe": "पाउँछु",
"labhet": "पाउँथ्यो",
"labhyaḥ": "प्राप्त गर्न सकिने",
"laghvāśī": "थोरै खाने",
"lavaṇa": "नुनिलो",
"lelihyase": "चाट्नुहुन्छ",
"limpanti": "टाँसिन्छन्",
"lipyate": "दागिन्छ",
"liṅgaiḥ": "चिह्नहरूले",
"lobha": "लोभ",
"lobhaḥ": "लोभ",
"lobhena": "लोभले",
"loka": "लोक",
"lokakṣayakṛt": "लोकको विनाशकर्ता",
"lokam": "लोक",
"lokamaheśvaram": "संसारका महान् स्वामीलाई",
"lokasya": "संसारको",
"lokatrayam": "तीनै लोक",
"lokatraye": "तीनै लोकमा",
"lokaḥ": "लोक",
"loke": "संसारमा",
"lokeṣu": "लोकहरूमा",
"lokān": "लोकहरू",
"lokāt": "संसारबाट",
"lokāḥ": "लोकहरू",
"lubdhaḥ": "लोभी",
"lupta": "वञ्चित",
"lābha": "लाभ",
"lābham": "लाभ",
"lāghavam": "तुच्छता",
"maccittaḥ": "मन ममा भएको",
"maccittāḥ": "जसका विचार ममा",
"mada": "घमण्ड (ले)",
"madam": "मद",
"madarpaṇam": "मेरो अर्पण",
"madartham": "मेरै निम्ति",
"madbhaktaḥ": "मेरो भक्त",
"madbhakteṣu": "मेरा भक्तहरूमा",
"madbhaktim": "मप्रतिको भक्ति",
"madbhaktāḥ": "मेरा भक्तहरू",
"madbhāvam": "मेरो भाव",
"madbhāvāya": "मेरो भावका निम्ति",
"madbhāvāḥ": "मेरो मनबाट जन्मेका",
"madgataprāṇāḥ": "जीवन मलाई दिइएका",
"madgatena": "ममा स्थिर",
"madhusūdana": "हे मधुसूदन",
"madhusūdanaḥ": "मधुसूदन",
"madhyam": "मध्य",
"madhyastha": "मध्यस्थ",
"madhye": "बीचमा",
"madhyāni": "मध्यका",
"madvyapāśrayaḥ": "मेरो शरण लिने",
"madyogam": "मेरो योग",
"madyājinaḥ": "मेरा पूजकहरू",
"madyājī": "मलाई अर्पण गर्ने",
"madāśrayaḥ": "मेरो शरण लिने",
"maharṣayaḥ": "महर्षिहरू",
"maharṣisiddhasaṅghāḥ": "महर्षि र सिद्धहरूका समूहहरू",
"maharṣīṇām": "महर्षिहरूका",
"mahat": "महान्",
"mahataḥ": "महान्बाट",
"mahati": "महान्मा",
"mahatā": "लामो",
"mahatīm": "महान्",
"maheśvaram": "महेश्वरलाई",
"maheśvaraḥ": "महेश्वर",
"mahimānam": "महिमा",
"mahā": "महान्",
"mahābhūtāni": "महाभूतहरू",
"mahābāho": "हे महाबाहो",
"mahān": "महान्",
"mahānubhāvān": "महानुभावहरूलाई",
"mahārathāḥ": "महारथीहरू",
"mahātman": "हे महात्मा",
"mahātmanaḥ": "महात्माको",
"mahātmā": "महात्मा",
"mahātmānaḥ": "महात्माहरू",
"mahāyogeśvaraḥ": "महान् योगेश्वर",
"mahī": "पृथ्वी",
"mahīm": "पृथ्वीलाई",
"mahīpate": "हे पृथ्वीपति",
"maitraḥ": "मित्रवत्",
"makaraḥ": "मकर",
"malena": "धुलोले",
"mama": "मेरो",
"manasam": "मनको",
"manasaḥ": "मनभन्दा",
"manasā": "मनले",
"manavaḥ": "मनुहरू",
"manave": "मनुलाई",
"manaḥ": "मन",
"manaḥprasādaḥ": "मनको प्रसन्नता",
"manaḥprāṇendriyakriyāḥ": "मन, प्राण र इन्द्रियका क्रियाहरू",
"manaḥṣaṣṭhāni": "मन छैठौं भएका",
"mandān": "मन्दबुद्धिहरूलाई",
"manmanāḥ": "मन ममा लगाउने",
"manmayāḥ": "ममा लीन",
"manobuddhiḥ": "मन र बुद्धि",
"manogatān": "मनका",
"manoratham": "इच्छा",
"mantavyaḥ": "मान्नुपर्ने",
"mantrahīnam": "मन्त्ररहित",
"mantraḥ": "मन्त्र",
"manuḥ": "मनु",
"manuṣyaloke": "मानव लोकमा",
"manuṣyeṣu": "मानिसहरूमा",
"manuṣyāḥ": "मानिसहरू",
"manuṣyāṇām": "मानिसहरूका",
"manyante": "सोच्छन्",
"manyase": "सोच्छौ",
"manyate": "सोच्छ",
"manye": "म ठान्छु",
"manyeta": "सोच्थ्यो",
"manāḥ": "जसको मन",
"manīṣiṇaḥ": "ज्ञानीहरू",
"manīṣiṇām": "ज्ञानीहरूका",
"maraṇa": "मृत्यु",
"maraṇāt": "मृत्युभन्दा",
"martyalokam": "मर्त्यलोक",
"martyeṣu": "मर्त्यहरूमा",
"marutaḥ": "मरुत्हरू",
"marutām": "मरुत्हरूका",
"marīciḥ": "मरीचि",
"mat": "मेरो",
"matam": "मत",
"mataḥ": "मानिन्छ",
"mate": "विचारमा",
"matiḥ": "बुद्धि",
"matkarmakṛt": "मेरो कर्म गर्ने",
"matkarmaparamaḥ": "मेरा निम्ति कर्ममा तत्पर",
"matparamaḥ": "मलाई परम मान्ने",
"matparamāḥ": "मलाई परम मान्ने",
"matparaḥ": "मलाई परम मान्ने",
"matparāyaṇaḥ": "ममै तत्पर",
"matparāḥ": "ममै तत्पर",
"matprasādāt": "मेरो कृपाले",
"matsaṁsthām": "ममा रहने",
"matsthāni": "ममा रहेका",
"mattaḥ": "मबाट",
"matvā": "सोचेर",
"matā": "मानिन्छ",
"matāḥ": "मानिन्छन्",
"maunam": "मौनता",
"maunī": "मौनी",
"mayi": "ममा",
"mayā": "मद्वारा",
"maṁsyante": "सोच्नेछन्",
"maṇigaṇāḥ": "मोतीहरूको माला",
"me": "मेरो",
"medhā": "मेधा",
"medhāvī": "मेधावी",
"meruḥ": "मेरु",
"mithyā": "व्यर्थ",
"mithyācāraḥ": "कपटी",
"mitra": "मित्र",
"mitre": "मित्रमा",
"mitrāripakṣayoḥ": "मित्र-शत्रुमा",
"miśram": "मिश्रित",
"modiṣye": "रम्नेछु",
"moghajñānāḥ": "व्यर्थ ज्ञान भएका",
"moghakarmāṇaḥ": "व्यर्थ कर्म गर्ने",
"mogham": "व्यर्थ",
"moghāśāḥ": "व्यर्थ आशा भएका",
"mohajālasamāvṛtāḥ": "मोहको जालले ढाकिएका",
"mohakalilam": "मोहको हिलो",
"moham": "मोह",
"mohanam": "मोहित पार्ने",
"mohayasi": "अलमल्याउँछौ",
"mohaḥ": "मोह",
"mohinīm": "मोहित गर्ने",
"mohitam": "मोहित",
"mohitāḥ": "मोहित",
"mohāt": "मोहबाट",
"mokṣa": "मुक्तिको",
"mokṣakāṅkṣibhiḥ": "मुक्ति चाहनेहरूद्वारा",
"mokṣam": "मुक्ति",
"mokṣayiṣyāmi": "मुक्त गर्नेछु",
"mokṣyase": "मुक्त हुनेछौ",
"mokṣāya": "मुक्तिका निम्ति",
"mriyate": "मर्छ",
"mucyante": "मुक्त हुन्छन्",
"muhurmuhuḥ": "बारम्बार",
"muhyanti": "मोहित हुन्छन्",
"muhyati": "मोहित हुन्छ",
"mukham": "मुख",
"mukhe": "मुखमा",
"mukhyam": "मुख्य",
"mukhāni": "मुखहरू",
"mukta": "मुक्त",
"muktam": "मुक्त",
"muktasaṅgaḥ": "आसक्तिमुक्त",
"muktasya": "मुक्तको",
"muktaḥ": "मुक्त",
"muktvā": "त्यागेर",
"mumukṣubhiḥ": "मुक्तिका खोजीहरूद्वारा",
"munayaḥ": "ऋषिहरू",
"muneḥ": "मुनिको",
"muniḥ": "मुनि",
"munīnām": "ऋषिहरूका",
"mā": "नगर",
"mādhava": "हे माधव",
"mādhavaḥ": "माधव",
"māhātmyam": "महिमा",
"mām": "मलाई",
"māmakam": "मेरो",
"māmakāḥ": "मेरा मानिसहरू",
"māmikām": "मेरो",
"māna": "मान",
"mānasam": "मनको",
"mānasaḥ": "मन",
"mānasāḥ": "मानसिक",
"mānavaḥ": "मानिस",
"mānavāḥ": "मानिसहरू",
"mānuṣam": "मानव",
"mānuṣe": "मानवमा",
"mānuṣīm": "मानवीय",
"mānāpamānayoḥ": "मान-अपमानमा",
"mārdavam": "कोमलता",
"mārgaśīrṣaḥ": "मार्गशीर्ष",
"mārutaḥ": "वायु",
"māsānām": "महिनाहरूका",
"mātrā": "विषयहरू",
"mātulān": "मामाहरूलाई",
"mātulāḥ": "मामाहरू",
"mātā": "माता",
"māyayā": "मायाद्वारा",
"māyā": "माया",
"māyām": "यो माया",
"mūlam": "जरा",
"mūlāni": "जराहरू",
"mūrdhni": "शिरमा",
"mūrtayaḥ": "रूपहरू",
"mūḍhagrāheṇa": "मूर्ख हठले",
"mūḍhayoniṣu": "मोहितहरूका योनिमा",
"mūḍhaḥ": "मूर्ख",
"mūḍhāḥ": "मोहितहरू",
"mṛgendraḥ": "सिंह",
"mṛgāṇām": "पशुहरूका",
"mṛtam": "मरेको",
"mṛtasya": "मरेकाको",
"mṛtyum": "मृत्यु",
"mṛtyusaṁsārasāgarāt": "जन्म-मृत्युको सागरबाट",
"mṛtyusaṁsāravartmani": "मृत्यु र पुनर्जन्मको बाटोमा",
"mṛtyuḥ": "मृत्यु",
"na": "न",
"nabhaḥ": "आकाश",
"nabhaḥspṛśam": "आकाश छुने",
"nacireṇa": "छिट्टै",
"nadīnām": "नदीहरूका",
"naikṛtikaḥ": "दुष्ट",
"naiṣkarmyam": "नैष्कर्म्य",
"naiṣkarmyasiddhim": "नैष्कर्म्यसिद्धि",
"naiṣṭhikīm": "स्थायी",
"nakulaḥ": "नकुल",
"nakṣatrāṇām": "नक्षत्रहरूका",
"namaskuru": "नमस्कार गर",
"namaskṛtvā": "नमस्कार गरेर",
"namasyantaḥ": "नमस्कार गर्दै",
"namasyanti": "नमस्कार गर्छन्",
"namaḥ": "नमस्कार",
"nameran": "झुक्थे",
"naraiḥ": "मानिसहरूद्वारा",
"narakasya": "नरकको",
"narake": "नरकमा",
"narakāya": "नरकका निम्ति",
"naralokavīrāḥ": "मर्त्यलोकका वीरहरू",
"narapuṅgavaḥ": "नरश्रेष्ठ",
"naraḥ": "मानिस",
"narādhamān": "नराधमहरूलाई",
"narādhamāḥ": "नराधमहरू",
"narādhipam": "राजालाई",
"narāṇām": "मानिसहरूका",
"navadvāre": "नौ ढोकाको",
"navāni": "नयाँ",
"nayet": "लैजानुपर्छ",
"naśyati": "नष्ट हुन्छ",
"naśyatsu": "नष्ट हुँदा",
"naḥ": "हामी",
"naṣṭaḥ": "नष्ट",
"naṣṭe": "नष्ट हुँदा",
"naṣṭān": "नष्ट",
"naṣṭātmānaḥ": "नष्ट आत्माहरू",
"neha": "यहाँ होइन",
"neṅgate": "चलमलाउँदैन",
"nibaddhaḥ": "बाँधिएको",
"nibadhnanti": "बाँध्छन्",
"nibadhnāti": "बाँध्छ",
"nibadhyate": "बाँधिन्छ",
"nibandhāya": "बन्धनका निम्ति",
"nibodha": "जान",
"nidhanam": "मृत्यु",
"nidhanāni": "अन्त्य हुने",
"nidhānam": "आश्रय",
"nidrālasyapramādottham": "निद्रा, आलस्य र प्रमादबाट जन्मेको",
"nigacchati": "पुग्छ",
"nigraham": "संयम",
"nigrahaḥ": "संयम",
"nigṛhītāni": "रोकिएका",
"nigṛhṇāmi": "रोक्छु",
"nihatya": "मारेर",
"nihatāḥ": "मारिएका",
"nimittamātram": "मात्र साधन",
"nimittāni": "शकुनहरू",
"nimiṣan": "आँखा चिम्लिँदै",
"nindantaḥ": "निन्दा गर्ने",
"nindā": "निन्दा",
"niragniḥ": "अग्निरहित",
"nirahaṅkāraḥ": "अहंकाररहित",
"nirdeśaḥ": "पदनाम",
"nirdhūta": "धोइएको",
"nirdoṣam": "निर्दोष",
"nirdvandvaḥ": "द्वन्द्वरहित",
"nirguṇam": "गुणरहित",
"nirguṇatvāt": "गुणरहित भएर",
"nirmalam": "निर्मल",
"nirmalatvāt": "शुद्धताले",
"nirmamaḥ": "निर्मम",
"nirmānamohāḥ": "अभिमान र मोहरहित",
"niruddham": "रोकिएको",
"nirudhya": "रोकेर",
"nirvairaḥ": "द्वेषरहित",
"nirvedam": "वैराग्य",
"nirvikāraḥ": "विकाररहित",
"nirvāṇaparamām": "परम निर्वाण",
"niryogakṣemaḥ": "लाभ-हानिभन्दा पर",
"nirāhārasya": "निराहारको",
"nirāśrayaḥ": "आश्रयरहित",
"nirāśīḥ": "निःस्पृह",
"nirīkṣe": "हेरूँ",
"nistraiguṇyaḥ": "त्रिगुणातीत",
"nitya": "नित्य",
"nityajātam": "नित्य जन्मने",
"nityam": "सधैँ",
"nityasannyāsī": "सदा संन्यासी",
"nityasattvasthaḥ": "सधैं सत्त्वमा स्थित",
"nityasya": "नित्यको",
"nityatṛptaḥ": "सधैं सन्तुष्ट",
"nityayuktasya": "सधैं युक्तको",
"nityayuktaḥ": "सधैं युक्त",
"nityayuktāḥ": "सधैं युक्त",
"nityaśaḥ": "निरन्तर",
"nityaḥ": "नित्य",
"nityābhiyuktānām": "सधैं समर्पितहरूका",
"nivartante": "फर्कन्छन्",
"nivartanti": "फर्कन्छन्",
"nivartate": "फर्कन्छ",
"nivartitum": "फर्कन",
"nivasiṣyasi": "बाँच्नेछौ",
"niveśaya": "स्थिर गर",
"nivāsaḥ": "निवास",
"nivātasthaḥ": "हावा नभएको ठाउँमा",
"nivṛttim": "अकर्म",
"nivṛttāni": "शान्त",
"niyamam": "नियम",
"niyamya": "नियन्त्रण गरेर",
"niyata": "नियमित",
"niyatam": "विहित",
"niyatamānasaḥ": "संयत मनको",
"niyatasya": "विहितको",
"niyatātmabhiḥ": "आत्मसंयमीहरूद्वारा",
"niyatāḥ": "नियन्त्रित",
"niyojayasi": "लगाउँछौ",
"niyojitaḥ": "प्रेरित",
"niyokṣyati": "बाध्य गर्नेछ",
"niścalā": "अचल",
"niścarati": "भड्किन्छ",
"niścayam": "निष्कर्ष",
"niścayena": "दृढ संकल्पले",
"niścitam": "निश्चित",
"niścitya": "निश्चय गरेर",
"niścitāḥ": "निश्चय गरेका",
"niśā": "रात",
"niḥspṛhaḥ": "निःस्पृह",
"niḥśreyasakarau": "परम हित गर्ने",
"niṣṭhā": "निष्ठा",
"nu": "नै",
"nyāsam": "त्याग",
"nyāyyam": "उचित",
"nādam": "गर्जन",
"nāgānām": "सर्पहरूका",
"nāhaṁkṛto": "अहंकाररहित",
"nāmayajñaiḥ": "नाममात्रका यज्ञले",
"nānā": "विविध",
"nānābhāvān": "विविध प्राणीहरूलाई",
"nānāvarṇākṛtīni": "विविध रङ्ग र आकारका",
"nānāvidhāni": "विविध प्रकारका",
"nāradaḥ": "नारद",
"nārīṇām": "स्त्रीहरूका",
"nāsikāgram": "नासिकाको अग्रभाग",
"nāsā": "नासिकाका",
"nātimānitā": "अभिमानरहितता",
"nāvam": "डुङ्गा",
"nāyakāḥ": "नेताहरू",
"nāyam": "यो होइन",
"nāśanam": "नाशक",
"nāśayāmi": "नष्ट गर्छु",
"nāśaḥ": "नाश",
"nāśitam": "नष्ट",
"nāśāya": "विनाशका निम्ति",
"nīcam": "नीच",
"nītiḥ": "नीति",
"nṛloke": "मानव लोकमा",
"nṛṣu": "मानिसहरूमा",
"ojasā": "शक्तिले",
"om": "ॐ",
"oṅkāraḥ": "ॐकार",
"pacanti": "पकाउँछन्",
"pacāmi": "पचाउँछु",
"padam": "स्थान",
"padmapatram": "कमलको पात",
"pakṣiṇām": "चराहरूका",
"para": "अर्काको",
"paradharmāt": "पराया धर्मभन्दा",
"param": "परम",
"parama": "परम",
"paramam": "परम",
"paramaḥ": "परम",
"parameśvara": "हे परमेश्वर",
"parameśvaram": "परमेश्वरलाई",
"paramparā": "परम्परा",
"paramām": "परम",
"paramātmā": "परमात्मा",
"parantapa": "हे परन्तप",
"parasparam": "परस्पर",
"parastāt": "पार",
"parasya": "अर्काको",
"parataram": "उच्च",
"parataḥ": "पर",
"parayā": "परम",
"paraḥ": "परम",
"paraṁtapa": "हे परन्तप",
"paricakṣate": "भनिन्छ",
"paricaryātmakam": "सेवाको स्वभावको",
"paricintayan": "चिन्तन गर्दै",
"paridahyate": "बल्छ",
"paridevanā": "विलाप",
"parigraham": "ममता",
"parigrahaḥ": "परिग्रह",
"parijñātā": "ज्ञाता",
"parikliṣṭam": "अनिच्छाले",
"parikīrtitaḥ": "भनिएको",
"parimārgitavyam": "खोज्नुपर्छ",
"paripanthinau": "बाटो छेक्ने",
"paripraśnena": "प्रश्नद्वारा",
"parisamāpyate": "पर्यवसान हुन्छ",
"paritrāṇāya": "रक्षाका निम्ति",
"parityajya": "त्यागेर",
"parityāgaḥ": "त्याग",
"pariśuṣyati": "सुक्छ",
"pariṇāme": "अन्त्यमा",
"parjanyaḥ": "वर्षा",
"parjanyāt": "वर्षाबाट",
"paryavatiṣṭhate": "स्थापित हुन्छ",
"paryupāsate": "अनुसरण गर्छन्",
"paryuṣitam": "बासी",
"paryāptam": "पर्याप्त",
"parā": "परा",
"parām": "परम",
"parāyaṇaḥ": "तत्पर",
"parāyaṇāḥ": "समर्पित",
"parāṇi": "उच्च",
"parṇāni": "पातहरू",
"patanti": "झर्छन्",
"pataṅgāḥ": "पुतलीहरू",
"pate": "हे प्रभु",
"pathi": "बाटोमा",
"patiḥ": "स्वामी",
"patram": "पात",
"pauruṣam": "आफ्नो क्षमता",
"paurvadehikam": "पूर्वशरीरको",
"pautrān": "नातिहरूलाई",
"pautrāḥ": "नातिहरू",
"pauṇḍram": "पौण्ड्र",
"pavanaḥ": "वायु",
"pavatām": "पवित्र गर्नेहरूमा",
"pavitram": "पवित्रकर्ता",
"pañca": "पाँच",
"pañcamam": "पाँचौं",
"paśya": "हेर",
"paśyan": "देख्दै",
"paśyanti": "देख्छन्",
"paśyataḥ": "हेर्नेको",
"paśyati": "देख्छ",
"paśyet": "देख्थ्यो",
"paśyāmi": "देख्छु",
"paṇava": "तुरहीहरू",
"paṇḍitam": "पण्डितलाई",
"paṇḍitāḥ": "ज्ञानीहरू",
"phala": "फल",
"phalahetavaḥ": "फलको खोजी गर्ने",
"phalam": "फल",
"phale": "फलमा",
"phaleṣu": "फलहरूमा",
"phalākāṅkṣī": "फल चाहने",
"phalāni": "फलहरू",
"pitaraḥ": "पितृहरू",
"pitā": "पिता",
"pitāmahaḥ": "पितामह",
"pitāmahān": "पितामहहरूलाई",
"pitāmahāḥ": "पितामहहरू",
"pitṛvratāḥ": "पितृ-पूजकहरू",
"pitṝn": "पितृहरूलाई",
"pitṝṇām": "पितृहरूका",
"piṇḍa": "पिण्ड",
"plavena": "डुङ्गाले",
"prabhavam": "उत्पत्ति",
"prabhavanti": "उत्पन्न हुन्छन्",
"prabhavati": "उत्पन्न हुन्छ",
"prabhavaḥ": "स्रोत",
"prabhaviṣṇu": "स्रष्टा",
"prabhavān": "जन्मेको",
"prabho": "हे प्रभु",
"prabhuḥ": "प्रभु",
"prabhā": "प्रभा",
"prabhāṣeta": "बोल्थ्यो",
"pradadhmatuḥ": "बजाए",
"pradigdhān": "लतपतिएका",
"pradiṣṭam": "घोषणा गरिएको",
"praduṣyanti": "भ्रष्ट हुन्छन्",
"pradviṣantaḥ": "घृणा गर्ने",
"pradām": "दिने",
"pradāḥ": "दिने",
"pradīptam": "बलेको",
"praharaṇāḥ": "हतियारधारी",
"prahasan": "मुस्कुराउँदै",
"prahlādaḥ": "प्रह्लाद",
"prahāsyasi": "त्याग्नेछौ",
"prahṛṣyati": "रम्छ",
"prahṛṣyet": "रम्थ्यो",
"prajahihi": "त्याग",
"prajahāti": "त्याग्छ",
"prajanaḥ": "जन्म दिने",
"prajñā": "प्रज्ञा",
"prajñām": "समझ",
"prajñāvādān": "ज्ञानका वचन",
"prajā": "प्राणीहरूका",
"prajānāmi": "बुझ्छु",
"prajānāti": "जान्दछ",
"prajāpatiḥ": "प्रजापति",
"prajāḥ": "प्राणीहरू",
"prakāśakam": "प्रकाश दिने",
"prakāśam": "प्रकाश",
"prakāśayati": "प्रकाशित गर्छ",
"prakāśaḥ": "प्रकाश",
"prakīrtyā": "कीर्तिले",
"prakṛteḥ": "प्रकृतिको",
"prakṛti": "प्रकृतिको",
"prakṛtijaiḥ": "प्रकृतिबाट जन्मेका",
"prakṛtijān": "प्रकृतिबाट जन्मेका",
"prakṛtim": "प्रकृतिलाई",
"prakṛtisambhavān": "प्रकृतिबाट जन्मेका",
"prakṛtisambhavāḥ": "प्रकृतिबाट जन्मेका",
"prakṛtisthaḥ": "प्रकृतिमा बसेको",
"prakṛtisthāni": "प्रकृतिमा रहने",
"prakṛtiḥ": "प्रकृति",
"prakṛtyā": "प्रकृतिद्वारा",
"pralapan": "बोल्दै",
"pralayam": "मृत्यु",
"pralayaḥ": "विनाश",
"pralaye": "विनाशमा",
"pralayāntām": "मृत्युमा समाप्त हुने",
"pralīnaḥ": "विलीन",
"pralīyante": "विलीन हुन्छन्",
"pralīyate": "विलीन हुन्छ",
"pramucyate": "मुक्त हुन्छ",
"pramukhataḥ": "अगुवाइमा",
"pramukhe": "अगाडि",
"pramādamohau": "प्रमाद र मोह",
"pramādaḥ": "प्रमाद",
"pramāde": "प्रमादमा",
"pramādālasyanidrābhiḥ": "प्रमाद, आलस्य र निद्राले",
"pramādāt": "प्रमादबाट",
"pramāthi": "चञ्चल",
"pramāthīni": "चञ्चल",
"pramāṇam": "प्रमाण",
"prapadyante": "शरण लिन्छन्",
"prapadyate": "शरण लिन्छ",
"prapadye": "शरण लिन्छु",
"prapannam": "शरण परेको",
"prapaśya": "हेर",
"prapaśyadbhiḥ": "देख्नेहरूद्वारा",
"prapaśyāmi": "देख्छु",
"prapitāmahaḥ": "पितामह",
"prasabham": "बलपूर्वक",
"prasaktānām": "आसक्तहरूका",
"prasaktāḥ": "समर्पित",
"prasannacetasaḥ": "प्रसन्न मनका",
"prasannena": "प्रसन्न भएर",
"prasannātmā": "प्रसन्न आत्मा",
"prasaviṣyadhvam": "फस्टाउनेछौ",
"prasaṅgena": "आसक्तिसँग",
"prasidhyet": "सफल हुन्थ्यो",
"prasādam": "प्रसन्नता",
"prasādaye": "कृपा माग्छु",
"prasāde": "प्रसन्नतामा",
"prasīda": "कृपा गर्नुहोस्",
"prasṛtā": "बगेको",
"prasṛtāḥ": "फैलिएका",
"pratapanti": "बल्छन्",
"prathitaḥ": "प्रसिद्ध",
"prati": "प्रति",
"pratijāne": "वचन दिन्छु",
"pratijānīhi": "निश्चय जान",
"pratipadyate": "प्राप्त गर्छ",
"pratiyotsyāmi": "लड्नेछु",
"pratiṣṭham": "स्थापित",
"pratiṣṭhitam": "स्थापित",
"pratiṣṭhitā": "स्थापित",
"pratiṣṭhā": "आधार",
"pratiṣṭhāpya": "स्थापित गरेर",
"pratyakṣāvagamam": "प्रत्यक्ष अनुभवयोग्य",
"pratyanīkeṣu": "विपक्षी पङ्क्तिहरूमा",
"pratyavāyaḥ": "उल्टो फल",
"pratyupakārārtham": "बदला अपेक्षा गरेर",
"pratāpavān": "तेजस्वी",
"pratīkāram": "रोकथाम",
"pravadanti": "भन्छन्",
"pravadatām": "वादीहरूमा",
"pravakṣye": "बताउनेछु",
"pravakṣyāmi": "बताउनेछु",
"pravartante": "सुरु हुन्छन्",
"pravartate": "अघि बढ्छ",
"pravartitam": "चलाइएको",
"praveṣṭum": "प्रवेश गर्न",
"pravibhaktam": "विभाजित",
"pravibhaktāni": "विभाजित",
"pravilīyate": "विलीन हुन्छ",
"praviśanti": "प्रवेश गर्छन्",
"pravyathitam": "कामेको",
"pravyathitāntarātmā": "काँप्दो हृदय भएको",
"pravyathitāḥ": "काँपेका",
"pravṛddhaḥ": "परिपक्व",
"pravṛddhe": "बढ्दा",
"pravṛttaḥ": "लागेको",
"pravṛtte": "सुरु हुँदा",
"pravṛttim": "प्रवृत्ति",
"pravṛttiḥ": "प्रवृत्ति",
"prayacchati": "दिन्छ",
"prayatnāt": "प्रयत्नले",
"prayatātmanaḥ": "शुद्ध हृदयको",
"prayujyate": "प्रयोग हुन्छ",
"prayuktaḥ": "प्रेरित",
"prayāti": "जान्छ",
"prayātāḥ": "जाने",
"prayāṇakāle": "मृत्युकालमा",
"praśaste": "शुभमा",
"praśānta": "शान्त",
"praśāntasya": "शान्तको",
"praśāntātmā": "शान्त आत्मा भएको",
"praṇamya": "नमस्कार गरेर",
"praṇavaḥ": "प्रणव",
"praṇayena": "स्नेहले",
"praṇaśyanti": "नष्ट हुन्छन्",
"praṇaśyati": "नष्ट हुन्छ",
"praṇaśyāmi": "हराउँछु",
"praṇaṣṭaḥ": "नष्ट",
"praṇidhāya": "निहुरेर",
"praṇipātena": "प्रणिपातद्वारा",
"pretya": "मृत्युपछि",
"pretān": "प्रेतहरूलाई",
"priya": "प्रिय गर्न",
"priyahitam": "प्रिय र हितकारी",
"priyakṛttamaḥ": "अझ बढी सेवा गर्ने",
"priyam": "प्रिय",
"priyataraḥ": "अझ प्रिय",
"priyaḥ": "प्रिय",
"priyāyāḥ": "प्रियतमाको",
"priyāḥ": "प्रियहरू",
"procyamānam": "भनिइरहेको",
"procyate": "भनिन्छ",
"proktam": "भनिएको",
"proktavān": "सिकाएको",
"proktaḥ": "वर्णन गरिएको",
"proktā": "भनिएको",
"proktāni": "भनिएका",
"protam": "गाँसिएको",
"prādhānyataḥ": "मुख्य रूपमा",
"prāha": "भने",
"prāhuḥ": "भन्छन्",
"prājña": "ज्ञानी",
"prāk": "पहिले",
"prākṛtaḥ": "असभ्य",
"prāpnuvanti": "पुग्छन्",
"prāpnuyāt": "प्राप्त गर्थ्यो",
"prāpsyasi": "प्राप्त गर्नेछौ",
"prāpsye": "प्राप्त गर्नेछु",
"prāptam": "प्राप्त",
"prāptaḥ": "प्राप्त गरेको",
"prāptiḥ": "प्राप्ति",
"prāpya": "पाएर",
"prāpyate": "प्राप्त गरिन्छ",
"prārabhate": "सुरु गर्छ",
"prārthayante": "माग्छन्",
"prāñjalayaḥ": "हात जोडेर",
"prāṇa": "प्राणका",
"prāṇam": "प्राण",
"prāṇe": "प्राणमा",
"prāṇeṣu": "प्राणहरूमा",
"prāṇinām": "प्राणीहरूका",
"prāṇān": "प्राणहरू",
"prāṇāpānasamāyuktaḥ": "प्राण र अपानसँग युक्त",
"prāṇāpānau": "प्राण र अपान",
"prāṇāyāma": "प्राणायाम",
"prītamanāḥ": "प्रसन्न हृदय",
"prīti": "प्रसन्नता",
"prītipūrvakam": "प्रेमसाथ",
"prītiḥ": "प्रीति",
"prīyamāṇāya": "प्रियलाई",
"pumān": "पुरुष",
"punarāvartinaḥ": "फर्कने",
"punaḥ": "फेरि",
"purastāt": "अगाडिबाट",
"pure": "सहरमा",
"purodhasām": "पुरोहितहरूका",
"purujit": "पुरुजित्",
"puruṣam": "पुरुषलाई",
"puruṣarṣabha": "हे नरर्षभ",
"puruṣasya": "पुरुषको",
"puruṣau": "दुई पुरुष",
"puruṣavyāghra": "हे नरश्रेष्ठ",
"puruṣaḥ": "पुरुष",
"puruṣottama": "हे पुरुषोत्तम",
"puruṣottamam": "पुरुषोत्तमलाई",
"puruṣottamaḥ": "पुरुषोत्तम",
"puruṣāḥ": "मानिसहरू",
"purā": "पहिले",
"purātanaḥ": "प्राचीन",
"purāṇam": "पुरातन",
"purāṇaḥ": "पुरातन",
"purāṇī": "पुरातन",
"putradāragṛhādiṣu": "छोरा, पत्नी, घर आदिमा",
"putrasya": "छोराको",
"putraḥ": "छोरा",
"putreṇa": "छोराद्वारा",
"putrān": "छोराहरूलाई",
"putrāḥ": "छोराहरू",
"putrāṇām": "छोराहरूका",
"puṁsaḥ": "पुरुषको",
"puṇyakarmaṇām": "सत्कर्मीहरूका",
"puṇyakṛtām": "सत्कर्मीहरूका",
"puṇyam": "पवित्र",
"puṇyaphalam": "पुण्यफल",
"puṇyaḥ": "पवित्र",
"puṇye": "पुण्यमा",
"puṇyāḥ": "पवित्र",
"puṣkalābhiḥ": "प्रशस्त",
"puṣpam": "फूल",
"puṣpitām": "फुलवारी",
"puṣṇāmi": "पोषण गर्छु",
"pāpakṛt": "पापी",
"pāpam": "पाप",
"pāpayonayaḥ": "पापी जन्मका",
"pāpebhyaḥ": "पापीहरूमा",
"pāpena": "पापले",
"pāpeṣu": "पापीहरूमा",
"pāpmā": "पापी",
"pāpmānam": "यस पापीलाई",
"pāpāt": "पापबाट",
"pāpāḥ": "पापीहरू",
"pārtha": "हे पार्थ",
"pārthasya": "पार्थको",
"pārthaḥ": "पार्थ",
"pārthāya": "पार्थलाई",
"pāruṣyam": "कठोरता",
"pātakam": "पाप",
"pātre": "योग्य व्यक्तिलाई",
"pāvakaḥ": "अग्नि",
"pāvanāni": "पवित्र गर्नेहरू",
"pāñcajanyam": "पाञ्चजन्य",
"pāṇayaḥ": "हातमा",
"pāṇipādam": "हात-खुट्टा",
"pāṇḍava": "हे पाण्डव",
"pāṇḍavaḥ": "पाण्डव",
"pāṇḍavānām": "पाण्डवहरूका",
"pāṇḍavāḥ": "पाण्डवहरू",
"pāṇḍu": "पाण्डुका",
"pīḍayā": "यातनाले",
"pūjanam": "पूजा",
"pūjyaḥ": "पूजनीय",
"pūjārhau": "पूजनीय",
"pūjārtham": "पूजाका निम्ति",
"pūreṇa": "भर्न",
"pūruṣaḥ": "पुरुष",
"pūrvaiḥ": "पूर्वजहरूद्वारा",
"pūrvam": "पहिले नै",
"pūrvataram": "पहिले",
"pūrve": "प्राचीन",
"pūrvābhyāsena": "पूर्वाभ्यासले",
"pūtapāpāḥ": "पापबाट शुद्ध",
"pūti": "गलेको",
"pūtāḥ": "शुद्ध",
"pṛcchāmi": "सोध्छु",
"pṛthagvidham": "विविध प्रकारको",
"pṛthagvidhān": "विविध प्रकारका",
"pṛthagvidhāḥ": "विविध प्रकारका",
"pṛthak": "अलग",
"pṛthak pṛthak": "छुट्टाछुट्टै",
"pṛthakceṣṭāḥ": "छुट्टाछुट्टै प्रयासहरू",
"pṛthaktvena": "छुट्टाछुट्टै",
"pṛthivyām": "पृथ्वीमा",
"pṛthivī": "पृथ्वीको",
"pṛthivīm": "पृथ्वीलाई",
"pṛṣṭhataḥ": "पछाडिबाट",
"rahasi": "एकान्तमा",
"rahasyam": "रहस्य",
"rajasam": "जसको रज",
"rajasaḥ": "रजबाट",
"rajasi": "रजमा",
"rajaḥ": "रज",
"rakṣāṁsi": "राक्षसहरू",
"ramanti": "रम्छन्",
"ramate": "रम्छ",
"rasanam": "रसना",
"rasavarjam": "रस बाहेक",
"rasaḥ": "रस",
"rasyāḥ": "रसिलो",
"rasātmakaḥ": "रसस्वरूप",
"ratha": "रथहरूको",
"ratham": "रथ",
"rathaḥ": "रथी",
"rathopastha": "रथको आसन",
"ratiḥ": "रुचि",
"ratāḥ": "रम्ने",
"raviḥ": "सूर्य",
"raṇa": "युद्धको",
"raṇe": "युद्धमा",
"raṇāt": "युद्धबाट",
"ripuḥ": "शत्रु",
"roma": "रौं",
"romaharṣaṇam": "रोमाञ्चक",
"ruddhvā": "रोकेर",
"rudhira": "रगतले",
"rudrādityāḥ": "रुद्र र आदित्यहरू",
"rudrān": "रुद्रहरूलाई",
"rudrāṇām": "रुद्रहरूका",
"rāga": "आसक्ति",
"rāgadveṣau": "राग-द्वेष",
"rāgātmakam": "रागको स्वभाव भएको",
"rāgī": "रागी",
"rājaguhyam": "राजगुह्य",
"rājan": "हे राजन्",
"rājarṣayaḥ": "राजर्षिहरू",
"rājasam": "राजस",
"rājasasya": "राजसको",
"rājasaḥ": "राजस",
"rājasāḥ": "राजसहरू",
"rājasī": "राजसी",
"rājavidyā": "राजविद्या",
"rājya": "राज्य",
"rājyam": "राज्य",
"rājyasya": "राज्यको",
"rājyena": "राज्यसँग",
"rājā": "राजा",
"rākṣasīm": "राक्षसी",
"rāmaḥ": "राम",
"rātrim": "रात",
"rātriḥ": "रात",
"rātryāgame": "रातको आगमनमा",
"rūkṣa": "सुक्खा",
"rūpam": "रूप",
"rūpasya": "रूपको",
"rūpeṇa": "रूपले",
"rūpāṇi": "रूपहरू",
"sa": "सहित",
"sacarācaram": "चर-अचर",
"sacetāḥ": "सचेत",
"sadbhāve": "सत्ताको अर्थमा",
"sadoṣam": "दोषसहित",
"sadā": "सधैँ",
"sadṛśam": "बराबर",
"sadṛśaḥ": "जस्तो",
"sadṛśī": "समान",
"sagadgadam": "अवरुद्ध स्वरमा",
"saha": "सँग",
"sahadevaḥ": "सहदेव",
"sahajam": "सहज",
"sahasrabāho": "हे सहस्रबाहु",
"sahasrakṛtvaḥ": "हजार पटक",
"sahasrayugaparyantam": "हजार युगसम्म",
"sahasraśaḥ": "हजारौं",
"sahasreṣu": "हजारौंमा",
"sahasā": "अचानक",
"sainyasya": "सेनाको",
"sajjante": "टाँसिन्छन्",
"sajjate": "आसक्त हुन्छ",
"sakhe": "हे मित्र",
"sakhyuḥ": "मित्रको",
"sakhā": "मित्र",
"sakhīn": "मित्रहरूलाई",
"saktam": "आसक्त",
"saktaḥ": "आसक्त",
"saktāḥ": "आसक्त",
"sama": "समान",
"samabuddhayaḥ": "समान बुद्धि भएका",
"samabuddhiḥ": "समान बुद्धि भएको",
"samacittatvam": "समचित्तता",
"samadarśanaḥ": "समान देख्ने",
"samadarśinaḥ": "समान दृष्टि भएका",
"samadhigacchati": "पुग्छ",
"samaduḥkhasukhaḥ": "सुख-दुःखमा समान",
"samagram": "सम्पूर्ण",
"samagrān": "सबै",
"samaloṣṭa": "माटोझैं",
"samaloṣṭāśmakāñcanaḥ": "माटो, ढुङ्गा र सुन समान देख्ने",
"samam": "समान",
"samantataḥ": "चारैतिर",
"samantāt": "चारैतिरबाट",
"samatvam": "समत्व",
"samatā": "समता",
"samatītya": "पार गरेर",
"samatītāni": "विगतका",
"samau": "समान",
"samavasthitam": "समान रूपमा स्थित",
"samavetān": "जम्मा भएकाहरूलाई",
"samavetāḥ": "जम्मा भएका",
"samaḥ": "समान",
"sambandhinaḥ": "नातेदारहरू",
"sambhavanti": "उत्पन्न हुन्छन्",
"sambhavaḥ": "जन्म",
"sambhavāmi": "जन्मिन्छु",
"sambhāvitasya": "सम्मानितको",
"sambhūtam": "जन्मेको",
"same": "समान",
"samiddhaḥ": "बलेको",
"samitiñjayaḥ": "समितिञ्जय",
"sammoham": "मोहमा",
"sammohaḥ": "मोह",
"sammohāt": "मोहबाट",
"sammūḍha": "मोहित",
"sammūḍhāḥ": "मोहित",
"sampadam": "सम्पत्तिमा",
"sampadyate": "प्राप्त गर्छ",
"sampanne": "युक्त",
"sampat": "सम्पत्ति",
"sampaśyan": "ध्यान राख्दै",
"samplutodake": "जलमग्न पानीमा",
"sampratiṣṭhā": "आधार",
"sampravṛttāni": "उठेका",
"samprekṣya": "हेरेर",
"sampāte": "संघर्षमा",
"samudbhavam": "उत्पन्न",
"samudbhavaḥ": "जन्मेको",
"samuddhartā": "उद्धारकर्ता",
"samudram": "समुद्र",
"samudyame": "प्रयासमा",
"samupasthitam": "आइपरेको",
"samupāśritaḥ": "शरण लिएको",
"samutthena": "जन्मेको",
"samyagvyavasitaḥ": "राम्ररी निश्चय गरेको",
"samyak": "राम्ररी",
"samācara": "गर",
"samācaran": "गर्दै",
"samādhau": "समाधिमा",
"samādhinā": "समाधिले",
"samādhisthasya": "समाधिमा स्थितको",
"samādhātum": "स्थिर गर्न",
"samādhāya": "स्थिर गरेर",
"samāgatāḥ": "जम्मा भएका",
"samāhartum": "नष्ट गर्न",
"samāhitaḥ": "स्थिर",
"samāpnoṣi": "व्याप्त गर्छौ",
"samārambhāḥ": "आरम्भहरू",
"samāsataḥ": "संक्षेपमा",
"samāsena": "संक्षेपमा",
"samāvṛtaḥ": "ढाकिएको",
"samāḥ": "वर्षहरू",
"samīkṣya": "हेरेर",
"samṛddham": "समृद्ध",
"samṛddhavegāḥ": "पूर्ण वेगसहित",
"san": "भएको",
"sandṛśyante": "देखिन्छन्",
"sanniviṣṭaḥ": "बसेको",
"sanniyamya": "नियन्त्रण गरेर",
"sannyasanāt": "संन्यासबाट",
"sannyasta": "त्यागिएको",
"sannyasya": "समर्पण गरेर",
"sannyāsam": "संन्यास",
"sannyāsayogayuktātmā": "संन्यासयोगले युक्त आत्मा",
"sannyāsaḥ": "संन्यास",
"sannyāsī": "संन्यासी",
"santariṣyasi": "पार गर्नेछौ",
"santaḥ": "सज्जनहरू",
"santuṣṭaḥ": "सन्तुष्ट",
"sanātanam": "सनातन",
"sanātanaḥ": "सनातन",
"sanātanāḥ": "सनातन",
"sapatnān": "प्रतिद्वन्द्वीहरूलाई",
"sapta": "सात",
"sarasām": "जलहरूका",
"sargaḥ": "संसार",
"sarge": "सृष्टिमा",
"sargāṇām": "सृष्टिहरूका",
"sarpāṇām": "सर्पहरूका",
"sarva": "हे सबै",
"sarvabhāvena": "सम्पूर्ण भावले",
"sarvabhūtahite": "सबै प्राणीको हितमा",
"sarvabhūtastham": "सबै प्राणीमा बस्ने",
"sarvabhūtasthitam": "सबै प्राणीमा रहने",
"sarvabhūteṣu": "सबै प्राणीमा",
"sarvabhūtāni": "सबै प्राणी",
"sarvabhūtānām": "सबै प्राणीको",
"sarvabhūtātmabhūtātmā": "सबै प्राणीको आत्मा",
"sarvabhūtāśayasthitaḥ": "सबै प्राणीको हृदयमा बस्ने",
"sarvabhṛt": "सबै धान्ने",
"sarvadehinām": "सबै देहधारीहरूका",
"sarvadharmān": "सबै धर्महरूलाई",
"sarvadurgāṇi": "सबै कठिनाइहरू",
"sarvadvāreṣu": "सबै ढोकाहरूबाट",
"sarvadvārāṇi": "शरीरका सबै ढोकाहरू",
"sarvagatam": "सर्वव्यापी",
"sarvagataḥ": "सर्वव्यापी",
"sarvaguhyatamam": "सबैभन्दा गोप्य",
"sarvaharaḥ": "सबै निल्ने",
"sarvaiḥ": "सबैले",
"sarvakarmaphalatyāgam": "सबै कर्मफलको त्याग",
"sarvakarmaṇām": "सबै कर्महरूका",
"sarvakarmāṇi": "सबै कर्महरू",
"sarvakṣetreṣu": "सबै क्षेत्रहरूमा",
"sarvam": "सबै",
"sarvapāpaiḥ": "सबै पापहरूबाट",
"sarvapāpebhyaḥ": "सबै पापहरूबाट",
"sarvasya": "सबैको",
"sarvataḥ": "सबैतिर",
"sarvathā": "सबै तरिकाले",
"sarvatra": "सर्वत्र",
"sarvatragam": "सर्वव्यापी",
"sarvatragaḥ": "सर्वत्र गमन गर्ने",
"sarvatrāvasthitaḥ": "सर्वत्र रहने",
"sarvavedeṣu": "सबै वेदहरूमा",
"sarvavit": "सबै जान्ने",
"sarvavṛkṣāṇām": "सबै रूखहरूका",
"sarvayajñānām": "सबै यज्ञहरूका",
"sarvayoniṣu": "सबै योनिहरूमा",
"sarvaśaḥ": "सबै प्रकारले",
"sarvaḥ": "सबै",
"sarve": "सबै",
"sarvebhyaḥ": "सबैमा",
"sarvendriyaguṇābhāsam": "सबै इन्द्रियका गुणसहित देखिने",
"sarvendriyavivarjitam": "सबै इन्द्रियरहित",
"sarveṣu": "सबैमा",
"sarveṣām": "सबैको",
"sarvān": "सबैलाई",
"sarvārambhaparityāgī": "सबै आरम्भ त्याग्ने",
"sarvārambhāḥ": "सबै आरम्भहरू",
"sarvārthān": "सबै कुरा",
"sarvāścaryamayam": "सबै आश्चर्यले भरिएको",
"sarvāḥ": "सबै",
"sarvāṇi": "सबै",
"sat": "सत्",
"satatam": "सधैँ",
"satatayuktānām": "सधैं समर्पितहरूका",
"satatayuktāḥ": "सधैं युक्त",
"sataḥ": "सत्को",
"sati": "भएको",
"satkāra": "सम्मानका निम्ति",
"sattva": "सत्त्व",
"sattvam": "सत्त्व",
"sattvasamāviṣṭaḥ": "सत्त्वयुक्त",
"sattvasaṁśuddhiḥ": "हृदयको शुद्धता",
"sattvasthāḥ": "सत्त्वमा स्थितहरू",
"sattvavatām": "असलहरूका",
"sattve": "सत्त्वमा",
"sattvānurūpā": "स्वभावअनुसार",
"sattvāt": "सत्त्वबाट",
"satyam": "सत्य",
"saubhadraḥ": "सुभद्रापुत्र",
"saukṣmyāt": "सूक्ष्मताले",
"saumadattiḥ": "सौमदत्ति",
"saumyam": "मनोहर",
"saumyatvam": "कोमलता",
"saumyavapuḥ": "मनोहर रूप भएको",
"savijñānam": "साक्षात्कारसहित",
"savikāram": "विकारहरूसहित",
"savyasācin": "हे सव्यसाची",
"sañchinna": "काटिएको",
"sañjanayan": "उत्पन्न गर्दै",
"sañjaya": "सञ्जय",
"sañjayati": "जोड्छ",
"sañjayaḥ": "सञ्जय",
"sañjāyate": "उत्पन्न हुन्छ",
"saśaram": "बाणसहित",
"saḥ": "ऊ",
"saṁharate": "तान्छ",
"saṁjñitam": "भनिने",
"saṁjñā": "जानकारी",
"saṁnyasya": "समर्पण गरेर",
"saṁnyāsam": "संन्यास",
"saṁnyāsasya": "संन्यासको",
"saṁnyāsaḥ": "संन्यास",
"saṁnyāsena": "संन्यासद्वारा",
"saṁnyāsinām": "संन्यासीको",
"saṁprakīrtitaḥ": "घोषणा गरिएको",
"saṁsiddhau": "सिद्धिका निम्ति",
"saṁsiddhaḥ": "सिद्ध भएको",
"saṁsiddhim": "सिद्धि",
"saṁsmṛtya": "बारम्बार सम्झेर",
"saṁsparśajāḥ": "सम्पर्कबाट जन्मेका",
"saṁstabhya": "दृढ गरेर",
"saṁsthāpana": "स्थापना",
"saṁsāreṣu": "पुनर्जन्मका चक्रहरूमा",
"saṁvigna": "व्यथित",
"saṁvādam": "संवाद",
"saṁvṛttaḥ": "भएको",
"saṁyama": "संयम",
"saṁyamatām": "दण्ड दिनेहरूका",
"saṁyamya": "संयम गरेर",
"saṁyamī": "संयमी",
"saṁyatendriyaḥ": "इन्द्रिय संयत",
"saṁyāti": "जान्छ",
"saṁśayam": "सन्देह",
"saṁśayasya": "यस सन्देहको",
"saṁśayaḥ": "सन्देह",
"saṁśayātmanaḥ": "सन्देही आत्माको",
"saṁśayātmā": "सन्देही आत्मा",
"saṁśita": "दृढ",
"saṁśritāḥ": "शरण लिएका",
"saṁśuddhakilbiṣaḥ": "पापबाट शुद्ध",
"saṅgam": "आसक्ति",
"saṅgarahitam": "आसक्तिरहित",
"saṅgasya": "आसक्तिको",
"saṅgavarjitaḥ": "आसक्तिरहित",
"saṅgavivarjitaḥ": "आसक्तिरहित",
"saṅgaḥ": "आसक्ति",
"saṅghātaḥ": "शरीर",
"saṅginām": "आसक्तहरूका",
"saṅgraham": "संग्रह",
"saṅgraheṇa": "संक्षेपमा",
"saṅgrāmam": "युद्ध",
"saṅgāt": "आसक्तिबाट",
"saṅkalpa": "सङ्कल्प",
"saṅkalpaḥ": "जसको संकल्प",
"saṅkarasya": "सङ्करको",
"saṅkaraḥ": "सङ्कर",
"saṅkhye": "युद्धमा",
"senayoḥ": "दुवै सेनाको",
"senānīnām": "सेनापतिहरूका",
"sevate": "सेवा गर्छ",
"sevayā": "अभ्यासद्वारा",
"siddhasaṅghāḥ": "सिद्धहरूका समूहहरू",
"siddhau": "सिद्धिमा",
"siddhaye": "सिद्धिका निम्ति",
"siddhaḥ": "सिद्ध",
"siddhim": "सिद्धि",
"siddhiḥ": "सिद्धि",
"siddhyasiddhyoḥ": "सिद्धि-असिद्धिमा",
"siddhānām": "सिद्धहरूका",
"siṁha": "सिंहको",
"skandaḥ": "स्कन्द",
"sma": "नै",
"smaran": "सम्झँदै",
"smarati": "सम्झन्छ",
"smṛtam": "मानिन्छ",
"smṛtaḥ": "सम्झिन्छ",
"smṛtibhraṁśāt": "स्मृतिभ्रमबाट",
"smṛtivibhramaḥ": "स्मृतिको भ्रम",
"smṛtiḥ": "स्मृति",
"smṛtā": "भनिएको",
"snigdhāḥ": "चिल्लो",
"somapāḥ": "सोमपानीहरू",
"somaḥ": "चन्द्रमा",
"soḍhum": "सहन",
"sparśanam": "स्पर्श",
"sparśeṣu": "सम्पर्कहरूमा",
"sparśān": "सम्पर्कहरूलाई",
"sparśāḥ": "सम्पर्कहरू",
"spṛhā": "लालसा",
"spṛśan": "छुँदै",
"sraṁsate": "चिप्लिन्छ",
"srotasām": "नदीहरूका",
"stabdhaḥ": "हठी",
"stabdhāḥ": "जिद्दी",
"stenaḥ": "चोर",
"sthairyam": "स्थैर्य",
"sthirabuddhiḥ": "स्थिरबुद्धि",
"sthiram": "स्थिर",
"sthiramatiḥ": "स्थिर मन",
"sthiraḥ": "स्थिर",
"sthirām": "स्थायी",
"sthirāḥ": "दृढ",
"sthitadhīḥ": "स्थिरबुद्धि",
"sthitam": "स्थित",
"sthitaprajñasya": "स्थितप्रज्ञको",
"sthitaprajñaḥ": "स्थितप्रज्ञ",
"sthitau": "स्थित",
"sthitaḥ": "स्थित",
"sthitim": "स्थिर आधार",
"sthitiḥ": "स्थिरता",
"sthitvā": "रहेर",
"sthitān": "स्थित",
"sthitāḥ": "स्थित",
"sthānam": "स्थान",
"sthāne": "उचित",
"sthāpaya": "राख",
"sthāpayitvā": "राखेर",
"sthāsyati": "रहनेछ",
"sthāvarajaṅgamam": "चर वा अचर",
"sthāvarāṇām": "स्थावरहरूका",
"sthāṇuḥ": "स्थिर",
"striyaḥ": "स्त्रीहरू",
"strīṣu": "स्त्रीहरूमा",
"stutibhiḥ": "स्तोत्रहरूले",
"stutiḥ": "स्तुति",
"stuvanti": "स्तुति गर्छन्",
"su": "असल",
"sudurdarśam": "देख्न धेरै गाह्रो",
"sudurlabhaḥ": "अति दुर्लभ",
"sudurācāraḥ": "अति दुष्ट आचरणको",
"suduṣkaram": "धेरै गाह्रो",
"sughoṣamaṇipuṣpakau": "सुघोष र मणिपुष्पक",
"suhṛdam": "मित्रलाई",
"suhṛt": "मित्र",
"sukha": "सुख",
"sukhaduḥkhasaṁjñaiḥ": "सुख-दुःख भनिने",
"sukhaduḥkheṣu": "सुख-दुःखमा",
"sukhaduḥkhānām": "सुख-दुःखको",
"sukham": "सुख",
"sukhasaṅgena": "सुखको आसक्तिले",
"sukhasya": "सुखको",
"sukhe": "सुखमा",
"sukhena": "सजिलै",
"sukheṣu": "सुखहरूमा",
"sukhinaḥ": "सुखी",
"sukhāni": "सुखहरू",
"sukhī": "सुखी",
"sukṛta": "असल",
"sukṛtam": "पुण्य",
"sukṛtasya": "असल",
"sukṛtinaḥ": "सत्कर्मीहरूका",
"sulabhaḥ": "सजिलै पाइने",
"suniścitam": "निश्चय गरेर",
"suragaṇāḥ": "देवताका समूहहरू",
"surasaṅghāḥ": "देवताका समूहहरू",
"surendralokam": "इन्द्रलोक",
"surāṇām": "देवताहरूका",
"susukham": "धेरै सजिलो",
"suvirūḍha": "दृढ जरा भएको",
"sva": "आफ्नो",
"svabhāvajam": "स्वभावबाट जन्मेको",
"svabhāvajena": "आफ्नै स्वभावबाट जन्मेको",
"svabhāvajā": "स्वभावबाट जन्मेको",
"svabhāvaniyatam": "आफ्नै स्वभावले निर्धारित",
"svabhāvaprabhavaiḥ": "आफ्नै स्वभावबाट जन्मेका",
"svabhāvaḥ": "स्वभाव",
"svacakṣuṣā": "आफ्नै आँखाले",
"svadharmam": "आफ्नो धर्म",
"svadharmaḥ": "आफ्नै धर्म",
"svadhā": "स्वधा",
"svakam": "आफ्नो",
"svakarmanirataḥ": "आफ्नै कर्तव्यमा तत्पर",
"svakarmaṇā": "आफ्नै कर्तव्यद्वारा",
"svalpam": "अलिकति",
"svam": "आफ्नो",
"svanuṣṭhitāt": "सुसम्पन्न",
"svapan": "सुत्दै",
"svapna": "निद्रामा",
"svapnam": "निद्रा",
"svargadvāram": "स्वर्गको ढोका",
"svargalokam": "स्वर्गलोक",
"svargam": "स्वर्ग",
"svargaparāḥ": "स्वर्ग चाहने",
"svargatim": "स्वर्गको मार्ग",
"svasthaḥ": "आत्मामै स्थित",
"svasti": "कल्याण",
"svasyāḥ": "आफ्नैको",
"svatejasā": "आफ्नै तेजले",
"svayam": "आफैं",
"svayā": "आफ्नै",
"sve": "आफ्नैमा",
"svena": "आफ्नैद्वारा",
"svādhyāya": "स्वाध्यायको",
"svādhyāyaḥ": "स्वाध्याय",
"svādhyāyābhyasanam": "शास्त्र-अध्ययनको अभ्यास",
"svām": "आफ्नो",
"syandane": "रथमा",
"syuḥ": "हुन्",
"syām": "होऊँ",
"syāma": "हुने थियौं",
"syāt": "होला",
"sā": "त्यो",
"sādharmyam": "एकत्व",
"sādhubhāve": "असलपनको अर्थमा",
"sādhuḥ": "असल",
"sādhuṣu": "सज्जनहरूमा",
"sādhyāḥ": "साध्यहरू",
"sādhūnām": "सज्जनहरूका",
"sāgaraḥ": "समुद्र",
"sāhaṁkāreṇa": "अहंकारसहित",
"sākṣāt": "प्रत्यक्ष",
"sākṣī": "साक्षी",
"sāma": "साम",
"sāmarthyam": "क्षमता",
"sāmavedaḥ": "सामवेद",
"sāmnām": "सामहरूका",
"sāmye": "समत्वमा",
"sāmyena": "समत्वका रूपमा",
"sāmāsikasya": "समासको",
"sāttvikam": "सात्त्विक",
"sāttvikapriyāḥ": "सात्त्विकलाई प्रिय",
"sāttvikaḥ": "सात्त्विक",
"sāttvikāḥ": "सात्त्विकहरू",
"sāttvikī": "सात्त्विकी",
"sātyakiḥ": "सात्यकि",
"sāṁkhye": "दर्शनमा",
"sāṅkhyaiḥ": "साङ्ख्यहरूद्वारा",
"sāṅkhyam": "साङ्ख्य",
"sāṅkhyayogau": "साङ्ख्य र योग",
"sāṅkhye": "साङ्ख्यमा",
"sāṅkhyena": "ज्ञानयोगद्वारा",
"sāṅkhyānām": "साङ्ख्यहरूका",
"sīdanti": "डुब्छन्",
"sūkṣmatvāt": "सूक्ष्म भएर",
"sūryasahasrasya": "हजार सूर्यको",
"sūryaḥ": "सूर्य",
"sūtaputraḥ": "सूतपुत्र",
"sūtre": "धागोमा",
"sūyate": "उत्पन्न गर्छे",
"sṛjati": "सृष्टि गर्छ",
"sṛjāmi": "सृष्टि गर्छु",
"sṛtī": "दुई बाटो",
"sṛṣṭam": "सृष्टि गरिएको",
"sṛṣṭvā": "सृष्टि गरेर",
"tadarthīyam": "त्यसैका निम्ति",
"tadbhāvabhāvitaḥ": "त्यही भावले व्याप्त",
"tadbuddhayaḥ": "जसको बुद्धि त्यसमा",
"tadvat": "त्यसरी",
"tadvidaḥ": "त्यसका ज्ञाता",
"tadā": "तब",
"tadātmānaḥ": "जसको आत्मा त्यसमा",
"taiḥ": "तिनीहरूद्वारा",
"tam": "उसलाई",
"tamasaḥ": "तमको",
"tamasi": "तममा",
"tamasāvṛtā": "अन्धकारले ढाकिएको",
"tamaḥ": "तम",
"tamodvāraiḥ": "अन्धकारका ढोकाहरूद्वारा",
"tanniṣṭhāḥ": "त्यसमै निष्ठा भएका",
"tanum": "रूप",
"tapantam": "बल्ने",
"tapasi": "तपस्या",
"tapasvibhyaḥ": "तपस्वीहरूभन्दा",
"tapasviṣu": "तपस्वीहरूमा",
"tapasyasi": "तप गर्छौ",
"tapasā": "तपस्या",
"tapasām": "तपस्याहरूको",
"tapaḥ": "तपस्या",
"tapaḥsu": "तपस्याहरूमा",
"tapobhiḥ": "तपस्याहरूद्वारा",
"taptam": "गरिएको",
"tapyante": "अभ्यास गर्छन्",
"tapāmi": "ताप दिन्छु",
"taranti": "पार गर्छन्",
"tariṣyasi": "पार गर्नेछौ",
"tasmin": "त्यसमा",
"tasmāt": "त्यसकारण",
"tasya": "त्यसको",
"tasyām": "त्यसमा",
"tat": "त्यो",
"tat tat": "यो र त्यो",
"tatam": "व्याप्त",
"tataḥ": "त्यसैले",
"tathā": "त्यसरी",
"tathāpi": "तैपनि",
"tatparam": "त्यसभन्दा पर",
"tatparaḥ": "त्यसमा तत्पर",
"tatparāyaṇāḥ": "त्यसमै तत्पर",
"tatprasādāt": "उहाँको कृपाले",
"tatra": "त्यहाँ",
"tatsamakṣam": "अरूको अगाडि",
"tattvadarśibhiḥ": "तत्त्वदर्शीहरूद्वारा",
"tattvadarśinaḥ": "तत्त्वदर्शीहरू",
"tattvajñānārthadarśanam": "तत्त्वज्ञानको प्रयोजनको दृष्टि",
"tattvam": "तत्त्व",
"tattvataḥ": "वास्तवमा",
"tattvavit": "तत्त्वज्ञ",
"tattvena": "साँच्चै",
"tau": "ती दुई",
"tava": "तिम्रो",
"tayoḥ": "दुवैको",
"tayā": "त्यसले",
"te": "तिम्रो",
"tejasvinām": "तेजस्वीहरूका",
"tejaḥ": "तेज",
"tejobhiḥ": "तेजले",
"tejomayam": "तेजोमय",
"tejorāśim": "प्रकाशको पुञ्ज",
"tejoṁśasambhavam": "मेरो तेजको अंशबाट जन्मेको",
"tena": "त्यसद्वारा",
"teṣu": "तिनीहरूमा",
"teṣām": "तिनीहरूको",
"titikṣasva": "सहन गर",
"tiṣṭhantam": "उभिएको",
"tiṣṭhanti": "रहन्छन्",
"tiṣṭhasi": "बस्छौ",
"tiṣṭhati": "रहन्छ",
"toyam": "जल",
"traiguṇya": "तीन गुण",
"trailokya": "तीनै लोकको",
"traividyāḥ": "तीन वेदका ज्ञाता",
"trayam": "तीन",
"trayīdharmam": "तीन वेदको धर्म",
"tribhiḥ": "तीनले",
"tridhā": "त्रिविध",
"trividham": "तीन प्रकारको",
"trividhaḥ": "त्रिविध",
"trividhā": "त्रिविध",
"triṣu": "तीनमा",
"trāyate": "रक्षा गर्छ",
"trīn": "तीन",
"tu": "तर",
"tulya": "समान",
"tulyanindātmasaṁstutiḥ": "निन्दा र आत्म-प्रशंसामा समान",
"tulyapriyāpriyaḥ": "प्रिय-अप्रियमा समान",
"tulyaḥ": "समान",
"tumulaḥ": "कोलाहलपूर्ण",
"tuṣyanti": "सन्तुष्ट हुन्छन्",
"tuṣyati": "सन्तुष्ट हुन्छ",
"tuṣṭaḥ": "सन्तुष्ट",
"tuṣṭiḥ": "सन्तोष",
"tv": "तर",
"tvadanyaḥ": "तिमीबाहेक अरू",
"tvadanyena": "तिमीबाहेक अरूद्वारा",
"tvak": "छाला",
"tvam": "तिमी",
"tvanayoḥ": "यी दुईका",
"tvaramāṇāḥ": "हतार गर्दै",
"tvatprasādāt": "तिम्रो कृपाले",
"tvatsamaḥ": "तिमीसरह",
"tvattaḥ": "तिमीबाट",
"tvayi": "तिमीमा",
"tvayā": "तिमीद्वारा",
"tveva": "नै",
"tvā": "तिमीलाई",
"tvām": "तिमीलाई",
"tyajan": "त्याग्दै",
"tyajati": "त्याग्छ",
"tyajet": "त्याग्नुपर्छ",
"tyakta": "त्यागेको",
"tyaktajīvitāḥ": "जीवन त्यागेका",
"tyaktum": "त्याग्न",
"tyaktvā": "त्यागेर",
"tyāgam": "त्याग",
"tyāgaphalam": "त्यागको फल",
"tyāgasya": "त्यागको",
"tyāgaḥ": "त्याग",
"tyāge": "त्यागमा",
"tyāgāt": "त्यागबाट",
"tyāgī": "त्यागी",
"tyājyam": "त्याग्नुपर्ने",
"tām": "त्यो",
"tāmasam": "तामस",
"tāmasapriyam": "तामसलाई प्रिय",
"tāmasaḥ": "तामस",
"tāmasāḥ": "तामसहरू",
"tāmasī": "तामसी",
"tān": "तिनीहरूलाई",
"tāni": "ती",
"tāsām": "तिनका",
"tāta": "हे पुत्र",
"tāvān": "त्यति",
"tīkṣṇa": "पिरो",
"tūṣṇīm": "मौन",
"tṛptaḥ": "तृप्त",
"tṛptiḥ": "सन्तोष",
"tṛptātmā": "आत्मामै सन्तुष्ट",
"tṛṣṇāsaṅgasamudbhavam": "तृष्णा र आसक्तिबाट जन्मेको",
"u": "नै",
"ubhau": "दुवै",
"ubhaya": "दुवै",
"ubhayoḥ": "दुवैको",
"ubhe": "दुवै",
"uccaiḥ": "ठूलो स्वरले",
"uccaiḥśravasam": "उच्चैःश्रवा",
"ucchiṣṭam": "बचेका",
"ucchoṣaṇam": "सुकाउने",
"ucyate": "भनिन्छ",
"udaka": "पानी",
"udapāne": "इनारमा",
"udbhavam": "जन्मेको",
"udbhavaḥ": "स्रोत",
"uddeśataḥ": "संक्षेपमा",
"uddharet": "उठाउनुपर्छ",
"uddiśya": "लक्ष्य गरेर",
"udvegaiḥ": "चिन्ताहरूले",
"udvijate": "विचलित हुन्छ",
"udvijet": "व्यथित हुन्थ्यो",
"udyamya": "उठाएर",
"udyatāḥ": "तयार",
"udāhṛtam": "भनिएको",
"udāhṛtaḥ": "भनिन्छ",
"udāhṛtya": "भनेर",
"udārāḥ": "उदार",
"udāsīna": "उदासीन",
"udāsīnavat": "उदासीनझैं",
"udāsīnaḥ": "उदासीन",
"ugraiḥ": "कठोर",
"ugrakarmāṇaḥ": "क्रूर कर्म गर्ने",
"ugram": "भयानक",
"ugrarūpaḥ": "भयानक रूप भएको",
"ugrāḥ": "भयानक",
"uktam": "भनिएको",
"uktaḥ": "भनिएको",
"uktvā": "भनेर",
"uktāḥ": "भनिएका",
"ulbena": "झिल्लीले",
"unmiṣan": "आँखा खोल्दै",
"upadekṣyanti": "उपदेश गर्नेछन्",
"upadhāraya": "जान",
"upadraṣṭā": "साक्षी",
"upahanyām": "नष्ट गर्थें",
"upahata": "ग्रस्त",
"upaiti": "प्राप्त हुन्छ",
"upaiṣyasi": "आउनेछौ",
"upajuhvati": "अर्पण गर्छन्",
"upajāyante": "उत्पन्न हुन्छन्",
"upajāyate": "उत्पन्न हुन्छ",
"upalabhyate": "अनुभव गरिन्छ",
"upalipyate": "दागिन्छ",
"upamā": "उपमा",
"upapadyate": "उचित हुन्छ",
"upapannam": "प्राप्त",
"uparamate": "शान्त हुन्छ",
"uparamet": "शान्त हुनुपर्छ",
"uparatam": "शान्त",
"upasaṅgamya": "पुगेर",
"upasevate": "भोग गर्छ",
"upaviśya": "बसेर",
"upayānti": "आउँछन्",
"upetaḥ": "युक्त",
"upetya": "पुगेर",
"upetāḥ": "युक्त",
"upāsate": "उपासना गर्छन्",
"upāviśat": "बसे",
"upāyataḥ": "उचित उपायले",
"upāśritya": "शरण लिएर",
"upāśritāḥ": "आश्रित",
"uragān": "सर्पहरूलाई",
"uta": "नै",
"utkrāmantam": "प्रस्थान गर्दै",
"utkrāmati": "प्रस्थान गर्छ",
"utsanna": "नष्ट",
"utsādanārtham": "विनाशका निम्ति",
"utsādyante": "नष्ट हुन्छन्",
"utsīdeyuḥ": "नष्ट हुन्थे",
"utsṛjya": "त्यागेर",
"utsṛjāmi": "छोड्छु",
"uttama": "हे श्रेष्ठ",
"uttamam": "उत्तम",
"uttamaujāḥ": "उत्तमौजा",
"uttamavidām": "परम ज्ञाताहरूका",
"uttamaḥ": "उच्च",
"uttamāṅgaiḥ": "शिरहरूले",
"uttaram": "फैलिएको",
"uttarāyaṇam": "उत्तरायण",
"utthitā": "उठेको",
"uttiṣṭha": "उठ",
"uvāca": "भने",
"uśanā": "उशना",
"uṣitvā": "बसेर",
"uṣmapāḥ": "उष्मापाहरू",
"uṣṇa": "तातो",
"vacanam": "वचन",
"vacaḥ": "वचन",
"vada": "भन",
"vadanaiḥ": "मुखले",
"vadanti": "भन्छन्",
"vadasi": "भन्छौ",
"vadati": "भन्छ",
"vadiṣyanti": "बोल्नेछन्",
"vahniḥ": "अग्नि",
"vahāmi": "बोक्छु",
"vainateyaḥ": "गरुड",
"vairiṇam": "शत्रुलाई",
"vairiṇā": "शत्रुद्वारा",
"vairāgyam": "वैराग्य",
"vairāgyeṇa": "वैराग्यद्वारा",
"vaiśvānaraḥ": "वैश्वानर",
"vaiśyakarma": "वैश्यको कर्तव्य",
"vaiśyāḥ": "वैश्यहरू",
"vajram": "वज्र",
"vaktrāṇi": "मुखहरू",
"vaktum": "भन्न",
"vakṣyāmi": "भन्नेछु",
"vara": "हे श्रेष्ठ",
"varjitāḥ": "रहित",
"vartamānaḥ": "बाँचेको",
"vartamānāni": "वर्तमान",
"vartante": "रहन्छन्",
"vartate": "रहन्छ",
"varte": "लागेको छु",
"varteta": "बस्नुपर्छ",
"varteyam": "गर्नुपर्छ",
"vartma": "मार्ग",
"varuṇaḥ": "वरुण",
"varṇa": "वर्णको",
"varṇasaṅkara": "वर्णसङ्कर",
"varṣam": "वर्षा",
"vasavaḥ": "वसुहरू",
"vasūn": "वसुहरूलाई",
"vasūnām": "वसुहरूका",
"vayam": "हामी",
"vaśam": "वशमा",
"vaśe": "वशमा",
"vaśyātmanā": "संयत आत्माले",
"vaśāt": "वशले",
"vaśī": "संयमी",
"vaḥ": "तिमीहरूलाई",
"veda": "जान्दछ",
"vedaiḥ": "वेदहरूद्वारा",
"vedavidaḥ": "वेदका ज्ञाता",
"vedavit": "वेदको ज्ञाता",
"vedavādaratāḥ": "वेदका वचनमा रम्ने",
"vedayajñādhyayanaiḥ": "वेद-अध्ययन र यज्ञद्वारा",
"vede": "वेदमा",
"vedeṣu": "वेदहरूमा",
"veditavyam": "जान्नुपर्ने",
"veditum": "जान्न",
"vedyam": "ज्ञेय",
"vedyaḥ": "जान्नुपर्ने",
"vedāntakṛt": "वेदान्तको कर्ता",
"vedānām": "वेदहरूका",
"vedāḥ": "वेदहरू",
"vegam": "वेग",
"vepamānaḥ": "काँप्दै",
"vepathuḥ": "कम्प",
"vettha": "जान्दछौ",
"vetti": "जान्दछ",
"vettā": "ज्ञाता",
"vibhaktam": "विभाजित",
"vibhakteṣu": "विभाजितमा",
"vibhraṣṭaḥ": "च्युत",
"vibhum": "सर्वव्यापी",
"vibhuḥ": "सर्वव्यापी",
"vibhāgayoḥ": "विभागको",
"vibhāgaśaḥ": "विभागअनुसार",
"vibhāvasau": "अग्निमा",
"vibhūteḥ": "विभूतिको",
"vibhūtibhiḥ": "विभूतिहरूद्वारा",
"vibhūtim": "विभूति",
"vibhūtimat": "विभूतिशाली",
"vibhūtīnām": "विभूतिहरूका",
"vicakṣaṇāḥ": "विज्ञहरू",
"vicetasaḥ": "अचेतन",
"vicālayet": "विचलित गर्नुपर्छ",
"vicālyate": "विचलित हुन्छ",
"vidadhāmi": "गर्छु",
"vidaḥ": "ज्ञाताहरू",
"viddhi": "जान",
"vidheyātmā": "संयत आत्मा",
"vidhidṛṣṭaḥ": "शास्त्रले विधान गरेको",
"vidhihīnam": "विधिरहित",
"vidhānoktāḥ": "विधानले भनिएका",
"vidhīyate": "स्थापित हुन्छ",
"viditvā": "जानेर",
"viditātmanām": "आत्मज्ञानीहरूका",
"vidmaḥ": "जान्दछौं",
"viduḥ": "जान्छन्",
"vidvān": "ज्ञानी",
"vidyate": "हुन्छ",
"vidyā": "विद्या",
"vidyām": "जानूँ",
"vidyānām": "विद्याहरूमा",
"vidyāt": "जान्नुपर्छ",
"vidāhinaḥ": "बल्ने",
"vigata": "गएको",
"vigatabhīḥ": "निर्भय",
"vigatakalmaṣaḥ": "पापरहित",
"vigataspṛhaḥ": "इच्छारहित",
"vigataḥ": "गएको",
"viguṇaḥ": "दोषपूर्ण",
"vihitān": "विधान गरिएका",
"vihitāḥ": "विधान गरिएका",
"vihāra": "विहारमा",
"vihārasya": "विहारको",
"vihāya": "त्यागेर",
"vijayam": "विजय",
"vijayaḥ": "विजय",
"vijitendriyaḥ": "इन्द्रियजित",
"vijitātmā": "आत्मजित",
"vijñāna": "साक्षात्कार",
"vijñānam": "विज्ञान",
"vijñānasahitam": "साक्षात्कारसहित",
"vijñātum": "जान्न",
"vijñāya": "जानेर",
"vijānataḥ": "जान्नेको",
"vijānītaḥ": "जान",
"vijānīyām": "बुझूँ",
"vikampitum": "हल्लिन",
"vikarmaṇaḥ": "विकर्मको",
"vikarṇaḥ": "विकर्ण",
"vikrāntaḥ": "पराक्रमी",
"vikāri": "यसका विकार",
"vikārān": "विकारहरूलाई",
"vilagnāḥ": "टाँसिएका",
"vimatsaraḥ": "डाहरहित",
"vimohayati": "मोहित गर्छ",
"vimokṣaṇāt": "मुक्तिबाट",
"vimokṣyase": "मुक्त हुनेछौ",
"vimokṣāya": "मुक्तिका निम्ति",
"vimucya": "मुक्त भएर",
"vimuhyati": "मोहित हुन्छ",
"vimuktaḥ": "मुक्त",
"vimuktāḥ": "मुक्त",
"vimuñcati": "छोड्छ",
"vimūḍha": "मोहित",
"vimūḍhabhāvaḥ": "मोह",
"vimūḍhaḥ": "मोहित",
"vimūḍhān": "मोहित",
"vimūḍhāḥ": "मोहितहरू",
"vimṛśya": "विचार गरेर",
"vinadya": "गर्जेर",
"vinaya": "विनय",
"vinaśyati": "नष्ट हुन्छ",
"vinaśyatsu": "नष्ट हुँदा",
"vinaṅkṣyasi": "नष्ट हुनेछौ",
"vindate": "पाउँछ",
"vindati": "पाउँछ",
"vindāmi": "पाउँछु",
"vinirmuktāḥ": "मुक्त",
"vinivartante": "टाढिन्छन्",
"vinivṛttakāmāḥ": "कामना फर्काइएका",
"viniyamya": "संयत गरेर",
"viniyatam": "राम्ररी संयत",
"viniścitaiḥ": "राम्ररी निर्णय गरिएको",
"vinā": "बिना",
"vināśam": "विनाश",
"vināśaḥ": "विनाश",
"vināśāya": "विनाशका निम्ति",
"viparivartate": "घुम्छ",
"viparītam": "उल्टो",
"viparītān": "उल्टो",
"viparītāni": "अशुभ",
"vipaścitaḥ": "ज्ञानीको",
"vipratipannā": "भ्रमित",
"virāṭaḥ": "विराट",
"visargaḥ": "सृष्टि-प्रेरणा",
"vismayaḥ": "आश्चर्य",
"vismayāviṣṭaḥ": "आश्चर्यले भरिएको",
"vismitāḥ": "आश्चर्यचकित",
"vistarasya": "विस्तारको",
"vistaraśaḥ": "विस्तारमा",
"vistaraḥ": "विस्तार",
"vistareṇa": "विस्तारमा",
"vistāram": "विस्तार",
"visṛjan": "त्याग्दै",
"visṛjya": "त्यागेर",
"visṛjāmi": "पठाउँछु",
"vitatāḥ": "फैलाइएका",
"vitteśaḥ": "धनका स्वामी",
"vivardhanāḥ": "बढाउने",
"vivasvataḥ": "विवस्वान्को",
"vivasvate": "विवस्वान्लाई",
"vivasvān": "विवस्वान्",
"vividhaiḥ": "विविध",
"vividhāḥ": "विविध",
"viviktadeśasevitvam": "एकान्त स्थानको सेवन",
"viviktasevī": "एकान्तमा बस्ने",
"vivṛddham": "बढेको",
"vivṛddhe": "बढ्दा",
"viyogam": "विच्छेद",
"viyuktaiḥ": "रहित",
"viyuktānām": "मुक्तहरूका",
"viśanti": "प्रवेश गर्छन्",
"viśate": "प्रवेश गर्छ",
"viśeṣa": "विविध",
"viśiṣyate": "श्रेष्ठ हुन्छ",
"viśiṣṭāḥ": "विशिष्ट",
"viśuddhayā": "शुद्ध",
"viśuddhātmā": "शुद्ध आत्मा भएको",
"viśvam": "विश्व",
"viśvamūrte": "हे विश्वमूर्ते",
"viśvarūpa": "हे विश्वरूप",
"viśvasya": "ब्रह्माण्डको",
"viśvatomukham": "सर्वत्र मुख भएको",
"viśvatomukhaḥ": "सर्वत्र मुख भएको",
"viśve": "विश्वेदेवहरू",
"viśveśvara": "हे विश्वेश्वर",
"viśālam": "विशाल",
"viśāradāḥ": "निपुण",
"viṣam": "विष",
"viṣame": "सङ्कटमा",
"viṣayapravālāḥ": "विषयहरू टुसा भएका",
"viṣayendriyasaṁyogāt": "इन्द्रिय-विषयको सम्पर्कबाट",
"viṣayān": "विषयहरू",
"viṣayāḥ": "विषयहरू",
"viṣādam": "निराशा",
"viṣādī": "निराश",
"viṣīdan": "शोक गर्दै",
"viṣīdantam": "शोक गर्ने",
"viṣṇo": "हे विष्णु",
"viṣṇuḥ": "विष्णु",
"viṣṭabhya": "धानेर",
"viṣṭhitam": "बसेको",
"vraja": "जाऊ",
"vrajeta": "जान्थ्यो",
"vratāḥ": "व्रतहरू",
"vyadārayat": "चिरिदियो",
"vyakta": "व्यक्त",
"vyaktayaḥ": "व्यक्तहरू",
"vyaktim": "प्रकट रूप",
"vyanunādayan": "गुञ्जाउँदै",
"vyapetabhīḥ": "डर हटेको",
"vyapāśrayaḥ": "भरोसा",
"vyapāśritya": "शरण लिएर",
"vyathanti": "व्यथित हुन्छन्",
"vyathayanti": "विचलित गर्छन्",
"vyathiṣṭhāḥ": "व्यथित हुनु",
"vyathā": "व्यथा",
"vyatitariṣyati": "पार गर्नेछ",
"vyatītāni": "बितेका",
"vyavasitāḥ": "दृढ संकल्प भएका",
"vyavasthitau": "स्थापित छन्",
"vyavasthitān": "स्थित",
"vyavasāyaḥ": "संकल्प",
"vyavasāyātmikā": "दृढ",
"vyudasya": "त्यागेर",
"vyāharan": "उच्चारण गर्दै",
"vyāmiśreṇa": "मिश्रित",
"vyāptam": "भरिएको",
"vyāpya": "व्याप्त गरेर",
"vyāsaprasādāt": "व्यासको कृपाले",
"vyāsaḥ": "व्यास",
"vyāttānanam": "खुला मुख भएको",
"vyūḍham": "सजिएको",
"vyūḍhām": "सजिएको",
"vā": "वा",
"vācam": "वाणी",
"vācyam": "भन्नुपर्ने",
"vādaḥ": "तर्क",
"vādinaḥ": "घोषणा गर्ने",
"vādān": "वचनहरू",
"vāk": "वाणी",
"vākyam": "वाक्य",
"vākyena": "वचनले",
"vārṣṇeya": "हे वार्ष्णेय",
"vāsavaḥ": "इन्द्र",
"vāsaḥ": "निवास",
"vāsudevasya": "वासुदेवको",
"vāsudevaḥ": "वासुदेव",
"vāsukiḥ": "वासुकि",
"vāsāṁsi": "वस्त्रहरू",
"vāyoḥ": "वायुको",
"vāyuḥ": "वायु",
"vāṅmayam": "वाणीमय",
"vīkṣante": "हेर्छन्",
"vīryavān": "शक्तिशाली",
"vīta": "रहित",
"vītarāgāḥ": "वीतराग",
"vṛddhaḥ": "वृद्ध",
"vṛjinam": "पाप",
"vṛkodaraḥ": "वृकोदर",
"vṛṣṇīnām": "वृष्णिहरूका",
"yad vā": "कि वा",
"yadi": "यदि",
"yadvat": "जसरी",
"yadyapi": "यद्यपि",
"yadā": "जब",
"yadṛcchayā": "आफैं",
"yadṛcchā": "आफैं",
"yajantaḥ": "पूजा गर्दै",
"yajante": "पूजा गर्छन्",
"yajanti": "पूजा गर्छन्",
"yajuḥ": "यजु",
"yajña": "यज्ञ",
"yajñadānatapaḥkarma": "यज्ञ, दान र तपस्या",
"yajñadānatapaḥkriyāḥ": "यज्ञ, दान र तपस्या-क्रियाहरू",
"yajñaiḥ": "यज्ञहरूद्वारा",
"yajñam": "यज्ञ",
"yajñatapaḥkriyāḥ": "यज्ञ र तपस्या-क्रियाहरू",
"yajñavidaḥ": "यज्ञका ज्ञाता",
"yajñaḥ": "यज्ञ",
"yajñe": "यज्ञमा",
"yajñena": "यज्ञद्वारा",
"yajñeṣu": "यज्ञहरूमा",
"yajñānām": "यज्ञहरूका",
"yajñāt": "यज्ञबाट",
"yajñāya": "यज्ञका निम्ति",
"yajñāḥ": "यज्ञहरू",
"yakṣarakṣasām": "यक्ष र राक्षसहरूका",
"yakṣarakṣāṁsi": "यक्ष र राक्षसहरूलाई",
"yakṣye": "यज्ञ गर्नेछु",
"yam": "जुन",
"yamaḥ": "यम",
"yantrārūḍhāni": "यन्त्रमा चढेका",
"yasmin": "जसमा",
"yasmāt": "किनकि",
"yasya": "जसको",
"yasyām": "जसमा",
"yat": "जुन",
"yata": "संयमित",
"yatacittasya": "संयत मनको",
"yatamānaḥ": "प्रयत्न गर्ने",
"yatantaḥ": "प्रयत्न गर्ने",
"yatanti": "प्रयत्न गर्छन्",
"yatataḥ": "प्रयत्न गर्ने",
"yatate": "प्रयत्न गर्छ",
"yatati": "प्रयत्न गर्छ",
"yatatā": "प्रयत्न गर्दै",
"yatatām": "प्रयत्न गर्नेहरूका",
"yatavākkāyamānasaḥ": "वाणी, शरीर र मनमाथि विजयी",
"yatayaḥ": "यतीहरू",
"yataḥ": "जसबाट",
"yathoktam": "भनिएअनुसार",
"yathā": "जसरी",
"yathāvat": "जस्ताको तस्तै",
"yatprabhāvaḥ": "के शक्ति भएको",
"yatra": "जहाँ",
"yatātmavān": "आत्मसंयमी",
"yatātmā": "आत्मसंयमी",
"yatīnām": "यतीहरूका",
"yauvanam": "युवावस्था",
"yayā": "जसद्वारा",
"yaśaḥ": "कीर्ति",
"yaḥ": "जो",
"yaṣṭavyam": "गर्नुपर्ने",
"ye": "जो",
"yena": "जसद्वारा",
"yeṣām": "जसको",
"yoddhavyam": "लड्नुपर्ने",
"yoddhum": "लड्न",
"yodhamukhyaiḥ": "प्रमुख योद्धाहरूद्वारा",
"yodhavīrān": "वीर-योद्धाहरूलाई",
"yodhāḥ": "योद्धाहरू",
"yoga": "योग",
"yogabalena": "योगशक्तिले",
"yogabhraṣṭaḥ": "योगबाट च्युत",
"yogadhāraṇām": "योगधारणामा",
"yogaiḥ": "योगीहरूद्वारा",
"yogakṣemam": "नपाएको र पाएको कुरा",
"yogam": "योग",
"yogamāyā": "योगमायाद्वारा",
"yogasaṁjñitam": "योग भनिने",
"yogasaṁsiddhaḥ": "योगमा सिद्ध",
"yogasaṁsiddhim": "योगमा सिद्धि",
"yogasthaḥ": "योगमा स्थित",
"yogasya": "योगको",
"yogavittamāḥ": "योगका उत्तम ज्ञाता",
"yogayuktaḥ": "योगयुक्त",
"yogayuktātmā": "योगयुक्त आत्मा",
"yogaḥ": "योग",
"yoge": "योगमा",
"yogena": "योगले",
"yogeśvara": "हे योगेश्वर",
"yogeśvaraḥ": "योगेश्वर",
"yogeśvarāt": "योगेश्वरबाट",
"yogin": "हे योगी",
"yoginam": "योगीलाई",
"yoginaḥ": "योगीहरू",
"yoginām": "योगीहरूका",
"yogārūḍhasya": "योगमा चढेकाको",
"yogārūḍhaḥ": "योगमा चढेको",
"yogāt": "योगबाट",
"yogāya": "योगका निम्ति",
"yogī": "योगी",
"yoktavyaḥ": "अभ्यास गर्नुपर्ने",
"yoni": "योनिहरू",
"yonim": "योनि",
"yoniḥ": "योनि",
"yoniṣu": "योनिहरूमा",
"yonīni": "योनिहरूलाई",
"yotsyamānān": "लड्नेहरूलाई",
"yotsye": "लड्नेछु",
"yuddha": "युद्धमा",
"yuddham": "युद्ध",
"yuddhe": "युद्धमा",
"yuddhāt": "युद्धभन्दा",
"yuddhāya": "युद्धका निम्ति",
"yudhi": "युद्धमा",
"yudhiṣṭhiraḥ": "युधिष्ठिर",
"yudhya": "लड",
"yudhyasva": "लड",
"yudhāmanyuḥ": "युधामन्यु",
"yugapat": "एकै पटक",
"yugasahasrāntām": "हजार युगमा समाप्त हुने",
"yuge": "युगपछि",
"yujyasva": "समर्पित होऊ",
"yujyate": "प्रयोग हुन्छ",
"yukta": "संयमित",
"yuktacetasaḥ": "स्थिर मन भएका",
"yuktaiḥ": "दृढहरूद्वारा",
"yuktatamaḥ": "सबैभन्दा युक्त",
"yuktatamāḥ": "सबैभन्दा युक्त",
"yuktaḥ": "युक्त",
"yukte": "युक्त",
"yuktvā": "जोडेर",
"yuktātmā": "आत्मायुक्त",
"yuyudhānaḥ": "युयुधान",
"yuyutsavaḥ": "लड्न चाहनेहरू",
"yuyutsum": "लड्न उत्सुक",
"yuñjan": "अभ्यास गर्दै",
"yuñjataḥ": "अभ्यास गर्ने",
"yuñjyāt": "अभ्यास गर्नुपर्छ",
"yuñjīta": "अभ्यास गर्नुपर्छ",
"yā": "जुन",
"yābhiḥ": "जसद्वारा",
"yādasām": "जलचरहरूका",
"yādava": "हे यादव",
"yādṛk": "कस्तो",
"yām": "जुन",
"yān": "जसलाई",
"yānti": "जान्छन्",
"yāsyasi": "जानेछौ",
"yātayāmam": "बासी",
"yāti": "जान्छ",
"yāvat": "जति",
"yāvān": "जति",
"yāḥ": "जुन",
"ā": "सम्म",
"ācaran": "गर्दै",
"ācarataḥ": "गर्नेको",
"ācarati": "गर्छ",
"ācāraḥ": "आचरण",
"ācārya": "हे गुरु",
"ācāryam": "गुरुलाई",
"ācāryopāsanam": "गुरुसेवा",
"ācāryān": "गुरुहरूलाई",
"ācāryāḥ": "गुरुहरू",
"ādarśaḥ": "ऐना",
"ādatte": "ग्रहण गर्छ",
"ādau": "सुरुमा",
"ādhatsva": "स्थिर गर",
"ādhipatyam": "स्वामित्व",
"ādhāya": "स्थिर गरेर",
"ādi": "आदि",
"ādidevam": "आदि देवतालाई",
"ādidevaḥ": "आदि देवता",
"ādikartre": "आदि सृष्टिकर्तालाई",
"ādim": "आदि",
"ādityagatam": "सूर्यमा रहेको",
"ādityavarṇam": "सूर्यजस्तो तेजस्वी",
"ādityavat": "सूर्यझैं",
"ādityān": "आदित्यहरूलाई",
"ādityānām": "आदित्यहरूका",
"ādiḥ": "आदि",
"ādyam": "आदिम",
"ādīni": "आदि",
"āgacchet": "आउनुपर्छ",
"āgama": "आगमन",
"āgatāḥ": "पुगेका",
"āha": "भने",
"āhave": "युद्धमा",
"āho": "वा",
"āhuḥ": "भन्छन्",
"āhāra": "आहारमा",
"āhāraḥ": "आहार",
"āhārāḥ": "आहारहरू",
"ājyam": "घिउ",
"ākhyāhi": "भन",
"ākhyātam": "घोषित",
"ākula": "आकुल",
"ākāśam": "आकाश",
"ākāśasthitaḥ": "आकाशमा रहने",
"āmaya": "रोग",
"ānaka": "नगारा",
"āpannam": "प्राप्त गरेको",
"āpannāḥ": "प्रवेश गरेका",
"āpaḥ": "जल",
"āpnoti": "प्राप्त गर्दछ",
"āpnuvanti": "पाउँछन्",
"āpnuyām": "पाऊँ",
"āptum": "पुग्न",
"āpūrya": "भरेर",
"āpūryamāṇam": "भरिइरहेको",
"ārabhate": "सुरु गर्छ",
"ārabhyate": "सुरु हुन्छ",
"ārambhaḥ": "आरम्भ",
"ārjavam": "सरलता",
"ārogya": "स्वास्थ्य",
"ārtaḥ": "दुःखी",
"ārurukṣoḥ": "चढ्न चाहनेको",
"ārādhanam": "पूजा",
"ārāmaḥ": "रम्ने",
"āsadam": "पार गर्न",
"āsakta": "आसक्त",
"āsam": "थिएँ",
"āsana": "बस्दा",
"āsanam": "आसन",
"āsane": "आसनमा",
"āsaṅgam": "आसक्ति",
"āste": "बस्छ",
"āsthitaḥ": "स्थित",
"āsthitāḥ": "पुगेका",
"āsthāya": "अनुसरण गरेर",
"āstikyam": "आस्तिक्य",
"āsuram": "आसुरी",
"āsuraniścayān": "आसुरी संकल्पका",
"āsuraḥ": "आसुरी",
"āsurāḥ": "आसुरीहरू",
"āsurī": "आसुरी",
"āsurīm": "आसुरी",
"āsurīṣu": "आसुरी",
"āsādya": "प्राप्त गरेर",
"āsīnam": "बसेको",
"āsīnaḥ": "बसेको",
"āsīta": "बसोस्",
"ātatāyinaḥ": "आक्रमणकारीहरू",
"ātiṣṭha": "दृढ रह",
"ātma": "आत्मा",
"ātmabhāvasthaḥ": "तिनको हृदयमा बस्ने",
"ātmabuddhiprasādajam": "आत्माको स्पष्टताबाट जन्मेको",
"ātmanaḥ": "आत्माको",
"ātmani": "आत्मामा",
"ātmanā": "आत्माद्वारा",
"ātmaparadeheṣu": "आफ्नो र अरूको शरीरमा",
"ātmasambhāvitāḥ": "आत्माभिमानी",
"ātmasaṁstham": "आत्मामा विश्राम गर्ने",
"ātmaupamyena": "आफूसँग तुलना गरेर",
"ātmavantam": "आत्मायुक्त",
"ātmavaśyaiḥ": "आत्मसंयमीहरूद्वारा",
"ātmavibhūtayaḥ": "मेरा विभूतिहरू",
"ātmavinigrahaḥ": "आत्मसंयम",
"ātmaviśuddhaye": "आत्मशुद्धिका निम्ति",
"ātmavān": "आत्मायुक्त",
"ātmayogāt": "आफ्नै शक्तिले",
"ātmaśuddhaye": "आत्मशुद्धिका निम्ति",
"ātmā": "आत्मा",
"ātmānam": "आत्मालाई",
"ātmānaḥ": "जसका आत्मा",
"āttha": "भन्यौ",
"ātyantikam": "असीम",
"āvahaḥ": "ल्याउने",
"āvartate": "फर्कन्छ",
"āvayoḥ": "हामी दुवैको",
"āveśita": "स्थिर गरिएको",
"āveśya": "स्थिर गरेर",
"āviśya": "प्रवेश गरेर",
"āviṣṭam": "ग्रस्त",
"āviṣṭaḥ": "ग्रस्त",
"āvriyate": "ढाकिन्छ",
"āvṛtam": "ढाकिएको",
"āvṛtaḥ": "ढाकिएको",
"āvṛttim": "फिर्ती",
"āvṛtya": "ढाकेर",
"āvṛtāḥ": "ढाकिएका",
"āyudhānām": "हतियारहरूका",
"āyuḥ": "जीवन",
"āśayāt": "आफ्नो ठाउँबाट",
"āścaryavat": "आश्चर्यझैं",
"āścaryāṇi": "आश्चर्यहरू",
"āśrayet": "आश्रय लिन्थ्यो",
"āśritam": "लगाएको",
"āśritaḥ": "आश्रित",
"āśritya": "आश्रय गरेर",
"āśritāḥ": "शरण लिएका",
"āśu": "छिट्टै",
"āśvāsayāmāsa": "सान्त्वना दिए",
"āśāpāśaśataiḥ": "सयौं आशाका बन्धनले",
"āḍhyaḥ": "धनी",
"īdṛk": "यस्तो",
"īdṛśam": "यस्तो",
"īhante": "प्रयत्न गर्छन्",
"īhate": "खोज्छ",
"īkṣate": "देख्छ",
"īkṣaṇam": "आँखा",
"īśam": "हे प्रभु",
"īśvarabhāvaḥ": "ईश्वरत्व",
"īśvaram": "ईश्वरलाई",
"īśvaraḥ": "ईश्वर",
"īḍyam": "हे पूजनीय",
"śabdabrahma": "शब्दब्रह्म",
"śabdaḥ": "शब्द",
"śabdādīn": "शब्द आदि",
"śaibyaḥ": "शैब्य",
"śaknomi": "सक्छु",
"śaknoti": "सक्छ",
"śaknoṣi": "सक्छौ",
"śakyam": "सम्भव",
"śakyase": "सक्छौ",
"śakyaḥ": "सक्ने",
"śamam": "शान्ति",
"śamaḥ": "शान्ति",
"śanaiḥ": "बिस्तारै",
"śaraṇam": "शरण",
"śarma": "शरण",
"śarīra": "शरीरको",
"śarīram": "शरीर",
"śarīrastham": "शरीरमा बस्ने",
"śarīrasthaḥ": "शरीरमा बस्ने",
"śarīravāṅmanobhiḥ": "शरीर, वाणी र मनले",
"śarīrayātrā": "शरीरको निर्वाह",
"śarīre": "शरीरमा",
"śarīriṇaḥ": "देहधारीको",
"śarīrāṇi": "शरीरहरू",
"śastra": "शस्त्र",
"śastrabhṛtām": "हतियारधारीहरूका",
"śastram": "शस्त्र",
"śastreṇa": "बन्चरोले",
"śastrāṇi": "शस्त्रहरू",
"śataśaḥ": "सयौं",
"śatrau": "शत्रुमा",
"śatrum": "शत्रुलाई",
"śatrutve": "शत्रुको रूपमा",
"śatruvat": "शत्रुझैं",
"śatruḥ": "शत्रु",
"śatrūn": "शत्रुहरूलाई",
"śaucam": "शुद्धता",
"śauryam": "शौर्य",
"śayyā": "विश्राममा",
"śaśisūryanetram": "चन्द्र-सूर्य आँखा भएको",
"śaśisūryayoḥ": "चन्द्र-सूर्यको",
"śaśvat": "स्थायी",
"śaśāṅkaḥ": "चन्द्रमा",
"śaśī": "चन्द्रमा",
"śaṁsasi": "प्रशंसा गर्छौ",
"śaṅkaraḥ": "शङ्कर",
"śaṅkham": "शङ्ख",
"śaṅkhau": "दुई शङ्ख",
"śaṅkhān": "शङ्खहरूलाई",
"śaṅkhāḥ": "शङ्खहरू",
"śaṭhaḥ": "कपटी",
"śikhariṇām": "पर्वतहरूका",
"śikhaṇḍī": "शिखण्डी",
"śirasā": "शिरले",
"śiraḥ": "शिर",
"śiṣyaḥ": "शिष्य",
"śiṣyeṇa": "शिष्यद्वारा",
"śiṣṭa": "बचेको",
"śocati": "शोक गर्छ",
"śocitum": "शोक गर्न",
"śoka": "शोक",
"śokam": "शोक",
"śoṣayati": "सुकाउँछ",
"śraddadhānāḥ": "श्रद्धा गर्नेहरू",
"śraddhayā": "श्रद्धासाथ",
"śraddhaḥ": "श्रद्धा",
"śraddhā": "श्रद्धा",
"śraddhām": "श्रद्धा",
"śraddhāmayaḥ": "श्रद्धामय",
"śraddhāvantaḥ": "श्रद्धावान्हरू",
"śraddhāvirahitam": "श्रद्धारहित",
"śraddhāvān": "श्रद्धावान्",
"śreyaḥ": "कल्याण",
"śreyān": "उत्तम",
"śreṣṭhaḥ": "श्रेष्ठ",
"śritāḥ": "आश्रित",
"śrotavyasya": "सुन्नुपर्नेको",
"śrotram": "श्रवण",
"śrotrādīni": "श्रवण आदि",
"śroṣyasi": "सुन्नेछौ",
"śrutam": "सुनिएको",
"śrutasya": "सुनिएकोको",
"śrutau": "सुनिएको",
"śrutavān": "सुनेँ",
"śruti": "श्रुतिको",
"śrutimat": "कान भएको",
"śrutiparāyaṇāḥ": "सुनिएको कुरामा समर्पित",
"śrutvā": "सुनेर",
"śrībhagavān": "श्रीभगवान्",
"śrīmat": "तेजस्वी",
"śrīmatām": "समृद्धहरूका",
"śrīḥ": "समृद्धि",
"śubha": "असल",
"śubhān": "शुभ",
"śubhāśubhaparityāgī": "असल-नराम्रो त्याग्ने",
"śubhāśubhaphalaiḥ": "असल-नराम्रो फलले",
"śucau": "शुद्धमा",
"śucaḥ": "शोक गर्छौ",
"śuciḥ": "शुद्ध",
"śucīnām": "शुद्धहरूका",
"śuklakṛṣṇe": "शुक्ल र कृष्ण",
"śuklaḥ": "शुक्ल पक्ष",
"śuni": "कुकुरमा",
"śvapāke": "चाण्डालमा",
"śvasan": "श्वास फेर्दै",
"śvaśurān": "ससुराहरूलाई",
"śvaśurāḥ": "ससुराहरू",
"śvetaiḥ": "सेता",
"śyālāḥ": "सालाहरू",
"śādhi": "सिकाऊ",
"śākham": "हाँगा",
"śākhāḥ": "हाँगाहरू",
"śānta": "शान्त",
"śāntaḥ": "शान्त",
"śāntim": "शान्ति",
"śāntiḥ": "शान्ति",
"śārīram": "शरीरको",
"śāstram": "शास्त्र",
"śāstravidhim": "शास्त्रको विधान",
"śāstravidhānoktam": "शास्त्रले विधान गरेको",
"śāśvatadharmagoptā": "नित्य धर्मका रक्षक",
"śāśvatam": "शाश्वत",
"śāśvatasya": "नित्यको",
"śāśvataḥ": "शाश्वत",
"śāśvate": "नित्य",
"śāśvatāḥ": "नित्य",
"śāśvatīḥ": "असंख्य",
"śīlasya": "आसक्तको",
"śīta": "जाडो",
"śītoṣṇa": "जाडो-गर्मी",
"śūdrasya": "शूद्रको",
"śūdrāḥ": "शूद्रहरू",
"śūdrāṇām": "शूद्रहरूका",
"śūrāḥ": "वीरहरू",
"śṛṇoti": "सुन्छ",
"śṛṇu": "सुन",
"śṛṇuyāt": "सुन्नुपर्छ",
"śṛṇvan": "सुन्दै",
"śṛṇvataḥ": "सुन्नेको",
"ūrdhva": "माथि",
"ūrdhvam": "माथि",
"ūrjitam": "बलवान्",
"ṛcchati": "प्राप्त गर्छ",
"ṛddham": "समृद्ध",
"ṛk": "ऋक्",
"ṛtam": "सत्य",
"ṛte": "बिना",
"ṛtūnām": "ऋतुहरूमा",
"ṛṣabha": "हे श्रेष्ठ",
"ṛṣayaḥ": "ऋषिहरू",
"ṛṣibhiḥ": "ऋषिहरूद्वारा",
"ṛṣīn": "ऋषिहरूलाई",
"ṣaṇmāsāḥ": "छ महिना",
}
