# -*- coding: utf-8 -*-
"""padachheda_ch9.py — per-pāda pada-chheda (word splits) for all 34 verses of Gita Chapter 9.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH9_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["इदम्", "idam", "this"],
        ["तु", "tu", "but"],
        ["ते", "te", "to you"],
        ["गुह्यतमम्", "guhyatamam", "the profoundest secret"]],
    1: [["प्रवक्ष्यामि", "pravakṣyāmi", "I will declare"],
        ["अनसूयवे", "anasūyave", "to one who does not carp"]],
    2: [["ज्ञानम्", "jñānam", "knowledge"],
        ["विज्ञानसहितम्", "vijñānasahitam", "with realization"]],
    3: [["यत्", "yat", "which"],
        ["ज्ञात्वा", "jñātvā", "knowing"],
        ["मोक्ष्यसे", "mokṣyase", "you will be freed"],
        ["अशुभात्", "aśubhāt", "from evil"]]},

2: {"s": [],
    0: [["राजविद्या", "rājavidyā", "the royal knowledge"],
        ["राजगुह्यम्", "rājaguhyam", "the royal secret"]],
    1: [["पवित्रम्", "pavitram", "the purifier"],
        ["इदम्", "idam", "this"],
        ["उत्तमम्", "uttamam", "supreme"]],
    2: [["प्रत्यक्षावगमम्", "pratyakṣāvagamam", "directly perceived"],
        ["धर्म्यम्", "dharmyam", "righteous"]],
    3: [["सुसुखम्", "susukham", "very easy"],
        ["कर्तुम्", "kartum", "to practise"],
        ["अव्ययम्", "avyayam", "imperishable"]]},

3: {"s": [],
    0: [["अश्रद्दधानाः", "aśraddadhānāḥ", "those without faith"],
        ["पुरुषाः", "puruṣāḥ", "men"]],
    1: [["धर्मस्य", "dharmasya", "in this dharma"],
        ["अस्य", "asya", "this"],
        ["परन्तप", "parantapa", "O scorcher of foes"]],
    2: [["अप्राप्य", "aprāpya", "not reaching"],
        ["माम्", "mām", "me"],
        ["निवर्तन्ते", "nivartante", "they return"]],
    3: [["मृत्युसंसारवर्त्मनि", "mṛtyusaṁsāravartmani", "on the path of death and rebirth"]]},

4: {"s": [],
    0: [["मया", "mayā", "by me"],
        ["ततम्", "tatam", "pervaded"],
        ["इदम्", "idam", "this"],
        ["सर्वम्", "sarvam", "all"]],
    1: [["जगत्", "jagat", "world"],
        ["अव्यक्तमूर्तिना", "avyaktamūrtinā", "by the unmanifest form"]],
    2: [["मत्स्थानि", "matsthāni", "resting in me"],
        ["सर्वभूतानि", "sarvabhūtāni", "all beings"]],
    3: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["अहम्", "aham", "I"],
        ["तेषु", "teṣu", "in them"],
        ["अवस्थितः", "avasthitaḥ", "situated"]]},

5: {"s": [],
    0: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["मत्स्थानि", "matsthāni", "resting in me"],
        ["भूतानि", "bhūtāni", "beings"]],
    1: [["पश्य", "paśya", "behold"],
        ["मे", "me", "my"],
        ["योगम्", "yogam", "yoga"],
        ["ऐश्वरम्", "aiśvaram", "divine"]],
    2: [["भूतभृत्", "bhūtabhṛt", "upholding beings"],
        ["न", "na", "not"],
        ["च", "ca", "and"],
        ["भूतस्थः", "bhūtasthaḥ", "abiding in beings"]],
    3: [["मम", "mama", "my"],
        ["आत्मा", "ātmā", "self"],
        ["भूतभावनः", "bhūtabhāvanaḥ", "the origin of beings"]]},

6: {"s": [],
    0: [["यथा", "yathā", "as"],
        ["आकाशस्थितः", "ākāśasthitaḥ", "abiding in space"],
        ["नित्यम्", "nityam", "always"]],
    1: [["वायुः", "vāyuḥ", "the wind"],
        ["सर्वत्रगः", "sarvatragaḥ", "moving everywhere"],
        ["महान्", "mahān", "great"]],
    2: [["तथा", "tathā", "so"],
        ["सर्वाणि", "sarvāṇi", "all"],
        ["भूतानि", "bhūtāni", "beings"]],
    3: [["मत्स्थानि", "matsthāni", "abiding in me"],
        ["इति", "iti", "thus"],
        ["उपधारय", "upadhāraya", "know"]]},

7: {"s": [],
    0: [["सर्वभूतानि", "sarvabhūtāni", "all beings"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    1: [["प्रकृतिम्", "prakṛtim", "into my nature"],
        ["यान्ति", "yānti", "go"],
        ["मामिकाम्", "māmikām", "mine"]],
    2: [["कल्पक्षये", "kalpakṣaye", "at the end of the kalpa"],
        ["पुनः", "punaḥ", "again"],
        ["तानि", "tāni", "them"]],
    3: [["कल्पादौ", "kalpādau", "at the beginning of the kalpa"],
        ["विसृजामि", "visṛjāmi", "I send forth"],
        ["अहम्", "aham", "I"]]},

8: {"s": [],
    0: [["प्रकृतिम्", "prakṛtim", "my nature"],
        ["स्वाम्", "svām", "own"],
        ["अवष्टभ्य", "avaṣṭabhya", "having taken hold of"]],
    1: [["विसृजामि", "visṛjāmi", "I send forth"],
        ["पुनः", "punaḥ", "again"],
        ["पुनः", "punaḥ", "and again"]],
    2: [["भूतग्रामम्", "bhūtagrāmam", "the host of beings"],
        ["इमम्", "imam", "this"],
        ["कृत्स्नम्", "kṛtsnam", "entire"]],
    3: [["अवशम्", "avaśam", "helpless"],
        ["प्रकृतेः", "prakṛteḥ", "of nature"],
        ["वशात्", "vaśāt", "under the power"]]},

9: {"s": [],
    0: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["माम्", "mām", "me"],
        ["तानि", "tāni", "those"],
        ["कर्माणि", "karmāṇi", "actions"]],
    1: [["निबध्नन्ति", "nibadhnanti", "bind"],
        ["धनञ्जय", "dhanañjaya", "O Dhanañjaya"]],
    2: [["उदासीनवत्", "udāsīnavat", "like one indifferent"],
        ["आसीनम्", "āsīnam", "sitting"]],
    3: [["असक्तम्", "asaktam", "unattached"],
        ["तेषु", "teṣu", "to those"],
        ["कर्मसु", "karmasu", "actions"]]},

10: {"s": [],
     0: [["मया", "mayā", "by me"],
         ["अध्यक्षेण", "adhyakṣeṇa", "by supervision"]],
     1: [["प्रकृतिः", "prakṛtiḥ", "nature"],
         ["सूयते", "sūyate", "brings forth"],
         ["सचराचरम्", "sacarācaram", "the moving and unmoving"]],
     2: [["हेतुना", "hetunā", "for this reason"],
         ["अनेन", "anena", "this"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["जगत्", "jagat", "the world"],
         ["विपरिवर्तते", "viparivartate", "revolves"]]},

11: {"s": [],
     0: [["अवजानन्ति", "avajānanti", "they despise"],
         ["माम्", "mām", "me"],
         ["मूढाः", "mūḍhāḥ", "the deluded"]],
     1: [["मानुषीम्", "mānuṣīm", "human"],
         ["तनुम्", "tanum", "form"],
         ["आश्रितम्", "āśritam", "wearing"]],
     2: [["परम्", "param", "the supreme"],
         ["भावम्", "bhāvam", "being"],
         ["अजानन्तः", "ajānantaḥ", "not knowing"]],
     3: [["मम", "mama", "my"],
         ["भूतमहेश्वरम्", "bhūtamaheśvaram", "the great Lord of beings"]]},

12: {"s": [],
     0: [["मोघाशाः", "moghāśāḥ", "of vain hopes"],
         ["मोघकर्माणः", "moghakarmāṇaḥ", "of vain works"]],
     1: [["मोघज्ञानाः", "moghajñānāḥ", "of vain knowledge"],
         ["विचेतसः", "vicetasaḥ", "senseless"]],
     2: [["राक्षसीम्", "rākṣasīm", "demoniac"],
         ["आसुरीम्", "āsurīm", "asuric"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     3: [["प्रकृतिम्", "prakṛtim", "nature"],
         ["मोहिनीम्", "mohinīm", "deluding"],
         ["श्रिताः", "śritāḥ", "clinging to"]]},

13: {"s": [],
     0: [["महात्मानः", "mahātmānaḥ", "the great souls"],
         ["तु", "tu", "but"],
         ["माम्", "mām", "me"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     1: [["दैवीम्", "daivīm", "divine"],
         ["प्रकृतिम्", "prakṛtim", "nature"],
         ["आश्रिताः", "āśritāḥ", "taking refuge in"]],
     2: [["भजन्ति", "bhajanti", "they worship"],
         ["अनन्यमनसः", "ananyamanasaḥ", "with undivided mind"]],
     3: [["ज्ञात्वा", "jñātvā", "having known"],
         ["भूतादिम्", "bhūtādim", "the source of beings"],
         ["अव्ययम्", "avyayam", "imperishable"]]},

14: {"s": [],
     0: [["सततम्", "satatam", "always"],
         ["कीर्तयन्तः", "kīrtayantaḥ", "glorifying"],
         ["माम्", "mām", "me"]],
     1: [["यतन्तः", "yatantaḥ", "striving"],
         ["च", "ca", "and"],
         ["दृढव्रताः", "dṛḍhavratāḥ", "with firm vows"]],
     2: [["नमस्यन्तः", "namasyantaḥ", "bowing"],
         ["च", "ca", "and"],
         ["माम्", "mām", "me"],
         ["भक्त्या", "bhaktyā", "with devotion"]],
     3: [["नित्ययुक्ताः", "nityayuktāḥ", "ever united"],
         ["उपासते", "upāsate", "worship"]]},

15: {"s": [],
     0: [["ज्ञानयज्ञेन", "jñānayajñena", "with the sacrifice of knowledge"],
         ["च", "ca", "and"],
         ["अपि", "api", "also"],
         ["अन्ये", "anye", "others"]],
     1: [["यजन्तः", "yajantaḥ", "worshipping"],
         ["माम्", "mām", "me"],
         ["उपासते", "upāsate", "they worship"]],
     2: [["एकत्वेन", "ekatvena", "as one"],
         ["पृथक्त्वेन", "pṛthaktvena", "as distinct"]],
     3: [["बहुधा", "bahudhā", "in many ways"],
         ["विश्वतोमुखम्", "viśvatomukham", "facing everywhere"]]},

16: {"s": [],
     0: [["अहम्", "aham", "I"],
         ["क्रतुः", "kratur", "the rite"],
         ["अहम्", "aham", "I"],
         ["यज्ञः", "yajñaḥ", "the sacrifice"]],
     1: [["स्वधा", "svadhā", "the ancestral oblation"],
         ["अहम्", "aham", "I"],
         ["अहम्", "aham", "I"],
         ["औषधम्", "auṣadham", "the herb"]],
     2: [["मन्त्रः", "mantraḥ", "the mantra"],
         ["अहम्", "aham", "I"],
         ["अहम्", "aham", "I"],
         ["एव", "eva", "indeed"],
         ["आज्यम्", "ājyam", "the butter"]],
     3: [["अहम्", "aham", "I"],
         ["अग्निः", "agniḥ", "the fire"],
         ["अहम्", "aham", "I"],
         ["हुतम्", "hutam", "the offering"]]},

17: {"s": [],
     0: [["पिता", "pitā", "the father"],
         ["अहम्", "aham", "I"],
         ["अस्य", "asya", "of this"],
         ["जगतः", "jagataḥ", "world"]],
     1: [["माता", "mātā", "the mother"],
         ["धाता", "dhātā", "the supporter"],
         ["पितामहः", "pitāmahaḥ", "the grandsire"]],
     2: [["वेद्यम्", "vedyam", "to be known"],
         ["पवित्रम्", "pavitram", "the purifier"],
         ["ओङ्कारः", "oṅkāraḥ", "the syllable Om"]],
     3: [["ऋक्", "ṛk", "the Ṛk"],
         ["साम", "sāma", "the Sāma"],
         ["यजुः", "yajuḥ", "the Yajus"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]]},

18: {"s": [],
     0: [["गतिः", "gatiḥ", "the goal"],
         ["भर्ता", "bhartā", "the sustainer"],
         ["प्रभुः", "prabhuḥ", "the lord"],
         ["साक्षी", "sākṣī", "the witness"]],
     1: [["निवासः", "nivāsaḥ", "the abode"],
         ["शरणम्", "śaraṇam", "the refuge"],
         ["सुहृत्", "suhṛt", "the friend"]],
     2: [["प्रभवः", "prabhavaḥ", "the origin"],
         ["प्रलयः", "pralayaḥ", "the dissolution"],
         ["स्थानम्", "sthānam", "the ground"]],
     3: [["निधानम्", "nidhānam", "the treasure"],
         ["बीजम्", "bījam", "the seed"],
         ["अव्ययम्", "avyayam", "eternal"]]},

19: {"s": [],
     0: [["तपामि", "tapāmi", "I give heat"],
         ["अहम्", "aham", "I"],
         ["अहम्", "aham", "I"],
         ["वर्षम्", "varṣam", "the rain"]],
     1: [["निगृह्णामि", "nigṛhṇāmi", "I withhold"],
         ["उत्सृजामि", "utsṛjāmi", "I release"],
         ["च", "ca", "and"]],
     2: [["अमृतम्", "amṛtam", "immortality"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["मृत्युः", "mṛtyuḥ", "death"],
         ["च", "ca", "and"]],
     3: [["सत्", "sat", "the real"],
         ["असत्", "asat", "the unreal"],
         ["च", "ca", "and"],
         ["अहम्", "aham", "I"],
         ["अर्जुन", "arjuna", "O Arjuna"]]},

20: {"s": [],
     0: [["त्रैविद्याः", "traividyāḥ", "knowers of the three Vedas"],
         ["माम्", "mām", "me"],
         ["सोमपाः", "somapāḥ", "soma-drinkers"],
         ["पूतपापाः", "pūtapāpāḥ", "purified of sin"]],
     1: [["यज्ञैः", "yajñaiḥ", "by sacrifices"],
         ["इष्ट्वा", "iṣṭvā", "having worshipped"],
         ["स्वर्गतिम्", "svargatim", "the path to heaven"],
         ["प्रार्थयन्ते", "prārthayante", "they pray for"]],
     2: [["ते", "te", "they"],
         ["पुण्यम्", "puṇyam", "merit"],
         ["आसाद्य", "āsādya", "having attained"],
         ["सुरेन्द्रलोकम्", "surendralokam", "the world of Indra"]],
     3: [["अश्नन्ति", "aśnanti", "they enjoy"],
         ["दिव्यान्", "divyān", "divine"],
         ["दिवि", "divi", "in heaven"],
         ["देवभोगान्", "devabhogān", "pleasures of the gods"]]},

21: {"s": [],
     0: [["ते", "te", "they"],
         ["तम्", "tam", "that"],
         ["भुक्त्वा", "bhuktvā", "having enjoyed"],
         ["स्वर्गलोकम्", "svargalokam", "the world of heaven"],
         ["विशालम्", "viśālam", "vast"]],
     1: [["क्षीणे", "kṣīṇe", "when exhausted"],
         ["पुण्ये", "puṇye", "merit"],
         ["मर्त्यलोकम्", "martyalokam", "the world of mortals"],
         ["विशन्ति", "viśanti", "they enter"]],
     2: [["एवम्", "evam", "thus"],
         ["त्रयीधर्मम्", "trayīdharmam", "the dharma of the three Vedas"],
         ["अनुप्रपन्नाः", "anuprapannāḥ", "following"]],
     3: [["गतागतम्", "gatāgatam", "going and coming"],
         ["कामकामाः", "kāmakāmāḥ", "desiring desires"],
         ["लभन्ते", "labhante", "they obtain"]]},

22: {"s": [],
     0: [["अनन्याः", "ananyāḥ", "undivided"],
         ["चिन्तयन्तः", "cintayantaḥ", "thinking of"],
         ["माम्", "mām", "me"]],
     1: [["ये", "ye", "who"],
         ["जनाः", "janāḥ", "people"],
         ["पर्युपासते", "paryupāsate", "worship"]],
     2: [["तेषाम्", "teṣām", "of them"],
         ["नित्याभियुक्तानाम्", "nityābhiyuktānām", "ever devoted"]],
     3: [["योगक्षेमम्", "yogakṣemam", "what they lack and what they have"],
         ["वहामि", "vahāmi", "I carry"],
         ["अहम्", "aham", "I"]]},

23: {"s": [],
     0: [["ये", "ye", "who"],
         ["अपि", "api", "even"],
         ["अन्यदेवताभक्ताः", "anyadevatābhaktāḥ", "devotees of other gods"]],
     1: [["यजन्ते", "yajante", "worship"],
         ["श्रद्धया", "śraddhayā", "with faith"],
         ["अन्विताः", "anvitāḥ", "endowed"]],
     2: [["ते", "te", "they"],
         ["अपि", "api", "even"],
         ["माम्", "mām", "me"],
         ["एव", "eva", "alone"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["यजन्ति", "yajanti", "worship"],
         ["अविधिपूर्वकम्", "avidhipūrvakam", "not in the prescribed way"]]},

24: {"s": [],
     0: [["अहम्", "aham", "I"],
         ["हि", "hi", "indeed"],
         ["सर्वयज्ञानाम्", "sarvayajñānām", "of all sacrifices"]],
     1: [["भोक्ता", "bhoktā", "the enjoyer"],
         ["च", "ca", "and"],
         ["प्रभुः", "prabhuḥ", "the lord"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["न", "na", "not"],
         ["तु", "tu", "but"],
         ["माम्", "mām", "me"],
         ["अभिजानन्ति", "abhijānanti", "they know"]],
     3: [["तत्त्वेन", "tattvena", "in truth"],
         ["अतः", "ataḥ", "therefore"],
         ["च्यवन्ति", "cyavanti", "they fall"],
         ["ते", "te", "they"]]},

25: {"s": [],
     0: [["यान्ति", "yānti", "they go"],
         ["देवव्रताः", "devavratāḥ", "the worshippers of gods"],
         ["देवान्", "devān", "to the gods"]],
     1: [["पितॄन्", "pitṝn", "the ancestors"],
         ["यान्ति", "yānti", "they go"],
         ["पितृव्रताः", "pitṛvratāḥ", "the ancestor-worshippers"]],
     2: [["भूतानि", "bhūtāni", "the spirits"],
         ["यान्ति", "yānti", "they go"],
         ["भूतेज्याः", "bhūtejyāḥ", "the spirit-worshippers"]],
     3: [["यान्ति", "yānti", "they go"],
         ["मद्याजिनः", "madyājinaḥ", "my worshippers"],
         ["अपि", "api", "even"],
         ["माम्", "mām", "to me"]]},

26: {"s": [],
     0: [["पत्रम्", "patram", "a leaf"],
         ["पुष्पम्", "puṣpam", "a flower"],
         ["फलम्", "phalam", "a fruit"],
         ["तोयम्", "toyam", "water"]],
     1: [["यः", "yaḥ", "whoever"],
         ["मे", "me", "to me"],
         ["भक्त्या", "bhaktyā", "with devotion"],
         ["प्रयच्छति", "prayacchati", "offers"]],
     2: [["तत्", "tat", "that"],
         ["अहम्", "aham", "I"],
         ["भक्त्युपहृतम्", "bhaktyupahṛtam", "offered with devotion"]],
     3: [["अश्नामि", "aśnāmi", "I accept"],
         ["प्रयतात्मनः", "prayatātmanaḥ", "of the pure-hearted"]]},

27: {"s": [],
     0: [["यत्", "yat", "whatever"],
         ["करोषि", "karoṣi", "you do"],
         ["यत्", "yat", "whatever"],
         ["अश्नासि", "aśnāsi", "you eat"]],
     1: [["यत्", "yat", "whatever"],
         ["जुहोषि", "juhoṣi", "you offer"],
         ["ददासि", "dadāsi", "you give"],
         ["यत्", "yat", "whatever"]],
     2: [["यत्", "yat", "whatever"],
         ["तपस्यसि", "tapasyasi", "you practise as austerity"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["तत्", "tat", "that"],
         ["कुरुष्व", "kuruṣva", "do"],
         ["मदर्पणम्", "madarpaṇam", "as an offering to me"]]},

28: {"s": [],
     0: [["शुभाशुभफलैः", "śubhāśubhaphalaiḥ", "with the fruits of good and evil"],
         ["एवम्", "evam", "thus"],
         ["मोक्ष्यसे", "mokṣyase", "you will be freed"]],
     1: [["कर्मबन्धनैः", "karmabandhanaiḥ", "from the bonds of action"]],
     2: [["सन्न्यासयोगयुक्तात्मा", "sannyāsayogayuktātmā", "with the self yoked in renunciation"],
         ["विमुक्तः", "vimuktaḥ", "liberated"]],
     3: [["माम्", "mām", "to me"],
         ["उपैष्यसि", "upaiṣyasi", "you will come"]]},

29: {"s": [],
     0: [["समः", "samaḥ", "the same"],
         ["अहम्", "aham", "I"],
         ["सर्वभूतेषु", "sarvabhūteṣu", "to all beings"]],
     1: [["न", "na", "not"],
         ["मे", "me", "to me"],
         ["द्वेष्यः", "dveṣyaḥ", "hated"],
         ["अस्ति", "asti", "is"],
         ["न", "na", "nor"],
         ["प्रियः", "priyaḥ", "dear"]],
     2: [["ये", "ye", "who"],
         ["भजन्ति", "bhajanti", "worship"],
         ["तु", "tu", "but"],
         ["माम्", "mām", "me"],
         ["भक्त्या", "bhaktyā", "with devotion"]],
     3: [["मयि", "mayi", "in me"],
         ["ते", "te", "they"],
         ["तेषु", "teṣu", "in them"],
         ["च", "ca", "and"],
         ["अपि", "api", "indeed"],
         ["अहम्", "aham", "I"]]},

30: {"s": [],
     0: [["अपि", "api", "even"],
         ["चेत्", "cet", "if"],
         ["सुदुराचारः", "sudurācāraḥ", "of very evil conduct"]],
     1: [["भजते", "bhajate", "worships"],
         ["माम्", "mām", "me"],
         ["अनन्यभाक्", "ananyabhāk", "with single devotion"]],
     2: [["साधुः", "sādhuḥ", "good"],
         ["एव", "eva", "indeed"],
         ["सः", "saḥ", "he"],
         ["मन्तव्यः", "mantavyaḥ", "is to be regarded"]],
     3: [["सम्यग्व्यवसितः", "samyagvyavasitaḥ", "rightly resolved"],
         ["हि", "hi", "indeed"],
         ["सः", "saḥ", "he"]]},

31: {"s": [],
     0: [["क्षिप्रम्", "kṣipram", "quickly"],
         ["भवति", "bhavati", "he becomes"],
         ["धर्मात्मा", "dharmātmā", "righteous of soul"]],
     1: [["शश्वत्", "śaśvat", "lasting"],
         ["शान्तिम्", "śāntim", "peace"],
         ["निगच्छति", "nigacchati", "attains"]],
     2: [["कौन्तेय", "kaunteya", "O son of Kuntī"],
         ["प्रतिजानीहि", "pratijānīhi", "know for certain"]],
     3: [["न", "na", "not"],
         ["मे", "me", "my"],
         ["भक्तः", "bhaktaḥ", "devotee"],
         ["प्रणश्यति", "praṇaśyati", "perishes"]]},

32: {"s": [],
     0: [["माम्", "mām", "me"],
         ["हि", "hi", "indeed"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["व्यपाश्रित्य", "vyapāśritya", "taking refuge in"]],
     1: [["ये", "ye", "who"],
         ["अपि", "api", "even"],
         ["स्युः", "syuḥ", "may be"],
         ["पापयोनयः", "pāpayonayaḥ", "of sinful birth"]],
     2: [["स्त्रियः", "striyaḥ", "women"],
         ["वैश्याः", "vaiśyāḥ", "traders"],
         ["तथा", "tathā", "also"],
         ["शूद्राः", "śūdrāḥ", "labourers"]],
     3: [["ते", "te", "they"],
         ["अपि", "api", "also"],
         ["यान्ति", "yānti", "reach"],
         ["पराम्", "parām", "the supreme"],
         ["गतिम्", "gatim", "goal"]]},

33: {"s": [],
     0: [["किम्", "kim", "how much more"],
         ["पुनः", "punaḥ", "again"],
         ["ब्राह्मणाः", "brāhmaṇāḥ", "the brāhmaṇas"],
         ["पुण्याः", "puṇyāḥ", "holy"]],
     1: [["भक्ताः", "bhaktāḥ", "devoted"],
         ["राजर्षयः", "rājarṣayaḥ", "royal sages"],
         ["तथा", "tathā", "also"]],
     2: [["अनित्यम्", "anityam", "impermanent"],
         ["असुखम्", "asukham", "joyless"],
         ["लोकम्", "lokam", "world"],
         ["इमम्", "imam", "this"]],
     3: [["प्राप्य", "prāpya", "having come to"],
         ["भजस्व", "bhajasva", "worship"],
         ["माम्", "mām", "me"]]},

34: {"s": [],
    0: [
    ["मन्मनाः", "manmanāḥ", "fixing the mind on me"], ["भव", "bhava", "be"],
        ["मद्भक्तः", "madbhaktaḥ", "my devotee"]],
    1: [
    ["मद्याजी", "madyājī", "offering to me"], ["माम्", "mām", "me"],
        ["नमस्कुरु", "namaskuru", "bow to"]],
    2: [
    ["माम्", "mām", "to me"], ["एव", "eva", "surely"],
        ["एष्यसि", "eṣyasi", "you will come"], ["युक्त्वा", "yuktvā", "having yoked"],
        ["एव", "eva", "(एवम्) indeed"]],
    3: [
    ["आत्मानम्", "ātmānam", "the self"], ["मत्परायणः", "matparāyaṇaḥ", "intent on me"]]
},
}
