# -*- coding: utf-8 -*-
"""padachheda_ch11.py — per-pāda pada-chheda (word splits) for all 55 verses of Gita Chapter 11.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH11_WORDS = {
1: {"s": [
    ["अर्जुनः", "arjunaḥ", "Arjuna"],
    ["उवाच", "uvāca", "said"]
],
    0: [
    ["मत्", "mat", "by my"],
        ["अनुग्रहाय", "anugrahāya", "for the favour, out of compassion"],
        ["परमम्", "paramam", "the supreme"]],
    1: [
    ["गुह्यम्", "guhyam", "secret"], ["अध्यात्म", "adhyātma", "of the Self"],
        ["संज्ञितम्", "saṁjñitam", "named, called"]],
    2: [
    ["यत्", "yat", "which"], ["त्वया", "tvayā", "by you"], ["उक्तम्", "uktam", "spoken"],
        ["वचः", "vacaḥ", "words"], ["तेन", "tena", "by that"]],
    3: [
    ["मोहः", "mohaḥ", "delusion"], ["अयम्", "ayam", "this"], ["विगतः", "vigataḥ", "gone"],
        ["मम", "mama", "my"]]
},
2: {"s": [],
    0: [
    ["भव", "bhava", "of coming into being"], ["अप्ययौ", "apyayau", "and passing away"],
        ["हि", "hi", "indeed"], ["भूतानाम्", "bhūtānām", "of beings"]],
    1: [
    ["श्रुतौ", "śrutau", "heard"], ["विस्तरशः", "vistaraśaḥ", "in detail"],
        ["मया", "mayā", "by me"]],
    2: [
    ["त्वत्तः", "tvattaḥ", "from you"],
        ["कमलपत्राक्ष", "kamalapatrākṣa", "O lotus-eyed one"]],
    3: [
    ["माहात्म्यम्", "māhātmyam", "the glory"], ["अपि", "api", "also"], ["च", "ca", "and"],
        ["अव्ययम्", "avyayam", "imperishable"]]
},
3: {"s": [],
    0: [
    ["एवम्", "evam", "thus"], ["एतत्", "etat", "this"], ["यथा", "yathā", "as"],
        ["आत्थ", "āttha", "you have said"], ["त्वम्", "tvam", "you"]],
    1: [
    ["आत्मानम्", "ātmānam", "yourself"], ["परमेश्वर", "parameśvara", "O supreme Lord"]],
    2: [
    ["द्रष्टुम्", "draṣṭum", "to see"], ["इच्छामि", "icchāmi", "I wish"],
        ["ते", "te", "your"], ["रूपम्", "rūpam", "form"]],
    3: [
    ["ऐश्वरम्", "aiśvaram", "divine, cosmic"],
        ["पुरुषोत्तम", "puruṣottama", "O best of persons"]]
},
4: {"s": [],
    0: [["मन्यसे", "manyase", "you think"],
        ["यदि", "yadi", "if"],
        ["तत्", "tat", "that"],
        ["शक्यम्", "śakyam", "possible"]],
    1: [["मया", "mayā", "by me"],
        ["द्रष्टुम्", "draṣṭum", "to be seen"],
        ["इति", "iti", "thus"],
        ["प्रभो", "prabho", "O Lord"]],
    2: [["योगेश्वर", "yogeśvara", "O Lord of yoga"],
        ["ततः", "tataḥ", "then"],
        ["मे", "me", "to me"],
        ["त्वम्", "tvam", "you"]],
    3: [["दर्शय", "darśaya", "show"],
        ["आत्मानम्", "ātmānam", "yourself"],
        ["अव्ययम्", "avyayam", "imperishable"]]},

5: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["पश्य", "paśya", "behold"],
        ["मे", "me", "my"],
        ["पार्थ", "pārtha", "O Pārtha"],
        ["रूपाणि", "rūpāṇi", "forms"]],
    1: [["शतशः", "śataśaḥ", "by hundreds"],
        ["अथ", "atha", "and"],
        ["सहस्रशः", "sahasraśaḥ", "by thousands"]],
    2: [["नानाविधानि", "nānāvidhāni", "of various kinds"],
        ["दिव्यानि", "divyāni", "divine"]],
    3: [["नानावर्णाकृतीनि", "nānāvarṇākṛtīni", "of various colors and shapes"],
        ["च", "ca", "and"]]},

6: {"s": [],
    0: [["पश्य", "paśya", "behold"],
        ["आदित्यान्", "ādityān", "the Ādityas"],
        ["वसून्", "vasūn", "the Vasus"],
        ["रुद्रान्", "rudrān", "the Rudras"]],
    1: [["अश्विनौ", "aśvinau", "the two Aśvins"],
        ["मरुतः", "marutaḥ", "the Maruts"],
        ["तथा", "tathā", "also"]],
    2: [["बहूनि", "bahūni", "many"],
        ["अदृष्टपूर्वाणि", "adṛṣṭapūrvāṇi", "never seen before"]],
    3: [["पश्य", "paśya", "behold"],
        ["आश्चर्याणि", "āścaryāṇi", "wonders"],
        ["भारत", "bhārata", "O Bhārata"]]},

7: {"s": [],
    0: [["इह", "iha", "here"],
        ["एकस्थम्", "ekastham", "gathered in one place"],
        ["जगत्", "jagat", "the world"],
        ["कृत्स्नम्", "kṛtsnam", "whole"]],
    1: [["पश्य", "paśya", "behold"],
        ["अद्य", "adya", "now"],
        ["सचराचरम्", "sacarācaram", "moving and unmoving"]],
    2: [["मम", "mama", "my"],
        ["देहे", "dehe", "in the body"],
        ["गुडाकेश", "guḍākeśa", "O Guḍākeśa"]],
    3: [["यत्", "yat", "whatever"],
        ["च", "ca", "and"],
        ["अन्यत्", "anyat", "other"],
        ["द्रष्टुम्", "draṣṭum", "to see"],
        ["इच्छसि", "icchasi", "you wish"]]},

8: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["न", "na", "not"],
        ["तु", "tu", "but"],
        ["माम्", "mām", "me"],
        ["शक्यसे", "śakyase", "you are able"],
        ["द्रष्टुम्", "draṣṭum", "to see"]],
    1: [["अनेन", "anena", "with this"],
        ["एव", "eva", "very"],
        ["स्वचक्षुषा", "svacakṣuṣā", "your own eye"]],
    2: [["दिव्यम्", "divyam", "the divine"],
        ["ददामि", "dadāmi", "I give"],
        ["ते", "te", "to you"],
        ["चक्षुः", "cakṣuḥ", "eye"]],
    3: [["पश्य", "paśya", "behold"],
        ["मे", "me", "my"],
        ["योगम्", "yogam", "sovereignty"],
        ["ऐश्वरम्", "aiśvaram", "divine"]]},

9: {"s": [["सञ्जयः", "sañjayaḥ", "Sañjaya"], ["उवाच", "uvāca", "said"]],
    0: [["एवम्", "evam", "thus"],
        ["उक्त्वा", "uktvā", "having spoken"],
        ["ततः", "tataḥ", "then"],
        ["राजन्", "rājan", "O king"]],
    1: [["महायोगेश्वरः", "mahāyogeśvaraḥ", "the great Lord of yoga"],
        ["हरिः", "hariḥ", "Hari"]],
    2: [["दर्शयामास", "darśayāmāsa", "showed"],
        ["पार्थाय", "pārthāya", "to Pārtha"]],
    3: [["परमम्", "paramam", "the supreme"],
        ["रूपम्", "rūpam", "form"],
        ["ऐश्वरम्", "aiśvaram", "divine"]]},

10: {"s": [],
    0: [
    ["अनेकवक्त्रनयनम्", "anekavaktranayanam", "with many mouths and eyes"]],
    1: [
    ["अनेकाद्भुतदर्शनम्", "anekādbhutadarśanam", "with many wondrous sights"]],
    2: [
    ["अनेकदिव्याभरणम्", "anekadivyābharaṇam", "with many divine ornaments"]],
    3: [
    ["दिव्यानेकोद्यतायुधम्", "divyānekodyatāyudham", "with many uplifted divine weapons"]]
},
11: {"s": [],
    0: [
    ["दिव्यमाल्याम्बरधरम्", "divyamālyāmbaradharam", "wearing divine garlands and robes"]],
    1: [
    ["दिव्यगन्धानुलेपनम्", "divyagandhānulepanam", "anointed with divine perfumes"]],
    2: [
    ["सर्वाश्चर्यमयम्", "sarvāścaryamayam", "full of all wonders"],
        ["देवम्", "devam", "the God"]],
    3: [
    ["अनन्तम्", "anantam", "the infinite"],
        ["विश्वतोमुखम्", "viśvatomukham", "facing everywhere"]]
},
12: {"s": [],
    0: [
    ["दिवि", "divi", "in the sky"],
        ["सूर्यसहस्रस्य", "sūryasahasrasya", "of a thousand suns"]],
    1: [
    ["भवेत्", "bhavet", "would be"], ["युगपत्", "yugapat", "simultaneously"],
        ["उत्थिता", "utthitā", "arisen"]],
    2: [
    ["यदि", "yadi", "if"], ["भाः", "bhāḥ", "the splendour"],
        ["सदृशी", "sadṛśī", "similar"], ["सा", "sā", "that"],
        ["स्यात्", "syāt", "would be"]],
    3: [
    ["भासः", "bhāsaḥ", "the splendour"], ["तस्य", "tasya", "of that"],
        ["महात्मनः", "mahātmanaḥ", "great being"]]
},
13: {"s": [],
    0: [
    ["तत्र", "tatra", "there"], ["एकस्थम्", "ekastham", "gathered in one place"],
        ["जगत्", "jagat", "the universe"], ["कृत्स्नम्", "kṛtsnam", "whole"]],
    1: [
    ["प्रविभक्तम्", "pravibhaktam", "divided"], ["अनेकधा", "anekadhā", "in many ways"]],
    2: [
    ["अपश्यत्", "apaśyat", "saw"], ["देवदेवस्य", "devadevasya", "of the God of gods"]],
    3: [
    ["शरीरे", "śarīre", "in the body"], ["पाण्डवः", "pāṇḍavaḥ", "the son of Pāṇḍu"],
        ["तदा", "tadā", "then"]]
},
14: {"s": [],
     0: [["ततः", "tataḥ", "then"],
         ["सः", "saḥ", "he"],
         ["विस्मयाविष्टः", "vismayāviṣṭaḥ", "filled with wonder"]],
     1: [["हृष्टरोमा", "hṛṣṭaromā", "hair standing on end"],
         ["धनञ्जयः", "dhanañjayaḥ", "Dhanañjaya"]],
     2: [["प्रणम्य", "praṇamya", "having bowed"],
         ["शिरसा", "śirasā", "with the head"],
         ["देवम्", "devam", "to the God"]],
     3: [["कृताञ्जलिः", "kṛtāñjaliḥ", "with joined palms"],
         ["अभाषत", "abhāṣata", "spoke"]]},

15: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["पश्यामि", "paśyāmi", "I see"],
         ["देवान्", "devān", "the gods"],
         ["तव", "tava", "your"],
         ["देव", "deva", "O God"],
         ["देहे", "dehe", "in the body"]],
     1: [["सर्वान्", "sarvān", "all"],
         ["तथा", "tathā", "and"],
         ["भूतविशेषसंघान्", "bhūtaviśeṣasaṅghān", "the hosts of various beings"]],
     2: [["ब्रह्माणम्", "brahmāṇam", "Brahmā"],
         ["ईशम्", "īśam", "the Lord"],
         ["कमलासनस्थम्", "kamalāsanastham", "seated on the lotus"]],
     3: [["ऋषीन्", "ṛṣīn", "the seers"],
         ["च", "ca", "and"],
         ["सर्वान्", "sarvān", "all"],
         ["उरगान्", "uragān", "the serpents"],
         ["च", "ca", "and"],
         ["दिव्यान्", "divyān", "divine"]]},

16: {"s": [],
    0: [

        ["अनेकबाहूदरवक्त्रनेत्रम्", "anekabāhūdaravaktranetram", "with many arms, bellies, mouths and eyes"]],
    1: [
    ["पश्यामि", "paśyāmi", "I see"], ["त्वाम्", "tvām", "you"],
        ["सर्वतः", "sarvataḥ", "on every side"],
        ["अनन्तरूपम्", "anantarūpam", "of endless form"]],
    2: [
    ["न", "na", "no"], ["अन्तम्", "antam", "end"], ["न", "na", "nor"],
        ["मध्यम्", "madhyam", "middle"], ["न", "na", "nor"], ["पुनः", "punaḥ", "again"],
        ["तव", "tava", "your"], ["आदिम्", "ādim", "beginning"]],
    3: [
    ["पश्यामि", "paśyāmi", "I see"],
        ["विश्वेश्वर", "viśveśvara", "O Lord of the universe"],
        ["विश्वरूप", "viśvarūpa", "O cosmic form"]]
},
17: {"s": [],
     0: [["किरीटिनम्", "kirīṭinam", "wearing a crown"],
         ["गदिनम्", "gadinam", "wielding the mace"],
         ["चक्रिणम्", "cakriṇam", "wielding the discus"],
         ["च", "ca", "and"]],
     1: [["तेजोराशिम्", "tejorāśim", "a mass of light"],
         ["सर्वतः", "sarvataḥ", "on every side"],
         ["दीप्तिमन्तम्", "dīptimantam", "blazing"]],
     2: [["पश्यामि", "paśyāmi", "I see"],
         ["त्वाम्", "tvām", "you"],
         ["दुर्निरीक्ष्यम्", "durnirīkṣyam", "hard to gaze upon"],
         ["समन्तात्", "samantāt", "all around"]],
     3: [["दीप्तानलार्कद्युतिम्", "dīptānalārkadyutim", "with the brilliance of blazing fire and sun"],
         ["अप्रमेयम्", "aprameyam", "immeasurable"]]},

18: {"s": [],
     0: [["त्वम्", "tvam", "you"],
         ["अक्षरम्", "akṣaram", "the imperishable"],
         ["परमम्", "paramam", "supreme"],
         ["वेदितव्यम्", "veditavyam", "to be known"]],
     1: [["त्वम्", "tvam", "you"],
         ["अस्य", "asya", "of this"],
         ["विश्वस्य", "viśvasya", "universe"],
         ["परम्", "param", "the supreme"],
         ["निधानम्", "nidhānam", "refuge, treasure"]],
     2: [["त्वम्", "tvam", "you"],
         ["अव्ययः", "avyayaḥ", "imperishable"],
         ["शाश्वतधर्मगोप्ता", "śāśvatadharmagoptā", "the guardian of eternal dharma"]],
     3: [["सनातनः", "sanātanaḥ", "eternal"],
         ["त्वम्", "tvam", "you"],
         ["पुरुषः", "puruṣaḥ", "the Person"],
         ["मतः", "mataḥ", "deemed"],
         ["मे", "me", "by me"]]},

19: {"s": [],
     0: [["अनादिमध्यान्तम्", "anādimadhyāntam", "without beginning, middle or end"],
         ["अनन्तवीर्यम्", "anantavīryam", "of infinite power"]],
     1: [["अनन्तबाहुम्", "anantabāhum", "with countless arms"],
         ["शशिसूर्यनेत्रम्", "śaśisūryanetram", "with moon and sun for eyes"]],
     2: [["पश्यामि", "paśyāmi", "I see"],
         ["त्वाम्", "tvām", "you"],
         ["दीप्तहुताशवक्त्रम्", "dīptahutāśavaktram", "with blazing fire-like mouths"]],
     3: [["स्वतेजसा", "svatejasā", "with your own radiance"],
         ["विश्वम्", "viśvam", "the universe"],
         ["इदम्", "idam", "this"],
         ["तपन्तम्", "tapantam", "burning"]]},

20: {"s": [],
     0: [["द्यावापृथिव्योः", "dyāvāpṛthivyoḥ", "of heaven and earth"],
         ["इदम्", "idam", "this"],
         ["अन्तरम्", "antaram", "space between"],
         ["हि", "hi", "indeed"]],
     1: [["व्याप्तम्", "vyāptam", "filled"],
         ["त्वया", "tvayā", "by you"],
         ["एकेन", "ekena", "alone"],
         ["दिशः", "diśaḥ", "the directions"],
         ["च", "ca", "and"],
         ["सर्वाः", "sarvāḥ", "all"]],
     2: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
         ["अद्भुतम्", "adbhutam", "wondrous"],
         ["रूपम्", "rūpam", "form"],
         ["इदम्", "idam", "this"],
         ["तव", "tava", "your"],
         ["उग्रम्", "ugram", "terrible"]],
     3: [["लोकत्रयम्", "lokatrayam", "the three worlds"],
         ["प्रव्यथितम्", "pravyathitam", "trembling"],
         ["महात्मन्", "mahātman", "O great soul"]]},

21: {"s": [],
     0: [["अमी", "amī", "these"],
         ["हि", "hi", "indeed"],
         ["त्वाम्", "tvām", "into you"],
         ["सुरसंघाः", "surasaṅghāḥ", "the hosts of gods"],
         ["विशन्ति", "viśanti", "enter"]],
     1: [["केचित्", "kecit", "some"],
         ["भीताः", "bhītāḥ", "afraid"],
         ["प्राञ्जलयः", "prāñjalayaḥ", "with folded hands"],
         ["गृणन्ति", "gṛṇanti", "praise"]],
     2: [["स्वस्ति", "svasti", "auspiciousness"],
         ["इति", "iti", "thus"],
         ["उक्त्वा", "uktvā", "having said"],
         ["महर्षिसिद्धसंघाः", "maharṣisiddhasaṅghāḥ", "the hosts of great seers and siddhas"]],
     3: [["स्तुवन्ति", "stuvanti", "they praise"],
         ["त्वाम्", "tvām", "you"],
         ["स्तुतिभिः", "stutibhiḥ", "with hymns"],
         ["पुष्कलाभिः", "puṣkalābhiḥ", "abundant"]]},

22: {"s": [],
     0: [["रुद्रादित्याः", "rudrādityāḥ", "the Rudras and Ādityas"],
         ["वसवः", "vasavaḥ", "the Vasus"],
         ["ये", "ye", "those who"],
         ["च", "ca", "and"],
         ["साध्याः", "sādhyāḥ", "the Sādhyas"]],
     1: [["विश्वे", "viśve", "the Viśve-devas"],
         ["अश्विनौ", "aśvinau", "the Aśvins"],
         ["मरुतः", "marutaḥ", "the Maruts"],
         ["च", "ca", "and"],
         ["उष्मपाः", "uṣmapāḥ", "the ancestors"],
         ["च", "ca", "and"]],
     2: [["गन्धर्वयक्षासुरसिद्धसंघाः", "gandharvayakṣāsurasiddhasaṅghāḥ", "the hosts of gandharvas, yakṣas, demons and siddhas"]],
     3: [["वीक्षन्ते", "vīkṣante", "they gaze at"],
         ["त्वाम्", "tvām", "you"],
         ["विस्मिताः", "vismitāḥ", "amazed"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["सर्वे", "sarve", "all"]]},

23: {"s": [],
     0: [["रूपम्", "rūpam", "the form"],
         ["महत्", "mahat", "immense"],
         ["ते", "te", "your"],
         ["बहुवक्त्रनेत्रम्", "bahuvaktranetram", "with many mouths and eyes"]],
     1: [["महाबाहो", "mahābāho", "O mighty-armed one"],
         ["बहुबाहूरुपादम्", "bahubāhūrupādam", "with many arms, thighs and feet"]],
     2: [["बहूदरम्", "bahūdaram", "with many bellies"],
         ["बहुदंष्ट्राकरालम्", "bahudaṁṣṭrākarālam", "with many fearsome fangs"]],
     3: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
         ["लोकाः", "lokāḥ", "the worlds"],
         ["प्रव्यथिताः", "pravyathitāḥ", "trembling"],
         ["तथा", "tathā", "so"],
         ["अहम्", "aham", "I"]]},

24: {"s": [],
    0: [
    ["नभःस्पृशम्", "nabhaḥspṛśam", "touching the sky"],
        ["दीप्तम्", "dīptam", "blazing"],
        ["अनेकवर्णम्", "anekavarṇam", "of many colours"]],
    1: [
    ["व्यात्ताननम्", "vyāttānanam", "with gaping mouths"],
        ["दीप्तविशालनेत्रम्", "dīptaviśālanetram", "with blazing wide eyes"]],
    2: [
    ["दृष्ट्वा", "dṛṣṭvā", "having seen"], ["हि", "hi", "indeed"],
        ["त्वाम्", "tvām", "you"],
        ["प्रव्यथितान्तरात्मा", "pravyathitāntarātmā", "with trembling heart"]],
    3: [
    ["धृतिम्", "dhṛtim", "firmness"], ["न", "na", "not"],
        ["विन्दामि", "vindāmi", "I find"], ["शमम्", "śamam", "peace"], ["च", "ca", "and"],
        ["विष्णो", "viṣṇo", "O Viṣṇu"]],
},
25: {"s": [],
     0: [["दंष्ट्राकरालानि", "daṁṣṭrākarālāni", "the terrible fanged"],
         ["च", "ca", "and"],
         ["ते", "te", "your"],
         ["मुखानि", "mukhāni", "mouths"]],
     1: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
         ["एव", "eva", "indeed"],
         ["कालानलसन्निभानि", "kālānalasannibhāni", "like the fire of time"]],
     2: [["दिशः", "diśaḥ", "the directions"],
         ["न", "na", "not"],
         ["जाने", "jāne", "I know"],
         ["न", "na", "nor"],
         ["लभे", "labhe", "I find"],
         ["च", "ca", "and"],
         ["शर्म", "śarma", "refuge"]],
     3: [["प्रसीद", "prasīda", "be gracious"],
         ["देवेश", "deveśa", "O Lord of gods"],
         ["जगन्निवास", "jagannivāsa", "O abode of the world"]]},

26: {"s": [],
     0: [["अमी", "amī", "these"],
         ["च", "ca", "and"],
         ["त्वाम्", "tvām", "you"],
         ["धृतराष्ट्रस्य", "dhṛtarāṣṭrasya", "of Dhṛtarāṣṭra"],
         ["पुत्राः", "putrāḥ", "the sons"]],
     1: [["सर्वे", "sarve", "all"],
         ["सह", "saha", "together"],
         ["एव", "eva", "indeed"],
         ["अवनिपालसंघैः", "avanipālasaṅghaiḥ", "with the hosts of kings"]],
     2: [["भीष्मः", "bhīṣmaḥ", "Bhīṣma"],
         ["द्रोणः", "droṇaḥ", "Droṇa"],
         ["सूतपुत्रः", "sūtaputraḥ", "Karṇa, the charioteer's son"],
         ["तथा", "tathā", "also"],
         ["असौ", "asau", "that"]],
     3: [["सह", "saha", "with"],
         ["अस्मदीयैः", "asmadīyaiḥ", "ours"],
         ["अपि", "api", "even"],
         ["योधमुख्यैः", "yodhamukhyaiḥ", "the chief warriors"]]},

27: {"s": [],
    0: [
    ["वक्राणि", "vaktrāṇi", "the mouths"], ["ते", "te", "your"],
        ["त्वरमाणाः", "tvaramāṇāḥ", "hurrying"], ["विशन्ति", "viśanti", "enter"]],
    1: [
    ["दंष्ट्राकरालानि", "daṁṣṭrākarālāni", "the terrible fanged"],
        ["भयानकानि", "bhayānakāni", "frightful"]],
    2: [
    ["केचित्", "kecit", "some"], ["विलग्नाः", "vilagnāḥ", "stuck"],
        ["दशनान्तरेषु", "daśanāntareṣu", "between the teeth"]],
    3: [
    ["सन्दृश्यन्ते", "sandṛśyante", "are seen"], ["चूर्णितैः", "cūrṇitaiḥ", "crushed"],
        ["उत्तमाङ्गैः", "uttamāṅgaiḥ", "with heads"]]
},
28: {"s": [],
     0: [["यथा", "yathā", "as"],
         ["नदीनाम्", "nadīnām", "of the rivers"],
         ["बहवः", "bahavaḥ", "many"],
         ["अम्बुवेगाः", "ambuvegāḥ", "the rushing waters"]],
     1: [["समुद्रम्", "samudram", "the ocean"],
         ["एव", "eva", "indeed"],
         ["अभिमुखाः", "abhimukhāḥ", "towards"],
         ["द्रवन्ति", "dravanti", "rush"]],
     2: [["तथा", "tathā", "so"],
         ["तव", "tava", "your"],
         ["अमी", "amī", "these"],
         ["नरलोकवीराः", "naralokavīrāḥ", "heroes of the mortal world"]],
     3: [["विशन्ति", "viśanti", "enter"],
         ["वक्राणि", "vaktrāṇi", "the mouths"],
         ["अभिविज्वलन्ति", "abhivijvalanti", "blazing"]]},

29: {"s": [],
     0: [["यथा", "yathā", "as"],
         ["प्रदीप्तम्", "pradīptam", "blazing"],
         ["ज्वलनम्", "jvalanam", "fire"],
         ["पतङ्गाः", "pataṅgāḥ", "moths"]],
     1: [["विशन्ति", "viśanti", "enter"],
         ["नाशाय", "nāśāya", "for destruction"],
         ["समृद्धवेगाः", "samṛddhavegāḥ", "with full speed"]],
     2: [["तथा", "tathā", "so"],
         ["एव", "eva", "indeed"],
         ["नाशाय", "nāśāya", "for destruction"],
         ["विशन्ति", "viśanti", "enter"],
         ["लोकाः", "lokāḥ", "the worlds"]],
     3: [["तव", "tava", "your"],
         ["अपि", "api", "even"],
         ["वक्राणि", "vaktrāṇi", "mouths"],
         ["समृद्धवेगाः", "samṛddhavegāḥ", "with full speed"]]},

30: {"s": [],
     0: [["लेलिह्यसे", "lelihyase", "you lick"],
         ["ग्रसमानः", "grasamānaḥ", "devouring"],
         ["समन्तात्", "samantāt", "on every side"]],
     1: [["लोकान्", "lokān", "the worlds"],
         ["समग्रान्", "samagrān", "all"],
         ["वदनैः", "vadanaiḥ", "with the mouths"],
         ["ज्वलद्भिः", "jvaladbhiḥ", "blazing"]],
     2: [["तेजोभिः", "tejobhiḥ", "with the radiance"],
         ["आपूर्य", "āpūrya", "having filled"],
         ["जगत्", "jagat", "the universe"],
         ["समग्रम्", "samagram", "whole"]],
     3: [["भासः", "bhāsaḥ", "the rays"],
         ["तव", "tava", "your"],
         ["उग्राः", "ugrāḥ", "terrible"],
         ["प्रतपन्ति", "pratapanti", "blaze"],
         ["विष्णो", "viṣṇo", "O Viṣṇu"]]},

31: {"s": [],
     0: [["आख्याहि", "ākhyāhi", "tell"],
         ["मे", "me", "me"],
         ["कः", "kaḥ", "who"],
         ["भवान्", "bhavān", "you are"],
         ["उग्ररूपः", "ugrarūpaḥ", "of terrible form"]],
     1: [["नमः", "namaḥ", "salutation"],
         ["अस्तु", "astu", "may be"],
         ["ते", "te", "to you"],
         ["देववर", "devavara", "O best of gods"],
         ["प्रसीद", "prasīda", "be gracious"]],
     2: [["विज्ञातुम्", "vijñātum", "to know"],
         ["इच्छामि", "icchāmi", "I wish"],
         ["भवन्तम्", "bhavantam", "you"],
         ["आद्यम्", "ādyam", "the primeval"]],
     3: [["न", "na", "not"],
         ["हि", "hi", "indeed"],
         ["प्रजानामि", "prajānāmi", "I understand"],
         ["तव", "tava", "your"],
         ["प्रवृत्तिम्", "pravṛttim", "workings"]]},

32: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
     0: [["कालः", "kālaḥ", "Time"],
         ["अस्मि", "asmi", "I am"],
         ["लोकक्षयकृत्", "lokakṣayakṛt", "the destroyer of worlds"],
         ["प्रवृद्धः", "pravṛddhaḥ", "grown mature"]],
     1: [["लोकान्", "lokān", "the worlds"],
         ["समाहर्तुम्", "samāhartum", "to destroy"],
         ["इह", "iha", "here"],
         ["प्रवृत्तः", "pravṛttaḥ", "engaged"]],
     2: [["ऋते", "ṛte", "without"],
         ["अपि", "api", "even"],
         ["त्वाम्", "tvām", "you"],
         ["न", "na", "not"],
         ["भविष्यन्ति", "bhaviṣyanti", "will remain"],
         ["सर्वे", "sarve", "all"]],
     3: [["ये", "ye", "those who"],
         ["अवस्थिताः", "avasthitāḥ", "standing"],
         ["प्रत्यनीकेषु", "pratyanīkeṣu", "in the opposing ranks"],
         ["योधाः", "yodhāḥ", "warriors"]]},

33: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["त्वम्", "tvam", "you"],
         ["उत्तिष्ठ", "uttiṣṭha", "arise"],
         ["यशः", "yaśaḥ", "glory"],
         ["लभस्व", "labhasva", "win"]],
     1: [["जित्वा", "jitvā", "having conquered"],
         ["शत्रून्", "śatrūn", "the enemies"],
         ["भुङ्क्ष्व", "bhuṅkṣva", "enjoy"],
         ["राज्यम्", "rājyam", "the kingdom"],
         ["समृद्धम्", "samṛddham", "prosperous"]],
     2: [["मया", "mayā", "by me"],
         ["एव", "eva", "indeed"],
         ["एते", "ete", "these"],
         ["निहताः", "nihatāḥ", "slain"],
         ["पूर्वम्", "pūrvam", "already"],
         ["एव", "eva", "indeed"]],
     3: [["निमित्तमात्रम्", "nimittamātram", "merely the instrument"],
         ["भव", "bhava", "be"],
         ["सव्यसाचिन्", "savyasācin", "O Sāvyasācin"]]},

34: {"s": [],
     0: [["द्रोणम्", "droṇam", "Droṇa"],
         ["च", "ca", "and"],
         ["भीष्मम्", "bhīṣmam", "Bhīṣma"],
         ["च", "ca", "and"],
         ["जयद्रथम्", "jayadratham", "Jayadratha"],
         ["च", "ca", "and"]],
     1: [["कर्णम्", "karṇam", "Karṇa"],
         ["तथा", "tathā", "also"],
         ["अन्यान्", "anyān", "others"],
         ["अपि", "api", "even"],
         ["योधवीरान्", "yodhavīrān", "warrior-heroes"]],
     2: [["मया", "mayā", "by me"],
         ["हतान्", "hatān", "slain"],
         ["त्वम्", "tvam", "you"],
         ["जहि", "jahi", "strike"],
         ["मा", "mā", "do not"],
         ["व्यथिष्ठाः", "vyathiṣṭhāḥ", "be distressed"]],
     3: [["युध्यस्व", "yudhyasva", "fight"],
         ["जेतासि", "jetāsi", "you will conquer"],
         ["रणे", "raṇe", "in battle"],
         ["सपत्नान्", "sapatnān", "the rivals"]]},

35: {"s": [["सञ्जयः", "sañjayaḥ", "Sañjaya"], ["उवाच", "uvāca", "said"]],
     0: [["एतत्", "etat", "this"],
         ["श्रुत्वा", "śrutvā", "having heard"],
         ["वचनम्", "vacanam", "the words"],
         ["केशवस्य", "keśavasya", "of Keśava"]],
     1: [["कृताञ्जलिः", "kṛtāñjaliḥ", "with joined palms"],
         ["वेपमानः", "vepamānaḥ", "trembling"],
         ["किरीटी", "kirīṭī", "the crowned one"]],
     2: [["नमस्कृत्वा", "namaskṛtvā", "having bowed"],
         ["भूयः", "bhūyaḥ", "again"],
         ["एव", "eva", "indeed"],
         ["आह", "āha", "spoke"],
         ["कृष्णम्", "kṛṣṇam", "to Kṛṣṇa"]],
     3: [["सगद्गदम्", "sagadgadam", "with a faltering voice"],
         ["भीतभीतः", "bhītabhītaḥ", "much afraid"],
         ["प्रणम्य", "praṇamya", "having bowed"]]},

36: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["स्थाने", "sthāne", "fitly"],
         ["हृषीकेश", "hṛṣīkeśa", "O Hṛṣīkeśa"],
         ["तव", "tava", "your"],
         ["प्रकीर्त्या", "prakīrtyā", "by the glory"]],
     1: [["जगत्", "jagat", "the world"],
         ["प्रहृष्यति", "prahṛṣyati", "rejoices"],
         ["अनुरज्यते", "anurajyate", "is delighted"],
         ["च", "ca", "and"]],
     2: [["रक्षांसि", "rakṣāṁsi", "the rākṣasas"],
         ["भीतानि", "bhītāni", "frightened"],
         ["दिशः", "diśaḥ", "the directions"],
         ["द्रवन्ति", "dravanti", "flee"]],
     3: [["सर्वे", "sarve", "all"],
         ["नमस्यन्ति", "namasyanti", "bow"],
         ["च", "ca", "and"],
         ["सिद्धसंघाः", "siddhasaṅghāḥ", "the hosts of siddhas"]]},

37: {"s": [],
     0: [["कस्मात्", "kasmāt", "why"],
         ["च", "ca", "and"],
         ["ते", "te", "to you"],
         ["न", "na", "not"],
         ["नमेरन्", "nameran", "should they bow"],
         ["महात्मन्", "mahātman", "O great soul"]],
     1: [["गरीयसे", "garīyase", "to the greater"],
         ["ब्रह्मणः", "brahmaṇaḥ", "than Brahmā"],
         ["अपि", "api", "even"],
         ["आदिकर्त्रे", "ādikartre", "to the primal creator"]],
     2: [["अनन्त", "ananta", "O infinite"],
         ["देवेश", "deveśa", "O Lord of gods"],
         ["जगन्निवास", "jagannivāsa", "O abode of the world"]],
     3: [["त्वम्", "tvam", "you"],
         ["अक्षरम्", "akṣaram", "the imperishable"],
         ["सत्", "sat", "the real"],
         ["असत्", "asat", "the unreal"],
         ["तत्परम्", "tatparam", "beyond both"],
         ["यत्", "yat", "which"]]},

38: {"s": [],
     0: [["त्वम्", "tvam", "you"],
         ["आदिदेवः", "ādidevaḥ", "the primal God"],
         ["पुरुषः", "puruṣaḥ", "the Person"],
         ["पुराणः", "purāṇaḥ", "ancient"]],
     1: [["त्वम्", "tvam", "you"],
         ["अस्य", "asya", "of this"],
         ["विश्वस्य", "viśvasya", "universe"],
         ["परम्", "param", "the supreme"],
         ["निधानम्", "nidhānam", "refuge"]],
     2: [["वेत्ता", "vettā", "the knower"],
         ["असि", "asi", "you are"],
         ["वेद्यम्", "vedyam", "the known"],
         ["च", "ca", "and"],
         ["परम्", "param", "the supreme"],
         ["च", "ca", "and"],
         ["धाम", "dhāma", "abode"]],
     3: [["त्वया", "tvayā", "by you"],
         ["ततम्", "tatam", "pervaded"],
         ["विश्वम्", "viśvam", "the universe"],
         ["अनन्तरूप", "anantarūpa", "O infinite form"]]},

39: {"s": [],
     0: [["वायुः", "vāyuḥ", "the wind"],
         ["यमः", "yamaḥ", "Death"],
         ["अग्निः", "agniḥ", "fire"],
         ["वरुणः", "varuṇaḥ", "Varuṇa"],
         ["शशाङ्कः", "śaśāṅkaḥ", "the moon"]],
     1: [["प्रजापतिः", "prajāpatiḥ", "the progenitor"],
         ["त्वम्", "tvam", "you"],
         ["प्रपितामहः", "prapitāmahaḥ", "the great grandsire"],
         ["च", "ca", "and"]],
     2: [["नमः", "namaḥ", "salutation"],
         ["नमः", "namaḥ", "salutation"],
         ["ते", "te", "to you"],
         ["अस्तु", "astu", "may be"],
         ["सहस्रकृत्वः", "sahasrakṛtvaḥ", "a thousand times"]],
     3: [["पुनः", "punaḥ", "again"],
         ["च", "ca", "and"],
         ["भूयः", "bhūyaḥ", "once more"],
         ["अपि", "api", "indeed"],
         ["नमः", "namaḥ", "salutation"],
         ["नमः", "namaḥ", "salutation"],
         ["ते", "te", "to you"]]},

40: {"s": [],
    0: [
    ["नमः", "namaḥ", "salutation"], ["पुरस्तात्", "purastāt", "from the front"],
        ["अथ", "atha", "and"], ["पृष्ठतः", "pṛṣṭhataḥ", "from behind"],
        ["ते", "te", "to you"]],
    1: [
    ["नमः", "namaḥ", "salutation"], ["अस्तु", "astu", "may be"], ["ते", "te", "to you"],
        ["सर्वतः", "sarvataḥ", "on every side"], ["एव", "eva", "indeed"],
        ["सर्व", "sarva", "O all"]],
    2: [
    ["अनन्तवीर्य", "anantavīrya", "O of infinite might"],
        ["अमितविक्रमः", "amitavikramaḥ", "of measureless vigour"],
        ["त्वम्", "tvam", "you"]],
    3: [
    ["सर्वम्", "sarvam", "all"], ["समाप्नोषि", "samāpnoṣi", "you pervade"],
        ["ततः", "tataḥ", "therefore"], ["असि", "asi", "you are"],
        ["सर्वः", "sarvaḥ", "all"]]
},
41: {"s": [],
     0: [["सखा", "sakhā", "friend"],
         ["इति", "iti", "thus"],
         ["मत्वा", "matvā", "thinking"],
         ["प्रसभम्", "prasabham", "rashly"],
         ["यत्", "yat", "which"],
         ["उक्तम्", "uktam", "was said"]],
     1: [["हे", "he", "O"],
         ["कृष्ण", "kṛṣṇa", "Kṛṣṇa"],
         ["हे", "he", "O"],
         ["यादव", "yādava", "Yādava"],
         ["हे", "he", "O"],
         ["सखे", "sakhe", "friend"],
         ["इति", "iti", "thus"]],
     2: [["अजानता", "ajānatā", "by one not knowing"],
         ["महिमानम्", "mahimānam", "the greatness"],
         ["तव", "tava", "your"],
         ["इदम्", "idam", "this"]],
     3: [["मया", "mayā", "by me"],
         ["प्रमादात्", "pramādāt", "from carelessness"],
         ["प्रणयेन", "praṇayena", "from affection"],
         ["वा", "vā", "or"],
         ["अपि", "api", "indeed"]]},

42: {"s": [],
     0: [["यत्", "yat", "whatever"],
         ["च", "ca", "and"],
         ["अवहासार्थम्", "avahāsārtham", "for the sake of jest"],
         ["असत्कृतः", "asatkṛtaḥ", "treated with disrespect"],
         ["असि", "asi", "you were"]],
     1: [["विहार", "vihāra", "in play"],
         ["शय्या", "śayyā", "in rest"],
         ["आसन", "āsana", "at sitting"],
         ["भोजनेषु", "bhojaneṣu", "at meals"]],
     2: [["एकः", "ekaḥ", "alone"],
         ["अथवा", "athavā", "or"],
         ["अपि", "api", "even"],
         ["अच्युत", "acyuta", "O Acyuta"],
         ["तत्समक्षम्", "tatsamakṣam", "in the presence of others"]],
     3: [["तत्", "tat", "that"],
         ["क्षामये", "kṣāmaye", "I beg forgiveness"],
         ["त्वाम्", "tvām", "you"],
         ["अहम्", "aham", "I"],
         ["अप्रमेयम्", "aprameyam", "O immeasurable one"]]},

43: {"s": [],
     0: [["पिता", "pitā", "the father"],
         ["असि", "asi", "you are"],
         ["लोकस्य", "lokasya", "of the world"],
         ["चराचरस्य", "carācarasya", "moving and unmoving"]],
     1: [["त्वम्", "tvam", "you"],
         ["अस्य", "asya", "of this"],
         ["पूज्यः", "pūjyaḥ", "the object of worship"],
         ["च", "ca", "and"],
         ["गुरुः", "guruḥ", "the teacher"],
         ["गरीयान्", "garīyān", "the greatest"]],
     2: [["न", "na", "not"],
         ["त्वत्समः", "tvatsamaḥ", "equal to you"],
         ["अस्ति", "asti", "there is"],
         ["अभ्यधिकः", "abhyadhikaḥ", "greater"],
         ["कुतः", "kutaḥ", "how then"],
         ["अन्यः", "anyaḥ", "another"]],
     3: [["लोकत्रये", "lokatraye", "in the three worlds"],
         ["अपि", "api", "even"],
         ["अप्रतिमप्रभाव", "apratimaprabhāva", "O of matchless power"]]},

44: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["प्रणम्य", "praṇamya", "having bowed"],
         ["प्रणिधाय", "praṇidhāya", "having prostrated"],
         ["कायम्", "kāyam", "the body"]],
     1: [["प्रसादये", "prasādaye", "I beg the grace"],
         ["त्वाम्", "tvām", "of you"],
         ["अहम्", "aham", "I"],
         ["ईशम्", "īśam", "O Lord"],
         ["ईड्यम्", "īḍyam", "O adorable one"]],
     2: [["पिता", "pitā", "a father"],
         ["इव", "iva", "like"],
         ["पुत्रस्य", "putrasya", "of a son"],
         ["सखा", "sakhā", "a friend"],
         ["इव", "iva", "like"],
         ["सख्युः", "sakhyuḥ", "of a friend"]],
     3: [["प्रियः", "priyaḥ", "the beloved"],
         ["प्रियायाः", "priyāyāḥ", "of the beloved"],
         ["अर्हसि", "arhasi", "you should"],
         ["देव", "deva", "O God"],
         ["सोढुम्", "soḍhum", "to forgive"]]},

45: {"s": [],
     0: [["अदृष्टपूर्वम्", "adṛṣṭapūrvam", "never seen before"],
         ["हृषितः", "hṛṣitaḥ", "delighted"],
         ["अस्मि", "asmi", "I am"],
         ["दृष्ट्वा", "dṛṣṭvā", "having seen"]],
     1: [["भयेन", "bhayena", "with fear"],
         ["च", "ca", "and"],
         ["प्रव्यथितम्", "pravyathitam", "trembling"],
         ["मनः", "manaḥ", "the mind"],
         ["मे", "me", "my"]],
     2: [["तत्", "tat", "that"],
         ["एव", "eva", "indeed"],
         ["मे", "me", "to me"],
         ["दर्शय", "darśaya", "show"],
         ["देव", "deva", "O God"],
         ["रूपम्", "rūpam", "form"]],
     3: [["प्रसीद", "prasīda", "be gracious"],
         ["देवेश", "deveśa", "O Lord of gods"],
         ["जगन्निवास", "jagannivāsa", "O abode of the world"]]},

46: {"s": [],
     0: [["किरीटिनम्", "kirīṭinam", "wearing the crown"],
         ["गदिनम्", "gadinam", "with the mace"],
         ["चक्रहस्तम्", "cakrahastam", "with the discus in hand"]],
     1: [["इच्छामि", "icchāmi", "I wish"],
         ["त्वाम्", "tvām", "you"],
         ["द्रष्टुम्", "draṣṭum", "to see"],
         ["अहम्", "aham", "I"],
         ["तथा", "tathā", "thus"],
         ["एव", "eva", "indeed"]],
     2: [["तेन", "tena", "in that"],
         ["एव", "eva", "very"],
         ["रूपेण", "rūpeṇa", "form"],
         ["चतुर्भुजेन", "caturbhujena", "four-armed"]],
     3: [["सहस्रबाहो", "sahasrabāho", "O thousand-armed one"],
         ["भव", "bhava", "be"],
         ["विश्वमूर्ते", "viśvamūrte", "O cosmic form"]]},

47: {"s": [
    ["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
    ["उवाच", "uvāca", "said"]
],
    0: [
    ["मया", "mayā", "by me"], ["प्रसन्नेन", "prasannena", "being gracious"],
        ["तव", "tava", "to you"], ["अर्जुन", "arjuna", "O Arjuna"],
        ["इदम्", "idam", "this"]],
    1: [
    ["रूपम्", "rūpam", "form"], ["परम्", "param", "supreme"],
        ["दर्शितम्", "darśitam", "shown"], ["आत्मयोगात्", "ātmayogāt", "by my own power"]],
    2: [
    ["तेजोमयम्", "tejomayam", "full of light"], ["विश्वम्", "viśvam", "universal"],
        ["अनन्तम्", "anantam", "infinite"], ["आद्यम्", "ādyam", "primeval"]],
    3: [
    ["यत्", "yat", "which"], ["मे", "me", "my"],
        ["त्वदन्येन", "tvadanyena", "by other than you"], ["न", "na", "not"],
        ["दृष्टपूर्वम्", "dṛṣṭapūrvam", "seen before"]]
},
48: {"s": [],
     0: [["न", "na", "not"],
         ["वेदयज्ञाध्ययनैः", "vedayajñādhyayanaiḥ", "by Vedic study and sacrifice"],
         ["न", "na", "nor"],
         ["दानैः", "dānaiḥ", "by gifts"]],
     1: [["न", "na", "nor"],
         ["च", "ca", "and"],
         ["क्रियाभिः", "kriyābhiḥ", "by rites"],
         ["न", "na", "nor"],
         ["तपोभिः", "tapobhiḥ", "by austerities"],
         ["उग्रैः", "ugraiḥ", "fierce"]],
     2: [["एवंरूपः", "evaṁrūpaḥ", "in this form"],
         ["शक्यः", "śakyaḥ", "can"],
         ["अहम्", "aham", "I"],
         ["नृलोके", "nṛloke", "in the world of men"]],
     3: [["द्रष्टुम्", "draṣṭum", "to be seen"],
         ["त्वदन्येन", "tvadanyena", "by other than you"],
         ["कुरुप्रवीर", "kurupravīra", "O prince of the Kurus"]]},

49: {"s": [],
    0: [
    ["मा", "mā", "do not"], ["ते", "te", "to you"], ["व्यथा", "vyathā", "distress"],
        ["मा", "mā", "nor"], ["च", "ca", "and"],
        ["विमूढभावः", "vimūḍhabhāvaḥ", "bewilderment"]],
    1: [
    ["दृष्ट्वा", "dṛṣṭvā", "having seen"], ["रूपम्", "rūpam", "the form"],
        ["घोरम्", "ghoram", "terrible"], ["ईदृक्", "īdṛk", "such as this"],
        ["मम", "mama", "my"], ["इदम्", "idam", "this"]],
    2: [
    ["व्यपेतभीः", "vyapetabhīḥ", "with fear gone"],
        ["प्रीतमनाः", "prītamanāḥ", "with glad heart"], ["पुनः", "punaḥ", "again"],
        ["त्वम्", "tvam", "you"]],
    3: [
    ["तत्", "tat", "that"], ["एव", "eva", "indeed"], ["मे", "me", "my"],
        ["रूपम्", "rūpam", "form"], ["इदम्", "idam", "this"],
        ["प्रपश्य", "prapaśya", "behold"]]
},
50: {"s": [["सञ्जयः", "sañjayaḥ", "Sañjaya"], ["उवाच", "uvāca", "said"]],
     0: [["इति", "iti", "thus"],
         ["अर्जुनम्", "arjunam", "to Arjuna"],
         ["वासुदेवः", "vāsudevaḥ", "Vāsudeva"],
         ["तथा", "tathā", "so"],
         ["उक्त्वा", "uktvā", "having spoken"]],
     1: [["स्वकम्", "svakam", "his own"],
         ["रूपम्", "rūpam", "form"],
         ["दर्शयामास", "darśayāmāsa", "showed"],
         ["भूयः", "bhūyaḥ", "again"]],
     2: [["आश्वासयामास", "āśvāsayāmāsa", "comforted"],
         ["च", "ca", "and"],
         ["भीतम्", "bhītam", "the frightened"],
         ["एनम्", "enam", "him"]],
     3: [["भूत्वा", "bhūtvā", "having become"],
         ["पुनः", "punaḥ", "again"],
         ["सौम्यवपुः", "saumyavapuḥ", "of gracious appearance"],
         ["महात्मा", "mahātmā", "the great soul"]]},

51: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
         ["इदम्", "idam", "this"],
         ["मानुषम्", "mānuṣam", "human"],
         ["रूपम्", "rūpam", "form"]],
     1: [["तव", "tava", "your"],
         ["सौम्यम्", "saumyam", "gracious"],
         ["जनार्दन", "janārdana", "O Janārdana"]],
     2: [["इदानीम्", "idānīm", "now"],
         ["अस्मि", "asmi", "I am"],
         ["संवृत्तः", "saṁvṛttaḥ", "become"]],
     3: [["सचेताः", "sacetāḥ", "composed"],
         ["प्रकृतिम्", "prakṛtim", "to my own nature"],
         ["गतः", "gataḥ", "restored"]]},

52: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
     0: [["सुदुर्दर्शम्", "sudurdarśam", "very hard to see"],
         ["इदम्", "idam", "this"],
         ["रूपम्", "rūpam", "form"]],
     1: [["दृष्टवान्", "dṛṣṭavān", "have seen"],
         ["असि", "asi", "you"],
         ["यत्", "yat", "which"],
         ["मम", "mama", "my"]],
     2: [["देवाः", "devāḥ", "the gods"],
         ["अपि", "api", "even"],
         ["अस्य", "asya", "of this"],
         ["रूपस्य", "rūpasya", "form"]],
     3: [["नित्यम्", "nityam", "always"],
         ["दर्शनकाङ्क्षिणः", "darśanakāṅkṣiṇaḥ", "desiring the sight"]]},

53: {"s": [],
     0: [["न", "na", "not"],
         ["अहम्", "aham", "I"],
         ["वेदैः", "vedaiḥ", "by the Vedas"],
         ["न", "na", "nor"],
         ["तपसा", "tapasā", "by austerity"]],
     1: [["न", "na", "nor"],
         ["दानेन", "dānena", "by gifts"],
         ["न", "na", "nor"],
         ["च", "ca", "and"],
         ["इज्यया", "ijyayā", "by worship"]],
     2: [["शक्यः", "śakyaḥ", "can"],
         ["एवंविधः", "evaṁvidhaḥ", "in this form"],
         ["द्रष्टुम्", "draṣṭum", "to be seen"]],
     3: [["दृष्टवान्", "dṛṣṭavān", "have seen"],
         ["असि", "asi", "you"],
         ["माम्", "mām", "me"],
         ["यथा", "yathā", "as"]]},

54: {"s": [],
     0: [["भक्त्या", "bhaktyā", "by devotion"],
         ["तु", "tu", "but"],
         ["अनन्यया", "ananyayā", "single-pointed"],
         ["शक्यः", "śakyaḥ", "can"]],
     1: [["अहम्", "aham", "I"],
         ["एवंविधः", "evaṁvidhaḥ", "in this form"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["ज्ञातुम्", "jñātum", "to be known"],
         ["द्रष्टुम्", "draṣṭum", "to be seen"],
         ["च", "ca", "and"],
         ["तत्त्वेन", "tattvena", "in truth"]],
     3: [["प्रवेष्टुम्", "praveṣṭum", "to be entered"],
         ["च", "ca", "and"],
         ["परन्तप", "parantapa", "O scorcher of foes"]]},

55: {"s": [],
     0: [["मत्कर्मकृत्", "matkarmakṛt", "doing my work"],
         ["मत्परमः", "matparamaḥ", "holding me as supreme"]],
     1: [["मद्भक्तः", "madbhaktaḥ", "devoted to me"],
         ["सङ्गवर्जितः", "saṅgavarjitaḥ", "free from attachment"]],
     2: [["निर्वैरः", "nirvairaḥ", "without enmity"],
         ["सर्वभूतेषु", "sarvabhūteṣu", "toward all beings"]],
     3: [["यः", "yaḥ", "who"],
         ["सः", "saḥ", "he"],
         ["माम्", "mām", "to me"],
         ["एति", "eti", "comes"],
         ["पाण्डव", "pāṇḍava", "O son of Pāṇḍu"]]},
}
