# -*- coding: utf-8 -*-
"""padachheda_ch12.py — per-pāda pada-chheda (word splits) for all 20 verses of Gita Chapter 12.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH12_WORDS = {
1: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
    0: [["एवम्", "evam", "thus"],
        ["सततयुक्ताः", "satatayuktāḥ", "ever united"],
        ["ये", "ye", "who"]],
    1: [["भक्ताः", "bhaktāḥ", "devotees"],
        ["त्वाम्", "tvām", "you"],
        ["पर्युपासते", "paryupāsate", "worship"]],
    2: [["ये", "ye", "who"],
        ["च", "ca", "and"],
        ["अपि", "api", "also"],
        ["अक्षरम्", "akṣaram", "the imperishable"],
        ["अव्यक्तम्", "avyaktam", "the unmanifest"]],
    3: [["तेषाम्", "teṣām", "of them"],
        ["के", "ke", "which"],
        ["योगवित्तमाः", "yogavittamāḥ", "the best knowers of yoga"]]},

2: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["मयि", "mayi", "on me"],
        ["आवेश्य", "āveśya", "having fixed"],
        ["मनः", "manaḥ", "the mind"],
        ["ये", "ye", "who"],
        ["माम्", "mām", "me"]],
    1: [["नित्ययुक्ताः", "nityayuktāḥ", "ever united"],
        ["उपासते", "upāsate", "worship"]],
    2: [["श्रद्धया", "śraddhayā", "with faith"],
        ["परया", "parayā", "supreme"],
        ["उपेताः", "upetāḥ", "endowed"]],
    3: [["ते", "te", "they"],
        ["मे", "me", "in my"],
        ["युक्ततमाः", "yuktatamāḥ", "the most yoked"],
        ["मताः", "matāḥ", "deemed"]]},

3: {"s": [],
    0: [["ये", "ye", "those who"],
        ["तु", "tu", "but"],
        ["अक्षरम्", "akṣaram", "the imperishable"],
        ["अनिर्देश्यम्", "anirdeśyam", "the indefinable"]],
    1: [["अव्यक्तम्", "avyaktam", "the unmanifest"],
        ["पर्युपासते", "paryupāsate", "worship"]],
    2: [["सर्वत्रगम्", "sarvatragam", "all-pervading"],
        ["अचिन्त्यम्", "acintyam", "unthinkable"],
        ["च", "ca", "and"]],
    3: [["कूटस्थम्", "kūṭastham", "unchanging"],
        ["अचलम्", "acalam", "immovable"],
        ["ध्रुवम्", "dhruvam", "eternal"]]},

4: {"s": [],
    0: [
    ["सन्नियम्य", "sanniyamya", "having controlled"],
        ["इन्द्रियग्रामम्", "indriyagrāmam", "the whole host of senses"]],
    1: [
    ["सर्वत्र", "sarvatra", "everywhere"], ["समबुद्धयः", "samabuddhayaḥ", "of equal mind"]],
    2: [
    ["ते", "te", "they"], ["प्राप्नुवन्ति", "prāpnuvanti", "reach"], ["माम्", "mām", "me"],
        ["एव", "eva", "indeed"]],
    3: [
    ["सर्वभूतहिते", "sarvabhūtahite", "in the welfare of all beings"],
        ["रताः", "ratāḥ", "rejoicing"]]
},
5: {"s": [],
    0: [["क्लेशः", "kleśaḥ", "toil"],
        ["अधिकतरः", "adhikataraḥ", "greater"],
        ["तेषाम्", "teṣām", "of those"]],
    1: [["अव्यक्त", "avyakta", "to the unmanifest"],
        ["आसक्त", "āsakta", "attached"],
        ["चेतसाम्", "cetasām", "of minds"]],
    2: [["अव्यक्ता", "avyaktā", "the unmanifest"],
        ["हि", "hi", "indeed"],
        ["गतिः", "gatiḥ", "the path"],
        ["दुःखम्", "duḥkham", "hard"]],
    3: [["देहवद्भिः", "dehavadbhiḥ", "by embodied beings"],
        ["अवाप्यते", "avāpyate", "is attained"]]},

6: {"s": [],
    0: [["ये", "ye", "those who"],
        ["तु", "tu", "but"],
        ["सर्वाणि", "sarvāṇi", "all"],
        ["कर्माणि", "karmāṇi", "actions"]],
    1: [["मयि", "mayi", "in me"],
        ["सन्न्यस्य", "sannyasya", "having surrendered"],
        ["मत्पराः", "matparāḥ", "intent on me"]],
    2: [["अनन्येन", "ananyena", "undivided"],
        ["एव", "eva", "indeed"],
        ["योगेन", "yogena", "with yoga"]],
    3: [["माम्", "mām", "me"],
        ["ध्यायन्तः", "dhyāyantaḥ", "meditating on"],
        ["उपासते", "upāsate", "worship"]]},

7: {"s": [],
    0: [["तेषाम्", "teṣām", "of them"],
        ["अहम्", "aham", "I"],
        ["समुद्धर्ता", "samuddhartā", "the deliverer"]],
    1: [["मृत्युसंसारसागरात्", "mṛtyusaṁsārasāgarāt", "from the ocean of death and rebirth"]],
    2: [["भवामि", "bhavāmi", "I become"],
        ["न", "na", "not"],
        ["चिरात्", "cirāt", "long, after a while"],
        ["पार्थ", "pārtha", "O Pārtha"]],
    3: [["मयि", "mayi", "on me"],
        ["आवेशित", "āveśita", "fixed"],
        ["चेतसाम्", "cetasām", "of those whose minds"]]},

8: {"s": [],
    0: [["मयि", "mayi", "on me"],
        ["एव", "eva", "alone"],
        ["मनः", "manaḥ", "the mind"],
        ["आधत्स्व", "ādhatsva", "fix"]],
    1: [["मयि", "mayi", "in me"],
        ["बुद्धिम्", "buddhim", "the intellect"],
        ["निवेशय", "niveśaya", "establish"]],
    2: [["निवसिष्यसि", "nivasiṣyasi", "you will live"],
        ["मयि", "mayi", "in me"],
        ["एव", "eva", "alone"]],
    3: [["अतः", "ataḥ", "then"],
        ["ऊर्ध्वम्", "ūrdhvam", "upwards, hereafter"],
        ["न", "na", "no"],
        ["संशयः", "saṁśayaḥ", "doubt"]]},

9: {"s": [],
    0: [["अथ", "atha", "if"],
        ["चित्तम्", "cittam", "the mind"],
        ["समाधातुम्", "samādhātum", "to fix steadily"]],
    1: [["न", "na", "not"],
        ["शक्नोषि", "śaknoṣi", "you are able"],
        ["मयि", "mayi", "on me"],
        ["स्थिरम्", "sthiram", "steadily"]],
    2: [["अभ्यासयोगेन", "abhyāsayogena", "by the yoga of practice"],
        ["ततः", "tataḥ", "then"]],
    3: [["माम्", "mām", "me"],
        ["इच्छ", "iccha", "seek"],
        ["आप्तुम्", "āptum", "to reach"],
        ["धनञ्जय", "dhanañjaya", "O Dhanañjaya"]]},

10: {"s": [],
     0: [["अभ्यासे", "abhyāse", "in practice"],
         ["अपि", "api", "even"],
         ["असमर्थः", "asamarthaḥ", "unable"],
         ["असि", "asi", "you are"]],
     1: [["मत्कर्मपरमः", "matkarmaparamaḥ", "devoted to working for me"],
         ["भव", "bhava", "be"]],
     2: [["मदर्थम्", "madartham", "for my sake"],
         ["अपि", "api", "even"],
         ["कर्माणि", "karmāṇi", "actions"]],
     3: [["कुर्वन्", "kurvan", "performing"],
         ["सिद्धिम्", "siddhim", "perfection"],
         ["अवाप्स्यसि", "avāpsyasi", "you will attain"]]},

11: {"s": [],
     0: [["अथ", "atha", "if"],
         ["एतत्", "etat", "this"],
         ["अपि", "api", "even"],
         ["अशक्तः", "aśaktaḥ", "unable"],
         ["असि", "asi", "you are"]],
     1: [["कर्तुम्", "kartum", "to do"],
         ["मद्योगम्", "madyogam", "my yoga"],
         ["आश्रितः", "āśritaḥ", "taking refuge in"]],
     2: [["सर्वकर्मफलत्यागम्", "sarvakarmaphalatyāgam", "the renunciation of the fruit of all actions"]],
     3: [["ततः", "tataḥ", "then"],
         ["कुरु", "kuru", "do"],
         ["यतात्मवान्", "yatātmavān", "self-controlled"]]},

12: {"s": [],
     0: [["श्रेयः", "śreyaḥ", "better"],
         ["हि", "hi", "indeed"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["अभ्यासात्", "abhyāsāt", "than practice"]],
     1: [["ज्ञानात्", "jñānāt", "than knowledge"],
         ["ध्यानम्", "dhyānam", "meditation"],
         ["विशिष्यते", "viśiṣyate", "is better"]],
     2: [["ध्यानात्", "dhyānāt", "than meditation"],
         ["कर्मफलत्यागः", "karmaphalatyāgaḥ", "renunciation of the fruit of action"]],
     3: [["त्यागात्", "tyāgāt", "from renunciation"],
         ["शान्तिः", "śāntiḥ", "peace"],
         ["अनन्तरम्", "anantaram", "immediately"]]},

13: {"s": [],
     0: [["अद्वेष्टा", "adveṣṭā", "not hating"],
         ["सर्वभूतानाम्", "sarvabhūtānām", "of all beings"]],
     1: [["मैत्रः", "maitraḥ", "friendly"],
         ["करुणः", "karuṇaḥ", "compassionate"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["निर्ममः", "nirmamaḥ", "free from possessiveness"],
         ["निरहङ्कारः", "nirahaṅkāraḥ", "free from ego"]],
     3: [["समदुःखसुखः", "samaduḥkhasukhaḥ", "equal in pleasure and pain"],
         ["क्षमी", "kṣamī", "forgiving"]]},

14: {"s": [],
     0: [["सन्तुष्टः", "santuṣṭaḥ", "content"],
         ["सततम्", "satatam", "always"],
         ["योगी", "yogī", "the yogi"]],
     1: [["यतात्मा", "yatātmā", "self-controlled"],
         ["दृढनिश्चयः", "dṛḍhaniścayaḥ", "of firm resolve"]],
     2: [["मयि", "mayi", "to me"],
         ["अर्पित", "arpita", "offered"],
         ["मनोबुद्धिः", "manobuddhiḥ", "mind and intellect"]],
     3: [["यः", "yaḥ", "who"],
         ["मद्भक्तः", "madbhaktaḥ", "my devotee"],
         ["सः", "saḥ", "he"],
         ["मे", "me", "to me"],
         ["प्रियः", "priyaḥ", "dear"]]},

15: {"s": [],
     0: [["यस्मात्", "yasmāt", "by whom"],
         ["न", "na", "not"],
         ["उद्विजते", "udvijate", "is agitated"],
         ["लोकः", "lokaḥ", "the world"]],
     1: [["लोकात्", "lokāt", "by the world"],
         ["न", "na", "not"],
         ["उद्विजते", "udvijate", "is agitated"],
         ["च", "ca", "and"],
         ["यः", "yaḥ", "who"]],
     2: [["हर्ष", "harṣa", "joy"],
         ["अमर्ष", "amarṣa", "anger"],
         ["भय", "bhaya", "fear"],
         ["उद्वेगैः", "udvegaiḥ", "anxiety"]],
     3: [["मुक्तः", "muktaḥ", "freed from"],
         ["यः", "yaḥ", "who"],
         ["सः", "saḥ", "he"],
         ["च", "ca", "and"],
         ["मे", "me", "to me"],
         ["प्रियः", "priyaḥ", "dear"]]},

16: {"s": [],
     0: [["अनपेक्षः", "anapekṣaḥ", "unattached, indifferent"],
         ["शुचिः", "śuciḥ", "pure"],
         ["दक्षः", "dakṣaḥ", "capable"]],
     1: [["उदासीनः", "udāsīnaḥ", "neutral, indifferent"],
         ["गतव्यथः", "gatavyathaḥ", "free from anxiety"]],
     2: [["सर्वारम्भपरित्यागी", "sarvārambhaparityāgī", "renouncing all undertakings"]],
     3: [["यः", "yaḥ", "who"],
         ["मद्भक्तः", "madbhaktaḥ", "my devotee"],
         ["सः", "saḥ", "he"],
         ["मे", "me", "to me"],
         ["प्रियः", "priyaḥ", "dear"]]},

17: {"s": [],
     0: [["यः", "yaḥ", "who"],
         ["न", "na", "neither"],
         ["हृष्यति", "hṛṣyati", "rejoices"],
         ["न", "na", "nor"],
         ["द्वेष्टि", "dveṣṭi", "hates"]],
     1: [["न", "na", "neither"],
         ["शोचति", "śocati", "grieves"],
         ["न", "na", "nor"],
         ["काङ्क्षति", "kāṅkṣati", "desires"]],
     2: [["शुभाशुभपरित्यागी", "śubhāśubhaparityāgī", "renouncing good and evil"]],
     3: [["भक्तिमान्", "bhaktimān", "devoted"],
         ["यः", "yaḥ", "who"],
         ["सः", "saḥ", "he"],
         ["मे", "me", "to me"],
         ["प्रियः", "priyaḥ", "dear"]]},

18: {"s": [],
     0: [["समः", "samaḥ", "equal"],
         ["शत्रौ", "śatrau", "to an enemy"],
         ["च", "ca", "and"],
         ["मित्रे", "mitre", "to a friend"],
         ["च", "ca", "and"]],
     1: [["तथा", "tathā", "so"],
         ["मान", "māna", "honour"],
         ["अपमानयोः", "apamānayoḥ", "and dishonour"]],
     2: [["शीतोष्ण", "śītoṣṇa", "cold and heat"],
         ["सुखदुःखेषु", "sukhaduḥkheṣu", "in pleasure and pain"]],
     3: [["समः", "samaḥ", "equal"],
         ["सङ्गविवर्जितः", "saṅgavivarjitaḥ", "free from attachment"]]},

19: {"s": [],
     0: [["तुल्य", "tulya", "equal in"],
         ["निन्दा", "nindā", "blame"],
         ["स्तुतिः", "stutiḥ", "and praise"],
         ["मौनी", "maunī", "silent"]],
     1: [["सन्तुष्टः", "santuṣṭaḥ", "content"],
         ["येन", "yena", "with whatever"],
         ["केनचित्", "kenacit", "anything"]],
     2: [["अनिकेतः", "aniketaḥ", "homeless"],
         ["स्थिरमतिः", "sthiramatiḥ", "of steady mind"]],
     3: [["भक्तिमान्", "bhaktimān", "devoted"],
         ["मे", "me", "to me"],
         ["प्रियः", "priyaḥ", "dear"],
         ["नरः", "naraḥ", "man"]]},

20: {"s": [],
    0: [
    ["ये", "ye", "those who"], ["तु", "tu", "but"],
        ["धर्म्य", "dharmya", "righteous, immortal"], ["अमृतम्", "amṛtam", "nectar"],
        ["इदम्", "idam", "this"]],
    1: [
    ["यथोक्तम्", "yathoktam", "as declared"], ["पर्युपासते", "paryupāsate", "follow"]],
    2: [
    ["श्रद्दधानाः", "śraddadhānāḥ", "having faith"],
        ["मत्परमाः", "matparamāḥ", "making me the supreme goal"]],
    3: [
    ["भक्ताः", "bhaktāḥ", "devotees"], ["ते", "te", "they"],
        ["अतीव", "atīva", "exceedingly"], ["मे", "me", "to me"],
        ["प्रियाः", "priyāḥ", "dear"]]
},
}
