# -*- coding: utf-8 -*-
"""padachheda_ch16.py — per-pāda pada-chheda (word splits) for all 24 verses of Gita Chapter 16.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH16_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
          ["उवाच", "uvāca", "said"]],
    0: [["अभयम्", "abhayam", "fearlessness"],
        ["सत्त्वसंशुद्धिः", "sattvasaṁśuddhiḥ", "purity of heart"]],
    1: [["ज्ञानयोगव्यवस्थितिः", "jñānayogavyavasthitiḥ", "steadfastness in knowledge and yoga"]],
    2: [["दानम्", "dānam", "charity"],
        ["दमः", "damaḥ", "self-control"],
        ["च", "ca", "and"],
        ["यज्ञः", "yajñaḥ", "sacrifice"],
        ["च", "ca", "and"]],
    3: [["स्वाध्यायः", "svādhyāyaḥ", "study of scripture"],
        ["तपः", "tapaḥ", "austerity"],
        ["आर्जवम्", "ārjavam", "uprightness"]]},

2: {"s": [],
    0: [["अहिंसा", "ahiṁsā", "non-violence"],
        ["सत्यम्", "satyam", "truth"],
        ["अक्रोधः", "akrodhaḥ", "freedom from anger"]],
    1: [["त्यागः", "tyāgaḥ", "renunciation"],
        ["शान्तिः", "śāntiḥ", "peace"],
        ["अपैशुनम्", "apaiśunam", "absence of slander"]],
    2: [["दया", "dayā", "compassion"],
        ["भूतेषु", "bhūteṣu", "toward beings"],
        ["अलोलुप्त्वम्", "aloluptvam", "non-covetousness"]],
    3: [["मार्दवम्", "mārdavam", "gentleness"],
        ["ह्रीः", "hrīḥ", "modesty"],
        ["अचापलम्", "acāpalam", "steadiness"]]},

3: {"s": [],
    0: [["तेजः", "tejaḥ", "vigour"],
        ["क्षमा", "kṣamā", "forgiveness"],
        ["धृतिः", "dhṛtiḥ", "fortitude"],
        ["शौचम्", "śaucam", "purity"]],
    1: [["अद्रोहः", "adrohaḥ", "freedom from malice"],
        ["नातिमानिता", "nātimānitā", "freedom from pride"]],
    2: [["भवन्ति", "bhavanti", "they belong to"],
        ["सम्पदम्", "sampadam", "the endowment"],
        ["दैवीम्", "daivīm", "divine"]],
    3: [["अभिजातस्य", "abhijātasya", "of one born to"],
        ["भारत", "bhārata", "O Bhārata"]]},

4: {"s": [],
    0: [["दम्भः", "dambhaḥ", "hypocrisy"],
        ["दर्पः", "darpaḥ", "arrogance"],
        ["अतिमानः", "atimānaḥ", "pride"],
        ["च", "ca", "and"]],
    1: [["क्रोधः", "krodhaḥ", "anger"],
        ["पारुष्यम्", "pāruṣyam", "harshness"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["अज्ञानम्", "ajñānam", "ignorance"],
        ["च", "ca", "and"],
        ["अभिजातस्य", "abhijātasya", "of one born to"]],
    3: [["पार्थ", "pārtha", "O Pārtha"],
        ["सम्पदम्", "sampadam", "the endowment"],
        ["आसुरीम्", "āsurīm", "demoniac"]]},

5: {"s": [],
    0: [["दैवी", "daivī", "the divine"],
        ["सम्पत्", "sampat", "endowment"],
        ["विमोक्षाय", "vimokṣāya", "for liberation"]],
    1: [["निबन्धाय", "nibandhāya", "for bondage"],
        ["आसुरी", "āsurī", "the demoniac"],
        ["मता", "matā", "is deemed"]],
    2: [["मा", "mā", "do not"],
        ["शुचः", "śucaḥ", "grieve"],
        ["सम्पदम्", "sampadam", "to the endowment"],
        ["दैवीम्", "daivīm", "divine"]],
    3: [["अभिजातः", "abhijātaḥ", "born"],
        ["असि", "asi", "you are"],
        ["पाण्डव", "pāṇḍava", "O Pāṇḍava"]]},

6: {"s": [],
    0: [["द्वौ", "dvau", "two"],
        ["भूतसर्गौ", "bhūtasargau", "creations of beings"],
        ["लोके", "loke", "in the world"],
        ["अस्मिन्", "asmin", "this"]],
    1: [["दैवः", "daivaḥ", "the divine"],
        ["आसुरः", "āsuraḥ", "the demoniac"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["दैवः", "daivaḥ", "the divine"],
        ["विस्तरशः", "vistaraśaḥ", "at length"],
        ["प्रोक्तः", "proktaḥ", "described"]],
    3: [["आसुरम्", "āsuram", "the demoniac"],
        ["पार्थ", "pārtha", "O Pārtha"],
        ["मे", "me", "from me"],
        ["शृणु", "śṛṇu", "hear"]]},

7: {"s": [],
    0: [["प्रवृत्तिम्", "pravṛttim", "right action"],
        ["च", "ca", "and"],
        ["निवृत्तिम्", "nivṛttim", "renunciation"],
        ["च", "ca", "and"]],
    1: [["जनाः", "janāḥ", "people"],
        ["न", "na", "not"],
        ["विदुः", "viduḥ", "know"],
        ["आसुराः", "āsurāḥ", "the demoniac"]],
    2: [["न", "na", "not"],
        ["शौचम्", "śaucam", "purity"],
        ["न", "na", "nor"],
        ["अपि", "api", "even"],
        ["च", "ca", "and"],
        ["आचारः", "ācāraḥ", "conduct"]],
    3: [["न", "na", "nor"],
        ["सत्यम्", "satyam", "truth"],
        ["तेषु", "teṣu", "in them"],
        ["विद्यते", "vidyate", "there is"]]},

8: {"s": [],
    0: [["असत्यम्", "asatyam", "unreal"],
        ["अप्रतिष्ठम्", "apratiṣṭham", "without foundation"],
        ["ते", "te", "they"]],
    1: [["जगत्", "jagat", "the world"],
        ["आहुः", "āhuḥ", "say"],
        ["अनीश्वरम्", "anīśvaram", "without a Lord"]],
    2: [["अपरस्परसम्भूतम्", "aparasparasambhūtam", "produced by mutual union"]],
    3: [["किम्", "kim", "what"],
        ["अन्यत्", "anyat", "else"],
        ["कामहैतुकम्", "kāmahaitukam", "born of lust"]]},

9: {"s": [],
    0: [["एताम्", "etām", "this"],
        ["दृष्टिम्", "dṛṣṭim", "view"],
        ["अवष्टभ्य", "avaṣṭabhya", "having held"]],
    1: [["नष्टात्मानः", "naṣṭātmānaḥ", "ruined souls"],
        ["अल्पबुद्धयः", "alpabuddhayaḥ", "of little understanding"]],
    2: [["प्रभवन्ति", "prabhavanti", "they arise"],
        ["उग्रकर्माणः", "ugrakarmāṇaḥ", "performing cruel deeds"]],
    3: [["क्षयाय", "kṣayāya", "for the destruction"],
        ["जगतः", "jagataḥ", "of the world"],
        ["अहिताः", "ahitāḥ", "enemies"]]},

10: {"s": [],
    0: [["कामम्", "kāmam", "desire"],
        ["आश्रित्य", "āśritya", "resorting to"],
        ["दुष्पूरम्", "duṣpūram", "insatiable"]],
    1: [["दम्भ", "dambha", "hypocrisy"],
        ["मान", "māna", "pride"],
        ["मद", "mada", "arrogance"],
        ["अन्विताः", "anvitāḥ", "full of"]],
    2: [["मोहात्", "mohāt", "through delusion"],
        ["गृहीत्वा", "gṛhītvā", "having taken"],
        ["असद्ग्राहान्", "asadgrāhān", "false views"]],
    3: [["प्रवर्तन्ते", "pravartante", "they act"],
        ["अशुचिव्रताः", "aśucivratāḥ", "with impure resolves"]]},

11: {"s": [],
    0: [["चिन्ताम्", "cintām", "anxieties"],
        ["अपरिमेयाम्", "aparimeyām", "boundless"],
        ["च", "ca", "and"]],
    1: [["प्रलयान्ताम्", "pralayāntām", "ending in death"],
        ["उपाश्रिताः", "upāśritāḥ", "given to"]],
    2: [["कामोपभोगपरमाः", "kāmopabhogaparamāḥ", "intent on the enjoyment of desires"]],
    3: [["एतावत्", "etāvat", "this much"],
        ["इति", "iti", "thus"],
        ["निश्चिताः", "niścitāḥ", "resolved"]]},

12: {"s": [],
    0: [["आशापाशशतैः", "āśāpāśaśataiḥ", "by hundreds of fetters of hope"],
        ["बद्धाः", "baddhāḥ", "bound"]],
    1: [["कामक्रोधपरायणाः", "kāmakrodhaparāyaṇāḥ", "devoted to desire and anger"]],
    2: [["ईहन्ते", "īhante", "they strive"],
        ["कामभोगार्थम्", "kāmabhogārtham", "for the gratification of lust"]],
    3: [["अन्यायेन", "anyāyena", "by unjust means"],
        ["अर्थसञ्चयान्", "arthasañcayān", "hoards of wealth"]]},

13: {"s": [],
    0: [["इदम्", "idam", "this"],
        ["अद्य", "adya", "today"],
        ["मया", "mayā", "by me"],
        ["लब्धम्", "labdham", "gained"]],
    1: [["इदम्", "idam", "this"],
        ["प्राप्स्ये", "prāpsye", "I shall obtain"],
        ["मनोरथम्", "manoratham", "the wish"]],
    2: [["इदम्", "idam", "this"],
        ["अस्ति", "asti", "is"],
        ["इदम्", "idam", "this"],
        ["अपि", "api", "also"],
        ["मे", "me", "my"]],
    3: [["भविष्यति", "bhaviṣyati", "will be"],
        ["पुनः", "punaḥ", "again"],
        ["धनम्", "dhanam", "wealth"]]},

14: {"s": [],
    0: [["असौ", "asau", "that one"],
        ["मया", "mayā", "by me"],
        ["हतः", "hataḥ", "slain"],
        ["शत्रुः", "śatruḥ", "enemy"]],
    1: [["हनिष्ये", "haniṣye", "I will slay"],
        ["च", "ca", "and"],
        ["अपरान्", "aparān", "others"],
        ["अपि", "api", "also"]],
    2: [["ईश्वरः", "īśvaraḥ", "the lord"],
        ["अहम्", "aham", "I"],
        ["अहम्", "aham", "I"],
        ["भोगी", "bhogī", "the enjoyer"]],
    3: [["सिद्धः", "siddhaḥ", "accomplished"],
        ["अहम्", "aham", "I"],
        ["बलवान्", "balavān", "powerful"],
        ["सुखी", "sukhī", "happy"]]},

15: {"s": [],
    0: [["आढ्यः", "āḍhyaḥ", "rich"],
        ["अभिजनवान्", "abhijanavān", "well-born"],
        ["अस्मि", "asmi", "I am"]],
    1: [["कः", "kaḥ", "who"],
        ["अन्यः", "anyaḥ", "other"],
        ["अस्ति", "asti", "is"],
        ["सदृशः", "sadṛśaḥ", "like"],
        ["मया", "mayā", "me"]],
    2: [["यक्ष्ये", "yakṣye", "I will sacrifice"],
        ["दास्यामि", "dāsyāmi", "I will give"],
        ["मोदिष्ये", "modiṣye", "I will rejoice"]],
    3: [["इति", "iti", "thus"],
        ["अज्ञानविमोहिताः", "ajñānavimohitāḥ", "deluded by ignorance"]]},

16: {"s": [],
    0: [["अनेकचित्तविभ्रान्ताः", "anekacittavibhrāntāḥ", "bewildered by many thoughts"]],
    1: [["मोहजालसमावृताः", "mohajālasamāvṛtāḥ", "wrapped in the net of delusion"]],
    2: [["प्रसक्ताः", "prasaktāḥ", "devoted"],
        ["कामभोगेषु", "kāmabhogeṣu", "to sensual pleasures"]],
    3: [["पतन्ति", "patanti", "they fall"],
        ["नरके", "narake", "into hell"],
        ["अशुचौ", "aśucau", "foul"]]},

17: {"s": [],
    0: [["आत्मसम्भाविताः", "ātmasambhāvitāḥ", "self-conceited"],
        ["स्तब्धाः", "stabdhāḥ", "stubborn"]],
    1: [["धनमानमदान्विताः", "dhanamānamadānvitāḥ", "filled with the pride of wealth"]],
    2: [["यजन्ते", "yajante", "they perform sacrifices"],
        ["नामयज्ञैः", "nāmayajñaiḥ", "with sacrifices in name only"],
        ["ते", "te", "they"]],
    3: [["दम्भेन", "dambhena", "with hypocrisy"],
        ["अविधिपूर्वकम्", "avidhipūrvakam", "not according to the rule"]]},

18: {"s": [],
    0: [["अहङ्कारम्", "ahaṅkāram", "ego"],
        ["बलम्", "balam", "power"],
        ["दर्पम्", "darpam", "pride"]],
    1: [["कामम्", "kāmam", "desire"],
        ["क्रोधम्", "krodham", "anger"],
        ["च", "ca", "and"],
        ["संश्रिताः", "saṁśritāḥ", "having taken refuge in"]],
    2: [["माम्", "mām", "me"],
        ["आत्मपरदेहेषु", "ātmaparadeheṣu", "in their own and others' bodies"]],
    3: [["प्रद्विषन्तः", "pradviṣantaḥ", "hating"],
        ["अभ्यसूयकाः", "abhyasūyakāḥ", "malicious"]]},

19: {"s": [],
    0: [["तान्", "tān", "them"],
        ["अहम्", "aham", "I"],
        ["द्विषतः", "dviṣataḥ", "hating"],
        ["क्रूरान्", "krūrān", "cruel"]],
    1: [["संसारेषु", "saṁsāreṣu", "in the rounds of rebirth"],
        ["नराधमान्", "narādhamān", "the vilest of men"]],
    2: [["क्षिपामि", "kṣipāmi", "I cast"],
        ["अजस्रम्", "ajasram", "again and again"],
        ["अशुभान्", "aśubhān", "the evil"]],
    3: [["आसुरीषु", "āsurīṣu", "demoniac"],
        ["एव", "eva", "indeed"],
        ["योनिषु", "yoniṣu", "in the wombs"]]},

20: {"s": [],
    0: [["आसुरीम्", "āsurīm", "demoniac"],
        ["योनिम्", "yonim", "womb"],
        ["आपन्नाः", "āpannāḥ", "having entered"]],
    1: [["मूढाः", "mūḍhāḥ", "deluded"],
        ["जन्मनि", "janmani", "in birth"],
        ["जन्मनि", "janmani", "after birth"]],
    2: [["माम्", "mām", "me"],
        ["अप्राप्य", "aprāpya", "not reaching"],
        ["एव", "eva", "indeed"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    3: [["ततः", "tataḥ", "then"],
        ["यान्ति", "yānti", "they go"],
        ["अधमाम्", "adhamām", "to the lowest"],
        ["गतिम्", "gatim", "state"]]},

21: {"s": [],
    0: [["त्रिविधम्", "trividham", "threefold"],
        ["नरकस्य", "narakasya", "of hell"],
        ["इदम्", "idam", "this"]],
    1: [["द्वारम्", "dvāram", "gate"],
        ["नाशनम्", "nāśanam", "the destroyer"],
        ["आत्मनः", "ātmanaḥ", "of the self"]],
    2: [["कामः", "kāmaḥ", "desire"],
        ["क्रोधः", "krodhaḥ", "anger"],
        ["तथा", "tathā", "and"],
        ["लोभः", "lobhaḥ", "greed"]],
    3: [["तस्मात्", "tasmāt", "therefore"],
        ["एतत्", "etat", "these"],
        ["त्रयम्", "trayam", "three"],
        ["त्यजेत्", "tyajet", "one should abandon"]]},

22: {"s": [],
    0: [["एतैः", "etaiḥ", "from these"],
        ["विमुक्तः", "vimuktaḥ", "freed"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    1: [["तमोद्वारैः", "tamodvāraiḥ", "the gates of darkness"],
        ["त्रिभिः", "tribhiḥ", "the three"],
        ["नरः", "naraḥ", "a man"]],
    2: [["आचरति", "ācarati", "works for"],
        ["आत्मनः", "ātmanaḥ", "his own"],
        ["श्रेयः", "śreyaḥ", "good"]],
    3: [["ततः", "tataḥ", "then"],
        ["याति", "yāti", "he goes"],
        ["पराम्", "parām", "to the supreme"],
        ["गतिम्", "gatim", "goal"]]},

23: {"s": [],
    0: [["यः", "yaḥ", "who"],
        ["शास्त्रविधिम्", "śāstravidhim", "the ordinance of scripture"],
        ["उत्सृज्य", "utsṛjya", "having cast aside"]],
    1: [["वर्तते", "vartate", "acts"],
        ["कामकारतः", "kāmakārataḥ", "by the impulse of desire"]],
    2: [["न", "na", "not"],
        ["सः", "saḥ", "he"],
        ["सिद्धिम्", "siddhim", "perfection"],
        ["अवाप्नोति", "avāpnoti", "attains"]],
    3: [["न", "na", "nor"],
        ["सुखम्", "sukham", "happiness"],
        ["न", "na", "nor"],
        ["पराम्", "parām", "the supreme"],
        ["गतिम्", "gatim", "goal"]]},

24: {"s": [],
    0: [["तस्मात्", "tasmāt", "therefore"],
        ["शास्त्रम्", "śāstram", "the scripture"],
        ["प्रमाणम्", "pramāṇam", "the authority"],
        ["ते", "te", "for you"]],
    1: [["कार्याकार्यव्यवस्थितौ", "kāryākāryavyavasthitau", "in determining what is to be done and not done"]],
    2: [["ज्ञात्वा", "jñātvā", "having known"],
        ["शास्त्रविधानोक्तम्", "śāstravidhānoktam", "ordained by the scripture"]],
    3: [["कर्म", "karma", "action"],
        ["कर्तुम्", "kartum", "to do"],
        ["इह", "iha", "here"],
        ["अर्हसि", "arhasi", "you are fit"]]},

}
