# -*- coding: utf-8 -*-
"""padachheda_ch14.py — per-pāda pada-chheda (word splits) for all 27 verses of Gita Chapter 14.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH14_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["परम्", "param", "the supreme"],
        ["भूयः", "bhūyaḥ", "again"],
        ["प्रवक्ष्यामि", "pravakṣyāmi", "I will declare"]],
    1: [["ज्ञानानाम्", "jñānānām", "of the knowledges"],
        ["ज्ञानम्", "jñānam", "the knowledge"],
        ["उत्तमम्", "uttamam", "the best"]],
    2: [["यत्", "yat", "which"],
        ["ज्ञात्वा", "jñātvā", "knowing"],
        ["मुनयः", "munayaḥ", "the sages"],
        ["सर्वे", "sarve", "all"]],
    3: [["पराम्", "parām", "to the highest"],
        ["सिद्धिम्", "siddhim", "perfection"],
        ["इतः", "itaḥ", "from here"],
        ["गताः", "gatāḥ", "have gone"]]},

2: {"s": [],
    0: [["इदम्", "idam", "this"],
        ["ज्ञानम्", "jñānam", "knowledge"],
        ["उपाश्रित्य", "upāśritya", "having taken refuge in"]],
    1: [["मम", "mama", "my"],
        ["साधर्म्यम्", "sādharmyam", "unity of being"],
        ["आगताः", "āgatāḥ", "have attained"]],
    2: [["सर्गे", "sarge", "at creation"],
        ["अपि", "api", "even"],
        ["न", "na", "not"],
        ["उपजायन्ते", "upajāyante", "they are born"]],
    3: [["प्रलये", "pralaye", "at dissolution"],
        ["न", "na", "not"],
        ["व्यथन्ति", "vyathanti", "they are troubled"],
        ["च", "ca", "and"]]},

3: {"s": [],
    0: [["मम", "mama", "my"],
        ["योनिः", "yoniḥ", "the womb"],
        ["महत्", "mahat", "the great"],
        ["ब्रह्म", "brahma", "Brahman"]],
    1: [["तस्मिन्", "tasmin", "in it"],
        ["गर्भम्", "garbham", "the seed"],
        ["दधामि", "dadhāmi", "I place"],
        ["अहम्", "aham", "I"]],
    2: [["सम्भवः", "sambhavaḥ", "the birth"],
        ["सर्वभूतानाम्", "sarvabhūtānām", "of all beings"]],
    3: [["ततः", "tataḥ", "from that"],
        ["भवति", "bhavati", "comes about"],
        ["भारत", "bhārata", "O Bhārata"]]},

4: {"s": [],
    0: [["सर्वयोनिषु", "sarvayoniṣu", "in all wombs"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    1: [["मूर्तयः", "mūrtayaḥ", "the forms"],
        ["सम्भवन्ति", "sambhavanti", "arise"],
        ["याः", "yāḥ", "which"]],
    2: [["तासाम्", "tāsām", "of them"],
        ["ब्रह्म", "brahma", "Brahman"],
        ["महत्", "mahat", "the great"],
        ["योनिः", "yoniḥ", "the womb"]],
    3: [["अहम्", "aham", "I"],
        ["बीजप्रदः", "bījapradaḥ", "the seed-giving"],
        ["पिता", "pitā", "father"]]},

5: {"s": [],
    0: [["सत्त्वम्", "sattvam", "sattva"],
        ["रजः", "rajaḥ", "rajas"],
        ["तमः", "tamaḥ", "tamas"],
        ["इति", "iti", "thus"]],
    1: [["गुणाः", "guṇāḥ", "the qualities"],
        ["प्रकृतिसम्भवाः", "prakṛtisambhavāḥ", "born of prakṛti"]],
    2: [["निबध्नन्ति", "nibadhnanti", "they bind"],
        ["महाबाहो", "mahābāho", "O mighty-armed one"]],
    3: [["देहे", "dehe", "in the body"],
        ["देहिनम्", "dehinam", "the embodied one"],
        ["अव्ययम्", "avyayam", "the imperishable"]]},

6: {"s": [],
    0: [["तत्र", "tatra", "of these"],
        ["सत्त्वम्", "sattvam", "sattva"],
        ["निर्मलत्वात्", "nirmalatvāt", "because of purity"]],
    1: [["प्रकाशकम्", "prakāśakam", "illumining"],
        ["अनामयम्", "anāmayam", "free from disease"]],
    2: [["सुखसङ्गेन", "sukhasaṅgena", "by attachment to happiness"],
        ["बध्नाति", "badhnāti", "it binds"]],
    3: [["ज्ञानसङ्गेन", "jñānasaṅgena", "by attachment to knowledge"],
        ["च", "ca", "and"],
        ["अनघ", "anagha", "O sinless one"]]},

7: {"s": [],
    0: [["रजः", "rajaḥ", "rajas"],
        ["रागात्मकम्", "rāgātmakam", "of the nature of passion"],
        ["विद्धि", "viddhi", "know"]],
    1: [["तृष्णासङ्गसमुद्भवम्", "tṛṣṇāsaṅgasamudbhavam", "born of thirst and attachment"]],
    2: [["तत्", "tat", "it"],
        ["निबध्नाति", "nibadhnāti", "binds"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    3: [["कर्मसङ्गेन", "karmasaṅgena", "by attachment to action"],
        ["देहिनम्", "dehinam", "the embodied one"]]},

8: {"s": [],
    0: [["तमः", "tamaḥ", "tamas"],
        ["तु", "tu", "but"],
        ["अज्ञानजम्", "ajñānajam", "born of ignorance"],
        ["विद्धि", "viddhi", "know"]],
    1: [["मोहनम्", "mohanam", "deluding"],
        ["सर्वदेहिनाम्", "sarvadehinām", "of all embodied beings"]],
    2: [["प्रमादालस्यनिद्राभिः", "pramādālasyanidrābhiḥ", "by heedlessness, sloth and sleep"]],
    3: [["तत्", "tat", "it"],
        ["निबध्नाति", "nibadhnāti", "binds"],
        ["भारत", "bhārata", "O Bhārata"]]},

9: {"s": [],
    0: [["सत्त्वम्", "sattvam", "sattva"],
        ["सुखे", "sukhe", "to happiness"],
        ["सञ्जयति", "sañjayati", "attaches"]],
    1: [["रजः", "rajaḥ", "rajas"],
        ["कर्मणि", "karmaṇi", "to action"],
        ["भारत", "bhārata", "O Bhārata"]],
    2: [["ज्ञानम्", "jñānam", "knowledge"],
        ["आवृत्य", "āvṛtya", "covering"],
        ["तु", "tu", "but"],
        ["तमः", "tamaḥ", "tamas"]],
    3: [["प्रमादे", "pramāde", "to heedlessness"],
        ["सञ्जयति", "sañjayati", "attaches"],
        ["उत", "uta", "indeed"]]},

10: {"s": [],
     0: [["रजः", "rajaḥ", "rajas"],
         ["तमः", "tamaḥ", "tamas"],
         ["च", "ca", "and"],
         ["अभिभूय", "abhibhūya", "having overpowered"]],
     1: [["सत्त्वम्", "sattvam", "sattva"],
         ["भवति", "bhavati", "arises"],
         ["भारत", "bhārata", "O Bhārata"]],
     2: [["रजः", "rajaḥ", "rajas"],
         ["सत्त्वम्", "sattvam", "sattva"],
         ["तमः", "tamaḥ", "tamas"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     3: [["तमः", "tamaḥ", "tamas"],
         ["सत्त्वम्", "sattvam", "sattva"],
         ["रजः", "rajaḥ", "rajas"],
         ["तथा", "tathā", "so"]]},

11: {"s": [],
     0: [["सर्वद्वारेषु", "sarvadvāreṣu", "through all the gates"],
         ["देहे", "dehe", "in the body"],
         ["अस्मिन्", "asmin", "this"]],
     1: [["प्रकाशः", "prakāśaḥ", "light"],
         ["उपजायते", "upajāyate", "arises"]],
     2: [["ज्ञानम्", "jñānam", "knowledge"],
         ["यदा", "yadā", "when"],
         ["तदा", "tadā", "then"],
         ["विद्यात्", "vidyāt", "one should know"]],
     3: [["विवृद्धम्", "vivṛddham", "grown"],
         ["सत्त्वम्", "sattvam", "sattva"],
         ["इति", "iti", "thus"],
         ["उत", "uta", "indeed"]]},

12: {"s": [],
     0: [["लोभः", "lobhaḥ", "greed"],
         ["प्रवृत्तिः", "pravṛttiḥ", "activity"],
         ["आरम्भः", "ārambhaḥ", "undertaking"]],
     1: [["कर्मणाम्", "karmaṇām", "of works"],
         ["अशमः", "aśamaḥ", "restlessness"],
         ["स्पृहा", "spṛhā", "longing"]],
     2: [["रजसि", "rajasi", "in rajas"],
         ["एतानि", "etāni", "these"],
         ["जायन्ते", "jāyante", "arise"]],
     3: [["विवृद्धे", "vivṛddhe", "when grown"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]]},

13: {"s": [],
     0: [["अप्रकाशः", "aprakāśaḥ", "darkness"],
         ["अप्रवृत्तिः", "apravṛttiḥ", "inertia"],
         ["च", "ca", "and"]],
     1: [["प्रमादः", "pramādaḥ", "heedlessness"],
         ["मोहः", "mohaḥ", "delusion"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["तमसि", "tamasi", "in tamas"],
         ["एतानि", "etāni", "these"],
         ["जायन्ते", "jāyante", "arise"]],
     3: [["विवृद्धे", "vivṛddhe", "when grown"],
         ["कुरुनन्दन", "kurunandana", "O joy of the Kurus"]]},

14: {"s": [],
     0: [["यदा", "yadā", "when"],
         ["सत्त्वे", "sattve", "in sattva"],
         ["प्रवृद्धे", "pravṛddhe", "grown"],
         ["तु", "tu", "indeed"]],
     1: [["प्रलयम्", "pralayam", "death"],
         ["याति", "yāti", "goes"],
         ["देहभृत्", "dehabhṛt", "the embodied one"]],
     2: [["तदा", "tadā", "then"],
         ["उत्तमविदाम्", "uttamavidām", "of the knowers of the highest"],
         ["लोकान्", "lokān", "the worlds"]],
     3: [["अमलान्", "amalān", "pure"],
         ["प्रतिपद्यते", "pratipadyate", "he attains"]]},

15: {"s": [],
     0: [["रजसि", "rajasi", "in rajas"],
         ["प्रलयम्", "pralayam", "death"],
         ["गत्वा", "gatvā", "having gone"]],
     1: [["कर्मसङ्गिषु", "karmasaṅgiṣu", "among those attached to action"],
         ["जायते", "jāyate", "one is born"]],
     2: [["तथा", "tathā", "so"],
         ["प्रलीनः", "pralīnaḥ", "dissolved"],
         ["तमसि", "tamasi", "in tamas"]],
     3: [["मूढयोनिषु", "mūḍhayoniṣu", "in the wombs of the deluded"],
         ["जायते", "jāyate", "one is born"]]},

16: {"s": [],
     0: [["कर्मणः", "karmaṇaḥ", "of action"],
         ["सुकृतस्य", "sukṛtasya", "good"],
         ["आहुः", "āhuḥ", "they say"]],
     1: [["सात्त्विकम्", "sāttvikam", "sāttvic"],
         ["निर्मलम्", "nirmalam", "pure"],
         ["फलम्", "phalam", "the fruit"]],
     2: [["रजसः", "rajasaḥ", "of rajas"],
         ["तु", "tu", "but"],
         ["फलम्", "phalam", "the fruit"],
         ["दुःखम्", "duḥkham", "sorrow"]],
     3: [["अज्ञानम्", "ajñānam", "ignorance"],
         ["तमसः", "tamasaḥ", "of tamas"],
         ["फलम्", "phalam", "the fruit"]]},

17: {"s": [],
     0: [["सत्त्वात्", "sattvāt", "from sattva"],
         ["सञ्जायते", "sañjāyate", "arises"],
         ["ज्ञानम्", "jñānam", "knowledge"]],
     1: [["रजसः", "rajasaḥ", "from rajas"],
         ["लोभः", "lobhaḥ", "greed"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["प्रमादमोहौ", "pramādamohau", "heedlessness and delusion"],
         ["तमसः", "tamasaḥ", "of tamas"]],
     3: [["भवतः", "bhavataḥ", "arise"],
         ["अज्ञानम्", "ajñānam", "ignorance"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]]},

18: {"s": [],
     0: [["ऊर्ध्वम्", "ūrdhvam", "upward"],
         ["गच्छन्ति", "gacchanti", "they go"],
         ["सत्त्वस्थाः", "sattvasthāḥ", "those established in sattva"]],
     1: [["मध्ये", "madhye", "in the middle"],
         ["तिष्ठन्ति", "tiṣṭhanti", "they stay"],
         ["राजसाः", "rājasāḥ", "the rājasic"]],
     2: [["जघन्यगुणवृत्तस्थाः", "jaghanyaguṇavṛttasthāḥ", "those engaged in the lowest quality"]],
     3: [["अधः", "adhaḥ", "downward"],
         ["गच्छन्ति", "gacchanti", "they go"],
         ["तामसाः", "tāmasāḥ", "the tāmasic"]]},

19: {"s": [],
     0: [["न", "na", "no"],
         ["अन्यम्", "anyam", "other"],
         ["गुणेभ्यः", "guṇebhyaḥ", "than the guṇas"],
         ["कर्तारम्", "kartāram", "agent"]],
     1: [["यदा", "yadā", "when"],
         ["द्रष्टा", "draṣṭā", "the seer"],
         ["अनुपश्यति", "anupaśyati", "perceives"]],
     2: [["गुणेभ्यः", "guṇebhyaḥ", "beyond the guṇas"],
         ["च", "ca", "and"],
         ["परम्", "param", "what is beyond"],
         ["वेत्ति", "vetti", "knows"]],
     3: [["मद्भावम्", "madbhāvam", "my being"],
         ["सः", "saḥ", "he"],
         ["अधिगच्छति", "adhigacchati", "attains"]]},

20: {"s": [],
     0: [["गुणान्", "guṇān", "the guṇas"],
         ["एतान्", "etān", "these"],
         ["अतीत्य", "atītya", "having transcended"],
         ["त्रीन्", "trīn", "the three"]],
     1: [["देही", "dehī", "the embodied one"],
         ["देहसमुद्भवान्", "dehasamudbhavān", "born of the body"]],
     2: [["जन्ममृत्युजरादुःखैः", "janmamṛtyujarāduḥkhaiḥ", "from birth, death, old age and sorrow"]],
     3: [["विमुक्तः", "vimuktaḥ", "freed"],
         ["अमृतम्", "amṛtam", "immortality"],
         ["अश्नुते", "aśnute", "tastes"]]},

21: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["कैः", "kaiḥ", "by what"],
         ["लिङ्गैः", "liṅgaiḥ", "marks"],
         ["त्रीन्", "trīn", "the three"],
         ["गुणान्", "guṇān", "guṇas"],
         ["एतान्", "etān", "these"]],
     1: [["अतीतः", "atītaḥ", "one who has transcended"],
         ["भवति", "bhavati", "is"],
         ["प्रभो", "prabho", "O Lord"]],
     2: [["किम्", "kim", "what"],
         ["आचारः", "ācāraḥ", "conduct"],
         ["कथम्", "katham", "how"],
         ["च", "ca", "and"],
         ["एतान्", "etān", "these"]],
     3: [["त्रीन्", "trīn", "the three"],
         ["गुणान्", "guṇān", "guṇas"],
         ["अतिवर्तते", "ativartate", "does he transcend"]]},

22: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
     0: [["प्रकाशम्", "prakāśam", "illumination"],
         ["च", "ca", "and"],
         ["प्रवृत्तिम्", "pravṛttim", "activity"],
         ["च", "ca", "and"]],
     1: [["मोहम्", "moham", "delusion"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"],
         ["पाण्डव", "pāṇḍava", "O Pāṇḍava"]],
     2: [["न", "na", "not"],
         ["द्वेष्टि", "dveṣṭi", "hates"],
         ["सम्प्रवृत्तानि", "sampravṛttāni", "arisen"]],
     3: [["न", "na", "nor"],
         ["निवृत्तानि", "nivṛttāni", "ceased"],
         ["काङ्क्षति", "kāṅkṣati", "longs for"]]},

23: {"s": [],
     0: [["उदासीनवत्", "udāsīnavat", "like an indifferent one"],
         ["आसीनः", "āsīnaḥ", "seated"]],
     1: [["गुणैः", "guṇaiḥ", "by the guṇas"],
         ["यः", "yaḥ", "who"],
         ["न", "na", "not"],
         ["विचाल्यते", "vicālyate", "is shaken"]],
     2: [["गुणाः", "guṇāḥ", "the guṇas"],
         ["वर्तन्ते", "vartante", "act"],
         ["इति", "iti", "thus"],
         ["एव", "eva", "indeed"]],
     3: [["यः", "yaḥ", "who"],
         ["अवतिष्ठति", "avatiṣṭhati", "abides"],
         ["न", "na", "not"],
         ["इङ्गते", "iṅgate", "moves"]]},

24: {"s": [],
     0: [["समदुःखसुखः", "samaduḥkhasukhaḥ", "equal in pleasure and pain"],
         ["स्वस्थः", "svasthaḥ", "self-abiding"]],
     1: [["समलोष्टाश्मकाञ्चनः", "samaloṣṭāśmakāñcanaḥ", "to whom clod, stone and gold are alike"]],
     2: [["तुल्यप्रियाप्रियः", "tulyapriyāpriyaḥ", "equal to the pleasant and unpleasant"],
         ["धीरः", "dhīraḥ", "firm"]],
     3: [["तुल्यनिन्दात्मसंस्तुतिः", "tulyanindātmasaṁstutiḥ", "equal in blame and self-praise"]]},

25: {"s": [],
     0: [["मानापमानयोः", "mānāpamānayoḥ", "in honour and dishonour"],
         ["तुल्यः", "tulyaḥ", "equal"]],
     1: [["तुल्यः", "tulyaḥ", "equal"],
         ["मित्रारिपक्षयोः", "mitrāripakṣayoḥ", "to friend and foe"]],
     2: [["सर्वारम्भपरित्यागी", "sarvārambhaparityāgī", "renouncing all undertakings"]],
     3: [["गुणातीतः", "guṇātītaḥ", "beyond the guṇas"],
         ["सः", "saḥ", "he"],
         ["उच्यते", "ucyate", "is said to be"]]},

26: {"s": [],
     0: [["माम्", "mām", "me"],
         ["च", "ca", "and"],
         ["यः", "yaḥ", "who"],
         ["अव्यभिचारेण", "avyabhicāreṇa", "with unwavering"]],
     1: [["भक्तियोगेन", "bhaktiyogena", "with the yoga of devotion"],
         ["सेवते", "sevate", "serves"]],
     2: [["सः", "saḥ", "he"],
         ["गुणान्", "guṇān", "the guṇas"],
         ["समतीत्य", "samatītya", "having transcended"],
         ["एतान्", "etān", "these"]],
     3: [["ब्रह्मभूयाय", "brahmabhūyāya", "for Brahman"],
         ["कल्पते", "kalpate", "becomes fit"]]},

27: {"s": [],
     0: [["ब्रह्मणः", "brahmaṇaḥ", "of Brahman"],
         ["हि", "hi", "indeed"],
         ["प्रतिष्ठा", "pratiṣṭhā", "the support"],
         ["अहम्", "aham", "I"]],
     1: [["अमृतस्य", "amṛtasya", "of immortality"],
         ["अव्ययस्य", "avyayasya", "the imperishable"],
         ["च", "ca", "and"]],
     2: [["शाश्वतस्य", "śāśvatasya", "of the eternal"],
         ["च", "ca", "and"],
         ["धर्मस्य", "dharmasya", "of dharma"]],
     3: [["सुखस्य", "sukhasya", "of bliss"],
         ["एकान्तिकस्य", "ekāntikasya", "absolute"],
         ["च", "ca", "and"]]},
}
