# -*- coding: utf-8 -*-
"""padachheda_ch15.py — per-pāda pada-chheda (word splits) for all 20 verses of Gita Chapter 15.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH15_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["ऊर्ध्व", "ūrdhva", "above"],
        ["मूलम्", "mūlam", "root"],
        ["अधः", "adhaḥ", "below"],
        ["शाखम्", "śākham", "branches"]],
    1: [["अश्वत्थम्", "aśvattham", "the sacred fig (world-tree)"],
        ["प्राहुः", "prāhuḥ", "they speak of"],
        ["अव्ययम्", "avyayam", "imperishable"]],
    2: [["छन्दांसि", "chandāṁsi", "the Vedas"],
        ["यस्य", "yasya", "whose"],
        ["पर्णानि", "parṇāni", "leaves"]],
    3: [["यः", "yaḥ", "who"],
        ["तम्", "tam", "it"],
        ["वेद", "veda", "knows"],
        ["सः", "saḥ", "he"],
        ["वेदवित्", "vedavit", "the knower of the Vedas"]]},

2: {"s": [],
    0: [["अधः", "adhaḥ", "below"],
        ["च", "ca", "and"],
        ["ऊर्ध्वम्", "ūrdhvam", "above"],
        ["प्रसृताः", "prasṛtāḥ", "spread out"],
        ["तस्य", "tasya", "its"],
        ["शाखाः", "śākhāḥ", "branches"]],
    1: [["गुणप्रवृद्धाः", "guṇapravṛddhāḥ", "nourished by the guṇas"],
        ["विषयप्रवालाः", "viṣayapravālāḥ", "with sense-objects as shoots"]],
    2: [["अधः", "adhaḥ", "below"],
        ["च", "ca", "and"],
        ["मूलानि", "mūlāni", "the roots"],
        ["अनुसन्ततानि", "anusantatāni", "stretching down"]],
    3: [["कर्मानुबन्धीनि", "karmānubandhīni", "binding to action"],
        ["मनुष्यलोके", "manuṣyaloke", "in the world of men"]]},

3: {"s": [],
    0: [["न", "na", "not"],
        ["रूपम्", "rūpam", "the form"],
        ["अस्य", "asya", "of it"],
        ["इह", "iha", "here"],
        ["तथा", "tathā", "thus"],
        ["उपलभ्यते", "upalabhyate", "is perceived"]],
    1: [["न", "na", "nor"],
        ["अन्तः", "antaḥ", "end"],
        ["न", "na", "nor"],
        ["च", "ca", "and"],
        ["आदिः", "ādiḥ", "beginning"],
        ["न", "na", "nor"],
        ["च", "ca", "and"],
        ["सम्प्रतिष्ठा", "sampratiṣṭhā", "support"]],
    2: [["अश्वत्थम्", "aśvattham", "the aśvattha"],
        ["एनम्", "enam", "this"],
        ["सुविरूढ", "suvirūḍha", "firmly-rooted"],
        ["मूलम्", "mūlam", "root"]],
    3: [["असङ्ग", "asaṅga", "of detachment"],
        ["शस्त्रेण", "śastreṇa", "with the axe"],
        ["दृढेन", "dṛḍhena", "strong"],
        ["छित्त्वा", "chittvā", "having cut"]]},

4: {"s": [],
    0: [["ततः", "tataḥ", "then"],
        ["पदम्", "padam", "the state"],
        ["तत्", "tat", "that"],
        ["परिमार्गितव्यम्", "parimārgitavyam", "must be sought"]],
    1: [["यस्मिन्", "yasmin", "from which"],
        ["गताः", "gatāḥ", "having gone"],
        ["न", "na", "not"],
        ["निवर्तन्ति", "nivartanti", "they return"],
        ["भूयः", "bhūyaḥ", "again"]],
    2: [["तम्", "tam", "to him"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"],
        ["आद्यम्", "ādyam", "the primal"],
        ["पुरुषम्", "puruṣam", "Person"],
        ["प्रपद्ये", "prapadye", "I take refuge"]],
    3: [["यतः", "yataḥ", "from whom"],
        ["प्रवृत्तिः", "pravṛttiḥ", "the course"],
        ["प्रसृता", "prasṛtā", "flowing"],
        ["पुराणी", "purāṇī", "ancient"]]},

5: {"s": [],
    0: [["निर्मानमोहाः", "nirmānamohāḥ", "free from pride and delusion"],
        ["जितसङ्गदोषाः", "jitasaṅgadoṣāḥ", "having conquered the fault of attachment"]],
    1: [["अध्यात्मनित्याः", "adhyātmanityāḥ", "ever established in the Self"],
        ["विनिवृत्तकामाः", "vinivṛttakāmāḥ", "desires turned away"]],
    2: [["द्वन्द्वैः", "dvandvaiḥ", "from the pairs"],
        ["विमुक्ताः", "vimuktāḥ", "freed"],
        ["सुखदुःखसंज्ञैः", "sukhaduḥkhasaṁjñaiḥ", "known as pleasure and pain"]],
    3: [["गच्छन्ति", "gacchanti", "they reach"],
        ["अमूढाः", "amūḍhāḥ", "the undeluded"],
        ["पदम्", "padam", "the state"],
        ["अव्ययम्", "avyayam", "imperishable"],
        ["तत्", "tat", "that"]]},

6: {"s": [],
    0: [["न", "na", "not"],
        ["तत्", "tat", "that"],
        ["भासयते", "bhāsayate", "illumines"],
        ["सूर्यः", "sūryaḥ", "the sun"]],
    1: [["न", "na", "nor"],
        ["शशाङ्कः", "śaśāṅkaḥ", "the moon"],
        ["न", "na", "nor"],
        ["पावकः", "pāvakaḥ", "fire"]],
    2: [["यत्", "yat", "where"],
        ["गत्वा", "gatvā", "having gone"],
        ["न", "na", "not"],
        ["निवर्तन्ते", "nivartante", "they return"]],
    3: [["तत्", "tat", "that"],
        ["धाम", "dhāma", "abode"],
        ["परमम्", "paramam", "supreme"],
        ["मम", "mama", "my"]]},

7: {"s": [],
    0: [["मम", "mama", "my"],
        ["एव", "eva", "indeed"],
        ["अंशः", "aṁśaḥ", "a portion"],
        ["जीवलोके", "jīvaloke", "in the world of life"]],
    1: [["जीवभूतः", "jīvabhūtaḥ", "become a living soul"],
        ["सनातनः", "sanātanaḥ", "eternal"]],
    2: [["मनःषष्ठानि", "manaḥṣaṣṭhāni", "of which the mind is the sixth"],
        ["इन्द्रियाणि", "indriyāṇi", "the senses"]],
    3: [["प्रकृतिस्थानि", "prakṛtisthāni", "resting in prakṛti"],
        ["कर्षति", "karṣati", "draws"]]},

8: {"s": [],
    0: [["शरीरम्", "śarīram", "a body"],
        ["यत्", "yat", "when"],
        ["अवाप्नोति", "avāpnoti", "he obtains"]],
    1: [["यत्", "yat", "and when"],
        ["च", "ca", "and"],
        ["अपि", "api", "indeed"],
        ["उत्क्रामति", "utkrāmati", "he departs"],
        ["ईश्वरः", "īśvaraḥ", "the lord"]],
    2: [["गृहीत्वा", "gṛhītvā", "having taken"],
        ["एतानि", "etāni", "these"],
        ["संयाति", "saṁyāti", "he goes"]],
    3: [["वायुः", "vāyuḥ", "the wind"],
        ["गन्धान्", "gandhān", "fragrances"],
        ["इव", "iva", "as"],
        ["आशयात्", "āśayāt", "from its seat"]]},

9: {"s": [],
    0: [["श्रोत्रम्", "śrotram", "hearing"],
        ["चक्षुः", "cakṣuḥ", "sight"],
        ["स्पर्शनम्", "sparśanam", "touch"],
        ["च", "ca", "and"]],
    1: [["रसनम्", "rasanam", "taste"],
        ["घ्राणम्", "ghrāṇam", "smell"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["अधिष्ठाय", "adhiṣṭhāya", "presiding over"],
        ["मनः", "manaḥ", "the mind"],
        ["च", "ca", "and"],
        ["अयम्", "ayam", "this"]],
    3: [["विषयान्", "viṣayān", "the sense-objects"],
        ["उपसेवते", "upasevate", "enjoys"]]},

10: {"s": [],
     0: [["उत्क्रामन्तम्", "utkrāmantam", "departing"],
         ["स्थितम्", "sthitam", "dwelling"],
         ["वा", "vā", "or"],
         ["अपि", "api", "even"]],
     1: [["भुञ्जानम्", "bhuñjānam", "enjoying"],
         ["वा", "vā", "or"],
         ["गुणान्वितम्", "guṇānvitam", "joined with the guṇas"]],
     2: [["विमूढाः", "vimūḍhāḥ", "the deluded"],
         ["न", "na", "not"],
         ["अनुपश्यन्ति", "anupaśyanti", "they see"]],
     3: [["पश्यन्ति", "paśyanti", "they see"],
         ["ज्ञानचक्षुषः", "jñānacakṣuṣaḥ", "those with the eye of knowledge"]]},

11: {"s": [],
     0: [["यतन्तः", "yatantaḥ", "striving"],
         ["योगिनः", "yoginaḥ", "the yogis"],
         ["च", "ca", "and"],
         ["एनम्", "enam", "him"]],
     1: [["पश्यन्ति", "paśyanti", "see"],
         ["आत्मनि", "ātmani", "in the Self"],
         ["अवस्थितम्", "avasthitam", "established"]],
     2: [["यतन्तः", "yatantaḥ", "striving"],
         ["अपि", "api", "though"],
         ["अकृतात्मानः", "akṛtātmānaḥ", "the undisciplined"]],
     3: [["न", "na", "not"],
         ["एनम्", "enam", "him"],
         ["पश्यन्ति", "paśyanti", "see"],
         ["अचेतसः", "acetasaḥ", "lacking understanding"]]},

12: {"s": [],
     0: [["यत्", "yat", "which"],
         ["आदित्यगतम्", "ādityagatam", "in the sun"],
         ["तेजः", "tejaḥ", "light"]],
     1: [["जगत्", "jagat", "the world"],
         ["भासयते", "bhāsayate", "illumines"],
         ["अखिलम्", "akhilam", "whole"]],
     2: [["यत्", "yat", "which"],
         ["चन्द्रमसि", "candramasi", "in the moon"],
         ["यत्", "yat", "which"],
         ["च", "ca", "and"],
         ["अग्नौ", "agnau", "in fire"]],
     3: [["तत्", "tat", "that"],
         ["तेजः", "tejaḥ", "light"],
         ["विद्धि", "viddhi", "know"],
         ["मामकम्", "māmakam", "as mine"]]},

13: {"s": [],
     0: [["गाम्", "gām", "the earth"],
         ["आविश्य", "āviśya", "having entered"],
         ["च", "ca", "and"],
         ["भूतानि", "bhūtāni", "beings"]],
     1: [["धारयामि", "dhārayāmi", "I sustain"],
         ["अहम्", "aham", "I"],
         ["ओजसा", "ojasā", "with my energy"]],
     2: [["पुष्णामि", "puṣṇāmi", "I nourish"],
         ["च", "ca", "and"],
         ["औषधीः", "auṣadhīḥ", "the herbs"],
         ["सर्वाः", "sarvāḥ", "all"]],
     3: [["सोमः", "somaḥ", "the moon"],
         ["भूत्वा", "bhūtvā", "having become"],
         ["रसात्मकः", "rasātmakaḥ", "the sap-natured"]]},

14: {"s": [],
     0: [["अहम्", "aham", "I"],
         ["वैश्वानरः", "vaiśvānaraḥ", "the fire of digestion"],
         ["भूत्वा", "bhūtvā", "becoming"]],
     1: [["प्राणिनाम्", "prāṇinām", "of living beings"],
         ["देहम्", "deham", "in the body"],
         ["आश्रितः", "āśritaḥ", "dwelling"]],
     2: [["प्राणापानसमायुक्तः", "prāṇāpānasamāyuktaḥ", "joined with the in-breath and out-breath"]],
     3: [["पचामि", "pacāmi", "I digest"],
         ["अन्नम्", "annam", "food"],
         ["चतुर्विधम्", "caturvidham", "of four kinds"]]},

15: {"s": [],
     0: [["सर्वस्य", "sarvasya", "of all"],
         ["च", "ca", "and"],
         ["अहम्", "aham", "I"],
         ["हृदि", "hṛdi", "in the heart"],
         ["सन्निविष्टः", "sanniviṣṭaḥ", "seated"]],
     1: [["मत्तः", "mattaḥ", "from me"],
         ["स्मृतिः", "smṛtiḥ", "memory"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["अपोहनम्", "apohanam", "their removal"],
         ["च", "ca", "and"]],
     2: [["वेदैः", "vedaiḥ", "by the Vedas"],
         ["च", "ca", "and"],
         ["सर्वैः", "sarvaiḥ", "all"],
         ["अहम्", "aham", "I"],
         ["एव", "eva", "alone"],
         ["वेद्यः", "vedyaḥ", "to be known"]],
     3: [["वेदान्तकृत्", "vedāntakṛt", "the author of Vedānta"],
         ["वेदवित्", "vedavit", "the knower of the Vedas"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"],
         ["अहम्", "aham", "I"]]},

16: {"s": [],
     0: [["द्वौ", "dvau", "two"],
         ["इमौ", "imau", "these"],
         ["पुरुषौ", "puruṣau", "persons"],
         ["लोके", "loke", "in the world"]],
     1: [["क्षरः", "kṣaraḥ", "the perishable"],
         ["च", "ca", "and"],
         ["अक्षरः", "akṣaraḥ", "the imperishable"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["क्षरः", "kṣaraḥ", "the perishable"],
         ["सर्वाणि", "sarvāṇi", "all"],
         ["भूतानि", "bhūtāni", "beings"]],
     3: [["कूटस्थः", "kūṭasthaḥ", "the unchanging"],
         ["अक्षरः", "akṣaraḥ", "the imperishable"],
         ["उच्यते", "ucyate", "is called"]]},

17: {"s": [],
     0: [["उत्तमः", "uttamaḥ", "the highest"],
         ["पुरुषः", "puruṣaḥ", "Person"],
         ["तु", "tu", "but"],
         ["अन्यः", "anyaḥ", "another"]],
     1: [["परमात्मा", "paramātmā", "the supreme Self"],
         ["इति", "iti", "thus"],
         ["उदाहृतः", "udāhṛtaḥ", "is called"]],
     2: [["यः", "yaḥ", "who"],
         ["लोकत्रयम्", "lokatrayam", "the three worlds"],
         ["आविश्य", "āviśya", "entering"]],
     3: [["बिभर्ति", "bibharti", "sustains"],
         ["अव्ययः", "avyayaḥ", "imperishable"],
         ["ईश्वरः", "īśvaraḥ", "the Lord"]]},

18: {"s": [],
     0: [["यस्मात्", "yasmāt", "since"],
         ["क्षरम्", "kṣaram", "the perishable"],
         ["अतीतः", "atītaḥ", "transcending"],
         ["अहम्", "aham", "I"]],
     1: [["अक्षरात्", "akṣarāt", "than the imperishable"],
         ["अपि", "api", "even"],
         ["च", "ca", "and"],
         ["उत्तमः", "uttamaḥ", "higher"]],
     2: [["अतः", "ataḥ", "therefore"],
         ["अस्मि", "asmi", "I am"],
         ["लोके", "loke", "in the world"],
         ["वेदे", "vede", "and in the Veda"],
         ["च", "ca", "and"]],
     3: [["प्रथितः", "prathitaḥ", "renowned"],
         ["पुरुषोत्तमः", "puruṣottamaḥ", "the highest Person"]]},

19: {"s": [],
     0: [["यः", "yaḥ", "who"],
         ["माम्", "mām", "me"],
         ["एवम्", "evam", "thus"],
         ["असम्मूढः", "asammūḍhaḥ", "undeluded"]],
     1: [["जानाति", "jānāti", "knows"],
         ["पुरुषोत्तमम्", "puruṣottamam", "the highest Person"]],
     2: [["सः", "saḥ", "he"],
         ["सर्ववित्", "sarvavit", "knowing all"],
         ["भजति", "bhajati", "worships"],
         ["माम्", "mām", "me"]],
     3: [["सर्वभावेन", "sarvabhāvena", "with all his being"],
         ["भारत", "bhārata", "O Bhārata"]]},

20: {"s": [],
     0: [["इति", "iti", "thus"],
         ["गुह्यतमम्", "guhyatamam", "the most secret"],
         ["शास्त्रम्", "śāstram", "scripture"]],
     1: [["इदम्", "idam", "this"],
         ["उक्तम्", "uktam", "declared"],
         ["मया", "mayā", "by me"],
         ["अनघ", "anagha", "O sinless one"]],
     2: [["एतत्", "etat", "this"],
         ["बुद्ध्वा", "buddhvā", "having understood"],
         ["बुद्धिमान्", "buddhimān", "wise"],
         ["स्यात्", "syāt", "becomes"]],
     3: [["कृतकृत्यः", "kṛtakṛtyaḥ", "having done all"],
         ["च", "ca", "and"],
         ["भारत", "bhārata", "O Bhārata"]]},
}
