# -*- coding: utf-8 -*-
"""padachheda_ch10.py — per-pāda pada-chheda (word splits) for all 42 verses of Gita Chapter 10.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH10_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["भूयः", "bhūyaḥ", "again"],
        ["एव", "eva", "indeed"],
        ["महाबाहो", "mahābāho", "O mighty-armed one"]],
    1: [["शृणु", "śṛṇu", "hear"],
        ["मे", "me", "my"],
        ["परमम्", "paramam", "supreme"],
        ["वचः", "vacaḥ", "words"]],
    2: [["यत्", "yat", "which"],
        ["ते", "te", "to you"],
        ["अहम्", "aham", "I"],
        ["प्रीयमाणाय", "prīyamāṇāya", "to one who is dear"]],
    3: [["वक्ष्यामि", "vakṣyāmi", "will speak"],
        ["हितकाम्यया", "hitakāmyayā", "wishing your good"]]},

2: {"s": [],
    0: [["न", "na", "not"],
        ["मे", "me", "my"],
        ["विदुः", "viduḥ", "they know"],
        ["सुरगणाः", "suragaṇāḥ", "the hosts of gods"]],
    1: [["प्रभवम्", "prabhavam", "the origin"],
        ["न", "na", "not"],
        ["महर्षयः", "maharṣayaḥ", "the great seers"]],
    2: [["अहम्", "aham", "I"],
        ["आदिः", "ādiḥ", "the beginning"],
        ["हि", "hi", "indeed"],
        ["देवानाम्", "devānām", "of the gods"]],
    3: [["महर्षीणाम्", "maharṣīṇām", "of the great seers"],
        ["च", "ca", "and"],
        ["सर्वशः", "sarvaśaḥ", "in every way"]]},

3: {"s": [],
    0: [["यः", "yaḥ", "who"],
        ["माम्", "mām", "me"],
        ["अजम्", "ajam", "the unborn"],
        ["अनादिम्", "anādim", "without beginning"],
        ["च", "ca", "and"]],
    1: [["वेत्ति", "vetti", "knows"],
        ["लोकमहेश्वरम्", "lokamaheśvaram", "the great Lord of the world"]],
    2: [["असम्मूढः", "asammūḍhaḥ", "undeluded"],
        ["सः", "saḥ", "he"],
        ["मर्त्येषु", "martyeṣu", "among mortals"]],
    3: [["सर्वपापैः", "sarvapāpaiḥ", "from all sins"],
        ["प्रमुच्यते", "pramucyate", "is freed"]]},

4: {"s": [],
    0: [["बुद्धिः", "buddhiḥ", "intellect"],
        ["ज्ञानम्", "jñānam", "knowledge"],
        ["असम्मोहः", "asammohaḥ", "freedom from delusion"]],
    1: [["क्षमा", "kṣamā", "forbearance"],
        ["सत्यम्", "satyam", "truth"],
        ["दमः", "damaḥ", "self-control"],
        ["शमः", "śamaḥ", "calm"]],
    2: [["सुखम्", "sukham", "pleasure"],
        ["दुःखम्", "duḥkham", "pain"],
        ["भवः", "bhavaḥ", "birth"],
        ["अभावः", "abhāvaḥ", "ceasing"]],
    3: [["भयम्", "bhayam", "fear"],
        ["च", "ca", "and"],
        ["अभयम्", "abhayam", "fearlessness"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]]},

5: {"s": [],
    0: [["अहिंसा", "ahiṁsā", "non-violence"],
        ["समता", "samatā", "equanimity"],
        ["तुष्टिः", "tuṣṭiḥ", "contentment"]],
    1: [["तपः", "tapaḥ", "austerity"],
        ["दानम्", "dānam", "generosity"],
        ["यशः", "yaśaḥ", "fame"],
        ["अयशः", "ayaśaḥ", "infamy"]],
    2: [["भवन्ति", "bhavanti", "arise"],
        ["भावाः", "bhāvāḥ", "the states"],
        ["भूतानाम्", "bhūtānām", "of beings"]],
    3: [["मत्तः", "mattaḥ", "from me"],
        ["एव", "eva", "alone"],
        ["पृथग्विधाः", "pṛthagvidhāḥ", "of various kinds"]]},

6: {"s": [],
    0: [["महर्षयः", "maharṣayaḥ", "the great seers"],
        ["सप्त", "sapta", "seven"],
        ["पूर्वे", "pūrve", "the ancient"]],
    1: [["चत्वारः", "catvāraḥ", "the four"],
        ["मनवः", "manavaḥ", "Manus"],
        ["तथा", "tathā", "also"]],
    2: [["मद्भावाः", "madbhāvāḥ", "born of my mind"],
        ["मानसाः", "mānasāḥ", "mental"],
        ["जाताः", "jātāḥ", "born"]],
    3: [["येषाम्", "yeṣām", "of whom"],
        ["लोके", "loke", "in the world"],
        ["इमाः", "imāḥ", "these"],
        ["प्रजाः", "prajāḥ", "beings"]]},

7: {"s": [],
    0: [["एताम्", "etām", "this"],
        ["विभूतिम्", "vibhūtim", "glory"],
        ["योगम्", "yogam", "power"],
        ["च", "ca", "and"]],
    1: [["मम", "mama", "my"],
        ["यः", "yaḥ", "who"],
        ["वेत्ति", "vetti", "knows"],
        ["तत्त्वतः", "tattvataḥ", "in truth"]],
    2: [["सः", "saḥ", "he"],
        ["अविकम्पेन", "avikampena", "with unwavering"],
        ["योगेन", "yogena", "yoga"]],
    3: [["युज्यते", "yujyate", "is united"],
        ["न", "na", "not"],
        ["अत्र", "atra", "here"],
        ["संशयः", "saṁśayaḥ", "doubt"]]},

8: {"s": [],
    0: [["अहम्", "aham", "I"],
        ["सर्वस्य", "sarvasya", "of all"],
        ["प्रभवः", "prabhavaḥ", "the source"]],
    1: [["मत्तः", "mattaḥ", "from me"],
        ["सर्वम्", "sarvam", "everything"],
        ["प्रवर्तते", "pravartate", "proceeds"]],
    2: [["इति", "iti", "thus"],
        ["मत्वा", "matvā", "knowing"],
        ["भजन्ते", "bhajante", "worship"],
        ["माम्", "mām", "me"]],
    3: [["बुधाः", "budhāḥ", "the wise"],
        ["भावसमन्विताः", "bhāvasamanvitāḥ", "filled with devotion"]]},

9: {"s": [],
    0: [["मच्चित्ताः", "maccittāḥ", "whose thoughts are on me"],
        ["मद्गतप्राणाः", "madgataprāṇāḥ", "whose lives are given to me"]],
    1: [["बोधयन्तः", "bodhayantaḥ", "enlightening"],
        ["परस्परम्", "parasparam", "one another"]],
    2: [["कथयन्तः", "kathayantaḥ", "speaking of"],
        ["च", "ca", "and"],
        ["माम्", "mām", "me"],
        ["नित्यम्", "nityam", "always"]],
    3: [["तुष्यन्ति", "tuṣyanti", "are content"],
        ["च", "ca", "and"],
        ["रमन्ति", "ramanti", "rejoice"],
        ["च", "ca", "and"]]},

10: {"s": [],
     0: [["तेषाम्", "teṣām", "to them"],
         ["सततयुक्तानाम्", "satatayuktānām", "ever devoted"]],
     1: [["भजताम्", "bhajatām", "worshipping"],
         ["प्रीतिपूर्वकम्", "prītipūrvakam", "with love"]],
     2: [["ददामि", "dadāmi", "I give"],
         ["बुद्धियोगम्", "buddhiyogam", "the yoga of discernment"],
         ["तम्", "tam", "that"]],
     3: [["येन", "yena", "by which"],
         ["माम्", "mām", "me"],
         ["उपयान्ति", "upayānti", "they come to"],
         ["ते", "te", "they"]]},

11: {"s": [],
     0: [["तेषाम्", "teṣām", "of them"],
         ["एव", "eva", "indeed"],
         ["अनुकम्पार्थम्", "anukampārtham", "out of compassion"]],
     1: [["अहम्", "aham", "I"],
         ["अज्ञानजम्", "ajñānajam", "born of ignorance"],
         ["तमः", "tamaḥ", "darkness"]],
     2: [["नाशयामि", "nāśayāmi", "I destroy"],
         ["आत्मभावस्थः", "ātmabhāvasthaḥ", "dwelling in their hearts"]],
     3: [["ज्ञानदीपेन", "jñānadīpena", "with the lamp of knowledge"],
         ["भास्वता", "bhāsvatā", "shining"]]},

12: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["परम्", "param", "supreme"],
         ["ब्रह्म", "brahma", "Brahman"],
         ["परम्", "param", "supreme"],
         ["धाम", "dhāma", "light, abode"]],
     1: [["पवित्रम्", "pavitram", "the purifier"],
         ["परमम्", "paramam", "supreme"],
         ["भवान्", "bhavān", "you are"]],
     2: [["पुरुषम्", "puruṣam", "the Person"],
         ["शाश्वतम्", "śāśvatam", "eternal"],
         ["दिव्यम्", "divyam", "divine"]],
     3: [["आदिदेवम्", "ādidevam", "the primal God"],
         ["अजम्", "ajam", "unborn"],
         ["विभुम्", "vibhum", "all-pervading"]]},

13: {"s": [],
     0: [["आहुः", "āhuḥ", "they call"],
         ["त्वाम्", "tvām", "you"],
         ["ऋषयः", "ṛṣayaḥ", "the seers"],
         ["सर्वे", "sarve", "all"]],
     1: [["देवर्षिः", "devarṣiḥ", "the divine sage"],
         ["नारदः", "nāradaḥ", "Nārada"],
         ["तथा", "tathā", "also"]],
     2: [["असितः", "asitaḥ", "Asita"],
         ["देवलः", "devalaḥ", "Devala"],
         ["व्यासः", "vyāsaḥ", "Vyāsa"]],
     3: [["स्वयम्", "svayam", "yourself"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["ब्रवीषि", "bravīṣi", "you tell"],
         ["मे", "me", "me"]]},

14: {"s": [],
     0: [["सर्वम्", "sarvam", "all"],
         ["एतत्", "etat", "this"],
         ["ऋतम्", "ṛtam", "true"],
         ["मन्ये", "manye", "I hold"]],
     1: [["यत्", "yat", "which"],
         ["माम्", "mām", "to me"],
         ["वदसि", "vadasi", "you say"],
         ["केशव", "keśava", "O Keśava"]],
     2: [["न", "na", "not"],
         ["हि", "hi", "indeed"],
         ["ते", "te", "your"],
         ["भगवन्", "bhagavan", "O Lord"],
         ["व्यक्तिम्", "vyaktim", "manifestation"]],
     3: [["विदुः", "viduḥ", "they know"],
         ["देवाः", "devāḥ", "the gods"],
         ["न", "na", "nor"],
         ["दानवाः", "dānavāḥ", "the demons"]]},

15: {"s": [],
     0: [["स्वयम्", "svayam", "yourself"],
         ["एव", "eva", "indeed"],
         ["आत्मना", "ātmanā", "by yourself"],
         ["आत्मानम्", "ātmānam", "yourself"]],
     1: [["वेत्थ", "vettha", "you know"],
         ["त्वम्", "tvam", "you"],
         ["पुरुषोत्तम", "puruṣottama", "O supreme Person"]],
     2: [["भूतभावन", "bhūtabhāvana", "O source of beings"],
         ["भूतेश", "bhūteśa", "O Lord of beings"]],
     3: [["देवदेव", "devadeva", "O God of gods"],
         ["जगत्पते", "jagatpate", "O Lord of the world"]]},

16: {"s": [],
     0: [["वक्तुम्", "vaktum", "to tell"],
         ["अर्हसि", "arhasi", "you should"],
         ["अशेषेण", "aśeṣeṇa", "without omission"]],
     1: [["दिव्याः", "divyāḥ", "divine"],
         ["हि", "hi", "indeed"],
         ["आत्मविभूतयः", "ātmavibhūtayaḥ", "your own glories"]],
     2: [["याभिः", "yābhiḥ", "by which"],
         ["विभूतिभिः", "vibhūtibhiḥ", "glories"],
         ["लोकान्", "lokān", "the worlds"]],
     3: [["इमान्", "imān", "these"],
         ["त्वम्", "tvam", "you"],
         ["व्याप्य", "vyāpya", "pervading"],
         ["तिष्ठसि", "tiṣṭhasi", "abide"]]},

17: {"s": [],
     0: [["कथम्", "katham", "how"],
         ["विद्याम्", "vidyām", "shall I know"],
         ["अहम्", "aham", "I"],
         ["योगिन्", "yogin", "O yogi"]],
     1: [["त्वाम्", "tvām", "you"],
         ["सदा", "sadā", "always"],
         ["परिचिन्तयन्", "paricintayan", "contemplating"]],
     2: [["केषु", "keṣu", "in which"],
         ["केषु", "keṣu", "in which"],
         ["च", "ca", "and"],
         ["भावेषु", "bhāveṣu", "states"]],
     3: [["चिन्त्यः", "cintyaḥ", "to be thought of"],
         ["असि", "asi", "you are"],
         ["भगवन्", "bhagavan", "O Lord"],
         ["मया", "mayā", "by me"]]},

18: {"s": [],
     0: [["विस्तरेण", "vistareṇa", "in detail"],
         ["आत्मनः", "ātmanaḥ", "of yourself"],
         ["योगम्", "yogam", "the yoga"]],
     1: [["विभूतिम्", "vibhūtim", "the glory"],
         ["च", "ca", "and"],
         ["जनार्दन", "janārdana", "O Janārdana"]],
     2: [["भूयः", "bhūyaḥ", "again"],
         ["कथय", "kathaya", "tell"],
         ["तृप्तिः", "tṛptiḥ", "satisfaction"],
         ["हि", "hi", "indeed"]],
     3: [["शृण्वतः", "śṛṇvataḥ", "of one hearing"],
         ["न", "na", "not"],
         ["अस्ति", "asti", "there is"],
         ["मे", "me", "my"],
         ["अमृतम्", "amṛtam", "nectar"]]},

19: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
     0: [["हन्त", "hanta", "behold, yes"],
         ["ते", "te", "to you"],
         ["कथयिष्यामि", "kathayiṣyāmi", "I shall declare"]],
     1: [["दिव्याः", "divyāḥ", "divine"],
         ["हि", "hi", "indeed"],
         ["आत्मविभूतयः", "ātmavibhūtayaḥ", "my own glories"]],
     2: [["प्राधान्यतः", "prādhānyataḥ", "chiefly"],
         ["कुरुश्रेष्ठ", "kuruśreṣṭha", "O best of the Kurus"]],
     3: [["न", "na", "not"],
         ["अस्ति", "asti", "there is"],
         ["अन्तः", "antaḥ", "end"],
         ["विस्तरस्य", "vistarasya", "of the extent"],
         ["मे", "me", "my"]]},

20: {"s": [],
     0: [["अहम्", "aham", "I"],
         ["आत्मा", "ātmā", "the Self"],
         ["गुडाकेश", "guḍākeśa", "O Guḍākeśa"]],
     1: [["सर्वभूताशयस्थितः", "sarvabhūtāśayasthitaḥ", "dwelling in the hearts of all beings"]],
     2: [["अहम्", "aham", "I"],
         ["आदिः", "ādiḥ", "the beginning"],
         ["च", "ca", "and"],
         ["मध्यम्", "madhyam", "the middle"],
         ["च", "ca", "and"]],
     3: [["भूतानाम्", "bhūtānām", "of beings"],
         ["अन्तः", "antaḥ", "the end"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]]},

21: {"s": [],
     0: [["आदित्यानाम्", "ādityānām", "among the Ādityas"],
         ["अहम्", "aham", "I"],
         ["विष्णुः", "viṣṇuḥ", "Viṣṇu"]],
     1: [["ज्योतिषाम्", "jyotiṣām", "among the lights"],
         ["रविः", "raviḥ", "the sun"],
         ["अंशुमान्", "aṁśumān", "radiant"]],
     2: [["मरीचिः", "marīciḥ", "Marīci"],
         ["मरुताम्", "marutām", "among the winds"],
         ["अस्मि", "asmi", "I am"]],
     3: [["नक्षत्राणाम्", "nakṣatrāṇām", "among the stars"],
         ["अहम्", "aham", "I"],
         ["शशी", "śaśī", "the moon"]]},

22: {"s": [],
     0: [["वेदानाम्", "vedānām", "among the Vedas"],
         ["सामवेदः", "sāmavedaḥ", "the Sāma-veda"],
         ["अस्मि", "asmi", "I am"]],
     1: [["देवानाम्", "devānām", "among the gods"],
         ["अस्मि", "asmi", "I am"],
         ["वासवः", "vāsavaḥ", "Indra"]],
     2: [["इन्द्रियाणाम्", "indriyāṇām", "among the senses"],
         ["मनः", "manaḥ", "the mind"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"]],
     3: [["भूतानाम्", "bhūtānām", "among beings"],
         ["अस्मि", "asmi", "I am"],
         ["चेतना", "cetanā", "consciousness"]]},

23: {"s": [],
     0: [["रुद्राणाम्", "rudrāṇām", "among the Rudras"],
         ["शङ्करः", "śaṅkaraḥ", "Śaṅkara"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"]],
     1: [["वित्तेशः", "vitteśaḥ", "the lord of wealth"],
         ["यक्षरक्षसाम्", "yakṣarakṣasām", "of the yakṣas and rākṣasas"]],
     2: [["वसूनाम्", "vasūnām", "among the Vasus"],
         ["पावकः", "pāvakaḥ", "fire"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"]],
     3: [["मेरुः", "meruḥ", "Meru"],
         ["शिखरिणाम्", "śikhariṇām", "among mountains"],
         ["अहम्", "aham", "I"]]},

24: {"s": [],
     0: [["पुरोधसाम्", "purodhasām", "among priests"],
         ["च", "ca", "and"],
         ["मुख्यम्", "mukhyam", "the chief"],
         ["माम्", "mām", "me"]],
     1: [["विद्धि", "viddhi", "know"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["बृहस्पतिम्", "bṛhaspatim", "Bṛhaspati"]],
     2: [["सेनानीनाम्", "senānīnām", "among generals"],
         ["अहम्", "aham", "I"],
         ["स्कन्दः", "skandaḥ", "Skanda"]],
     3: [["सरसाम्", "sarasām", "among waters"],
         ["अस्मि", "asmi", "I am"],
         ["सागरः", "sāgaraḥ", "the ocean"]]},

25: {"s": [],
     0: [["महर्षीणाम्", "maharṣīṇām", "among the great seers"],
         ["भृगुः", "bhṛguḥ", "Bhṛgu"],
         ["अहम्", "aham", "I"]],
     1: [["गिराम्", "girām", "among words"],
         ["अस्मि", "asmi", "I am"],
         ["एकम्", "ekam", "the one"],
         ["अक्षरम्", "akṣaram", "syllable (Om)"]],
     2: [["यज्ञानाम्", "yajñānām", "among sacrifices"],
         ["जपयज्ञः", "japayajñaḥ", "the japa-sacrifice"],
         ["अस्मि", "asmi", "I am"]],
     3: [["स्थावराणाम्", "sthāvarāṇām", "among the immovable"],
         ["हिमालयः", "himālayaḥ", "the Himālaya"]]},

26: {"s": [],
     0: [["अश्वत्थः", "aśvatthaḥ", "the sacred fig"],
         ["सर्ववृक्षाणाम्", "sarvavṛkṣāṇām", "among all trees"]],
     1: [["देवर्षीणाम्", "devarṣīṇām", "among the divine sages"],
         ["च", "ca", "and"],
         ["नारदः", "nāradaḥ", "Nārada"]],
     2: [["गन्धर्वाणाम्", "gandharvāṇām", "among the gandharvas"],
         ["चित्ररथः", "citrarathaḥ", "Citraratha"]],
     3: [["सिद्धानाम्", "siddhānām", "among the perfected"],
         ["कपिलः", "kapilaḥ", "Kapila"],
         ["मुनिः", "muniḥ", "the sage"]]},

27: {"s": [],
     0: [["उच्चैःश्रवसम्", "uccaiḥśravasam", "Uccaiḥśravas"],
         ["अश्वानाम्", "aśvānām", "among horses"]],
     1: [["विद्धि", "viddhi", "know"],
         ["माम्", "mām", "me"],
         ["अमृतोद्भवम्", "amṛtodbhavam", "born of nectar"]],
     2: [["ऐरावतम्", "airāvatam", "Airāvata"],
         ["गजेन्द्राणाम्", "gajendrāṇām", "among lordly elephants"]],
     3: [["नराणाम्", "narāṇām", "among men"],
         ["च", "ca", "and"],
         ["नराधिपम्", "narādhipam", "the king"]]},

28: {"s": [],
     0: [["आयुधानाम्", "āyudhānām", "among weapons"],
         ["अहम्", "aham", "I"],
         ["वज्रम्", "vajram", "the thunderbolt"]],
     1: [["धेनूनाम्", "dhenūnām", "among cows"],
         ["अस्मि", "asmi", "I am"],
         ["कामधुक्", "kāmadhuk", "the wish-cow"]],
     2: [["प्रजनः", "prajanaḥ", "the procreator"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"],
         ["कन्दर्पः", "kandarpaḥ", "Kāma"]],
     3: [["सर्पाणाम्", "sarpāṇām", "among serpents"],
         ["अस्मि", "asmi", "I am"],
         ["वासुकिः", "vāsukiḥ", "Vāsuki"]]},

29: {"s": [],
     0: [["अनन्तः", "anantaḥ", "the infinite"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"],
         ["नागानाम्", "nāgānām", "among serpents"]],
     1: [["वरुणः", "varuṇaḥ", "Varuṇa"],
         ["यादसाम्", "yādasām", "among the waters"],
         ["अहम्", "aham", "I"]],
     2: [["पितॄणाम्", "pitṝṇām", "among the ancestors"],
         ["अर्यमा", "aryamā", "Aryaman"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"]],
     3: [["यमः", "yamaḥ", "Yama"],
         ["संयमताम्", "saṁyamatām", "among the punishers"],
         ["अहम्", "aham", "I"]]},

30: {"s": [],
     0: [["प्रह्लादः", "prahlādaḥ", "Prahlāda"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"],
         ["दैत्यानाम्", "daityānām", "among the demons"]],
     1: [["कालः", "kālaḥ", "time"],
         ["कलयताम्", "kalayatām", "among the calculators"],
         ["अहम्", "aham", "I"]],
     2: [["मृगाणाम्", "mṛgāṇām", "among beasts"],
         ["च", "ca", "and"],
         ["मृगेन्द्रः", "mṛgendraḥ", "the lion"],
         ["अहम्", "aham", "I"]],
     3: [["वैनतेयः", "vainateyaḥ", "Garuḍa"],
         ["च", "ca", "and"],
         ["पक्षिणाम्", "pakṣiṇām", "among birds"]]},

31: {"s": [],
     0: [["पवनः", "pavanaḥ", "the wind"],
         ["पवताम्", "pavatām", "among purifiers"],
         ["अस्मि", "asmi", "I am"]],
     1: [["रामः", "rāmaḥ", "Rāma"],
         ["शस्त्रभृताम्", "śastrabhṛtām", "among weapon-bearers"],
         ["अहम्", "aham", "I"]],
     2: [["झषाणाम्", "jhaṣāṇām", "among fishes"],
         ["मकरः", "makaraḥ", "the makara"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"]],
     3: [["स्रोतसाम्", "srotasām", "among streams"],
         ["अस्मि", "asmi", "I am"],
         ["जाह्नवी", "jāhnavī", "the Ganges"]]},

32: {"s": [],
     0: [["सर्गाणाम्", "sargāṇām", "of creations"],
         ["आदिः", "ādiḥ", "the beginning"],
         ["अन्तः", "antaḥ", "the end"],
         ["च", "ca", "and"]],
     1: [["मध्यम्", "madhyam", "the middle"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["अहम्", "aham", "I"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["अध्यात्मविद्या", "adhyātmavidyā", "the science of the Self"],
         ["विद्यानाम्", "vidyānām", "among the sciences"]],
     3: [["वादः", "vādaḥ", "the argument"],
         ["प्रवदताम्", "pravadatām", "among debaters"],
         ["अहम्", "aham", "I"]]},

33: {"s": [],
     0: [["अक्षराणाम्", "akṣarāṇām", "among letters"],
         ["अकारः", "akāraḥ", "the letter A"],
         ["अस्मि", "asmi", "I am"]],
     1: [["द्वन्द्वः", "dvandvaḥ", "the dvandva (compound)"],
         ["सामासिकस्य", "sāmāsikasya", "of the compound"],
         ["च", "ca", "and"]],
     2: [["अहम्", "aham", "I"],
         ["एव", "eva", "indeed"],
         ["अक्षयः", "akṣayaḥ", "inexhaustible"],
         ["कालः", "kālaḥ", "time"]],
     3: [["धाता", "dhātā", "the ordainer"],
         ["अहम्", "aham", "I"],
         ["विश्वतोमुखः", "viśvatomukhaḥ", "facing everywhere"]]},

34: {"s": [],
     0: [["मृत्युः", "mṛtyuḥ", "death"],
         ["सर्वहरः", "sarvaharaḥ", "all-devouring"],
         ["च", "ca", "and"],
         ["अहम्", "aham", "I"]],
     1: [["उद्भवः", "udbhavaḥ", "the source"],
         ["च", "ca", "and"],
         ["भविष्यताम्", "bhaviṣyatām", "of all that will be"]],
     2: [["कीर्तिः", "kīrtiḥ", "fame"],
         ["श्रीः", "śrīḥ", "fortune"],
         ["वाक्", "vāk", "speech"],
         ["च", "ca", "and"],
         ["नारीणाम्", "nārīṇām", "of women"]],
     3: [["स्मृतिः", "smṛtiḥ", "memory"],
         ["मेधा", "medhā", "wisdom"],
         ["धृतिः", "dhṛtiḥ", "constancy"],
         ["क्षमा", "kṣamā", "forbearance"]]},

35: {"s": [],
     0: [["बृहत्साम", "bṛhatsāma", "the Bṛhat-sāma"],
         ["तथा", "tathā", "also"],
         ["साम्नाम्", "sāmnām", "among the Sāma-chants"]],
     1: [["गायत्री", "gāyatrī", "the Gāyatrī"],
         ["छन्दसाम्", "chandasām", "among metres"],
         ["अहम्", "aham", "I"]],
     2: [["मासानाम्", "māsānām", "among months"],
         ["मार्गशीर्षः", "mārgaśīrṣaḥ", "Mārgaśīrṣa"],
         ["अहम्", "aham", "I"]],
     3: [["ऋतूनाम्", "ṛtūnām", "among seasons"],
         ["कुसुमाकरः", "kusumākaraḥ", "the spring"]]},

36: {"s": [],
     0: [["द्यूतम्", "dyūtam", "the dice"],
         ["छलयताम्", "chalayatām", "among the crafty"],
         ["अस्मि", "asmi", "I am"]],
     1: [["तेजः", "tejaḥ", "the splendour"],
         ["तेजस्विनाम्", "tejasvinām", "of the splendid"],
         ["अहम्", "aham", "I"]],
     2: [["जयः", "jayaḥ", "victory"],
         ["अस्मि", "asmi", "I am"],
         ["व्यवसायः", "vyavasāyaḥ", "determination"],
         ["अस्मि", "asmi", "I am"]],
     3: [["सत्त्वम्", "sattvam", "the goodness"],
         ["सत्त्ववताम्", "sattvavatām", "of the good"],
         ["अहम्", "aham", "I"]]},

37: {"s": [],
     0: [["वृष्णीनाम्", "vṛṣṇīnām", "among the Vṛṣṇis"],
         ["वासुदेवः", "vāsudevaḥ", "Vāsudeva"],
         ["अस्मि", "asmi", "I am"]],
     1: [["पाण्डवानाम्", "pāṇḍavānām", "among the Pāṇḍavas"],
         ["धनञ्जयः", "dhanañjayaḥ", "Arjuna"]],
     2: [["मुनीनाम्", "munīnām", "among the sages"],
         ["अपि", "api", "also"],
         ["अहम्", "aham", "I"],
         ["व्यासः", "vyāsaḥ", "Vyāsa"]],
     3: [["कवीनाम्", "kavīnām", "among the poets"],
         ["उशना", "uśanā", "Uśanas"],
         ["कविः", "kaviḥ", "the poet"]]},

38: {"s": [],
     0: [["दण्डः", "daṇḍaḥ", "the rod"],
         ["दमयताम्", "damayatām", "among the punishers"],
         ["अस्मि", "asmi", "I am"]],
     1: [["नीतिः", "nītiḥ", "statesmanship"],
         ["अस्मि", "asmi", "I am"],
         ["जिगीषताम्", "jigīṣatām", "of those seeking victory"]],
     2: [["मौनम्", "maunam", "silence"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["अस्मि", "asmi", "I am"],
         ["गुह्यानाम्", "guhyānām", "of the secret"]],
     3: [["ज्ञानम्", "jñānam", "knowledge"],
         ["ज्ञानवताम्", "jñānavatām", "of the wise"],
         ["अहम्", "aham", "I"]]},

39: {"s": [],
     0: [["यत्", "yat", "which"],
         ["च", "ca", "and"],
         ["अपि", "api", "indeed"],
         ["सर्वभूतानाम्", "sarvabhūtānām", "of all beings"]],
     1: [["बीजम्", "bījam", "the seed"],
         ["तत्", "tat", "that"],
         ["अहम्", "aham", "I"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["न", "na", "not"],
         ["तत्", "tat", "that"],
         ["अस्ति", "asti", "exists"],
         ["विना", "vinā", "without"],
         ["यत्", "yat", "which"]],
     3: [["स्यात्", "syāt", "might be"],
         ["मया", "mayā", "by me"],
         ["भूतम्", "bhūtam", "being"],
         ["चराचरम्", "carācaram", "moving or unmoving"]]},

40: {"s": [],
     0: [["न", "na", "not"],
         ["अन्तः", "antaḥ", "end"],
         ["अस्ति", "asti", "there is"],
         ["मम", "mama", "my"],
         ["दिव्यानाम्", "divyānām", "of the divine"]],
     1: [["विभूतीनाम्", "vibhūtīnām", "glories"],
         ["परन्तप", "parantapa", "O scorcher of foes"]],
     2: [["एषः", "eṣaḥ", "this"],
         ["तु", "tu", "but"],
         ["उद्देशतः", "uddeśataḥ", "as a summary"],
         ["प्रोक्तः", "proktaḥ", "declared"]],
     3: [["विभूतेः", "vibhūteḥ", "of the glory"],
         ["विस्तरः", "vistaraḥ", "the extent"],
         ["मया", "mayā", "by me"]]},

41: {"s": [],
     0: [["यत्", "yat", "whatever"],
         ["यत्", "yat", "whatever"],
         ["विभूतिमत्", "vibhūtimat", "glorious"],
         ["सत्त्वम्", "sattvam", "being"]],
     1: [["श्रीमत्", "śrīmat", "radiant"],
         ["ऊर्जितम्", "ūrjitam", "mighty"],
         ["एव", "eva", "indeed"],
         ["वा", "vā", "or"]],
     2: [["तत्", "tat", "that"],
         ["तत्", "tat", "that"],
         ["एव", "eva", "indeed"],
         ["अवगच्छ", "avagaccha", "know"],
         ["त्वम्", "tvam", "you"]],
     3: [["मम", "mama", "my"],
         ["तेजोंशसम्भवम्", "tejoṁśasambhavam", "born of a portion of my splendour"]]},

42: {"s": [],
     0: [["अथवा", "athavā", "or"],
         ["बहुना", "bahunā", "with much"],
         ["एतेन", "etena", "this"]],
     1: [["किम्", "kim", "what"],
         ["ज्ञातेन", "jñātena", "known"],
         ["तव", "tava", "for you"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["विष्टभ्य", "viṣṭabhya", "having supported"],
         ["अहम्", "aham", "I"],
         ["इदम्", "idam", "this"],
         ["कृत्स्नम्", "kṛtsnam", "whole"]],
     3: [["एकांशेन", "ekāṁśena", "with one part"],
         ["स्थितः", "sthitaḥ", "standing"],
         ["जगत्", "jagat", "world"]]},
}
