# -*- coding: utf-8 -*-
"""padachheda_ch4.py — per-pāda pada-chheda (word splits) for all 42 verses of Gita Chapter 4.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH4_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
          ["उवाच", "uvāca", "said"]],
    0: [["इमम्", "imam", "this"],
        ["विवस्वते", "vivasvate", "to Vivasvān (the sun-god)"],
        ["योगम्", "yogam", "yoga"]],
    1: [["प्रोक्तवान्", "proktavān", "declared, taught"],
        ["अहम्", "aham", "I"],
        ["अव्ययम्", "avyayam", "imperishable"]],
    2: [["विवस्वान्", "vivasvān", "Vivasvān"],
        ["मनवे", "manave", "to Manu"],
        ["प्राह", "prāha", "told, communicated"]],
    3: [["मनुः", "manuḥ", "Manu"],
        ["इक्ष्वाकवे", "ikṣvākave", "to Ikṣvāku"],
        ["अब्रवीत्", "abravīt", "proclaimed"]]},

2: {"s": [],
    0: [["एवम्", "evam", "thus"],
        ["परम्परा", "paramparā", "in succession, by tradition"],
        ["प्राप्तम्", "prāptam", "received"]],
    1: [["इमम्", "imam", "this"],
        ["राजर्षयः", "rājarṣayaḥ", "the royal sages"],
        ["विदुः", "viduḥ", "knew"]],
    2: [["सः", "saḥ", "that"],
        ["कालेन", "kālena", "in the course of time"],
        ["इह", "iha", "here, in this world"],
        ["महता", "mahatā", "long"]],
    3: [["योगः", "yogaḥ", "yoga"],
        ["नष्टः", "naṣṭaḥ", "lost"],
        ["परन्तप", "parantapa", "O scorcher of foes"]]},

3: {"s": [],
    0: [
    ["सः", "saḥ", "that"], ["एव", "eva", "very, same"], ["अयम्", "ayam", "this"],
        ["मया", "mayā", "by me"], ["ते", "te", "to you"], ["अद्य", "adya", "now"]],
    1: [
    ["योगः", "yogaḥ", "yoga"], ["प्रोक्तः", "proktaḥ", "declared"],
        ["पुरातनः", "purātanaḥ", "ancient"]],
    2: [
    ["भक्तः", "bhaktaḥ", "devotee"], ["असि", "asi", "you are"], ["मे", "me", "my"],
        ["सखा", "sakhā", "friend"], ["च", "ca", "and"], ["इति", "iti", "because, thus"]],
    3: [
    ["रहस्यम्", "rahasyam", "secret"], ["हि", "hi", "indeed"], ["एतत्", "etat", "this"],
        ["उत्तमम्", "uttamam", "supreme"]]
},
4: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"],
          ["उवाच", "uvāca", "said"]],
    0: [["अपरम्", "aparam", "later"],
        ["भवतः", "bhavataḥ", "your"],
        ["जन्म", "janma", "birth"]],
    1: [["परम्", "param", "earlier"],
        ["जन्म", "janma", "birth"],
        ["विवस्वतः", "vivasvataḥ", "of Vivasvān"]],
    2: [["कथम्", "katham", "how"],
        ["एतत्", "etat", "this"],
        ["विजानीयाम्", "vijānīyām", "am I to understand"]],
    3: [["त्वम्", "tvam", "you"],
        ["आदौ", "ādau", "in the beginning"],
        ["प्रोक्तवान्", "proktavān", "taught"],
        ["इति", "iti", "that"]]},

5: {"s": [
    ["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
    ["उवाच", "uvāca", "said"]
],
    0: [
    ["बहूनि", "bahūni", "many"], ["मे", "me", "my"],
        ["व्यतीतानि", "vyatītāni", "passed, gone by"]],
    1: [
    ["जन्मानि", "janmāni", "births"], ["तव", "tava", "your"], ["च", "ca", "and"],
        ["अर्जुन", "arjuna", "O Arjuna"]],
    2: [
    ["तानि", "tāni", "them"], ["अहम्", "aham", "I"], ["वेद", "veda", "know"],
        ["सर्वाणि", "sarvāṇi", "all"]],
    3: [
    ["न", "na", "not"], ["त्वम्", "tvam", "you"], ["वेत्थ", "vettha", "know"],
        ["परन्तप", "parantapa", "O scorcher of foes"]]
},
6: {"s": [],
    0: [["अजः", "ajaḥ", "unborn"],
        ["अपि", "api", "though"],
        ["सन्", "san", "being"],
        ["अव्ययात्मा", "avyayātmā", "of imperishable Self"]],
    1: [["भूतानाम्", "bhūtānām", "of beings"],
        ["ईश्वरः", "īśvaraḥ", "the Lord"],
        ["अपि", "api", "though"],
        ["सन्", "san", "being"]],
    2: [["प्रकृतिम्", "prakṛtim", "prakṛti, nature"],
        ["स्वाम्", "svām", "my own"],
        ["अधिष्ठाय", "adhiṣṭhāya", "resorting to"]],
    3: [["सम्भवामि", "sambhavāmi", "I come into being"],
        ["आत्म", "ātma", "my own"],
        ["मायया", "māyayā", "by māyā (divine power)"]]},

7: {"s": [],
    0: [
    ["यदा", "yadā", "whenever"], ["यदा", "yadā", "whenever"], ["हि", "hi", "indeed"],
        ["धर्मस्य", "dharmasya", "of dharma"]],
    1: [
    ["ग्लानिः", "glāniḥ", "decline"], ["भवति", "bhavati", "occurs"],
        ["भारत", "bhārata", "O Bhārata"]],
    2: [
    ["अभ्युत्थानम्", "abhyutthānam", "the rise"], ["अधर्मस्य", "adharmasya", "of adharma"]],
    3: [
    ["तदा", "tadā", "then"], ["आत्मानम्", "ātmānam", "myself"],
        ["सृजामि", "sṛjāmi", "I create, manifest"], ["अहम्", "aham", "I"]]
},
8: {"s": [],
    0: [["परित्राणाय", "paritrāṇāya", "for the protection"],
        ["साधूनाम्", "sādhūnām", "of the good"]],
    1: [["विनाशाय", "vināśāya", "for the destruction"],
        ["च", "ca", "and"],
        ["दुष्कृताम्", "duṣkṛtām", "of the evil-doers"]],
    2: [["धर्म", "dharma", "of dharma"],
        ["संस्थापन", "saṁsthāpana", "the establishment"],
        ["अर्थाय", "arthāya", "for the purpose"]],
    3: [["सम्भवामि", "sambhavāmi", "I am born"],
        ["युगे", "yuge", "in age"],
        ["युगे", "yuge", "after age"]]},

9: {"s": [],
    0: [["जन्म", "janma", "birth"],
        ["कर्म", "karma", "action"],
        ["च", "ca", "and"],
        ["मे", "me", "my"],
        ["दिव्यम्", "divyam", "divine"]],
    1: [["एवम्", "evam", "thus"],
        ["यः", "yaḥ", "who"],
        ["वेत्ति", "vetti", "knows"],
        ["तत्त्वतः", "tattvataḥ", "in truth"]],
    2: [["त्यक्त्वा", "tyaktvā", "having abandoned"],
        ["देहम्", "deham", "the body"],
        ["पुनः", "punaḥ", "again"],
        ["जन्म", "janma", "birth"]],
    3: [["न", "na", "not"],
        ["एति", "eti", "goes"],
        ["माम्", "mām", "to me"],
        ["एति", "eti", "goes"],
        ["सः", "saḥ", "he"],
        ["अर्जुन", "arjuna", "O Arjuna"]]},

10: {"s": [],
     0: [["वीत", "vīta", "free from"],
         ["राग", "rāga", "attachment"],
         ["भय", "bhaya", "fear"],
         ["क्रोधाः", "krodhāḥ", "anger"]],
     1: [["मन्मयाः", "manmayāḥ", "absorbed in me"],
         ["माम्", "mām", "in me"],
         ["उपाश्रिताः", "upāśritāḥ", "taking refuge"]],
     2: [["बहवः", "bahavaḥ", "many"],
         ["ज्ञान", "jñāna", "of knowledge"],
         ["तपसा", "tapasā", "by austerity"]],
     3: [["पूताः", "pūtāḥ", "purified"],
         ["मद्भावम्", "madbhāvam", "my state, my being"],
         ["आगताः", "āgatāḥ", "have reached"]]},

11: {"s": [],
     0: [["ये", "ye", "who"],
         ["यथा", "yathā", "in whatever way"],
         ["माम्", "mām", "me"],
         ["प्रपद्यन्ते", "prapadyante", "approach"]],
     1: [["तान्", "tān", "them"],
         ["तथा", "tathā", "in that way"],
         ["एव", "eva", "indeed"],
         ["भजामि", "bhajāmi", "I favour, I receive"],
         ["अहम्", "aham", "I"]],
     2: [["मम", "mama", "my"],
         ["वर्त्म", "vartma", "path"],
         ["अनुवर्तन्ते", "anuvartante", "follow"]],
     3: [["मनुष्याः", "manuṣyāḥ", "people, men"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सर्वशः", "sarvaśaḥ", "in every way"]]},

12: {"s": [],
     0: [["काङ्क्षन्तः", "kāṅkṣantaḥ", "desiring"],
         ["कर्मणाम्", "karmaṇām", "of actions"],
         ["सिद्धिम्", "siddhim", "success"]],
     1: [["यजन्ते", "yajante", "they worship"],
         ["इह", "iha", "here"],
         ["देवताः", "devatāḥ", "the gods"]],
     2: [["क्षिप्रम्", "kṣipram", "quickly"],
         ["हि", "hi", "indeed"],
         ["मानुषे", "mānuṣe", "in the human"],
         ["लोके", "loke", "world"]],
     3: [["सिद्धिः", "siddhiḥ", "success"],
         ["भवति", "bhavati", "comes to be"],
         ["कर्मजा", "karmajā", "born of action"]]},

13: {"s": [],
     0: [["चातुर्वर्ण्यम्", "cāturvarṇyam", "the fourfold order"],
         ["मया", "mayā", "by me"],
         ["सृष्टम्", "sṛṣṭam", "created"]],
     1: [["गुण", "guṇa", "of qualities"],
         ["कर्म", "karma", "and actions"],
         ["विभागशः", "vibhāgaśaḥ", "according to the division"]],
     2: [["तस्य", "tasya", "of it"],
         ["कर्तारम्", "kartāram", "the author, doer"],
         ["अपि", "api", "even"],
         ["माम्", "mām", "me"]],
     3: [["विद्धि", "viddhi", "know"],
         ["अकर्तारम्", "akartāram", "as the non-doer"],
         ["अव्ययम्", "avyayam", "imperishable"]]},

14: {"s": [],
     0: [["न", "na", "not"],
         ["माम्", "mām", "me"],
         ["कर्माणि", "karmāṇi", "actions"],
         ["लिम्पन्ति", "limpanti", "cling to, stain"]],
     1: [["न", "na", "nor"],
         ["मे", "me", "my"],
         ["कर्मफले", "karmaphale", "in the fruit of action"],
         ["स्पृहा", "spṛhā", "longing"]],
     2: [["इति", "iti", "thus"],
         ["माम्", "mām", "me"],
         ["यः", "yaḥ", "who"],
         ["अभिजानाति", "abhijānāti", "knows"]],
     3: [["कर्मभिः", "karmabhiḥ", "by actions"],
         ["न", "na", "not"],
         ["सः", "saḥ", "he"],
         ["बध्यते", "badhyate", "is bound"]]},

15: {"s": [],
     0: [["एवम्", "evam", "thus"],
         ["ज्ञात्वा", "jñātvā", "having known"],
         ["कृतम्", "kṛtam", "performed"],
         ["कर्म", "karma", "action"]],
     1: [["पूर्वैः", "pūrvaiḥ", "by the ancients"],
         ["अपि", "api", "even"],
         ["मुमुक्षुभिः", "mumukṣubhiḥ", "by seekers of liberation"]],
     2: [["कुरु", "kuru", "perform"],
         ["कर्म", "karma", "action"],
         ["एव", "eva", "indeed"],
         ["तस्मात्", "tasmāt", "therefore"],
         ["त्वम्", "tvam", "you"]],
     3: [["पूर्वैः", "pūrvaiḥ", "by the ancients"],
         ["पूर्वतरम्", "pūrvataram", "in earlier times"],
         ["कृतम्", "kṛtam", "performed"]]},

16: {"s": [],
     0: [["किम्", "kim", "what"],
         ["कर्म", "karma", "action"],
         ["किम्", "kim", "what"],
         ["अकर्म", "akarma", "inaction"],
         ["इति", "iti", "this"]],
     1: [["कवयः", "kavayaḥ", "the wise"],
         ["अपि", "api", "even"],
         ["अत्र", "atra", "here"],
         ["मोहिताः", "mohitāḥ", "bewildered"]],
     2: [["तत्", "tat", "that"],
         ["ते", "te", "to you"],
         ["कर्म", "karma", "action"],
         ["प्रवक्ष्यामि", "pravakṣyāmi", "I shall declare"]],
     3: [["यत्", "yat", "which"],
         ["ज्ञात्वा", "jñātvā", "knowing"],
         ["मोक्ष्यसे", "mokṣyase", "you will be freed"],
         ["अशुभात्", "aśubhāt", "from evil"]]},

17: {"s": [],
     0: [["कर्मणः", "karmaṇaḥ", "of action"],
         ["हि", "hi", "indeed"],
         ["अपि", "api", "also"],
         ["बोद्धव्यम्", "boddhavyam", "must be understood"]],
     1: [["बोद्धव्यम्", "boddhavyam", "must be understood"],
         ["च", "ca", "and"],
         ["विकर्मणः", "vikarmaṇaḥ", "of forbidden action"]],
     2: [["अकर्मणः", "akarmaṇaḥ", "of inaction"],
         ["च", "ca", "and"],
         ["बोद्धव्यम्", "boddhavyam", "must be understood"]],
     3: [["गहना", "gahanā", "mysterious, deep"],
         ["कर्मणः", "karmaṇaḥ", "of action"],
         ["गतिः", "gatiḥ", "the way"]]},

18: {"s": [],
     0: [["कर्मणि", "karmaṇi", "in action"],
         ["अकर्म", "akarma", "inaction"],
         ["यः", "yaḥ", "who"],
         ["पश्येत्", "paśyet", "sees"]],
     1: [["अकर्मणि", "akarmaṇi", "in inaction"],
         ["च", "ca", "and"],
         ["कर्म", "karma", "action"],
         ["यः", "yaḥ", "who"]],
     2: [["सः", "saḥ", "he"],
         ["बुद्धिमान्", "buddhimān", "wise, intelligent"],
         ["मनुष्येषु", "manuṣyeṣu", "among men"]],
     3: [["सः", "saḥ", "he"],
         ["युक्तः", "yuktaḥ", "engaged (in yoga)"],
         ["कृत्स्नकर्मकृत्", "kṛtsnakarmakṛt", "performer of all actions"]]},

19: {"s": [],
     0: [["यस्य", "yasya", "whose"],
         ["सर्वे", "sarve", "all"],
         ["समारम्भाः", "samārambhāḥ", "undertakings"]],
     1: [["काम", "kāma", "of desire"],
         ["सङ्कल्प", "saṅkalpa", "selfish resolve"],
         ["वर्जिताः", "varjitāḥ", "free from"]],
     2: [["ज्ञान", "jñāna", "of knowledge"],
         ["अग्नि", "agni", "by the fire"],
         ["दग्ध", "dagdha", "burnt"],
         ["कर्माणम्", "karmāṇam", "whose actions"]],
     3: [["तम्", "tam", "him"],
         ["आहुः", "āhuḥ", "they call"],
         ["पण्डितम्", "paṇḍitam", "a wise man, learned"],
         ["बुधाः", "budhāḥ", "the learned"]]},

20: {"s": [],
     0: [["त्यक्त्वा", "tyaktvā", "having abandoned"],
         ["कर्मफल", "karmaphala", "of the fruit of action"],
         ["आसङ्गम्", "āsaṅgam", "the attachment"]],
     1: [["नित्यतृप्तः", "nityatṛptaḥ", "ever content"],
         ["निराश्रयः", "nirāśrayaḥ", "without support, dependent on nothing"]],
     2: [["कर्मणि", "karmaṇi", "in action"],
         ["अभिप्रवृत्तः", "abhipravṛttaḥ", "engaged"],
         ["अपि", "api", "though"]],
     3: [["न", "na", "not"],
         ["एव", "eva", "indeed"],
         ["किञ्चित्", "kiñcit", "anything"],
         ["करोति", "karoti", "does"],
         ["सः", "saḥ", "he"]]},

21: {"s": [],
     0: [["निराशीः", "nirāśīḥ", "free from desire"],
         ["यत", "yata", "controlled"],
         ["चित्तात्मा", "cittātmā", "mind and self"]],
     1: [["त्यक्त", "tyakta", "having renounced"],
         ["सर्व", "sarva", "all"],
         ["परिग्रहः", "parigrahaḥ", "possessions"]],
     2: [["शारीरम्", "śārīram", "bodily, of the body"],
         ["केवलम्", "kevalam", "only"],
         ["कर्म", "karma", "action"]],
     3: [["कुर्वन्", "kurvan", "performing"],
         ["आप्नोति", "āpnoti", "incurs, meets"],
         ["किल्बिषम्", "kilbiṣam", "sin"]]},

22: {"s": [],
     0: [["यदृच्छा", "yadṛcchā", "by chance, unsought"],
         ["लाभ", "lābha", "gain"],
         ["सन्तुष्टः", "santuṣṭaḥ", "content"]],
     1: [["द्वन्द्व", "dvandva", "the pairs of opposites"],
         ["अतीतः", "atītaḥ", "beyond"],
         ["विमत्सरः", "vimatsaraḥ", "free from envy"]],
     2: [["समः", "samaḥ", "equal"],
         ["सिद्धौ", "siddhau", "in success"],
         ["असिद्धौ", "asiddhau", "in failure"],
         ["च", "ca", "and"]],
     3: [["कृत्वा", "kṛtvā", "having done"],
         ["अपि", "api", "even"],
         ["न", "na", "not"],
         ["निबध्यते", "nibadhyate", "is bound"]]},

23: {"s": [],
    0: [
    ["गत", "gata", "gone, freed from"], ["सङ्गस्य", "saṅgasya", "of attachment"],
        ["मुक्तस्य", "muktasya", "of the liberated"]],
    1: [
    ["ज्ञान", "jñāna", "in knowledge"], ["अवस्थित", "avasthita", "established"],
        ["चेतसः", "cetasaḥ", "of the mind"]],
    2: [
    ["यज्ञाय", "yajñāya", "for sacrifice"], ["आचरतः", "ācarataḥ", "of one acting"],
        ["कर्म", "karma", "action"]],
    3: [
    ["समग्रम्", "samagram", "wholly, entirely"],
        ["प्रविलीयते", "pravilīyate", "dissolves"]]
},
24: {"s": [],
     0: [["ब्रह्म", "brahma", "Brahman"],
         ["अर्पणम्", "arpaṇam", "the offering"],
         ["ब्रह्म", "brahma", "Brahman"],
         ["हविः", "haviḥ", "the oblation"]],
     1: [["ब्रह्म", "brahma", "Brahman"],
         ["अग्नौ", "agnau", "in the fire"],
         ["ब्रह्मणा", "brahmaṇā", "by Brahman"],
         ["हुतम्", "hutam", "offered"]],
     2: [["ब्रह्म", "brahma", "Brahman"],
         ["एव", "eva", "indeed"],
         ["तेन", "tena", "by him"],
         ["गन्तव्यम्", "gantavyam", "to be reached"]],
     3: [["ब्रह्म", "brahma", "of Brahman"],
         ["कर्म", "karma", "action"],
         ["समाधिना", "samādhinā", "by absorption, concentration"]]},

25: {"s": [],
     0: [["दैवम्", "daivam", "of the gods"],
         ["एव", "eva", "indeed"],
         ["अपरे", "apare", "others"],
         ["यज्ञम्", "yajñam", "sacrifice"]],
     1: [["योगिनः", "yoginaḥ", "yogis"],
         ["पर्युपासते", "paryupāsate", "worship, serve"]],
     2: [["ब्रह्म", "brahma", "of Brahman"],
         ["अग्नौ", "agnau", "in the fire"],
         ["अपरे", "apare", "others"],
         ["यज्ञम्", "yajñam", "sacrifice"]],
     3: [["यज्ञेन", "yajñena", "by sacrifice"],
         ["एव", "eva", "indeed"],
         ["उपजुह्वति", "upajuhvati", "offer"]]},

26: {"s": [],
    0: [
    ["श्रोत्रादीनि", "śrotrādīni", "hearing and the other (senses)"],
        ["इन्द्रियाणि", "indriyāṇi", "the senses"], ["अन्ये", "anye", "others"]],
    1: [
    ["संयम", "saṁyama", "of restraint"], ["अग्निषु", "agniṣu", "in the fires"],
        ["जुह्वति", "juhvati", "offer"]],
    2: [
    ["शब्दादीन्", "śabdādīn", "sound and the other"], ["विषयान्", "viṣayān", "objects"],
        ["अन्य", "anya", "others"]],
    3: [
    ["इन्द्रिय", "indriya", "of the senses"], ["अग्निषु", "agniṣu", "in the fires"],
        ["जुह्वति", "juhvati", "offer"]]
},
27: {"s": [],
     0: [["सर्वाणि", "sarvāṇi", "all"],
         ["इन्द्रिय", "indriya", "of the senses"],
         ["कर्माणि", "karmāṇi", "the activities"]],
     1: [["प्राण", "prāṇa", "of the vital breaths"],
         ["कर्माणि", "karmāṇi", "the activities"],
         ["च", "ca", "and"],
         ["अपरे", "apare", "others"]],
     2: [["आत्म", "ātma", "of the self"],
         ["संयम", "saṁyama", "restraint"],
         ["योग", "yoga", "of yoga"],
         ["अग्नौ", "agnau", "in the fire"]],
     3: [["जुह्वति", "juhvati", "offer"],
         ["ज्ञान", "jñāna", "by knowledge"],
         ["दीपिते", "dīpite", "kindled"]]},

28: {"s": [],
     0: [["द्रव्य", "dravya", "of wealth, material"],
         ["यज्ञाः", "yajñāḥ", "sacrifices"],
         ["तपः", "tapaḥ", "of austerity"],
         ["यज्ञाः", "yajñāḥ", "sacrifices"]],
     1: [["योग", "yoga", "of yoga"],
         ["यज्ञाः", "yajñāḥ", "sacrifices"],
         ["तथा", "tathā", "likewise"],
         ["अपरे", "apare", "others"]],
     2: [["स्वाध्याय", "svādhyāya", "of scriptural study"],
         ["ज्ञान", "jñāna", "of knowledge"],
         ["यज्ञाः", "yajñāḥ", "sacrifices"],
         ["च", "ca", "and"]],
     3: [["यतयः", "yatayaḥ", "the ascetics"],
         ["संशित", "saṁśita", "firm"],
         ["व्रताः", "vratāḥ", "of vows"]]},

29: {"s": [],
     0: [["अपाने", "apāne", "in the down-breath"],
         ["जुह्वति", "juhvati", "they offer"],
         ["प्राणम्", "prāṇam", "the up-breath"]],
     1: [["प्राणे", "prāṇe", "in the up-breath"],
         ["अपानम्", "apānam", "the down-breath"],
         ["तथा", "tathā", "likewise"],
         ["अपरे", "apare", "others"]],
     2: [["प्राण", "prāṇa", "of the breaths"],
         ["अपान", "apāna", "and down-breaths"],
         ["गती", "gatī", "the courses"],
         ["रुद्ध्वा", "ruddhvā", "having restrained"]],
     3: [["प्राणायाम", "prāṇāyāma", "breath-control"],
         ["परायणाः", "parāyaṇāḥ", "devoted to"]]},

30: {"s": [],
     0: [["अपरे", "apare", "others"],
         ["नियत", "niyata", "regulated"],
         ["आहाराः", "āhārāḥ", "whose food"]],
     1: [["प्राणान्", "prāṇān", "the vital breaths"],
         ["प्राणेषु", "prāṇeṣu", "in the vital breaths"],
         ["जुह्वति", "juhvati", "offer"]],
     2: [["सर्वे", "sarve", "all"],
         ["अपि", "api", "indeed"],
         ["एते", "ete", "these"],
         ["यज्ञविदः", "yajñavidaḥ", "knowers of sacrifice"]],
     3: [["यज्ञ", "yajña", "by sacrifice"],
         ["क्षपित", "kṣapita", "consumed"],
         ["कल्मषाः", "kalmaṣāḥ", "whose sins"]]},

31: {"s": [],
     0: [["यज्ञ", "yajña", "of sacrifice"],
         ["शिष्ट", "śiṣṭa", "remnant, leftover"],
         ["अमृत", "amṛta", "nectar"],
         ["भुजः", "bhujaḥ", "who eat"]],
     1: [["यान्ति", "yānti", "they go to"],
         ["ब्रह्म", "brahma", "Brahman"],
         ["सनातनम्", "sanātanam", "eternal"]],
     2: [["न", "na", "not"],
         ["अयम्", "ayam", "this"],
         ["लोकः", "lokaḥ", "world"],
         ["अस्ति", "asti", "is"],
         ["अयज्ञस्य", "ayajñasya", "of the non-sacrificer"]],
     3: [["कुतः", "kutaḥ", "how then"],
         ["अन्यः", "anyaḥ", "the other"],
         ["कुरुसत्तम", "kurusattama", "O best of the Kurus"]]},

32: {"s": [],
     0: [["एवम्", "evam", "thus"],
         ["बहुविधाः", "bahuvidhāḥ", "many kinds of"],
         ["यज्ञाः", "yajñāḥ", "sacrifices"]],
     1: [["वितताः", "vitatāḥ", "spread, set forth"],
         ["ब्रह्मणः", "brahmaṇaḥ", "of Brahman (the Vedas)"],
         ["मुखे", "mukhe", "in the mouth"]],
     2: [["कर्मजान्", "karmajān", "born of action"],
         ["विद्धि", "viddhi", "know"],
         ["तान्", "tān", "them"],
         ["सर्वान्", "sarvān", "all"]],
     3: [["एवम्", "evam", "thus"],
         ["ज्ञात्वा", "jñātvā", "having known"],
         ["विमोक्ष्यसे", "vimokṣyase", "you shall be freed"]]},

33: {"s": [],
     0: [["श्रेयान्", "śreyān", "better"],
         ["द्रव्यमयात्", "dravyamayāt", "than the material"],
         ["यज्ञात्", "yajñāt", "sacrifice"]],
     1: [["ज्ञानयज्ञः", "jñānayajñaḥ", "the sacrifice of knowledge"],
         ["परन्तप", "parantapa", "O scorcher of foes"]],
     2: [["सर्वम्", "sarvam", "all"],
         ["कर्म", "karma", "action"],
         ["अखिलम्", "akhilam", "entirely"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     3: [["ज्ञाने", "jñāne", "in knowledge"],
         ["परिसमाप्यते", "parisamāpyate", "culminates, ends"]]},

34: {"s": [],
     0: [["तत्", "tat", "that"],
         ["विद्धि", "viddhi", "know"],
         ["प्रणिपातेन", "praṇipātena", "by prostration"]],
     1: [["परिप्रश्नेन", "paripraśnena", "by questioning"],
         ["सेवया", "sevayā", "by service"]],
     2: [["उपदेक्ष्यन्ति", "upadekṣyanti", "they will instruct"],
         ["ते", "te", "you"],
         ["ज्ञानम्", "jñānam", "knowledge"]],
     3: [["ज्ञानिनः", "jñāninaḥ", "the wise"],
         ["तत्त्वदर्शिनः", "tattvadarśinaḥ", "seers of truth"]]},

35: {"s": [],
     0: [["यत्", "yat", "which"],
         ["ज्ञात्वा", "jñātvā", "having known"],
         ["न", "na", "not"],
         ["पुनः", "punaḥ", "again"],
         ["मोहम्", "moham", "delusion"]],
     1: [["एवम्", "evam", "thus"],
         ["यास्यसि", "yāsyasi", "you will go, fall"],
         ["पाण्डव", "pāṇḍava", "O son of Pāṇḍu"]],
     2: [["येन", "yena", "by which"],
         ["भूतानि", "bhūtāni", "beings"],
         ["अशेषेण", "aśeṣeṇa", "without exception"]],
     3: [["द्रक्ष्यसि", "drakṣyasi", "you will see"],
         ["आत्मनि", "ātmani", "in the Self"],
         ["अथो", "atho", "and then"],
         ["मयि", "mayi", "in me"]]},

36: {"s": [],
     0: [["अपि", "api", "even"],
         ["चेत्", "cet", "if"],
         ["असि", "asi", "you are"],
         ["पापेभ्यः", "pāpebhyaḥ", "among sinners"]],
     1: [["सर्वेभ्यः", "sarvebhyaḥ", "among all"],
         ["पापकृत्", "pāpakṛt", "sinner"],
         ["तमः", "tamaḥ", "the worst"]],
     2: [["सर्वम्", "sarvam", "all"],
         ["ज्ञान", "jñāna", "of knowledge"],
         ["प्लवेन", "plavena", "by the raft, boat"],
         ["एव", "eva", "alone"]],
     3: [["वृजिनम्", "vṛjinam", "sin, evil"],
         ["सन्तरिष्यसि", "santariṣyasi", "you will cross"]]},

37: {"s": [],
     0: [["यथा", "yathā", "as"],
         ["एधांसि", "edhāṁsi", "fuel"],
         ["समिद्धः", "samiddhaḥ", "blazing"],
         ["अग्निः", "agniḥ", "fire"]],
     1: [["भस्मसात्", "bhasmasāt", "to ashes"],
         ["कुरुते", "kurute", "reduces, makes"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["ज्ञान", "jñāna", "of knowledge"],
         ["अग्निः", "agniḥ", "the fire"],
         ["सर्वकर्माणि", "sarvakarmāṇi", "all actions"]],
     3: [["भस्मसात्", "bhasmasāt", "to ashes"],
         ["कुरुते", "kurute", "reduces"],
         ["तथा", "tathā", "so"]]},

38: {"s": [],
     0: [["न", "na", "not"],
         ["हि", "hi", "indeed"],
         ["ज्ञानेन", "jñānena", "with knowledge"],
         ["सदृशम्", "sadṛśam", "equal, comparable"]],
     1: [["पवित्रम्", "pavitram", "purifying"],
         ["इह", "iha", "here"],
         ["विद्यते", "vidyate", "there is"]],
     2: [["तत्", "tat", "that"],
         ["स्वयम्", "svayam", "by oneself"],
         ["योगसंसिद्धः", "yogasaṁsiddhaḥ", "perfected in yoga"]],
     3: [["कालेन", "kālena", "in time"],
         ["आत्मनि", "ātmani", "in the Self"],
         ["विन्दति", "vindati", "finds"]]},

39: {"s": [],
    0: [
    ["श्रद्धावान्", "śraddhāvān", "the man of faith"], ["लभते", "labhate", "gains"],
        ["ज्ञानम्", "jñānam", "knowledge"]],
    1: [
    ["तत्परः", "tatparaḥ", "intent on it, devoted to it"],
        ["संयतेन्द्रियः", "saṁyatendriyaḥ", "with senses subdued"]],
    2: [
    ["ज्ञानम्", "jñānam", "knowledge"], ["लब्ध्वा", "labdhvā", "having gained"],
        ["पराम्", "parām", "supreme"], ["शान्तिम्", "śāntim", "peace"]],
    3: [
    ["अचिरेण", "acireṇa", "soon, before long"], ["अधिगच्छति", "adhigacchati", "attains"]]
},
40: {"s": [],
     0: [["अज्ञः", "ajñaḥ", "the ignorant"],
         ["च", "ca", "and"],
         ["अश्रद्दधानः", "aśraddadhānaḥ", "without faith"],
         ["च", "ca", "and"]],
     1: [["संशयात्मा", "saṁśayātmā", "of doubting mind"],
         ["विनश्यति", "vinaśyati", "perishes"]],
     2: [["न", "na", "not"],
         ["अयम्", "ayam", "this"],
         ["लोकः", "lokaḥ", "world"],
         ["अस्ति", "asti", "is"],
         ["न", "na", "nor"],
         ["परः", "paraḥ", "the next"]],
     3: [["न", "na", "nor"],
         ["सुखम्", "sukham", "happiness"],
         ["संशयात्मनः", "saṁśayātmanaḥ", "of the doubting soul"]]},

41: {"s": [],
    0: [
    ["योग", "yoga", "by yoga"], ["सन्न्यस्त", "sannyasta", "renounced"],
        ["कर्माणम्", "karmāṇam", "whose actions"]],
    1: [
    ["ज्ञान", "jñāna", "by knowledge"], ["सञ्छिन्न", "sañchinna", "cut"],
        ["संशयम्", "saṁśayam", "whose doubt"]],
    2: [
    ["आत्मवन्तम्", "ātmavantam", "self-possessed"], ["न", "na", "not"],
        ["कर्माणि", "karmāṇi", "actions"]],
    3: [
    ["निबध्नन्ति", "nibadhnanti", "bind"], ["धनञ्जय", "dhanañjaya", "O Dhanañjaya"]]
},
42: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["अज्ञान", "ajñāna", "ignorance"],
         ["सम्भूतम्", "sambhūtam", "born of"]],
     1: [["हृत्स्थम्", "hṛtstham", "dwelling in the heart"],
         ["ज्ञान", "jñāna", "of knowledge"],
         ["असिना", "asinā", "with the sword"],
         ["आत्मनः", "ātmanaḥ", "of the Self"]],
     2: [["छित्त्वा", "chittvā", "having cut"],
         ["एनम्", "enam", "this"],
         ["संशयम्", "saṁśayam", "doubt"],
         ["योगम्", "yogam", "in yoga"]],
     3: [["आतिष्ठ", "ātiṣṭha", "stand firm"],
         ["उत्तिष्ठ", "uttiṣṭha", "arise"],
         ["भारत", "bhārata", "O Bhārata"]]},
}
