# -*- coding: utf-8 -*-
"""padachheda_ch3.py — per-pāda pada-chheda (word splits) for all 43 verses of Gita Chapter 3.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH3_WORDS = {
1: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"],
          ["उवाच", "uvāca", "said"]],
    0: [["ज्यायसी", "jyāyasī", "better, superior"],
        ["चेत्", "cet", "if"],
        ["कर्मणः", "karmaṇaḥ", "than action"],
        ["ते", "te", "by you"]],
    1: [["मता", "matā", "considered"],
        ["बुद्धिः", "buddhiḥ", "wisdom, intelligence"],
        ["जनार्दन", "janārdana", "O Janārdana (Kṛṣṇa)"]],
    2: [["तत्", "tat", "then"],
        ["किम्", "kim", "why"],
        ["कर्मणि", "karmaṇi", "in action"],
        ["घोरे", "ghore", "dreadful, terrible"],
        ["माम्", "mām", "me"]],
    3: [["नियोजयसि", "niyojayasi", "you engage"],
        ["केशव", "keśava", "O Keśava (Kṛṣṇa)"]]},

2: {"s": [],
    0: [["व्यामिश्रेण", "vyāmiśreṇa", "with equivocal, mixed"],
        ["इव", "iva", "as it were"],
        ["वाक्येन", "vākyena", "words"]],
    1: [["बुद्धिम्", "buddhim", "the intellect"],
        ["मोहयसि", "mohayasi", "you confuse"],
        ["इव", "iva", "indeed"],
        ["मे", "me", "my"]],
    2: [["तत्", "tat", "therefore"],
        ["एकम्", "ekam", "one"],
        ["वद", "vada", "tell"],
        ["निश्चित्य", "niścitya", "having determined"]],
    3: [["येन", "yena", "by which"],
        ["श्रेयः", "śreyaḥ", "the good, welfare"],
        ["अहम्", "aham", "I"],
        ["आप्नुयाम्", "āpnuyām", "may attain"]]},

3: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
          ["उवाच", "uvāca", "said"]],
    0: [["लोके", "loke", "in the world"],
        ["अस्मिन्", "asmin", "this"],
        ["द्विविधा", "dvividhā", "twofold"],
        ["निष्ठा", "niṣṭhā", "path of steadfastness"]],
    1: [["पुरा", "purā", "formerly, of old"],
        ["प्रोक्ता", "proktā", "declared, taught"],
        ["मया", "mayā", "by me"],
        ["अनघ", "anagha", "O sinless one"]],
    2: [["ज्ञानयोगेन", "jñānayogena", "through the yoga of knowledge"],
        ["साङ्ख्यानाम्", "sāṅkhyānām", "of the Sāṅkhyas (contemplatives)"]],
    3: [["कर्मयोगेन", "karmayogena", "through the yoga of action"],
        ["योगिनाम्", "yoginām", "of the yogis (workers)"]]},

4: {"s": [],
    0: [["न", "na", "not"],
        ["कर्मणाम्", "karmaṇām", "of actions"],
        ["अनारम्भात्", "anārambhāt", "by non-performance, non-beginning"]],
    1: [["नैष्कर्म्यम्", "naiṣkarmyam", "freedom from action"],
        ["पुरुषः", "puruṣaḥ", "a man"],
        ["अश्नुते", "aśnute", "attains"]],
    2: [["न", "na", "nor"],
        ["च", "ca", "and"],
        ["सन्न्यसनात्", "sannyasanāt", "by renunciation"],
        ["एव", "eva", "alone, indeed"]],
    3: [["सिद्धिम्", "siddhim", "perfection"],
        ["समधिगच्छति", "samadhigacchati", "reaches"]]},

5: {"s": [],
    0: [["न", "na", "not"],
        ["हि", "hi", "indeed"],
        ["कश्चित्", "kaścit", "anyone"],
        ["क्षणम्", "kṣaṇam", "a moment"],
        ["अपि", "api", "even"]],
    1: [["जातु", "jātu", "at all, ever"],
        ["तिष्ठति", "tiṣṭhati", "remains"],
        ["अकर्मकृत्", "akarmakṛt", "actionless, not performing action"]],
    2: [["कार्यते", "kāryate", "is made to act"],
        ["हि", "hi", "indeed"],
        ["अवशः", "avaśaḥ", "helpless"],
        ["कर्म", "karma", "action"]],
    3: [["सर्वः", "sarvaḥ", "everyone"],
        ["प्रकृति", "prakṛti", "of nature (prakṛti)"],
        ["जैः", "jaiḥ", "born"],
        ["गुणैः", "guṇaiḥ", "by the guṇas (qualities)"]]},

6: {"s": [],
    0: [["कर्म", "karma", "of action"],
        ["इन्द्रियाणि", "indriyāṇi", "the organs"],
        ["संयम्य", "saṁyamya", "having restrained"]],
    1: [["यः", "yaḥ", "who"],
        ["आस्ते", "āste", "sits, remains"],
        ["मनसा", "manasā", "in mind"],
        ["स्मरन्", "smaran", "recollecting, remembering"]],
    2: [["इन्द्रिय", "indriya", "sense"],
        ["अर्थान्", "arthān", "objects"],
        ["विमूढ", "vimūḍha", "deluded"],
        ["आत्मा", "ātmā", "one whose self"]],
    3: [["मिथ्याचारः", "mithyācāraḥ", "hypocrite, one of false conduct"],
        ["सः", "saḥ", "he"],
        ["उच्यते", "ucyate", "is called"]]},

7: {"s": [],
    0: [["यः", "yaḥ", "who"],
        ["तु", "tu", "but"],
        ["इन्द्रियाणि", "indriyāṇi", "the senses"],
        ["मनसा", "manasā", "with the mind"]],
    1: [["नियम्य", "niyamya", "having controlled"],
        ["आरभते", "ārabhate", "begins, undertakes"],
        ["अर्जुन", "arjuna", "O Arjuna"]],
    2: [["कर्म", "karma", "of action"],
        ["इन्द्रियैः", "indriyaiḥ", "with the organs"],
        ["कर्म", "karma", "of action"],
        ["योगम्", "yogam", "the yoga"]],
    3: [["असक्तः", "asaktaḥ", "unattached"],
        ["सः", "saḥ", "he"],
        ["विशिष्यते", "viśiṣyate", "excels, is superior"]]},

8: {"s": [],
    0: [["नियतम्", "niyatam", "prescribed, fixed"],
        ["कुरु", "kuru", "perform"],
        ["कर्म", "karma", "action"],
        ["त्वम्", "tvam", "you"]],
    1: [["कर्म", "karma", "action"],
        ["ज्यायः", "jyāyaḥ", "superior"],
        ["हि", "hi", "indeed"],
        ["अकर्मणः", "akarmaṇaḥ", "than inaction"]],
    2: [["शरीरयात्रा", "śarīrayātrā", "the maintenance of the body"],
        ["अपि", "api", "even"],
        ["च", "ca", "and"],
        ["ते", "te", "your"]],
    3: [["न", "na", "not"],
        ["प्रसिध्येत्", "prasidhyet", "would succeed"],
        ["अकर्मणः", "akarmaṇaḥ", "through inaction"]]},

9: {"s": [],
    0: [["यज्ञ", "yajña", "for sacrifice"],
        ["अर्थात्", "arthāt", "for the sake of"],
        ["कर्मणः", "karmaṇaḥ", "from action"],
        ["अन्यत्र", "anyatra", "other than, except"]],
    1: [["लोकः", "lokaḥ", "the world"],
        ["अयम्", "ayam", "this"],
        ["कर्म", "karma", "by action"],
        ["बन्धनः", "bandhanaḥ", "bound"]],
    2: [["तत्", "tat", "that"],
        ["अर्थम्", "artham", "for that purpose"],
        ["कर्म", "karma", "action"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    3: [["मुक्त", "mukta", "freed"],
        ["सङ्गः", "saṅgaḥ", "from attachment"],
        ["समाचर", "samācara", "perform"]]},

10: {"s": [],
     0: [["सह", "saha", "together with"],
         ["यज्ञाः", "yajñāḥ", "sacrifice"],
         ["प्रजाः", "prajāḥ", "creatures, people"],
         ["सृष्ट्वा", "sṛṣṭvā", "having created"]],
     1: [["पुरा", "purā", "in the beginning, of old"],
         ["उवाच", "uvāca", "said"],
         ["प्रजा", "prajā", "of creatures"],
         ["पतिः", "patiḥ", "the Lord (Prajāpati)"]],
     2: [["अनेन", "anena", "by this"],
         ["प्रसविष्यध्वम्", "prasaviṣyadhvam", "may you prosper, multiply"]],
     3: [["एषः", "eṣaḥ", "this"],
         ["वः", "vaḥ", "to you"],
         ["अस्तु", "astu", "may it be"],
         ["इष्ट", "iṣṭa", "of desires"],
         ["कामधुक्", "kāmadhuk", "the cow (bestower)"]]},

11: {"s": [],
     0: [["देवान्", "devān", "the gods"],
         ["भावयत", "bhāvayata", "nourish, please"],
         ["अनेन", "anena", "with this"]],
     1: [["ते", "te", "those"],
         ["देवाः", "devāḥ", "gods"],
         ["भावयन्तु", "bhāvayantu", "may they nourish"],
         ["वः", "vaḥ", "you"]],
     2: [["परस्परम्", "parasparam", "one another"],
         ["भावयन्तः", "bhāvayantaḥ", "nourishing"]],
     3: [["श्रेयः", "śreyaḥ", "the highest good"],
         ["परम्", "param", "supreme"],
         ["अवाप्स्यथ", "avāpsyatha", "you shall attain"]]},

12: {"s": [],
     0: [["इष्टान्", "iṣṭān", "desired"],
         ["भोगान्", "bhogān", "enjoyments"],
         ["हि", "hi", "indeed"],
         ["वः", "vaḥ", "to you"],
         ["देवाः", "devāḥ", "the gods"]],
     1: [["दास्यन्ते", "dāsyante", "will give"],
         ["यज्ञ", "yajña", "by sacrifice"],
         ["भाविताः", "bhāvitāḥ", "nourished, gratified"]],
     2: [["तैः", "taiḥ", "by them"],
         ["दत्तान्", "dattān", "given"],
         ["अप्रदाय", "apradāya", "without offering back"],
         ["एभ्यः", "ebhyaḥ", "to them"]],
     3: [["यः", "yaḥ", "who"],
         ["भुङ्क्ते", "bhuṅkte", "enjoys"],
         ["स्तेनः", "stenaḥ", "a thief"],
         ["एव", "eva", "verily"],
         ["सः", "saḥ", "he"]]},

13: {"s": [],
     0: [["यज्ञ", "yajña", "of sacrifice"],
         ["शिष्ट", "śiṣṭa", "the remnant, leftover"],
         ["अशिनः", "aśinaḥ", "who eat"],
         ["सन्तः", "santaḥ", "the good, virtuous"]],
     1: [["मुच्यन्ते", "mucyante", "are released"],
         ["सर्व", "sarva", "all"],
         ["किल्बिषैः", "kilbiṣaiḥ", "from sins"]],
     2: [["भुञ्जते", "bhuñjate", "they eat"],
         ["ते", "te", "they"],
         ["तु", "tu", "but, indeed"],
         ["अघम्", "agham", "sin"],
         ["पापाः", "pāpāḥ", "the wicked"]],
     3: [["ये", "ye", "who"],
         ["पचन्ति", "pacanti", "cook"],
         ["आत्म", "ātma", "for themselves"],
         ["कारणात्", "kāraṇāt", "for the sake of"]]},

14: {"s": [],
     0: [["अन्नात्", "annāt", "from food"],
         ["भवन्ति", "bhavanti", "arise"],
         ["भूतानि", "bhūtāni", "beings"]],
     1: [["पर्जन्यात्", "parjanyāt", "from rain"],
         ["अन्न", "anna", "of food"],
         ["सम्भवः", "sambhavaḥ", "the arising"]],
     2: [["यज्ञात्", "yajñāt", "from sacrifice"],
         ["भवति", "bhavati", "arises"],
         ["पर्जन्यः", "parjanyaḥ", "rain"]],
     3: [["यज्ञः", "yajñaḥ", "sacrifice"],
         ["कर्म", "karma", "from action"],
         ["समुद्भवः", "samudbhavaḥ", "born, arising"]]},

15: {"s": [],
     0: [["कर्म", "karma", "action"],
         ["ब्रह्म", "brahma", "from Brahman"],
         ["उद्भवम्", "udbhavam", "arising"],
         ["विद्धि", "viddhi", "know"]],
     1: [["ब्रह्म", "brahma", "Brahman"],
         ["अक्षर", "akṣara", "from the Imperishable"],
         ["समुद्भवम्", "samudbhavam", "arising"]],
     2: [["तस्मात्", "tasmāt", "therefore"],
         ["सर्व", "sarva", "all"],
         ["गतम्", "gatam", "pervading"],
         ["ब्रह्म", "brahma", "Brahman"]],
     3: [["नित्यम्", "nityam", "eternally, always"],
         ["यज्ञे", "yajñe", "in sacrifice"],
         ["प्रतिष्ठितम्", "pratiṣṭhitam", "established"]]},

16: {"s": [],
     0: [["एवम्", "evam", "thus"],
         ["प्रवर्तितम्", "pravartitam", "set in motion"],
         ["चक्रम्", "cakram", "the wheel"]],
     1: [["न", "na", "not"],
         ["अनुवर्तयति", "anuvartayati", "follows, keeps turning"],
         ["इह", "iha", "here, in this world"],
         ["यः", "yaḥ", "who"]],
     2: [["अघ", "agha", "of sin"],
         ["आयुः", "āyuḥ", "whose life"],
         ["इन्द्रिय", "indriya", "in the senses"],
         ["आरामः", "ārāmaḥ", "who delights"]],
     3: [["मोघम्", "mogham", "in vain"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सः", "saḥ", "he"],
         ["जीवति", "jīvati", "lives"]]},

17: {"s": [],
     0: [["यः", "yaḥ", "who"],
         ["तु", "tu", "but"],
         ["आत्म", "ātma", "in the Self"],
         ["रतिः", "ratiḥ", "taking delight"],
         ["एव", "eva", "alone"],
         ["स्यात्", "syāt", "may be"]],
     1: [["आत्म", "ātma", "with the Self"],
         ["तृप्तः", "tṛptaḥ", "satisfied"],
         ["च", "ca", "and"],
         ["मानवः", "mānavaḥ", "a man"]],
     2: [["आत्मनि", "ātmani", "in the Self"],
         ["एव", "eva", "alone"],
         ["च", "ca", "and"],
         ["सन्तुष्टः", "santuṣṭaḥ", "content"]],
     3: [["तस्य", "tasya", "for him"],
         ["कार्यम्", "kāryam", "duty, work"],
         ["न", "na", "not"],
         ["विद्यते", "vidyate", "there is"]]},

18: {"s": [],
     0: [["न", "na", "not"],
         ["एव", "eva", "indeed"],
         ["तस्य", "tasya", "for him"],
         ["कृतेन", "kṛtena", "by what is done"],
         ["अर्थः", "arthaḥ", "purpose"]],
     1: [["न", "na", "nor"],
         ["अकृतेन", "akṛtena", "by what is not done"],
         ["इह", "iha", "here"],
         ["कश्चन", "kaścana", "any"]],
     2: [["न", "na", "nor"],
         ["च", "ca", "and"],
         ["अस्य", "asya", "of him"],
         ["सर्व", "sarva", "all"],
         ["भूतेषु", "bhūteṣu", "among beings"]],
     3: [["कश्चित्", "kaścit", "any"],
         ["अर्थ", "artha", "of purpose"],
         ["व्यपाश्रयः", "vyapāśrayaḥ", "dependence"]]},

19: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["असक्तः", "asaktaḥ", "unattached"],
         ["सततम्", "satatam", "always"]],
     1: [["कार्यम्", "kāryam", "the duty to be done"],
         ["कर्म", "karma", "action"],
         ["समाचर", "samācara", "perform"]],
     2: [["असक्तः", "asaktaḥ", "unattached"],
         ["हि", "hi", "indeed"],
         ["आचरन्", "ācaran", "performing"],
         ["कर्म", "karma", "action"]],
     3: [["परम्", "param", "the Supreme"],
         ["आप्नोति", "āpnoti", "attains"],
         ["पूरुषः", "pūruṣaḥ", "a man"]]},

20: {"s": [],
     0: [["कर्मणा", "karmaṇā", "by action"],
         ["एव", "eva", "alone"],
         ["हि", "hi", "indeed"],
         ["संसिद्धिम्", "saṁsiddhim", "perfection"]],
     1: [["आस्थिताः", "āsthitāḥ", "attained, reached"],
         ["जनकादयः", "janakādayaḥ", "Janaka and others"]],
     2: [["लोक", "loka", "of the world"],
         ["सङ्ग्रहम्", "saṅgraham", "the welfare, gathering"],
         ["एव", "eva", "even"],
         ["अपि", "api", "also"]],
     3: [["सम्पश्यन्", "sampaśyan", "having regard for"],
         ["कर्तुम्", "kartum", "to do"],
         ["अर्हसि", "arhasi", "you should"]]},

21: {"s": [],
     0: [["यत्", "yat", "whatever"],
         ["यत्", "yat", "whatever"],
         ["आचरति", "ācarati", "does, performs"],
         ["श्रेष्ठः", "śreṣṭhaḥ", "the best, the leader"]],
     1: [["तत्", "tat", "that"],
         ["तत्", "tat", "that"],
         ["एव", "eva", "indeed"],
         ["इतरः", "itaraḥ", "the other, common"],
         ["जनः", "janaḥ", "person"]],
     2: [["सः", "saḥ", "he"],
         ["यत्", "yat", "which"],
         ["प्रमाणम्", "pramāṇam", "standard, authority"],
         ["कुरुते", "kurute", "makes"]],
     3: [["लोकः", "lokaḥ", "the world"],
         ["तत्", "tat", "that"],
         ["अनुवर्तते", "anuvartate", "follows"]]},

22: {"s": [],
     0: [["न", "na", "not"],
         ["मे", "me", "for me"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["अस्ति", "asti", "there is"],
         ["कर्तव्यम्", "kartavyam", "to be done"]],
     1: [["त्रिषु", "triṣu", "in the three"],
         ["लोकेषु", "lokeṣu", "worlds"],
         ["किञ्चन", "kiñcana", "anything"]],
     2: [["न", "na", "not"],
         ["अनवाप्तम्", "anavāptam", "unattained"],
         ["अवाप्तव्यम्", "avāptavyam", "to be attained"]],
     3: [["वर्ते", "varte", "I engage, I am engaged"],
         ["एव", "eva", "still, indeed"],
         ["च", "ca", "and"],
         ["कर्मणि", "karmaṇi", "in action"]]},

23: {"s": [],
     0: [["यदि", "yadi", "if"],
         ["हि", "hi", "indeed"],
         ["अहम्", "aham", "I"],
         ["न", "na", "not"],
         ["वर्तेयम्", "varteyam", "I should engage"]],
     1: [["जातु", "jātu", "ever, at any time"],
         ["कर्मणि", "karmaṇi", "in action"],
         ["अतन्द्रितः", "atandritaḥ", "untiring, diligent"]],
     2: [["मम", "mama", "my"],
         ["वर्त्म", "vartma", "path"],
         ["अनुवर्तन्ते", "anuvartante", "they follow"]],
     3: [["मनुष्याः", "manuṣyāḥ", "people"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सर्वशः", "sarvaśaḥ", "in all respects"]]},

24: {"s": [],
     0: [["उत्सीदेयुः", "utsīdeyuḥ", "would perish"],
         ["इमे", "ime", "these"],
         ["लोकाः", "lokāḥ", "worlds"]],
     1: [["न", "na", "not"],
         ["कुर्याम्", "kuryām", "I should perform"],
         ["कर्म", "karma", "action"],
         ["चेत्", "cet", "if"],
         ["अहम्", "aham", "I"]],
     2: [["सङ्करस्य", "saṅkarasya", "of chaos, mixture"],
         ["च", "ca", "and"],
         ["कर्ता", "kartā", "the author, doer"],
         ["स्याम्", "syām", "I would be"]],
     3: [["उपहन्याम्", "upahanyām", "I would destroy"],
         ["इमाः", "imāḥ", "these"],
         ["प्रजाः", "prajāḥ", "creatures"]]},

25: {"s": [],
     0: [["सक्ताः", "saktāḥ", "attached"],
         ["कर्मणि", "karmaṇi", "to action"],
         ["अविद्वांसः", "avidvāṁsaḥ", "the ignorant, unwise"]],
     1: [["यथा", "yathā", "as"],
         ["कुर्वन्ति", "kurvanti", "they act"],
         ["भारत", "bhārata", "O Bhārata"]],
     2: [["कुर्यात्", "kuryāt", "should act"],
         ["विद्वान्", "vidvān", "the wise"],
         ["तथा", "tathā", "so"],
         ["असक्तः", "asaktaḥ", "unattached"]],
     3: [["चिकीर्षुः", "cikīrṣuḥ", "desiring to do"],
         ["लोक", "loka", "of the world"],
         ["सङ्ग्रहम्", "saṅgraham", "the welfare"]]},

26: {"s": [],
     0: [["न", "na", "not"],
         ["बुद्धि", "buddhi", "of mind"],
         ["भेदम्", "bhedam", "disturbance, division"],
         ["जनयेत्", "janayet", "should cause"]],
     1: [["अज्ञानाम्", "ajñānām", "of the ignorant"],
         ["कर्म", "karma", "in action"],
         ["सङ्गिनाम्", "saṅginām", "attached"]],
     2: [["जोषयेत्", "joṣayet", "should encourage"],
         ["सर्व", "sarva", "all"],
         ["कर्माणि", "karmāṇi", "actions"]],
     3: [["विद्वान्", "vidvān", "the wise"],
         ["युक्तः", "yuktaḥ", "devoted, engaged"],
         ["समाचरन्", "samācaran", "performing"]]},

27: {"s": [],
     0: [["प्रकृतेः", "prakṛteḥ", "of prakṛti (nature)"],
         ["क्रियमाणानि", "kriyamāṇāni", "being performed"]],
     1: [["गुणैः", "guṇaiḥ", "by the guṇas"],
         ["कर्माणि", "karmāṇi", "actions"],
         ["सर्वशः", "sarvaśaḥ", "in every way"]],
     2: [["अहङ्कार", "ahaṅkāra", "by egoism"],
         ["विमूढ", "vimūḍha", "deluded"],
         ["आत्मा", "ātmā", "one whose self"]],
     3: [["कर्ता", "kartā", "the doer"],
         ["अहम्", "aham", "I"],
         ["इति", "iti", "thus"],
         ["मन्यते", "manyate", "thinks"]]},

28: {"s": [],
     0: [["तत्त्ववित्", "tattvavit", "the knower of truth"],
         ["तु", "tu", "but"],
         ["महा", "mahā", "great"],
         ["बाहो", "bāho", "O armed one"]],
     1: [["गुण", "guṇa", "of the guṇas"],
         ["कर्म", "karma", "and actions"],
         ["विभागयोः", "vibhāgayoḥ", "of the distinction"]],
     2: [["गुणाः", "guṇāḥ", "the guṇas"],
         ["गुणेषु", "guṇeṣu", "among the guṇas"],
         ["वर्तन्ते", "vartante", "move, act"]],
     3: [["इति", "iti", "thus"],
         ["मत्वा", "matvā", "having known"],
         ["न", "na", "not"],
         ["सज्जते", "sajjate", "becomes attached"]]},

29: {"s": [],
     0: [["प्रकृतेः", "prakṛteḥ", "of prakṛti"],
         ["गुण", "guṇa", "by the guṇas"],
         ["सम्मूढाः", "sammūḍhāḥ", "deluded"]],
     1: [["सज्जन्ते", "sajjante", "they cling"],
         ["गुण", "guṇa", "to the actions"],
         ["कर्मसु", "karmasu", "of the guṇas"]],
     2: [["तान्", "tān", "them"],
         ["अकृत्स्न", "akṛtsna", "partial, incomplete"],
         ["विदः", "vidaḥ", "knowers"],
         ["मन्दान्", "mandān", "the dull-witted"]],
     3: [["कृत्स्नवित्", "kṛtsnavit", "the one of complete knowledge"],
         ["न", "na", "not"],
         ["विचालयेत्", "vicālayet", "should unsettle"]]},

30: {"s": [],
     0: [["मयि", "mayi", "in me"],
         ["सर्वाणि", "sarvāṇi", "all"],
         ["कर्माणि", "karmāṇi", "actions"]],
     1: [["सन्न्यस्य", "sannyasya", "having renounced, surrendered"],
         ["अध्यात्म", "adhyātma", "on the Self"],
         ["चेतसा", "cetasā", "with the mind"]],
     2: [["निराशीः", "nirāśīḥ", "free from desire"],
         ["निर्ममः", "nirmamaḥ", "free from possessiveness"],
         ["भूत्वा", "bhūtvā", "having become"]],
     3: [["युध्यस्व", "yudhyasva", "fight"],
         ["विगत", "vigata", "free from"],
         ["ज्वरः", "jvaraḥ", "fever, agitation"]]},

31: {"s": [],
     0: [["ये", "ye", "those who"],
         ["मे", "me", "my"],
         ["मतम्", "matam", "teaching"],
         ["इदम्", "idam", "this"],
         ["नित्यम्", "nityam", "always"]],
     1: [["अनुतिष्ठन्ति", "anutiṣṭhanti", "follow, practise"],
         ["मानवाः", "mānavāḥ", "people"]],
     2: [["श्रद्धावन्तः", "śraddhāvantaḥ", "having faith"],
         ["अनसूयन्तः", "anasūyantaḥ", "without finding fault, not grudging"]],
     3: [["मुच्यन्ते", "mucyante", "are released"],
         ["ते", "te", "they"],
         ["अपि", "api", "even"],
         ["कर्मभिः", "karmabhiḥ", "from actions"]]},

32: {"s": [],
     0: [["ये", "ye", "those who"],
         ["तु", "tu", "but"],
         ["एतत्", "etat", "this"],
         ["अभ्यसूयन्तः", "abhyasūyantaḥ", "finding fault, resenting"]],
     1: [["न", "na", "not"],
         ["अनुतिष्ठन्ति", "anutiṣṭhanti", "follow"],
         ["मे", "me", "my"],
         ["मतम्", "matam", "teaching"]],
     2: [["सर्व", "sarva", "all"],
         ["ज्ञान", "jñāna", "of knowledge"],
         ["विमूढान्", "vimūḍhān", "deluded"],
         ["तान्", "tān", "them"]],
     3: [["विद्धि", "viddhi", "know"],
         ["नष्टान्", "naṣṭān", "ruined, lost"],
         ["अचेतसः", "acetasaḥ", "senseless, without understanding"]]},

33: {"s": [],
     0: [["सदृशम्", "sadṛśam", "according to, in conformity with"],
         ["चेष्टते", "ceṣṭate", "acts"],
         ["स्वस्याः", "svasyāḥ", "of one's own"]],
     1: [["प्रकृतेः", "prakṛteḥ", "nature"],
         ["ज्ञानवान्", "jñānavān", "a man of knowledge"],
         ["अपि", "api", "even"]],
     2: [["प्रकृतिम्", "prakṛtim", "to nature"],
         ["यान्ति", "yānti", "they go, follow"],
         ["भूतानि", "bhūtāni", "beings"]],
     3: [["निग्रहः", "nigrahaḥ", "restraint, control"],
         ["किम्", "kim", "what"],
         ["करिष्यति", "kariṣyati", "will accomplish"]]},

34: {"s": [],
     0: [["इन्द्रियस्य", "indriyasya", "of the sense"],
         ["इन्द्रियस्य", "indriyasya", "of each sense"],
         ["अर्थे", "arthe", "in the object"]],
     1: [["राग", "rāga", "attachment"],
         ["द्वेषौ", "dveṣau", "and aversion"],
         ["व्यवस्थितौ", "vyavasthitau", "are fixed, established"]],
     2: [["तयोः", "tayoḥ", "of them, of those two"],
         ["न", "na", "not"],
         ["वशम्", "vaśam", "under the power"],
         ["आगच्छेत्", "āgacchet", "should come"]],
     3: [["तौ", "tau", "those two"],
         ["हि", "hi", "indeed"],
         ["अस्य", "asya", "of him"],
         ["परिपन्थिनौ", "paripanthinau", "waylayers, enemies on the path"]]},

35: {"s": [],
     0: [["श्रेयान्", "śreyān", "better"],
         ["स्व", "sva", "one's own"],
         ["धर्मः", "dharmaḥ", "dharma, duty"],
         ["विगुणः", "viguṇaḥ", "though defective"]],
     1: [["पर", "para", "of another"],
         ["धर्मात्", "dharmāt", "than the dharma"],
         ["स्वनुष्ठितात्", "svanuṣṭhitāt", "well-performed"]],
     2: [["स्व", "sva", "one's own"],
         ["धर्मे", "dharme", "in dharma"],
         ["निधनम्", "nidhanam", "death"],
         ["श्रेयः", "śreyaḥ", "is better"]],
     3: [["पर", "para", "another's"],
         ["धर्मः", "dharmaḥ", "dharma"],
         ["भय", "bhaya", "fear"],
         ["आवहः", "āvahaḥ", "bringing"]]},

36: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"],
          ["उवाच", "uvāca", "said"]],
     0: [["अथ", "atha", "then"],
         ["केन", "kena", "by what"],
         ["प्रयुक्तः", "prayuktaḥ", "impelled, urged"],
         ["अयम्", "ayam", "this"]],
     1: [["पापम्", "pāpam", "sin, evil"],
         ["चरति", "carati", "commits, practises"],
         ["पूरुषः", "pūruṣaḥ", "a man"]],
     2: [["अनिच्छन्", "anicchan", "not willing"],
         ["अपि", "api", "even"],
         ["वार्ष्णेय", "vārṣṇeya", "O Vārṣṇeya (Kṛṣṇa)"]],
     3: [["बलात्", "balāt", "by force"],
         ["इव", "iva", "as it were"],
         ["नियोजितः", "niyojitaḥ", "driven, compelled"]]},

37: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"],
          ["उवाच", "uvāca", "said"]],
     0: [["कामः", "kāmaḥ", "desire"],
         ["एषः", "eṣaḥ", "this"],
         ["क्रोधः", "krodhaḥ", "anger"],
         ["एषः", "eṣaḥ", "this"]],
     1: [["रजः", "rajaḥ", "of rajas (passion)"],
         ["गुण", "guṇa", "the guṇa"],
         ["समुद्भवः", "samudbhavaḥ", "born of"]],
     2: [["महा", "mahā", "great"],
         ["अशनः", "aśanaḥ", "devourer, insatiable"],
         ["महा", "mahā", "great"],
         ["पाप्मा", "pāpmā", "sinful"]],
     3: [["विद्धि", "viddhi", "know"],
         ["एनम्", "enam", "this"],
         ["इह", "iha", "here"],
         ["वैरिणम्", "vairiṇam", "as the enemy"]]},

38: {"s": [],
     0: [["धूमेन", "dhūmena", "by smoke"],
         ["आव्रियते", "āvriyate", "is enveloped, covered"],
         ["वह्निः", "vahniḥ", "fire"]],
     1: [["यथा", "yathā", "as"],
         ["आदर्शः", "ādarśaḥ", "a mirror"],
         ["मलेन", "malena", "by dust, dirt"],
         ["च", "ca", "and"]],
     2: [["यथा", "yathā", "as"],
         ["उल्बेन", "ulbena", "by the membrane, caul"],
         ["आवृतः", "āvṛtaḥ", "covered"],
         ["गर्भः", "garbhaḥ", "an embryo"]],
     3: [["तथा", "tathā", "so"],
         ["तेन", "tena", "by that"],
         ["इदम्", "idam", "this"],
         ["आवृतम्", "āvṛtam", "covered"]]},

39: {"s": [],
     0: [["आवृतम्", "āvṛtam", "covered"],
         ["ज्ञानम्", "jñānam", "wisdom"],
         ["एतेन", "etena", "by this"]],
     1: [["ज्ञानिनः", "jñāninaḥ", "of the wise"],
         ["नित्य", "nitya", "constant"],
         ["वैरिणा", "vairiṇā", "by the enemy"]],
     2: [["काम", "kāma", "of desire"],
         ["रूपेण", "rūpeṇa", "in the form"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["दुः", "duḥ", "hard, difficult"],
         ["पूरेण", "pūreṇa", "to fill, satisfy"],
         ["अनलेन", "analena", "by fire"],
         ["च", "ca", "and"]]},

40: {"s": [],
     0: [["इन्द्रियाणि", "indriyāṇi", "the senses"],
         ["मनः", "manaḥ", "the mind"],
         ["बुद्धिः", "buddhiḥ", "the intellect"]],
     1: [["अस्य", "asya", "of it"],
         ["अधिष्ठानम्", "adhiṣṭhānam", "the abode, seat"],
         ["उच्यते", "ucyate", "is said"]],
     2: [["एतैः", "etaiḥ", "by these"],
         ["विमोहयति", "vimohayati", "deludes"],
         ["एषः", "eṣaḥ", "this (desire)"]],
     3: [["ज्ञानम्", "jñānam", "wisdom"],
         ["आवृत्य", "āvṛtya", "having covered"],
         ["देहिनम्", "dehinam", "the embodied one"]]},

41: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["त्वम्", "tvam", "you"],
         ["इन्द्रियाणि", "indriyāṇi", "the senses"],
         ["आदौ", "ādau", "first"]],
     1: [["नियम्य", "niyamya", "having controlled"],
         ["भरत", "bharata", "of the Bhāratas"],
         ["ऋषभ", "ṛṣabha", "O bull, best"]],
     2: [["पाप्मानम्", "pāpmānam", "this evil one"],
         ["प्रजहिहि", "prajahihi", "cast off, give up"],
         ["एनम्", "enam", "this"]],
     3: [["ज्ञान", "jñāna", "of knowledge"],
         ["विज्ञान", "vijñāna", "and discrimination"],
         ["नाशनम्", "nāśanam", "the destroyer"]]},

42: {"s": [],
     0: [["इन्द्रियाणि", "indriyāṇi", "the senses"],
         ["पराणि", "parāṇi", "higher, superior"],
         ["आहुः", "āhuḥ", "they say"]],
     1: [["इन्द्रियेभ्यः", "indriyebhyaḥ", "than the senses"],
         ["परम्", "param", "higher"],
         ["मनः", "manaḥ", "the mind"]],
     2: [["मनसः", "manasaḥ", "than the mind"],
         ["तु", "tu", "but"],
         ["परा", "parā", "higher"],
         ["बुद्धिः", "buddhiḥ", "the intellect"]],
     3: [["यः", "yaḥ", "who, which"],
         ["बुद्धेः", "buddheḥ", "than the intellect"],
         ["परतः", "parataḥ", "beyond"],
         ["तु", "tu", "but"],
         ["सः", "saḥ", "he, that"]]},

43: {"s": [],
     0: [["एवम्", "evam", "thus"],
         ["बुद्धेः", "buddheḥ", "than the intellect"],
         ["परम्", "param", "beyond"],
         ["बुद्ध्वा", "buddhvā", "having known"]],
     1: [["संस्तभ्य", "saṁstabhya", "having steadied, restrained"],
         ["आत्मानम्", "ātmānam", "the self"],
         ["आत्मना", "ātmanā", "by the Self"]],
     2: [["जहि", "jahi", "slay"],
         ["शत्रुम्", "śatrum", "the enemy"],
         ["महा", "mahā", "great"],
         ["बाहो", "bāho", "O armed one"]],
     3: [["काम", "kāma", "of desire"],
         ["रूपम्", "rūpam", "in the form"],
         ["दुर्", "dur", "hard"],
         ["आसदम्", "āsadam", "to overcome"]]},
}
