# -*- coding: utf-8 -*-
"""padachheda_ch13.py — per-pāda pada-chheda (word splits) for all 34 verses of Gita Chapter 13.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH13_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["इदम्", "idam", "this"],
        ["शरीरम्", "śarīram", "body"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    1: [["क्षेत्रम्", "kṣetram", "the field"],
        ["इति", "iti", "thus"],
        ["अभिधीयते", "abhidhīyate", "is called"]],
    2: [["एतत्", "etat", "this"],
        ["यः", "yaḥ", "who"],
        ["वेत्ति", "vetti", "knows"],
        ["तम्", "tam", "him"],
        ["प्राहुः", "prāhuḥ", "they call"]],
    3: [["क्षेत्रज्ञः", "kṣetrajñaḥ", "the knower of the field"],
        ["इति", "iti", "thus"],
        ["तद्विदः", "tadvidaḥ", "the knowers of that"]]},

2: {"s": [],
    0: [["क्षेत्रज्ञम्", "kṣetrajñam", "the knower of the field"],
        ["च", "ca", "and"],
        ["अपि", "api", "also"],
        ["माम्", "mām", "me"],
        ["विद्धि", "viddhi", "know"]],
    1: [["सर्वक्षेत्रेषु", "sarvakṣetreṣu", "in all fields"],
        ["भारत", "bhārata", "O Bhārata"]],
    2: [["क्षेत्रक्षेत्रज्ञयोः", "kṣetrakṣetrajñayoḥ", "of the field and its knower"],
        ["ज्ञानम्", "jñānam", "the knowledge"]],
    3: [["यत्", "yat", "which"],
        ["तत्", "tat", "that"],
        ["ज्ञानम्", "jñānam", "knowledge"],
        ["मतम्", "matam", "deemed"],
        ["मम", "mama", "by me"]]},

3: {"s": [],
    0: [["तत्", "tat", "that"],
        ["क्षेत्रम्", "kṣetram", "field"],
        ["यत्", "yat", "what"],
        ["च", "ca", "and"],
        ["यादृक्", "yādṛk", "of what nature"],
        ["च", "ca", "and"]],
    1: [["यत्", "yat", "what"],
        ["विकारि", "vikāri", "its modifications"],
        ["यतः", "yataḥ", "from what"],
        ["च", "ca", "and"],
        ["यत्", "yat", "what"]],
    2: [["सः", "saḥ", "he"],
        ["च", "ca", "and"],
        ["यः", "yaḥ", "who"],
        ["यत्प्रभावः", "yatprabhāvaḥ", "of what power"],
        ["च", "ca", "and"]],
    3: [["तत्", "tat", "that"],
        ["समासेन", "samāsena", "in brief"],
        ["मे", "me", "from me"],
        ["शृणु", "śṛṇu", "hear"]]},

4: {"s": [],
    0: [["ऋषिभिः", "ṛṣibhiḥ", "by the seers"],
        ["बहुधा", "bahudhā", "in many ways"],
        ["गीतम्", "gītam", "sung"]],
    1: [["छन्दोभिः", "chandobhiḥ", "in the meters"],
        ["विविधैः", "vividhaiḥ", "diverse"],
        ["पृथक्", "pṛthak", "variously"]],
    2: [["ब्रह्मसूत्रपदैः", "brahmasūtrapadaiḥ", "in the aphorisms of Brahman"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["हेतुमद्भिः", "hetumadbhiḥ", "with reasons"],
        ["विनिश्चितैः", "viniścitaiḥ", "well-decided"]]},

5: {"s": [],
    0: [["महाभूतानि", "mahābhūtāni", "the great elements"],
        ["अहङ्कारः", "ahaṅkāraḥ", "ego"]],
    1: [["बुद्धिः", "buddhiḥ", "intellect"],
        ["अव्यक्तम्", "avyaktam", "the unmanifest"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["इन्द्रियाणि", "indriyāṇi", "the senses"],
        ["दश", "daśa", "ten"],
        ["एकम्", "ekam", "and the one"],
        ["च", "ca", "and"]],
    3: [["पञ्च", "pañca", "the five"],
        ["च", "ca", "and"],
        ["इन्द्रियगोचराः", "indriyagocarāḥ", "the objects of the senses"]]},

6: {"s": [],
    0: [["इच्छा", "icchā", "desire"],
        ["द्वेषः", "dveṣaḥ", "aversion"],
        ["सुखम्", "sukham", "pleasure"],
        ["दुःखम्", "duḥkham", "pain"]],
    1: [["संघातः", "saṅghātaḥ", "the body"],
        ["चेतना", "cetanā", "consciousness"],
        ["धृतिः", "dhṛtiḥ", "constancy"]],
    2: [["एतत्", "etat", "this"],
        ["क्षेत्रम्", "kṣetram", "the field"],
        ["समासेन", "samāsena", "in brief"]],
    3: [["सविकारम्", "savikāram", "with its modifications"],
        ["उदाहृतम्", "udāhṛtam", "declared"]]},

7: {"s": [],
    0: [["अमानित्वम्", "amānitvam", "humility"],
        ["अदम्भित्वम्", "adambhitvam", "modesty"],
        ["अहिंसा", "ahiṁsā", "non-violence"]],
    1: [["क्षान्तिः", "kṣāntiḥ", "forbearance"],
        ["आर्जवम्", "ārjavam", "uprightness"]],
    2: [["आचार्योपासनम्", "ācāryopāsanam", "service to the teacher"],
        ["शौचम्", "śaucam", "purity"]],
    3: [["स्थैर्यम्", "sthairyam", "steadfastness"],
        ["आत्मविनिग्रहः", "ātmavinigrahaḥ", "self-control"]]},

8: {"s": [],
    0: [["इन्द्रियार्थेषु", "indriyārtheṣu", "toward the objects of the senses"],
        ["वैराग्यम्", "vairāgyam", "dispassion"]],
    1: [["अनहङ्कारः", "anahaṅkāraḥ", "absence of ego"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["जन्ममृत्युजराव्याधि", "janmamṛtyujarāvyādhi", "of birth, death, old age and disease"]],
    3: [["दुःखदोषानुदर्शनम्", "duḥkhadoṣānudarśanam", "the perception of the evil of suffering"]]},

9: {"s": [],
    0: [["असक्तिः", "asaktiḥ", "non-attachment"],
        ["अनभिष्वङ्गः", "anabhiṣvaṅgaḥ", "non-clinging"]],
    1: [["पुत्रदारगृहादिषु", "putradāragṛhādiṣu", "to son, wife, home and the like"]],
    2: [["नित्यम्", "nityam", "constant"],
        ["च", "ca", "and"],
        ["समचित्तत्वम्", "samacittatvam", "even-mindedness"]],
    3: [["इष्टानिष्टोपपत्तिषु", "iṣṭāniṣṭopapattiṣu", "in gain and loss"]]},

10: {"s": [],
     0: [["मयि", "mayi", "to me"],
         ["च", "ca", "and"],
         ["अनन्ययोगेन", "ananyayogena", "with undivided yoga"]],
     1: [["भक्तिः", "bhaktiḥ", "devotion"],
         ["अव्यभिचारिणी", "avyabhicāriṇī", "unwavering"]],
     2: [["विविक्तदेशसेवित्वम्", "viviktadeśasevitvam", "delight in solitude"]],
     3: [["अरतिः", "aratiḥ", "distaste"],
         ["जनसंसदि", "janasaṁsadi", "for the company of men"]]},

11: {"s": [],
     0: [["अध्यात्मज्ञाननित्यत्वम्", "adhyātmajñānanityatvam", "constant commitment to Self-knowledge"]],
     1: [["तत्त्वज्ञानार्थदर्शनम्", "tattvajñānārthadarśanam", "insight into the purpose of truth-knowledge"]],
     2: [["एतत्", "etat", "this"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["इति", "iti", "thus"],
         ["प्रोक्तम्", "proktam", "declared"]],
     3: [["अज्ञानम्", "ajñānam", "ignorance"],
         ["यत्", "yat", "which"],
         ["अतः", "ataḥ", "from this"],
         ["अन्यथा", "anyathā", "otherwise"]]},

12: {"s": [],
     0: [["ज्ञेयम्", "jñeyam", "the knowable"],
         ["यत्", "yat", "which"],
         ["तत्", "tat", "that"],
         ["प्रवक्ष्यामि", "pravakṣyāmi", "I shall declare"]],
     1: [["यत्", "yat", "which"],
         ["ज्ञात्वा", "jñātvā", "knowing"],
         ["अमृतम्", "amṛtam", "immortality"],
         ["अश्नुते", "aśnute", "one tastes"]],
     2: [["अनादिमत्", "anādimat", "beginningless"],
         ["परम्", "param", "supreme"],
         ["ब्रह्म", "brahma", "Brahman"]],
     3: [["न", "na", "not"],
         ["सत्", "sat", "being"],
         ["तत्", "tat", "that"],
         ["न", "na", "nor"],
         ["असत्", "asat", "non-being"],
         ["उच्यते", "ucyate", "is called"]]},

13: {"s": [],
    0: [
    ["सर्वतः", "sarvataḥ", "everywhere"],
        ["पाणिपादम्", "pāṇipādam", "with hands and feet"], ["तत्", "tat", "that"]],
    1: [
    ["सर्वतः", "sarvataḥ", "everywhere"],
        ["अक्षिशिरोमुखम्", "akṣiśiromukham", "with eyes, heads and faces"]],
    2: [
    ["सर्वतः", "sarvataḥ", "everywhere"], ["श्रुतिमत्", "śrutimat", "with ears"],
        ["लोके", "loke", "in the world"]],
    3: [
    ["सर्वम्", "sarvam", "all"], ["आवृत्य", "āvṛtya", "pervading"],
        ["तिष्ठति", "tiṣṭhati", "stands"]]
},
14: {"s": [],
     0: [["सर्वेन्द्रियगुणाभासम्", "sarvendriyaguṇābhāsam", "appearing with all the senses' qualities"]],
     1: [["सर्वेन्द्रियविवर्जितम्", "sarvendriyavivarjitam", "devoid of all senses"]],
     2: [["असक्तम्", "asaktam", "unattached"],
         ["सर्वभृत्", "sarvabhṛt", "upholding all"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     3: [["निर्गुणम्", "nirguṇam", "without guṇas"],
         ["गुणभोक्तृ", "guṇabhoktṛ", "enjoying the guṇas"],
         ["च", "ca", "and"]]},

15: {"s": [],
     0: [["बहिः", "bahiḥ", "outside"],
         ["अन्तः", "antaḥ", "inside"],
         ["च", "ca", "and"],
         ["भूतानाम्", "bhūtānām", "of beings"]],
     1: [["अचरम्", "acaram", "unmoving"],
         ["चरम्", "caram", "moving"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["सूक्ष्मत्वात्", "sūkṣmatvāt", "being subtle"],
         ["तत्", "tat", "that"],
         ["अविज्ञेयम्", "avijñeyam", "unknowable"]],
     3: [["दूरस्थम्", "dūrastham", "far away"],
         ["च", "ca", "and"],
         ["अन्तिके", "antike", "near"],
         ["च", "ca", "and"],
         ["तत्", "tat", "that"]]},

16: {"s": [],
     0: [["अविभक्तम्", "avibhaktam", "undivided"],
         ["च", "ca", "and"],
         ["भूतेषु", "bhūteṣu", "among beings"]],
     1: [["विभक्तम्", "vibhaktam", "divided"],
         ["इव", "iva", "as it were"],
         ["च", "ca", "and"],
         ["स्थितम्", "sthitam", "standing"]],
     2: [["भूतभर्तृ", "bhūtabhartṛ", "the supporter of beings"],
         ["च", "ca", "and"],
         ["तत्", "tat", "that"],
         ["ज्ञेयम्", "jñeyam", "to be known"]],
     3: [["ग्रसिष्णु", "grasiṣṇu", "the devourer"],
         ["प्रभविष्णु", "prabhaviṣṇu", "the creator"],
         ["च", "ca", "and"]]},

17: {"s": [],
     0: [["ज्योतिषाम्", "jyotiṣām", "of the lights"],
         ["अपि", "api", "even"],
         ["तत्", "tat", "that"],
         ["ज्योतिः", "jyotiḥ", "the light"]],
     1: [["तमसः", "tamasaḥ", "beyond darkness"],
         ["परम्", "param", "beyond"],
         ["उच्यते", "ucyate", "is declared"]],
     2: [["ज्ञानम्", "jñānam", "knowledge"],
         ["ज्ञेयम्", "jñeyam", "the knowable"],
         ["ज्ञानगम्यम्", "jñānagamyam", "the goal of knowledge"]],
     3: [["हृदि", "hṛdi", "in the heart"],
         ["सर्वस्य", "sarvasya", "of all"],
         ["विष्ठितम्", "viṣṭhitam", "seated"]]},

18: {"s": [],
     0: [["इति", "iti", "thus"],
         ["क्षेत्रम्", "kṣetram", "the field"],
         ["तथा", "tathā", "and"],
         ["ज्ञानम्", "jñānam", "knowledge"]],
     1: [["ज्ञेयम्", "jñeyam", "the knowable"],
         ["च", "ca", "and"],
         ["उक्तम्", "uktam", "declared"],
         ["समासतः", "samāsataḥ", "in brief"]],
     2: [["मद्भक्तः", "madbhaktaḥ", "my devotee"],
         ["एतत्", "etat", "this"],
         ["विज्ञाय", "vijñāya", "knowing"]],
     3: [["मद्भावाय", "madbhāvāya", "to my being"],
         ["उपपद्यते", "upapadyate", "attains"]]},

19: {"s": [],
     0: [["प्रकृतिम्", "prakṛtim", "prakṛti"],
         ["पुरुषम्", "puruṣam", "puruṣa"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     1: [["विद्धि", "viddhi", "know"],
         ["अनादी", "anādī", "beginningless"],
         ["उभौ", "ubhau", "both"],
         ["अपि", "api", "indeed"]],
     2: [["विकारान्", "vikārān", "the modifications"],
         ["च", "ca", "and"],
         ["गुणान्", "guṇān", "the guṇas"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     3: [["विद्धि", "viddhi", "know"],
         ["प्रकृतिसम्भवान्", "prakṛtisambhavān", "born of prakṛti"]]},

20: {"s": [],
     0: [["कार्यकरणकर्तृत्वे", "kāryakaraṇakartṛtve", "in agency of effect and instrument"],
         ["हेतुः", "hetuḥ", "the cause"]],
     1: [["प्रकृतिः", "prakṛtiḥ", "prakṛti"],
         ["उच्यते", "ucyate", "is said"]],
     2: [["पुरुषः", "puruṣaḥ", "puruṣa"],
         ["सुखदुःखानाम्", "sukhaduḥkhānām", "of pleasure and pain"]],
     3: [["भोक्तृत्वे", "bhoktṛtve", "in the enjoyment"],
         ["हेतुः", "hetuḥ", "the cause"],
         ["उच्यते", "ucyate", "is said"]]},

21: {"s": [],
     0: [["पुरुषः", "puruṣaḥ", "puruṣa"],
         ["प्रकृतिस्थः", "prakṛtisthaḥ", "seated in prakṛti"],
         ["हि", "hi", "indeed"]],
     1: [["भुङ्क्ते", "bhuṅkte", "enjoys"],
         ["प्रकृतिजान्", "prakṛtijān", "born of prakṛti"],
         ["गुणान्", "guṇān", "the guṇas"]],
     2: [["कारणम्", "kāraṇam", "the cause"],
         ["गुणसङ्गः", "guṇasaṅgaḥ", "attachment to the guṇas"],
         ["अस्य", "asya", "of him"]],
     3: [["सत्", "sat", "good"],
         ["असत्", "asat", "evil"],
         ["योनि", "yoni", "wombs"],
         ["जन्मसु", "janmasu", "in births"]]},

22: {"s": [],
     0: [["उपद्रष्टा", "upadraṣṭā", "the witness"],
         ["अनुमन्ता", "anumantā", "the approver"],
         ["च", "ca", "and"],
         ["भर्ता", "bhartā", "the sustainer"]],
     1: [["भोक्ता", "bhoktā", "the enjoyer"],
         ["महेश्वरः", "maheśvaraḥ", "the great Lord"]],
     2: [["परमात्मा", "paramātmā", "the supreme Self"],
         ["इति", "iti", "thus"],
         ["च", "ca", "and"],
         ["अपि", "api", "also"],
         ["उक्तः", "uktaḥ", "called"]],
     3: [["देहे", "dehe", "in the body"],
         ["अस्मिन्", "asmin", "this"],
         ["पुरुषः", "puruṣaḥ", "puruṣa"],
         ["परः", "paraḥ", "supreme"]]},

23: {"s": [],
     0: [["यः", "yaḥ", "who"],
         ["एवम्", "evam", "thus"],
         ["वेत्ति", "vetti", "knows"],
         ["पुरुषम्", "puruṣam", "puruṣa"]],
     1: [["प्रकृतिम्", "prakṛtim", "prakṛti"],
         ["च", "ca", "and"],
         ["गुणैः", "guṇaiḥ", "with its guṇas"],
         ["सह", "saha", "together"]],
     2: [["सर्वथा", "sarvathā", "in every way"],
         ["वर्तमानः", "vartamānaḥ", "living"],
         ["अपि", "api", "even"]],
     3: [["न", "na", "not"],
         ["सः", "saḥ", "he"],
         ["भूयः", "bhūyaḥ", "again"],
         ["अभिजायते", "abhijāyate", "is born"]]},

24: {"s": [],
     0: [["ध्यानेन", "dhyānena", "by meditation"],
         ["आत्मनि", "ātmani", "in the self"],
         ["पश्यन्ति", "paśyanti", "they see"]],
     1: [["केचित्", "kecit", "some"],
         ["आत्मानम्", "ātmānam", "the Self"],
         ["आत्मना", "ātmanā", "by the self"]],
     2: [["अन्ये", "anye", "others"],
         ["साङ्ख्येन", "sāṅkhyena", "by the yoga of knowledge"],
         ["योगेन", "yogena", "by yoga"]],
     3: [["कर्मयोगेन", "karmayogena", "by the yoga of action"],
         ["च", "ca", "and"],
         ["अपरे", "apare", "still others"]]},

25: {"s": [],
     0: [["अन्ये", "anye", "others"],
         ["तु", "tu", "but"],
         ["एवम्", "evam", "thus"],
         ["अजानन्तः", "ajānantaḥ", "not knowing"]],
     1: [["श्रुत्वा", "śrutvā", "having heard"],
         ["अन्येभ्यः", "anyebhyaḥ", "from others"],
         ["उपासते", "upāsate", "worship"]],
     2: [["ते", "te", "they"],
         ["अपि", "api", "also"],
         ["च", "ca", "and"],
         ["अतितरन्ति", "atitaranti", "cross beyond"],
         ["एव", "eva", "indeed"]],
     3: [["मृत्युम्", "mṛtyum", "death"],
         ["श्रुतिपरायणाः", "śrutiparāyaṇāḥ", "devoted to what they have heard"]]},

26: {"s": [],
     0: [["यावत्", "yāvat", "whatever"],
         ["सञ्जायते", "sañjāyate", "is born"],
         ["किञ्चित्", "kiñcit", "anything"]],
     1: [["सत्त्वम्", "sattvam", "being"],
         ["स्थावरजङ्गमम्", "sthāvarajaṅgamam", "moving or unmoving"]],
     2: [["क्षेत्रक्षेत्रज्ञसंयोगात्", "kṣetrakṣetrajñasaṁyogāt", "from the union of field and knower"]],
     3: [["तत्", "tat", "that"],
         ["विद्धि", "viddhi", "know"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]]},

27: {"s": [],
     0: [["समम्", "samam", "equally"],
         ["सर्वेषु", "sarveṣu", "in all"],
         ["भूतेषु", "bhūteṣu", "beings"]],
     1: [["तिष्ठन्तम्", "tiṣṭhantam", "standing"],
         ["परमेश्वरम्", "parameśvaram", "the supreme Lord"]],
     2: [["विनश्यत्सु", "vinaśyatsu", "in the perishing"],
         ["अविनश्यन्तम्", "avināśyantam", "the imperishable"]],
     3: [["यः", "yaḥ", "who"],
         ["पश्यति", "paśyati", "sees"],
         ["सः", "saḥ", "he"],
         ["पश्यति", "paśyati", "sees"]]},

28: {"s": [],
     0: [["समम्", "samam", "equally"],
         ["पश्यन्", "paśyan", "seeing"],
         ["हि", "hi", "indeed"],
         ["सर्वत्र", "sarvatra", "everywhere"]],
     1: [["समवस्थितम्", "samavasthitam", "equally established"],
         ["ईश्वरम्", "īśvaram", "the Lord"]],
     2: [["न", "na", "not"],
         ["हिनस्ति", "hinasti", "harms"],
         ["आत्मना", "ātmanā", "by the self"],
         ["आत्मानम्", "ātmānam", "the Self"]],
     3: [["ततः", "tataḥ", "therefore"],
         ["याति", "yāti", "he goes"],
         ["पराम्", "parām", "to the supreme"],
         ["गतिम्", "gatim", "goal"]]},

29: {"s": [],
     0: [["प्रकृत्या", "prakṛtyā", "by prakṛti"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"],
         ["कर्माणि", "karmāṇi", "actions"]],
     1: [["क्रियमाणानि", "kriyamāṇāni", "being performed"],
         ["सर्वशः", "sarvaśaḥ", "in every way"]],
     2: [["यः", "yaḥ", "who"],
         ["पश्यति", "paśyati", "sees"],
         ["तथा", "tathā", "so"],
         ["आत्मानम्", "ātmānam", "the Self"]],
     3: [["अकर्तारम्", "akartāram", "the non-doer"],
         ["सः", "saḥ", "he"],
         ["पश्यति", "paśyati", "sees"]]},

30: {"s": [],
     0: [["यदा", "yadā", "when"],
         ["भूतपृथग्भावम्", "bhūtapṛthagbhāvam", "the manifold states of beings"]],
     1: [["एकस्थम्", "ekastham", "resting in the One"],
         ["अनुपश्यति", "anupaśyati", "he sees"]],
     2: [["ततः", "tataḥ", "then"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"],
         ["विस्तारम्", "vistāram", "the spread"]],
     3: [["ब्रह्म", "brahma", "Brahman"],
         ["सम्पद्यते", "sampadyate", "he attains"],
         ["तदा", "tadā", "then"]]},

31: {"s": [],
     0: [["अनादित्वात्", "anāditvāt", "because of beginninglessness"],
         ["निर्गुणत्वात्", "nirguṇatvāt", "because of being without guṇas"]],
     1: [["परमात्मा", "paramātmā", "the supreme Self"],
         ["अयम्", "ayam", "this"],
         ["अव्ययः", "avyayaḥ", "imperishable"]],
     2: [["शरीरस्थः", "śarīrasthaḥ", "dwelling in the body"],
         ["अपि", "api", "though"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["न", "na", "neither"],
         ["करोति", "karoti", "acts"],
         ["न", "na", "nor"],
         ["लिप्यते", "lipyate", "is stained"]]},

32: {"s": [],
     0: [["यथा", "yathā", "as"],
         ["सर्वगतम्", "sarvagatam", "all-pervading"],
         ["सौक्ष्म्यात्", "saukṣmyāt", "because of subtlety"]],
     1: [["आकाशम्", "ākāśam", "space"],
         ["न", "na", "not"],
         ["उपलिप्यते", "upalipyate", "is stained"]],
     2: [["सर्वत्रावस्थितः", "sarvatrāvasthitaḥ", "present everywhere"],
         ["देहे", "dehe", "in the body"]],
     3: [["तथा", "tathā", "so"],
         ["आत्मा", "ātmā", "the Self"],
         ["न", "na", "not"],
         ["उपलिप्यते", "upalipyate", "is stained"]]},

33: {"s": [],
     0: [["यथा", "yathā", "as"],
         ["प्रकाशयति", "prakāśayati", "illumines"],
         ["एकः", "ekaḥ", "the one"]],
     1: [["कृत्स्नम्", "kṛtsnam", "the whole"],
         ["लोकम्", "lokam", "world"],
         ["इमम्", "imam", "this"],
         ["रविः", "raviḥ", "the sun"]],
     2: [["क्षेत्रम्", "kṣetram", "the field"],
         ["क्षेत्री", "kṣetrī", "the knower of the field"],
         ["तथा", "tathā", "so"],
         ["कृत्स्नम्", "kṛtsnam", "the whole"]],
     3: [["प्रकाशयति", "prakāśayati", "illumines"],
         ["भारत", "bhārata", "O Bhārata"]]},

34: {"s": [],
     0: [["क्षेत्रक्षेत्रज्ञयोः", "kṣetrakṣetrajñayoḥ", "of the field and its knower"],
         ["एवम्", "evam", "thus"],
         ["अन्तरम्", "antaram", "the distinction"]],
     1: [["ज्ञानचक्षुषा", "jñānacakṣuṣā", "with the eye of knowledge"]],
     2: [["भूतप्रकृतिमोक्षम्", "bhūtaprakṛtimokṣam", "the liberation from prakṛti"],
         ["च", "ca", "and"]],
     3: [["ये", "ye", "those who"],
         ["विदुः", "viduḥ", "know"],
         ["यान्ति", "yānti", "reach"],
         ["ते", "te", "they"],
         ["परम्", "param", "the supreme"]]},
}
