# -*- coding: utf-8 -*-
"""padachheda_ch8.py — per-pāda pada-chheda (word splits) for all 28 verses of Gita Chapter 8.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH8_WORDS = {
1: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
    0: [["किम्", "kim", "what"],
        ["तत्", "tat", "that"],
        ["ब्रह्म", "brahma", "Brahman"],
        ["किम्", "kim", "what"],
        ["अध्यात्मम्", "adhyātmam", "adhyātma, the Self"]],
    1: [["किम्", "kim", "what"],
        ["कर्म", "karma", "action"],
        ["पुरुषोत्तम", "puruṣottama", "O best of men"]],
    2: [["अधिभूतम्", "adhibhūtam", "adhibhūta"],
        ["च", "ca", "and"],
        ["किम्", "kim", "what"],
        ["प्रोक्तम्", "proktam", "declared"]],
    3: [["अधिदैवम्", "adhidaivam", "adhidaiva"],
        ["किम्", "kim", "what"],
        ["उच्यते", "ucyate", "is called"]]},

2: {"s": [],
    0: [["अधियज्ञः", "adhiyajñaḥ", "adhiyajña"],
        ["कथम्", "katham", "how"],
        ["कः", "kaḥ", "who"],
        ["अत्र", "atra", "here"]],
    1: [["देहे", "dehe", "in the body"],
        ["अस्मिन्", "asmin", "this"],
        ["मधुसूदन", "madhusūdana", "O Madhusūdana"]],
    2: [["प्रयाणकाले", "prayāṇakāle", "at the time of death"],
        ["च", "ca", "and"],
        ["कथम्", "katham", "how"]],
    3: [["ज्ञेयः", "jñeyaḥ", "to be known"],
        ["असि", "asi", "you are"],
        ["नियतात्मभिः", "niyatātmabhiḥ", "by the self-controlled"]]},

3: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["अक्षरम्", "akṣaram", "the imperishable"],
        ["ब्रह्म", "brahma", "Brahman"],
        ["परमम्", "paramam", "supreme"]],
    1: [["स्वभावः", "svabhāvaḥ", "one's own nature"],
        ["अध्यात्मम्", "adhyātmam", "adhyātma"],
        ["उच्यते", "ucyate", "is called"]],
    2: [["भूतभावोद्भवकरः", "bhūtabhāvodbhavakaraḥ", "the cause of the arising of beings"]],
    3: [["विसर्गः", "visargaḥ", "the creative impulse"],
        ["कर्मसंज्ञितः", "karmasaṁjñitaḥ", "called karma"]]},

4: {"s": [],
    0: [["अधिभूतम्", "adhibhūtam", "adhibhūta"],
        ["क्षरः", "kṣaraḥ", "the perishable"],
        ["भावः", "bhāvaḥ", "nature"]],
    1: [["पुरुषः", "puruṣaḥ", "the Puruṣa"],
        ["च", "ca", "and"],
        ["अधिदैवतम्", "adhidaivatam", "adhidaivata"]],
    2: [["अधियज्ञः", "adhiyajñaḥ", "adhiyajña"],
        ["अहम्", "aham", "I"],
        ["एव", "eva", "myself"],
        ["अत्र", "atra", "here"]],
    3: [["देहे", "dehe", "in the body"],
        ["देहभृताम्", "dehabhṛtām", "of the embodied"],
        ["वर", "vara", "O best"]]},

5: {"s": [],
    0: [["अन्तकाले", "antakāle", "at the end, at death"],
        ["च", "ca", "and"],
        ["माम्", "mām", "me"],
        ["एव", "eva", "alone"]],
    1: [["स्मरन्", "smaran", "remembering"],
        ["मुक्त्वा", "muktvā", "having abandoned"],
        ["कलेवरम्", "kalevaram", "the body"]],
    2: [["यः", "yaḥ", "who"],
        ["प्रयाति", "prayāti", "departs"],
        ["सः", "saḥ", "he"],
        ["मद्भावम्", "madbhāvam", "my being"]],
    3: [["याति", "yāti", "attains"],
        ["न", "na", "not"],
        ["अस्ति", "asti", "there is"],
        ["अत्र", "atra", "here"],
        ["संशयः", "saṁśayaḥ", "doubt"]]},

6: {"s": [],
    0: [["यम्", "yam", "which"],
        ["यम्", "yam", "which"],
        ["वा", "vā", "or"],
        ["अपि", "api", "indeed"],
        ["स्मरन्", "smaran", "remembering"],
        ["भावम्", "bhāvam", "state"]],
    1: [["त्यजति", "tyajati", "leaves"],
        ["अन्ते", "ante", "at the end"],
        ["कलेवरम्", "kalevaram", "the body"]],
    2: [["तम्", "tam", "to that"],
        ["तम्", "tam", "to that"],
        ["एव", "eva", "very"],
        ["एति", "eti", "goes"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    3: [["सदा", "sadā", "always"],
        ["तद्भावभावितः", "tadbhāvabhāvitaḥ", "pervaded by that thought"]]},

7: {"s": [],
    0: [["तस्मात्", "tasmāt", "therefore"],
        ["सर्वेषु", "sarveṣu", "in all"],
        ["कालेषु", "kāleṣu", "times"]],
    1: [["माम्", "mām", "me"],
        ["अनुस्मर", "anusmara", "remember"],
        ["युध्य", "yudhya", "fight"],
        ["च", "ca", "and"]],
    2: [["मयि", "mayi", "in me"],
        ["अर्पित", "arpita", "offered"],
        ["मनोबुद्धिः", "manobuddhiḥ", "mind and intellect"]],
    3: [["माम्", "mām", "to me"],
        ["एव", "eva", "surely"],
        ["एष्यसि", "eṣyasi", "you will come"],
        ["असंशयः", "asaṁśayaḥ", "without doubt"]]},

8: {"s": [],
    0: [["अभ्यासयोगयुक्तेन", "abhyāsayogayuktena", "united with the yoga of practice"]],
    1: [["चेतसा", "cetasā", "with the mind"],
        ["न", "na", "not"],
        ["अन्यगामिना", "anyagāminā", "going elsewhere"]],
    2: [["परमम्", "paramam", "the supreme"],
        ["पुरुषम्", "puruṣam", "Person"],
        ["दिव्यम्", "divyam", "divine"]],
    3: [["याति", "yāti", "reaches"],
        ["पार्थ", "pārtha", "O Pārtha"],
        ["अनुचिन्तयन्", "anucintayan", "contemplating"]]},

9: {"s": [],
    0: [["कविम्", "kavim", "the ancient seer"],
        ["पुराणम्", "purāṇam", "the ancient"],
        ["अनुशासितारम्", "anuśāsitāram", "the ruler"]],
    1: [["अणोः", "aṇoḥ", "than the subtle"],
        ["अणीयांसम्", "aṇīyāṁsam", "subtler"],
        ["अनुस्मरेत्", "anusmaret", "should meditate on"],
        ["यः", "yaḥ", "he who"]],
    2: [["सर्वस्य", "sarvasya", "of all"],
        ["धातारम्", "dhātāram", "the support, sustainer"],
        ["अचिन्त्यरूपम्", "acintyarūpam", "of inconceivable form"]],
    3: [["आदित्यवर्णम्", "ādityavarṇam", "radiant as the sun"],
        ["तमसः", "tamasaḥ", "of darkness"],
        ["परस्तात्", "parastāt", "beyond"]]},

10: {"s": [],
     0: [["प्रयाणकाले", "prayāṇakāle", "at the time of death"],
         ["मनसा", "manasā", "with the mind"],
         ["अचलेन", "acalena", "unwavering"]],
     1: [["भक्त्या", "bhaktyā", "with devotion"],
         ["युक्तः", "yuktaḥ", "united"],
         ["योगबलेन", "yogabalena", "with the power of yoga"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     2: [["भ्रुवोः", "bhruvoḥ", "of the eyebrows"],
         ["मध्ये", "madhye", "between"],
         ["प्राणम्", "prāṇam", "the breath"],
         ["आवेश्य", "āveśya", "having fixed"],
         ["सम्यक्", "samyak", "properly"]],
     3: [["सः", "saḥ", "he"],
         ["तम्", "tam", "that"],
         ["परम्", "param", "supreme"],
         ["पुरुषम्", "puruṣam", "Person"],
         ["उपैति", "upaiti", "reaches"],
         ["दिव्यम्", "divyam", "divine"]]},

11: {"s": [],
     0: [["यत्", "yat", "which"],
         ["अक्षरम्", "akṣaram", "the imperishable"],
         ["वेदविदः", "vedavidaḥ", "the knowers of the Vedas"],
         ["वदन्ति", "vadanti", "declare"]],
     1: [["विशन्ति", "viśanti", "enter"],
         ["यत्", "yat", "which"],
         ["यतयः", "yatayaḥ", "the ascetics"],
         ["वीतरागाः", "vītarāgāḥ", "free from desire"]],
     2: [["यत्", "yat", "which"],
         ["इच्छन्तः", "icchantaḥ", "desiring"],
         ["ब्रह्मचर्यम्", "brahmacaryam", "celibacy"],
         ["चरन्ति", "caranti", "practise"]],
     3: [["तत्", "tat", "that"],
         ["ते", "te", "to you"],
         ["पदम्", "padam", "goal"],
         ["सङ्ग्रहेण", "saṅgraheṇa", "briefly"],
         ["प्रवक्ष्ये", "pravakṣye", "I shall declare"]]},

12: {"s": [],
     0: [["सर्वद्वाराणि", "sarvadvārāṇi", "all the gates of the body"],
         ["संयम्य", "saṁyamya", "having restrained"]],
     1: [["मनः", "manaḥ", "the mind"],
         ["हृदि", "hṛdi", "in the heart"],
         ["निरुध्य", "nirudhya", "having confined"],
         ["च", "ca", "and"]],
     2: [["मूर्ध्नि", "mūrdhni", "in the head"],
         ["आधाय", "ādhāya", "having fixed"],
         ["आत्मनः", "ātmanaḥ", "of the self"],
         ["प्राणम्", "prāṇam", "the breath"]],
     3: [["आस्थितः", "āsthitaḥ", "established"],
         ["योगधारणाम्", "yogadhāraṇām", "in yogic concentration"]]},

13: {"s": [],
    0: [
    ["ओम्", "om", "Om"], ["इति", "iti", "thus"],
        ["एकाक्षरम्", "ekākṣaram", "the single syllable"], ["ब्रह्म", "brahma", "Brahman"]],
    1: [
    ["व्याहरन्", "vyāharan", "uttering"], ["माम्", "mām", "me"],
        ["अनुस्मरन्", "anusmaran", "remembering"]],
    2: [
    ["यः", "yaḥ", "who"], ["प्रयाति", "prayāti", "departs"],
        ["त्यजन्", "tyajan", "giving up"], ["देहम्", "deham", "the body"]],
    3: [
    ["सः", "saḥ", "he"], ["याति", "yāti", "reaches"], ["परमाम्", "paramām", "the supreme"],
        ["गतिम्", "gatim", "goal"]]
},
14: {"s": [],
     0: [["अनन्यचेताः", "ananyacetāḥ", "with undivided mind"],
         ["सततम्", "satatam", "always"]],
     1: [["यः", "yaḥ", "who"],
         ["माम्", "mām", "me"],
         ["स्मरति", "smarati", "remembers"],
         ["नित्यशः", "nityaśaḥ", "ever"]],
     2: [["तस्य", "tasya", "for him"],
         ["अहम्", "aham", "I"],
         ["सुलभः", "sulabhaḥ", "easy to reach"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     3: [["नित्ययुक्तस्य", "nityayuktasya", "of the ever-yoked"],
         ["योगिनः", "yoginaḥ", "yogi"]]},

15: {"s": [],
    0: [
    ["माम्", "mām", "me"], ["उपेत्य", "upetya", "having reached"],
        ["पुनः", "punaḥ", "again"], ["जन्म", "janma", "birth"]],
    1: [
    ["दुःखालयम्", "duḥkhālayam", "the abode of sorrow"],
        ["अशाश्वतम्", "aśāśvatam", "impermanent"]],
    2: [
    ["न", "na", "not"], ["आप्नुवन्ति", "āpnuvanti", "do they attain"],
        ["महात्मानः", "mahātmānaḥ", "the great souls"]],
    3: [
    ["संसिद्धिम्", "saṁsiddhim", "perfection"], ["परमाम्", "paramām", "the highest"],
        ["गताः", "gatāḥ", "having reached"]]
},
16: {"s": [],
     0: [["आ", "ā", "up to"],
         ["ब्रह्मभुवनात्", "brahmabhuvanāt", "from the world of Brahmā"],
         ["लोकाः", "lokāḥ", "the worlds"]],
     1: [["पुनरावर्तिनः", "punarāvartinaḥ", "returning again"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["माम्", "mām", "me"],
         ["उपेत्य", "upetya", "having reached"],
         ["तु", "tu", "but"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["पुनः", "punaḥ", "again"],
         ["जन्म", "janma", "birth"],
         ["न", "na", "not"],
         ["विद्यते", "vidyate", "there is"]]},

17: {"s": [],
     0: [["सहस्रयुगपर्यन्तम्", "sahasrayugaparyantam", "ending in a thousand yugas"]],
     1: [["अहः", "ahaḥ", "the day"],
         ["यत्", "yat", "which"],
         ["ब्रह्मणः", "brahmaṇaḥ", "of Brahmā"],
         ["विदुः", "viduḥ", "they know"]],
     2: [["रात्रिम्", "rātrim", "the night"],
         ["युगसहस्रान्ताम्", "yugasahasrāntām", "ending in a thousand yugas"]],
     3: [["ते", "te", "they"],
         ["अहोरात्रविदः", "ahorātravidaḥ", "knowers of day and night"],
         ["जनाः", "janāḥ", "people"]]},

18: {"s": [],
     0: [["अव्यक्तात्", "avyaktāt", "from the unmanifest"],
         ["व्यक्तयः", "vyaktayaḥ", "the manifest"],
         ["सर्वाः", "sarvāḥ", "all"]],
     1: [["प्रभवन्ति", "prabhavanti", "arise"],
         ["अहरागमे", "aharāgame", "at the coming of day"]],
     2: [["रात्र्यागमे", "rātryāgame", "at the coming of night"],
         ["प्रलीयन्ते", "pralīyante", "they dissolve"]],
     3: [["तत्र", "tatra", "there"],
         ["एव", "eva", "indeed"],
         ["अव्यक्तसंज्ञके", "avyaktasaṁjñake", "called the unmanifest"]]},

19: {"s": [],
     0: [["भूतग्रामः", "bhūtagrāmaḥ", "the host of beings"],
         ["सः", "saḥ", "this"],
         ["एव", "eva", "very"],
         ["अयम्", "ayam", "this"]],
     1: [["भूत्वा", "bhūtvā", "having arisen"],
         ["भूत्वा", "bhūtvā", "again and again"],
         ["प्रलीयते", "pralīyate", "dissolves"]],
     2: [["रात्र्यागमे", "rātryāgame", "at the coming of night"],
         ["अवशः", "avaśaḥ", "helpless"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     3: [["प्रभवति", "prabhavati", "arises"],
         ["अहरागमे", "aharāgame", "at the coming of day"]]},

20: {"s": [],
     0: [["परः", "paraḥ", "other"],
         ["तस्मात्", "tasmāt", "beyond that"],
         ["तु", "tu", "but"],
         ["भावः", "bhāvaḥ", "existence"],
         ["अन्यः", "anyaḥ", "another"]],
     1: [["अव्यक्तः", "avyaktaḥ", "the unmanifest"],
         ["अव्यक्तात्", "avyaktāt", "from the unmanifest"],
         ["सनातनः", "sanātanaḥ", "eternal"]],
     2: [["यः", "yaḥ", "which"],
         ["सः", "saḥ", "that"],
         ["सर्वेषु", "sarveṣu", "in all"],
         ["भूतेषु", "bhūteṣu", "beings"]],
     3: [["नश्यत्सु", "naśyatsu", "when they perish"],
         ["न", "na", "does not"],
         ["विनश्यति", "vinaśyati", "perish"]]},

21: {"s": [],
    0: [
    ["अव्यक्तः", "avyaktaḥ", "the unmanifest"], ["अक्षरः", "akṣaraḥ", "the imperishable"],
        ["इति", "iti", "thus"], ["उक्तः", "uktaḥ", "is called"]],
    1: [
    ["तम्", "tam", "it"], ["आहुः", "āhuḥ", "they call"],
        ["परमाम्", "paramām", "the supreme"], ["गतिम्", "gatim", "goal"]],
    2: [
    ["यम्", "yam", "which"], ["प्राप्य", "prāpya", "having reached"], ["न", "na", "not"],
        ["निवर्तन्ते", "nivartante", "they return"]],
    3: [
    ["तत्", "tat", "that"], ["धाम", "dhāma", "abode"], ["परमम्", "paramam", "supreme"],
        ["मम", "mama", "my"]]
},
22: {"s": [],
     0: [["पुरुषः", "puruṣaḥ", "the Person"],
         ["सः", "saḥ", "that"],
         ["परः", "paraḥ", "supreme"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     1: [["भक्त्या", "bhaktyā", "by devotion"],
         ["लभ्यः", "labhyaḥ", "attainable"],
         ["तु", "tu", "but"],
         ["अनन्यया", "ananyayā", "by single-pointed"]],
     2: [["यस्य", "yasya", "in whom"],
         ["अन्तःस्थानि", "antaḥsthāni", "dwelling within"],
         ["भूतानि", "bhūtāni", "all beings"]],
     3: [["येन", "yena", "by whom"],
         ["सर्वम्", "sarvam", "all this"],
         ["इदम्", "idam", "this"],
         ["ततम्", "tatam", "is pervaded"]]},

23: {"s": [],
     0: [["यत्र", "yatra", "in which"],
         ["काले", "kāle", "time"],
         ["तु", "tu", "but"],
         ["अनावृत्तिम्", "anāvṛttim", "non-return"]],
     1: [["आवृत्तिम्", "āvṛttim", "return"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["योगिनः", "yoginaḥ", "yogis"]],
     2: [["प्रयाताः", "prayātāḥ", "departing"],
         ["यान्ति", "yānti", "go"],
         ["तम्", "tam", "that"],
         ["कालम्", "kālam", "time"]],
     3: [["वक्ष्यामि", "vakṣyāmi", "I shall declare"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]]},

24: {"s": [],
     0: [["अग्निः", "agniḥ", "fire"],
         ["ज्योतिः", "jyotiḥ", "light"],
         ["अहः", "ahaḥ", "day"],
         ["शुक्लः", "śuklaḥ", "the bright fortnight"]],
     1: [["षण्मासाः", "ṣaṇmāsāḥ", "the six months"],
         ["उत्तरायणम्", "uttarāyaṇam", "the northern course"]],
     2: [["तत्र", "tatra", "by that path"],
         ["प्रयाताः", "prayātāḥ", "departing"],
         ["गच्छन्ति", "gacchanti", "go"]],
     3: [["ब्रह्म", "brahma", "to Brahman"],
         ["ब्रह्मविदः", "brahmavidaḥ", "the knowers of Brahman"],
         ["जनाः", "janāḥ", "people"]]},

25: {"s": [],
     0: [["धूमः", "dhūmaḥ", "smoke"],
         ["रात्रिः", "rātriḥ", "night"],
         ["तथा", "tathā", "also"],
         ["कृष्णः", "kṛṣṇaḥ", "the dark fortnight"]],
     1: [["षण्मासाः", "ṣaṇmāsāḥ", "the six months"],
         ["दक्षिणायनम्", "dakṣiṇāyanam", "the southern course"]],
     2: [["तत्र", "tatra", "by that path"],
         ["चान्द्रमसम्", "cāndramasam", "the lunar"],
         ["ज्योतिः", "jyotiḥ", "light"]],
     3: [["योगी", "yogī", "the yogi"],
         ["प्राप्य", "prāpya", "having attained"],
         ["निवर्तते", "nivartate", "returns"]]},

26: {"s": [],
     0: [["शुक्लकृष्णे", "śuklakṛṣṇe", "the bright and dark"],
         ["गती", "gatī", "paths"],
         ["हि", "hi", "indeed"],
         ["एते", "ete", "these"]],
     1: [["जगतः", "jagataḥ", "of the world"],
         ["शाश्वते", "śāśvate", "eternal"],
         ["मते", "mate", "considered"]],
     2: [["एकया", "ekayā", "by one"],
         ["याति", "yāti", "one goes"],
         ["अनावृत्तिम्", "anāvṛttim", "without return"]],
     3: [["अन्यया", "anyayā", "by the other"],
         ["आवर्तते", "āvartate", "returns"],
         ["पुनः", "punaḥ", "again"]]},

27: {"s": [],
     0: [["न", "na", "not"],
         ["एते", "ete", "these"],
         ["सृती", "sṛtī", "two paths"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["जानन्", "jānan", "knowing"]],
     1: [["योगी", "yogī", "the yogi"],
         ["मुह्यति", "muhyati", "is deluded"],
         ["कश्चन", "kaścana", "any"]],
     2: [["तस्मात्", "tasmāt", "therefore"],
         ["सर्वेषु", "sarveṣu", "in all"],
         ["कालेषु", "kāleṣu", "times"]],
     3: [["योगयुक्तः", "yogayuktaḥ", "united in yoga"],
         ["भव", "bhava", "be"],
         ["अर्जुन", "arjuna", "O Arjuna"]]},

28: {"s": [],
     0: [["वेदेषु", "vedeṣu", "in the Vedas"],
         ["यज्ञेषु", "yajñeṣu", "in sacrifices"],
         ["तपःसु", "tapaḥsu", "in austerities"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     1: [["दानेषु", "dāneṣu", "in gifts"],
         ["यत्", "yat", "which"],
         ["पुण्यफलम्", "puṇyaphalam", "fruit of merit"],
         ["प्रदिष्टम्", "pradiṣṭam", "declared"]],
     2: [["अत्येति", "atyeti", "transcends"],
         ["तत्", "tat", "that"],
         ["सर्वम्", "sarvam", "all"],
         ["इदम्", "idam", "this"],
         ["विदित्वा", "viditvā", "having known"]],
     3: [["योगी", "yogī", "the yogi"],
         ["परम्", "param", "the supreme"],
         ["स्थानम्", "sthānam", "abode"],
         ["उपैति", "upaiti", "reaches"],
         ["च", "ca", "and"],
         ["आद्यम्", "ādyam", "primeval"]]},
}
