# -*- coding: utf-8 -*-
"""padachheda_ch17.py — per-pāda pada-chheda (word splits) for all 28 verses of Gita Chapter 17.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH17_WORDS = {
1: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
    0: [["ये", "ye", "those who"],
        ["शास्त्रविधिम्", "śāstravidhim", "the ordinance of scripture"],
        ["उत्सृज्य", "utsṛjya", "having cast aside"]],
    1: [["यजन्ते", "yajante", "worship"],
        ["श्रद्धया", "śraddhayā", "with faith"],
        ["अन्विताः", "anvitāḥ", "endowed"]],
    2: [["तेषाम्", "teṣām", "of them"],
        ["निष्ठा", "niṣṭhā", "the state"],
        ["तु", "tu", "but"],
        ["का", "kā", "what"],
        ["कृष्ण", "kṛṣṇa", "O Kṛṣṇa"]],
    3: [["सत्त्वम्", "sattvam", "sattva"],
        ["आहो", "āho", "or"],
        ["रजः", "rajaḥ", "rajas"],
        ["तमः", "tamaḥ", "tamas"]]},

2: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["त्रिविधा", "trividhā", "threefold"],
        ["भवति", "bhavati", "is"],
        ["श्रद्धा", "śraddhā", "faith"]],
    1: [["देहिनाम्", "dehinām", "of embodied beings"],
        ["सा", "sā", "that"],
        ["स्वभावजा", "svabhāvajā", "born of one's own nature"]],
    2: [["सात्त्विकी", "sāttvikī", "sāttvic"],
        ["राजसी", "rājasī", "rājasic"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["तामसी", "tāmasī", "tāmasic"],
        ["च", "ca", "and"],
        ["इति", "iti", "thus"],
        ["ताम्", "tām", "that"],
        ["शृणु", "śṛṇu", "hear"]]},

3: {"s": [],
    0: [["सत्त्वानुरूपा", "sattvānurūpā", "according to one's nature"],
        ["सर्वस्य", "sarvasya", "of each"]],
    1: [["श्रद्धा", "śraddhā", "faith"],
        ["भवति", "bhavati", "is"],
        ["भारत", "bhārata", "O Bhārata"]],
    2: [["श्रद्धामयः", "śraddhāmayaḥ", "made of faith"],
        ["अयम्", "ayam", "this"],
        ["पुरुषः", "puruṣaḥ", "man"]],
    3: [["यः", "yaḥ", "who"],
        ["यत्", "yat", "as his"],
        ["श्रद्धः", "śraddhaḥ", "faith"],
        ["सः", "saḥ", "he"],
        ["एव", "eva", "indeed"],
        ["सः", "saḥ", "that"]]},

4: {"s": [],
    0: [["यजन्ते", "yajante", "worship"],
        ["सात्त्विकाः", "sāttvikāḥ", "the sāttvic"],
        ["देवान्", "devān", "the gods"]],
    1: [["यक्षरक्षांसि", "yakṣarakṣāṁsi", "the yakṣas and rākṣasas"],
        ["राजसाः", "rājasāḥ", "the rājasic"]],
    2: [["प्रेतान्", "pretān", "the departed"],
        ["भूतगणान्", "bhūtagaṇān", "the hosts of spirits"],
        ["च", "ca", "and"],
        ["अन्ये", "anye", "others"]],
    3: [["यजन्ते", "yajante", "worship"],
        ["तामसाः", "tāmasāḥ", "the tāmasic"],
        ["जनाः", "janāḥ", "people"]]},

5: {"s": [],
    0: [["अशास्त्रविहितम्", "aśāstravihitam", "not ordained by scripture"],
        ["घोरम्", "ghoram", "terrible"]],
    1: [["तप्यन्ते", "tapyante", "they practise"],
        ["ये", "ye", "who"],
        ["तपः", "tapaḥ", "austerity"],
        ["जनाः", "janāḥ", "people"]],
    2: [["दम्भाहङ्कारसंयुक्ताः", "dambhāhaṅkārasaṁyuktāḥ", "full of hypocrisy and ego"]],
    3: [["कामरागबलान्विताः", "kāmarāgabalānvitāḥ", "impelled by desire and attachment"]]},

6: {"s": [],
    0: [["कर्षयन्तः", "karśayantaḥ", "tormenting"],
        ["शरीरस्थम्", "śarīrastham", "dwelling in the body"]],
    1: [["भूतग्रामम्", "bhūtagrāmam", "the elements of the body"],
        ["अचेतसः", "acetasaḥ", "foolish"]],
    2: [["माम्", "mām", "me"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"],
        ["अन्तःशरीरस्थम्", "antaḥśarīrastham", "dwelling within the body"]],
    3: [["तान्", "tān", "them"],
        ["विद्धि", "viddhi", "know"],
        ["आसुरनिश्चयान्", "āsuraniścayān", "of demoniac resolves"]]},

7: {"s": [],
    0: [["आहारः", "āhāraḥ", "food"],
        ["तु", "tu", "indeed"],
        ["अपि", "api", "also"],
        ["सर्वस्य", "sarvasya", "of each"]],
    1: [["त्रिविधः", "trividhaḥ", "threefold"],
        ["भवति", "bhavati", "is"],
        ["प्रियः", "priyaḥ", "dear"]],
    2: [["यज्ञः", "yajñaḥ", "sacrifice"],
        ["तपः", "tapaḥ", "austerity"],
        ["तथा", "tathā", "and"],
        ["दानम्", "dānam", "gift"]],
    3: [["तेषाम्", "teṣām", "of them"],
        ["भेदम्", "bhedam", "the distinction"],
        ["इमम्", "imam", "this"],
        ["शृणु", "śṛṇu", "hear"]]},

8: {"s": [],
    0: [["आयुः", "āyuḥ", "life"],
        ["सत्त्व", "sattva", "purity"],
        ["बल", "bala", "strength"],
        ["आरोग्य", "ārogya", "health"]],
    1: [["सुख", "sukha", "joy"],
        ["प्रीति", "prīti", "cheer"],
        ["विवर्धनाः", "vivardhanāḥ", "increasing"]],
    2: [["रस्याः", "rasyāḥ", "savoury"],
        ["स्निग्धाः", "snigdhāḥ", "smooth"],
        ["स्थिराः", "sthirāḥ", "firm"],
        ["हृद्याः", "hṛdyāḥ", "agreeable"]],
    3: [["आहाराः", "āhārāḥ", "foods"],
        ["सात्त्विकप्रियाः", "sāttvikapriyāḥ", "dear to the sāttvic"]]},

9: {"s": [],
    0: [["कटु", "kaṭu", "bitter"],
        ["अम्ल", "amla", "sour"],
        ["लवण", "lavaṇa", "salty"],
        ["अत्युष्ण", "atyuṣṇa", "very hot"]],
    1: [["तीक्ष्ण", "tīkṣṇa", "pungent"],
        ["रूक्ष", "rūkṣa", "dry"],
        ["विदाहिनः", "vidāhinaḥ", "burning"]],
    2: [["आहाराः", "āhārāḥ", "foods"],
        ["राजसस्य", "rājasasya", "of the rājasic"],
        ["इष्टाः", "iṣṭāḥ", "dear"]],
    3: [["दुःख", "duḥkha", "pain"],
        ["शोक", "śoka", "grief"],
        ["आमय", "āmaya", "disease"],
        ["प्रदाः", "pradāḥ", "causing"]]},

10: {"s": [],
     0: [["यातयामम्", "yātayāmam", "stale"],
         ["गतरसम्", "gatarasam", "tasteless"]],
     1: [["पूति", "pūti", "putrid"],
         ["पर्युषितम्", "paryuṣitam", "leftover"],
         ["च", "ca", "and"],
         ["यत्", "yat", "which"]],
     2: [["उच्छिष्टम्", "ucchiṣṭam", "leavings"],
         ["अपि", "api", "even"],
         ["च", "ca", "and"],
         ["अमेध्यम्", "amedhyam", "impure"]],
     3: [["भोजनम्", "bhojanam", "food"],
         ["तामसप्रियम्", "tāmasapriyam", "dear to the tāmasic"]]},

11: {"s": [],
     0: [["अफलाकाङ्क्षिभिः", "aphalākāṅkṣibhiḥ", "by those not desiring fruit"],
         ["यज्ञः", "yajñaḥ", "the sacrifice"]],
     1: [["विधिदृष्टः", "vidhidṛṣṭaḥ", "ordained by scripture"],
         ["यः", "yaḥ", "which"],
         ["इज्यते", "ijyate", "is offered"]],
     2: [["यष्टव्यम्", "yaṣṭavyam", "must be performed"],
         ["एव", "eva", "indeed"],
         ["इति", "iti", "thus"],
         ["मनः", "manaḥ", "the mind"]],
     3: [["समाधाय", "samādhāya", "having fixed"],
         ["सः", "saḥ", "that"],
         ["सात्त्विकः", "sāttvikaḥ", "sāttvic"]]},

12: {"s": [],
     0: [["अभिसन्धाय", "abhisandhāya", "seeking"],
         ["तु", "tu", "but"],
         ["फलम्", "phalam", "fruit"]],
     1: [["दम्भार्थम्", "dambhārtham", "for the sake of display"],
         ["अपि", "api", "also"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["यत्", "yat", "which"]],
     2: [["इज्यते", "ijyate", "is offered"],
         ["भरतश्रेष्ठ", "bharataśreṣṭha", "O best of the Bhāratas"]],
     3: [["तम्", "tam", "that"],
         ["यज्ञम्", "yajñam", "sacrifice"],
         ["विद्धि", "viddhi", "know"],
         ["राजसम्", "rājasam", "rājasic"]]},

13: {"s": [],
     0: [["विधिहीनम्", "vidhihīnam", "without rule"],
         ["असृष्टान्नम्", "asṛṣṭānnam", "without food-gifts"]],
     1: [["मन्त्रहीनम्", "mantrahīnam", "without mantra"],
         ["अदक्षिणम्", "adakṣiṇam", "without fees"]],
     2: [["श्रद्धाविरहितम्", "śraddhāvirahitam", "devoid of faith"],
         ["यज्ञम्", "yajñam", "sacrifice"]],
     3: [["तामसम्", "tāmasam", "tāmasic"],
         ["परिचक्षते", "paricakṣate", "they declare"]]},

14: {"s": [],
     0: [["देव", "deva", "of gods"],
         ["द्विज", "dvija", "the twice-born"],
         ["गुरु", "guru", "teachers"],
         ["प्राज्ञ", "prājña", "the wise"],
         ["पूजनम्", "pūjanam", "worship"]],
     1: [["शौचम्", "śaucam", "purity"],
         ["आर्जवम्", "ārjavam", "uprightness"]],
     2: [["ब्रह्मचर्यम्", "brahmacaryam", "chastity"],
         ["अहिंसा", "ahiṁsā", "non-violence"],
         ["च", "ca", "and"]],
     3: [["शारीरम्", "śārīram", "of the body"],
         ["तपः", "tapaḥ", "austerity"],
         ["उच्यते", "ucyate", "is called"]]},

15: {"s": [],
     0: [["अनुद्वेगकरम्", "anudvegakaram", "causing no distress"],
         ["वाक्यम्", "vākyam", "speech"]],
     1: [["सत्यम्", "satyam", "truthful"],
         ["प्रियहितम्", "priyahitam", "pleasant and beneficial"],
         ["च", "ca", "and"],
         ["यत्", "yat", "which"]],
     2: [["स्वाध्यायाभ्यसनम्", "svādhyāyābhyasanam", "the regular study of scripture"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     3: [["वाङ्मयम्", "vāṅmayam", "of speech"],
         ["तपः", "tapaḥ", "austerity"],
         ["उच्यते", "ucyate", "is called"]]},

16: {"s": [],
     0: [["मनःप्रसादः", "manaḥprasādaḥ", "serenity of mind"],
         ["सौम्यत्वम्", "saumyatvam", "gentleness"]],
     1: [["मौनम्", "maunam", "silence"],
         ["आत्मविनिग्रहः", "ātmavinigrahaḥ", "self-control"]],
     2: [["भावसंशुद्धिः", "bhāvasaṁśuddhiḥ", "purity of heart"],
         ["इति", "iti", "thus"],
         ["एतत्", "etat", "this"]],
     3: [["तपः", "tapaḥ", "austerity"],
         ["मानसम्", "mānasam", "of the mind"],
         ["उच्यते", "ucyate", "is called"]]},

17: {"s": [],
     0: [["श्रद्धया", "śraddhayā", "with faith"],
         ["परया", "parayā", "supreme"],
         ["तप्तम्", "taptam", "performed"]],
     1: [["तपः", "tapaḥ", "austerity"],
         ["तत्", "tat", "that"],
         ["त्रिविधम्", "trividham", "threefold"],
         ["नरैः", "naraiḥ", "by men"]],
     2: [["अफलाकाङ्क्षिभिः", "aphalākāṅkṣibhiḥ", "without desiring fruit"],
         ["युक्तैः", "yuktaiḥ", "by the steadfast"]],
     3: [["सात्त्विकम्", "sāttvikam", "sāttvic"],
         ["परिचक्षते", "paricakṣate", "is declared"]]},

18: {"s": [],
     0: [["सत्कार", "satkāra", "for honour"],
         ["मान", "māna", "reverence"],
         ["पूजार्थम्", "pūjārtham", "for worship"]],
     1: [["तपः", "tapaḥ", "austerity"],
         ["दम्भेन", "dambhena", "with hypocrisy"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["यत्", "yat", "which"]],
     2: [["क्रियते", "kriyate", "is performed"],
         ["तत्", "tat", "that"],
         ["इह", "iha", "here"],
         ["प्रोक्तम्", "proktam", "declared"]],
     3: [["राजसम्", "rājasam", "rājasic"],
         ["चलम्", "calam", "unstable"],
         ["अध्रुवम्", "adhruvam", "transitory"]]},

19: {"s": [],
     0: [["मूढग्राहेण", "mūḍhagrāheṇa", "with foolish obstinacy"],
         ["आत्मनः", "ātmanaḥ", "of the self"]],
     1: [["यत्", "yat", "which"],
         ["पीडया", "pīḍayā", "with torment"],
         ["क्रियते", "kriyate", "is performed"],
         ["तपः", "tapaḥ", "austerity"]],
     2: [["परस्य", "parasya", "of another"],
         ["उत्सादनार्थम्", "utsādanārtham", "for the ruin"]],
     3: [["वा", "vā", "or"],
         ["तत्", "tat", "that"],
         ["तामसम्", "tāmasam", "tāmasic"],
         ["उदाहृतम्", "udāhṛtam", "is declared"]]},

20: {"s": [],
     0: [["दातव्यम्", "dātavyam", "ought to be given"],
         ["इति", "iti", "thus"],
         ["यत्", "yat", "which"],
         ["दानम्", "dānam", "gift"]],
     1: [["दीयते", "dīyate", "is given"],
         ["अनुपकारिणे", "anupakāriṇe", "to one who can do nothing in return"]],
     2: [["देशे", "deśe", "at the place"],
         ["काले", "kāle", "at the time"],
         ["च", "ca", "and"],
         ["पात्रे", "pātre", "to a worthy person"],
         ["च", "ca", "and"]],
     3: [["तत्", "tat", "that"],
         ["दानम्", "dānam", "gift"],
         ["सात्त्विकम्", "sāttvikam", "sāttvic"],
         ["स्मृतम्", "smṛtam", "is deemed"]]},

21: {"s": [],
     0: [["यत्", "yat", "which"],
         ["तु", "tu", "but"],
         ["प्रत्युपकारार्थम्", "pratyupakārārtham", "expecting a return"]],
     1: [["फलम्", "phalam", "fruit"],
         ["उद्दिश्य", "uddiśya", "seeking"],
         ["वा", "vā", "or"],
         ["पुनः", "punaḥ", "again"]],
     2: [["दीयते", "dīyate", "is given"],
         ["च", "ca", "and"],
         ["परिक्लिष्टम्", "parikliṣṭam", "reluctantly"]],
     3: [["तत्", "tat", "that"],
         ["दानम्", "dānam", "gift"],
         ["राजसम्", "rājasam", "rājasic"],
         ["स्मृतम्", "smṛtam", "is deemed"]]},

22: {"s": [],
     0: [["अदेशकाले", "adeśakāle", "at the wrong place and time"],
         ["यत्", "yat", "which"],
         ["दानम्", "dānam", "gift"]],
     1: [["अपात्रेभ्यः", "apātrebhyaḥ", "to unworthy persons"],
         ["च", "ca", "and"],
         ["दीयते", "dīyate", "is given"]],
     2: [["असत्कृतम्", "asatkṛtam", "without respect"],
         ["अवज्ञातम्", "avajñātam", "with contempt"]],
     3: [["तत्", "tat", "that"],
         ["तामसम्", "tāmasam", "tāmasic"],
         ["उदाहृतम्", "udāhṛtam", "is declared"]]},

23: {"s": [],
     0: [["ओम्", "om", "Om"],
         ["तत्", "tat", "Tat"],
         ["सत्", "sat", "Sat"],
         ["इति", "iti", "thus"],
         ["निर्देशः", "nirdeśaḥ", "the designation"]],
     1: [["ब्रह्मणः", "brahmaṇaḥ", "of Brahman"],
         ["त्रिविधः", "trividhaḥ", "threefold"],
         ["स्मृतः", "smṛtaḥ", "is remembered"]],
     2: [["ब्राह्मणाः", "brāhmaṇāḥ", "the brāhmaṇas"],
         ["तेन", "tena", "by that"],
         ["वेदाः", "vedāḥ", "the Vedas"],
         ["च", "ca", "and"]],
     3: [["यज्ञाः", "yajñāḥ", "the sacrifices"],
         ["च", "ca", "and"],
         ["विहिताः", "vihitāḥ", "ordained"],
         ["पुरा", "purā", "of old"]]},

24: {"s": [],
     0: [["तस्मात्", "tasmāt", "therefore"],
         ["ओम्", "om", "Om"],
         ["इति", "iti", "thus"],
         ["उदाहृत्य", "udāhṛtya", "having uttered"]],
     1: [["यज्ञदानतपःक्रियाः", "yajñadānatapaḥkriyāḥ", "the acts of sacrifice, gift and austerity"]],
     2: [["प्रवर्तन्ते", "pravartante", "are begun"],
         ["विधानोक्ताः", "vidhānoktāḥ", "ordained by rule"]],
     3: [["सततम्", "satatam", "ever"],
         ["ब्रह्मवादिनाम्", "brahmavādinām", "of the knowers of Brahman"]]},

25: {"s": [],
    0: [
    ["तत्", "tat", "Tat"], ["इति", "iti", "thus"],
        ["अनभिसन्धाय", "anabhisandhāya", "without seeking"]],
    1: [
    ["फलम्", "phalam", "fruit"],
        ["यज्ञतपःक्रियाः", "yajñatapaḥkriyāḥ", "the acts of sacrifice and austerity"]],
    2: [
    ["दानक्रियाः", "dānakriyāḥ", "the acts of giving"], ["च", "ca", "and"],
        ["विविधाः", "vividhāḥ", "various"]],
    3: [
    ["क्रियन्ते", "kriyante", "are performed"],
        ["मोक्षकाङ्क्षिभिः", "mokṣakāṅkṣibhiḥ", "by seekers of liberation"]]
},
26: {"s": [],
     0: [["सद्भावे", "sadbhāve", "in the sense of reality"],
         ["साधुभावे", "sādhubhāve", "in the sense of goodness"],
         ["च", "ca", "and"]],
     1: [["सत्", "sat", "Sat"],
         ["इति", "iti", "thus"],
         ["एतत्", "etat", "this"],
         ["प्रयुज्यते", "prayujyate", "is used"]],
     2: [["प्रशस्ते", "praśaste", "in auspicious"],
         ["कर्मणि", "karmaṇi", "works"],
         ["तथा", "tathā", "also"]],
     3: [["सत्", "sat", "Sat"],
         ["शब्दः", "śabdaḥ", "the word"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["युज्यते", "yujyate", "is used"]]},

27: {"s": [],
     0: [["यज्ञे", "yajñe", "in sacrifice"],
         ["तपसि", "tapasi", "in austerity"],
         ["दाने", "dāne", "in giving"],
         ["च", "ca", "and"]],
     1: [["स्थितिः", "sthitiḥ", "steadfastness"],
         ["सत्", "sat", "Sat"],
         ["इति", "iti", "thus"],
         ["च", "ca", "and"],
         ["उच्यते", "ucyate", "is called"]],
     2: [["कर्म", "karma", "action"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["तदर्थीयम्", "tadarthīyam", "for the sake of that"]],
     3: [["सत्", "sat", "Sat"],
         ["इति", "iti", "thus"],
         ["एव", "eva", "indeed"],
         ["अभिधीयते", "abhidhīyate", "is called"]]},

28: {"s": [],
     0: [["अश्रद्धया", "aśraddhayā", "without faith"],
         ["हुतम्", "hutam", "offered"]],
     1: [["दत्तम्", "dattam", "given"],
         ["तपः", "tapaḥ", "austerity"],
         ["तप्तम्", "taptam", "performed"],
         ["कृतम्", "kṛtam", "done"],
         ["च", "ca", "and"],
         ["यत्", "yat", "which"]],
     2: [["असत्", "asat", "Asat"],
         ["इति", "iti", "thus"],
         ["उच्यते", "ucyate", "is called"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     3: [["न", "na", "not"],
         ["च", "ca", "and"],
         ["तत्", "tat", "that"],
         ["प्रेत्य", "pretya", "after death"],
         ["न", "na", "nor"],
         ["उ", "u", "indeed"],
         ["इह", "iha", "here"]]},
}
