# -*- coding: utf-8 -*-
"""padachheda_ch1.py — per-pāda pada-chheda (word splits) for all 47 verses of Gita Chapter 1.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
"""

GITA_CH1_WORDS = {
1: {"s": [["धृतराष्ट्र", "dhṛtarāṣṭra", "Dhṛtarāṣṭra (the blind king)"],
          ["उवाच", "uvāca", "said"]],
    0: [["धर्म", "dharma", "righteousness, sacred duty"],
        ["क्षेत्रे", "kṣetre", "on the field"],
        ["कुरु", "kuru", "of the Kurus", "कुरुको", "कुरुके"],
        ["क्षेत्रे", "kṣetre", "on the field"]],
    1: [["समवेता", "samavetāḥ", "assembled"],
        ["युयुत्सवः", "yuyutsavaḥ", "desiring to fight"]],
    2: [["मामकाः", "māmakāḥ", "my people"],
        ["पाण्डवाः", "pāṇḍavāḥ", "the sons of Pāṇḍu"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["किम्", "kim", "what"],
        ["अकुर्वत", "akurvata", "did they do"],
        ["सञ्जय", "sañjaya", "O Sañjaya"]]},

2: {"s": [["सञ्जय", "sañjaya", "Sañjaya (the narrator)"],
          ["उवाच", "uvāca", "said"]],
    0: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
        ["तु", "tu", "but, indeed"],
        ["पाण्डव", "pāṇḍava", "of the Pāṇḍavas"],
        ["अनीकम्", "anīkam", "the army"]],
    1: [["व्यूढम्", "vyūḍham", "arrayed, drawn up"],
        ["दुर्योधनः", "duryodhanaḥ", "Duryodhana"],
        ["तदा", "tadā", "then"]],
    2: [["आचार्यम्", "ācāryam", "the teacher"],
        ["उपसङ्गम्य", "upasaṅgamya", "having approached"]],
    3: [["राजा", "rājā", "the king"],
        ["वचनम्", "vacanam", "words"],
        ["अब्रवीत्", "abravīt", "spoke, said"]]},

3: {"s": [],
    0: [["पश्य", "paśya", "behold"],
        ["एताम्", "etām", "this"],
        ["पाण्डु", "pāṇḍu", "of Pāṇḍu"],
        ["पुत्राणाम्", "putrāṇām", "of the sons"]],
    1: [["आचार्य", "ācārya", "O teacher"],
        ["महतीम्", "mahatīm", "great"],
        ["चमूम्", "camūm", "army"]],
    2: [["व्यूढाम्", "vyūḍhām", "arrayed"],
        ["द्रुपद", "drupada", "of Drupada"],
        ["पुत्रेण", "putreṇa", "by the son"]],
    3: [["तव", "tava", "your"],
        ["शिष्येण", "śiṣyeṇa", "by the disciple"],
        ["धीमता", "dhīmatā", "wise, intelligent"]]},

4: {"s": [],
    0: [["अत्र", "atra", "here"],
        ["शूराः", "śūrāḥ", "heroes"],
        ["महा", "mahā", "great"],
        ["इष्वासाः", "iṣvāsāḥ", "archers"]],
    1: [["भीम", "bhīma", "to Bhīma"],
        ["अर्जुन", "arjuna", "and Arjuna"],
        ["समाः", "samāḥ", "equal"],
        ["युधि", "yudhi", "in war"]],
    2: [["युयुधानः", "yuyudhānaḥ", "Yuyudhāna (Sātyaki)"],
        ["विराटः", "virāṭaḥ", "Virāṭa (king of Matsya)"],
        ["च", "ca", "and"]],
    3: [["द्रुपदः", "drupadaḥ", "Drupada"],
        ["च", "ca", "and"],
        ["महा", "mahā", "great"],
        ["रथः", "rathaḥ", "chariot-warrior"]]},

5: {"s": [],
    0: [["धृष्टकेतुः", "dhṛṣṭaketuḥ", "Dhṛṣṭaketu"],
        ["चेकितानः", "cekitānaḥ", "Cekitāna"]],
    1: [["काशीराजः", "kāśīrājaḥ", "king of Kāśī"],
        ["च", "ca", "and"],
        ["वीर्यवान्", "vīryavān", "valiant"]],
    2: [["पुरुजित्", "purujit", "Purujit"],
        ["कुन्तिभोजः", "kuntibhojaḥ", "Kuntibhoja"],
        ["च", "ca", "and"]],
    3: [["शैब्यः", "śaibyaḥ", "Śaibya"],
        ["च", "ca", "and"],
        ["नरपुङ्गवः", "narapuṅgavaḥ", "bull among men"]]},

6: {"s": [],
    0: [["युधामन्युः", "yudhāmanyuḥ", "Yudhāmanyu"],
        ["च", "ca", "and"],
        ["विक्रान्तः", "vikrāntaḥ", "mighty"]],
    1: [["उत्तमौजाः", "uttamaujāḥ", "Uttamaujas"],
        ["च", "ca", "and"],
        ["वीर्यवान्", "vīryavān", "powerful"]],
    2: [["सौभद्रः", "saubhadraḥ", "the son of Subhadrā (Abhimanyu)"],
        ["द्रौपदेयाः", "draupadeyāḥ", "the sons of Draupadī"],
        ["च", "ca", "and"]],
    3: [["सर्व", "sarva", "all"],
        ["एव", "eva", "indeed"],
        ["महारथाः", "mahārathāḥ", "great chariot-warriors"]]},

7: {"s": [],
    0: [["अस्माकम्", "asmākam", "of us"],
        ["तु", "tu", "but"],
        ["विशिष्टाः", "viśiṣṭāḥ", "distinguished"],
        ["ये", "ye", "who"]],
    1: [["तान्", "tān", "them"],
        ["निबोध", "nibodha", "know, hear"],
        ["द्विज", "dvija", "of the twice-born"],
        ["उत्तम", "uttama", "O best"]],
    2: [["नायकाः", "nāyakāḥ", "leaders"],
        ["मम", "mama", "my"],
        ["सैन्यस्य", "sainyasya", "of the army"]],
    3: [["संज्ञा", "saṁjñā", "information"],
        ["अर्थम्", "artham", "for the sake of"],
        ["तान्", "tān", "them"],
        ["ब्रवीमि", "bravīmi", "I tell"],
        ["ते", "te", "to you"]]},

8: {"s": [],
    0: [["भवान्", "bhavān", "you"],
        ["भीष्मः", "bhīṣmaḥ", "Bhīṣma"],
        ["च", "ca", "and"],
        ["कर्णः", "karṇaḥ", "Karṇa"],
        ["च", "ca", "and"]],
    1: [["कृपः", "kṛpaḥ", "Kṛpa"],
        ["च", "ca", "and"],
        ["समितिञ्जयः", "samitiñjayaḥ", "conqueror in battle"]],
    2: [["अश्वत्थामा", "aśvatthāmā", "Aśvatthāmā"],
        ["विकर्णः", "vikarṇaḥ", "Vikarṇa"],
        ["च", "ca", "and"]],
    3: [["सौमदत्तिः", "saumadattiḥ", "son of Somadatta (Bhūriśravā)"],
        ["तथा", "tathā", "likewise"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]]},

9: {"s": [],
    0: [["अन्ये", "anye", "others"],
        ["च", "ca", "and"],
        ["बहवः", "bahavaḥ", "many"],
        ["शूराः", "śūrāḥ", "heroes"]],
    1: [["मत्", "mat", "my"],
        ["अर्थे", "arthe", "for the sake of"],
        ["त्यक्तजीविताः", "tyaktajīvitāḥ", "having given up their lives"]],
    2: [["नाना", "nānā", "various"],
        ["शस्त्र", "śastra", "weapons"],
        ["प्रहरणाः", "praharaṇāḥ", "armed with"]],
    3: [["सर्वे", "sarve", "all"],
        ["युद्ध", "yuddha", "in war"],
        ["विशारदाः", "viśāradāḥ", "skilled"]]},

10: {"s": [],
    0: [["अपर्याप्तम्", "aparyāptam", "insufficient, limited"],
        ["तत्", "tat", "that"],
        ["अस्माकम्", "asmākam", "our"]],
    1: [["बलम्", "balam", "strength"],
        ["भीष्म", "bhīṣma", "by Bhīṣma"],
        ["अभिरक्षितम्", "abhirakṣitam", "protected"]],
    2: [["पर्याप्तम्", "paryāptam", "sufficient"],
        ["तु", "tu", "but"],
        ["इदम्", "idam", "this"],
        ["एतेषाम्", "eteṣām", "of these"]],
    3: [["बलम्", "balam", "strength"],
        ["भीम", "bhīma", "by Bhīma"],
        ["अभिरक्षितम्", "abhirakṣitam", "protected"]]},

11: {"s": [],
    0: [["अयनेषु", "ayaneṣu", "in the approaches"],
        ["च", "ca", "and"],
        ["सर्वेषु", "sarveṣu", "in all"]],
    1: [["यथा", "yathā", "according to"],
        ["भागम्", "bhāgam", "their divisions"],
        ["अवस्थिताः", "avasthitāḥ", "stationed"]],
    2: [["भीष्मम्", "bhīṣmam", "Bhīṣma"],
        ["एव", "eva", "alone"],
        ["अभिरक्षन्तु", "abhirakṣantu", "let them protect"]],
    3: [["भवन्तः", "bhavantaḥ", "you all"],
        ["सर्व", "sarva", "all"],
        ["एव", "eva", "indeed"],
        ["हि", "hi", "verily"]]},

12: {"s": [],
    0: [["तस्य", "tasya", "his (Duryodhana's)"],
        ["सञ्जनयन्", "sañjanayan", "causing, giving"],
        ["हर्षम्", "harṣam", "joy"]],
    1: [["कुरु", "kuru", "of the Kurus", "कुरुको", "कुरुके"],
        ["वृद्धः", "vṛddhaḥ", "the elder"],
        ["पितामहः", "pitāmahaḥ", "the grandsire"]],
    2: [["सिंह", "siṁha", "lion's"],
        ["नादम्", "nādam", "roar"],
        ["विनद्य", "vinadya", "having uttered"],
        ["उच्चैः", "uccaiḥ", "loudly"]],
    3: [["शङ्खम्", "śaṅkham", "the conch"],
        ["दध्मौ", "dadhmau", "blew"],
        ["प्रतापवान्", "pratāpavān", "the glorious"]]},

13: {"s": [],
    0: [["ततः", "tataḥ", "then"],
        ["शङ्खाः", "śaṅkhāḥ", "conches"],
        ["च", "ca", "and"],
        ["भेर्यः", "bheryaḥ", "kettledrums"],
        ["च", "ca", "and"]],
    1: [["पणव", "paṇava", "tabors"],
        ["आनक", "ānaka", "kettledrums"],
        ["गोमुखाः", "gomukhāḥ", "horn-trumpets"]],
    2: [["सहसा", "sahasā", "suddenly"],
        ["एव", "eva", "indeed"],
        ["अभ्यहन्यन्त", "abhyahanyanta", "were struck"]],
    3: [["सः", "saḥ", "that"],
        ["शब्दः", "śabdaḥ", "sound"],
        ["तुमुलः", "tumulaḥ", "tumultuous"],
        ["अभवत्", "abhavat", "became"]]},

14: {"s": [],
    0: [["ततः", "tataḥ", "then"],
        ["श्वेतैः", "śvetaiḥ", "with white"],
        ["हयैः", "hayaiḥ", "horses"],
        ["युक्ते", "yukte", "yoked"]],
    1: [["महति", "mahati", "in the great"],
        ["स्यन्दने", "syandane", "chariot"],
        ["स्थितौ", "sthitau", "stationed"]],
    2: [["माधवः", "mādhavaḥ", "Mādhava (Kṛṣṇa)"],
        ["पाण्डवः", "pāṇḍavaḥ", "the son of Pāṇḍu (Arjuna)"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["दिव्यौ", "divyau", "divine"],
        ["शङ्खौ", "śaṅkhau", "conches"],
        ["प्रदध्मतुः", "pradadhmatuḥ", "blew"]]},

15: {"s": [],
    0: [["पाञ्चजन्यम्", "pāñcajanyam", "Pāñcajanya (Kṛṣṇa's conch)"],
        ["हृषीकेशः", "hṛṣīkeśaḥ", "Hṛṣīkeśa (Kṛṣṇa)"]],
    1: [["देवदत्तम्", "devadattam", "Devadatta (Arjuna's conch)"],
        ["धनञ्जयः", "dhanañjayaḥ", "Dhanañjaya (Arjuna)"]],
    2: [["पौण्ड्रम्", "pauṇḍram", "Pauṇḍra (Bhīma's conch)"],
        ["दध्मौ", "dadhmau", "blew"],
        ["महा", "mahā", "great"],
        ["शङ्खम्", "śaṅkham", "the conch"]],
    3: [["भीम", "bhīma", "terrific"],
        ["कर्मा", "karmā", "deeds (doer of)"],
        ["वृकोदरः", "vṛkodaraḥ", "Vṛkodara (Bhīma)"]]},

16: {"s": [],
    0: [["अनन्तविजयम्", "anantavijayam", "Anantavijaya (Yudhiṣṭhira's conch)"],
        ["राजा", "rājā", "the king"]],
    1: [["कुन्ती", "kuntī", "of Kuntī"],
        ["पुत्रः", "putraḥ", "the son"],
        ["युधिष्ठिरः", "yudhiṣṭhiraḥ", "Yudhiṣṭhira"]],
    2: [["नकुलः", "nakulaḥ", "Nakula"],
        ["सहदेवः", "sahadevaḥ", "Sahadeva"],
        ["च", "ca", "and"]],
    3: [["सुघोषमणिपुष्पकौ", "sughoṣamaṇipuṣpakau", "Sughoṣa and Maṇipuṣpaka (their conches)"]]},

17: {"s": [],
    0: [["काश्यः", "kāśyaḥ", "king of Kāśī"],
        ["च", "ca", "and"],
        ["परम", "parama", "supreme"],
        ["इष्वासः", "iṣvāsaḥ", "archer"]],
    1: [["शिखण्डी", "śikhaṇḍī", "Śikhaṇḍī"],
        ["च", "ca", "and"],
        ["महा", "mahā", "great"],
        ["रथः", "rathaḥ", "chariot-warrior"]],
    2: [["धृष्टद्युम्नः", "dhṛṣṭadyumnaḥ", "Dhṛṣṭadyumna"],
        ["विराटः", "virāṭaḥ", "Virāṭa"],
        ["च", "ca", "and"]],
    3: [["सात्यकिः", "sātyakiḥ", "Sātyaki"],
        ["च", "ca", "and"],
        ["अपराजितः", "aparājitaḥ", "unconquered"]]},

18: {"s": [],
    0: [["द्रुपदः", "drupadaḥ", "Drupada"],
        ["द्रौपदेयाः", "draupadeyāḥ", "the sons of Draupadī"],
        ["च", "ca", "and"]],
    1: [["सर्वशः", "sarvaśaḥ", "all, one and all"],
        ["पृथिवी", "pṛthivī", "of the earth"],
        ["पते", "pate", "O lord"]],
    2: [["सौभद्रः", "saubhadraḥ", "the son of Subhadrā"],
        ["च", "ca", "and"],
        ["महा", "mahā", "mighty"],
        ["बाहुः", "bāhuḥ", "armed"]],
    3: [["शङ्खान्", "śaṅkhān", "conches"],
        ["दध्मुः", "dadhmuḥ", "blew"],
        ["पृथक् पृथक्", "pṛthak pṛthak", "each separately"]]},

19: {"s": [],
    0: [["सः", "saḥ", "that"],
        ["घोषः", "ghoṣaḥ", "clamour, sound"],
        ["धार्तराष्ट्राणाम्", "dhārtarāṣṭrāṇām", "of the sons of Dhṛtarāṣṭra"]],
    1: [["हृदयानि", "hṛdayāni", "hearts"],
        ["व्यदारयत्", "vyadārayat", "rent, shattered"]],
    2: [["नभः", "nabhaḥ", "the sky"],
        ["च", "ca", "and"],
        ["पृथिवीम्", "pṛthivīm", "the earth"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["तुमुलः", "tumulaḥ", "tumultuous"],
        ["व्यनुनादयन्", "vyanunādayan", "resounding through"]]},

20: {"s": [],
    0: [["अथ", "atha", "then"],
        ["व्यवस्थितान्", "vyavasthitān", "stationed"],
        ["दृष्ट्वा", "dṛṣṭvā", "having seen"]],
    1: [["धार्तराष्ट्रान्", "dhārtarāṣṭrān", "the sons of Dhṛtarāṣṭra"],
        ["कपि", "kapi", "ape"],
        ["ध्वजः", "dhvajaḥ", "bannered"]],
    2: [["प्रवृत्ते", "pravṛtte", "about to begin"],
        ["शस्त्र", "śastra", "of weapons"],
        ["सम्पाते", "sampāte", "in the clash"]],
    3: [["धनुः", "dhanuḥ", "the bow"],
        ["उद्यम्य", "udyamya", "having raised"],
        ["पाण्डवः", "pāṇḍavaḥ", "the son of Pāṇḍu (Arjuna)"]]},

21: {"s": [["अर्जुन", "arjuna", "Arjuna"],
          ["उवाच", "uvāca", "said"]],
    0: [["हृषीकेशम्", "hṛṣīkeśam", "to Hṛṣīkeśa (Kṛṣṇa)"],
        ["तदा", "tadā", "then"],
        ["वाक्यम्", "vākyam", "words"]],
    1: [["इदम्", "idam", "this"],
        ["आह", "āha", "spoke"],
        ["महीपते", "mahīpate", "O lord of the earth"]],
    2: [["सेनयोः", "senayoḥ", "of the two armies"],
        ["उभयोः", "ubhayoḥ", "of both"],
        ["मध्ये", "madhye", "in the midst"]],
    3: [["रथम्", "ratham", "the chariot"],
        ["स्थापय", "sthāpaya", "place"],
        ["मे", "me", "my"],
        ["अच्युत", "acyuta", "O infallible one"]]},

22: {"s": [],
    0: [["यावत्", "yāvat", "so that"],
        ["एतान्", "etān", "these"],
        ["निरीक्षे", "nirīkṣe", "I may see"],
        ["अहम्", "aham", "I"]],
    1: [["योद्धुम्", "yoddhum", "to fight"],
        ["कामान्", "kāmān", "desiring"],
        ["अवस्थितान्", "avasthitān", "stationed"]],
    2: [["कैः", "kaiḥ", "with whom"],
        ["मया", "mayā", "by me"],
        ["सह", "saha", "with"],
        ["योद्धव्यम्", "yoddhavyam", "to be fought"]],
    3: [["अस्मिन्", "asmin", "in this"],
        ["रण", "raṇa", "of war"],
        ["समुद्यमे", "samudyame", "in the enterprise"]]},

23: {"s": [],
    0: [["योत्स्यमानान्", "yotsyamānān", "those who will fight"],
        ["अवेक्षे", "avekṣe", "I wish to see"],
        ["अहम्", "aham", "I"]],
    1: [["ये", "ye", "who"],
        ["एते", "ete", "these"],
        ["अत्र", "atra", "here"],
        ["समागताः", "samāgatāḥ", "assembled"]],
    2: [["धार्तराष्ट्रस्य", "dhārtarāṣṭrasya", "of the son of Dhṛtarāṣṭra (Duryodhana)"],
        ["दुर्बुद्धेः", "durbuddheḥ", "of the evil-minded"]],
    3: [["युद्धे", "yuddhe", "in battle"],
        ["प्रिय", "priya", "to please"],
        ["चिकीर्षवः", "cikīrṣavaḥ", "desiring"]]},

24: {"s": [["सञ्जय", "sañjaya", "Sañjaya"],
          ["उवाच", "uvāca", "said"]],
    0: [["एवम्", "evam", "thus"],
        ["उक्तः", "uktaḥ", "addressed"],
        ["हृषीकेशः", "hṛṣīkeśaḥ", "Hṛṣīkeśa (Kṛṣṇa)"]],
    1: [["गुडाकेशेन", "guḍākeśena", "by Guḍākeśa (Arjuna)"],
        ["भारत", "bhārata", "O descendant of Bharata"]],
    2: [["सेनयोः", "senayoḥ", "of the two armies"],
        ["उभयोः", "ubhayoḥ", "of both"],
        ["मध्ये", "madhye", "in the midst"]],
    3: [["स्थापयित्वा", "sthāpayitvā", "having placed"],
        ["रथ", "ratha", "of chariots"],
        ["उत्तमम्", "uttamam", "the best"]]},

25: {"s": [],
    0: [["भीष्म", "bhīṣma", "Bhīṣma"],
        ["द्रोण", "droṇa", "Droṇa"],
        ["प्रमुखतः", "pramukhataḥ", "before (headed by)"]],
    1: [["सर्वेषाम्", "sarveṣām", "of all"],
        ["च", "ca", "and"],
        ["मही", "mahī", "of the earth"],
        ["क्षिताम्", "kṣitām", "the rulers"]],
    2: [["उवाच", "uvāca", "said"],
        ["पार्थ", "pārtha", "O Pārtha (Arjuna)"],
        ["पश्य", "paśya", "behold"],
        ["एतान्", "etān", "these"]],
    3: [["समवेतान्", "samavetān", "assembled"],
        ["कुरून्", "kurūn", "the Kurus"],
        ["इति", "iti", "thus"]]},

26: {"s": [],
    0: [["तत्र", "tatra", "there"],
        ["अपश्यत्", "apaśyat", "saw"],
        ["स्थितान्", "sthitān", "stationed"],
        ["पार्थः", "pārthaḥ", "Arjuna"]],
    1: [["पितॄन्", "pitṝn", "fathers"],
        ["अथ", "atha", "then"],
        ["पितामहान्", "pitāmahān", "grandfathers"]],
    2: [["आचार्यान्", "ācāryān", "teachers"],
        ["मातुलान्", "mātulān", "maternal uncles"],
        ["भ्रातॄन्", "bhrātṝn", "brothers"]],
    3: [["पुत्रान्", "putrān", "sons"],
        ["पौत्रान्", "pautrān", "grandsons"],
        ["सखीन्", "sakhīn", "friends"],
        ["तथा", "tathā", "also"]]},

27: {"s": [],
    0: [["श्वशुरान्", "śvaśurān", "fathers-in-law"],
        ["सु", "su", "good"],
        ["हृदः", "hṛdaḥ", "hearted (well-wishers)"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    1: [["सेनयोः", "senayoḥ", "of the armies"],
        ["उभयोः", "ubhayoḥ", "of both"],
        ["अपि", "api", "also"]],
    2: [["तान्", "tān", "them"],
        ["समीक्ष्य", "samīkṣya", "having seen"],
        ["सः", "saḥ", "he"],
        ["कौन्तेयः", "kaunteyaḥ", "the son of Kuntī"]],
    3: [["सर्वान्", "sarvān", "all"],
        ["बन्धून्", "bandhūn", "kinsmen"],
        ["अवस्थितान्", "avasthitān", "stationed"]]},

28: {"s": [["अर्जुन", "arjuna", "Arjuna"],
          ["उवाच", "uvāca", "said"]],
    0: [["कृपया", "kṛpayā", "with compassion"],
        ["परया", "parayā", "profound"],
        ["आविष्टः", "āviṣṭaḥ", "overcome"]],
    1: [["विषीदन्", "viṣīdan", "grieving"],
        ["इदम्", "idam", "this"],
        ["अब्रवीत्", "abravīt", "spoke"]],
    2: [["दृष्ट्वा", "dṛṣṭvā", "having seen"],
        ["इमम्", "imam", "this"],
        ["स्व", "sva", "own"],
        ["जनम्", "janam", "people"],
        ["कृष्ण", "kṛṣṇa", "O Kṛṣṇa"]],
    3: [["युयुत्सुम्", "yuyutsum", "eager for battle"],
        ["समुपस्थितम्", "samupasthitam", "standing before"]]},

29: {"s": [],
    0: [["सीदन्ति", "sīdanti", "fail, sink"],
        ["मम", "mama", "my"],
        ["गात्राणि", "gātrāṇi", "limbs"]],
    1: [["मुखम्", "mukham", "mouth"],
        ["च", "ca", "and"],
        ["परिशुष्यति", "pariśuṣyati", "dries up"]],
    2: [["वेपथुः", "vepathuḥ", "trembling"],
        ["च", "ca", "and"],
        ["शरीरे", "śarīre", "in the body"],
        ["मे", "me", "my"]],
    3: [["रोम", "roma", "hair"],
        ["हर्षः", "harṣaḥ", "standing on end"],
        ["च", "ca", "and"],
        ["जायते", "jāyate", "arises"]]},

30: {"s": [],
    0: [["गाण्डीवम्", "gāṇḍīvam", "the bow Gāṇḍīva"],
        ["स्रंसते", "sraṁsate", "slips"],
        ["हस्तात्", "hastāt", "from the hand"]],
    1: [["त्वक्", "tvak", "the skin"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"],
        ["परिदह्यते", "paridahyate", "burns"]],
    2: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["शक्नोमि", "śaknomi", "am able"],
        ["अवस्थातुम्", "avasthātum", "to stand"]],
    3: [["भ्रमति", "bhramati", "reels"],
        ["इव", "iva", "as it were"],
        ["च", "ca", "and"],
        ["मे", "me", "my"],
        ["मनः", "manaḥ", "mind"]]},

31: {"s": [],
    0: [["निमित्तानि", "nimittāni", "omens"],
        ["च", "ca", "and"],
        ["पश्यामि", "paśyāmi", "I see"]],
    1: [["विपरीतानि", "viparītāni", "inauspicious"],
        ["केशव", "keśava", "O Keśava"]],
    2: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["श्रेयः", "śreyaḥ", "good"],
        ["अनुपश्यामि", "anupaśyāmi", "I see"]],
    3: [["हत्वा", "hatvā", "having killed"],
        ["स्व", "sva", "own"],
        ["जनम्", "janam", "people"],
        ["आहवे", "āhave", "in battle"]]},

32: {"s": [],
    0: [["न", "na", "not"],
        ["काङ्क्षे", "kāṅkṣe", "I desire"],
        ["विजयम्", "vijayam", "victory"],
        ["कृष्ण", "kṛṣṇa", "O Kṛṣṇa"]],
    1: [["न", "na", "not"],
        ["च", "ca", "and"],
        ["राज्यम्", "rājyam", "kingdom"],
        ["सुखानि", "sukhāni", "pleasures"],
        ["च", "ca", "and"]],
    2: [["किम्", "kim", "what"],
        ["नः", "naḥ", "to us"],
        ["राज्येन", "rājyena", "with the kingdom"],
        ["गोविन्द", "govinda", "O Govinda"]],
    3: [["किम्", "kim", "what"],
        ["भोगैः", "bhogaiḥ", "with enjoyments"],
        ["जीवितेन", "jīvitena", "with life"],
        ["वा", "vā", "or"]]},

33: {"s": [],
    0: [["येषाम्", "yeṣām", "for whom"],
        ["अर्थे", "arthe", "for the sake of"],
        ["काङ्क्षितम्", "kāṅkṣitam", "desired"],
        ["नः", "naḥ", "our"]],
    1: [["राज्यम्", "rājyam", "kingdom"],
        ["भोगाः", "bhogāḥ", "enjoyments"],
        ["सुखानि", "sukhāni", "pleasures"],
        ["च", "ca", "and"]],
    2: [["ते", "te", "they"],
        ["इमे", "ime", "these"],
        ["अवस्थिताः", "avasthitāḥ", "stationed"],
        ["युद्धे", "yuddhe", "in battle"]],
    3: [["प्राणान्", "prāṇān", "lives"],
        ["त्यक्त्वा", "tyaktvā", "having given up"],
        ["धनानि", "dhanāni", "wealth"],
        ["च", "ca", "and"]]},

34: {"s": [],
    0: [["आचार्याः", "ācāryāḥ", "teachers"],
        ["पितरः", "pitaraḥ", "fathers"],
        ["पुत्राः", "putrāḥ", "sons"]],
    1: [["तथा", "tathā", "likewise"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"],
        ["पितामहाः", "pitāmahāḥ", "grandfathers"]],
    2: [["मातुलाः", "mātulāḥ", "maternal uncles"],
        ["श्वशुराः", "śvaśurāḥ", "fathers-in-law"],
        ["पौत्राः", "pautrāḥ", "grandsons"]],
    3: [["श्यालाः", "śyālāḥ", "brothers-in-law"],
        ["संबन्धिनः", "sambandhinaḥ", "relatives"],
        ["तथा", "tathā", "also"]]},

35: {"s": [],
    0: [["एतान्", "etān", "these"],
        ["न", "na", "not"],
        ["हन्तुम्", "hantum", "to kill"],
        ["इच्छामि", "icchāmi", "I wish"]],
    1: [["घ्नतः", "ghnataḥ", "even killing"],
        ["अपि", "api", "even"],
        ["मधुसूदन", "madhusūdana", "O Madhusūdana"]],
    2: [["अपि", "api", "even"],
        ["त्रैलोक्य", "trailokya", "of the three worlds"],
        ["राज्यस्य", "rājyasya", "of the sovereignty"]],
    3: [["हेतोः", "hetoḥ", "for the sake of"],
        ["किम्", "kim", "what"],
        ["नु", "nu", "then"],
        ["मही", "mahī", "the earth"],
        ["कृते", "kṛte", "for the sake of"]]},

36: {"s": [],
    0: [["निहत्य", "nihatya", "having slain"],
        ["धार्तराष्ट्रान्", "dhārtarāṣṭrān", "the sons of Dhṛtarāṣṭra"],
        ["नः", "naḥ", "our"]],
    1: [["का", "kā", "what"],
        ["प्रीतिः", "prītiḥ", "pleasure"],
        ["स्यात्", "syāt", "would be"],
        ["जनार्दन", "janārdana", "O Janārdana"]],
    2: [["पापम्", "pāpam", "sin"],
        ["एव", "eva", "indeed"],
        ["आश्रयेत्", "āśrayet", "would take hold of"],
        ["अस्मान्", "asmān", "us"]],
    3: [["हत्वा", "hatvā", "having killed"],
        ["एतान्", "etān", "these"],
        ["आततायिनः", "ātatāyinaḥ", "aggressors"]]},

37: {"s": [],
    0: [["तस्मात्", "tasmāt", "therefore"],
        ["न", "na", "not"],
        ["अर्हाः", "arhāḥ", "worthy"],
        ["वयम्", "vayam", "we"],
        ["हन्तुम्", "hantum", "to kill"]],
    1: [["धार्तराष्ट्रान्", "dhārtarāṣṭrān", "the sons of Dhṛtarāṣṭra"],
        ["स्व", "sva", "own"],
        ["बान्धवान्", "bāndhavān", "kinsmen"]],
    2: [["स्व", "sva", "own"],
        ["जनम्", "janam", "people"],
        ["हि", "hi", "indeed"],
        ["कथम्", "katham", "how"],
        ["हत्वा", "hatvā", "having killed"]],
    3: [["सुखिनः", "sukhinaḥ", "happy"],
        ["स्याम", "syāma", "would we be"],
        ["माधव", "mādhava", "O Mādhava"]]},

38: {"s": [],
    0: [["यद्यपि", "yadyapi", "although"],
        ["एते", "ete", "these"],
        ["न", "na", "not"],
        ["पश्यन्ति", "paśyanti", "see"]],
    1: [["लोभ", "lobha", "greed"],
        ["उपहत", "upahata", "overcome"],
        ["चेतसः", "cetasaḥ", "minds"]],
    2: [["कुलक्षय", "kulakṣaya", "family destruction"],
        ["कृतम्", "kṛtam", "caused by"],
        ["दोषम्", "doṣam", "fault"]],
    3: [["मित्र", "mitra", "toward friends"],
        ["द्रोहे", "drohe", "in treachery"],
        ["च", "ca", "and"],
        ["पातकम्", "pātakam", "sin"]]},

39: {"s": [],
    0: [["कथम्", "katham", "how"],
        ["न", "na", "not"],
        ["ज्ञेयम्", "jñeyam", "to be known"],
        ["अस्माभिः", "asmābhiḥ", "by us"]],
    1: [["पापात्", "pāpāt", "from sin"],
        ["अस्मात्", "asmāt", "this"],
        ["निवर्तितुम्", "nivartitum", "to turn back"]],
    2: [["कुलक्षय", "kulakṣaya", "family destruction"],
        ["कृतम्", "kṛtam", "caused by"],
        ["दोषम्", "doṣam", "fault"]],
    3: [["प्रपश्यद्भिः", "prapaśyadbhiḥ", "by those who see"],
        ["जनार्दन", "janārdana", "O Janārdana"]]},

40: {"s": [],
    0: [["कुल", "kula", "of the family"],
        ["क्षये", "kṣaye", "with the destruction"],
        ["प्रणश्यन्ति", "praṇaśyanti", "perish"]],
    1: [["कुल", "kula", "family"],
        ["धर्माः", "dharmāḥ", "duties"],
        ["सनातनाः", "sanātanāḥ", "eternal"]],
    2: [["धर्मे", "dharme", "when dharma"],
        ["नष्टे", "naṣṭe", "destroyed"],
        ["कुलम्", "kulam", "the family"],
        ["कृत्स्नम्", "kṛtsnam", "whole"]],
    3: [["अधर्मः", "adharmaḥ", "irreligion"],
        ["अभिभवति", "abhibhavati", "overwhelms"],
        ["उत", "uta", "indeed"]]},

41: {"s": [],
    0: [["अधर्म", "adharma", "irreligion"],
        ["अभिभवात्", "abhibhavāt", "from the rise of"],
        ["कृष्ण", "kṛṣṇa", "O Kṛṣṇa"]],
    1: [["प्रदुष्यन्ति", "praduṣyanti", "become corrupted"],
        ["कुल", "kula", "of the family"],
        ["स्त्रियः", "striyaḥ", "the women"]],
    2: [["स्त्रीषु", "strīṣu", "when women"],
        ["दुष्टासु", "duṣṭāsu", "corrupted"],
        ["वार्ष्णेय", "vārṣṇeya", "O Vārṣṇeya"]],
    3: [["जायते", "jāyate", "arises"],
        ["वर्ण", "varṇa", "of classes"],
        ["सङ्करः", "saṅkaraḥ", "the mixing"]]},

42: {"s": [],
    0: [["सङ्करः", "saṅkaraḥ", "the mixing"],
        ["नरकाय", "narakāya", "to hell"],
        ["एव", "eva", "indeed"]],
    1: [["कुल", "kula", "of the family"],
        ["घ्नानाम्", "ghnānām", "of the destroyers"],
        ["कुलस्य", "kulasya", "of the family"],
        ["च", "ca", "and"]],
    2: [["पतन्ति", "patanti", "fall"],
        ["पितरः", "pitaraḥ", "ancestors"],
        ["हि", "hi", "indeed"],
        ["एषाम्", "eṣām", "of them"]],
    3: [["लुप्त", "lupta", "deprived of"],
        ["पिण्ड", "piṇḍa", "rice-offerings"],
        ["उदक", "udaka", "water"],
        ["क्रियाः", "kriyāḥ", "rites"]]},

43: {"s": [],
    0: [["दोषैः", "doṣaiḥ", "by the faults"],
        ["एतैः", "etaiḥ", "these"],
        ["कुल", "kula", "of the family"],
        ["घ्नानाम्", "ghnānām", "of the destroyers"]],
    1: [["वर्णसङ्कर", "varṇasaṅkara", "the mixing of classes"],
        ["कारकैः", "kārakaiḥ", "causing"]],
    2: [["उत्साद्यन्ते", "utsādyante", "are destroyed"],
        ["जाति", "jāti", "community"],
        ["धर्माः", "dharmāḥ", "duties"]],
    3: [["कुल", "kula", "family"],
        ["धर्माः", "dharmāḥ", "duties"],
        ["च", "ca", "and"],
        ["शाश्वताः", "śāśvatāḥ", "eternal"]]},

44: {"s": [],
    0: [["उत्सन्न", "utsanna", "destroyed"],
        ["कुल", "kula", "family"],
        ["धर्माणाम्", "dharmāṇām", "duties"]],
    1: [["मनुष्याणाम्", "manuṣyāṇām", "of men"],
        ["जनार्दन", "janārdana", "O Janārdana"]],
    2: [["नरके", "narake", "in hell"],
        ["नियतम्", "niyatam", "certainly"],
        ["वासः", "vāsaḥ", "dwelling"]],
    3: [["भवति", "bhavati", "is"],
        ["इति", "iti", "thus"],
        ["अनुशुश्रुम", "anuśuśruma", "we have heard"]]},

45: {"s": [],
    0: [["अहो", "aho", "alas"],
        ["बत", "bata", "alas"],
        ["महत्", "mahat", "great"],
        ["पापम्", "pāpam", "sin"]],
    1: [["कर्तुम्", "kartum", "to commit"],
        ["व्यवसिताः", "vyavasitāḥ", "resolved"],
        ["वयम्", "vayam", "we"]],
    2: [["यत्", "yat", "because"],
        ["राज्य", "rājya", "kingdom"],
        ["सुख", "sukha", "pleasure"],
        ["लोभेन", "lobhena", "by greed"]],
    3: [["हन्तुम्", "hantum", "to kill"],
        ["स्व", "sva", "own"],
        ["जनम्", "janam", "people"],
        ["उद्यताः", "udyatāḥ", "prepared"]]},

46: {"s": [],
    0: [["यदि", "yadi", "if"],
        ["माम्", "mām", "me"],
        ["अ", "a", "not"],
        ["प्रतीकारम्", "pratīkāram", "resisting"]],
    1: [["अ", "a", "without"],
        ["शस्त्रम्", "śastram", "weapons (unarmed)"],
        ["शस्त्र", "śastra", "weapons"],
        ["पाणयः", "pāṇayaḥ", "in hand"]],
    2: [["धार्तराष्ट्राः", "dhārtarāṣṭrāḥ", "the sons of Dhṛtarāṣṭra"],
        ["रणे", "raṇe", "in battle"],
        ["हन्युः", "hanyuḥ", "would kill"]],
    3: [["तत्", "tat", "that"],
        ["मे", "me", "for me"],
        ["क्षेमतरम्", "kṣemataram", "better"],
        ["भवेत्", "bhavet", "would be"]]},

47: {"s": [["सञ्जय", "sañjaya", "Sañjaya"],
          ["उवाच", "uvāca", "said"]],
    0: [["एवम्", "evam", "thus"],
        ["उक्त्वा", "uktvā", "having spoken"],
        ["अर्जुनः", "arjunaḥ", "Arjuna"],
        ["सङ्ख्ये", "saṅkhye", "on the battlefield"]],
    1: [["रथोपस्थ", "rathopastha", "the chariot-seat"],
        ["उपाविशत्", "upāviśat", "sat down"]],
    2: [["विसृज्य", "visṛjya", "having cast aside"],
        ["सशरम्", "saśaram", "with arrows"],
        ["चापम्", "cāpam", "the bow"]],
    3: [["शोक", "śoka", "grief"],
        ["संविग्न", "saṁvigna", "agitated, overwhelmed"],
        ["मानसः", "mānasaḥ", "the mind"]]},
}
