# -*- coding: utf-8 -*-
"""padachheda_ch18.py — per-pāda pada-chheda (word splits) for all 78 verses of Gita Chapter 18.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH18_WORDS = {
1: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
    0: [["संन्यासस्य", "saṁnyāsasya", "of renunciation"],
        ["महाबाहो", "mahābāho", "O mighty-armed one"]],
    1: [["तत्त्वम्", "tattvam", "the truth"],
        ["इच्छामि", "icchāmi", "I wish"],
        ["वेदितुम्", "veditum", "to know"]],
    2: [["त्यागस्य", "tyāgasya", "of abandonment"],
        ["च", "ca", "and"],
        ["हृषीकेश", "hṛṣīkeśa", "O Hṛṣīkeśa"]],
    3: [["पृथक्", "pṛthak", "separately"],
        ["केशिनिषूदन", "keśiniṣūdana", "O slayer of Keśin"]]},

2: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["काम्यानाम्", "kāmyānām", "of desired"],
        ["कर्मणाम्", "karmaṇām", "actions"],
        ["न्यासम्", "nyāsam", "the giving up"]],
    1: [["संन्यासम्", "saṁnyāsam", "renunciation"],
        ["कवयः", "kavayaḥ", "the wise"],
        ["विदुः", "viduḥ", "know"]],
    2: [["सर्वकर्मफलत्यागम्", "sarvakarmaphalatyāgam", "the abandonment of all fruits of action"]],
    3: [["प्राहुः", "prāhuḥ", "they call"],
        ["त्यागम्", "tyāgam", "tyāga"],
        ["विचक्षणाः", "vicakṣaṇāḥ", "the wise"]]},

3: {"s": [],
    0: [["त्याज्यम्", "tyājyam", "to be given up"],
        ["दोषवत्", "doṣavat", "as evil"],
        ["इति", "iti", "thus"],
        ["एके", "eke", "some"]],
    1: [["कर्म", "karma", "action"],
        ["प्राहुः", "prāhuḥ", "declare"],
        ["मनीषिणः", "manīṣiṇaḥ", "the wise"]],
    2: [["यज्ञदानतपःकर्म", "yajñadānatapaḥkarma", "sacrifice, gift and austerity"]],
    3: [["न", "na", "not"],
        ["त्याज्यम्", "tyājyam", "to be given up"],
        ["इति", "iti", "thus"],
        ["च", "ca", "and"],
        ["अपरे", "apare", "others"]]},

4: {"s": [],
    0: [["निश्चयम्", "niścayam", "the conclusion"],
        ["शृणु", "śṛṇu", "hear"],
        ["मे", "me", "my"],
        ["तत्र", "tatra", "there"]],
    1: [["त्यागे", "tyāge", "in tyāga"],
        ["भरतसत्तम", "bharatasattama", "O best of the Bhāratas"]],
    2: [["त्यागः", "tyāgaḥ", "tyāga"],
        ["हि", "hi", "indeed"],
        ["पुरुषव्याघ्र", "puruṣavyāghra", "O tiger among men"]],
    3: [["त्रिविधः", "trividhaḥ", "threefold"],
        ["संप्रकीर्तितः", "saṁprakīrtitaḥ", "is declared"]]},

5: {"s": [],
    0: [["यज्ञदानतपःकर्म", "yajñadānatapaḥkarma", "sacrifice, gift and austerity"]],
    1: [["न", "na", "not"],
        ["त्याज्यम्", "tyājyam", "to be given up"],
        ["कार्यम्", "kāryam", "must be done"],
        ["एव", "eva", "indeed"],
        ["तत्", "tat", "that"]],
    2: [["यज्ञः", "yajñaḥ", "sacrifice"],
        ["दानम्", "dānam", "gift"],
        ["तपः", "tapaḥ", "austerity"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["पावनानि", "pāvanāni", "the purifiers"],
        ["मनीषिणाम्", "manīṣiṇām", "of the wise"]]},

6: {"s": [],
    0: [["एतानि", "etāni", "these"],
        ["अपि", "api", "even"],
        ["तु", "tu", "but"],
        ["कर्माणि", "karmāṇi", "actions"]],
    1: [["सङ्गम्", "saṅgam", "attachment"],
        ["त्यक्त्वा", "tyaktvā", "having given up"],
        ["फलानि", "phalāni", "the fruits"],
        ["च", "ca", "and"]],
    2: [["कर्तव्यानि", "kartavyāni", "must be done"],
        ["इति", "iti", "thus"],
        ["मे", "me", "my"],
        ["पार्थ", "pārtha", "O Pārtha"]],
    3: [["निश्चितम्", "niścitam", "certain"],
        ["मतम्", "matam", "conviction"],
        ["उत्तमम्", "uttamam", "best"]]},

7: {"s": [],
    0: [["नियतस्य", "niyatasya", "of the prescribed"],
        ["तु", "tu", "but"],
        ["संन्यासः", "saṁnyāsaḥ", "renunciation"]],
    1: [["कर्मणः", "karmaṇaḥ", "of action"],
        ["न", "na", "not"],
        ["उपपद्यते", "upapadyate", "is proper"]],
    2: [["मोहात्", "mohāt", "through delusion"],
        ["तस्य", "tasya", "its"],
        ["परित्यागः", "parityāgaḥ", "abandonment"]],
    3: [["तामसः", "tāmasaḥ", "tāmasic"],
        ["परिकीर्तितः", "parikīrtitaḥ", "is declared"]]},

8: {"s": [],
    0: [["दुःखम्", "duḥkham", "painful"],
        ["इति", "iti", "thus"],
        ["एव", "eva", "indeed"],
        ["यत्", "yat", "which"],
        ["कर्म", "karma", "action"]],
    1: [["कायक्लेशभयात्", "kāyakleśabhayāt", "from fear of bodily suffering"],
        ["त्यजेत्", "tyajet", "one gives up"]],
    2: [["सः", "saḥ", "he"],
        ["कृत्वा", "kṛtvā", "having done"],
        ["राजसम्", "rājasam", "rājasic"],
        ["त्यागम्", "tyāgam", "renunciation"]],
    3: [["न", "na", "not"],
        ["एव", "eva", "indeed"],
        ["त्यागफलम्", "tyāgaphalam", "the fruit of renunciation"],
        ["लभेत्", "labhet", "gains"]]},

9: {"s": [],
    0: [["कार्यम्", "kāryam", "to be done"],
        ["इति", "iti", "thus"],
        ["एव", "eva", "indeed"],
        ["यत्", "yat", "which"],
        ["कर्म", "karma", "action"]],
    1: [["नियतम्", "niyatam", "prescribed"],
        ["क्रियते", "kriyate", "is done"],
        ["अर्जुन", "arjuna", "O Arjuna"]],
    2: [["सङ्गम्", "saṅgam", "attachment"],
        ["त्यक्त्वा", "tyaktvā", "having given up"],
        ["फलम्", "phalam", "the fruit"],
        ["च", "ca", "and"],
        ["एव", "eva", "indeed"]],
    3: [["सः", "saḥ", "that"],
        ["त्यागः", "tyāgaḥ", "renunciation"],
        ["सात्त्विकः", "sāttvikaḥ", "sāttvic"],
        ["मतः", "mataḥ", "is deemed"]]},

10: {"s": [],
     0: [["न", "na", "not"],
         ["द्वेष्टि", "dveṣṭi", "hates"],
         ["अकुशलम्", "akuśalam", "unpleasant"],
         ["कर्म", "karma", "action"]],
     1: [["कुशले", "kuśale", "to pleasant"],
         ["न", "na", "not"],
         ["अनुषज्जते", "anuṣajjate", "is attached"]],
     2: [["त्यागी", "tyāgī", "the renouncer"],
         ["सत्त्वसमाविष्टः", "sattvasamāviṣṭaḥ", "endowed with sattva"]],
     3: [["मेधावी", "medhāvī", "the wise"],
         ["छिन्नसंशयः", "chinnasaṁśayaḥ", "with doubt cut"]]},

11: {"s": [],
     0: [["न", "na", "not"],
         ["हि", "hi", "indeed"],
         ["देहभृता", "dehabhṛtā", "by the embodied one"],
         ["शक्यम्", "śakyam", "possible"]],
     1: [["त्यक्तुम्", "tyaktum", "to give up"],
         ["कर्माणि", "karmāṇi", "actions"],
         ["अशेषतः", "aśeṣataḥ", "entirely"]],
     2: [["यः", "yaḥ", "who"],
         ["तु", "tu", "but"],
         ["कर्मफलत्यागी", "karmaphalatyāgī", "renouncing the fruit of action"]],
     3: [["सः", "saḥ", "he"],
         ["त्यागी", "tyāgī", "the renouncer"],
         ["इति", "iti", "thus"],
         ["अभिधीयते", "abhidhīyate", "is called"]]},

12: {"s": [],
     0: [["अनिष्टम्", "aniṣṭam", "unpleasant"],
         ["इष्टम्", "iṣṭam", "pleasant"],
         ["मिश्रम्", "miśram", "mixed"],
         ["च", "ca", "and"]],
     1: [["त्रिविधम्", "trividham", "threefold"],
         ["कर्मणः", "karmaṇaḥ", "of action"],
         ["फलम्", "phalam", "the fruit"]],
     2: [["भवति", "bhavati", "comes"],
         ["अत्यागिनाम्", "atyāginām", "of the non-renouncer"],
         ["प्रेत्य", "pretya", "after death"]],
     3: [["न", "na", "not"],
         ["तु", "tu", "but"],
         ["संन्यासिनाम्", "saṁnyāsinām", "of the renouncer"],
         ["क्वचित्", "kvacit", "ever"]]},

13: {"s": [],
    0: [
    ["पञ्च", "pañca", "five"], ["एतानि", "etāni", "these"],
        ["महाबाहो", "mahābāho", "O mighty-armed one"]],
    1: [
    ["कारणानि", "kāraṇāni", "causes"], ["निबोध", "nibodha", "know"],
        ["मे", "me", "from me"]],
    2: [
    ["सांख्ये", "sāṁkhye", "in the philosophy"],
        ["कृतान्ते", "kṛtānte", "of the end of action"],
        ["प्रोक्तानि", "proktāni", "declared"]],
    3: [
    ["सिद्धये", "siddhaye", "for the accomplishment"],
        ["सर्वकर्मणाम्", "sarvakarmaṇām", "of all actions"]]
},
14: {"s": [],
     0: [["अधिष्ठानम्", "adhiṣṭhānam", "the seat"],
         ["तथा", "tathā", "and"],
         ["कर्ता", "kartā", "the agent"]],
     1: [["करणम्", "karaṇam", "the instrument"],
         ["च", "ca", "and"],
         ["पृथग्विधम्", "pṛthagvidham", "of various kinds"]],
     2: [["विविधाः", "vividhāḥ", "various"],
         ["च", "ca", "and"],
         ["पृथक्चेष्टाः", "pṛthakceṣṭāḥ", "the separate efforts"]],
     3: [["दैवम्", "daivam", "destiny"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["अत्र", "atra", "here"],
         ["पञ्चमम्", "pañcamam", "the fifth"]]},

15: {"s": [],
     0: [["शरीरवाङ्मनोभिः", "śarīravāṅmanobhiḥ", "with body, speech and mind"]],
     1: [["यत्", "yat", "which"],
         ["कर्म", "karma", "action"],
         ["प्रारभते", "prārabhate", "undertakes"],
         ["नरः", "naraḥ", "a man"]],
     2: [["न्याय्यम्", "nyāyyam", "right"],
         ["वा", "vā", "or"],
         ["विपरीतम्", "viparītam", "wrong"],
         ["वा", "vā", "or"]],
     3: [["पञ्च", "pañca", "five"],
         ["एते", "ete", "these"],
         ["तस्य", "tasya", "of it"],
         ["हेतवः", "hetavaḥ", "the causes"]]},

16: {"s": [],
     0: [["तत्र", "tatra", "there"],
         ["एवम्", "evam", "thus"],
         ["सति", "sati", "being"],
         ["कर्तारम्", "kartāram", "the agent"]],
     1: [["आत्मानम्", "ātmānam", "the Self"],
         ["केवलम्", "kevalam", "alone"],
         ["तु", "tu", "but"],
         ["यः", "yaḥ", "who"]],
     2: [["पश्यति", "paśyati", "sees"],
         ["अकृतबुद्धित्वात्", "akṛtabuddhitvāt", "from imperfect understanding"]],
     3: [["न", "na", "not"],
         ["सः", "saḥ", "he"],
         ["पश्यति", "paśyati", "sees"],
         ["दुर्मतिः", "durmatiḥ", "the wrong-minded"]]},

17: {"s": [],
     0: [["यस्य", "yasya", "whose"],
         ["नाहंकृतो", "nāhaṁkṛto", "free from ego"],
         ["भावः", "bhāvaḥ", "the mind"]],
     1: [["बुद्धिः", "buddhiḥ", "the intellect"],
         ["यस्य", "yasya", "whose"],
         ["न", "na", "not"],
         ["लिप्यते", "lipyate", "is stained"]],
     2: [["हत्वा", "hatvā", "having slain"],
         ["अपि", "api", "even"],
         ["सः", "saḥ", "he"],
         ["इमान्", "imān", "these"],
         ["लोकान्", "lokān", "worlds"]],
     3: [["न", "na", "not"],
         ["हन्ति", "hanti", "slays"],
         ["न", "na", "nor"],
         ["निबध्यते", "nibadhyate", "is bound"]]},

18: {"s": [],
     0: [["ज्ञानम्", "jñānam", "knowledge"],
         ["ज्ञेयम्", "jñeyam", "the known"],
         ["परिज्ञाता", "parijñātā", "the knower"]],
     1: [["त्रिविधा", "trividhā", "threefold"],
         ["कर्मचोदना", "karmacodanā", "the impulse to action"]],
     2: [["करणम्", "karaṇam", "the instrument"],
         ["कर्म", "karma", "the act"],
         ["कर्ता", "kartā", "the agent"],
         ["इति", "iti", "thus"]],
     3: [["त्रिविधः", "trividhaḥ", "threefold"],
         ["कर्मसंग्रहः", "karmasaṁgrahaḥ", "the basis of action"]]},

19: {"s": [],
     0: [["ज्ञानम्", "jñānam", "knowledge"],
         ["कर्म", "karma", "action"],
         ["च", "ca", "and"],
         ["कर्ता", "kartā", "agent"],
         ["च", "ca", "and"]],
     1: [["त्रिधा", "tridhā", "threefold"],
         ["एव", "eva", "indeed"],
         ["गुणभेदतः", "guṇabhedataḥ", "by the distinction of the guṇas"]],
     2: [["प्रोच्यते", "procyate", "is declared"],
         ["गुणसंख्याने", "guṇasaṁkhyāne", "in the enumeration of the guṇas"]],
     3: [["यथावत्", "yathāvat", "as they are"],
         ["शृणु", "śṛṇu", "hear"],
         ["तानि", "tāni", "them"],
         ["अपि", "api", "also"]]},

20: {"s": [],
     0: [["सर्वभूतेषु", "sarvabhūteṣu", "in all beings"],
         ["येन", "yena", "by which"],
         ["एकम्", "ekam", "one"]],
     1: [["भावम्", "bhāvam", "being"],
         ["अव्ययम्", "avyayam", "imperishable"],
         ["ईक्षते", "īkṣate", "sees"]],
     2: [["अविभक्तम्", "avibhaktam", "undivided"],
         ["विभक्तेषु", "vibhakteṣu", "in the divided"]],
     3: [["तत्", "tat", "that"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["विद्धि", "viddhi", "know"],
         ["सात्त्विकम्", "sāttvikam", "sāttvic"]]},

21: {"s": [],
     0: [["पृथक्त्वेन", "pṛthaktvena", "as separate"],
         ["तु", "tu", "but"],
         ["यत्", "yat", "which"],
         ["ज्ञानम्", "jñānam", "knowledge"]],
     1: [["नानाभावान्", "nānābhāvān", "the manifold beings"],
         ["पृथग्विधान्", "pṛthagvidhān", "of various kinds"]],
     2: [["वेत्ति", "vetti", "knows"],
         ["सर्वेषु", "sarveṣu", "in all"],
         ["भूतेषु", "bhūteṣu", "beings"]],
     3: [["तत्", "tat", "that"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["विद्धि", "viddhi", "know"],
         ["राजसम्", "rājasam", "rājasic"]]},

22: {"s": [],
     0: [["यत्", "yat", "which"],
         ["तु", "tu", "but"],
         ["कृत्स्नवत्", "kṛtsnavat", "as if the whole"],
         ["एकस्मिन्", "ekasmin", "in one"]],
     1: [["कार्ये", "kārye", "effect"],
         ["सक्तम्", "saktam", "attached"],
         ["अहैतुकम्", "ahaitukam", "without reason"]],
     2: [["अतत्त्वार्थवत्", "atattvārthavat", "without truth"],
         ["अल्पम्", "alpam", "trivial"],
         ["च", "ca", "and"]],
     3: [["तत्", "tat", "that"],
         ["तामसम्", "tāmasam", "tāmasic"],
         ["उदाहृतम्", "udāhṛtam", "is declared"]]},

23: {"s": [],
    0: [
    ["नियतम्", "niyatam", "prescribed"],
        ["सङ्गरहितम्", "saṅgarahitam", "without attachment"]],
    1: [
    ["अरागद्वेषतः", "arāgadveṣataḥ", "without desire or aversion"],
        ["कृतम्", "kṛtam", "done"]],
    2: [
    ["अफलप्रेप्सुना", "aphalaprepsunā", "by one not desiring fruit"],
        ["कर्म", "karma", "action"]],
    3: [
    ["यत्", "yat", "which"], ["तत्", "tat", "that"],
        ["सात्त्विकम्", "sāttvikam", "sāttvic"], ["उच्यते", "ucyate", "is called"]]
},
24: {"s": [],
     0: [["यत्", "yat", "which"],
         ["तु", "tu", "but"],
         ["कामेप्सुना", "kāmepsunā", "by one desiring desires"],
         ["कर्म", "karma", "action"]],
     1: [["साहंकारेण", "sāhaṁkāreṇa", "with ego"],
         ["वा", "vā", "or"],
         ["पुनः", "punaḥ", "again"]],
     2: [["क्रियते", "kriyate", "is done"],
         ["बहुलायासम्", "bahulāyāsam", "with great effort"]],
     3: [["तत्", "tat", "that"],
         ["राजसम्", "rājasam", "rājasic"],
         ["उदाहृतम्", "udāhṛtam", "is declared"]]},

25: {"s": [],
    0: [
    ["अनुबन्धम्", "anubandham", "the consequence"], ["क्षयम्", "kṣayam", "the ruin"],
        ["हिंसाम्", "hiṁsām", "the injury"]],
    1: [
    ["अनपेक्ष्य", "anapekṣya", "not regarding"], ["च", "ca", "and"],
        ["पौरुषम्", "pauruṣam", "one's own capacity"]],
    2: [
    ["मोहात्", "mohāt", "through delusion"], ["आरभ्यते", "ārabhyate", "is begun"],
        ["कर्म", "karma", "action"]],
    3: [
    ["यत्", "yat", "which"], ["तत्", "tat", "that"], ["तामसम्", "tāmasam", "tāmasic"],
        ["उच्यते", "ucyate", "is called"]]
},
26: {"s": [],
     0: [["मुक्तसङ्गः", "muktasaṅgaḥ", "free from attachment"],
         ["अनहंवादी", "anahaṁvādī", "without ego"]],
     1: [["धृत्युत्साहसमन्वितः", "dhṛtyutsāhasamanvitaḥ", "endowed with fortitude and zeal"]],
     2: [["सिद्ध्यसिद्ध्योः", "siddhyasiddhyoḥ", "in success and failure"],
         ["निर्विकारः", "nirvikāraḥ", "unmoved"]],
     3: [["कर्ता", "kartā", "the agent"],
         ["सात्त्विकः", "sāttvikaḥ", "sāttvic"],
         ["उच्यते", "ucyate", "is called"]]},

27: {"s": [],
     0: [["रागी", "rāgī", "passionate"],
         ["कर्मफलप्रेप्सुः", "karmaphalaprepsuḥ", "longing for the fruit of action"]],
     1: [["लुब्धः", "lubdhaḥ", "greedy"],
         ["हिंसात्मकः", "hiṁsātmakaḥ", "cruel"],
         ["अशुचिः", "aśuciḥ", "impure"]],
     2: [["हर्षशोकान्वितः", "harṣaśokānvitaḥ", "moved by joy and sorrow"],
         ["कर्ता", "kartā", "the agent"]],
     3: [["राजसः", "rājasaḥ", "rājasic"],
         ["परिकीर्तितः", "parikīrtitaḥ", "is declared"]]},

28: {"s": [],
     0: [["अयुक्तः", "ayuktaḥ", "undisciplined"],
         ["प्राकृतः", "prākṛtaḥ", "vulgar"],
         ["स्तब्धः", "stabdhaḥ", "obstinate"]],
     1: [["शठः", "śaṭhaḥ", "deceitful"],
         ["नैकृतिकः", "naikṛtikaḥ", "malicious"],
         ["अलसः", "alasaḥ", "lazy"]],
     2: [["विषादी", "viṣādī", "despondent"],
         ["दीर्घसूत्री", "dīrghasūtrī", "procrastinating"],
         ["च", "ca", "and"]],
     3: [["कर्ता", "kartā", "the agent"],
         ["तामसः", "tāmasaḥ", "tāmasic"],
         ["उच्यते", "ucyate", "is called"]]},

29: {"s": [],
     0: [["बुद्धेः", "buddheḥ", "of intellect"],
         ["भेदम्", "bhedam", "the distinction"],
         ["धृतेः", "dhṛteḥ", "of fortitude"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"]],
     1: [["गुणतः", "guṇataḥ", "by the guṇas"],
         ["त्रिविधम्", "trividham", "threefold"],
         ["शृणु", "śṛṇu", "hear"]],
     2: [["प्रोच्यमानम्", "procyamānam", "being declared"],
         ["अशेषेण", "aśeṣeṇa", "fully"]],
     3: [["पृथक्त्वेन", "pṛthaktvena", "separately"],
         ["धनंजय", "dhanaṁjaya", "O Dhanañjaya"]]},

30: {"s": [],
     0: [["प्रवृत्तिम्", "pravṛttim", "action"],
         ["च", "ca", "and"],
         ["निवृत्तिम्", "nivṛttim", "inaction"],
         ["च", "ca", "and"]],
     1: [["कार्याकार्ये", "kāryākārye", "right and wrong"],
         ["भयाभये", "bhayābhaye", "fear and fearlessness"]],
     2: [["बन्धम्", "bandham", "bondage"],
         ["मोक्षम्", "mokṣam", "liberation"],
         ["च", "ca", "and"],
         ["या", "yā", "which"],
         ["वेत्ति", "vetti", "knows"]],
     3: [["बुद्धिः", "buddhiḥ", "the intellect"],
         ["सा", "sā", "that"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सात्त्विकी", "sāttvikī", "sāttvic"]]},

31: {"s": [],
     0: [["यया", "yayā", "by which"],
         ["धर्मम्", "dharmam", "right"],
         ["अधर्मम्", "adharmam", "wrong"],
         ["च", "ca", "and"]],
     1: [["कार्यम्", "kāryam", "to be done"],
         ["च", "ca", "and"],
         ["अकार्यम्", "akāryam", "not to be done"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["अयथावत्", "ayathāvat", "incorrectly"],
         ["प्रजानाति", "prajānāti", "knows"]],
     3: [["बुद्धिः", "buddhiḥ", "the intellect"],
         ["सा", "sā", "that"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["राजसी", "rājasī", "rājasic"]]},

32: {"s": [],
     0: [["अधर्मम्", "adharmam", "wrong"],
         ["धर्मम्", "dharmam", "as right"],
         ["इति", "iti", "thus"],
         ["या", "yā", "which"]],
     1: [["मन्यते", "manyate", "thinks"],
         ["तमसावृता", "tamasāvṛtā", "enveloped in darkness"]],
     2: [["सर्वार्थान्", "sarvārthān", "all things"],
         ["विपरीतान्", "viparītān", "perversely"],
         ["च", "ca", "and"]],
     3: [["बुद्धिः", "buddhiḥ", "the intellect"],
         ["सा", "sā", "that"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["तामसी", "tāmasī", "tāmasic"]]},

33: {"s": [],
     0: [["धृत्या", "dhṛtyā", "with fortitude"],
         ["यया", "yayā", "by which"],
         ["धारयते", "dhārayate", "one holds"]],
     1: [["मनःप्राणेन्द्रियक्रियाः", "manaḥprāṇendriyakriyāḥ", "the activities of mind, breath and senses"]],
     2: [["योगेन", "yogena", "by yoga"],
         ["अव्यभिचारिण्या", "avyabhicāriṇyā", "unwavering"]],
     3: [["धृतिः", "dhṛtiḥ", "the fortitude"],
         ["सा", "sā", "that"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सात्त्विकी", "sāttvikī", "sāttvic"]]},

34: {"s": [],
     0: [["यया", "yayā", "by which"],
         ["तु", "tu", "but"],
         ["धर्मकामार्थान्", "dharmakāmārthān", "duty, pleasure and wealth"]],
     1: [["धृत्या", "dhṛtyā", "with fortitude"],
         ["धारयते", "dhārayate", "one holds"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["प्रसङ्गेन", "prasaṅgena", "with attachment"],
         ["फलाकाङ्क्षी", "phalākāṅkṣī", "desiring fruit"]],
     3: [["धृतिः", "dhṛtiḥ", "the fortitude"],
         ["सा", "sā", "that"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["राजसी", "rājasī", "rājasic"]]},

35: {"s": [],
     0: [["यया", "yayā", "by which"],
         ["स्वप्नम्", "svapnam", "sleep"],
         ["भयम्", "bhayam", "fear"],
         ["शोकम्", "śokam", "grief"]],
     1: [["विषादम्", "viṣādam", "despair"],
         ["मदम्", "madam", "arrogance"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["न", "na", "not"],
         ["विमुञ्चति", "vimuñcati", "lets go"],
         ["दुर्मेधा", "durmedhā", "the dull-minded"]],
     3: [["धृतिः", "dhṛtiḥ", "the fortitude"],
         ["सा", "sā", "that"],
         ["तामसी", "tāmasī", "tāmasic"],
         ["मता", "matā", "is deemed"]]},

36: {"s": [],
     0: [["सुखम्", "sukham", "happiness"],
         ["तु", "tu", "but"],
         ["इदानीम्", "idānīm", "now"],
         ["त्रिविधम्", "trividham", "threefold"]],
     1: [["शृणु", "śṛṇu", "hear"],
         ["मे", "me", "from me"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]],
     2: [["अभ्यासात्", "abhyāsāt", "from practice"],
         ["रमते", "ramate", "one rejoices"],
         ["यत्र", "yatra", "in which"]],
     3: [["दुःखान्तम्", "duḥkhāntam", "the end of suffering"],
         ["च", "ca", "and"],
         ["निगच्छति", "nigacchati", "reaches"]]},

37: {"s": [],
     0: [["यत्", "yat", "which"],
         ["तत्", "tat", "that"],
         ["अग्रे", "agre", "at first"],
         ["विषम्", "viṣam", "poison"],
         ["इव", "iva", "like"]],
     1: [["परिणामे", "pariṇāme", "at the end"],
         ["अमृतोपमम्", "amṛtopamam", "like nectar"]],
     2: [["तत्", "tat", "that"],
         ["सुखम्", "sukham", "happiness"],
         ["सात्त्विकम्", "sāttvikam", "sāttvic"],
         ["प्रोक्तम्", "proktam", "is declared"]],
     3: [["आत्मबुद्धिप्रसादजम्", "ātmabuddhiprasādajam", "born of the clarity of the Self"]]},

38: {"s": [],
     0: [["विषयेन्द्रियसंयोगात्", "viṣayendriyasaṁyogāt", "from the contact of senses and objects"]],
     1: [["यत्", "yat", "which"],
         ["तत्", "tat", "that"],
         ["अग्रे", "agre", "at first"],
         ["अमृतोपमम्", "amṛtopamam", "like nectar"]],
     2: [["परिणामे", "pariṇāme", "at the end"],
         ["विषम्", "viṣam", "poison"],
         ["इव", "iva", "like"]],
     3: [["तत्", "tat", "that"],
         ["सुखम्", "sukham", "happiness"],
         ["राजसम्", "rājasam", "rājasic"],
         ["स्मृतम्", "smṛtam", "is deemed"]]},

39: {"s": [],
     0: [["यत्", "yat", "which"],
         ["अग्रे", "agre", "at first"],
         ["च", "ca", "and"],
         ["अनुबन्धे", "anubandhe", "at the end"],
         ["च", "ca", "and"]],
     1: [["सुखम्", "sukham", "happiness"],
         ["मोहनम्", "mohanam", "deluding"],
         ["आत्मनः", "ātmanaḥ", "of the self"]],
     2: [["निद्रालस्यप्रमादोत्थम्", "nidrālasyapramādottham", "born of sleep, sloth and heedlessness"]],
     3: [["तत्", "tat", "that"],
         ["तामसम्", "tāmasam", "tāmasic"],
         ["उदाहृतम्", "udāhṛtam", "is declared"]]},

40: {"s": [],
     0: [["न", "na", "not"],
         ["तत्", "tat", "that"],
         ["अस्ति", "asti", "there is"],
         ["पृथिव्याम्", "pṛthivyām", "on earth"],
         ["वा", "vā", "or"]],
     1: [["दिवि", "divi", "in heaven"],
         ["देवेषु", "deveṣu", "among the gods"],
         ["वा", "vā", "or"],
         ["पुनः", "punaḥ", "again"]],
     2: [["सत्त्वम्", "sattvam", "being"],
         ["प्रकृतिजैः", "prakṛtijaiḥ", "born of prakṛti"],
         ["मुक्तम्", "muktam", "free"]],
     3: [["यत्", "yat", "which"],
         ["एभिः", "ebhiḥ", "from these"],
         ["स्यात्", "syāt", "might be"],
         ["त्रिभिः", "tribhiḥ", "three"],
         ["गुणैः", "guṇaiḥ", "qualities"]]},

41: {"s": [],
     0: [["ब्राह्मणक्षत्रियविशाम्", "brāhmaṇakṣatriyaviśām", "of brāhmaṇas, kṣatriyas and vaiśyas"]],
     1: [["शूद्राणाम्", "śūdrāṇām", "of śūdras"],
         ["च", "ca", "and"],
         ["परंतप", "paraṁtapa", "O scorcher of foes"]],
     2: [["कर्माणि", "karmāṇi", "the duties"],
         ["प्रविभक्तानि", "pravibhaktāni", "divided"]],
     3: [["स्वभावप्रभवैः", "svabhāvaprabhavaiḥ", "born of their own nature"],
         ["गुणैः", "guṇaiḥ", "by the qualities"]]},

42: {"s": [],
     0: [["शमः", "śamaḥ", "tranquillity"],
         ["दमः", "damaḥ", "self-control"],
         ["तपः", "tapaḥ", "austerity"],
         ["शौचम्", "śaucam", "purity"]],
     1: [["क्षान्तिः", "kṣāntiḥ", "patience"],
         ["आर्जवम्", "ārjavam", "uprightness"],
         ["एव", "eva", "indeed"],
         ["च", "ca", "and"]],
     2: [["ज्ञानम्", "jñānam", "knowledge"],
         ["विज्ञानम्", "vijñānam", "wisdom"],
         ["आस्तिक्यम्", "āstikyam", "faith"]],
     3: [["ब्रह्मकर्म", "brahmakarma", "the duty of the brāhmaṇa"],
         ["स्वभावजम्", "svabhāvajam", "born of his nature"]]},

43: {"s": [],
     0: [["शौर्यम्", "śauryam", "valour"],
         ["तेजः", "tejaḥ", "splendour"],
         ["धृतिः", "dhṛtiḥ", "fortitude"],
         ["दाक्ष्यम्", "dākṣyam", "skill"]],
     1: [["युद्धे", "yuddhe", "in battle"],
         ["च", "ca", "and"],
         ["अपि", "api", "even"],
         ["अपलायनम्", "apalāyanam", "not fleeing"]],
     2: [["दानम्", "dānam", "generosity"],
         ["ईश्वरभावः", "īśvarabhāvaḥ", "lordship"],
         ["च", "ca", "and"]],
     3: [["क्षात्रम्", "kṣātram", "of the kṣatriya"],
         ["कर्म", "karma", "the duty"],
         ["स्वभावजम्", "svabhāvajam", "born of his nature"]]},

44: {"s": [],
     0: [["कृषिगौरक्ष्यवाणिज्यम्", "kṛṣigaurakṣyavāṇijyam", "agriculture, cattle-rearing and trade"]],
     1: [["वैश्यकर्म", "vaiśyakarma", "the duty of the vaiśya"],
         ["स्वभावजम्", "svabhāvajam", "born of his nature"]],
     2: [["परिचर्यात्मकम्", "paricaryātmakam", "of the nature of service"],
         ["कर्म", "karma", "the duty"]],
     3: [["शूद्रस्य", "śūdrasya", "of the śūdra"],
         ["अपि", "api", "also"],
         ["स्वभावजम्", "svabhāvajam", "born of his nature"]]},

45: {"s": [],
     0: [["स्वे", "sve", "in his own"],
         ["स्वे", "sve", "in his own"],
         ["कर्मणि", "karmaṇi", "duty"],
         ["अभिरतः", "abhirataḥ", "delighting"]],
     1: [["संसिद्धिम्", "saṁsiddhim", "perfection"],
         ["लभते", "labhate", "attains"],
         ["नरः", "naraḥ", "a man"]],
     2: [["स्वकर्मनिरतः", "svakarmanirataḥ", "devoted to his own duty"],
         ["सिद्धिम्", "siddhim", "perfection"]],
     3: [["यथा", "yathā", "how"],
         ["विन्दति", "vindati", "attains"],
         ["तत्", "tat", "that"],
         ["शृणु", "śṛṇu", "hear"]]},

46: {"s": [],
     0: [["यतः", "yataḥ", "from whom"],
         ["प्रवृत्तिः", "pravṛttiḥ", "the origin"],
         ["भूतानाम्", "bhūtānām", "of beings"]],
     1: [["येन", "yena", "by whom"],
         ["सर्वम्", "sarvam", "all"],
         ["इदम्", "idam", "this"],
         ["ततम्", "tatam", "is pervaded"]],
     2: [["स्वकर्मणा", "svakarmaṇā", "by his own duty"],
         ["तम्", "tam", "him"],
         ["अभ्यर्च्य", "abhyarcya", "worshipping"]],
     3: [["सिद्धिम्", "siddhim", "perfection"],
         ["विन्दति", "vindati", "attains"],
         ["मानवः", "mānavaḥ", "a man"]]},

47: {"s": [],
     0: [["श्रेयान्", "śreyān", "better"],
         ["स्वधर्मः", "svadharmaḥ", "one's own dharma"],
         ["विगुणः", "viguṇaḥ", "though imperfect"]],
     1: [["परधर्मात्", "paradharmāt", "than another's dharma"],
         ["स्वनुष्ठितात्", "svanuṣṭhitāt", "well-performed"]],
     2: [["स्वभावनियतम्", "svabhāvaniyatam", "fixed by one's own nature"],
         ["कर्म", "karma", "action"]],
     3: [["कुर्वन्", "kurvan", "doing"],
         ["आप्नोति", "āpnoti", "incurs"],
         ["किल्बिषम्", "kilbiṣam", "sin"]]},

48: {"s": [],
     0: [["सहजम्", "sahajam", "born with oneself"],
         ["कर्म", "karma", "action"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     1: [["सदोषम्", "sadoṣam", "with fault"],
         ["अपि", "api", "even"],
         ["न", "na", "not"],
         ["त्यजेत्", "tyajet", "should abandon"]],
     2: [["सर्वारम्भाः", "sarvārambhāḥ", "all undertakings"],
         ["हि", "hi", "indeed"],
         ["दोषेण", "doṣeṇa", "with fault"]],
     3: [["धूमेन", "dhūmena", "by smoke"],
         ["अग्निः", "agniḥ", "fire"],
         ["इव", "iva", "as"],
         ["आवृताः", "āvṛtāḥ", "covered"]]},

49: {"s": [],
    0: [
    ["असक्तबुद्धिः", "asaktabuddhiḥ", "of unattached intellect"],
        ["सर्वत्र", "sarvatra", "everywhere"]],
    1: [
    ["जितात्मा", "jitātmā", "self-conquered"],
        ["विगतस्पृहः", "vigataspṛhaḥ", "free from desire"]],
    2: [
    ["नैष्कर्म्यसिद्धिम्", "naiṣkarmyasiddhim", "the perfection of freedom from action"],
        ["परमाम्", "paramām", "the supreme"]],
    3: [
    ["संन्यासेन", "saṁnyāsena", "through renunciation"],
        ["अधिगच्छति", "adhigacchati", "attains"]]
},
50: {"s": [],
     0: [["सिद्धिम्", "siddhim", "perfection"],
         ["प्राप्तः", "prāptaḥ", "having attained"],
         ["यथा", "yathā", "how"],
         ["ब्रह्म", "brahma", "Brahman"]],
     1: [["तथा", "tathā", "so"],
         ["आप्नोति", "āpnoti", "attains"],
         ["निबोध", "nibodha", "know"],
         ["मे", "me", "from me"]],
     2: [["समासेन", "samāsena", "in brief"],
         ["एव", "eva", "indeed"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     3: [["निष्ठा", "niṣṭhā", "the culmination"],
         ["ज्ञानस्य", "jñānasya", "of knowledge"],
         ["या", "yā", "which"],
         ["परा", "parā", "supreme"]]},

51: {"s": [],
     0: [["बुद्ध्या", "buddhyā", "with intellect"],
         ["विशुद्धया", "viśuddhayā", "pure"],
         ["युक्तः", "yuktaḥ", "endowed"]],
     1: [["धृत्या", "dhṛtyā", "with fortitude"],
         ["आत्मानम्", "ātmānam", "the self"],
         ["नियम्य", "niyamya", "having restrained"],
         ["च", "ca", "and"]],
     2: [["शब्दादीन्", "śabdādīn", "sound and the other"],
         ["विषयान्", "viṣayān", "objects"],
         ["त्यक्त्वा", "tyaktvā", "having given up"]],
     3: [["रागद्वेषौ", "rāgadveṣau", "desire and aversion"],
         ["व्युदस्य", "vyudasya", "having cast aside"],
         ["च", "ca", "and"]]},

52: {"s": [],
     0: [["विविक्तसेवी", "viviktasevī", "dwelling in solitude"],
         ["लघ्वाशी", "laghvāśī", "eating little"]],
     1: [["यतवाक्कायमानसः", "yatavākkāyamānasaḥ", "master of speech, body and mind"]],
     2: [["ध्यानयोगपरः", "dhyānayogaparaḥ", "ever engaged in meditation"],
         ["नित्यम्", "nityam", "always"]],
     3: [["वैराग्यम्", "vairāgyam", "detachment"],
         ["समुपाश्रितः", "samupāśritaḥ", "having taken refuge in"]]},

53: {"s": [],
     0: [["अहंकारम्", "ahaṁkāram", "ego"],
         ["बलम्", "balam", "power"],
         ["दर्पम्", "darpam", "pride"]],
     1: [["कामम्", "kāmam", "desire"],
         ["क्रोधम्", "krodham", "anger"],
         ["परिग्रहम्", "parigraham", "possessiveness"]],
     2: [["विमुच्य", "vimucya", "having freed oneself from"],
         ["निर्ममः", "nirmamaḥ", "without possessiveness"],
         ["शान्तः", "śāntaḥ", "peaceful"]],
     3: [["ब्रह्मभूयाय", "brahmabhūyāya", "for Brahman"],
         ["कल्पते", "kalpate", "becomes fit"]]},

54: {"s": [],
     0: [["ब्रह्मभूतः", "brahmabhūtaḥ", "become Brahman"],
         ["प्रसन्नात्मा", "prasannātmā", "serene of soul"]],
     1: [["न", "na", "not"],
         ["शोचति", "śocati", "grieves"],
         ["न", "na", "nor"],
         ["काङ्क्षति", "kāṅkṣati", "desires"]],
     2: [["समः", "samaḥ", "equal"],
         ["सर्वेषु", "sarveṣu", "to all"],
         ["भूतेषु", "bhūteṣu", "beings"]],
     3: [["मद्भक्तिम्", "madbhaktim", "devotion to me"],
         ["लभते", "labhate", "attains"],
         ["पराम्", "parām", "supreme"]]},

55: {"s": [],
     0: [["भक्त्या", "bhaktyā", "by devotion"],
         ["माम्", "mām", "me"],
         ["अभिजानाति", "abhijānāti", "knows"]],
     1: [["यावान्", "yāvān", "what"],
         ["यः", "yaḥ", "who"],
         ["च", "ca", "and"],
         ["अस्मि", "asmi", "I am"],
         ["तत्त्वतः", "tattvataḥ", "in truth"]],
     2: [["ततः", "tataḥ", "then"],
         ["माम्", "mām", "me"],
         ["तत्त्वतः", "tattvataḥ", "in truth"],
         ["ज्ञात्वा", "jñātvā", "having known"]],
     3: [["विशते", "viśate", "enters"],
         ["तत्", "tat", "that"],
         ["अनन्तरम्", "anantaram", "immediately"]]},

56: {"s": [],
     0: [["सर्वकर्माणि", "sarvakarmāṇi", "all actions"],
         ["अपि", "api", "even"],
         ["सदा", "sadā", "always"]],
     1: [["कुर्वाणः", "kurvāṇaḥ", "performing"],
         ["मद्व्यपाश्रयः", "madvyapāśrayaḥ", "taking refuge in me"]],
     2: [["मत्प्रसादात्", "matprasādāt", "by my grace"],
         ["अवाप्नोति", "avāpnoti", "attains"]],
     3: [["शाश्वतम्", "śāśvatam", "the eternal"],
         ["पदम्", "padam", "state"],
         ["अव्ययम्", "avyayam", "imperishable"]]},

57: {"s": [],
     0: [["चेतसा", "cetasā", "in thought"],
         ["सर्वकर्माणि", "sarvakarmāṇi", "all actions"]],
     1: [["मयि", "mayi", "in me"],
         ["संन्यस्य", "saṁnyasya", "having surrendered"],
         ["मत्परः", "matparaḥ", "holding me supreme"]],
     2: [["बुद्धियोगम्", "buddhiyogam", "the yoga of discernment"],
         ["उपाश्रित्य", "upāśritya", "having resorted to"]],
     3: [["मच्चित्तः", "maccittaḥ", "with your mind on me"],
         ["सततम्", "satatam", "always"],
         ["भव", "bhava", "be"]]},

58: {"s": [],
     0: [["मच्चित्तः", "maccittaḥ", "with your mind on me"],
         ["सर्वदुर्गाणि", "sarvadurgāṇi", "all difficulties"]],
     1: [["मत्प्रसादात्", "matprasādāt", "by my grace"],
         ["तरिष्यसि", "tariṣyasi", "you will cross"]],
     2: [["अथ", "atha", "but"],
         ["चेत्", "cet", "if"],
         ["त्वम्", "tvam", "you"],
         ["अहंकारात्", "ahaṁkārāt", "from ego"]],
     3: [["न", "na", "not"],
         ["श्रोष्यसि", "śroṣyasi", "will listen"],
         ["विनङ्क्ष्यसि", "vinaṅkṣyasi", "you will be destroyed"]]},

59: {"s": [],
    0: [
    ["यदि", "yadi", "if"], ["अहंकारम्", "ahaṁkāram", "on ego"],
        ["आश्रित्य", "āśritya", "relying"]],
    1: [
    ["न", "na", "not"], ["योत्स्ये", "yotsye", "I will fight"], ["इति", "iti", "thus"],
        ["मन्यसे", "manyase", "you think"]],
    2: [
    ["मिथ्या", "mithyā", "vain"], ["एषः", "eṣaḥ", "this"],
        ["व्यवसायः", "vyavasāyaḥ", "resolve"], ["ते", "te", "your"]],
    3: [
    ["प्रकृतिः", "prakṛtiḥ", "nature"], ["त्वाम्", "tvām", "you"],
        ["नियोक्ष्यति", "niyokṣyati", "will compel"]]
},
60: {"s": [],
     0: [["स्वभावजेन", "svabhāvajena", "born of your own nature"],
         ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
     1: [["निबद्धः", "nibaddhaḥ", "bound"],
         ["स्वेन", "svena", "by your own"],
         ["कर्मणा", "karmaṇā", "action"]],
     2: [["कर्तुम्", "kartum", "to do"],
         ["न", "na", "not"],
         ["इच्छसि", "icchasi", "you wish"],
         ["यत्", "yat", "what"]],
     3: [["मोहात्", "mohāt", "from delusion"],
         ["करिष्यसि", "kariṣyasi", "you will do"],
         ["अवशः", "avaśaḥ", "helpless"],
         ["अपि", "api", "even"],
         ["तत्", "tat", "that"]]},

61: {"s": [],
     0: [["ईश्वरः", "īśvaraḥ", "the Lord"],
         ["सर्वभूतानाम्", "sarvabhūtānām", "of all beings"]],
     1: [["हृद्देशे", "hṛddeśe", "in the heart"],
         ["अर्जुन", "arjuna", "O Arjuna"],
         ["तिष्ठति", "tiṣṭhati", "dwells"]],
     2: [["भ्रामयन्", "bhrāmayan", "causing to revolve"],
         ["सर्वभूतानि", "sarvabhūtāni", "all beings"]],
     3: [["यन्त्रारूढानि", "yantrārūḍhāni", "mounted on a machine"],
         ["मायया", "māyayā", "by his power"]]},

62: {"s": [],
     0: [["तम्", "tam", "him"],
         ["एव", "eva", "alone"],
         ["शरणम्", "śaraṇam", "refuge"],
         ["गच्छ", "gaccha", "go"]],
     1: [["सर्वभावेन", "sarvabhāvena", "with all your being"],
         ["भारत", "bhārata", "O Bhārata"]],
     2: [["तत्प्रसादात्", "tatprasādāt", "by his grace"],
         ["पराम्", "parām", "supreme"],
         ["शान्तिम्", "śāntim", "peace"]],
     3: [["स्थानम्", "sthānam", "the abode"],
         ["प्राप्स्यसि", "prāpsyasi", "you will attain"],
         ["शाश्वतम्", "śāśvatam", "eternal"]]},

63: {"s": [],
     0: [["इति", "iti", "thus"],
         ["ते", "te", "to you"],
         ["ज्ञानम्", "jñānam", "knowledge"],
         ["आख्यातम्", "ākhyātam", "declared"]],
     1: [["गुह्यात्", "guhyāt", "than the secret"],
         ["गुह्यतरम्", "guhyataram", "more secret"],
         ["मया", "mayā", "by me"]],
     2: [["विमृश्य", "vimṛśya", "having reflected on"],
         ["एतत्", "etat", "this"],
         ["अशेषेण", "aśeṣeṇa", "fully"]],
     3: [["यथा", "yathā", "as"],
         ["इच्छसि", "icchasi", "you wish"],
         ["तथा", "tathā", "so"],
         ["कुरु", "kuru", "do"]]},

64: {"s": [],
     0: [["सर्वगुह्यतमम्", "sarvaguhyatamam", "the most secret of all"],
         ["भूयः", "bhūyaḥ", "again"]],
     1: [["शृणु", "śṛṇu", "hear"],
         ["मे", "me", "my"],
         ["परमम्", "paramam", "supreme"],
         ["वचः", "vacaḥ", "word"]],
     2: [["इष्टः", "iṣṭaḥ", "dear"],
         ["असि", "asi", "you are"],
         ["मे", "me", "to me"],
         ["दृढम्", "dṛḍham", "deeply"],
         ["इति", "iti", "thus"]],
     3: [["ततः", "tataḥ", "therefore"],
         ["वक्ष्यामि", "vakṣyāmi", "I will speak"],
         ["ते", "te", "for your"],
         ["हितम्", "hitam", "good"]]},

65: {"s": [],
     0: [["मन्मनाः", "manmanāḥ", "fixing the mind on me"],
         ["भव", "bhava", "be"],
         ["मद्भक्तः", "madbhaktaḥ", "my devotee"]],
     1: [["मद्याजी", "madyājī", "offering to me"],
         ["माम्", "mām", "me"],
         ["नमस्कुरु", "namaskuru", "bow to"]],
     2: [["माम्", "mām", "to me"],
         ["एव", "eva", "surely"],
         ["एष्यसि", "eṣyasi", "you will come"],
         ["सत्यम्", "satyam", "truly"],
         ["ते", "te", "to you"]],
     3: [["प्रतिजाने", "pratijāne", "I promise"],
         ["प्रियः", "priyaḥ", "dear"],
         ["असि", "asi", "you are"],
         ["मे", "me", "to me"]]},

66: {"s": [],
     0: [["सर्वधर्मान्", "sarvadharmān", "all dharmas"],
         ["परित्यज्य", "parityajya", "having abandoned"]],
     1: [["माम्", "mām", "me"],
         ["एकम्", "ekam", "alone"],
         ["शरणम्", "śaraṇam", "refuge"],
         ["व्रज", "vraja", "go"]],
     2: [["अहम्", "aham", "I"],
         ["त्वा", "tvā", "you"],
         ["सर्वपापेभ्यः", "sarvapāpebhyaḥ", "from all sins"]],
     3: [["मोक्षयिष्यामि", "mokṣayiṣyāmi", "will free"],
         ["मा", "mā", "do not"],
         ["शुचः", "śucaḥ", "grieve"]]},

67: {"s": [],
     0: [["इदम्", "idam", "this"],
         ["ते", "te", "by you"],
         ["न", "na", "not"],
         ["अतपस्काय", "atapaskāya", "to one without austerity"]],
     1: [["न", "na", "nor"],
         ["अभक्ताय", "abhaktāya", "to the faithless"],
         ["कदाचन", "kadācana", "ever"]],
     2: [["न", "na", "nor"],
         ["च", "ca", "and"],
         ["अशुश्रूषवे", "aśuśrūṣave", "to one who does not serve"],
         ["वाच्यम्", "vācyam", "is to be spoken"]],
     3: [["न", "na", "nor"],
         ["च", "ca", "and"],
         ["माम्", "mām", "me"],
         ["यः", "yaḥ", "who"],
         ["अभ्यसूयति", "abhyasūyati", "reviles"]]},

68: {"s": [],
     0: [["यः", "yaḥ", "who"],
         ["इमम्", "imam", "this"],
         ["परमम्", "paramam", "supreme"],
         ["गुह्यम्", "guhyam", "secret"]],
     1: [["मद्भक्तेषु", "madbhakteṣu", "among my devotees"],
         ["अभिधास्यति", "abhidhāsyati", "will teach"]],
     2: [["भक्तिम्", "bhaktim", "devotion"],
         ["मयि", "mayi", "to me"],
         ["पराम्", "parām", "supreme"],
         ["कृत्वा", "kṛtvā", "having given"]],
     3: [["माम्", "mām", "me"],
         ["एव", "eva", "surely"],
         ["एष्यति", "eṣyati", "he will reach"],
         ["असंशयः", "asaṁśayaḥ", "without doubt"]]},

69: {"s": [],
     0: [["न", "na", "not"],
         ["च", "ca", "and"],
         ["तस्मात्", "tasmāt", "than him"],
         ["मनुष्येषु", "manuṣyeṣu", "among men"]],
     1: [["कश्चित्", "kaścit", "anyone"],
         ["मे", "me", "to me"],
         ["प्रियकृत्तमः", "priyakṛttamaḥ", "doing greater service"]],
     2: [["भविता", "bhavitā", "will be"],
         ["न", "na", "nor"],
         ["च", "ca", "and"],
         ["मे", "me", "to me"],
         ["तस्मात्", "tasmāt", "than him"]],
     3: [["अन्यः", "anyaḥ", "another"],
         ["प्रियतरः", "priyataraḥ", "dearer"],
         ["भुवि", "bhuvi", "on earth"]]},

70: {"s": [],
     0: [["अध्येष्यते", "adhyeṣyate", "will study"],
         ["च", "ca", "and"],
         ["यः", "yaḥ", "who"],
         ["इमम्", "imam", "this"]],
     1: [["धर्म्यम्", "dharmyam", "sacred"],
         ["संवादम्", "saṁvādam", "dialogue"],
         ["आवयोः", "āvayoḥ", "of us two"]],
     2: [["ज्ञानयज्ञेन", "jñānayajñena", "with the sacrifice of knowledge"],
         ["तेन", "tena", "by him"],
         ["अहम्", "aham", "I"]],
     3: [["इष्टः", "iṣṭaḥ", "worshipped"],
         ["स्याम्", "syām", "may be"],
         ["इति", "iti", "thus"],
         ["मे", "me", "my"],
         ["मतिः", "matiḥ", "opinion"]]},

71: {"s": [],
     0: [["श्रद्धावान्", "śraddhāvān", "with faith"],
         ["अनसूयः", "anasūyaḥ", "without envy"],
         ["च", "ca", "and"]],
     1: [["शृणुयात्", "śṛṇuyāt", "should hear"],
         ["अपि", "api", "even"],
         ["यः", "yaḥ", "who"],
         ["नरः", "naraḥ", "a man"]],
     2: [["सः", "saḥ", "he"],
         ["अपि", "api", "also"],
         ["मुक्तः", "muktaḥ", "freed"],
         ["शुभान्", "śubhān", "the auspicious"],
         ["लोकान्", "lokān", "worlds"]],
     3: [["प्राप्नुयात्", "prāpnuyāt", "would attain"],
         ["पुण्यकर्मणाम्", "puṇyakarmaṇām", "of the virtuous"]]},

72: {"s": [],
     0: [["कच्चित्", "kaccit", "whether"],
         ["एतत्", "etat", "this"],
         ["श्रुतम्", "śrutam", "heard"],
         ["पार्थ", "pārtha", "O Pārtha"]],
     1: [["त्वया", "tvayā", "by you"],
         ["एकाग्रेण", "ekāgreṇa", "with one-pointed"],
         ["चेतसा", "cetasā", "mind"]],
     2: [["कच्चित्", "kaccit", "whether"],
         ["अज्ञानसंमोहः", "ajñānasaṁmohaḥ", "the delusion of ignorance"]],
     3: [["प्रणष्टः", "praṇaṣṭaḥ", "destroyed"],
         ["ते", "te", "your"],
         ["धनंजय", "dhanaṁjaya", "O Dhanañjaya"]]},

73: {"s": [["अर्जुनः", "arjunaḥ", "Arjuna"], ["उवाच", "uvāca", "said"]],
     0: [["नष्टः", "naṣṭaḥ", "destroyed"],
         ["मोहः", "mohaḥ", "delusion"],
         ["स्मृतिः", "smṛtiḥ", "memory"],
         ["लब्धा", "labdhā", "gained"]],
     1: [["त्वत्प्रसादात्", "tvatprasādāt", "by your grace"],
         ["मया", "mayā", "by me"],
         ["अच्युत", "acyuta", "O Acyuta"]],
     2: [["स्थितः", "sthitaḥ", "standing"],
         ["अस्मि", "asmi", "I am"],
         ["गतसंदेहः", "gatasaṁdehaḥ", "my doubt gone"]],
     3: [["करिष्ये", "kariṣye", "I will do"],
         ["वचनम्", "vacanam", "your word"],
         ["तव", "tava", "your"]]},

74: {"s": [["सञ्जयः", "sañjayaḥ", "Sañjaya"], ["उवाच", "uvāca", "said"]],
     0: [["इति", "iti", "thus"],
         ["अहम्", "aham", "I"],
         ["वासुदेवस्य", "vāsudevasya", "of Vāsudeva"]],
     1: [["पार्थस्य", "pārthasya", "of Pārtha"],
         ["च", "ca", "and"],
         ["महात्मनः", "mahātmanaḥ", "the great-souled"]],
     2: [["संवादम्", "saṁvādam", "the dialogue"],
         ["इमम्", "imam", "this"],
         ["अश्रौषम्", "aśrauṣam", "I heard"]],
     3: [["अद्भुतम्", "adbhutam", "wondrous"],
         ["रोमहर्षणम्", "romaharṣaṇam", "thrilling"]]},

75: {"s": [],
     0: [["व्यासप्रसादात्", "vyāsaprasādāt", "by the grace of Vyāsa"],
         ["श्रुतवान्", "śrutavān", "I heard"]],
     1: [["इमम्", "imam", "this"],
         ["गुह्यतमम्", "guhyatamam", "most secret"],
         ["परम्", "param", "supreme"]],
     2: [["योगम्", "yogam", "yoga"],
         ["योगेश्वरात्", "yogeśvarāt", "from the Lord of yoga"],
         ["कृष्णात्", "kṛṣṇāt", "from Kṛṣṇa"]],
     3: [["साक्षात्", "sākṣāt", "directly"],
         ["कथयतः", "kathayataḥ", "speaking"],
         ["स्वयम्", "svayam", "himself"]]},

76: {"s": [],
     0: [["राजन्", "rājan", "O king"],
         ["संस्मृत्य", "saṁsmṛtya", "remembering"],
         ["संस्मृत्य", "saṁsmṛtya", "again and again"]],
     1: [["संवादम्", "saṁvādam", "the dialogue"],
         ["इमम्", "imam", "this"],
         ["अद्भुतम्", "adbhutam", "wondrous"]],
     2: [["केशवार्जुनयोः", "keśavārjunayoḥ", "of Keśava and Arjuna"],
         ["पुण्यम्", "puṇyam", "holy"]],
     3: [["हृष्यामि", "hṛṣyāmi", "I rejoice"],
         ["च", "ca", "and"],
         ["मुहुर्मुहुः", "muhurmuhuḥ", "again and again"]]},

77: {"s": [],
     0: [["तत्", "tat", "that"],
         ["च", "ca", "and"],
         ["संस्मृत्य", "saṁsmṛtya", "remembering"],
         ["संस्मृत्य", "saṁsmṛtya", "again and again"]],
     1: [["रूपम्", "rūpam", "the form"],
         ["अत्यद्भुतम्", "atyadbhutam", "most wondrous"],
         ["हरेः", "hareḥ", "of Hari"]],
     2: [["विस्मयः", "vismayaḥ", "wonder"],
         ["मे", "me", "my"],
         ["महान्", "mahān", "great"],
         ["राजन्", "rājan", "O king"]],
     3: [["हृष्यामि", "hṛṣyāmi", "I rejoice"],
         ["च", "ca", "and"],
         ["पुनः", "punaḥ", "again"],
         ["पुनः", "punaḥ", "and again"]]},

78: {"s": [],
     0: [["यत्र", "yatra", "wherever"],
         ["योगेश्वरः", "yogeśvaraḥ", "the Lord of yoga"],
         ["कृष्णः", "kṛṣṇaḥ", "Kṛṣṇa"]],
     1: [["यत्र", "yatra", "wherever"],
         ["पार्थः", "pārthaḥ", "Pārtha"],
         ["धनुर्धरः", "dhanurdharaḥ", "the archer"]],
     2: [["तत्र", "tatra", "there"],
         ["श्रीः", "śrīḥ", "prosperity"],
         ["विजयः", "vijayaḥ", "victory"],
         ["भूतिः", "bhūtiḥ", "glory"]],
     3: [["ध्रुवा", "dhruvā", "constant"],
         ["नीतिः", "nītiḥ", "wisdom"],
         ["मतिः", "matiḥ", "judgment"],
         ["मम", "mama", "my"]]},
}
