# -*- coding: utf-8 -*-
"""padachheda_ch7.py — per-pāda pada-chheda (word splits) for all 30 verses of Gita Chapter 7.

Structure: verse_number -> {
    "s": [[deva_word, iast, meaning], ...]   # speaker line words (if any)
    0..3: [[deva_word, iast, meaning], ...]  # the four pādas
}
Readings aligned to the Śaṅkara-bhāṣya edition."""

GITA_CH7_WORDS = {
1: {"s": [["श्रीभगवान्", "śrībhagavān", "the Blessed Lord"], ["उवाच", "uvāca", "said"]],
    0: [["मयि", "mayi", "in me"],
        ["आसक्त", "āsakta", "attached"],
        ["मनाः", "manāḥ", "whose mind"],
        ["पार्थ", "pārtha", "O Pārtha"]],
    1: [["योगम्", "yogam", "yoga"],
        ["युञ्जन्", "yuñjan", "practising"],
        ["मदाश्रयः", "madāśrayaḥ", "taking refuge in me"]],
    2: [["असंशयम्", "asaṁśayam", "without doubt"],
        ["समग्रम्", "samagram", "completely, in full"],
        ["माम्", "mām", "me"]],
    3: [["यथा", "yathā", "how"],
        ["ज्ञास्यसि", "jñāsyasi", "you will know"],
        ["तत्", "tat", "that"],
        ["शृणु", "śṛṇu", "hear"]]},

2: {"s": [],
    0: [
    ["ज्ञानम्", "jñānam", "knowledge"], ["ते", "te", "to you"], ["अहम्", "aham", "I"],
        ["सविज्ञानम्", "savijñānam", "with realization"]],
    1: [
    ["इदम्", "idam", "this"], ["वक्ष्यामि", "vakṣyāmi", "shall declare"],
        ["अशेषतः", "aśeṣataḥ", "without remainder"]],
    2: [
    ["यत्", "yat", "which"], ["ज्ञात्वा", "jñātvā", "having known"], ["न", "na", "not"],
        ["इह", "iha", "here"], ["भूयः", "bhūyaḥ", "further"],
        ["अन्यत्", "anyat", "anything else"]],
    3: [
    ["ज्ञातव्यम्", "jñātavyam", "to be known"], ["अवशिष्यते", "avaśiṣyate", "remains"]]
},
3: {"s": [],
    0: [["मनुष्याणाम्", "manuṣyāṇām", "among men"],
        ["सहस्रेषु", "sahasreṣu", "among thousands"]],
    1: [["कश्चित्", "kaścit", "one, someone"],
        ["यतति", "yatati", "strives"],
        ["सिद्धये", "siddhaye", "for perfection"]],
    2: [["यतताम्", "yatatām", "of those who strive"],
        ["अपि", "api", "even"],
        ["सिद्धानाम्", "siddhānām", "of the perfected"]],
    3: [["कश्चित्", "kaścit", "one"],
        ["माम्", "mām", "me"],
        ["वेत्ति", "vetti", "knows"],
        ["तत्त्वतः", "tattvataḥ", "in truth"]]},

4: {"s": [],
    0: [["भूमिः", "bhūmiḥ", "earth"],
        ["आपः", "āpaḥ", "water"],
        ["अनलः", "analaḥ", "fire"],
        ["वायुः", "vāyuḥ", "air"]],
    1: [["खम्", "kham", "ether, space"],
        ["मनः", "manaḥ", "mind"],
        ["बुद्धिः", "buddhiḥ", "intellect"],
        ["एव", "eva", "indeed"],
        ["च", "ca", "and"]],
    2: [["अहङ्कारः", "ahaṅkāraḥ", "egoism"],
        ["इति", "iti", "thus"],
        ["इयम्", "iyam", "this"],
        ["मे", "me", "my"]],
    3: [["भिन्ना", "bhinnā", "divided"],
        ["प्रकृतिः", "prakṛtiḥ", "nature"],
        ["अष्टधा", "aṣṭadhā", "eightfold"]]},

5: {"s": [],
    0: [["अपरा", "aparā", "the lower"],
        ["इयम्", "iyam", "this"],
        ["इतः", "itaḥ", "than this"],
        ["तु", "tu", "but"],
        ["अन्याम्", "anyām", "another"]],
    1: [["प्रकृतिम्", "prakṛtim", "nature"],
        ["विद्धि", "viddhi", "know"],
        ["मे", "me", "my"],
        ["पराम्", "parām", "higher"]],
    2: [["जीवभूताम्", "jīvabhūtām", "the life-element"],
        ["महाबाहो", "mahābāho", "O mighty-armed one"]],
    3: [["यया", "yayā", "by which"],
        ["इदम्", "idam", "this"],
        ["धार्यते", "dhāryate", "is upheld"],
        ["जगत्", "jagat", "world"]]},

6: {"s": [],
    0: [["एतत्", "etat", "these"],
        ["योनीनि", "yonīni", "the wombs"],
        ["भूतानि", "bhūtāni", "of beings"]],
    1: [["सर्वाणि", "sarvāṇi", "all"],
        ["इति", "iti", "thus"],
        ["उपधारय", "upadhāraya", "know"]],
    2: [["अहम्", "aham", "I"],
        ["कृत्स्नस्य", "kṛtsnasya", "of the whole"],
        ["जगतः", "jagataḥ", "world"]],
    3: [["प्रभवः", "prabhavaḥ", "the origin"],
        ["प्रलयः", "pralayaḥ", "the dissolution"],
        ["तथा", "tathā", "also"]]},

7: {"s": [],
    0: [["मत्तः", "mattaḥ", "than me"],
        ["परतरम्", "parataram", "higher"],
        ["न", "na", "not"],
        ["अन्यत्", "anyat", "anything else"]],
    1: [["किञ्चित्", "kiñcit", "anything whatever"],
        ["अस्ति", "asti", "there is"],
        ["धनञ्जय", "dhanañjaya", "O Dhanañjaya"]],
    2: [["मयि", "mayi", "on me"],
        ["सर्वम्", "sarvam", "all this"],
        ["इदम्", "idam", "this"],
        ["प्रोतम्", "protam", "strung"]],
    3: [["सूत्रे", "sūtre", "on a thread"],
        ["मणिगणाः", "maṇigaṇāḥ", "a row of gems"],
        ["इव", "iva", "like"]]},

8: {"s": [],
    0: [["रसः", "rasaḥ", "the taste"],
        ["अहम्", "aham", "I"],
        ["अप्सु", "apsu", "in waters"],
        ["कौन्तेय", "kaunteya", "O son of Kuntī"]],
    1: [["प्रभा", "prabhā", "the radiance"],
        ["अस्मि", "asmi", "I am"],
        ["शशिसूर्ययोः", "śaśisūryayoḥ", "of the moon and the sun"]],
    2: [["प्रणवः", "praṇavaḥ", "the sacred syllable Om"],
        ["सर्ववेदेषु", "sarvavedeṣu", "in all the Vedas"]],
    3: [["शब्दः", "śabdaḥ", "the sound"],
        ["खे", "khe", "in ether"],
        ["पौरुषम्", "pauruṣam", "the manliness"],
        ["नृषु", "nṛṣu", "in men"]]},

9: {"s": [],
    0: [["पुण्यः", "puṇyaḥ", "the pure"],
        ["गन्धः", "gandhaḥ", "fragrance"],
        ["पृथिव्याम्", "pṛthivyām", "of the earth"],
        ["च", "ca", "and"]],
    1: [["तेजः", "tejaḥ", "the heat, radiance"],
        ["च", "ca", "and"],
        ["अस्मि", "asmi", "I am"],
        ["विभावसौ", "vibhāvasau", "in fire"]],
    2: [["जीवनम्", "jīvanam", "the life"],
        ["सर्वभूतेषु", "sarvabhūteṣu", "in all beings"]],
    3: [["तपः", "tapaḥ", "the austerity"],
        ["च", "ca", "and"],
        ["अस्मि", "asmi", "I am"],
        ["तपस्विषु", "tapasviṣu", "in the ascetics"]]},

10: {"s": [],
     0: [["बीजम्", "bījam", "the seed"],
         ["माम्", "mām", "me"],
         ["सर्वभूतानाम्", "sarvabhūtānām", "of all beings"]],
     1: [["विद्धि", "viddhi", "know"],
         ["पार्थ", "pārtha", "O Pārtha"],
         ["सनातनम्", "sanātanam", "eternal"]],
     2: [["बुद्धिः", "buddhiḥ", "the intelligence"],
         ["बुद्धिमताम्", "buddhimatām", "of the intelligent"],
         ["अस्मि", "asmi", "I am"]],
     3: [["तेजः", "tejaḥ", "the splendour"],
         ["तेजस्विनाम्", "tejasvinām", "of the splendid"],
         ["अहम्", "aham", "I"]]},

11: {"s": [],
     0: [["बलम्", "balam", "the strength"],
         ["बलवताम्", "balavatām", "of the strong"],
         ["च", "ca", "and"],
         ["अहम्", "aham", "I"]],
     1: [["कामरागविवर्जितम्", "kāmarāgavivarjitam", "free from desire and attachment"]],
     2: [["धर्माविरुद्धः", "dharmāviruddhaḥ", "not opposed to dharma"],
         ["भूतेषु", "bhūteṣu", "in beings"]],
     3: [["कामः", "kāmaḥ", "desire"],
         ["अस्मि", "asmi", "I am"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]]},

12: {"s": [],
     0: [["ये", "ye", "which"],
         ["च", "ca", "and"],
         ["एव", "eva", "indeed"],
         ["सात्त्विकाः", "sāttvikāḥ", "sāttvic"],
         ["भावाः", "bhāvāḥ", "states"]],
     1: [["राजसाः", "rājasāḥ", "rājasic"],
         ["तामसाः", "tāmasāḥ", "tāmasic"],
         ["च", "ca", "and"],
         ["ये", "ye", "which"]],
     2: [["मत्तः", "mattaḥ", "from me"],
         ["एव", "eva", "alone"],
         ["इति", "iti", "thus"],
         ["तान्", "tān", "them"],
         ["विद्धि", "viddhi", "know"]],
     3: [["न", "na", "not"],
         ["तु", "tu", "but"],
         ["अहम्", "aham", "I"],
         ["तेषु", "teṣu", "in them"],
         ["ते", "te", "they"],
         ["मयि", "mayi", "in me"]]},

13: {"s": [],
     0: [["त्रिभिः", "tribhiḥ", "by the three"],
         ["गुणमयैः", "guṇamayaiḥ", "made of the guṇas"],
         ["भावैः", "bhāvaiḥ", "by the states"]],
     1: [["एभिः", "ebhiḥ", "by these"],
         ["सर्वम्", "sarvam", "this entire"],
         ["इदम्", "idam", "this"],
         ["जगत्", "jagat", "world"]],
     2: [["मोहितम्", "mohitam", "deluded"],
         ["न", "na", "not"],
         ["अभिजानाति", "abhijānāti", "knows"]],
     3: [["माम्", "mām", "me"],
         ["एभ्यः", "ebhyaḥ", "beyond them"],
         ["परम्", "param", "beyond"],
         ["अव्ययम्", "avyayam", "imperishable"]]},

14: {"s": [],
     0: [["दैवी", "daivī", "divine"],
         ["हि", "hi", "indeed"],
         ["एषा", "eṣā", "this"],
         ["गुणमयी", "guṇamayī", "made of the guṇas"]],
     1: [["मम", "mama", "my"],
         ["माया", "māyā", "māyā"],
         ["दुरत्यया", "duratyayā", "hard to cross"]],
     2: [["माम्", "mām", "me"],
         ["एव", "eva", "alone"],
         ["ये", "ye", "who"],
         ["प्रपद्यन्ते", "prapadyante", "take refuge in"]],
     3: [["मायाम्", "māyām", "this māyā"],
         ["एताम्", "etām", "this"],
         ["तरन्ति", "taranti", "they cross"],
         ["ते", "te", "they"]]},

15: {"s": [],
     0: [["न", "na", "not"],
         ["माम्", "mām", "me"],
         ["दुष्कृतिनः", "duṣkṛtinaḥ", "the wrong-doers"],
         ["मूढाः", "mūḍhāḥ", "the deluded"]],
     1: [["प्रपद्यन्ते", "prapadyante", "take refuge in"],
         ["नराधमाः", "narādhamāḥ", "the lowest of men"]],
     2: [["मायया", "māyayā", "by māyā"],
         ["अपहृतज्ञानाः", "apahṛtajñānāḥ", "robbed of knowledge"]],
     3: [["आसुरम्", "āsuram", "demoniac"],
         ["भावम्", "bhāvam", "nature"],
         ["आश्रिताः", "āśritāḥ", "clinging to"]]},

16: {"s": [],
     0: [["चतुर्विधाः", "caturvidhāḥ", "four kinds of"],
         ["भजन्ते", "bhajante", "worship"],
         ["माम्", "mām", "me"]],
     1: [["जनाः", "janāḥ", "people"],
         ["सुकृतिनः", "sukṛtinaḥ", "of good deeds"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["आर्तः", "ārtaḥ", "the afflicted"],
         ["जिज्ञासुः", "jijñāsuḥ", "the seeker of knowledge"],
         ["अर्थार्थी", "arthārthī", "the seeker of wealth"]],
     3: [["ज्ञानी", "jñānī", "the man of wisdom"],
         ["च", "ca", "and"],
         ["भरतर्षभ", "bharatarṣabha", "O bull of the Bhāratas"]]},

17: {"s": [],
     0: [["तेषाम्", "teṣām", "of them"],
         ["ज्ञानी", "jñānī", "the man of wisdom"],
         ["नित्ययुक्तः", "nityayuktaḥ", "ever yoked"]],
     1: [["एकभक्तिः", "ekabhaktiḥ", "of single devotion"],
         ["विशिष्यते", "viśiṣyate", "is the best"]],
     2: [["प्रियः", "priyaḥ", "dear"],
         ["हि", "hi", "indeed"],
         ["ज्ञानिनः", "jñāninaḥ", "to the wise"],
         ["अत्यर्थम्", "atyartham", "exceedingly"]],
     3: [["अहम्", "aham", "I"],
         ["सः", "saḥ", "he"],
         ["च", "ca", "and"],
         ["मम", "mama", "to me"],
         ["प्रियः", "priyaḥ", "dear"]]},

18: {"s": [],
     0: [["उदाराः", "udārāḥ", "noble"],
         ["सर्वे", "sarve", "all"],
         ["एव", "eva", "indeed"],
         ["एते", "ete", "these"]],
     1: [["ज्ञानी", "jñānī", "the wise one"],
         ["तु", "tu", "but"],
         ["आत्मा", "ātmā", "my very self"],
         ["एव", "eva", "indeed"],
         ["मे", "me", "in my"],
         ["मतम्", "matam", "opinion"]],
     2: [["आस्थितः", "āsthitaḥ", "established"],
         ["सः", "saḥ", "he"],
         ["हि", "hi", "indeed"],
         ["युक्तात्मा", "yuktātmā", "self-possessed"]],
     3: [["माम्", "mām", "me"],
         ["एव", "eva", "alone"],
         ["अनुत्तमाम्", "anuttamām", "the supreme"],
         ["गतिम्", "gatim", "goal"]]},

19: {"s": [],
     0: [["बहूनाम्", "bahūnām", "of many"],
         ["जन्मनाम्", "janmanām", "births"],
         ["अन्ते", "ante", "at the end"]],
     1: [["ज्ञानवान्", "jñānavān", "the man of wisdom"],
         ["माम्", "mām", "me"],
         ["प्रपद्यते", "prapadyate", "takes refuge in"]],
     2: [["वासुदेवः", "vāsudevaḥ", "Vāsudeva"],
         ["सर्वम्", "sarvam", "is all"],
         ["इति", "iti", "thus"]],
     3: [["सः", "saḥ", "that"],
         ["महात्मा", "mahātmā", "great soul"],
         ["सुदुर्लभः", "sudurlabhaḥ", "very rare"]]},

20: {"s": [],
     0: [["कामैः", "kāmaiḥ", "by desires"],
         ["तैः", "taiḥ", "those"],
         ["तैः", "taiḥ", "those"],
         ["हृतज्ञानाः", "hṛtajñānāḥ", "robbed of knowledge"]],
     1: [["प्रपद्यन्ते", "prapadyante", "they resort to"],
         ["अन्यदेवताः", "anyadevatāḥ", "other deities"]],
     2: [["तम्", "tam", "this"],
         ["तम्", "tam", "this"],
         ["नियमम्", "niyamam", "rite"],
         ["आस्थाय", "āsthāya", "following"]],
     3: [["प्रकृत्या", "prakṛtyā", "by nature"],
         ["नियताः", "niyatāḥ", "constrained"],
         ["स्वया", "svayā", "their own"]]},

21: {"s": [],
    0: [
    ["यः", "yaḥ", "whatever"], ["यः", "yaḥ", "whatever"], ["याम्", "yām", "which"],
        ["याम्", "yām", "which"], ["तनुम्", "tanum", "form"],
        ["भक्तः", "bhaktaḥ", "a devotee"]],
    1: [
    ["श्रद्धया", "śraddhayā", "with faith"], ["अर्चितुम्", "arcitum", "to worship"],
        ["इच्छति", "icchati", "desires"]],
    2: [
    ["तस्य", "tasya", "of him"], ["तस्य", "tasya", "of him"],
        ["अचलाम्", "acalām", "unwavering"], ["श्रद्धाम्", "śraddhām", "faith"]],
    3: [
    ["ताम्", "tām", "that"], ["एव", "eva", "very"], ["विदधामि", "vidadhāmi", "I make"],
        ["अहम्", "aham", "I"]]
},
22: {"s": [],
     0: [["सः", "saḥ", "he"],
         ["तया", "tayā", "with that"],
         ["श्रद्धया", "śraddhayā", "faith"],
         ["युक्तः", "yuktaḥ", "endowed"]],
     1: [["तस्य", "tasya", "of that (deity)"],
         ["आराधनम्", "ārādhanam", "the worship"],
         ["ईहते", "īhate", "he seeks"]],
     2: [["लभते", "labhate", "he obtains"],
         ["च", "ca", "and"],
         ["ततः", "tataḥ", "from it"],
         ["कामान्", "kāmān", "his desires"]],
     3: [["मया", "mayā", "by me"],
         ["एव", "eva", "indeed"],
         ["विहितान्", "vihitān", "ordained"],
         ["हि", "hi", "verily"],
         ["तान्", "tān", "those"]]},

23: {"s": [],
     0: [["अन्तवत्", "antavat", "finite"],
         ["तु", "tu", "but"],
         ["फलम्", "phalam", "the fruit"],
         ["तेषाम्", "teṣām", "of those"]],
     1: [["तत्", "tat", "that"],
         ["भवति", "bhavati", "is"],
         ["अल्पमेधसाम्", "alpamedhasām", "of the small-minded"]],
     2: [["देवान्", "devān", "to the gods"],
         ["देवयजः", "devayajaḥ", "the worshippers of the gods"],
         ["यान्ति", "yānti", "go"]],
     3: [["मद्भक्ताः", "madbhaktāḥ", "my devotees"],
         ["यान्ति", "yānti", "go"],
         ["माम्", "mām", "to me"],
         ["अपि", "api", "indeed"]]},

24: {"s": [],
     0: [["अव्यक्तम्", "avyaktam", "the unmanifest"],
         ["व्यक्तिम्", "vyaktim", "manifestation"],
         ["आपन्नम्", "āpannam", "having attained"]],
     1: [["मन्यन्ते", "manyante", "they think"],
         ["माम्", "mām", "me"],
         ["अबुद्धयः", "abuddhayaḥ", "the unintelligent"]],
     2: [["परम्", "param", "the higher"],
         ["भावम्", "bhāvam", "nature"],
         ["अजानन्तः", "ajānantaḥ", "not knowing"]],
     3: [["मम", "mama", "my"],
         ["अव्ययम्", "avyayam", "imperishable"],
         ["अनुत्तमम्", "anuttamam", "unsurpassed"]]},

25: {"s": [],
     0: [["न", "na", "not"],
         ["अहम्", "aham", "I"],
         ["प्रकाशः", "prakāśaḥ", "manifest"],
         ["सर्वस्य", "sarvasya", "to all"]],
     1: [["योगमाया", "yogamāyā", "by yoga-māyā"],
         ["समावृतः", "samāvṛtaḥ", "enveloped"]],
     2: [["मूढः", "mūḍhaḥ", "deluded"],
         ["अयम्", "ayam", "this"],
         ["न", "na", "not"],
         ["अभिजानाति", "abhijānāti", "knows"]],
     3: [["लोकः", "lokaḥ", "the world"],
         ["माम्", "mām", "me"],
         ["अजम्", "ajam", "the unborn"],
         ["अव्ययम्", "avyayam", "the imperishable"]]},

26: {"s": [],
     0: [["वेद", "veda", "I know"],
         ["अहम्", "aham", "I"],
         ["समतीतानि", "samatītāni", "the past"]],
     1: [["वर्तमानानि", "vartamānāni", "the present"],
         ["च", "ca", "and"],
         ["अर्जुन", "arjuna", "O Arjuna"]],
     2: [["भविष्याणि", "bhaviṣyāṇi", "the future"],
         ["च", "ca", "and"],
         ["भूतानि", "bhūtāni", "beings"]],
     3: [["माम्", "mām", "me"],
         ["तु", "tu", "but"],
         ["वेद", "veda", "knows"],
         ["न", "na", "no"],
         ["कश्चन", "kaścana", "one"]]},

27: {"s": [],
     0: [["इच्छा", "icchā", "desire"],
         ["द्वेष", "dveṣa", "and aversion"],
         ["समुत्थेन", "samutthena", "born of"]],
     1: [["द्वन्द्वमोहेन", "dvandvamohena", "by the delusion of the pairs"],
         ["भारत", "bhārata", "O Bhārata"]],
     2: [["सर्वभूतानि", "sarvabhūtāni", "all beings"],
         ["सम्मोहम्", "sammoham", "to delusion"]],
     3: [["सर्गे", "sarge", "at birth"],
         ["यान्ति", "yānti", "go"],
         ["परन्तप", "parantapa", "O scorcher of foes"]]},

28: {"s": [],
     0: [["येषाम्", "yeṣām", "of those"],
         ["तु", "tu", "but"],
         ["अन्तगतम्", "antagatam", "come to an end"],
         ["पापम्", "pāpam", "sin"]],
     1: [["जनानाम्", "janānām", "of men"],
         ["पुण्यकर्मणाम्", "puṇyakarmaṇām", "of good deeds"]],
     2: [["ते", "te", "they"],
         ["द्वन्द्वमोहनिर्मुक्ताः", "dvandvamohanirmuktāḥ", "freed from the delusion of the pairs"]],
     3: [["भजन्ते", "bhajante", "worship"],
         ["माम्", "mām", "me"],
         ["दृढव्रताः", "dṛḍhavratāḥ", "with firm vows"]]},

29: {"s": [],
     0: [["जरा", "jarā", "old age"],
         ["मरण", "maraṇa", "and death"],
         ["मोक्षाय", "mokṣāya", "for freedom from"]],
     1: [["माम्", "mām", "me"],
         ["आश्रित्य", "āśritya", "taking refuge in"],
         ["यतन्ति", "yatanti", "strive"],
         ["ये", "ye", "those who"]],
     2: [["ते", "te", "they"],
         ["ब्रह्म", "brahma", "Brahman"],
         ["तत्", "tat", "that"],
         ["विदुः", "viduḥ", "know"],
         ["कृत्स्नम्", "kṛtsnam", "the entire"]],
     3: [["अध्यात्मम्", "adhyātmam", "the Self"],
         ["कर्म", "karma", "action"],
         ["च", "ca", "and"],
         ["अखिलम्", "akhilam", "all"]]},

30: {"s": [],
    0: [
    ["स", "sa", "along with"], ["अधिभूत", "adhibhūta", "the elements"],
        ["अधिदैवम्", "adhidaivam", "the deities"], ["माम्", "mām", "me"]],
    1: [
    ["स", "sa", "along with"], ["अधियज्ञम्", "adhiyajñam", "the sacrifice"],
        ["च", "ca", "and"], ["ये", "ye", "who"], ["विदुः", "viduḥ", "know"]],
    2: [
    ["प्रयाणकाले", "prayāṇakāle", "at the time of death"], ["अपि", "api", "even"],
        ["च", "ca", "and"], ["माम्", "mām", "me"]],
    3: [
    ["ते", "te", "they"], ["विदुः", "viduḥ", "know"],
        ["युक्तचेतसः", "yuktacetasaḥ", "with minds established"]]
},
}
